### ISSUE TITLE
Request FileAliases​.CopyFiles(IEnumerable<string>, ​DirectoryPath) that supports filepathes with patterns

### ISSUE THREAD

**Issue by robgha01** [cake-build/cake#1005]
I was wondering if we could ether add support for the existing method listed above or make a new method that will take in a list of patterns like the above and process like this method here
http://cakebuild.net/api/cake.common.io/0589fca9/42eb1132

i would like to do it like this
```
var files = new [] {
        $"{buildDir}/bin/*.dll",
        $"{buildDir}/DataServices/*.svc",
        $"{buildDir}/scripts/**",
        $"{buildDir}/*.config",
        $"{buildDir}/*.aspx",
        $"{buildDir}/*.ico",
        $"{buildDir}/*.html"
    };
	
	CopyFiles(files, targetOutput);
```
this is not supported and i must use `CopyFiles("Cake.*", "./publish");` this makes the code more cluttery and would be better if we could pass in a pattern string list like the above.

**Comment by patriksvensson** [comment]
@robgha01 You can solve this by writing it like this:

```csharp
var files = new [] {
        $"{buildDir}/bin/*.dll",
        $"{buildDir}/DataServices/*.svc",
        $"{buildDir}/scripts/**",
        $"{buildDir}/*.config",
        $"{buildDir}/*.aspx",
        $"{buildDir}/*.ico",
        $"{buildDir}/*.html"
    };

foreach(var pattern in files) {
   CopyFiles(files, targetOutput);
}
```

**Comment by robgha01** [comment]
@patriksvensson oh yes i dide not think of that way i think i need to wake up a bit xD thancks mate.

**Comment by patriksvensson** [comment]
@robgha01 Not a problem at all. Happy to help :smile:

**Comment by patriksvensson** [comment]
@robgha01 I'm closing this issue.
