### ISSUE TITLE
DoInDirectory Extension to DSL

### ISSUE THREAD

**Issue by pitermarx** [cake-build/cake#1007]
I have created an extension that I think makes sense to include in the BuiltIn DSL of Cake.

https://github.com/pitermarx/Cake.DoInDirectory
```cs
    DoInDirectory("Some/Sub/Directory", () =>
        Npm.RunScript("test")
    );
```

It changes the current directory for some action and then changes it back

What do you think?

**Comment by devlead** [comment]
@pitermarx  PR  #1009 added ability to set working directory for tools, think that covers most scenarios and has a lower risk for race conditions if we in the future would allow to do tasks in parallel.
But good scenario for an addin and we appreciate the feedback :+1:
