### ISSUE TITLE
Port to .NET Core

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#1015]
#### Agenda

The goal with this port is to maintain the current `NET45` implementation side by side with `netstandard1.6` to ensure that people who has invested in Cake can continue using it. At least until .NET 4.6.2 is widespread enough and also supported on Mono.

#### Supported frameworks

* net45
* netstandard1.6

#### Assemblies ported to .NET Core

- [x] Cake
- [x] Cake.Tests
- [x] Cake.Core
- [x] Cake.Core.Tests
- [x] Cake.Common
- [x] Cake.Common.Tests
- [x] Cake.NuGet
- [x] Cake.NuGet.Tests
- [x] Cake.Testing
- [x] Cake.Testing.Xunit

#### Other work that needs to be done

- [x] PowerShell bootstrapper
- [x] Linux/OSX bootstrapper
- [x] Build script
  - [x] Update version in project.json
  - [x] Restore
  - [x] Build
  - [x] Create NuGet Packages
    - [x] Cake _(net45 assemblies)_
    - [x] Cake.CoreClr _(netcore assemblies)_
    - [x] Cake.Core _(net45 + netstandard1.6)_
    - [x] Cake.Common _(net45 + netstandard1.6)_
    - [x] Cake.Testing _(net45 + netstandard1.6)_
  - [x] Create Chocolatey Package _(net45 assemblies)_
  - [x] Run unit tests
  - [x] Create zip package _(coreclr assemblies)_
  - [x] Create zip package _(net45 assemblies)_
- [x] StyleCop

#### Known issues for .NET Core

- [x] Cross platform script engine (Cake)
- [x] Framework moniker matching (Cake.NuGet)
- [x] Module searching (Cake)
- [x] Debugging
- [x] CakeEnvironment.GetSpecialPath (Cake.Core)
- [x] CakeEnvironment.GetTargetFramework (Cake.Core)

#### CI working

- [x] AppVeyor (Windows)
- [x] Travis (Ubuntu)
- [x] Travis (OS X)
- [x] Bitrise (Ubuntu)
- [x] Bitrise (OS X)
- [x] TeamCity (Windows)

#### Questions

- ~~How do we remove the `StyleCop.Analyzers` dependency from our packages?~~ (solved)

#### Removed in .NET Core port (due to lack of support)

- XmlTransformation (Cake.Common)
- XmlSettingsWriter.DoNotEscapeUriAttributes (Cake.Common)

#### Source

Check out the [coreclr branch](https://github.com/cake-build/cake/tree/coreclr) in this repository.
Going to add a PR from that branch soon.

#### Pull requests

I'm not accepting pull requests at the moment but will as soon as everything compiles as it used to :smile:

**Comment by adamhathcock** [comment]
Any chance this can be reduced to NET461 instead of NET462?

**Comment by patriksvensson** [comment]
We will keep support for NET452 (for non .NET Core and Mono). I just haven't added it yet.
NET462 is just there so we will be able to use the stabile roslyn bits ootb if we want to.

**Comment by adamhathcock** [comment]
do the roslyn bits only support net462?  I just didn't want to have to install a preview of net462 to mess around with this.

**Comment by patriksvensson** [comment]
@adamhathcock No, but we want to keep as close to netstandard1.6 as possible API wise. .NET 4.6.3 is recommended but I haven't found it yet :smile:

**Comment by adamhathcock** [comment]
How about just dropping full framework from the libraries?  The tests can do full framework and .net core?

I'm just tossing around ideas.  I guess I only care about running Cake as a .net core app so it doesn't matter what build machine I use, windows or whatever.

**Comment by patriksvensson** [comment]
@adamhathcock I absolutely understand your view. We have however decided to keep full framework support to continue supporting people who've invested in Cake on the full framework and Mono.

**Comment by adamhathcock** [comment]
No problem.  Just feeling out where you'll land.

I'd want to contribute more to this fork but I'm about to go on vacation for two weeks.  I'm hoping you'll be done by the time I'm back :)

**Comment by patriksvensson** [comment]
**Update:**

The `XmlTransform` alias will not be supported on .NET Core due to lack of support in the framework.

**Comment by patriksvensson** [comment]
Removed .NET 4.6.2 support in the port to keep the porting effort to a minimum. We will however add this later on when the .NET Core port has reached RTM.

**Comment by luisgoncalves** [comment]
I just tried [this build](https://ci.appveyor.com/api/buildjobs/69i5lnu128c4yk0m/artifacts/Cake-bin-coreclr-v0.16.0-PullRequest1038.zip) against [this script](https://github.com/luisgoncalves/aspnetcore-cookietempdata/blob/dev/build.cake) and I got an error on `GetFiles("./src/*/project.json").First()`:

```
error CS1061: 'FilePathCollection' does not contain a definition for 'First' and no extension method 'First' accepting a first argument of type 'FilePathCollection' could be found
```

From the verbose output:

```
Processing build script...
Adding reference to System.Private.CoreLib.ni.dll...
Adding reference to System.Private.Uri.dll...
Adding reference to System.Linq.Expressions.dll...
Adding reference to System.Xml.ReaderWriter.dll...
Adding reference to System.Xml.XDocument.dll...
Adding reference to Cake.Core.dll...
Adding reference to Cake.Common.dll...
Importing namespace Cake.Common...
...
Importing namespace System.Linq...
...
```
