### ISSUE TITLE
Tool should support other exit codes than 0

### ISSUE THREAD

**Issue by Sam13** [cake-build/cake#1023]
Currently a ```CakeException``` is thrown when a tool has other exit code than zero.

Since they are tools around (e.g. RoboCopy) which have different exit codes I suggest to add a list of valid exit codes to the ```ToolSettings``` class.

Or add a custom validation callback (```Func<int, bool>```) to validate the exit code on client side (similar to ```postAction```) of ```Tool.Run()```

**Comment by devlead** [comment]
Fixed by  #1031
