### ISSUE TITLE
Support async callbacks

### ISSUE THREAD

**Issue by ejball** [cake-build/cake#1032]
It would be nice if callbacks (e.g. the action callback of `Does()`) supported async callbacks, so that async operations within the callback could be awaited rather than blocked.

``` csharp
Task("Whatever").Does(() =>
{
    ...
    var response = httpClient.GetAsync("http://example.com").GetAwaiter().GetResult();
    ...
}
```

vs.

``` csharp
Task("Whatever").Does(async () =>
{
    ...
    var response = await httpClient.GetAsync("http://example.com");
    ...
}
```

**Comment by RichiCoder1** [comment]
Related: #156

**Comment by ejball** [comment]
Definitely, but to be clear, I'd be just as happy if it blocked on the returned async task. I just want to be able to call `Async` methods with `await` syntax. :-)

**Comment by devlead** [comment]
Relates to PR #1258

**Comment by adamhathcock** [comment]
Updated my PR again https://github.com/cake-build/cake/pull/1258

**Comment by adamhathcock** [comment]
For 0.22?  I'll rebase again in that case :)

**Comment by devlead** [comment]
I've assigned this to 0.23.0

**Comment by devlead** [comment]
Fixed by #1258

**Comment by jnm2** [comment]
This update broke all my code that was doing this:

```cs
void ReusableMethod()
{
    // ...
}

Task("Foo").Does(ReusableMethod);
```

Now I get a series of these messages:

```
Error: Error occurred when compiling build script: error CS0121: The call is ambiguous between the following methods or properties: 'CakeTaskBuilderExtensions.Does(CakeTaskBuilder<ActionTask>, Action)' and 'CakeTaskBuilderExtensions.Does(CakeTaskBuilder<ActionTask>, Func<Task>)'
```

**Comment by jnm2** [comment]
These are the workarounds:
 - `Task("Foo").Does(() => ReusableMethod());`
 - `Task("Foo").Does((Action)ReusableMethod());`
