### ISSUE TITLE
Allow paths with spaces for OutputDirectory on DotNetCore Aliases

### ISSUE THREAD

**Issue by SavaNDragos** [cake-build/cake#1034]
I tried to run:

```csharp
DotNetCoreAliases.DotNetCorePublish(inSolutionDetails.context, iterProjectLocation + "\\project.json", new DotNetCorePublishSettings() {
    Configuration = "Release",
    OutputDirectory =inSolutionDetails.ArtifactsFolder + "\\" + projectName,
});
```

Note: `inSolutionDetails.ArtifactsFolder` has spaces in it (\Visual Studio) and .NET Core CLI will return an error:

```
Unrecognize command or argument 'Studio'. 
```

The error is actually commind from the project.json location (I am sendinf the full path) not the OutputDirectory. 

I used `"\""+iterProjectLocation + "\\project.json\""` to specify the project location and it worked.

**Comment by SavaNDragos** [comment]
Unrecognize command or argument 'Studio'. 
The error is actually commind from the project.json location (I am sendinf the full path) not the OutputDirectory.

**Comment by SavaNDragos** [comment]
I used "\""+iterProjectLocation + "\\project.json\"" to specify the project location and it worked.

**Comment by patriksvensson** [comment]
@SavaNDragos I moved your comments to the issue and fixed the formatting.

**Comment by gep13** [comment]
@SavaNDragos this should be available in the next release of Cake.
