### ISSUE TITLE
Documentation: Provide a link to the corrosponding GitHub File?

### ISSUE THREAD

**Issue by robertmuehsig** [cake-build/cake#1042]
I hope this is the correct repository for documentation "issues" - this is more or less a suggestion or an idea.

I'm currently digging in CAKE and read the documentation, e.g. this:
![image](https://cloud.githubusercontent.com/assets/756703/16722325/192ecfbe-4746-11e6-970c-0059f8ed1725.png)

http://cakebuild.net/api/cake.core.tooling/d75cd243/60ae911b

It would be very handy if there would be a big "Improve on GitHub" button which points directly to this file. 
This could improve the documentation and would help to understand the code better.

I'm not sure how the documentation is currently build - if you gave me some hints I could try to implement this "feature".

What do you think?

**Comment by gep13** [comment]
@robertmuehsig you will see that on some pages, i.e. this one:

http://cakebuild.net/docs

that we already have that.  For this particular page that you are referring to, the documentation is generated directly from the XML comments within the source code of the file

While I agree with your comment that it would be nice to have this functionality, I am not sure if this is something that we want to tackle just now.  I know @patriksvensson has some ideas about the current site, and how it is written/constructed, and this way well change.

**Comment by robertmuehsig** [comment]
Ah - yeah - I noticed that some page have this functionality and others don't. If you think this would be valuable, just let me know and I try to help.

**Comment by gep13** [comment]
>@robertmuehsig said...
Ah - yeah - I noticed that some page have this functionality and others don't. If you think this would be valuable, just let me know and I try to help.

In general, we will accept any help that is offered with regard to the site.  Neither @patriksvensson @devlead or myself have any sort of flair when it comes to web design :smile: I think that would need to be part of a larger conversation though, perhaps when @patriksvensson is back from holiday.

**Comment by devlead** [comment]
I too would love to see this functionality :+1: 

Issue is that the xml docs don't contain any file or line number information, we generate from the nuget using assembly and xml doc file for both Cake & Addin assemblies.
Currently we'rent shipping any symbols either so we don't have any PDBs, also for it to fully work we and addin authors would need to use something like [GitLink](https://github.com/GitTools/GitLink) so we can link to the right repository, branch and version of each file.

So providing this functionality likely isn't impossible but do entail some yak shaving.

**Comment by gep13** [comment]
>@devlead said....
So providing this functionality likely isn't impossible but do entail some yak shaving.

yak yak yak :smile:

**Comment by devlead** [comment]
> @gep13 said...
> yak yak yak :smile:

"We accept pull requests..."  :wink: 
![gd0a7bnrh5unw](https://cloud.githubusercontent.com/assets/1647294/16723935/4bd8eba2-4750-11e6-9e4b-677ecdb45367.gif)

**Comment by robertmuehsig** [comment]
How do you generate those pages?

**Comment by devlead** [comment]
@robertmuehsig it's currently dynamically generated when the website starts, it's all custom code mostly written by @patriksvensson .

**Comment by devlead** [comment]
Issue moved to [cake-build/website #189](https://github.com/cake-build/website/issues/189) via [**ZenHub**](https://www.zenhub.com/)
