### ISSUE TITLE
Examples for the bootstrapper should be provided 

### ISSUE THREAD

**Issue by donnib** [cake-build/cake#1049]
Hi,
I think there should be examples that shows how to use the bootstrapper scripts for Powershell and Bash such as how to pass arguments to the cake script. 

/donnib

**Comment by luisgoncalves** [comment]
The command line options and usage is described [here](http://cakebuild.net/docs/cli/usage). Maybe adding a note/link on the [getting started page](http://cakebuild.net/docs/tutorials/setting-up-a-new-project) is sufficient? Something like "command line options can also be supplied to the bootstrapper and are forwarded to cake".

**Comment by gep13** [comment]
@donnib @luisgoncalves can you guys have a look at this page: http://cakebuild.net/docs/tutorials/extending-the-bootstrapper It has been in the website for a while, but not accessible as the breadcrumb link wasn't there.  I have just corrected that.

Let me know if you think this is enough, or whether additional information is required.

Regardless, can any website related issues be raised over here:

https://github.com/cake-build/website

Thanks!
