### ISSUE TITLE
Cake 0.14.0.0 WithCriteria is not working when using #load

### ISSUE THREAD

**Issue by robgha01** [cake-build/cake#1050]
I cant get WithCriteria to work tested the example code DateTime.... and the one i want working Tasks but i get the bellow error.

tested the following
```
WithCriteria(() => DateTime.Now.Second % 2 == 0)
WithCriteria(() => Tasks.Any(x => x.Name == "Build-Nuget"))
WithCriteria(Tasks.Any(x => x.Name == "Build-Nuget"))
```

```
Task("Publish-Nuget")
    .WithCriteria(() => DateTime.Now.Second % 2 == 0)
    .IsDependentOn("Build-Nuget")
    //.WithCriteria(() => Tasks.Any(x => x.Name == "Build-Nuget"))
    .Does(() =>
```

> Error: Microsoft.CodeAnalysis.Scripting.CompilationErrorException: D:/Workspace/BlueLeet/BlueLeet.Build/BlueLeet.Build/Scripts/base.cake(108,6): **error CS1928: 'CakeTaskBuilder<ActionTask>' does not contain a definition for 'WithCriteria' and the best extension method overload 'CakeTaskBuilderExtensions.WithCriteria<T>(CakeTaskBuilder<T>, bool)' has some invalid arguments**
> vid Microsoft.CodeAnalysis.Scripting.Script.CompilationError(DiagnosticBag diagnostics)
> vid Microsoft.CodeAnalysis.Scripting.Script.GetExecutor(CancellationToken cancellationToken)
> vid Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
> vid Microsoft.CodeAnalysis.Scripting.Script.Run(Object globals)
> vid Cake.Scripting.Roslyn.Nightly.DefaultRoslynNightlyScriptSession.Execute(Script script)
> vid Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
> vid Cake.Commands.BuildCommand.Execute(CakeOptions options)
> vid Cake.CakeApplication.Run(CakeOptions options)
> vid Cake.Program.Main()

im using the following settings:
-Experimental

**Comment by devlead** [comment]
Just so we're clear is `WithCriteria(Tasks.Any(x => x.Name == "Build-Nuget"))` a typo in this issue as it lacks _"lambda"_ `()=>`?

**Comment by luisgoncalves** [comment]
I just tested this on Windows and Ubuntu with Cake 0.14 and it worked as expected. I'm using the following cake script:

```
var target = Argument("target", "Default");
var name = Argument("name", "John Doe");

Task("Default")
    .IsDependentOn("WhatTimeIsIt")
    .Does(() =>
    {
        Information("Hello " + name);
    });

Task("WhatTimeIsIt")
    .WithCriteria(name == "X")
    .WithCriteria(() => name == "X")
    .WithCriteria(() => Tasks.Any(x => x.Name == "WhatTimeIsIt"))
    .Does(() => 
    {
        Warning(DateTime.Now.ToString());
    });

RunTarget(target);
```

And running `.\build.ps1 -name=X -Experimental`

**Comment by robgha01** [comment]
@luisgoncalves  Im using two cake scripts one called base.cake and other called build.cake

Dide you use expremental ? and dide you load a second script in with the code ?
```
#load "../BlueLeet.Build/Scripts/base.cake"
Task("Build-Nuget")
    .IsDependentOn("Patch-Assembly-Info")
    .IsDependentOn("Run-Unit-Tests")
    .Does(() =>
{    
    // Build Main
    var mainPackage = $"./{projectName}.nuspec";
    var nuGetPackSettings   = CreateNuGetPackSettings($"{projectName}", mainPackageVersion, new NuSpecContent { Source = $"/Scripts", Target = "content"} );
	nuGetPackSettings.BasePath = srcDir;
	Debug("Building nuget package '{0}' Version '{1}'", nuGetPackSettings.Id, nuGetPackSettings.Version);
    NuGetPack(mainPackage, nuGetPackSettings);
});
```
the base
```
#addin "Cake.Powershell"
#addin "Cake.Git"
#addin "nuget:?package=RestSharp&version=105.2.3"
#addin "Cake.Json"
#addin "Cake.DocFx"
#tool "docfx.msbuild"
#tool "nuget:?package=NUnit.ConsoleRunner&version=3.2.1"
#tool "nuget:?package=GitVersion.CommandLine"
#reference "Microsoft.CSharp.dll"
#reference "System.dll"
#reference "mscorlib.dll"
#reference "System.Core.dll"

//////////////////////////////////////////////////////////////////////
// Using statements
//////////////////////////////////////////////////////////////////////
using System.Collections;
using System.Diagnostics;
using System.Linq;
using RestSharp;
using RestSharp.Authenticators;

Task("Ensure-Vso-Environment")
    .WithCriteria(vsoCredentials==null)
    .Does(() =>
{
});
```

**Comment by robgha01** [comment]
@gep13 @luisgoncalves  I tested WithCriteria outside of the base and it worked so it has someting to do with the #load thing.

**Comment by gep13** [comment]
@robgha01 I suspect that is has to do with the vsoCredentials variable.  Where is that getting defined?  I don't see that in either of your scripts.  I suspect that this will have to be declared/set within your Setup function.

**Comment by robgha01** [comment]
@gep13 yes that is true its defined in the top and its of type dynamic and i set it to null and it throws if i call it likethis .WithCriteria(vsoCredentials == null) but it seams to work when i call it like this .WithCriteria(() => vsoCredentials == null)

**Comment by luisgoncalves** [comment]
With `vsoCredentials ` being dynamic, the `vsoCredentials ==null` expression's type is also dynamic. And then there's no `WithCriteria` overload to match that.

**Comment by robgha01** [comment]
ye that is true, small things esey to miss xD

**Comment by devlead** [comment]
@robgha01 does doing something ` .WithCriteria( ()=>(bool)(vsoCredentials==null))` work around the dynamic issue?
