### ISSUE TITLE
NuGetRestore failed: Default nuget.exe is too old for newer packages

### ISSUE THREAD

**Issue by robertmuehsig** [cake-build/cake#1063]
### What You Are Seeing?
NuGetRestore("foo.sln") fails when using AutoMapper 5.0.0

```
PS C:\BuildAgent\_work\4\s> .\.cake\Cake.exe build.cake -target="NuGetRestore"
```

```
========================================
NuGetRestore
========================================
WARNUNG: 'AutoMapper' already has a dependency defined for 'Microsoft.CSharp'.
Installing 'AutoMapper 5.0.0'.
'AutoMapper' already has a dependency defined for 'Microsoft.CSharp'.
An error occured when executing task 'NuGetRestore'.
Error: NuGet: Process returned an error (exit code 1).
```

### What is Expected?

AutoMapper Package should have been downloaded (like with the most recent nuget.exe)

### What version of Cake are you using?
0.14.0

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)

* Use AutoMapper 5.0.0 in one of your projects
* Invoke NuGetRestore("your.sln")

### Output Log

```
Executing task: NuGetRestore
Executing: "C:/BuildAgent/_work/4/s/tools/NuGet.exe" restore "C:/BuildAgent/_work/4/s/my.sln" -NonInteractive
WARNUNG: 'AutoMapper' already has a dependency defined for 'Microsoft.CSharp'.
Installing 'AutoMapper 5.0.0'.
'AutoMapper' already has a dependency defined for 'Microsoft.CSharp'.
```

### My Workaround

We have our own .nuget directory checked in and can use the most recent NuGet.exe:
![image](https://cloud.githubusercontent.com/assets/756703/16867744/d4adc670-4a73-11e6-83ab-cf5e6a8d4eb7.png)

```
Task("NuGetRestore")
    .Does(() =>
{
    NuGetRestore("my.sln", new NuGetRestoreSettings() { ToolPath = @".nuget/nuget.exe" });
});
```

### "Root cause":

The nuget.exe that Cake tries to use is too old for the new package stuff (that AutoMapper 5.0.0 is using)

![image](https://cloud.githubusercontent.com/assets/756703/16867777/1657783c-4a74-11e6-9239-6bac15836c4a.png)

**Comment by devlead** [comment]
@robertmuehsig Cake's tool resolution uses what you provide in it's tools folder or avail in system path.
you can find the latest version of nuget here
https://dist.nuget.org/index.html

If you don't want to use what's provided by computer running you can modify your bootrapper to always download specific or latest version like Cake's own does
https://github.com/cake-build/cake/blob/develop/build.ps1#L20

You can override tool path for just one alias call by specifying the `ToolPath` property avail on all tool settings classes.

You can also register tools paths globally in script using `context.Tools.Register(FilePath)` in your setup task.

**Comment by robertmuehsig** [comment]
Ah - the NuGet.exe with version 2.8.6xxx was copied over from somewhere on my machine?

**Comment by devlead** [comment]
Yes, likely from the CI system.

**Comment by ravensorb** [comment]
What about adding support for nuget.exe update -self in the bootstrapper for this type of scenario?

**Comment by gep13** [comment]
@ravensorb not sure that this is something that we would want in the default bootstrapper, but certainly nothing to stop you doing that in your own version of it.

@robertmuehsig sounds like the original problem is resolved, so I am going to close this issue, feel free to re-open.
