### ISSUE TITLE
Feature Request: Add support for "delete" to NuSpec Alias

### ISSUE THREAD

**Issue by ravensorb** [cake-build/cake#1066]
### What You Are Seeing?

There are times when something goes wrong and there is a need to "delete" one or more nuget packages from a server.  It would be nice if this was possible via cake
### What is Expected?

Add NuGetDelete Alias to NuSpec namespace

**Comment by gep13** [comment]
@ravensorb just to confirm... This would be a standalone task within the build.cake file right?  This isn't something that you would want to do as part of the automated build process.  It seems like quite a dangerous operation.

**Comment by ravensorb** [comment]
Correct, this would be just an alais that someone creating a build.cake file could use if they wanted to.  For me, I have an Task called "UnPublish" that allows me to unpublish the last build or override with a specific build I use this if a regression error was accidentally introduced in nuget packages that is not discovered until after they are published to nuget.org -- considering how amazingly difficult it is to automate testing packages (installations, upgrades, etc) sometimes the only option is to pull down a package if it is not working.

**Comment by gep13** [comment]
@cake-build/team what are your thoughts on this one?

**Comment by devlead** [comment]
@ravensorb are you in a position to submit a PR for this?

**Comment by augustoproiete** [comment]
Closing as #2784

The [`NuGetDelete` alias](https://cakebuild.net/dsl/nuget/#Delete) is available since Cake v0.38.0

We also have a [`DotNetNuGetDelete` alias](https://cakebuild.net/dsl/dotnet/#NuGet) since Cake v2.0.0 that runs `dotnet nuget delete`
