### ISSUE TITLE
Parameters to bootstrap with "." not supported

### ISSUE THREAD

**Issue by ravensorb** [cake-build/cake#1069]
### What You Are Seeing?
Calling build.ps with a parameter that contains a "." is failing

Ex: .\build.ps1 -Target UnPublish -skipBuild=1 -versionToDelete="2.3.0-pre01"

Error: 
Preparing to run build script...
Running build script...
More than one build script specified.

### What is Expected?
Parameter is passed to cake script

### What version of Cake are you using?
0.13.0

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### How Did You Get This To Happen? (Steps to Reproduce)
Run the following command
* .\build.ps1 -Target UnPublish -skipBuild=1 -versionToDelete="2.3.0-pre01"

### Output Log
PS E:\Project> .\build.ps1 -Target UnPublish -skipBuild=1 -versionToDelete="2.3.0-pre01" -verbosity Diagnostic -debug
Preparing to run build script...
Running build script...
More than one build script specified.
Module directory does not exist.

Usage: Cake.exe [build-script] [-verbosity=value]
                [-showdescription] [-dryrun] [..]

Example: Cake.exe
Example: Cake.exe build.cake -verbosity=quiet
Example: Cake.exe build.cake -showdescription

Options:
    -verbosity=value    Specifies the amount of information to be displayed.
                        (Quiet, Minimal, Normal, Verbose, Diagnostic)
    -debug              Performs a debug.
    -showdescription    Shows description about tasks.
    -dryrun             Performs a dry run.
    -version            Displays version information.
    -help               Displays usage information.
    -mono               Uses the Mono Compiler, rather than Roslyn script engine.
    -experimental       Uses the nightly builds of Roslyn script engine.

**Comment by devlead** [comment]
Does it work if you change to 
`.\build.ps1 -Target UnPublish -Script .\build.cake -verbosity Diagnostic '-skipBuild=1 -versionToDelete="2.3.0-pre01" -debug'`

**Comment by ravensorb** [comment]
Yes that does seem to work

**Comment by devlead** [comment]
Excellent 👍

**Comment by ravensorb** [comment]
Hopefully that means its an easy fix :grinning:

**Comment by Sebazzz** [comment]
The default bootstrapper script is wrong and over complicated. It evals an expression, and if you format your command line parameters a certain way, the expression is invalid. 

I've [added a pull request](https://github.com/cake-build/example/issues/27) to fix the bootstrapper script.

**Comment by devlead** [comment]
Issue moved to [cake-build/resources #20](https://github.com/cake-build/resources/issues/20) via [**ZenHub**](https://www.zenhub.com/)
