### ISSUE TITLE
Default value of DRYRUN in build.sh cause build fail

### ISSUE THREAD

**Issue by wk-j** [cake-build/cake#1077]
### What You Are Seeing?

Default value of DRYRUN is `DRYRUN=false`

```
# Define default arguments.
SCRIPT="build.cake"
TARGET="Default"
CONFIGURATION="Release"
VERBOSITY="verbose"
DRYRUN=false
SHOW_VERSION=false
SCRIPT_ARGUMENTS=()
```
When I execute `./build.sh --target test`  it alway show

> More than one build script specified.

### What version of Cake are you using?

> Version 0.14.0+Branch.main.Sha.295cea62406bf905d085d14a67e3656381b72707

### Are you running on a 32 or 64 bit system?

> 64 bit

### What environment are you running on?  Windows? Linux? Mac?

> Mac

### Are you running on a CI Server?  If so, which one?

> No

### Output Log

```
./build.sh --target test
Feeds used:
  /Users/wk/.local/share/NuGet/Cache
  /Users/wk/.nuget/packages/
  https://www.nuget.org/api/v2/

All packages listed in /Users/wk/Source/csharp/TryFixie/tools/packages.config are already installed.
More than one build script specified.

Usage: Cake.exe [script] [--verbosity=value]
                [--showdescription] [--dryrun] [..]

Example: Cake.exe
Example: Cake.exe build.cake --verbosity=quiet
Example: Cake.exe build.cake --showdescription

Options:
    --verbosity=value    Specifies the amount of information to be displayed.
                         (Quiet, Minimal, Normal, Verbose, Diagnostic)
    --debug              Performs a debug.
    --showdescription    Shows description about tasks.
    --dryrun             Performs a dry run.
    --version            Displays version information.
    --help               Displays usage information.
```

### My question 

Default value of DRYRUN could be `DRYRUN=""` or not?
Because I found previous version of `build.sh` use this pattern and no above error occure.

**Comment by gep13** [comment]
@wk-j please accept my apologies.  This happened as a result of some refactoring work that I was doing last night.  @mholo65 already ready has a PR open here: https://github.com/cake-build/cake/pull/1075 to correct the problem.

Thanks for reporting the issue!
