### ISSUE TITLE
Added raw version string property in ReleaseNotes class

### ISSUE THREAD

**Issue by markrendle** [cake-build/cake#1086]
This is kind of a follow-on from #885

@Redth's [SemVer package](https://github.com/Redth/Cake.SemVer) is great for parsing strings.
Built-in `ReleaseNotesParser` is great for extracting strings from a MarkDown file, but `ReleaseNotes` contains a typed `Version` property, with anything like `-preview3-rc8-0002938` stripped off.
If the Parser included the raw string that the Version was parsed from, we could send it off to SemVer for more complex parsing.

**Comment by gep13** [comment]
@markrendle I think that this would be a sensible addition.  Would you be in a position to submit a PR for this?  Would be more than happy to accept it :smile:

**Comment by markrendle** [comment]
I'll see what I can do...

**Comment by markrendle** [comment]
Done: #1087

**Comment by gep13** [comment]
>@markrendle said,,,
Done: #1087

Cool, will take a look tonight.

**Comment by gep13** [comment]
@markrendle thanks again for your contribution to Cake :smile:
