### ISSUE TITLE
Support directory creation in CopyFile

### ISSUE THREAD

**Issue by GeertvanHorrik** [cake-build/cake#1088]
### What You Are Seeing?

CopyFile("somefile.txt", "./mynewdir/myfile.txt"); 

Error: directory mynewdir does not exist

### What is Expected?

File to be copied

### What version of Cake are you using?

Latest

### Are you running on a 32 or 64 bit system?

64-bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

No

### How Did You Get This To Happen? (Steps to Reproduce)

CopyFile("somefile.txt", "./mynewdir/myfile.txt"); 

### Output Log

The directory 'C:/source/MyProduct/output/Release/packages/MyProduct/lib/netstandard1.6' do not exist.

**Comment by gep13** [comment]
@GeertvanHorrik I see where you are coming from, but not sure if we want to do that work in the CopyFile alias.  Typically, we recommend that you use CleanDirectory or CleanDirectories, to ensure that all required paths for the build are in place, prior to doing any work.

@devlead @patriksvensson what are your thoughts?

**Comment by devlead** [comment]
@GeertvanHorrik @gep13 basically would recommend calling [EnsureDirectoryExists](http://cakebuild.net/api/cake.common.io/11f79db6/bd4d9fa7) alias first if you want to ensure it's existence. Though if it's an artifacts directory I would go with [CleanDirectory](http://cakebuild.net/api/cake.common.io/11f79db6/1ae3e7d1) as @gep13 suggests to make sure no of residue is left causing unexpected issues.

**Comment by GeertvanHorrik** [comment]
I fully agree on the cleaning stuff, but.... that still doesn't fix the creation issue ;-)

**Comment by devlead** [comment]
It kinda does as CleanDirectory creates directory if it doesn't exist.

**Comment by GeertvanHorrik** [comment]
But how does it know? Say that I have an empty ./output directory. Then I need to copy this file:

./src/MyProject/bin/debug/MyProject.dll => ./output/debug/packages/MyProject/lib/netstandard1.6/MyProject.dll

**Comment by gep13** [comment]
@GeertvanHorrik ah, ok, I see what you are asking.  No, that wouldn't be supported.  You would need seperate entries for each sub-folder in `CleanDirectory` as I don't "think" `CleanDirectory("./output/debug/packages/MyProject/lib/netstandard1.6")` would work.

**Comment by GeertvanHorrik** [comment]
I think we can close this one, thanks for all the replies. I will just create the folder before copying the file, that's easiest for now.
