### ISSUE TITLE
Launching an application from OSX via "open" (i.e. launching GUI applications from Cake)

### ISSUE THREAD

**Issue by ghuntley** [cake-build/cake#1095]
This issue is to discuss how to start GUI processes/applications i.e. `MyCoolApp.app` from a cakebuild script or implement functionality within core to make it possible.

I've found myself in a situation where the tool can be installed anywhere [1] and the user needs to specify identifiers which are appended as a postfix to the tool [2]. This is simple....

[1] Easily handled by creating `MyCustomTool<T> : Tool<TSettings>`
[2] Use `CreateArgumentBuilder().Append(xxx)` and pass into the `Run` of the tool.

Except the way start an OSX application process is to launch via `/usr/bin/open`. I've got a dodgy workaround in place now to define the tool location as `/usr/bin/open` and then mash arguments onto this tool but doing it this way means that the user can no longer customize the location of the tool.

```
const string deviceIdentifier = "passedInViaMethodParam"

 var arguments =
    CreateArgumentBuilder(Settings)
        .Append(" -Fgn").Append("/Applications/Xcode.app/Contents/Developer/Applications/Simulator.app")
        .Append("--args")
        .AppendQuoted(deviceIdentifier);

Run(Settings, arguments);
```

It's worth noting unless the `-W` param is set on `/usr/bin/open` then the command is non-blocking, you must set `-W` to block/pause cakebuild - see https://developer.apple.com/legacy/library/documentation/Darwin/Reference/ManPages/man1/open.1.html - imho this and all args for `/usr/bin/open` should be user configurable (i.e. `Append(xxx)`)

/cc @gep13 continuing our discussion from gitter.

**Comment by gep13** [comment]
@ghuntley thanks for posting this.

I am going to need some input from @patriksvensson and @devlead on this one.

**Comment by devlead** [comment]
Do we have more Mac specific scenarios? Would an Cake.Mac addin make sense or could we make something generic that would make sense in common?

**Comment by devlead** [comment]
Think addin makes more sense. Will go ahead an close this issue.
