### ISSUE TITLE
UploadArtifact support via the AppVeyor provider is incomplete

### ISSUE THREAD

**Issue by Philo** [cake-build/cake#1096]
Raising the issue to attach to my incoming pull request to add these options :)

---

### What You Are Seeing?
The ```.UploadArtifact(FilePath path)``` method does not support the full options available for AppVeyor.

### What is Expected?
```
appveyor <path> [-FileName <string>] [-DeploymentName <string>] [-Type <type> {Auto, WebDeployPackage, NuGetPackage}]
```
```c#
BuildSystem.AppVeyor.UploadArtifact("./artifacts/webdeploy.zip", AppVeyorUploadArtifactType.WebDeployPackage);

BuildSystem.AppVeyor.UploadArtifact("./artifacts/package.zip"); // Uploads as "Auto"

BuildSystem.AppVeyor.UploadArtifact("./artifacts/webdeploy.zip", AppVeyorUploadArtifactType.WebDeployPackage, "MyApp.Web"); // assigns deployment name as required when using the deployment agent

```

### What version of Cake are you using?
0.14.0

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
AppVeyor (Windows)

### Are you running on a CI Server?  If so, which one?
AppVeyor

**Comment by gep13** [comment]
@Philo thanks again! :smile:
