### ISSUE TITLE
AppVeyor.UploadTestResults failing silently

### ISSUE THREAD

**Issue by gjstockham** [cake-build/cake#1097]
### What You Are Seeing?
When uploading test results using the AppVeyor.UploadTestResults method, no test results appear in the appveyor build, but there is no error produced.

After some debugging, it appears the appveyor api is returning 415 Unsupported Media Type

### What is Expected?
The tests should upload correctly, or some sort of error should be produced

### What version of Cake are you using?
0.14.0.0

### Are you running on a 32 or 64 bit system?
x64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
AppVeyor

### How Did You Get This To Happen? (Steps to Reproduce)
Cake build with NUnit tests, then upload to AppVeyor

```
Task("Run-Tests")
    .IsDependentOn("Build")
    .Does(() =>
{  
    NUnit(testAssemblies);

    if(AppVeyor.IsRunningOnAppVeyor)
    {
        AppVeyor.UploadTestResults(testOutput, AppVeyorTestResultsType.NUnit);
    }
});
```

### Output Log
There is no output produced on failure

### Possible Resolution

The appveyor example for this uses powershell: https://www.appveyor.com/docs/running-tests#uploading-xml-test-results

I have tried adding content-type, changing to multipart content upload and a few other changes, but nothing worked.

However, the powershell example uses System.Net.WebClient rather than System.Net.Http.HttpClient.  Changing to this worked for me.  I can submit a pull request with this change, but wondered if there were any other factors that I hadn't considered?

**Comment by ChrisMaddock** [comment]
In addition to the fix, would it be possible to report the error here? 

I've hit a 'silent failure' here also - at the time I had bigger problems so didn't investigate further. Would be great if the failure could be logged though!

**Comment by gep13** [comment]
>@ChrisMaddock said...
In addition to the fix, would it be possible to report the error here?
I've hit a 'silent failure' here also - at the time I had bigger problems so didn't investigate further. Would be great if the failure could be logged though!

I think we need to tackle this as a separate issue.

**Comment by gep13** [comment]
@ChrisMaddock new issue created here: https://github.com/cake-build/cake/issues/1112

**Comment by ChrisMaddock** [comment]
Thanks @gep13 :-)

Appveyor.exe doesn't appear to be used for uploading test results however - these just go through a web request, which I thought might be easier to handle. Is this still covered by #1112?

Thanks for spotting it when closing the issue, regardless!

**Comment by gep13** [comment]
Hmmm, yes and no, I think your particular requirement is already going to be met.  This was added:

https://github.com/cake-build/cake/pull/1099/files#diff-5ea055597d8263244198033de799294dR82

Which as documented here:

https://msdn.microsoft.com/en-us/library/system.net.http.httpresponsemessage.ensuresuccessstatuscode(v=vs.118).aspx

Will throw an exception, if not a successful operation.  The other AppVeyor methods will get similar treatment as a result of #1112

**Comment by ChrisMaddock** [comment]
Aha - great! Don't think that was in the first version of the PR I looked at. Thanks @gep13, and @Philo!
