### ISSUE TITLE
OpenCover doesn't fail the build if tests fail

### ISSUE THREAD

**Issue by MarkusAmshove** [cake-build/cake#1101]
### What You Are Seeing?

When I have a failing unittest, the OpenCover buildstep doesn't fail the build.
I could do a seperate test step before the coverage, but then I had to run the tests twice.

### What is Expected?

I expect the build to fail, because the tests are failing.

### What version of Cake are you using?

Version 0.14.0+Branch.main.Sha.295cea62406bf905d085d14a67e3656381b72707

### Are you running on a 32 or 64 bit system?

64bit

### What environment are you running on?  Windows? Linux? Mac?

Windows 10

### Are you running on a CI Server?  If so, which one?

No

### How Did You Get This To Happen? (Steps to Reproduce)

I created a repository to reproduce it:

https://github.com/MarkusAmshove/OpenCoverDoesntFail

The build is creating reports for the unit tests and the coverage, which can be viewed in:

    .\build\reports\Tests\NUnit3.html

and

    .\build\reports\Coverage\index.htm

### Output Log

If I run build.ps1 I expect the following output:

    .\build.ps1
    $?

to yield False, but it gives True.

**Comment by gep13** [comment]
@MarkusAmshove I don't see anything in the repo that you link to.  Have you pushed the source?

**Comment by MarkusAmshove** [comment]
Oops, sorry @gep13 

I just pushed it ;)

**Comment by gep13** [comment]
@MarkusAmshove try setting this property in your NUnit3Settings class:

http://cakebuild.net/api/cake.common.tools.nunit/7bd0c6da/14279c2d

As per here:

https://github.com/OpenCover/opencover/issues/168

**Comment by gep13** [comment]
Also, you might want to look at this setting:

http://cakebuild.net/api/cake.common.tools.opencover/48327845/d90cdd53

**Comment by MarkusAmshove** [comment]
The "StopOnError" didn't do the trick, but sounds like a good default settings, because I had unittests with errors which also wouldn't fail the build ;-)

Setting the ReturnTargetCodeOffset to 0 did the trick.

I pushed the changes to the repository.

Is Cake able to set some setting defaults or does it just instantiate those classes? Those settings sounds like they should be a default.

Anyway, thanks for your help! I'm closing this as my original issue is resolved :+1:

**Comment by gep13** [comment]
>@MarkusAmshove said....
Is Cake able to set some setting defaults or does it just instantiate those classes? Those settings sounds like they should be a default.

Cake is just a Wrapper around the underlying tools, so we don't add anything to them that aren't there by default already.  If you were manually running the tool, you would have add to add those flags as well.

>@MarkusAmshove said...
Anyway, thanks for your help! I'm closing this as my original issue is resolved :+1:

Thanks!
