### ISSUE TITLE
Add support for adding messages to the AppVeyor build log

### ISSUE THREAD

**Issue by Philo** [cake-build/cake#1102]
Add the ability to send messages to the AppVeyor build log via the:

```appveyor AddMessage``` command.

This could then be used to push specific messages (info, warning and error) to the separate AppVeyor messages tab for a build.

I would like to be able to combine this with the TaskSetup and TaskTeardown methods to log build script progress:

```c#
TaskSetup((context, task) =>
{
    var message = string.Format("Task: {0}", task.Task.Name);
    // custom logging
    if(BuildSystem.IsRunningOnAppVeyor) {
      BuildSystem.AppVeyor.AddInformationalMessage(message);
    }
});

TaskTeardown((context, task) =>
{
    var message = string.Format("Task: {0}", task.Task.Name);
    // custom logging
    if(BuildSystem.IsRunningOnAppVeyor) {
      BuildSystem.AppVeyor.AddInformationalMessage(message);
    }
});
```

Then further refine this into a common abstraction that can be agnostic of build system and can report messages specific to the current build environment (teamcity system messages, appveyor messages):

```c#
TaskSetup((context, task) =>
{
    var message = string.Format("Task: {0}", task.Task.Name);
    // custom logging
    BuildSystem.AddInformationalMessage(message);
});

TaskTeardown((context, task) =>
{
    var message = string.Format("Task: {0}", task.Task.Name);
    // custom logging
    BuildSystem.AddInformationalMessage(message);
});
```

**Comment by gep13** [comment]
@Philo  Thank you for your contribution to Cake!
