### ISSUE TITLE
Corrected setting /m parameter to MSBuild when not requested

### ISSUE THREAD

**Issue by ravensorb** [cake-build/cake#1104]
### What You Are Seeing?
Xamarin based projects are not compiling correctly.  Either SDK files are not found or Android packages are not downloading correctly on a clean build server with minimal build tools installed.

Note: This works perfectly if I execute msbuild manually on exact same system

![error](https://i.imgur.com/R5fG5GD.png)

and

```
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(387,2): error XA5207: Please install package: 'Xamarin.Android.Support.v4' available in SDK installer. Java library file C:\Users\build\AppData\Local\Xamarin\Xamarin.Android.Support.v4\23.3.0.0\embedded\classes.jar doesn't exist. [E:\Builds\GitHub\Xamarin-Forms-Labs\src\Forms\XLabs.Forms.Droid\XLabs.Forms.Droid.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(387,2): error XA5207: Please install package: 'Xamarin.Android.Support.v4' available in SDK installer. Java library file C:\Users\build\AppData\Local\Xamarin\Xamarin.Android.Support.v4\23.3.0.0\embedded\libs/internal_impl-23.3.0.jar doesn't exist. [E:\Builds\GitHub\Xamarin-Forms-Labs\src\Forms\XLabs.Forms.Droid\XLabs.Forms.Droid.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(387,2): error XA5206: Please install package: 'Xamarin.Android.Support.v4' available in SDK installer. Android resource directory C:\Users\build\AppData\Local\Xamarin\Xamarin.Android.Support.v4\23.3.0.0\embedded\./ doesn't exist. [E:\Builds\GitHub\Xamarin-Forms-Labs\src\Forms\XLabs.Forms.Droid\XLabs.Forms.Droid.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(387,2): error XA5207: Please install package: 'Xamarin.Android.Support.v7.CardView' available in SDK installer. Java library file C:\Users\build\AppData\Local\Xamarin\Xamarin.Android.Support.v7.CardView\23.3.0.0\embedded\classes.jar doesn't exist. [E:\Builds\GitHub\Xamarin-Forms-Labs\src\Forms\XLabs.Forms.Droid\XLabs.Forms.Droid.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(387,2): error XA5206: Please install package: 'Xamarin.Android.Support.v7.CardView' available in SDK installer. Android resource directory C:\Users\build\AppData\Local\Xamarin\Xamarin.Android.Support.v7.CardView\23.3.0.0\embedded\./ doesn't exist. [E:\Builds\GitHub\Xamarin-Forms-Labs\src\Forms\XLabs.Forms.Droid\XLabs.Forms.Droid.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(387,2): error XA5207: Please install package: 'Xamarin.Android.Support.v7.RecyclerView' available in SDK installer. Java library file C:\Users\build\AppData\Local\Xamarin\Xamarin.Android.Support.v7.RecyclerView\23.3.0.0\embedded\classes.jar doesn't exist. [E:\Builds\GitHub\Xamarin-Forms-Labs\src\Forms\XLabs.Forms.Droid\XLabs.Forms.Droid.csproj]
C:\Program Files (x86)\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets(387,2): error XA5206: Please install package: 'Xamarin.Android.Support.v7.RecyclerView' available in SDK installer. Android resource directory C:\Users\build\AppData\Local\Xamarin\Xamarin.Android.Support.v7.RecyclerView\23.3.0.0\embedded\./ doesn't exist. [E:\Builds\GitHub\Xamarin-Forms-Labs\src\Forms\XLabs.Forms.Droid\XLabs.Forms.Droid.csproj]
```

I have also replicated this on both a Windows 10 (Build 1511 base) and a Windows 2016 Tap 5 build server.

It seems that there is something that cake is doing when it executes msbuild that is resulting in the error.

### What is Expected?
Build should work as expected.  if I run msbuild manually it works 100% of the time on a clean system

### What version of Cake are you using?
Tried 
* Version 0.13.0+Branch.main.Sha.f7346f2a5fb4e19a24cf15780ce635529f921be4
* 
### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
* Windows 2012R2
* Windows 10 (based on 1511)
* Windows 2015 Tap 5

### Are you running on a CI Server?  If so, which one?
* Standalone and appveyor (both have same issue)

https://ci.appveyor.com/project/xlabs/xamarin-forms-labs-hva8p/build/2.3.0.3.master

### How Did You Get This To Happen? (Steps to Reproduce)

**Test 1** 
Windows 2012 R2
* Setup
  * Windows Updates as of 7/21/2016
  * Install Chocolatey
  * Install 7zip
  * Install Visual Studio 2015 Enterprise w/Update 3 (full install all components except emulators and lightspeed)
* Build Process
  * Clone repository
  * Execute .\build.ps1 -Target Package  
  * Result Fails
  * Immediately execute .\build.ps1 -Target Package (which does a full clean)
  * Result Succeeds

**Test 2** 
Windows 2012 R2
* Setup
  * Windows Updates as of 7/21/2016
  * Install Chocolatey
  * Install 7zip
  * Install Visual Studio 2015 Enterprise w/Update 3 (full install all components except emulators and lightspeed)
  * Install Xamarin Tools (from Xamarin.com) with defaults (see screenshots below)
* Build Process
  * Clone repository
  * Execute .\build.ps1 -Target Package  
  * Result Fails

!(AndroidSDKInstall)[https://i.imgur.com/T76dTVv.png]
!(MissingComponents)[https://i.imgur.com/fkWOYAx.png]

**Test 3**
Windows 2012 R2
* Setup
  * Windows Updates as of 7/21/2016
  * Install Chocolatey
  * Install 7zip
  * Install Visual Studio 2015 Enterprise w/Update 3 (full install all components except emulators and lightspeed)
  * Install Xamarin Tools (from Xamarin.com) with defaults (see screenshots below)
* Build Process
  * Clone repository
  * Execute .\.nuget\nuget restore .\src\XLabs.sln -ConfigFile .\.nuget\nuget.config
  * Execute msbuild /m /v:normal /p:Configuration="Release" /p:Platform="Any CPU" /p:TreatWarningsAsErrors=False /target:Build "E:/Builds/GitHub/Xamarin-Forms-Labs/src/XLabs.sln
  * Result Fails

**Test 4**
Windows 2012 R2
* Setup
  * Windows Updates as of 7/21/2016
  * Install Chocolatey
  * Install 7zip
  * Install Visual Studio 2015 Enterprise w/Update 3 (full install all components except emulators and lightspeed)
  * Install Xamarin Tools (from Xamarin.com) with defaults (see screenshots below)
* Build Process
  * Clone repository
  * Execute .\.nuget\nuget restore .\src\XLabs.sln -ConfigFile .\.nuget\nuget.config
  * Execute msbuild /v:normal /p:Configuration="Release" /p:Platform="Any CPU" /p:TreatWarningsAsErrors=False /target:Build "E:/Builds/GitHub/Xamarin-Forms-Labs/src/XLabs.sln
  * Result Sucess

**The issue seems to be related to the /m property**

[Link to GitHub Repository](https://github.com/XLabs/Xamarin-Forms-Labs/)

### Output Log

[cakebuild-20160723-0706.txt](https://github.com/cake-build/cake/files/379847/cakebuild-20160723-0706.txt)

**Comment by gep13** [comment]
@ravensorb Have you ran Cake with diagnostic verbosity, found the msbuild command it is using, and then tried running that directly?

**Comment by gep13** [comment]
@ravensorb does that work? If so, what is different between you running manually?

**Comment by ravensorb** [comment]
yes -- the log file attached shows a failed build.  I have tracked it down the the "/m" as I mentioned in the write up.  It is possible that this is actually an msbuild issue.  I am going to try to set MaxCpu to 0 in my MSBuildSettings next

**Comment by devlead** [comment]
@ravensorb make sure you're running same version of MSBuild too, you can set toolversion via the settings.

**Comment by gep13** [comment]
Off the top of my head, I am not familiar with the "/m" flag. What is it? And how is it getting set?

**Comment by ravensorb** [comment]
@devlead yes, I am 100% sure.  I took the msbuild command from the detailed log, removed the /m and ran it -- it worked

@gep13 the /m tells msbuild to do a multi-threaded build

**Comment by gep13** [comment]
So are you setting that in your cake file? On phone just now, so hard to check.

**Comment by ravensorb** [comment]
@gep13 seems like default behavior of cake is to set the /m option.  I am going to override it and see if that helps right now

**Comment by gep13** [comment]
@ravensorb so, looks like this value is set by default: https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs#L55 either to just `/m` or `/m:{x}` where x is the number of CPU's on the machine.

**Comment by gep13** [comment]
@cake-build/team should the following:

```
builder.Append(settings.MaxCpuCount > 0 ? string.Concat("/m:", settings.MaxCpuCount) : "/m");
```

be:

```
builder.Append(settings.MaxCpuCount > 0 ? string.Concat("/m:", settings.MaxCpuCount) : "/m:1");
```

**Comment by gep13** [comment]
Above suggestion is based on this:

![image](https://cloud.githubusercontent.com/assets/1271146/17079005/a3df087c-50fb-11e6-98bb-b6d42390929b.png)

**Comment by ravensorb** [comment]
@gep13 I believe a /m on its own will use all possible CPUs.  There should be a way to "remove" the /m if needed (maybe set MaxCpuCount = -1 or make it a nullable type (null don't include, 0 include /m on its own, anything else try as an actual number)?

**Comment by gep13** [comment]
@ravensorb yes, however, surely `\m:1` would be the same as not including it, right?  As you are saying only use one CPU.

**Comment by patriksvensson** [comment]
We can probably make it nullable (don't set if null) and make zero mean `/m`. The default valuenahould probably be null to keep as close to just rynning `msbuild.exe myproject.sln`.

What do uou think?

**Comment by ravensorb** [comment]
@gep13 not sure yet -- still testing. That will be one of the tests I run and I'll let you know what the result it.

**Comment by ravensorb** [comment]
@patriksvensson I would agree

**Comment by gep13** [comment]
Me too.

**Comment by gep13** [comment]
@ravensorb would you be in a position to submit a PR?

@patriksvensson should this be a hotfix?

**Comment by patriksvensson** [comment]
@gep13 Not against it being a hotfix, but since it wasn't introduced in 0.14.0, perhaps it's better to include it in 0.15.0. That is if there's a workaround that solves the issue.

What do you think?

**Comment by gep13** [comment]
Makes sense to me :-)

**Comment by ravensorb** [comment]
Using the following

```
MSBuild(solution, settings =>
    settings.SetPlatformTarget(PlatformTarget.MSIL)
                .SetMaxCpuCount(1)
                .WithProperty("TreatWarningsAsErrors",buildSettings.Build.TreatWarningsAsErrors.ToString())
                .WithTarget("Build")
                .SetConfiguration(configuration));
```

Seems to work -- everything compiles now.

I have also submitted an issue on the [msbuild git repository](https://github.com/Microsoft/msbuild/issues/812)
