### ISSUE TITLE
DotNetCoreRestore: dotnet restore no longer supports globbing

### ISSUE THREAD

**Issue by luisgoncalves** [cake-build/cake#1111]
As pointed [here](https://gitter.im/cake-build/cake?at=5793a37d67c448730eee57ef) by @mmisztal1980, `dotnet restore` no longer supports globbing on the `root` parameter. The XML docs on `DotNetCoreRestore` are OK, but the example shows a string with a globbing pattern. I also came across this problem and an issue wasn't created yyet.

@patriksvensson suggested that the `root` parameter on `DotNetCoreRestore` could become a `DirectoryPath`. However, on `dotnet restore` it actually can be a list of project.json, global.json or root directory.
- Is there any type on cake that can represent both files and directory paths?
- Maybe we could have a `params` argument?
- Or maybe we can assume the common use case, which I think will be a root directory for search, as Patrick suggested.

**Comment by mmisztal1980** [comment]
I believe the same applies to `dotnet test`

**Comment by devlead** [comment]
@andycmaj Is this related to your issue #985?
