### ISSUE TITLE
Issues found with 0.15.0 AppVeyor updates

### ISSUE THREAD

**Issue by Philo** [cake-build/cake#1126]
### What You Are Seeing?

* The ```UploadArtifact``` has an incorrectly named parameter (-ArtifactType should be -Type)
* The ```UploadTestResults``` is still silently completing without displaying uploaded test data

### What is Expected?

* ```UploadArtifact``` should upload with the type specified, however it will use the default "Auto" type at the moment
* ```UploadTestResults``` needs an additional name parameter set for the multipart-form-data request

### What version of Cake are you using?

0.15.0

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

AppVeyor

----

I will have a pull request incoming asap with these corrections.

**Comment by gep13** [comment]
@Philo can you hold off submitting a PR?  This might need to a be hotfix, and to facilitate that PR, we will need to create a hotfix branch, which you can select as the destination for the PR.

**Comment by gep13** [comment]
@philo can you target this branch? https://github.com/cake-build/cake/tree/hotfix/0.15.1

**Comment by Philo** [comment]
ok, will do
