### ISSUE TITLE
Allow custom loggers in the VSTestSettings

### ISSUE THREAD

**Issue by Jericho** [cake-build/cake#1138]
VSTestSettings has a property called "Logger" with two possible values: None or Trx.

However, we need to be able to specify custom values. For example, when running on AppVeyor we can specify "/logger:AppVeyor".

As a workaround, I was able to specify the AppVeyor logger using ArgumentCustomization like so:

```
Task("Run-Code-Coverage")
	.IsDependentOn("Build")
	.Does(() =>
{
	var testAssemblyPath = string.Format("./MyLibraryUnitTests/bin/{0}/MyLibrary.UnitTests.dll", configuration);
	var vsTestSettings = new VSTestSettings();
	if (AppVeyor.IsRunningOnAppVeyor) vsTestSettings.ArgumentCustomization = args => args.Append("/logger:Appveyor");

	OpenCover(
		tool => { tool.VSTest(testAssemblyPath, vsTestSettings); },
		new FilePath("./CodeCoverageData/coverage.xml"),
		new OpenCoverSettings()
			.ExcludeByAttribute("*.ExcludeFromCodeCoverage*")
			.WithFilter("+[MyLibrary]*")
			.WithFilter("-[MyLibrary]MyLibrary.Properties.*")
	);
});

```

A few ideas were suggested:

- Change the Logger property to a string and create some nice extension methods to accomplish the same thing. Like .WithAppVeyorLogger() or similar (this would probably break existing scripts though).
- Perhaps a CustomLogger string?

**Comment by Jericho** [comment]
I propose the following:

1. Mark the 'Logger' property as obsolete (I don't know what you policy is regarding obsolete properties but I imagine you want to keep it around for a release or two before removing it).
2. Also mark the VSTestLogger enum as obsolete. It wil no longer be necessary when the 'Logger' property is removed.
3. Add a new string property called 'LoggerName'
4. Add a few extension methods such as:
        .WithTrxLogger()
        .WithAppVeyorLogger()
        .WithCustomLogger(string loggerName)
        .WithoutAnyLogger()
5. As much as possible, keep the obsolete 'Logger' property and the new property in sync (for example: set LoggerName to "trx" if Logger is set to VSTestLogger.Trx; set LoggerName to a blank string if Logger is set to VSTestLogger.None; etc) and throw an exception if, for some reason, the two properties can't be kept in sync.
6. Add a new value called 'Custom' to the VSTestLogger enum. This will make it a little bit easier to keep the two properties in sync

I would be happy to submit a PR with these changes.

**Comment by gep13** [comment]
@Jericho in general, this seems like a valid approach to me. Question though... Aren't 2 and 6 slightly contradictory?

**Comment by Jericho** [comment]
They are not contradictory. #6 is necessary to keep the to properties in sync. For example if I invoke .WhitCustomLogger("mylogger") I will set the LoggerName to "mylogger" and I also need to be able to set Logger to VSTestLogger.Custom 

To be clear, #6 is temporary, until we remove the obsolete property and obsolete enum.
