### ISSUE TITLE
What tool are you using for generating documentation?

### ISSUE THREAD

**Issue by tompazourek** [cake-build/cake#1150]
Hi Cake team,

Sorry for a bit of a spammy post, I was just wondering what toolchain you use to generate the documentation on your website [cakebuild.net](http://cakebuild.net/).

Both the [markdown-based docs](http://cakebuild.net/docs) and the [API reference docs](http://cakebuild.net/dsl) have outstanding quality and are one of the best I've ever seen among open-source projects. I wish there were more docs like that.

**What technologies and tools are needed to achieve it and how do you integrate them?**

I'm sorry if it's obvious, I couldn't figure it out just by looking at the source code. I am guessing it's not part of this public repo. But maybe I missed something.

Thanks for sharing.
Tom

**Comment by patriksvensson** [comment]
Hello @tompazourek!

Thank you for your kind words. They made my afternoon when I saw them :smile: 

The documentation for Cake is a home grown system based on ASP.NET MVC, and can be found at https://github.com/cake-build/website. I'm not a web developer so there's probably a million things that can be improved in it.

Gives us a shout on our Gitter channel if you want some guidance on how to set it up.

**Comment by patriksvensson** [comment]
@tompazourek Forgot to mention that we're planning on switching to Wyam in the future, so if you're interested in generating documentation with API reference and similar and use a proper, dedicated system for this (built on Roslyn), you should check it out at http://wyam.io (or ask @daveaglick for more information).

**Comment by tompazourek** [comment]
Hi @patriksvensson,

I'm happy to see that the Cake website repo is public and Wyam sure looks exciting as well. I think I'll be fine studying both of these. 

Keep up the good work a thanks again for the pointers.
