### ISSUE TITLE
Get return code from intercepted process in SpecFlow TestExecutionReport

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#1160]
In order to know if tests passed/or failed, then SpecFlow TestExecutionReporter should return the code of the intercepted process (Unit test runner).

Another alternative would be to create an alias which takes the results of the Unit Test runner and converts it to a report using SpecFlow (this is how SpecFlow is designed to work).

**Comment by mholo65** [comment]
@gep13 @patriksvensson @devlead if ok, You may assign this to me.

**Comment by patriksvensson** [comment]
@mholo65 Done!

**Comment by mholo65** [comment]
@patriksvensson :+1: This probably means that I may implement this feature :smile:

**Comment by patriksvensson** [comment]
@mholo65 Yes! :smile:

**Comment by devlead** [comment]
@mholo65 any progress made in this area?

**Comment by mholo65** [comment]
@devlead actually, I have implemented this already (or think I have, might be only stored locally on one of my computer).. Just need to find it, rebase and fix a test before committing a PR. Somehow I have forgot about this 😄

What's the timeframe for 0.17.0?

**Comment by devlead** [comment]
@mholo65 Depending on available time 😄 , feature freeze is planned for this weekend.

**Comment by mholo65** [comment]
@devlead ok, I'll see if I could dig it up til then!

**Comment by devlead** [comment]
@mholo65 Perfect 👌

**Comment by gep13** [comment]
@mholo65 thanks again for this contribution!
