### ISSUE TITLE
Documentation doesn't show inherited interface methods / properties

### ISSUE THREAD

**Issue by IanMercer** [cake-build/cake#1170]
The [documentation](http://cakebuild.net/api/cake.core.io/9aa5daa2) for `IFile` doesn't show an `Exists` property, presumably because that property was inherited from `IFileSystemInfo`.

The documentation doesn't show that `IFile` inherits from `IFileSystemInfo`.

Either the documentation should show the inheritance relationship of `IFile` to `IFileSystemInfo` or it should automatically show all the methods and interfaces from any interfaces that are inherited.

**Comment by devlead** [comment]
Issue moved to [cake-build/website #187](https://github.com/cake-build/website/issues/187) via [**ZenHub**](https://www.zenhub.com/)
