### ISSUE TITLE
Add Ability to Redirect Standard Error on IProcess

### ISSUE THREAD

**Issue by CaptainCow95** [cake-build/cake#1172]
I was looking into redirecting standard error, as that is what one of the git commands I'm running writes to so that I can suppress it, and noticed that while it isn't currently implemented, it would be a pretty easy thing for me to add and send a pull-request for. The problem is that adding it would likely involve adding a function to the IProcess interface, effectively breaking any code that uses that interface when they would use the version that contains that addition. Is there any sort of process laid out to add things like this without breaking compatibility?

**Comment by devlead** [comment]
I think it would make sense to add GetStandardError() to IProcess and add an RedirectStandardError to ProcessSettings.

**Comment by CaptainCow95** [comment]
I'll go ahead and write up a pull-request then. We can talk about what would need to happen to safely change the interface once we see all the changes that would have to be made.

**Comment by devlead** [comment]
Fixed by #1175
