### ISSUE TITLE
XCopy-like functionality

### ISSUE THREAD

**Issue by gregfiske** [cake-build/cake#118]
I'm missing the ability in my old scripts to call xcopy to recursively copy the files in a directory and its subdirectories to a target directory.  Wondering if there could be either new API commands or some recommendations in documentation on how to do recursive directory copying in cake scripts.

**Comment by patriksvensson** [comment]
@gregfiske This functionality has been implemented by @RichiCoder1 and merged today. Will appear in the next release (probably tomorrow).

**Comment by stevensn99** [comment]
Have added a gist of the helper bases on the one by @RichiCoder1 which adds the ability to pass an array of sub directories to ignore during the copy, gist can be found here: https://gist.github.com/stevensn99/63cd45cdcc96321564101d45a8518b75

**Comment by PandaWood** [comment]
> 
> 
> Have added a gist of the helper bases on the one by @RichiCoder1 which adds the ability to pass an array of sub directories to ignore during the copy, gist can be found here: https://gist.github.com/stevensn99/63cd45cdcc96321564101d45a8518b75

FYI that gist is now dead

**Comment by StickNitro** [comment]
@PandaWood I have updated the link to the gist in my previous comment
