### ISSUE TITLE
Add include & exlude parameters to #tool directive

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#1184]
Currently `#tool` directive exclusively looks for `*.exe`, this locks out a few scenarios including _CoreCLR_ as command line assemblies there have `dll` extension.

Proposed fix for this is to add 2 new optional parameters to the `#tool` directive that lets you specify your own globbing pattern to override the default behavior.

| parameter | description | example |
|-------------|------------- |----------|
| include      | pattern of which files to look for | `#tool #tool nuget:?package=Cake.Foo&include=./**/Foo.dll`|
| exclude     | pattern of which files not considered tools  | `#tool #tool nuget:?package=Cake.Foo&exclude=./**/*Serializer*.dll`|

You should also be able to specify multiple globbing patterns i.e.
`#tool #tool nuget:?package=Cake.Foo&include=./**/*.dll&include=./**/*.exe&exclude=./**/*Serializer*.dll&exclude=./**/Foo.dll`

**Comment by patriksvensson** [comment]
@gep13 @devlead Anyone started with this yet or can I implement this?

**Comment by devlead** [comment]
@patriksvensson no
