### ISSUE TITLE
Publish symbol files

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#1196]
We should publish the symbol files for all our packages.

- [ ] Cake
- [ ] Cake.Core
- [ ] Cake.Common
- [ ] Cake.Testing

**Comment by gep13** [comment]
@patriksvensson what was the plan here?  Where are we planning on pushing them to?  Are you wanting to push to MyGet, or use GitLink, or something else? Both?

**Comment by patriksvensson** [comment]
@gep13 I was thinking about pushing them to NuGet and MyGet like normal. (NuGet automatically publishes to symbolsource.org automatically if it detects a symbol package)

**Comment by gep13** [comment]
@patriksvensson @devlead what, if anything, is required on this issue?  Has this work already been completed somewhere, and it just needs to be referenced?

**Comment by patriksvensson** [comment]
Closed via #1226.
