### ISSUE TITLE
Update Universal Windows Platform "Package.appxmanifest" Version

### ISSUE THREAD

**Issue by dachibox** [cake-build/cake#1208]
### What You Are Seeing?
I want to update the version of the **Package.appxmanifest**. Is there any better way?
### Are you running on a 32 or 64 bit system?
64 bit system
### What environment are you running on?  Windows? Linux? Mac?
Windows
### How Did You Get This To Happen? (Steps to Reproduce)

```
Task("Update-Manifest")
    .Does(() =>
{
    var fileManifest = "../ABCD/Package.appxmanifest";
    Information(fileManifest);
    XmlPokeString(fileManifest, "/Package/Identity/@Version", informationalVersion, new XmlPokeSettings {
        Namespaces = new Dictionary<string, string> {
            { /* Prefix */ "mp", /* URI */ "http://schemas.microsoft.com/appx/2014/phone/manifest" },
            { /* Prefix */ "uap", /* URI */ "http://schemas.microsoft.com/appx/manifest/uap/windows10" }
        }
    });
});
```

### Output Log
An error occured when executing task 'Update-Manifest'.
Error: Los datos del nivel de raíz no son válidos. línea 1, posición 1.

**Comment by dachibox** [comment]
@gep13 this looks really great! I will give it a try tomorrow! thanks!

**Comment by devlead** [comment]
@dachibox the error is because you're using the XmlPokeString alias which expects xml as an string the XmlPoke alias alias takes an file path though.
Read more at:
http://cakebuild.net/api/cake.common.xml/e86574fc/4620ed16

**Comment by dachibox** [comment]
@gep13 I tried magic-chunks and it is really easy to use it. It just works at the first time. 💃 

@devlead I will try it tomorrow, but I remember that XmlPoke was deprecated or something? I will confirm this.

But this issue can be closed with the magic-chunks solution. :)

Thank you guys!

**Comment by devlead** [comment]
@dachibox It was the overload that took a string that was obsoleted.

**Comment by gep13** [comment]
@dachibox nice one! Glad to hear that you got it working! :smile:
