### ISSUE TITLE
Cannot load addin written in F#

### ISSUE THREAD

**Issue by wk-j** [cake-build/cake#1214]
I have problem when execute addin that written in F#, Look like Cake not load extension method into executing context.

I don't know may Cake have any restrictions about F# or not because my code is work well on Visual Studio. I can load extension method from C# project without problems.

My repository already on github here https://github.com/cake-addin/cake-square-logo

### Error message

```
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Compiling build script...
Error: Z:/Source/github/cake-addin/Cake.SquareLogo/Example/build.cake(7,5): error CS0103: The name 'CreateLogo' does not exist in the current context
```

### Extension method

```fsharp
namespace Cake.SquareLogo.LogoAlias

type LogoSettings() =
      member val FontFamily = "Optima" with set,get
      member val FontSize = 45.0f with set,get
      member val Foreground = "White" with set,get
      member val Background = "DimGray" with set,get

[<Extension>]
type ContextExtension =
      [<CakeMethodAlias>]
      [<Extension>]
      static member CreateLogo(context: ICakeContext, text: string, outputPath: string, settings: LogoSettings) =
            let settings =
                { DrawSettings.FontSize =  settings.FontSize
                  FontFamily = settings.FontFamily
                  Foreground = settings.Foreground
                  Background = settings.Background }
            drawText(text, outputPath, settings)

      [<CakeMethodAlias>]
      [<Extension>]
      static member CreateLogo(context: ICakeContext, text: string, outputPath: string) =
            let settings = LogoSettings()
            ContextExtension.CreateLogo(context, text, outputPath, settings)
```

### Cake file

```csharp
#r "../Cake.SquareLogo/bin/Debug/Cake.SquareLogo.dll"

using Cake.SquareLogo.LogoAlias;

Task("Create-Logo").Does(() => {
    CreateLogo("Hello", "Hello.png");
});

var target = Argument("target", "default");
RunTarget(target);
```

**Comment by mrange** [comment]
I am no `CAKE` expert but it seems that if we would declare a simple extension in `C#` it could look like this:

```csharp
namespace Cake.SquareLogo.LogoAlias
{
  using Cake.Core;
  using Cake.Core.Annotations;

  public static class MyCakeExtension
  {
      [CakeMethodAlias]
      public static int GetMagicNumber(this ICakeContext context, bool value)
      {
          return value? int.MinValue : int.MaxValue;
      }
  }
}
```

Note the use of `static class` as well as a `C#` extension methods. `F#` has AFAIK no explicit support for static classes, the closest we get it `F#` modules. However, modules don't support overloading which you seem to want.

In addition `F#` extensions `type ICakeContext with ...` don't seem to append the correct attributes.

So we fake it by adding the necessary attributes to make an `F#` class look static with extension methods.

```fsharp
namespace Cake.SquareLogo.LogoAlias

open System.Runtime.CompilerServices
open Cake.Core.Annotations
open Cake.Core

type LogoSettings() =
  member val FontFamily = "Optima" with set,get
  member val FontSize = 45.0f with set,get
  member val Foreground = "White" with set,get
  member val Background = "DimGray" with set,get

// AbstractClass + Sealed makes the type look like a static class
[<AbstractClass>]
[<Sealed>]
// Static classes in C# that contains extensions methods are annotated with Extension attribute
[<Extension>] 
type ContextExtension =
  [<CakeMethodAlias>]
  // Extension methods in C# are annotated with Extension attribute
  [<Extension>] 
  static member CreateLogo(context: ICakeContext, text: string, outputPath: string, settings: LogoSettings) : int =
    printfn "GG"
    0

  [<CakeMethodAlias>]
  // Extension methods in C# are annotated with Extension attribute
  [<Extension>] 
  static member CreateLogo(context: ICakeContext, text: string, outputPath: string) : int=
    let settings = LogoSettings()
    ContextExtension.CreateLogo(context, text, outputPath, settings)
```

This seems to work for me but again, I am no `CAKE` expert.

See [this stackoverflow question](http://stackoverflow.com/questions/702256/f-extension-methods-in-c-sharp) for some more info.

Regards,

Mårten

**Comment by wk-j** [comment]
Thanks @mrange

Use `[<AbstractClass>]` and `[<Sealed>]` solve my problem. But I still confuse because I never see people use this pattern.

For example

https://github.com/fsprojects/FSharp.Core.Fluent/blob/master/src/Fluent.fs#L2161

In ListExtensionsConstrained there is no  `[<AbstractClass>]` and `[<Sealed>]` but  its work fine  in `C#`.

### Load extension from `C#`
```csharp
using Microsoft.FSharp.Collections
using FSharp.Core.Fluent;


namespace Cake.SquareLogo.CSharp
{
    public class LoadFromCSharp
    {
        [Test]
        public void ShouldVisibleFromCSharp()
        {
            var list = new FSharpList<string>("Hello", FSharpList<string>.Empty);
            var max = list.max();
            max.Should().Be("Hello");
        }
    }
```

But different in CAKE.

### Load extension from CAKE

```csharp
#r "../Cake.SquareLogo.CSharp/bin/Debug/FSharp.Core.dll"
#r "../Cake.SquareLogo.CSharp/bin/Debug/FSharp.Core.Fluent-4.0.dll"

using FSharp.Core.Fluent;
using Microsoft.FSharp.Collections;

Task("List-Max").Does(() => {
    var list = new FSharpList<string>("Hello", FSharpList<string>.Empty);
    Console.WriteLine(list.max());
});
```
When execute this task I got error about 
`FSharp.Core.Fluent.ArrayExtensionsConstrained.max<T>`

### Error message
```
Analyzing build script...
Processing build script...
Compiling build script...
build.cake (12,28): The type arguments for method `FSharp.Core.Fluent.ArrayExtensionsConstrained.max<T>(this T[])' cannot be inferred from the usage. Try specifying the type arguments explicitly
Error: An error occured while executing build script.
```

I see something wrong , Because CAKE complain about `FSharp.Core.Fluent.ArrayExtensionsConstrained.max` that never use in script.

I don’t know what cake doing in background so weird for me, you have any idea for this?

**Comment by mrange** [comment]
`CAKE` might have more restrictions when picking up extensions than `C#` ie enforcing Abstract/Sealed but I can't tell.

The other error `CAKE` seems to pickup the wrong extension method. With `list.max()` `CAKE` attempt to invoke `max<T>(this T[])` but this won't work as `list` is an `FSharpList<string>` . To answer that requires more in-depth knowledge of how `CAKE`/`Roslyn` works than what I have.

Overall, I am not too surprised that you run into problems with `FSharp.Core.Fluent` and `CAKE`. It's after all designed for `F#`, tested a bit in `C#` but probably no tests for `CAKE`/`Roslyn`.

Regards,

Mårten

**Comment by wk-j** [comment]
Whatever, use `[<AbstractClass>]` and `[<Sealed>]` solve the problem.
So I close this issue.
