### ISSUE TITLE
Feature Request: Search for documentation in the website.

### ISSUE THREAD

**Issue by bibodha** [cake-build/cake#1216]
I would love to be able to search the documentation from the cakebuild.net website. Currently, to search, I have to go to google, type `site:cakebuild.net <search term>`. It would be awesome if we can just have a simple google search input field added to the website as a first iteration and see if it needs to be made better.

**Comment by gep13** [comment]
Issue moved to [cake-build/website #153](https://github.com/cake-build/website/issues/153) via [**ZenHub**](https://www.zenhub.com/)
