### ISSUE TITLE
Better error message on failed NuGetRestore

### ISSUE THREAD

**Issue by trailmax** [cake-build/cake#1220]
### What You Are Seeing?
We are using private NuGet feed that is behind the password. Authentication is funny and does not always work. When authentication is denied I get exception stack-trace:

> System.InvalidOperationException: Unable to find version '1.0.33' of package 'MySecret.Package'.
at NuGet.PackageHelper.ResolvePackage(IPackageRepository repository, String packageId, SemanticVersion version)
at NuGet.Commands.RestoreCommand.RestorePackage(IFileSystem packagesFolderFileSystem, String packageId, SemanticVersion version, Boolean packageRestoreConsent, ConcurrentQueue`1 satellitePackages)
at NuGet.Commands.RestoreCommand.<>c__DisplayClass5.<>c__DisplayClass7.<ExecuteInParallel>b__2()

### What is Expected?
I would be really good to see there was `401 Unauthenticated` response from the server.

### What version of Cake are you using?
Latest

### What environment are you running on?  Windows? Linux? Mac?
Windows, in Visual Studio Team Services

### Are you running on a CI Server?  If so, which one?
Visual Studio Team Services

### Output Log
~~~sh
   ========================================
    Restore-NuGet-Packages
    ========================================
    Executing task: Restore-NuGet-Packages
    Starting Nuget Restore
    Executing: "C:/a/1/s/tools/NuGet.exe" restore "C:/a/1/s/src/PleaseWork.sln" -NoCache -Verbosity detailed -ConfigFile "C:/a/1/s/src/NuGet.config" -NonInteractive
    GET https://www.nuget.org/api/v2/Packages(Id='Newtonsoft.Json',Version='6.0.1')
    GET https://www.nuget.org/api/v2/Packages(Id='MyProject.Configuration.Models',Version='1.0.33')
    GET https://www.nuget.org/api/v2/Packages(Id='MyProject.Configuration.Models',Version='1.0.33.0')
    Installing 'Newtonsoft.Json 6.0.1'.
    GET https://www.nuget.org/api/v2/package/Newtonsoft.Json/6.0.1
    GET https://www.nuget.org/api/v2/Packages(Id='MyCompany.CQRS',Version='1.13.7')
    GET https://www.nuget.org/api/v2/Packages(Id='MyCompany.CQRS',Version='1.13.7.0')
    Successfully installed 'Newtonsoft.Json 6.0.1'.
    GET https://www.nuget.org/api/v2/Packages(Id='MyCompany.Helpers',Version='1.13.7')
    Using credentials from config. UserName: MyUsername
    GET https://www.nuget.org/api/v2/Packages(Id='MyCompany.Helpers',Version='1.13.7.0')
    GET https://MyCompany.pkgs.visualstudio.com/_packaging/MyCompany/nuget/v3/index.json/Packages(Id='MyProject.Configuration.Models',Version='1.0.33')
    GET https://MyCompany.pkgs.visualstudio.com/_packaging/MyCompany/nuget/v3/index.json/Packages(Id='MyCompany.CQRS',Version='1.13.7')
    GET https://MyCompany.pkgs.visualstudio.com/_packaging/MyCompany/nuget/v3/index.json/Packages(Id='MyCompany.Helpers',Version='1.13.7')
    GET https://MyCompany.pkgs.visualstudio.com/_packaging/MyCompany/nuget/v3/index.json/Packages(Id='MyCompany.CQRS',Version='1.13.7.0')
    GET https://MyCompany.pkgs.visualstudio.com/_packaging/MyCompany/nuget/v3/index.json/Packages(Id='MyProject.Configuration.Models',Version='1.0.33.0')
    GET https://MyCompany.pkgs.visualstudio.com/_packaging/MyCompany/nuget/v3/index.json/Packages(Id='MyCompany.Helpers',Version='1.13.7.0')
    System.InvalidOperationException: Unable to find version '1.0.33' of package 'MyProject.Configuration.Models'.
    at NuGet.PackageHelper.ResolvePackage(IPackageRepository repository, String packageId, SemanticVersion version)
    at NuGet.Commands.RestoreCommand.RestorePackage(IFileSystem packagesFolderFileSystem, String packageId, SemanticVersion version, Boolean packageRestoreConsent, ConcurrentQueue`1 satellitePackages)
    at NuGet.Commands.RestoreCommand.<>c__DisplayClass5.<>c__DisplayClass7.<ExecuteInParallel>b__2()
    at System.Threading.Tasks.Task`1.InnerInvoke()
    at System.Threading.Tasks.Task.Execute()

~~~

## Nuget.config is

    <?xml version="1.0" encoding="utf-8"?>
    <configuration>
      <solution>
        <add key="disableSourceControlIntegration" value="true" />
      </solution>
      <activePackageSource>
        <add key="All" value="(Aggregate source)" />
      </activePackageSource>
      <packageSources>
        <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
        <add key="VSTSMyCompany" value="https://MyCompany.pkgs.visualstudio.com/_packaging/MyCompany/nuget/v3/index.json" />
      </packageSources>
      <disabledPackageSources />
       <packageSourceCredentials>
        <VSTSMyCompany>
          <add key="Username" value="MyUsername" />
          <add key="ClearTextPassword" value="MySecretPassword" />
        </VSTSMyCompany>
      </packageSourceCredentials>
     </configuration>

## Build.cake
```
    Task("Restore-NuGet-Packages")
        .Does(() =>
        {
            var settings = new NuGetRestoreSettings()
            {
                ConfigFile = "./src/NuGet.config", 
                NoCache = true,
                Verbosity = NuGetVerbosity.Detailed,
            };
            NuGetRestore(solution, settings);
        });

    Task("Build")
        .IsDependentOn("Restore-NuGet-Packages")
        .Does(() =>
        {
            MSBuild(solution, settings =>
                settings.SetConfiguration(configuration)
                        .WithTarget("Build")
                        .SetPlatformTarget(PlatformTarget.MSIL)
                        );
        });
```

**Comment by devlead** [comment]
@trailmax currently we're utilizing the nuget command line tool so not much more we can do more than allowing you to set the tools verbosity, the output you're seeing is directly from that tool.

Improved error messages isn't am bad idea and I suggest you raise an issue for that in the nuget official repo:
https://github.com/nuget/home
