### ISSUE TITLE
OctopusDeploy missing option to deploy to an environment when release is created

### ISSUE THREAD

**Issue by trailmax** [cake-build/cake#1227]
While creating Octopus Deploy Release through `octo.exe` there is an option to deploy the release to an environment: see `--deployto` option here: http://docs.octopusdeploy.com/display/OD/Creating+releases

But this is not available in Cake as far as I can see: https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/OctopusDeploy/CreateReleaseSettings.cs

It'll be nice to have all the options provided by `octo.exe`. I've almost started a PR for that, but decided to check first.

**Comment by gep13** [comment]
@trailmax sounds good to me!

**Comment by devlead** [comment]
Fixed by #1229
