### ISSUE TITLE
GetEntryAssembly can return null, leading to NullReferenceException

### ISSUE THREAD

**Issue by asbjornu** [cake-build/cake#1231]
When `Cake.Common.Tools.Cake. CakeRunner` is initialized, it has a `private static readonly` field called `_executingAssemblyToolPaths` that is set to `System.Reflection.Assembly.GetEntryAssembly().Location`. Since `GetEntryAssembly()` can return `null`, this can fail quite horribly.

**Comment by devlead** [comment]
This is fixed by #1141
