### ISSUE TITLE
Support TeamCity WriteStartBlock/WriteEndBlock on Task Begin/End

### ISSUE THREAD

**Issue by DustinVenegas** [cake-build/cake#1235]
### What You Are Seeing?

TeamCity has the ability to group tasks together in blocks. Cake builds are currently executed as a single block in TeamCity (Step: Build.ps1 for example). This means that all output falls under a single block. 

### What is Expected?

I expect TeamCity to group related output together by logical "blocks". In the world of Cake, this means that by default each Task should be grouped as a single block in TeamCity. 

### What version of Cake are you using?

0.15.2+Branch.main.Sha.c2ca4f7ca51c59dc9c47c9830125b4e66cf14e7a

### Are you running on a 32 or 64 bit system?

Both

### What environment are you running on?  Windows? Linux? Mac?

Both

### Are you running on a CI Server?  If so, which one?

TeamCity

### How Did You Get This To Happen? (Steps to Reproduce)

1. Create a task in TeamCity to run a cake script that contains multiple tasks. 
2. Execute the build.
3. Note that output is only grouped under a single block.

**Comment by mholo65** [comment]
Use [Task Setup/Teardown](http://cakebuild.net/docs/fundamentals/setup-and-teardown) combined with [TeamCity provider Write Start/End block](http://cakebuild.net/api/cake.common.build.teamcity/1fc6a1a4). This is how many have solved this today (including me).

**Comment by devlead** [comment]
@DustinVenegas don't think this is something we would like to have in Core, build system parts are complex as is, but it's a great idea and would probably be an excellent addin/module to Cake. The proof concept solution could just be an reusable `teamcity.cake` file that hook up some static methods to the right extension points as @mholo65 explained above.

There's an StackOverflow question which has some good example code around this [here](https://stackoverflow.com/questions/38761827/cake-build-script-progress).

**Comment by DustinVenegas** [comment]
@devlead,

I can live with this functionality in an external module. Long-term, is the TeamCity functionality going to be split out from Core completely?

**Comment by gep13** [comment]
>@DustinVenegas said...
I can live with this functionality in an external module. Long-term, is the TeamCity functionality going to be split out from Core completely?

Can you confirm what you mean by this?  The current TeamCity code within Cake contained within Cake.Common, not Cake.Core.

**Comment by DustinVenegas** [comment]
@gep13,

When I first looked at Cake Build I expected Teamcity support to be an optional, separate, module. It's OK it's baked into the Cake.Common library and distributed with Cake, but I'd expect that to come "batteries included". Otherwise I'd expect that module to be in a separate library. 

I'm trying to feel out how to modify this type of component in Cake.

**Comment by DustinVenegas** [comment]
As clarification, I had other modifications than the block messages that should be added in such as writing telemetry, ensuring bits set for dependencies, etc.
