### ISSUE TITLE
Unzip with overwrite existing files 

### ISSUE THREAD

**Issue by MohsenAra** [cake-build/cake#1236]
### What You Are Seeing?
i have folder with many files , then i want extract some dlls inside it 
if files exist unzip failed
### What is Expected?
i wanna unzip with options for decision override files 
### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
windows

### Output Log
the file xxxxxx already exists

**Comment by devlead** [comment]
Currently we just use the .NET Build in [ZipFile.ExtractToDirectory](https://msdn.microsoft.com/en-us/library/hh485723.aspx), it doesn't have en overload that allows you to overwrite files.
something special like a [ZipFile.OpenRead](https://msdn.microsoft.com/en-us/library/system.io.compression.zipfile.openread.aspx) would have to be used and iterate over each entry in the archive and use the extension methods [ZipFileExtensions.ExtractToFile(this ZipArchiveEntry source, 	string destinationFileName, bool overwrite)](https://msdn.microsoft.com/en-us/library/hh485718.aspx) with overwrite set to true. So doable would need a bit of refactoring.

**Comment by gep13** [comment]
@MohsenAra I haven't checked, but it might be worth looking at this addin https://github.com/akordowski/Cake.Compression to see if it provides the functionality that you are looking for.

**Comment by MohsenAra** [comment]
thanks  @gep13 
its ok

**Comment by molesmoke** [comment]
I just hit this problem too.

@devlead An overload for overwriting was added to .NET 8 if that's helpful?
https://learn.microsoft.com/en-us/dotnet/api/system.io.compression.zipfile.extracttodirectory?view=net-8.0#system-io-compression-zipfile-extracttodirectory(system-string-system-string-system-text-encoding-system-boolean)
