### ISSUE TITLE
Validating that an addin is compatible with a specific Cake version

### ISSUE THREAD

**Issue by luisgoncalves** [cake-build/cake#1240]
As discussed on Gitter, this issue is for discussion/tracking of a mechanism for validating that an addin is compatible with a specific Cake version. @patriksvensson mentioned that this has already been discussed by the Cake team.

As an example, here's a situation I recently bumped into that would benefit from such a mechanism:
- .Net solution with _src_ and _test_ solution folders.
- Using Cake version 0.14.0
- Using Cake.Stylecop version 1.1.0 (which, looking into source code, was built against Cake.Core/Common 0.10.X)
- Cake.Stylecop uses the `SolutionParser` class in Cake.Common.
- Update Cake to latest. `SolutionParser` was updated to support solution folders on v0.15.0 and now returns **additional items** in the `Projects` collection
- Cake.Stylecop is not aware of the additional items; stops working because it can't find a _src_ project.

I have the following additional considerations/facts:
- Cake.Stylecop could have filtered the projects using the `Type` property.
- Adding additional items to the `Projects` collection seems a breaking change (probably that's why it was added on a minor version change and not a patch change, considering it's pre 1.0.0).
- Seems that most (all?) addins don't include Cake as a package dependency. Cake doesn't resolve addins' package dependencies anyway.

Is this something that could be handled by proper semver and NuGet (if addin depedencies were considered)?

**Comment by devlead** [comment]
Fixed by #1414
