### ISSUE TITLE
Wrap MakeAppX.exe

### ISSUE THREAD

**Issue by vktr** [cake-build/cake#1243]
There should be a tool wrapper for `MakeAppX.exe` which is used to package UWP apps for the Windows Store.

**Comment by phillipsj** [comment]
@vktr This would probably be best as an Addin to start and should not be too difficult to provide.  I will take a look and see if I can get something together for it.

**Comment by gep13** [comment]
@phillipsj thanks for taking a look at this!  Really appreciate your help!

**Comment by devlead** [comment]
@phillipsj  Excellent, I'll close this and you can just ping us & @vktr when addin is ready.

**Comment by phillipsj** [comment]
@vktr Just wanted to let you know that I have a few more commands and testing to do.  Then I will publish a version to myget if you would like to test it, before pushing to Nuget.  I am thinking sometime next week I should be there.

**Comment by phillipsj** [comment]
@vktr Here is the myget published version if you want to do a little testing, I still have a little to work out.  
https://www.myget.org/feed/beta-cake-addins/package/nuget/Cake.AppPackager

**Comment by phillipsj** [comment]
@vktr Here it is, I have done some testing, but I only created one UWP app.  https://www.nuget.org/packages/Cake.AppPackager/
