### ISSUE TITLE
Request for ftp support FTP Operations

### ISSUE THREAD

**Issue by sinall** [cake-build/cake#1244]
I noticed that cake supports HTTP Operations, but could not find ftp operations. Can we support ftp?

**Comment by devlead** [comment]
@sinall it's certainly possible, initially probably best suited as an addin to Cake.

**Comment by devlead** [comment]
I've suggested an answer the following StackOverflow post in how to upload a file via FTP
http://stackoverflow.com/a/39620181/5883153

There's no FTP support in .NET Core so we can't have it in Cake.Common but it could be an good addition as an Full framework only addin.

**Comment by patriksvensson** [comment]
I get the impression this has been resolved in some way so I'm going ahead and closing this issue. If I'm wrong, please reopen the issue.

**Comment by ecampidoglio** [comment]
Fast-forward a few months and there are now two add-ins to transfer files with FTP:

- [Cake.Ftp](https://github.com/phillipsj/Cake.Ftp)
- [Cake.Curl](https://github.com/ecampidoglio/Cake.Curl)

It's worth noting that Cake.Ftp [uses `FtpWebRequest`](https://github.com/phillipsj/Cake.Ftp/blob/d0f668ffafdd63ac3850e00387f6a58b459bf22e/src/Cake.Ftp/Services/FtpService.cs#L20) and therefore requires the .NET Framework. As for the FTP support in .NET Core, right now it's still missing (dotnet/corefx#7439) but it's [supposedly coming back in `netstandard2.0`](http://stackoverflow.com/a/40600388/26396) so Cake.Ftp could potentially be ported to it at some point. (@phillipsj)

Cake.Curl targets `netstandard1.6` and `net45` so it will run on Linux, macOS and Windows, as long as you have the [curl](https://curl.haxx.se) executable somewhere on your system.
