### ISSUE TITLE
Add VSTS build system support

### ISSUE THREAD

**Issue by agc93** [cake-build/cake#1250]
I will try and pick this one up soon.

**Comment by trailmax** [comment]
I've got some basic stuff done already  - let me know when you start on this, I'll share my stuff. 
I've moved our flagship project into Cake in VSTS and the most pain points I found working with their nuget feeds - VSTS feeds authentication is insane. Plus I could not publish test results so they are readable by the system.

**Comment by trailmax** [comment]
uh.. just seen your commit. Nevermind about my stuff - you already have far more than I have done. Good effort!

**Comment by patriksvensson** [comment]
Closed via #1253
