### ISSUE TITLE
OctoCreateRelease is missing channel option

### ISSUE THREAD

**Issue by vip32** [cake-build/cake#1251]
it is not possible to pass an octopus channel when creation a release. it is missing on the CreateReleaseSettings. more info [here](http://docs.octopusdeploy.com/display/OD/Channels)

**Comment by gep13** [comment]
@vip32 thank you for raising this. In the meantime, you can use ArgumentCustomization to add the missing property.

**Comment by vip32** [comment]
this maybe fits the DSL better : https://github.com/cake-build/cake/pull/1252

**Comment by devlead** [comment]
Fixed by #1252
