### ISSUE TITLE
Unquoted VSTest settings file path

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#1271]
I wanted to add a different path VSTest argument and I looked at SettingsFile as a pattern to copy, but I  found some issues with its current implementation.
The SettingsFile argument is not quoted. Filenames that contain spaces will cause problems. I've confirmed the expected behavior at the command line.

@gep13 pointed out `AppendSwitchQuoted` which is more idiomatic than the `string.Format` that was previously used in this method, so I changed all the switches to use `AppendSwitch` or `AppendSwitchQuoted` and that resolved the issue.

Fix is here: #1268

**Comment by gep13** [comment]
Thanks for noticing and fixing this.  It will be released in 0.17.0 of Cake.
