### ISSUE TITLE
Add GitLab CI build system support

### ISSUE THREAD

**Issue by reicheltp** [cake-build/cake#1274]
I run my builds on GitLab CI and it would be awesome if there is 1st class support for this environment. 

I will do a PR soon if nobody have any objections.

**Comment by gep13** [comment]
@reicheltp no objections from me 👍

**Comment by antwilliams** [comment]
Well this is good/bad timing (depending on your point of view)!

I'm just finishing off the test cases for my implementation of this. https://github.com/WarwickControl/cake/tree/feature/gitlab-ci

**Comment by gep13** [comment]
Ha ha :-D Great minds think a like!

Perhaps you and @reicheltp can work together to finalize the implementation, and then submit the PR.

@antwilliams this is part of the reason why in the contributing documentation we ask that you submit an issue before starting to work on a PR.  That way, it reduces the changes of duplication of effort, and also effort on something that might not get pulled into Cake.

**Comment by antwilliams** [comment]
Oops, I missed that (first) step in the guide in my eagerness!

@reicheltp - do you already have an implementation for this functionality? I have just pushed a completed implementation and test fixture for GitLab CI support. 
I am just ensuring everything works correctly on a local GitLab installation and then I will create a PR. Let me know if you have anything to add to my code and I can add you as a collaborator.

**Comment by reicheltp** [comment]
@antwilliams Good that I've created an issue first, before starting to implement this. 😄 I will take a look on the PR now.

**Comment by antwilliams** [comment]
I've just rebased my PR based on the latest development branch, this includes the changes merged with PR #1222. 

I notice that this ticket has been tagged as being part of the 0.17 release, I don't know when that is scheduled for but I am going on holiday tomorrow for a week. I won't be able to respond to any review actions until I get back.

**Comment by devlead** [comment]
Fixed by #1275
