### ISSUE TITLE
WiXHeat misleading signature- no mode operates on file list

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#1276]
There are currently  `WiXHeat(IEnumerable<FilePath>, ...)` signatures. `heat.exe` ignores all but the first file, so this is misleading.

What we need, as per http://wixtoolset.org/documentation/manual/v3/overview/heat.html:

| Mode | Signature |
| --- | --- |
| `dir` | `WiXHeat(DirectoryPath, ...)` |
| `file`, `project`, `reg` | `WiXHeat(FilePath, ...)` |
| `perf`, `website` | `WiXHeat(string, ...)` |

Via command line experimentation, I can confirm that `file`, `project`, and `reg` all ignore subsequent files.

Willing to PR.

**Comment by devlead** [comment]
@jnm2 if you could do a WIP PR that would be great.

**Comment by jnm2** [comment]
I got distracted and did this critical fix instead: https://github.com/cake-build/cake/pull/1360
Never had two PRs in flight on the same repo before, but I assume I do _not_ base one off the other.

**Comment by devlead** [comment]
@jnm2 no seperate feature branches for each PR.

**Comment by jnm2** [comment]
@devlead I would create two feature branches certainly, but my question was whether I base the second feature branch off develop or off  the critical fixes in the first feature branch. My gut says not to tie one feature branch to the other, but I'm editing the same files so I wasn't sure what's ideal.

**Comment by gep13** [comment]
>@jnm2 said...
I'm editing the same files so I wasn't sure what's ideal, but my gut says not to tie one feature branch to the other.

I think it is ok to base the second feature branch off the first, and then once merged, rebase one last time on develop branch.

However, for the second PR, mark it as `[WIP]` in the title of the PR, so we know not to do anything with it.

**Comment by jnm2** [comment]
I didn't think of this before, but I want the file changes of the second PR to be shown on their own so I'm pretty much forced to base of develop.

**Comment by jnm2** [comment]
This is no longer waiting for issuer feedback.
