### ISSUE TITLE
Request for `using (TempDirectory(x))` syntax

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#1277]
Instead of this:
```c#
    .Does(() =>
{
    var stagingDir = Directory("path");
    CreateDirectory(stagingDir);
    try
    {
        CleanDirectory(stagingDir);
        CopyFiles("glob", stagingDir);
        // Run some non-globbable tool on stagingDir
    }
    finally
    {
        DeleteDirectory(stagingDir, true);
    }
    // stagingDir is gone
}
```

I would like to be able to do this:

```c#
    .Does(() =>
{
    var stagingDir = Directory("path");
    using (TempDirectory(stagingDir))
    {
        CopyFiles("glob", stagingDir);
        // Run some non-globbable tool on stagingDir
    }
    // stagingDir is gone
}
```

Willing to PR if you like this idea.

**Comment by devlead** [comment]
@jnm2 doesn't sound like an bad idea, not 100% sure about the naming though, @cake-build/team thoughts?

**Comment by gep13** [comment]
@devlead agreed, not against the idea. It is at least partially implemented in this addin:

https://github.com/pitermarx/Cake.DoInDirectory

So perhaps this is best implemented there, rather in Cake directly?

**Comment by devlead** [comment]
@gep13 ah perfect, @jnm2 would you be in a postion to raise an issue at [pitermarx/Cake.DoInDirectory/issues](https://github.com/pitermarx/Cake.DoInDirectory/issues)

**Comment by jnm2** [comment]
Sure, but I really hoped this would be a core feature.
Also I think @gep13 meant to post about DoInDirectory for the `using (WorkingDirectory(x))`  syntax issue (#1270)- this issue isn't really relate to that repo.

**Comment by jnm2** [comment]
Would like clarification. Can I implement this as a core feature?

**Comment by patriksvensson** [comment]
@jnm2 The problem with something like `using(WorkingDirectory(x))` is that it would manipulate global state. This would make it problematic to do things like task parallelisation. So I think that we wait with a PR until we have way of solving this.

**Comment by jnm2** [comment]
@patriksvensson Oh good! I didn't know parallelization was a goal, but I'm glad it is. I wonder if using `AsyncLocal` for the implementation would be all that's needed?
