### ISSUE TITLE
Adding all current parameters for VSTest

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#1279]
I'd like to be able to use some of these unimplemented properties:

 * Parallel
 * EnableCodeCoverage
 * UseVsixExtensions
 * TestAdapterPath
 * TestCaseFilter
 * Diag

This is all the usable parameters as per the latest VSTest in VS2015.3, except the `/List*` parameters which didn't quite fit the flow because they return information instead of running tests.

PR #1273

**Comment by patriksvensson** [comment]
Closed via #1273
