### ISSUE TITLE
Add a "Prepend" extension for the ProcessArgumentBuilder 

### ISSUE THREAD

**Issue by antwilliams** [cake-build/cake#1281]
It would be useful to add an `Insert` method for the `ProcessArgumentBuilder` to complement the `Append` method.

This would allow additional arguments to be specified for tools that use the final argument as the target. 

An example (and my motivation) of this is the [SignTool command](https://msdn.microsoft.com/en-us/library/windows/desktop/aa387764(v=vs.85).aspx), I need to add an additional flag that isn't supported by the current tool implementation. If I use the `ArgumentCustomization` property the new flag is added to the end of the arguments and then SignTool interprets this as a filename to try and sign.

The flag I require could be added to the SignTool implementation but that would only resolve this specific use case, I would imagine that there are many tools that use the final argument as the input filename and this modification would enable those scenarios as well.

I am willing to submit a PR for this if there is interest in the improvement.

**Comment by gep13** [comment]
In principal, I don't have a problem with this.  The only suggestion would be the rather `Insert` which would suggest inserting at a particular location, the method might be called `Prepend` instead?

**Comment by gep13** [comment]
And yes, perhaps raise another issue for adding the Target property to the SignTool implementation.

**Comment by agc93** [comment]
As @gep13 mentioned, `Prepend` seems more appropriate since most `Insert` methods (even including `StringBuilder` for example) seem to be for inserting into a specified location.

**Comment by antwilliams** [comment]
Makes sense to me, I had been thinking about an Insert method that would allow a position to be specified but on further consideration this wouldn't make much sense.
The user couldn't guarantee what other arguments were being added by the tool implementation and wouldn't be able to guarantee the final position.

I'll start on a PR!

**Comment by gep13** [comment]
@antwilliams thanks again for your contribution!
