### ISSUE TITLE
Add a directive to compile a C# VS project and load it

### ISSUE THREAD

**Issue by xclayl** [cake-build/cake#1286]
A nice feature would be to have a directive that compiles a visual studio project (cotaining my aliases) and then loads the DLL.  

**rationale**: Reshaper makes it easier to code C# and there is unlikely be something as good as Resharper for editing *.cake files.

**work around**: have two *.cake files.  The first one compiles the custom aliases and then calls the second cake file which uses a directive to load the DLL.  It's complicated and two cake files isn't ideal.

**Comment by gep13** [comment]
@xclayl an interesting idea!

Out of interest, have you looked at Cake.Frosting?

**Comment by xclayl** [comment]
Scratch my idea, Cake.Frosting is better!

Hopefully we can keep the existing syntax. This is fairly verbose:
```
[TaskName("Provide-Another-Name-Like-This")]
public class Build : FrostingTask<MySettings>
{
    public override void Run(MySettings context)
    {
        context.Information("Magic: {0}", context.Magic);
    }
}
```
In comparison to:

```
Task("Provide-Another-Name-Like-This")
.Does(() => {
Information("Magic: {0}", context.Magic);
});
```
