### ISSUE TITLE
Some properties for RoundhouseSettings in Cake.Common.Tools.Roundhouse are not working properly

### ISSUE THREAD

**Issue by ferminmoli** [cake-build/cake#1292]
Error: C:/Examples/Ecommerce/blanqueria/Ecommerce/build.cake(92,4): error CS0117
: 'Cake.Common.Tools.Roundhouse.RoundhouseSettings' does not contain a definitio
n for 'Drop'

I need to drop the database using this command:

RoundhouseMigrate(new RoundhouseSettings{
            ConnectionString = connectionString,
            SqlFilesDirectory = "Ecommerce\\Scripts",
	    Drop = false
        });

Cake version: 0.15.2
Windows 10 64Bits

**Comment by phillipsj** [comment]
@ferminmoli Everything is there it just isn't working as you would expect.  The Drop Boolean in the settings file is internal. So you run the RoundHouseDrop command and it will toggle the Drop setting as part of the runner.  Look here at the RoundhouseDrop alias.:  https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/Roundhouse/RoundhouseAliases.cs

    var runner = new RoundhouseRunner(context.FileSystem, context.Environment, context.ProcessRunner,   context.Tools);
    runner.Run(settings, true);

So you need to run without the drop and it will not execute it:

RoundhouseMigrate(new RoundhouseSettings{
ConnectionString = connectionString,
SqlFilesDirectory = "Ecommerce\Scripts"});

As can be seen here:  https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/Roundhouse/RoundhouseRunner.cs

public void Run(RoundhouseSettings settings, bool drop = false)

**Comment by ferminmoli** [comment]
Thanks for your help @phillipsj

**Comment by patriksvensson** [comment]
Hmm, this feels like something that should be changed.

**Comment by ferminmoli** [comment]
@patriksvensson, yes I'm agree with you. I can't figure out how to extend roundhouse functionality to pass more parameters. At the moment I can only run a simple migration and a Drop database but whole roundhouse functionality is encapsulated inside cake classes.

**Comment by phillipsj** [comment]
@patriksvensson @ferminmoli I agree it isn't intuitive, but having separate commands prevents mistakes as far as drop.  I have been wanting to learn more about roundhouse and I don't mind adding the additional that is needed and making that change if you want.

**Comment by ferminmoli** [comment]
@phillipsj maybe it can be changed to accept manually parameters to take advantage of whole roundhouse functionality. I'm pretty sure that you have a better idea.

**Comment by phillipsj** [comment]
@ferminmoli  I will use some of the other implementations and post back and example for review.

**Comment by gep13** [comment]
@phillipsj thanks again for your contribution!
