### ISSUE TITLE
MoveDirectory alias

### ISSUE THREAD

**Issue by daveaglick** [cake-build/cake#1300]
There's several `MoveFile`/`MoveFiles` aliases which work great for moving and renaming files but no equivalent for directories. I propose a `MoveDirectory` alias that will move/rename a directory.

**Comment by gep13** [comment]
@daveaglick is this a duplicate? https://github.com/cake-build/cake/issues/260

**Comment by daveaglick** [comment]
So it is! I searched for "rename" before @patriksvensson pointed out that move semantics are equivalent. I'll close this and take a look at that issue.
