### ISSUE TITLE
Add DotCover Merge

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#1301]
Taken from #724

**Comment by devlead** [comment]
@mholo65 are you in a position to do a PR for this?

**Comment by mholo65** [comment]
@devlead Sure, but probably not til 0.17.0

**Comment by devlead** [comment]
@mholo65 perfect then I'll assign to you and set to v0.18.0 as target milestone.

**Comment by devlead** [comment]
@mholo65 just checking, will you be able to look at this in a near future or should we bump it to next release?

**Comment by mholo65** [comment]
@devlead I think I'll start looking into this soon. Should be quite straightforward.

**Comment by devlead** [comment]
Perfect 👍

**Comment by devlead** [comment]
@mholo65 just checking what's the current status of this PR?

**Comment by mholo65** [comment]
@devlead sorry, have been doing so much actual work lately that haven't had time and totally forgot about this..

Will try to find some spare time today or tomorrow and send a PR.

**Comment by devlead** [comment]
Superb, thank you. :+1:
