### ISSUE TITLE
Add support for InnoSetup

### ISSUE THREAD

**Issue by thomaslevesque** [cake-build/cake#1311]
Cake already supports WiX and NSIS, but InnoSetup is also a very popular setup tool.

**Comment by gep13** [comment]
@thomaslevesque I think this is a good idea. Would you be interested in creating a PR for this?

**Comment by thomaslevesque** [comment]
> Would you be interested in creating a PR for this?

Sure. I'll look at how it's implemented for NSIS, since NSIS and InnoSetup work in a very similar way.

**Comment by phillipsj** [comment]
@thomaslevesque If you need any assistance, just give a shout.

**Comment by thomaslevesque** [comment]
@phillipsj thanks, but it's mostly done already 😉
