### ISSUE TITLE
NUnit Multi-Assembly Support

### ISSUE THREAD

**Issue by RichiCoder1** [cake-build/cake#132]
Move NUnit from running multiple assemblies separately to running the all in on Run. This keeps result files from overriding each other, as well as reducing console output clutter.

**Comment by RichiCoder1** [comment]
Wanted to push out a note that this fix is alive and well. I just got back into town and will be updating/repushing my fixes.

**Comment by patriksvensson** [comment]
No hurry, the PR is waiting for you until you have time :smile:
