### ISSUE TITLE
NuGetRestore is failing for Universal Windows Platform.

### ISSUE THREAD

**Issue by soydachi** [cake-build/cake#1322]
### What You Are Seeing?

NuGetRestore fails for Universal Windows Platform.
### What is Expected?

Restore al nuget packages. This all works before fine.
### What version of Cake are you using?

0.16.2
### Are you running on a 32 or 64 bit system?

64 bit system
### What environment are you running on?  Windows? Linux? Mac?

Windows
### How Did You Get This To Happen? (Steps to Reproduce)

NuGetRestore(solutionPath.ToString());
### Output Log

``` sh
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.Common.targets(6,18): error MSB4086: Se intentó real
izar una comparación numérica en "$(TargetPlatformMinVersion)" que se evalúa como "10.0.10240.0" en lugar de un número, en la condición "
'$(TargetPlatformIdentifier)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVersion)' > '10.0.10587.0'". [C:\AAA.csproj]
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.Common.targets(6,18): error MSB4086: Se intentó real
izar una comparación numérica en "$(TargetPlatformMinVersion)" que se evalúa como "10.0.10240.0" en lugar de un número, en la condición "
'$(TargetPlatformIdentifier)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVersion)' > '10.0.10587.0'". [C:\AAA.csproj]
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.Common.targets(6,18): error MSB4086: Se intentó real
izar una comparación numérica en "$(TargetPlatformMinVersion)" que se evalúa como "10.0.10240.0" en lugar de un número, en la condición "
'$(TargetPlatformIdentifier)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVersion)' > '10.0.10587.0'". [C:\AAA.csproj]
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.Common.targets(6,18): error MSB4086: Se intentó real
izar una comparación numérica en "$(TargetPlatformMinVersion)" que se evalúa como "10.0.10240.0" en lugar de un número, en la condición "
'$(TargetPlatformIdentifier)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVersion)' > '10.0.10587.0'". [C:\AAA.csproj]
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.Common.targets(6,18): error MSB4086: Se intentó real
izar una comparación numérica en "$(TargetPlatformMinVersion)" que se evalúa como "10.0.10240.0" en lugar de un número, en la condición "
'$(TargetPlatformIdentifier)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVersion)' > '10.0.10587.0'". [C:\AAA.csproj]
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.Common.targets(6,18): error MSB4086: Se intentó real
izar una comparación numérica en "$(TargetPlatformMinVersion)" que se evalúa como "10.0.10240.0" en lugar de un número, en la condición "
'$(TargetPlatformIdentifier)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVersion)' > '10.0.10587.0'". [C:\AAA.csproj]
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.Common.targets(6,18): error MSB4086: Se intentó real
izar una comparación numérica en "$(TargetPlatformMinVersion)" que se evalúa como "10.0.10240.0" en lugar de un número, en la condición "
'$(TargetPlatformIdentifier)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVersion)' > '10.0.10587.0'". [C:\AAA.csproj]
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.Common.targets(6,18): error MSB4086: Se intentó real
izar una comparación numérica en "$(TargetPlatformMinVersion)" que se evalúa como "10.0.10240.0" en lugar de un número, en la condición "
'$(TargetPlatformIdentifier)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVersion)' > '10.0.10587.0'". [C:\AAA.csproj]
C:\Program Files (x86)\MSBuild\Microsoft\WindowsXaml\v14.0\Microsoft.Windows.UI.Xaml.Common.targets(6,18): error MSB4086: Se intentó real
izar una comparación numérica en "$(TargetPlatformMinVersion)" que se evalúa como "10.0.10240.0" en lugar de un número, en la condición "
'$(TargetPlatformIdentifier)' == 'UAP' And '$(TargetPlatformMinVersion)' != '' And '$(TargetPlatformMinVersion)' > '10.0.10587.0'". [C:\AAA.csproj]
```

**Comment by devlead** [comment]
Which version of nuget.exe do you have installed/in path/tools? UWP requires NuGet version 3.1 or later. Do you get this error locally or on a build system?

If you start Cake with diagnostic verbosity you'll see how nuget it's launched.

**Comment by dachibox** [comment]
I downloaded just the latest from here: [https://dist.nuget.org/index.html](https://dist.nuget.org/index.html)

But it still fails with the same error. In diagnostic mode we have this:

`An error occured when executing task 'Restore-Nuget-Packages'. Error: Cake.Core.CakeException: NuGet: Process returned an error (exit code 1).   en Cake.Core.Tooling.Tool 1.ProcessExitCode(Int32 exitCode)  en Cake.Core.Tooling.Tool 1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction)   en Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments)   en Cake.Common.Tools.NuGet.Restore.NuGetRestorer.Restore(FilePath targetFilePath, NuGetRestoreSettings settings)   en Cake.Common.Tools.NuGet.NuGetAliases.NuGetRestore(ICakeContext context, FilePath targetFilePath, NuGetRestoreSettings settings)   en Cake.Common.Tools.NuGet.NuGetAliases.NuGetRestore(ICakeContext context, FilePath targetFilePath)
   en Submission#0.<.ctor>b__8()   en Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass4_0.<Does>b__0(ICakeContext context)   en Cake.Core.ActionTask.Execute(ICakeContext context)
   en Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   en Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask task, CakeReport report)   en Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)   en Cake.Scripting.BuildScriptHost.RunTarget(String target)   en Submission#0..ctor(Session session, Object& submissionResult)   en Submission#0.<Factory>(Session session)   en Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String ath, DiagnosticBag diagnostics, Session session, Boolean isInteractive)
   en Roslyn.Scripting.Session.Execute(String code)
   en Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
   en Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   en Cake.Commands.BuildCommand.Execute(CakeOptions options)
   en Cake.CakeApplication.Run(CakeOptions options)
   en Cake.Program.Main()`

Thanks!

**Comment by gep13** [comment]
@dachibox just nuget restore work if you run it directly on the command line?  i.e. take Cake out of the equation for now.

**Comment by devlead** [comment]
@dachibox  also just before executing nuget.exe Cake should print out how nuget.exe is executed.

**Comment by augustoproiete** [comment]
Closing this due to no response from issue creator. Feel free to reopen if still relevant
