### ISSUE TITLE
 Cake.Core.IO.File is an internal class but it should be public

### ISSUE THREAD

**Issue by larzw** [cake-build/cake#1330]
For the current Cake source code Cake.Core.IO.File (https://github.com/cake-build/cake/blob/develop/src/Cake.Core/IO/File.cs#L10) is an **internal** class. Should it be a **public** class? The interface it implements (IFile) is a public interface, and Cake.Core.IO.File has public methods in it. Also, all the other classes under the namespace Cake.Core.IO are public classes. Well, except for Cake.Core.IO. Directory (https://github.com/cake-build/cake/blob/develop/src/Cake.Core/IO/Directory.cs#L12), is this a bug too?

I noticed this when I was trying to create a cake module and did not have access to the File class. The simple work around was to just create a new class that implements the IFile interface.

Thanks!

**Comment by devlead** [comment]
It's by design, in general they're depending on the IFileSystem implementation.

**Comment by devlead** [comment]
For an example you can see the [cake-contrib/Cake.LongPath.Module](https://github.com/cake-contrib/Cake.LongPath.Module)

**Comment by larzw** [comment]
👍 

Thanks for the quick response and link!
