### ISSUE TITLE
Using Linq in script

### ISSUE THREAD

**Issue by fleed** [cake-build/cake#1331]
Is it possible to use Linq queries in a cake script?

**Comment by devlead** [comment]
Yes that's fully supported.

It's just like in regular C# (it's using the Roslyn compiler, which is also used by .NET core i.e. , so basically any C# it supports should work)
```cake
var data = new [] {
    new { FirstName = "John", LastName = "Doe" },
    new { FirstName = "Jane", LastName = "Doe" }
};

var john = (
        from person in data
        where person.FirstName == "John"
        select person
    ).FirstOrDefault();

Information("John: {0}", john);


var jane = data.FirstOrDefault(person=>person.FirstName == "Jane");
Information("Jane: {0}", jane);

foreach(var firstName in data.OrderBy(person=>person.FirstName)
                            .Select(person=>person.FirstName))
{
    Information("FirstName: {0}", firstName);
}
```
this will output:

![image](https://cloud.githubusercontent.com/assets/1647294/19886023/eb03af62-a021-11e6-86a0-b62f513d7b65.png)

**Comment by fleed** [comment]
It works perfectly, without needing any additional directive.

**Comment by devlead** [comment]
Excellent 👍
