### ISSUE TITLE
Circumvent Encoding issue (error CS1002: ; expected)

### ISSUE THREAD

**Issue by pmiossec** [cake-build/cake#1334]
Note: That's more a trick about how to solve this issue than a real issue in cake (but I'm sure it will help a lot other cake users...)

I don't really explain why (and I think that I have this behaviour only with your website!) but often, when I copy some code from your reference documentation (I paste it in a UTF8 file), when I launch the cake script, I end up with the error:

    error CS1002: ; expected

It was already encounters by someone else in https://github.com/cake-build/cake/issues/586#issuecomment-164578777

I also saw 2 other guys having the issue months ago with differents text editors so it don't seems to be the problem. I had it myself with 2 different computers, 2 different text editors.

It seems that an invisible character is introduced after the last parenthesis.

And the ONLY way I found to delete it is to convert the file in another encoding (for me "Windows 1252") and save. Then the bad character appears like a '?' and could now be deleted. Save and convert back to Utf8.

Boring....

I never had such a problem other than with your website documentation, so I think that there is something to do but I don't understand well where the problem come from :(

**Comment by devlead** [comment]
Issue moved to [cake-build/website #211](https://github.com/cake-build/website/issues/211) via [**ZenHub**](https://www.zenhub.com/)

**Comment by m-sande** [comment]
I changed the running version from 0.33.0 to 0.35.0 and this issue went away.

In my case, further up the logs I could see different SDK's being called: https://github.com/cake-build/cake/issues/2546
