### ISSUE TITLE
Missing "params" in documentation

### ISSUE THREAD

**Issue by pmiossec** [cake-build/cake#1335]
If you look at this doc, http://cakebuild.net/api/cake.git/8654684f/66b43fe5, the `params` key word is missing and so the doc is misleading :(

It seems to be an issue with the generator...

/ cc @devlead (I don't know if I should create the issue here or in the https://github.com/WCOMAB/Cake_Git repository . But in the source code, it seems good: https://github.com/WCOMAB/Cake_Git/blob/master/src/Cake.Git/GitAliases.Remove.cs#L20 )

**Comment by devlead** [comment]
Params is an attribute, it's not related to the addin but rather the website documentation generation, so I'll move the issue to website repo.

**Comment by devlead** [comment]
Issue moved to [cake-build/website #215](https://github.com/cake-build/website/issues/215) via [**ZenHub**](https://www.zenhub.com/)
