### ISSUE TITLE
NuGetPack alias does not use the current build configuration

### ISSUE THREAD

**Issue by aateeque** [cake-build/cake#1337]
### What You Are Seeing?
`NuGet.CommandLineException:`  Unable to find '...\Debug\blah.exe'. Make sure the project has been built.

### What is Expected?
A nupkg with the exe using the csproj file

### What version of Cake are you using?
Version 0.16.2+Branch.main.Sha.fb23be463dacfa51c9b19a7cd111149dda7e8c6b

### Are you running on a 32 or 64 bit system?
64-bit

### What environment are you running on?  Windows? Linux? Mac?
Win7

### Are you running on a CI Server?  If so, which one?
Nope

### How Did You Get This To Happen? (Steps to Reproduce)
Cake script with:
 1 `MSBuild("slnFile", settings => settings.SetConfiguration("Release"))`
 2 `NugetPack(".csprojFilePath")`

Nuget Pack complains because the build directory was \Release not \Debug.  `NuGetPackSettings` should probably have a Configuration parameter

**Comment by gep13** [comment]
What I think you are looking for is this:

http://cakebuild.net/api/cake.common.tools.nuget.pack/88db3dc2/a6dc0c4e

As per the NuGet documentation here:

https://docs.nuget.org/ndocs/create-packages/creating-a-package#additional-options

**Comment by aateeque** [comment]
That's the one, thanks!!
