### ISSUE TITLE
Break the output of a single cake build step into multiple build output sections

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#1340]
@jnm2 commented on [Thu Nov 03 2016](https://github.com/cake-build/cake-vso/issues/33)

When you convert TFS build steps to Cake, you end up removing individual steps in TFS and replacing them with a single Cake step.

The single build step is nice but I don't want to give up the ability to see timings and sections of the build output for restoring nuget packages, for msbuild, for testing, and any other Cake targets.

**Comment by jnm2** [comment]
What would this take to accomplish? I can't find the conversation on this earlier.

**Comment by gep13** [comment]
@jnm2 I believe that @agc93 has the makings of "something" that can be used to provide this functionality.

**Comment by agc93** [comment]
@gep13 @jnm2 Yep, have something that will achieve this, need to brush up the documentation and I should be able to get an initial release out very soon.

**Comment by jnm2** [comment]
@agc93 Fantastic! I can hardly wait to use it! I don't care whether the log itself is split.

**Comment by agc93** [comment]
[Good news everyone!](https://media.giphy.com/media/3o7abA4a0QCXtSxGN2/giphy.gif) (but especially @jnm2 )

I've just published a module for improved support in CI environments, including TFS/VSTS, on NuGet: [Cake.BuildSystems.Module](https://www.nuget.org/packages/Cake.BuildSystems.Module/).

You can find the source [on GitHub](https://github.com/agc93/Cake.BuildSystems.Module) and instructions on installation and usage [in the README](https://github.com/agc93/Cake.BuildSystems.Module/blob/master/README.md). Report any issues you encounter using that module on that repo.

Hopefully, this solves your issue 😄

**Comment by jnm2** [comment]
Thanks @agc93! You rock!

**Comment by gep13** [comment]
@jnm2 let us know what you think about the above, and whether you think this issue can be closed.  Thanks!

**Comment by jnm2** [comment]
This can be closed. I'll get to try this out tomorrow and I'll follow up in that repo if I have any issues.

**Comment by jnm2** [comment]
Before I open an issue actually, I was expecting the sections to stay separated like that even when the build finishes or errors. Right now while the build is running the sections and timings are available, but as soon as it stops it's as though there was no integration. Can you clarify, is that not possible due to not being able to split the log?

**Comment by jnm2** [comment]
Oh, my bad! It does work. TFS switches to Timeline view when I click the Cake node when it's running and it switches to Log view when I click the Cake node when it's stopped.
