### ISSUE TITLE
Cake's default tools / addins / modules paths are not so default as they seem.

### ISSUE THREAD

**Issue by nalla** [cake-build/cake#1344]
### What You Are Seeing?
Cake ist installing addins / tools and modules *not* relative to the build script.

### What is Expected?
Cake should install addins / tools and modules relative to the build script - per default configuration.

### What version of Cake are you using?
16.0.2

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)

```PowerShell
$> cd C:\
$> New-Item -Type Directory repo
$> cd repo
$> nuget install Cake -ExcludeVersion -OutputDirectory .\tools\foo
$> "#addin Cake.FileHelpers" > cake.build
$> .\tools\foo\Cake\Cake.exe .\cake.build
$> ls .\tools

    Directory: C:\repo\tools

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       04.11.2016     17:06                foo

$> ls .\tools\foo

    Directory: C:\repo\tools\foo

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       04.11.2016     17:07                Addins
d-----       04.11.2016     17:07                Cake
```

### What is Expected?

```
$> ls .\tools

    Directory: C:\repo\tools\foo

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----       04.11.2016     17:07                Addins
d-----       04.11.2016     17:07                foo
```

**Comment by nalla** [comment]
As already noted in the PR, only the addins folder was affected.

**Comment by devlead** [comment]
fixed by #1348

**Comment by RehanSaeed** [comment]
I'm trying to change the cake tools folder. I've changed this line in my `build.ps1` to point to a `cake-tools` folder:

```
$TOOLS_DIR = Join-Path $PSScriptRoot "cake-tools"
```

However, NuGet addins are still downloaded to a `tools` folder. Will this PR fix that?

**Comment by devlead** [comment]
Cake's default folders can be changed thru configuration, read more about it at
http://cakebuild.net/docs/fundamentals/configuration

You can read more about the default values and how to override then at
http://cakebuild.net/docs/fundamentals/default-configuration-values
