### ISSUE TITLE
How to use C# Wix in my cake script?

### ISSUE THREAD

**Issue by vadivel1234** [cake-build/cake#1347]
I have a server machine in which i didn't installer Wix Toolset software. Instead included the Wix nuget in my cake script. What are the steps that i have to follow to compile my wix file?

Whether the wix nuget package included in cake will automatically download and install the wix in my server machine? Or else what i have to follow?

1)  64 bit system

2) Windows Server 2012 R2

3) CI Server.

**Comment by patriksvensson** [comment]
@vadivel1234 GitHub issues is for issues within Cake and not questions. I would suggest that you ask questions on StackOverflow using the `cakebuild` tag, or visit our [Gitter chatrom](https://gitter.im/cake-build/cake).
