### ISSUE TITLE
Add support for importing namespaces at the assembly level

### ISSUE THREAD

**Issue by kcamp** [cake-build/cake#1352]
It would be useful to provide the ability to import namespaces in a global way at the assembly level. 

When creating an add-in library, there are namespaces that are desirable to be imported at a global level as opposed to decorating classes/methods in a redundant way, particularly when the classes within those namespaces are used from integration points that _aren't_ an alias method.   i.e., I have a base `BuildParameters` style class that exposes a certain amount of logic to the build script, but doesn't actually involve any method aliases.

Will submit PR for the same shortly.

**Comment by devlead** [comment]
Fixed by #1353

**Comment by gep13** [comment]
@kcamp I think we could benefit with some documentation to go along with this change.  Would you be in a position to help with this?

**Comment by kcamp** [comment]
@gep13 i can absolutely lend a hand with this.  this would be under the cake-build/website project?  existing page/content or new?

**Comment by gep13** [comment]
Yew, this would be on the website repo. Off the top of my head, not sure if there is an existing place for this or not. If not, then yes, a new page, and perhaps new group.

**Comment by kcamp** [comment]
@gep13 sounds good.  i will make a pass at it and see what we can come up with.

**Comment by devlead** [comment]
@kcamp @gep13 this would be under
http://cakebuild.net/docs/contributing/documentation
