### ISSUE TITLE
Remove suppression of StyleCop rule SA1633

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#1357]
Will make sure that the header text is correct in each file (which it isn't at the moment).

**Comment by gep13** [comment]
http://stylecop.soyuz5.com/SA1633.html

**Comment by gep13** [comment]
That is perhaps the old rule documentation, which expected the header text to contain a specific format, i.e copyright tag, etc.

Is that still the case with the new Roslyn Based StyleCop Analyzers?

Or can we specify exactly what it should contain?

**Comment by patriksvensson** [comment]
@gep13 Yes. I just tried it. Almost all headers in Cake.Core are wrong.

**Comment by patriksvensson** [comment]
@gep13 
![image](https://cloud.githubusercontent.com/assets/357872/20258430/ea0a3602-aa4f-11e6-9b2e-736f95a83803.png)

**Comment by gep13** [comment]
Oops! 😄 

Good catch!

**Comment by patriksvensson** [comment]
@gep13 There is also a setting in `stylecop.json` that tells StyleCop Analyzer if it's the old XML headers or not.

**Comment by gep13** [comment]
>@patriksvensson said...
@gep13 There is also a setting in stylecop.json that tells StyleCop Analyzer if it's the old XML headers or not.

Noice! Seems like they have certainly thought about this.

**Comment by patriksvensson** [comment]
@gep13 We could do that ourselves by adding a `\n\n` to the end of the header definition.

**Comment by gep13** [comment]
>@patriksvensson said...
@gep13 We could do that ourselves by adding a \n\n to the end of the header definition.

Yip, that makes sense!

**Comment by gep13** [comment]
@patriksvensson thanks for adding this in! 😄
