### ISSUE TITLE
Cake when Visual Studio Mac is installed == boom (due to bundling Mono.CSharp)

### ISSUE THREAD

**Issue by ghuntley** [cake-build/cake#1368]
See discussion over at https://twitter.com/GeoffreyHuntley/status/799393862846324736

Repro: 

- Install Xamarin Studio Stable on macOS Sierra (or any OSX really)
- Run https://github.com/ghuntley/appstore-automation-with-fastlane
- 🎉 
- Install Visual Studio for Mac on macOS Sierra (or any OSX really)
- Run https://github.com/ghuntley/appstore-automation-with-fastlane
- 💥 

Upstream change that triggered this behaviour:

https://github.com/mono/mono/commit/5da8cfe05df331723584997bb9bbc6ac961c12d4

**Comment by akoeplinger** [comment]
I'll talk to a few people tomorrow, but as it is right now there's a coupling between Mono.CSharp.dll and Microsoft.CSharp.dll on Mono so mixing and matching isn't going to work (or only if you're lucky).

**Comment by akoeplinger** [comment]
To be clear: this has nothing to do with VS for Mac, it's rather in the Mono 4.8 that comes with it.

**Comment by patriksvensson** [comment]
@ghuntley @akoeplinger We are willing to make changes to make this work for you. Suggestions are very welcome (ping @cake-build/team)

**Comment by devlead** [comment]
Is 4.8 RTM? Does Roslyn scripting work with 4.8? If so perhaps finally time to drop Mono scripting and unify around one engine.

**Comment by patriksvensson** [comment]
@devlead Excellent thinking. That would solve a lot of other problems as well.

**Comment by akoeplinger** [comment]
Mono 4.8 is currently in the alpha channel and will ship sometime later this year. If Roslyn scripting works then that'd be a good solution, though we did make a lot of stability fixes in Mono master as part of our move to Roslyn which is currently a work in progress (so those fixes won't show up in 4.8, whether that impacts you or not is hard to say).

We discussed a few workarounds that might work for you:

- add `<probing>` to app.config and move Mono.CSharp.dll into a subdirectory, it should then fail when you use a backslash in the probing path on Unix and load the version from the GAC.
- ILMerge Mono.CSharp.dll
- Compile your own version of Mono.CSharp.dll e.g. Mono.CSharp.Private.dll
- Bundle mcs.exe and reference that. Mono.CSharp.dll is basically the mcs.exe source code in .dll form: https://github.com/mono/mono/blob/master/mcs/class/Mono.CSharp/Mono.CSharp.dll.sources.

It all boils down to getting rid of Mono.CSharp.dll 😄

**Comment by akoeplinger** [comment]
We decided to implement a workaround that would make this scenario not break:
https://github.com/mono/mono/commit/26c17a5b0f2c043a4bbccce2861b815492ad3aa2

It will be available in Mono 4.8.0.383 and later.

**Comment by devlead** [comment]
Ah cool, thanks for getting back to us @akoeplinger 👍

**Comment by ghuntley** [comment]
![image](https://user-images.githubusercontent.com/127353/27109757-1f5938c8-50e8-11e7-8171-826a60c992b0.png)
