### ISSUE TITLE
Support for uninstall packages using Chocolatey

### ISSUE THREAD

**Issue by mvput** [cake-build/cake#1377]
Add support for uninstalling packages using chocolatey. Currently there is no support for this. The case is to install tools using chocolatey during the build and uninstall when the build finishes to keep the build environment as clean as possible.

**Comment by phillipsj** [comment]
@gep13 I can take this one if that works for you.

**Comment by gep13** [comment]
@phillipsj sure thing, happy for you to take this.

**Comment by devlead** [comment]
Fixed by #1390
