### ISSUE TITLE
Bootstrapper (build.ps1) restricts the build configuration to either "Release" or "Debug"

### ISSUE THREAD

**Issue by paulomorgado** [cake-build/cake#1385]
Is there a reason for this, since the  build configuration can be anything the user wants it to be.

**Comment by patriksvensson** [comment]
The bootstrapper is meant to be a starting point, so feel free to add new configurations to your bootstrapper as you see fit.

**Comment by patriksvensson** [comment]
@paulomorgado Closing this issue, but feel free to reopen it if you need some clarification or you got other questions.
