### ISSUE TITLE
Add CakeNamespaceImport for BuildSystem Aliases

### ISSUE THREAD

**Issue by phillipsj** [cake-build/cake#1386]
The following build system aliases do not have the CakeNamespaceImport attribute:

- TeamCity
- MyGet
- Bamboo

**Comment by phillipsj** [comment]
Pull request will be coming shortly.

**Comment by gep13** [comment]
@phillipsj thanks for adding this! :+1:

**Comment by devlead** [comment]
Fixed by #1387
