### ISSUE TITLE
PowerShell bootstrap script not working with PS 6

### ISSUE THREAD

**Issue by kentcb** [cake-build/cake#1393]
### What You Are Seeing?

When running the [bootstrap script](https://github.com/cake-build/example/blob/master/build.ps1) on PowerShell 6 (.NET core):
```
Method invocation failed because [System.Reflection.Assembly] does not contain a method named 'LoadWithPartialName'.
At C:\XXX\build.ps1:58 char:1
+ [Reflection.Assembly]::LoadWithPartialName("System.Security") | Out-N ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : MethodNotFound
```

`$PSVersionTable.PSVersion` gives me:

```
Major Minor Patch Label
----- ----- ----- -----
    6     0     0 alpha
```

### What is Expected?

Script should work with new versions of PS.

### What version of Cake are you using?

Haven't gotten that far yet (bootstrapping).

### Are you running on a 32 or 64 bit system?

64 bit.

### What environment are you running on?  Windows? Linux? Mac?

Windows 10, but the same behavior _should_ be present on other operating systems.

### Are you running on a CI Server?  If so, which one?

No

### How Did You Get This To Happen? (Steps to Reproduce)

1. Grab the bootstrap script
2. Attempt to execute it in a PS 6 session

### Output Log

N/A

**Comment by gep13** [comment]
Issue moved to [cake-build/resources #21](https://github.com/cake-build/resources/issues/21) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gep13** [comment]
@kentcb thank you for raising this.  I am moving this to the resources repo, as that is where the bootstrappers live, and if there is a problem, that is where it should be addressed.
