### ISSUE TITLE
Extend the ICakeEnvironment to contain the PathComparer

### ISSUE THREAD

**Issue by nalla** [cake-build/cake#1394]
As [discussed on Gitter](https://gitter.im/cake-build/cake?at=582972d188fa21d53c1b8ca7) the `ICakeEnvironment` could provide the environment specific `PathComparer` as an easy to use property. The comparer can then be accessed in a cake script just by calling

```c#
var filtered = GetFiles(./**/*.*).Distinct( Conext.Environment.PathComparer );
```

**Comment by gep13** [comment]
@nalla thank you for raising this, but at this time, we don't think that this is required.

Comment from PR:

>@patriksvensson said...
Consumers could always use the PathComparer.Default to get the default path comparer for the environment they're on.

As a result, we have decided to close this issue.

Please feel free to re-open this issue if further discussion is required.
