### ISSUE TITLE
Remove obsoleted DNU aliases

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#1396]
DNU tooling Been obsoleted for a few versions, time to remove it from Cake.Common

I'll send an PR shortly.

**Comment by gep13** [comment]
We should add an issue on the website repo as well to document this as well.  I think a new section here: http://cakebuild.net/docs would be required where we can list what has been obsoleted (and in what version), as well as when it was ultimately removed.

**Comment by devlead** [comment]
Fixed by #1397
