### ISSUE TITLE
Support for dotCover configuration file

### ISSUE THREAD

**Issue by matkoch** [cake-build/cake#1401]
As described in the [help](https://www.jetbrains.com/help/dotcover/2016.2/dotCover__Console_Runner_Commands.html#cover), dotCover can also be called with a `configuration file`:

    dotCover cover <configuration file name> [parameters]

I guess this is especially interesting for specifying filters. Since they might be reused from within the IDE at some point.

**Comment by gep13** [comment]
@matkoch this sounds like a very useful addition. Are you interested in sending a PR to implement this?

**Comment by mholo65** [comment]
Quickly checking, the settings param should be added to the abstract DotCoverSettings class and make it available to all DotCover aliases.

If @matkoch is not in a position to send a PR, I could send one when I have time (beginning of January)..

**Comment by B3nCr** [comment]
Did anyone do anything with this? I'm guessing not as I can't see it.

**Comment by gep13** [comment]
@B3nCr no, not that I am aware of.  We would be happy to accept a PR if this is something you are interested in seeing getting added.

**Comment by AdaskoTheBeAsT** [comment]
I already added PR
@gep13 could you please review my changes?

**Comment by asci13** [comment]
This would be great to have, is there any news on merging the PR?

**Comment by devlead** [comment]
@asci13 Looks like issuer closed the PR #2108, and a new one hasn't been opened. Unsure if it's up for grabs or if @AdaskoTheBeAsT is planning to open a new PR.

**Comment by gep13** [comment]
@devlead the source branch is still there, I "think" it just needs another rebase.  I was actually just away to look into it...   Will report back on what I find.

**Comment by gep13** [comment]
Doh!  Looks like @AdaskoTheBeAsT hasn't allowed pushing back to his repository.  So even though I have rebased the changes onto the latest develop branch, I can't push them back to his repo.  I could rebase/merge directly, but we would lose the CI checks prior to merging 😢

**Comment by devlead** [comment]
Permission disappeared when PR closed, unfortunately GitHub won't allow you to reopen a PR , you could push branch to your personal repo and open new PR, original issuer would still get attribution for the commit.

**Comment by gep13** [comment]
@devlead interesting idea.  I will see what I can do over lunch time.

**Comment by AdaskoTheBeAsT** [comment]
Hi I found some time on vacation to properly rebase branch and squash - now in pull https://github.com/cake-build/cake/pull/2213
