### ISSUE TITLE
Add optional Go.CD Server URL Parameter to GetHistory

### ISSUE THREAD

**Issue by RehanSaeed** [cake-build/cake#1403]
Raised this PR https://github.com/cake-build/cake/pull/1402

A small tweak to the Go.CD GetHistory function to allow you to optionally set a custom GO.CD server URL. This is useful if your URL is different from the default (This can happen if you have used non-standard settings, the environment variable is not always correct sadly).

**Comment by gep13** [comment]
@RehanSaeed this issue has now been resolved, as your PR has been merged.  Thanks for your contribution!
