### ISSUE TITLE
Using Globber on a specific directory

### ISSUE THREAD

**Issue by fleed** [cake-build/cake#1410]
I'm writing a custom cake extension. How could I use glowing search patterns (`**/*.exe` for instance) to search in a specific directory?

If I use `ICakeContext.Globber.GetFiles()` I'm searching in the current directory. And if I get the `IDirectory`, I can only use *standard* search pattern and I'd need to specify the `SearchOptions` as parameter. Anyway, my goal is to give the possibility to configure the search using glowing patterns.

**Comment by devlead** [comment]
Well your cake alias will have an context as first parameter so you can use that to invoke GetFiles, so you could do something like below if you have the correct usings.
```csharp
DirectoryPath path = context.MakeAbsolute(context.Directory("/temp/priv"));
var files = context.GetFiles($"{path}/**/*.exe");
```

**Comment by fleed** [comment]
This solution works as expected
