### ISSUE TITLE
Support for running dotnet ef commands

### ISSUE THREAD

**Issue by Meir017** [cake-build/cake#1421]
I would like to be able to run dotnet ef commands.

to be used for integration tests.

````csharp
Task("Run-Tests")
    .Does(() =>
    {
        // create database
        DotNetCoreEfDatabaseUpdate();

        DotNetCoreTest();

        // drop database
        DotNetCoreEfDatabaseDrop(new DotNetCoreEfDatabaseSettings
        {
            Force = true
        });
    });
````

**Comment by mvput** [comment]
Do you need some  specific commands, or all the commands? There are quite a few commands for dotnet ef.

**Comment by mvput** [comment]
I'm able to build support for the most commonly used commands of dotnet ef as this seems the best option to begin with.

**Comment by gep13** [comment]
@mvput are you planning on approaching this as a PR into this repo, or as a standalone addin?

**Comment by patriksvensson** [comment]
@gep13 @mvput I think an addin would be the best option to start with (as always).

**Comment by mvput** [comment]
First version is release with support for database drop and database update commands. https://github.com/cake-contrib/Cake.DotNetCoreEf/releases/tag/0.1.0

**Comment by gep13** [comment]
@mvput great news! I think we can go ahead and close this issue.
