### ISSUE TITLE
XBuildRunner#GetToolExecutableNames returning wrong executables

### ISSUE THREAD

**Issue by bspinner** [cake-build/cake#1427]
I've noticed, in the code for XBuildRunner are wrong executable names. Looks like some error due to copy&paste.

https://github.com/cake-build/cake/blob/a49462f9cd812a13255122220f9a4b954ea829b4/src/Cake.Common/Tools/XBuild/XBuildRunner.cs#L134

My Pull Request #1425 fixes this.

**Comment by devlead** [comment]
Fixed by #1425
