### ISSUE TITLE
Teach XmlPeek to silence warnings, if needed

### ISSUE THREAD

**Issue by nalla** [cake-build/cake#1438]
The current implementation of the `XmlPeek` alias throws a warning if it cannot find the requested `XPath`. While this is a good thing, there are those situations where could guess multiple values inside the given xml file. In those situations it would be pleasant if one could silence those warnings.

E.g.

```c#
Task( "ConsistencyCheck" )
	.Does( () =>
{
	bool consistent = true;

	Parallel.ForEach( GetFiles( "./src/**/packages.config" ), file =>
	{
		foreach( var dependency in GetDependencies() )
		{
			string version = XmlPeek( file, "/packages/package[@id='" + dependency.Id + "']/@version" );

			if( string.IsNullOrWhiteSpace( version ) )
				continue;

			if( version != dependency.Version )
			{
				Error( "You are using v" + version + " in " + file + " instead of v" + dependency.Version );
				consistent = false;
			}
		}
	} );

	if( !consistent )
		throw new Exception("Found at least one invalid consistency." );
} );
```

would be such a situation.

See https://gitter.im/cake-build/cake?at=58761aebcbcb28177055fb83 for a gitter reference.

**Comment by devlead** [comment]
Fixed by #1440
