### ISSUE TITLE
Nuget aliases not on the dsl site

### ISSUE THREAD

**Issue by stefandevo** [cake-build/cake#1443]
On http://cakebuild.net/dsl the Nuget aliases are missing from the left navigation bar.
Basically there is no link to http://cakebuild.net/api/cake.common.tools.nuget and http://cakebuild.net/api/cake.common.tools.nuget/bdfa6572

**Comment by gep13** [comment]
Issue moved to [cake-build/website #244](https://github.com/cake-build/website/issues/244) via [**ZenHub**](https://www.zenhub.com/)

**Comment by devlead** [comment]
@stefandevo yes known issure, an addin used same category and that manifested an bug in the code. We' rereving the site so hopefully it gets sorted soon.

**Comment by stefandevo** [comment]
Ok thanks!
