### ISSUE TITLE
Documentation issue for DotNetTest alias

### ISSUE THREAD

**Issue by andycmaj** [cake-build/cake#1446]
### What You Are Seeing?
http://cakebuild.net/api/cake.common.tools.dotnetcore/df2c8647/4bb6f2e8

![cakedocs](https://cloud.githubusercontent.com/assets/97470/21871362/86e87ed6-d816-11e6-933c-e219c88a1fd2.png)

### What is Expected?
Expect `DotNetTest` example instead of `DotNetRun`. Looks liek copy-paste error.

**Comment by phillipsj** [comment]
I can take this one, unless the OP wants it.

**Comment by mvput** [comment]
This is already fixed with #1434
