### ISSUE TITLE
Restore-NuGet-Packages always looking for  'Microsoft.Build, Version=14.0.0.0'

### ISSUE THREAD

**Issue by fals** [cake-build/cake#1449]
Cake is always looking for MSBuild 14.0.0 when I do restore my Nuget-Packages. How can I change It to use MSBuildToolVersion.VS2013?

### What You Are Seeing?

Error when the Restore Nuget Package block runs. When I take out this step from the code Build runs.

### What is Expected?

I expect that the Restore step works.

### What version of Cake are you using?
0.17.0

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 7

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)

build.ps1

### Output Log
```
========================================
Restore-NuGet-Packages
========================================
Executing task: Restore-NuGet-Packages
Failed to load msbuild Toolset
  Não foi possível carregar arquivo ou assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f
5f7f11d50a3a' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.
An error occurred when executing task 'Restore-NuGet-Packages'.
Error: NuGet: Process returned an error (exit code 1).
```

**Comment by patriksvensson** [comment]
@fals You will need to download an earlier version of NuGet.exe in your bootstrapper.

**Comment by fals** [comment]
@patriksvensson  What do you mean? I already have the latest version installed on my Visual Studio 2013.

![image](https://cloud.githubusercontent.com/assets/3750960/21892617/da01f342-d8be-11e6-873c-08ecfdee9a24.png)

**Comment by devlead** [comment]
You can also specify msbuild version to the nuget.exe with `-MSBuildVersion` arg.

**Comment by devlead** [comment]
You can set this via NuGetRestoreSettings
http://cakebuild.net/api/cake.common.tools.nuget.restore/71880157
passed to the restore command
http://cakebuild.net/api/cake.common.tools.nuget/bdfa6572/256fc700

**Comment by fals** [comment]
@devlead I changeg my build.cake file to setup the NuGetRestoreSettings as you suggested, but got the same error.

```
Task("Restore-NuGet-Packages")
    .IsDependentOn("Clean")
    .Does(() =>
{
    NuGetRestore("./SIGOP.sln", new NuGetRestoreSettings { MSBuildVersion = NuGetMSBuildVersion.MSBuild12 });
});
```

**Comment by patriksvensson** [comment]
@fals What is the path to NuGet that is used? You can run Cake with diagnostic verbosity to see the call to NuGet when restoring packages.

**Comment by fals** [comment]
@patriksvensson I did what you said, It's using the nuget from the tools folder as you can see below:

```
========================================
Restore-NuGet-Packages
========================================
Executing task: Restore-NuGet-Packages
Executing: "D:/Repository/SEST_SENAT/src/Development/Api/tools/NuGet.exe" restore "D:/Repository/SEST_SENAT/src/Developm
ent/Api/SIGOP.sln" -MSBuildVersion 12 -NonInteractive
Failed to load msbuild Toolset
  Não foi possível carregar arquivo ou assembly 'Microsoft.Build, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f
5f7f11d50a3a' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.
An error occurred when executing task 'Restore-NuGet-Packages'.
Error: Cake.Core.CakeException: NuGet: Process returned an error (exit code 1).
   em Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode)
   em Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings
, Action`1 postAction)
   em Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments)
   em Cake.Common.Tools.NuGet.Restore.NuGetRestorer.Restore(FilePath targetFilePath, NuGetRestoreSettings settings)
   em Cake.Common.Tools.NuGet.NuGetAliases.NuGetRestore(ICakeContext context, FilePath targetFilePath, NuGetRestoreSetti
ngs settings)
   em Submission#0.<.ctor>b__2()
   em Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass5_0.<Does>b__0(ICakeContext context)
   em Cake.Core.ActionTask.Execute(ICakeContext context)
   em Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   em Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask
task, CakeReport report)
   em Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   em Cake.Scripting.BuildScriptHost.RunTarget(String target)
   em Submission#0..ctor(Session session, Object& submissionResult)
   em Submission#0.<Factory>(Session session)
   em Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session sessio
n, Boolean isInteractive)
   em Roslyn.Scripting.Session.Execute(String code)
   em Cake.Scripting.Roslyn.Stable.DefaultRoslynScriptSession.Execute(Script script)
   em Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   em Cake.Commands.BuildCommand.Execute(CakeOptions options)
   em Cake.CakeApplication.Run(CakeOptions options)
   em Cake.Program.Main()
```

**Comment by devlead** [comment]
What's the version if you execute that nuget.exe manually?

You should see something like:
![image](https://cloud.githubusercontent.com/assets/1647294/21893192/5d47a40c-d8da-11e6-8031-af5a4856a3ea.png)

**Comment by patriksvensson** [comment]
@fals So the NuGet that is used is in your tools folder, downloaded by the bootstrapper. You might want to change it to use an older version of NuGet.exe if you can't get it to work.

**Comment by devlead** [comment]
Available nuget versions can be found here:
https://dist.nuget.org/index.html

**Comment by fals** [comment]
@patriksvensson and @devlead I'm trying to change the NuGet.exe, I have it at the root of the solution, because I enabled NuGet package restore, but It's not working. Which parametter I should set?

```
 NuGetRestore("./SIGOP.sln", new NuGetRestoreSettings { 
        MSBuildVersion = NuGetMSBuildVersion.MSBuild12,
        ToolPath = "./nuget" <------------- is this right? 
    });
```

**Comment by fals** [comment]
Also I noticed, the Enable Package Restore from VS 2013 creates the .nuget buuuut... It's the v3.5:

![image](https://cloud.githubusercontent.com/assets/3750960/21893999/bd05f44a-d8c4-11e6-8aa5-cd487be49c56.png)

I will look for how to use the v2.12

**Comment by fals** [comment]
@patriksvensson and @devlead  I did solve the issue. I had to download the v2.xx of NuGet.exe and place somewhere with the solution. Now the restore works using the legacy version of NugetPackage. One thing, the  **MSBuildVersion = NuGetMSBuildVersion.MSBuild1**, doesn't work with NuGet v2.

Thank you for the help!

^^

**Comment by patriksvensson** [comment]
@fals Glad you got it working 😄

**Comment by Gudahtt** [comment]
I'm having this problem as well, with NuGet `3.5.0.1938`. I see the same problem when trying to call NuGet.exe directly with `-MSBuildVersion 12`

It works fine with NuGet v3.4.4. It looks like this was broken in NuGet v3.5.

**Comment by devlead** [comment]
If so I suggest yo raise an issue at [nuget/home](https://github.com/nuget/home/issues) and reference this issue.

**Comment by Gudahtt** [comment]
Yep, will do! Doing a bit more investigation first.

**Comment by Gudahtt** [comment]
Seems to work fine if I build the NuGet client from their development branch. Must have been fixed in v4.
