### ISSUE TITLE
Logging throws exception when there are curly braces in the string

### ISSUE THREAD

**Issue by dassie** [cake-build/cake#1455]
### What You Are Seeing?
The following line causes an exception saying "Input string was not in a correct format."
`Information("{Bon}jour");`

Output
```
========================================
Dummy-Task
========================================

An error occurred when executing task 'Dummy-Task'.
Error: Input string was not in a correct format.
```

### What is Expected?
Intuitively, I would expect the logging functions to not call into String.Format if the second argument is not passed in. Unlike the line of code above, the following doesn't cause any issues.
`Console.WriteLine("{Bon}jour");`

### What version of Cake are you using?
Version 0.17.0-beta.1+0.Branch.release/0.17.0.Sha.edc3cfda2d70f30acd59ba2092162ebe83482588

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### Output Log

GIST LINK - Please create a gist and link to that gist here

OR

~~~sh
PLACE LOG CONTENT HERE
~~~

**Comment by devlead** [comment]
It's a tokenized string(like i.e. string.Format), change from `Information("{Bon}jour");` to `Information("{0}", "{Bon}jour");` and it'll work with out issue.

**Comment by dassie** [comment]
Ah I see, I just assumed it called into String.Format because the exception messages are the same.

Anyway, thanks for the workaround. I just think the behavior should be more akin to Console.WriteLine which most C# programmers are used to.

**Comment by dassie** [comment]
Note: it also makes it safer to print arbitrary strings to the log (having to always use `Information("{0}", myString);` for safety isn't very clean).

**Comment by devlead** [comment]
Adding `Information(object value)` extension method that called `Information("{0}", value);` would probably solve this issue.

**Comment by dassie** [comment]
Yeah, that would be perfect. Probably not a high priority thing, but something to consider for the future.

**Comment by devlead** [comment]
@dassie submitted PR #1456 with suggested fix.

**Comment by patriksvensson** [comment]
@devlead System.Format will throw the exact same exception if I'm not incorrect... You need to escape braces.

**Comment by devlead** [comment]
@patriksvensson Yes, but PR doesn't use string.Format, it merely adds two overloads so if only 1 arg it's passed to the value part of log write. Same as console.writeline does. IncludeD integration test that used issuers string without issue.

**Comment by patriksvensson** [comment]
@devlead Ok, go for it.

**Comment by devlead** [comment]
Did it yesterday #1456
