### ISSUE TITLE
NUnitSettings does not have X86 property

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#1466]
Unlike NUnit3Settings, NUnitSettings does not have an `X86` property, so there is no way to specify that NUnit tests should run in x86 mode.

**Comment by gep13** [comment]
@flcdrg are you in a position to submit a PR to correct this?

For now, you should be able to use ArgumentCustomization to add the required additional parameters to the tool.

**Comment by patriksvensson** [comment]
@flcdrg There is one: http://cakebuild.net/api/Cake.Common.Tools.NUnit/NUnit3Settings/B4C75865

**Comment by gep13** [comment]
@patriksvensson that is `NUnit3Settings`.  The issue here is for `NUnitSettings`

**Comment by patriksvensson** [comment]
@gep13 Ah, I misread.

**Comment by flcdrg** [comment]
I probably can.

Yes, I since noticed ArgumentCustomization as another option, and also
found some comments on Gitter about someone using the NUnit3 with the
Driver package.

**Comment by flcdrg** [comment]
@gep13 Actually using ArgumentCustomization wouldn't work for this, as you need to run a different test runner, rather than just pass in different arguments.

PR submitted, comments welcome :-)

**Comment by devlead** [comment]
Fixed by #1468
