### ISSUE TITLE
XML examples are broken in XmlPoke docs

### ISSUE THREAD

**Issue by molehillrocker** [cake-build/cake#1467]
### What You Are Seeing?
XML examples are broken in the XmlPoke docs, because they are not visible. Instead of the XML content, ``]]>`` is printed (see image).

![image](https://cloud.githubusercontent.com/assets/7221361/22196095/b3166642-e14b-11e6-8053-35b6fd892389.png)

However, the XML content is available in the DOM, so it seems to be an issue with unmatched HTML tags or something.

### What is Expected?
Readable XML examples.

### What version of Cake are you using?
None, it's on the documentation page: http://cakebuild.net/api/Cake.Common.Xml/XmlPokeAliases/A9DB73CD

### Are you running on a 32 or 64 bit system?
Not relevant.

### What environment are you running on?  Windows? Linux? Mac?
Not relevant.

### Are you running on a CI Server?  If so, which one?
Not relevant.

### How Did You Get This To Happen? (Steps to Reproduce)
I navigated to http://cakebuild.net/api/Cake.Common.Xml/XmlPokeAliases/A9DB73CD in my browser.

### Output Log
Not relevant.

**Comment by devlead** [comment]
Issue moved to [cake-build/website #270](https://github.com/cake-build/website/issues/270) via [**ZenHub**](https://www.zenhub.com/)
