### ISSUE TITLE
Mac OSX is not properly detected when running on Mono

### ISSUE THREAD

**Issue by Redth** [cake-build/cake#1469]
### What You Are Seeing?
`Environment.Platform.Family` returns `PlatformFamily.Linux` when running cake under mono on MacOS.

### What is Expected?
It should return `PlatformFamily.OSX`

### What version of Cake are you using?
0.17

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Mac

This should be fixed with PR #1465

**Comment by gep13** [comment]
@Redth thank you!

**Comment by devlead** [comment]
Fixed by #1465
