### ISSUE TITLE
Retry Helper

### ISSUE THREAD

**Issue by RichiCoder1** [cake-build/cake#147]
It's a small thing, but I wondered if there'd be any interest in a general utility helper that allows you to retry an action if it fails, multiple times.

https://gist.github.com/RichiCoder1/6a20333202a3003e5d36

I've used it for the clean and delete directory methods specifically, as sometimes they fail due to the nature of how files are deleted. (Marked deleted, but not actually removed, resulting in parent directories to not allow deletion once a blue moon)

**Comment by patriksvensson** [comment]
Sure, I can see a use for this :smile: 
Would also be nice to be able to set a delay as well between retries.

**Comment by devlead** [comment]
Indeed, the Microsoft Transient Fault Handling Application Block has some good patterns with its retrying policies
http://msdn.microsoft.com/en-us/library/hh680899(v=PandP.50).aspx

**Comment by RagingKore** [comment]
Have a look at Polly https://github.com/michael-wolfenden/Polly
It seems a perfect fit.
I can even volunteer for this, but I'm trying to finish Cake.Topshelf :)

**Comment by RichiCoder1** [comment]
Polly may be the answer for this if we don't need something built in. I haven't tried, but due to Polly's singleton nature, I would imagine that `#addin Polly` would work.

**Comment by RichiCoder1** [comment]
Thinking I'm going to do both. I have a resilient retry helper which should cover most cases, and then people can pull in Polly (which doesn't actually need an addon and can be directly referenced) if they need more power.

**Comment by jrnail23** [comment]
After experimenting a bit with Polly, I think it's got a lot to offer, and it really could benefit from a bootstrapper like @RichiCoder1 mentioned.  The easier to get it going, the better.

**Comment by gep13** [comment]
@RichiCoder1 @jrnail23 Cake itself is now making use of Polly within it's own build script:

https://github.com/cake-build/cake/blob/develop/build.cake#L78

Not sure if there is anything else required here.  As a result, I am going to go ahead and close this issue.  Please feel free to re-open if required.
