### ISSUE TITLE
Forwarded args from dotnet core commandline lose their quotes

### ISSUE THREAD

**Issue by EdinaLewis** [cake-build/cake#1475]
### What You Are Seeing?
More than one build script specified.

### What is Expected?
One build script specified

### What version of Cake are you using?
0.17

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)

Error occurs when running from dotnet command line:
dotnet "C:\My Project\Cake.dll" "build.cake"

Works fine if there is no space in the path, ie:
dotnet "C:\MyProject\Cake.dll" "build.cake"

After some investigation, it appears that the arguments that get passed in from the dotnet launch process are loosing thier quotes. So the command line arguments that cake sees are:

C:\My
Project\Cake.dll
build.cake

(I've broken them up by line so it's easier to see what's happening)

The issue appears to be in `.\src\Cake\Polyfill\EnvironmentHelper.cs` at line 16:

    // Extremely naive solution.
    return string.Join(" ", Environment.GetCommandLineArgs();

The comment was already there, I had nothing to do with it I swear! :)

Since the arguments that are received from the launching process already have their quotes stripped from them when you read from `Environment.GetCommandLineArgs()`, all that is required is to wrap them back in quotes again if they need them, like so:

    // Less naive solution.
    return string.Join(" ", Environment.GetCommandLineArgs().Select(a => a.Contains(" ") ? $"\"{a}\"" : a));

I'm pretty new to the whole github thing, so not sure on the process of submitting a fix for this myself, figured it was best to create an issue and get some feedback first :)

**Comment by augustoproiete** [comment]
Closing this as fixed in the v0.30.0 milestone:

- `build.cake`

```cakescript
var args = Environment.GetCommandLineArgs();

for (int i = 0; i < args.Length; i++)
{
    Information("arg[{0}] = {1}", i, args[i]);
}
```

```powershell
dotnet "C:\My Project\Cake.dll" "build.cake"
```

Output:
```powershell
arg[0] = C:\My Project\Cake.dll
arg[1] = build.cake
```
