### ISSUE TITLE
MSBuild on Mac/Linux

### ISSUE THREAD

**Issue by Redth** [cake-build/cake#1476]
We now ship an implementation of `msbuild` with mono on Mac (it's an option on linux, but not by default, and not fully supported, so I think we can avoid it here for now).

The MSBuild resolver needs to be updated to be able to find this.

PR to follow :)

**Comment by Redth** [comment]
This should probably cause some more discussion about how DotNetBuild work too.  I think for now it's best to leave the behaviour as is, and people can opt into using MSBuild specifically on Mac if that's what they intend.

**Comment by agc93** [comment]
Fixed by #1477
