### ISSUE TITLE
MyGet build support

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#148]
As @gep13 says [in a comment](https://github.com/cake-build/cake/pull/146#issuecomment-68878328) to PR #146, it would be nice with MyGet support.

> You might also want to throw MyGet into the mix as well :-)
> I have just added some MyGet helpers to psake:
> https://github.com/psake/psake-contrib/blob/develop/myget.psm1
> They expose similar Service Messaging to what TeamCity does.

**Comment by gep13** [comment]
Ooo, I had forgotten about this one.  @patriksvensson you want me to take this and see what I can come up with?

**Comment by devlead** [comment]
@gep13 go ahead :+1:
