### ISSUE TITLE
Usage of -NoCache on installing tools and addins

### ISSUE THREAD

**Issue by pitermarx** [cake-build/cake#1487]
### What You Are Seeing?
I cannot install tools and addins from nuget when the internet connection is down because of the usage of the [-NoCache](https://github.com/cake-build/cake/blob/develop/src/Cake.NuGet/NuGetPackageInstaller.cs#L231) flag
### What is Expected?
I expect that nuget uses local cache

### What version of Cake are you using?
0.17.0

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
TeamCity

### How Did You Get This To Happen? (Steps to Reproduce)
0. Have a cake.build file with tools or addins
1. Clean .\tools folder
2. Get offline
3. try to run cake

### Output Log
```
Executing: "C:/ProgramData/chocolatey/bin/nuget.exe" install "OpenCover" -OutputDirectory "C:/work/git/svnmirror/source/tools" -Version "4.6.519" -ExcludeVersion -NonInteractive -NoCache
Unable to load the service index for source https://www.nuget.org/api/v2/.
  Unable to load the service index for source https://www.nuget.org/api/v2/.
  An error occurred while sending the request.
  The remote name could not be resolved: 'www.nuget.org'
NuGet exited with 1
```

**Comment by pitermarx** [comment]
Can you elaborate the reasons for the '-NoCache' flag?
Can it be safely removed or should it be an option? (opt in or opt out)
Will this be possible to address on 0.18 ?

**Comment by patriksvensson** [comment]
@pitermarx I seriously can't remember the reason for `-NoCache` but I'm pretty sure it had a reason back in the days. We could probably add a new parameter `&nocache` to make it opt-in.

Not sure if we can get it in 0.18 unless you're willing to submit a pull request as soon as possible.

**Comment by pitermarx** [comment]
on it

**Comment by pitermarx** [comment]
https://github.com/cake-build/cake/pull/1488

I'm not sure if you'd want more unit tests

**Comment by patriksvensson** [comment]
@pitermarx Left a comment in the PR 👍

**Comment by pitermarx** [comment]
already added 2 tests. any more work required?
