### ISSUE TITLE
Build Failing on 1.0.0-rc4-004771

### ISSUE THREAD

**Issue by threenine** [cake-build/cake#1497]
Hi Guys,

I tried out a CakeBuild script on .netcore RC4 this evening on my ubuntu desktop.   Before I installed RC4  I tested my existing build script on an existing project and it was working.

I installled RC4, tried out the script on the same project and it is now failing.

The  error I recieve is:

Executing task: Build
An error occurred when executing task 'Build'.
Error: ApplicationName='/usr/local/bin/dotnet', CommandLine='build "./src/src.csproj" --output "/home/gary/code/swcportal/src/bin/Release" --framework netcoreapp1.1 --configuration Release', CurrentDirectory='/home/gary/code/swcportal', Native error= Cannot find the specified file

The following is my dotnet --info  

.NET Command Line Tools (1.0.0-rc4-004771)

Product Information:
 Version:            1.0.0-rc4-004771
 Commit SHA-1 hash:  4228198f0e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  16.04
 OS Platform: Linux
 RID:         ubuntu.16.04-x64
 Base Path:   /usr/share/dotnet/sdk/1.0.0-rc4-004771

Just thought I would raise this. I will explore more to see if I can any further info

**Comment by RichiCoder1** [comment]
I'm 90% sure Cake is still only `project.json` tooling which breaks w/ RC3+ tool, aka the `.csproj` tooling.

**Comment by patriksvensson** [comment]
Could you publish your build log (running with diagnostic verbosity) here and I'll see if I can help out.

**Comment by garywoodfine** [comment]
Hi guys apologies for the late reply!  I think @RichiCoder1 hit it on the head. I had upgraded my project to  make use of the .csproj format.  Which  doesn't seem play nice with Cake at this stage.

**Comment by augustoproiete** [comment]
Marking this as resolved on milestone/release v0.30.0
