### ISSUE TITLE
Please support C# 7 and Roslyn v2

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#1512]
Even with the experimental flag, Cake only runs Roslyn v1.0.0-rc2.
It results in things like [not being able to write extension methods](https://github.com/dotnet/roslyn/issues/9139#issuecomment-282400188).

I want to invest in a platform that will stay up to date with C# 7.x scripting features.

What work is there to do to arrive at support of Roslyn v2 (releasing March 7) without requiring an experimental flag?

**Comment by patriksvensson** [comment]
@jnm2 We have plans to integrate it in 0.19 as well as deprecating the Mono script engine.

**Comment by jnm2** [comment]
That's great news!

**Comment by patriksvensson** [comment]
@jnm2 Yes! We only have to make sure that it's not a blocker for people who want to stay on Mono.

**Comment by adamhathcock** [comment]
Does this mean I can have a .NET Core only cake build now?

I know I can boot strap it myself but the "official" instructions don't include it.  Also, nuget.exe is still used but can be avoided?

**Comment by patriksvensson** [comment]
Yes, until 0.19 Cake on .Net Core is the only option. You also won't be able to use NuGet on other platforms than Windows.

**Comment by adamhathcock** [comment]
Msbuild 15 has nuget built in I think.  I'll look into contributing that :)

**Comment by devlead** [comment]
Here's an example of bootstrapping without nuget
https://github.com/WCOMAB/Cake.Kudu

**Comment by beufordy3k** [comment]
What is the general time frame for version 0.19.0? Do you use must-have issues slated for this release as the release criteria or do you cut a new release based on a time interval?
Would like the new C# 7.0 syntax features as well, so if there are contrib items that need work to move it forward, I'll be glad to help on those.

**Comment by gep13** [comment]
@beufordy3k we are planning a team meeting within the next week or so, so we should be in a better position to answer that question after then.

**Comment by beufordy3k** [comment]
@gep13 Thanks, looking forward to the update!

**Comment by devlead** [comment]
Fixed by #1645
