### ISSUE TITLE
Add VSWhere support

### ISSUE THREAD

**Issue by phillipsj** [cake-build/cake#1517]
As discussed in #1369 , please assign to me and I am going to try to get this added this weekend.

**Comment by phillipsj** [comment]
@devlead I already have a lot of this stubbed out.  I need to think about the use cases that are supported by the tool and decide what to add.  I may just add getting the installation path as that is the most needed.

**Comment by devlead** [comment]
@phillipsj getting the FilePaths first sounds good to me.

**Comment by phillipsj** [comment]
Here is currently what I have, I am still thinking through the implementation.  Feedback welcomed.

https://github.com/phillipsj/cake/tree/GH1517-add-vswhere-support

**Comment by damianh** [comment]
@phillipsj great that you took this on so quickly. I think this is on critical path for cake users who need to use the new MSBuild 15 BuildTools on their CI servers. (It is for me anyway).

Open a `[WIP]` PR and lgtm?

**Comment by phillipsj** [comment]
That is a great suggestion, I will do it.

**Comment by phillipsj** [comment]
@damianh The pull request is here now.

**Comment by gep13** [comment]
@devlead so, this can be closed, right?

**Comment by devlead** [comment]
@gep13 correct, closed by #1520

**Comment by jnm2** [comment]
I wonder if this changes anything?
https://blogs.msdn.microsoft.com/heaths/2017/04/21/vswhere-is-now-installed-with-visual-studio-2017/

The package would only have to be downloaded if `%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe` and `%ProgramFiles%\Microsoft Visual Studio\Installer\vswhere.exe` do not exist.

**Comment by phillipsj** [comment]
@jnm2 It would just change how the tool is found.  May need to add a custom resolver that looks for it in that default location first.

**Comment by damianh** [comment]
vswherewhere
