### ISSUE TITLE
Load files at "runtime"

### ISSUE THREAD

**Issue by fleed** [cake-build/cake#1535]
Is there a way to load scripts at "runtime"?
I'd like to add some logic that runs only if a "partial" `deploy.cake` file is found as part of a CI pipeline.

The optional logic could also be run as separate script, but before doing that I'd like to know if there is any similar solution already available.

**Comment by gep13** [comment]
There is a mechanism to load scripts, yes.  This is done via the load pre-processor directive which is documented here:

http://cakebuild.net/docs/fundamentals/preprocessor-directives

However, this is easier included, or not, you can't make a decision on whether it is included.

What I think you might be after is this:

http://cakebuild.net/api/Cake.Common.Tools.Cake/CakeAliases/5FCD85B6

Where you could optionally execute a particular Cake script.

**Comment by fleed** [comment]
Thank you @gep13 , `CakeExecuteScript` looks exactly what I was looking for.
