### ISSUE TITLE
Escaping curly braces in log messages

### ISSUE THREAD

**Issue by DixonDs** [cake-build/cake#1547]
It seems that is not possible to escape curly braces properly in log messages. 

1. `Information("{} {0}", 123);` leads to error "Error: Input string was not in a correct format."
2. `Information("{{}} {0}", 123);` outputs "{{}} 123". The same input to `string.Format` yields "{} 123" which is what I want to get.

This is related to https://github.com/SharpeRAD/Cake.Powershell/issues/25 when the powershell output contains this particular string "{}"

**Comment by kcamp** [comment]
I've made a first pass over this bug and think the changes I've made at 88b2f9d represent the appropriate solution.  I've added the tests that cover the two use-cases referenced above.

The one thing that I think this exposes is a bug in the `LiteralToken` that is being returned for escaped curlies - 
> Information("{{}} {0}", 123); outputs "{{}} 123"

@DixonDs is right in that this should probably output `{} 123` to be consistent with expectations, namely the implementation of `string.Format`.  I have adjusted the parser to return a single '{' or '}' in those cases and updated the tests to match.

If this seems reasonable, I will create a PR with the changes.

**Comment by devlead** [comment]
@kcamp Can you submit a PR we can review?

**Comment by kcamp** [comment]
@devlead Sure, will have that put together in the next day or so.

**Comment by devlead** [comment]
@kcamp excellent! 👍

**Comment by devlead** [comment]
Fixed by #1863
