### ISSUE TITLE
Dry run mode

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#155]
Add a `dry run` mode that does the exact same as a normal build, but instead of executing the tasks, just outputs the resulting task graph.

```shell
PS C:\> .\Cake.exe cake.build -dryrun

Dry running build.cake...
Target: Default

1. Clean
2. Restore-NuGet-Packages
3. Patch-Assembly-Info
4. Build
5. Run-Unit-Tests
6. Copy-Files
7. Zip-Files
8. Create-Cake-NuGet-Package
9. Create-Core-NuGet-Package
10. Package (Delegate)
11. Default (Delegate)

This was a dry run.
No tasks were executed.
```

**Comment by gep13** [comment]
Just a thought, should this flag not be called -noop (as in no operation)?  This is a fairly standard flag in the *nix world, that is starting to flow over to the windows world.

**Comment by devlead** [comment]
In PowerShell it's called `-WhatIf`, regardless of naming it sounds like a great feature, one could in the long run take it over step further and have some commands have an optional mode for this where they print out what they would do without executing. I.e. globber operations like Copy/Delete could printout which files matched,

**Comment by gep13** [comment]
>  regardless of naming it sounds like a great feature, one could in the long run take it over step further and have some commands have an optional mode for this where they print out what they would do without executing

Agreed :+1:

**Comment by patriksvensson** [comment]
It's easy to add a `noop` and `whatif` alias so it feels familiar to everyone. Going to start implement this tonight if there is time, and will submit a PR for discussion :)
