### ISSUE TITLE
TeamCity BuildNumber is a string

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#1556]
### What You Are Seeing?
[TeamCityBuildInfo.Number](http://cakebuild.net/api/Cake.Common.Build.TeamCity.Data/TeamCityBuildInfo/1F181B9F) is a `int` getting its value from the `BUILD_NUMBER` environment variable (see [here](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Build/TeamCity/Data/TeamCityBuildInfo.cs#L28))

Based on the [TeamCity documentation](https://confluence.jetbrains.com/display/TCD8/Predefined+Build+Parameters) the `BUILD_NUMBER` environment variable is a string:

> The build number assigned to the build by TeamCity using the build number format. The property is assigned based on the build number format. 

Where the build number format can be anything including strings.

If the `BUILD_NUMBER` environment variable actually contains a string, `TeamCityBuildInfo.Number` returns `0`.

### What is Expected?
I would expect either the `TeamCityBuildInfo.Number` property return the actual string value of the `BUILD_NUMBER` environment variable or otherwise have this behavior documented.

### What version of Cake are you using?
0.19.1

### Are you running on a 32 or 64 bit system?
64-Bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
TeamCity

### How Did You Get This To Happen? (Steps to Reproduce)

Change build number format to something that `BUILD_NUMBER` no longer is numerical.

**Comment by mholo65** [comment]
Comments seems to refer to counter ([%build.counter%](https://confluence.jetbrains.com/plugins/servlet/mobile#content/view/74847321) which is in fact an integer. But code does return vaule of environment variable BUILD_NUMBER.

We also have ITeamCityProvider.SetBuildNumber(string) which allows setting of build number as string.

So question is. Was the intention to return build counter or number? Either way, there's a bug that needs to be fixed.

**Comment by mholo65** [comment]
@pascalberger after giving this some thought. We should change the return value to `string`. Would you mind submitting a PR to fix this?

**Comment by pascalberger** [comment]
@mholo65 Sure will create a PR
