### ISSUE TITLE
Fix integration tests to include new DotNetCore aliases

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#1571]
Currently a few of the .NET Core CLI aliases are missing integrations tests
https://github.com/cake-build/cake/blob/develop/tests/integration/Cake.Common/Tools/DotNetCore/DotNetCoreAliases.cake

Available aliases:
https://cakebuild.net/api/Cake.Common.Tools.DotNetCore/DotNetCoreAliases/

**Comment by jdbohrman** [comment]
I'd love to take a stab at this, I'm fairly new but I feel confident I could accomplish this!

**Comment by strobelt** [comment]
If this issue is still up for grabs, I would like to help!

**Comment by Delpire** [comment]
The last two comments are over a year old, and I have been interested in getting into contributing the open source. I went ahead and added some tests for the missing aliases and created a PR following the contribution guidelines.

**Comment by devlead** [comment]
fixed by #2686
