### ISSUE TITLE
Files loaded with #load can't define a global variable and use it on linux

### ISSUE THREAD

**Issue by mabead** [cake-build/cake#1573]
### What You Are Seeing?

I have a very simple cake.build script:

````
#load "./Helpers.cake"

Task("Default")
    .Does(() => {
        SayHello();
    });

RunTarget(Argument("target", "Default"));
````

Then, the file "Helpers.cake" contains the following:

````
var name = "you";

void SayHello()
{
    Information("Hello " + name);
}
````

When I run this script on Windows with the provided build.ps1, the script runs fine and prints `Hello you`. But when I run it on Linux (under TeamCity), it fails with the following error message:

````
Starting: /data/work/68ac37aa1e3c7f/build.sh --configuration release --verbosity Verbose
in directory: /data/work/68ac37aa1e3c7f
Downloading NuGet...
Feeds used:
  https://api.nuget.org/v3/index.json

Restoring NuGet package Cake.0.19.3.
  GET https://api.nuget.org/v3-flatcontainer/cake/0.19.3/cake.0.19.3.nupkg
  OK https://api.nuget.org/v3-flatcontainer/cake/0.19.3/cake.0.19.3.nupkg 392ms
Installing Cake 0.19.3.
Adding package 'Cake.0.19.3' to folder '/data/work/68ac37aa1e3c7f/build/tools'
Added package 'Cake.0.19.3' to folder '/data/work/68ac37aa1e3c7f/build/tools'
Analyzing build script...
Processing build script...
Compiling build script...
unknown.cake (2206,28): The name `name' does not exist in the current context
Error: An error occurred while executing build script.
Process exited with code 1
Step Run bash (Command Line) failed
````

### What is Expected?

It should work the same on Linux and Windows ;)

### What version of Cake are you using?

0.19.3

### Are you running on a 32 or 64 bit system?

Not totally sure, but most likely 64 bit.

### What environment are you running on?  Windows? Linux? Mac?

Linux

### Are you running on a CI Server?  If so, which one?

TeamCity

**Comment by mabead** [comment]
Looks like a duplicate of #555

**Comment by mabead** [comment]
I confirm. The workaround described in #555 works for me as well.

**Comment by devlead** [comment]
@mabead this is an issue in the Mono script engine used when running under Mono. We're in the process of unifying around the Roslyn scripting engine for all platforms which will give a unified experience.

Cake.CoreCLR uses Roslyn on all platforms, so using .NET Core can also be an option today to get a consistent experience.

**Comment by casz** [comment]
How would you go about using .NET Core? Any ETA on the unifying process?

**Comment by devlead** [comment]
No hard deadline set, we have a few pre-requisites to sort first. 
Hopefully we'll be able to ship VS2017/csproj upgrade within 1-2 weeks. So sometime after that.

**Comment by devlead** [comment]
For .NET Core you can get some insight from this discussion
https://gitter.im/cake-build/cake?at=592e8125cb83ba6a4117042d
