### ISSUE TITLE
Dependent module Roslyn.Compilers.CSharp no longer published on Nuget

### ISSUE THREAD

**Issue by nagoh** [cake-build/cake#1582]
### What You Are Seeing?
Error when bootstrapping Cake 

### What is Expected?
No error
### What version of Cake are you using?
0.19.3
### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
Windows
### Are you running on a CI Server?  If so, which one?
Reproduced both locally and on TC

### How Did You Get This To Happen? (Steps to Reproduce)
(Clean repository, including nuget cache)
Run .\build.ps1 

### Output Log
Downloading and installing Roslyn...
Installing packages (using https://packages.nuget.org/api/v2)...
Error: System.InvalidOperationException: Unable to find version '1.2.20906.2' of package 'Roslyn.Compilers.CSharp'.
   at NuGet.PackageRepositoryHelper.ResolvePackage(IPackageRepository sourceRepository, IPackageRepository localReposito
ry, IPackageConstraintProvider constraintProvider, String packageId, SemanticVersion version, Boolean allowPrereleaseVer
sions)
   at NuGet.PackageManager.InstallPackage(String packageId, SemanticVersion version, Boolean ignoreDependencies, Boolean
 allowPrereleaseVersions)
   at Cake.Scripting.Roslyn.Stable.RoslynScriptSessionFactory.Install(DirectoryPath root)
   at Cake.Scripting.Roslyn.Stable.RoslynScriptSessionFactory.CreateSession(IScriptHost host)
   at Cake.Scripting.Roslyn.RoslynScriptEngine.CreateSession(IScriptHost host, IDictionary`2 arguments)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()

[src/Cake/project.json](https://github.com/cake-build/cake/blob/main/src/Cake/project.json) has the following reference: 
Roslyn.Compilers.CSharp

Which has been unlisted from nuget: https://www.nuget.org/packages/Roslyn.Compilers.CSharp/

**Comment by nagoh** [comment]
Odd - ran: `nuget locals all -clear` again, and all working.

**Comment by gep13** [comment]
NuGet.org, unless there is a strong reason to not, always keeps package versions in place.  While they can be unlisted (which removes them from appears on the site and don't show up in search, installing them directly using the `version` parameter should always work.

**Comment by devlead** [comment]
@nagoh FYI nuget.org has been having issues for a few hours, so might be related to that.

**Comment by nagoh** [comment]
Ah - looks like it was an issue on nuget: https://status.nuget.org/

**Comment by VQuery** [comment]
@devlead  When it will be resolved or any update from nuget.org ?.Not able to run cake script due to this issue .

**Comment by devlead** [comment]
@VQuery only info I have is what's posted at  https://status.nuget.org/

I would recommend having a fallback source for your builds either self hosted or something like MyGet, @maartenba has written an excellent blog post on why that's important
https://blog.maartenballiauw.be/post/2016/03/23/someone-broke-the-internet!-or-why-you-may-want-to-mirror-your-dependencies.html

If it's Cake you can't fetch, then you could switch to use our MyGet feed until sorted:
Gallery: https://www.myget.org/gallery/cake
V3 Feed: https://www.myget.org/F/cake/api/v3/index.json
V2 Feed: https://www.myget.org/F/cake/

If it's a Cake addin that's causing you trouble, many of those exist under the cake-contrib feed 
Gallery: https://www.myget.org/gallery/cake-contrib
V3 Feed: https://www.myget.org/F/cake-contrib/api/v3/index.json
V2 Feed: https://www.myget.org/F/cake-contrib/

**Comment by NachbarsLumpi** [comment]
Thank you Martin for your quick response and apologies for the duplicate.

Please note that cake 0.19.4 refuses to give a hint on the actual error.

~~~sh
powershell.exe -executionpolicy RemoteSigned -command "build.ps1" -Script build.cake -Configuration Debug
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing tools...
Downloading and installing Roslyn...
Installing packages (using https://packages.nuget.org/api/v2)...
**Error: An error has occurred.**
~~~

**Comment by agc93** [comment]
@NachbarsLumpi if you run with a higher verbosity (Verbose or Diagnostic for example), it *should* give you more information on what went wrong.

**Comment by VQuery** [comment]
@NachbarsLumpi  Now working fine .please check

**Comment by NachbarsLumpi** [comment]
Yep, it's working again. Looks like nuget was able to solve some of the outage. *crossing fingers* Obviously now I'm unable to check the diagnostic / verbose output, but I'm hoping that I don't need it anytime soon. ;-)

Cheers

**Comment by agc93** [comment]
Great to hear :+1: Worth nothing that NuGet are still reporting degraded service so there might still be some lingering issues.

**Comment by VQuery** [comment]
![image](https://cloud.githubusercontent.com/assets/23099088/25425849/e6b1a830-2a8a-11e7-9f91-940bc2c5cfea.png)
👍

**Comment by NachbarsLumpi** [comment]
We upgraded our CI hardware over the past few days and as soon as we switched it back on for the first time all went red. That was quite a shocking start. *laughing* Glad that the issue is just an outage and that it is going to be solved. It could be worse.
