### ISSUE TITLE
cake.config Tools directory not picked up for latest version

### ISSUE THREAD

**Issue by robgha01** [cake-build/cake#1588]
### What You Are Seeing?
The cake binaries are downloaded to the tools folder in my build folder.
The rest of the tools are downloaded to the correct location specified in the config.
i upgraded cake from 0.15.x to 0.19.4.0

Project zip
https://1drv.ms/u/s!AvOXr9f-QF0p22E1gMD_I9kTNWLS

### What is Expected?
That the cake is installed in the correct configured path.

### What version of Cake are you using?
0.19.4.0

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
See the included zip.

### Output Log
None

**Comment by mholo65** [comment]
@robgha01 cake itself is downloaded by the bootstrapper to the folder specified in in the bootstrapper (see https://github.com/cake-build/resources/blob/develop/build.ps1#L89).

Feel free to modify your bootstrapper to whatever suits your needs (e.g. like downloading `Cake` to another folder).

**Comment by robgha01** [comment]
ok, thanks i will look there then.

**Comment by robgha01** [comment]
I managed to get it to install cake to the correct path will look into a way to read the config file and parse it out there later when i manage to get a working build script again as to the other issue :) https://github.com/cake-build/cake/issues/1589 i will close this one for now.

**Comment by mholo65** [comment]
Yes, but that would add more complexity to the bootstrapper. We are trying to keep that simple. However, we encourage people to modify their bootstrapper to suit their own needs.

Closing issue as it is solved.

**Comment by mholo65** [comment]
@robgha01 [here's](https://github.com/cake-build/resources/pull/17) a PR for the bootstrapper that parses `cake.config` if You'd like to take a look.
