### ISSUE TITLE
Add support for choco download

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#1591]
Add support for `choco download` which would allow to use a Cake script for [internalizing Chocolatey packages](https://chocolatey.org/docs/features-automatically-recompile-packages) from the community feed and publish them to an internal feed.

**Comment by gep13** [comment]
@pascalberger I like it! I think we can safely assume that consumers of that function have a licensed edition of choco, and just try to execute it.

**Comment by pascalberger** [comment]
OK, will create a PR in this case :)

**Comment by gep13** [comment]
Sweet!
