### ISSUE TITLE
Add overload to WithCriteria which prints a message

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#1594]
It would be nice to have an overload of the `WithCriteria` extension which takes a message which will be printed out in case of the criteria being false, additionally to the `Skipping task: xy` text. This would allow to give some information why a task was skipped to the user.

**Comment by fatmanmclone90** [comment]
this would be really useful, the current stack trace tells you nothing about why it aborted

**Comment by patriksvensson** [comment]
Excellent idea!

**Comment by pleb** [comment]
Yeah. I end up doing validation in the task because I can't print a custom message. I would rather use WithCriteria

**Comment by devlead** [comment]
@gtbuchanan the task message is written with `Verbose` verbosity,  so you need to launch Cake with `Verbose` or `Diagnostic` verbosity to see it.
