### ISSUE TITLE
Add Alistair and Martin names to all required places

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#1595]
In the same way that @patriksvensson @devlead and @gep13 names appear in various locations within the code base, the same should happen with @agc93 and @mholo65.

PR incoming.

**Comment by mholo65** [comment]
Part of this is in #1562

**Comment by devlead** [comment]
@mholo65 which parts aren't? Would if any would you be in a position to send a PR?

**Comment by mholo65** [comment]
@devlead see PR #1596. Rebase that (ignore project.json) changes, and it's all good, I think :smile:

**Comment by devlead** [comment]
@mholo65 perfect 👍
