### ISSUE TITLE
CommitsSinceVersionSource and PreReleaseNumber as Integer

### ISSUE THREAD

**Issue by WebDucer** [cake-build/cake#1597]
### What You Are Seeing?
The GitVersion properties `CommitsSinceVersionSource` and `PreReleaseNumber` are currently of type `string`. The JSON file from the CLI of GitVersion returns both values as int (that make sense for me). 

```json
MacBook-er-osx:AddPhoto er$ mono tools/GitVersion.CommandLine/tools/GitVersion.exe
{
  "Major":0,
  "Minor":2,
  "Patch":0,
  "PreReleaseTag":"alpha.59",
  "PreReleaseTagWithDash":"-alpha.59",
  "PreReleaseLabel":"alpha",
  "PreReleaseNumber":59,
  "BuildMetaData":"",
  "BuildMetaDataPadded":"",
  "FullBuildMetaData":"Branch.feature/40_FAKE_to_CAKE.Sha.279a1141bfb8ba2ea31227eae5ee47badeeef71b",
  "MajorMinorPatch":"0.2.0",
  "SemVer":"0.2.0-alpha.59",
  "LegacySemVer":"0.2.0-alpha59",
  "LegacySemVerPadded":"0.2.0-alpha0059",
  "AssemblySemVer":"0.2.0.0",
  "FullSemVer":"0.2.0-alpha.59",
  "InformationalVersion":"0.2.0-alpha.59+Branch.feature/40_FAKE_to_CAKE.Sha.279a1141bfb8ba2ea31227eae5ee47badeeef71b",
  "BranchName":"feature/40_FAKE_to_CAKE",
  "Sha":"279a1141bfb8ba2ea31227eae5ee47badeeef71b",
  "NuGetVersionV2":"0.2.0-alpha0059",
  "NuGetVersion":"0.2.0-alpha0059",
  "CommitsSinceVersionSource":59,
  "CommitsSinceVersionSourcePadded":"0059",
  "CommitDate":"2017-05-05"
}
```

### What is Expected?

- Both properties should be of type `int`.

### What version of Cake are you using?

- 0.19.5

### What environment are you running on?  Windows? Linux? Mac?

- Win 10
- macOS

### Are you running on a CI Server?  If so, which one?

- GitLab CI (9.1)

### How Did You Get This To Happen? (Steps to Reproduce)

I wanted to use the version parts for calculation (android version code), but failed in first approach with `PreReleaseNumber` is not a number.

**Comment by gep13** [comment]
@WebDucer can you confirm what version of GitVersion you are using?  Just want to make sure that this isn't a change in the output between versions of GitVersion.

**Comment by WebDucer** [comment]
@gep13 I use the current version 3.6.5.

**Comment by gep13** [comment]
@WebDucer In which case, I agree.  This is something that we should fix.  Are you in a position to submit a PR to correct this?

**Comment by WebDucer** [comment]
@gep13 Yes, I can do that on weekend. But this change would cause a breaking change for all that uses this properties as strings.

**Comment by gep13** [comment]
@WebDucer Yes, you are right.

@devlead any ideas about a "graceful" way to handle this?
