### ISSUE TITLE
Add additional VSTS actions

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#1609]
VSTS uses Logging Commands to allow build scripts to interact with it:

https://github.com/Microsoft/vsts-tasks/blob/master/docs/authoring/commands.md

These are already used for certain things within the VSTS Provider within Cake.

However, it would appear that there are a number of undocumented Commands that can also be utilised.  As an example:

https://github.com/Microsoft/vsts-tasks/blob/a67d378b12399fca682f534ed3bea6d317d554c8/Tests-Legacy/L0/PublishCodeCoverageResults/_suite.ts#L38

The ability to Publish Code Coverage Results.

We should find out what these undocumented Commands are, and provide implementations where we can.

I have an open question with the team:

https://twitter.com/vsreleasemgmt/status/864761672577163264

To try to get some clarity on what is, and isn't, supported.

**Comment by agc93** [comment]
I might be able to get the same support for publishing test results, just testing it has such a brutal feedback cycle :neutral_face:

**Comment by gep13** [comment]
Yip, wasn't limiting this issue to only the publishing of code coverage reports.  Ideally, anything that is a Logging Command, and makes sense to be included as part of a Cake run should be included.

**Comment by agc93** [comment]
Yeah agreed, this one's mostly a fight with Microsoft's not-very-good and constantly-changing documentation :laughing: Will try and get a look at this over the weekend.

**Comment by louisfischer** [comment]
Hi @gep13 and @agc93 I currently have a need to have the same  additional TFS Commands added to the core cake library. I have some experience with TFS/VSTS and the "Logging Commands." Do you mind if I try to create a pull request and add the additional commands of PublishCodeCoverage and PublishTestResults? These 2 additional features would fill the gap of having separate Tasks in TFS/VSTS to publish test results and code coverage results. I will just follow the existing way the other TFS commands are being generated.

**Comment by gep13** [comment]
@louisfischer I would have no objections to you picking this up.  Let us know if you have any questions.

**Comment by devlead** [comment]
Fixed by #2109
