### ISSUE TITLE
How to call build.ps1 with c #

### ISSUE THREAD

**Issue by gaoconggit** [cake-build/cake#1612]
### Output Log

GIST LINK - Please create a gist and link to that gist here

OR

~~~sh
PLACE LOG CONTENT HERE
~~~

**Comment by devlead** [comment]
What are you trying to achieve? To launch a PowerShell script is general thru process start of PowerShell.exe or using a PowerShell script host.

But a little more detail on the why would make it easier to suggest the how.

**Comment by gaoconggit** [comment]
I would like to use c # to run build.ps1。
This is my code：


  private static void CallPS1(string script)
        {
            using (Runspace runspace = RunspaceFactory.CreateRunspace())
            {
                runspace.Open();
                PowerShell ps = PowerShell.Create();
                ps.Runspace = runspace;
                ps.AddScript(script);
                ps.Invoke();
            }

        }

**Comment by gaoconggit** [comment]
I solved this problem by cmd
"powershell.exe ./build.ps1"

I use c # to call cmd

**Comment by patriksvensson** [comment]
@gaoconggit Perfect. I'm closing this issue since it's been resolved for you.
