### ISSUE TITLE
Visual Studio Online - Cake Task failure not failing build

### ISSUE THREAD

**Issue by volak** [cake-build/cake#1617]
### What You Are Seeing?

I'm using cake and in the process of moving to VSTS for builds - and it seems the cake task from the market place: https://marketplace.visualstudio.com/items?itemName=cake-build.cake
Is not passing errors to the build? Even when cake throws a build exception the build succeeds - as noted in the following shots

<img width="631" alt="sshot-94" src="https://cloud.githubusercontent.com/assets/1750226/26534394/67c1aeee-43e9-11e7-988b-15425ef4ab63.png">
<img width="815" alt="sshot-95" src="https://cloud.githubusercontent.com/assets/1750226/26534393/67bdab6e-43e9-11e7-96fb-c86cb6954d04.png">

### What is Expected?
When cake throws an exception the build should fail

**Comment by devlead** [comment]
Looks like you're missing MS build web targets Sdk on build agent. 

Either it needs to be installed or use something like this nuget package 
https://www.nuget.org/packages/MSBuild.Microsoft.VisualStudio.Web.targets/14.0.0.3

**Comment by volak** [comment]
Thank you for the tip - you are right about the error I'm getting during the build.

But that's just for example - the problem is VSTS thinks the build succeeded even though cake failed 😞

**Comment by devlead** [comment]
Issue moved to [cake-build/cake-vso #39](https://github.com/cake-build/cake-vso/issues/39) via [**ZenHub**](https://www.zenhub.com/)
