### ISSUE TITLE
Improve documentation for RedirectStandardError and RedirectStandardOutput

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#1620]
### What You Are Seeing?
Documentation for `ProcessSettings.RedirectStandardError` and `ProcessSettings.RedirectStandardOutput` seems to be just a copy from `ProcessStartInfo` documentation on MSDN, which is misleading in the context of the `ProcessSettings` class.

### What is Expected?
Documentation specific for the `ProcessSettings` class.
 
### What version of Cake are you using?
0.19.5

**Comment by mholo65** [comment]
Closed via #1619
