### ISSUE TITLE
Comma in msbuild commands are not escaped 

### ISSUE THREAD

**Issue by Julien-Mialon** [cake-build/cake#1625]
### What You Are Seeing?
MSBuild generated commande line is invalid when property contains a comma.

### What is Expected?
Valid generated command line

### What version of Cake are you using?
v0.19.5

### Are you running on a 32 or 64 bit system?
64 bits

### What environment are you running on?  Windows? Linux? Mac?
Mac

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
I made a simple cake script available there https://gist.github.com/Julien-Mialon/1918cc8c9db470558eaa8e0f9fdfb77b to reproduce the problem

### Output Log
Here is the generated command

~~~sh
Executing: /Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild /v:normal /p:CodesignKey='iPhone Distribution: Company, SA (XXXXXXXXXX)' /target:Build "/Users/Julien/Documents/Source/tmp/cake/test.sln"

Microsoft (R) Build Engine version 15.2.0.0 (xplat-2017-02/c2edfeb Thu May 18 13:58:03 EDT 2017)
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1006: Property is not valid.
Switch:  SA (XXXXXXXXXX)

For switch syntax, type "MSBuild /help"
~~~

Jenkins has a similar issue and resolve it by replacing every comma by %2c (link to issue for jenkins : https://issues.jenkins-ci.org/browse/JENKINS-5552?focusedCommentId=143769&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-143769)

I would be happy to propose a PR, if the solution to replace comma by %2c is accepted.

**Comment by devlead** [comment]
@Julien-Mialon your suggestion sounds valid, so a PR sounds reasonable, there's a few more special values which probably also could be covered by the PR
* https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-special-characters
* https://docs.microsoft.com/en-us/visualstudio/msbuild/how-to-escape-special-characters-in-msbuild

also looks like uppercase hex is preferred.

**Comment by Julien-Mialon** [comment]
@devlead I'm not sure all of specials characters should be escaped because they could be valid values for msbuild properties. The only two characters that really cause issues are comma (,) and semicolon (;)

I'm gonna start working on a PR for this two but we can talk about adding others if really needed.

**Comment by devlead** [comment]
Sounds reasonable 👍

**Comment by devlead** [comment]
Fixed by #1793

**Comment by georgehemmings** [comment]
This has broken the ability to specify multiple constants. Example:

`settings.WithProperty("DefineConstants", "A=a;B=b");`

The semi-colon should not be escaped in this scenario.

Should a new issue be raised for this, @devlead ?

**Comment by devlead** [comment]
@georgehemmings doesn't `  .WithProperty("DefineConstants", "A=a","B=b");` work? If not then yes please raise an separate issue. Comments on closed issue easy to miss.

**Comment by georgehemmings** [comment]
@devlead no, it seems only one `/p:DefineConstants` is allowed, the last one wins.

`.WithProperty("DefineConstants", "A=a;B=b".Quote());` last worked in v21.1.
 
Ok, I'll raise a new issue.
