### ISSUE TITLE
Remove need for a nuspec file

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#163]
Since @devlead added support for adding files to a nuget package programmatically (see [commit](https://github.com/cake-build/cake/commit/a59b0656ae98da269042ed17f21f711684f7c08b)) there really isn't a need to provide att nuspec file since all (afaik) attributes of a nuspec file is supported via code.

```csharp
NuGetPack(new NuGetPackSettings 
{
    Id = "Cake.Core",
    Name = "Cake.Core",
    Authors = "patriksvensson",
    Owners = "patriksvensson",
    Description = "The Cake core library.",
    Version = semVersion,
    ReleaseNotes = releaseNotes.Notes.ToArray(),
    BasePath = binDir,
    OutputDirectory = nugetRoot,
    NoPackageAnalysis = true,
    Files = new[] 
    {
        new NuSpecContent { Source = "Cake.Core.dll", Target = "lib/net45" },
        new NuSpecContent { Source = "Cake.Core.xml", Target = "lib/net45" },
        new NuSpecContent { Source = "Cake.Core.pdb", Target = "lib/net45" },
    }
});
```

Of course, there should still be possible to provide a nuspec file if the user wants to.

**Comment by ChrisMissal** [comment]
:+1:

I believe the best approach for this would be to create a "blank" nuspec file with the name of:

```csharp
string.Format("{0}.nuspec", settings.Id);
```

So in this case it would be `Cake.Core.nuspec`.

**Comment by gep13** [comment]
@patriksvensson this is marked as a feature, but is there anything that needs to be done here?  Or is this related to: https://github.com/cake-build/cake/issues/511.

If the latter, I think we can close out one of these.  Thoughts?

**Comment by devlead** [comment]
You don't need a spec anymore so this can be closed.
