### ISSUE TITLE
Nuget mismatch when compiling Build Script and nuget addin.

### ISSUE THREAD

**Issue by danwalmsley** [cake-build/cake#1642]
### What You Are Seeing?
Fails to run script that was previously working mismatch with nuget.core versions...

```
Preparing to run build script...
Running build script...
Analyzing build script...
Processing build script...
Installing addins...
Compiling build script...
Error: error CS1705: Assembly 'Cake, Version=0.20.0.0, Culture=neutral, PublicKeyTo
.14.0.832, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher ver
Core, Version=2.12.0.817, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
```

### What is Expected?
Runs normally.

### What version of Cake are you using?
0.20.0 (previous versions worked)

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
AppVeyor (but can reproduce locally)

https://ci.appveyor.com/project/danwalmsley/avalonstudio/build/0.2.0.2978

### How Did You Get This To Happen? (Steps to Reproduce)
I hadn't pinned cake to a specific version (you learn some things the hard way)

Build.cake for repro...

I had thought changing the version for the nuget.core package would have fixed it, but doesn't seem to resolve it.

```
/////////////////////////////////////////////////////////////////////
// ADDINS
/////////////////////////////////////////////////////////////////////

#addin "Cake.FileHelpers"
#addin "Cake.Docker"
#addin "nuget:?package=NuGet.Core&version=2.12.0"

//////////////////////////////////////////////////////////////////////
// TOOLS
//////////////////////////////////////////////////////////////////////

///////////////////////////////////////////////////////////////////////////////
// USINGS
///////////////////////////////////////////////////////////////////////////////

//////////////////////////////////////////////////////////////////////
// ARGUMENTS
//////////////////////////////////////////////////////////////////////


///////////////////////////////////////////////////////////////////////////////
// TASKS
/////////////////////////////////////////////////////////////////////////////// 

Task("Restore-NetCore")
    .IsDependentOn("Clean")
    .Does(() =>
{
    foreach (var project in netCoreProjects)
    {
        DotNetCoreRestore(project.Path);
    }
});

Task("Default")
    .IsDependentOn("Restore-NetCore");

RunTarget(target);
```

**Comment by gep13** [comment]
@danwalmsley After changing the version number in the build.cake file, did you clear out your `tools` folder?

If not, can you try again, but first clear out the `tools` folder.

**Comment by danwalmsley** [comment]
yes clearing tools directory fixed it, so to confirm

if anyone else comes across this:

1) Update nuget.core adding to 2.14.0 
```
#addin "nuget:?package=NuGet.Core&version=2.14.0"
```

2) Delete `tools\Addins` directory.

**Comment by danwalmsley** [comment]
@gep13 thanks for your help :) 👍

**Comment by devlead** [comment]
@danwalmsley does this mean 0.20.0 works for you can we can close this issue?

**Comment by danwalmsley** [comment]
I think its working, maybe a note somewhere in release notes that people using the nuget addon could come across this.

**Comment by devlead** [comment]
Yes could make sense to add as a known issue to the blog post [here](https://github.com/cake-build/website/blob/develop/input/blog/2017-06-12-cake-v0.20.0-released.md)

**Comment by devlead** [comment]
Issue moved to [cake-build/website #366](https://github.com/cake-build/website/issues/366) via [**ZenHub**](https://www.zenhub.com/)
