### ISSUE TITLE
Re-enable Integration Tests

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#1647]
During the process of upgrading Cake to use VS 2017 Tooling, some integration tests were disabled.  These need to be turned back on again.

https://github.com/cake-build/cake/pull/1562#discussion_r116984405

**Comment by devlead** [comment]
Fixed by cd29816cb769360e0888a0f68d6187fbc0f2d88b

**Comment by gep13** [comment]
👍

**Comment by gep13** [comment]
@devlead I have assigned this to the 0.21.0 milestone.
