### ISSUE TITLE
NUnit3Settings ``Verbose`` flag obsoleted by NUnit console runner

### ISSUE THREAD

**Issue by RSchwoerer** [cake-build/cake#1651]
### What You Are Seeing?
The NUnit3 test runner tool's ``NUnit3Settings `` has a ``Verbose`` flag, the NUnit console runner's command line argument this represents was removed.

### What is Expected?
Initially I was thinking the ``Verbose`` flag should set set the ``--trace=LEVEL`` command line argument.
However it looks like the functionality is different. Maybe just remove the ``Verbose`` flag completely.

[NUnit console runner command line.](https://github.com/nunit/docs/wiki/Console-Command-Line)

### What version of Cake are you using?
0.17

### What environment are you running on?  Windows? Linux? Mac?
Windows.

### Other

Link to NUnit console runner where argument was removed:
https://github.com/nunit/nunit-console/pull/170

Link to Cake's NUnit3Runner where argument is parsed:
https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/NUnit/NUnit3Runner.cs#L166

**Comment by devlead** [comment]
@RSchwoerer thanks for your feedback! 

Then I think it should be obsoleted with warning via attribute upcoming release and then removed the following release. 

Would you be willing to send a PR?

**Comment by ChrisMaddock** [comment]
Good catch. 🙂 The same also applies to the `Full` option also in Cake.

Both these options were added in the early days of NUnit3 - but the relevant functionality never implemented/later removed. They've both been no-ops since the first full release of 3.0, and were removed in 3.7 once reported.
