### ISSUE TITLE
Add Before and After options to NUnit3Labels enum

### ISSUE THREAD

**Issue by ChrisMaddock** [cake-build/cake#1653]
When NUnit Console 3.7 is released, it will include new options for the `--labels` argument - `Before` and `After`. Cake's `NUnit3Labels` enum will also want updating, to allow people to access these.

The new options aren't currently documented yet - but what will probably become the docs is at the link below: https://github.com/nunit/nunit-console/pull/186#issue-212287096

**Comment by phillipsj** [comment]
@devlead @gep13 @patriksvenson I will take this one too, if no objections.

**Comment by patriksvensson** [comment]
@phillipsj @ChrisMaddock Has 3.7 been released with the new labels?

**Comment by ChrisMaddock** [comment]
Yes 😄
