### ISSUE TITLE
NUnit3 crashes if Format and Transform are set

### ISSUE THREAD

**Issue by Roemer** [cake-build/cake#1671]
NUnit will crash if both are supplied as parameters (see nunit/nunit-console#252).

We should make a sanity check for this and adjust all examples / tests where this is wrongly set.

See #1666 for more details. This change is also dependent on the merge of #1666 

Open points:
Should we throw an exception or a just log a warning if both are set? Or when it is executed?

**Comment by mholo65** [comment]
@Roemer thanks for creating this! I've assigned this issue to you and assigned it to the v0.22.0 milestone.

**Comment by mholo65** [comment]
@Roemer said:
> Open points:
Should we throw an exception or a just log a warning if both are set? Or when it is executed?

I'd say we throw an exception (see other examples for sanity check settings here https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/SignTool/SignToolSignRunner.cs#L131)

**Comment by Roemer** [comment]
Ok so the general guideline is to throw an exception when the command is run (not when the parameters are set). Will do this after the merge of #1666

**Comment by ChrisMaddock** [comment]
Just to be totally clear - NUnit will currently crash in this situation - but in the near future, will just 'error' and return whatever the 'invalid arguments' error code is. (Afraid I can't remember off the top of my head - but I remember I added it to the Cake source at some point!)

In the even further future, someone may PR Nunit to allow format and transform to be specified together - so maybe the best solution is to ignore Nunits current bug with the crash - and just handle the 'invalid arguments' code correctly - which I believe cake already does?

Will leave that with you guys to decide the best course of action!

**Comment by mholo65** [comment]
@Roemer as https://github.com/nunit/nunit-console/issues/252 is now solved and NUnit will no longer crash, we think that solution proposed by @ChrisMaddock and don't interfere would be the wisest thing to do.

Therefore I'm closing this issue. Thanks!
