### ISSUE TITLE
MSBuildFileLogger LogFile is a string and not a FilePath

### ISSUE THREAD

**Issue by Roemer** [cake-build/cake#1674]
As the title says, the Property `LogFile` in MSBuildFileLogger is a `string`. I think it would make more sense that it is a `FilePath` so that you can direcly use it like:
```csharp
LogFile = artifactsDir.CombineWithFilePath("BuildLog.txt")
```

**Comment by Roemer** [comment]
I will do a PR with this. This would be a breaking change.

**Comment by mholo65** [comment]
Solved by #1676
