### ISSUE TITLE
Better performance for --showdescription

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#1677]
Currently it's taking between 4 and 5 seconds. Is there anything that can be done about that? Ideally there would be some way to get it under 500ms.

I added target name autocomplete to my bootstrapper which executes `--showdescription`, but it freezes the console for 4-5 seconds every time I press tab. 200ms would be so cool though...

I know Cake takes a while to check dependencies and compile, but no one ever creates targets that only conditionally appear, so in my mind we wouldn't even have to compile the script to obtain the list of calls to `Target`. But if you wanted to be absolutely completely safe, the `--showdescription` logic could look like this:

 1. Parse the script file's syntax
 2. Locate all usages of the name `Target`
 3. If every usage of `Target` is a call with a literal string name and the call is not nested under a conditional, add it to the list. Otherwise, finish compiling the script and discover the list the old way.

I'm pretty sure the fallback will never actually be needed though.

**Comment by devlead** [comment]
Currently it'll codgen, reference dependencies, compile and execute the C# code. for it to be 200ms likely would have to not do that but rather some specific `--showdescription` parsing code.

Unsure if this is a a high priority or worth it at the moment, a potential work around would be to in boostrapper use powershell to extract the needed info i.e. something like
```PowerShell
[string[]] $tasks = Get-Content .\build.cake|Select-String -Pattern 'Task\("(.*?)"\)' | % Matches | % {$_.Groups[1].Value}
```
that takes around 8 ms on my machine on cake's build.cake, resulting in an array containing
```
Clean
Restore-NuGet-Packages
Build
Run-Unit-Tests
Copy-Files
Zip-Files
Create-Chocolatey-Packages
Create-NuGet-Packages
Sign-Binaries
Upload-AppVeyor-Artifacts
Upload-Coverage-Report
Publish-MyGet
Publish-NuGet
Publish-Chocolatey
Publish-HomeBrew
Publish-GitHub-Release
Create-Release-Notes
Package
Default
AppVeyor
Travis
ReleaseNotes
```

 where it would fail would be if tasks are defined in any other file external to take i.e. included via `#load` which is one of the complexities as some files make be located in nuget packages needed to be fetched an loaded.

**Comment by jnm2** [comment]
@devlead I think your suggestion is even better. I'd guess this will cover the 99.99% case. It can easily be extended to follow `#load` references, and is it really a big deal if autocomplete skips targets defined in NuGet dependencies?

**Comment by devlead** [comment]
@jnm2 for anyone using something like cake recipe it would matter as all tasks are defined externally. It'll depend on your use case as any text parsing will be "best effort".

**Comment by jnm2** [comment]
I see. Going back a step, it also wouldn't hurt to to start running the whole resolved and compiled script in under 500ms either. Perhaps the whole startup business could be profiled to see what's taking 4 seconds and possible workarounds.

**Comment by gep13** [comment]
@jnm2 as @devlead said, this is unlikely to be a priority for is right now. But if you wanted to take a stab at profiling it, and post your results back here?

**Comment by jnm2** [comment]
Closing due to lack of priority.
