### ISSUE TITLE
Cake on dotnet core doesn't load reference dll correctly if referenced from a subdirectory

### ISSUE THREAD

**Issue by phenixdotnet** [cake-build/cake#1679]
### What You Are Seeing?
If you're using Cake.CoreCLR, the referenced libs (using #reference) aren't loaded correctly if the cake script is in a subdirectory. 
```
Error: System.ArgumentException: Absolute path information is required.
Parameter name: assemblyPath
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Cake.Core.Reflection.AssemblyLoader.Load(FilePath path, Boolean verify)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

### What is Expected?
The lib should be loaded and available in the cake script

### What version of Cake are you using?
Cake.CoreCLR version 0.21.0-dotnetV10tooling0001 from myget
Cake.Docker version 0.7.7 from nuget

### Are you running on a 32 or 64 bit system?
x64

### What environment are you running on?  Windows? Linux? Mac?
- Windows x64 
- Mac OS 16.6.0 Darwin

### How Did You Get This To Happen? (Steps to Reproduce)
You can find a repro project here: https://github.com/phenixdotnet/cake-repro

The important thing is to use a cake script file from a subdirectory (in the repro example, the build/docker.cake file)

### Output Log

logs from .\build.ps1 -v Diagnostic and .\build.ps1 -v Diagnostic -Experimental

~~~sh
Preparing to run build script...
Feeds used:
  C:\Users\vlaine\.nuget\packages\
  https://api.nuget.org/v3/index.json
  https://www.myget.org/F/cake/api/v3/index.json
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\

Restoring NuGet package Cake.CoreClr.0.21.0-dotnetV10tooling0001.
Restoring NuGet package Cake.Docker.0.7.7.
Adding package 'Cake.CoreClr.0.21.0-dotnetV10tooling0001' to folder 'C:\dev\Test\ReproCake\tools'
Adding package 'Cake.Docker.0.7.7' to folder 'C:\dev\Test\ReproCake\tools'
Added package 'Cake.Docker.0.7.7' to folder 'C:\dev\Test\ReproCake\tools'
Added package 'Cake.CoreClr.0.21.0-dotnetV10tooling0001' to folder 'C:\dev\Test\ReproCake\tools'
Running build script...
Module directory does not exist.
Analyzing build script...
Analyzing C:/dev/Test/ReproCake/build.cake...
Analyzing C:/dev/Test/ReproCake/build/docker.cake...
Processing build script...
Installing tools...
Package Cake.Docker has already been installed.
Error: System.ArgumentException: Absolute path information is required.
Parameter name: assemblyPath
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at Cake.Core.Reflection.AssemblyLoader.Load(FilePath path, Boolean verify)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
~~~

I have a quick fix for this bug it's ugly. I can submit a PR if you whish.
In Cake.Core\Polyfill\AssemblyHelper.cs
```
diff --git a/src/Cake.Core/Polyfill/AssemblyHelper.cs b/src/Cake.Core/Polyfill/AssemblyHelper.cs
index 0f603a59..0ec035c6 100644
--- a/src/Cake.Core/Polyfill/AssemblyHelper.cs
+++ b/src/Cake.Core/Polyfill/AssemblyHelper.cs
@@ -3,6 +3,7 @@
 // See the LICENSE file in the project root for more information.

 using System;
+using System.IO;
 using System.Reflection;
 using Cake.Core.IO;
 using Cake.Core.Reflection;
@@ -34,8 +35,9 @@ namespace Cake.Core.Polyfill
                 return Assembly.Load(new AssemblyName(path.FullPath));
             }

+            FileInfo fi = new FileInfo(path.FullPath);
             var loader = new CakeAssemblyLoadContext(fileSystem, path.GetDirectory());
-            return loader.LoadFromAssemblyPath(path.FullPath);
+            return loader.LoadFromAssemblyPath(fi.FullName);
 #else
             return Assembly.LoadFrom(path.FullPath);
 #endif
```

**Comment by patriksvensson** [comment]
@phenixdotnet Thanks for reporting this.

Instead of using a `FileInfo` to get the full path in your patch, you should use `path.MakeAbsolute(environment)`.

We should however look into why the path isn't absolute in the first place. According to https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Scripting/Processors/ReferenceDirectiveProcessor.cs#L46 it should use the absolute path already.

**Comment by phenixdotnet** [comment]
@patriksvensson Thanks for quick response.

Problem with the ```path.MakeAbsolute(env)``` is we don't have the env in this method. Adding it on the whole stack is a huge breaking change. I can go to this way if you valid it.

I guess the root cause of this bug in somewhere in ```FilePath``` (or base class) and how absolute path are handled.

**Comment by patriksvensson** [comment]
@phenixdotnet The polyfills are internal so this wouldn't be a breaking change. Not sure what you mean with a bug in `FilePath` though, could you elaborate?

**Comment by phenixdotnet** [comment]
> Not sure what you mean with a bug in FilePath though, could you elaborate?
Mistake from my side, I didn't understand correctly the FullPath property. From the property name I guess to get the absolute path but it isn't. I just don't under the diff between path and fullpath.

I changed the patch implementation and created a PR #1680
