### ISSUE TITLE
Using Cake Contribution Guidelines

### ISSUE THREAD

**Issue by kcamp** [cake-build/cake#1681]
I have two projects that I am polishing up in preparation for potential release/contribution (repos are not yet public). As part of that, I am working on including contribution guidelines.   

The content used by the [Cake Contribution Guielines](https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md) is excellent, and I'd like to use that as the basis for my own content.  Would that be an option?  Would I also need to seek permission of the Chocolatey project as well?

Assuming we are able to move forward, it seems that it would be appropriate to acknowledge both upstream projects, similar to:
```
This contribution guide was taken from the Chocolatey project with permission and was edited to follow Cake's conventions and processes.
```

Let me know what the next steps, if any, might be.

Thanks.

cc: @gep13

**Comment by gep13** [comment]
> @kcamp said...
Would that be an option?

Almost certainly.  As you know, we actually borrowed the Guidelines from the Chocolatey Project.  @ferventcoder did an excellent job in creating the original version.

I am fairly sure that Rob won't have an issue with you also borrowing it, but yes, I would suggest that an acknowledgement, similar to what we have here:

https://github.com/cake-build/cake/blob/develop/CONTRIBUTING.md#acknowledgement

Would be a good idea.

**Comment by kcamp** [comment]
Sounds good, thank you.

@ferventcoder : If there is any issue with this re-use, let me know.  Otherwise, I intend to proceed & will add the appropriate acknowledgements to the final copy.

**Comment by ferventcoder** [comment]
Not at all. Check out the updated CONTRIBUTING in the Chocolatey project - https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md

**Comment by ferventcoder** [comment]
Not at all == no issues from reuse, it's flattering 👍

**Comment by ferventcoder** [comment]
Updated the text in the first to mention Chocolatey is Apache2 licensed, so I'm not sure you would need to ask permission, just attribute where you got it from like Cake did. 👍

**Comment by gep13** [comment]
@kcamp by the way... let me know when you release the Cake Addin's, so I can follow up regarding cake-contrib user on NuGet.org, etc.

**Comment by ferventcoder** [comment]
@gep13 specifically this section might be good for Cake to add - https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#set-up-your-environment

**Comment by ferventcoder** [comment]
This is also new - https://github.com/chocolatey/choco/blob/master/CONTRIBUTING.md#debugging--testing

**Comment by kcamp** [comment]
great! thanks to all.   I will have a look at the referenced updates and incorporate as necessary.
@gep13 I will let you know when things are ready to go.

closing this issue as i consider it resolved.
