### ISSUE TITLE
ChocolateyDownload should be documented to only work in paid edition

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#1689]
If you use the `ChocolateyDownload ` alias without a paid edition, you will get:

```
Could not find a command registered that meets 'download'.
 Try choco -? for command reference/help.
```

**Comment by gep13** [comment]
@jnm2 no, this is not the case.  The Chocolatey download command is only available in the paid editions of Chocolatey.

https://chocolatey.org/docs/features-automatically-recompile-packages

**Comment by gep13** [comment]
Perhaps this issue should be changed to indicate that this alias will only work with the licensed editions.

**Comment by jnm2** [comment]
@gep13 Sorry! Thanks for the clarification.

**Comment by pascalberger** [comment]
Specific options with its requirements are already documented in https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/Chocolatey/Download/ChocolateyDownloadSettings.cs. I thought plain `choco download` is also available in Community edition but this doesn't seem to be the case, so documenting it on the alias would make sense

**Comment by pascalberger** [comment]
Created #1975 for fixing this
