### ISSUE TITLE
Support For Interpolated String Literal Expressions

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#1691]
@chazt3n commented on [Wed Jul 19 2017](https://github.com/cake-build/website/issues/389)

It would be awesome to have support for code like:
```csharp
Console.WriteLine($"Name = {name}, hours = {hours:hh}");
```

**Comment by gep13** [comment]
@chazt3n This should be possible, OOTB, once we move to the latest version of Roslyn, which is due to ship in the next release, 0.22.0.

For now, you might be able to use this today by passing the `-Experimental` flag.

**Comment by mholo65** [comment]
@gep13 could we close this as #1645 is merged?

**Comment by gep13** [comment]
@mholo65 yes, I would say that that is correct, yes.

**Comment by gep13** [comment]
Relates to #1645
