### ISSUE TITLE
Possible bug when setting process environment variable

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#1693]
Was cleaning up Resharper warnings as part of a PR and noticed this: https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Polyfill/ProcessHelper.cs#L20

We should figure out what is the intended behavior here, and if the current behavior is correct, remove `envKey`.

**Comment by devlead** [comment]
env key should be used if we want consistent xplat, otherwise it can be removed. 

Thinking initial intent was to work around a casing issue with corrupt environment variables, which it didn't, but this could also be the reason it didn't 😁
