### ISSUE TITLE
Add CakeReferenceImportAttribute for Cake Addins

### ISSUE THREAD

**Issue by louisfischer** [cake-build/cake#1698]
This idea is to add a new "CakeReferenceImportAttribute" that can be used by Cake addins to automatically import references into the script. This feature would work very similar to the "[CakeNamespaceImportAttribute](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Annotations/CakeNamespaceImportAttribute.cs)" which imports "using" statements into the running cake script

The use case is for addins that reference .NET Framework Assemblies that the Addin may depend on but is not available as a nuget package. An addin author has no options currently to force an assembly to load that maybe required. Even adding the "<frameworkAssemblies>" to the nuspec file did not load or reference the assemblies required.

**Comment by louisfischer** [comment]
I can do a pull request if it is something the team thinks is worth pursuing.

**Comment by gep13** [comment]
@cake-build/cake-team what were your thoughts on this one?

**Comment by mholo65** [comment]
Could we as a starter honor `<frameworkAssemblies>` in the nuspec file of the Addin?

**Comment by louisfischer** [comment]
@mholo65 That would be a good alternative. That was the first thing I tried but it did not work.

**Comment by louisfischer** [comment]
@cake-build/cake-team I did so see any other opinions on the issue. I would gladly take a stab at it but wanted the thumbs up before I started any thing.

**Comment by mholo65** [comment]
@louisfischer now when we have our own NuGet client implementation in `Cake.NuGet` it should be possible to implement support for honoring `<frameworkAssemblies>`. Would like to take a stab at that?

**Comment by louisfischer** [comment]
@mholo65 I will take a look at it and submit a PR.

**Comment by mholo65** [comment]
Awesome, thanks! Hint, you should be able to get the framework references from the NuSpec somewhere around here... https://github.com/cake-build/cake/blob/develop/src/Cake.NuGet/Install/NuGetFolderProject.cs#L61

**Comment by louisfischer** [comment]
@mholo65 I was reviewing the code and running some of the tests just to get familiar with cide. I noticed that when I install an a nuget package in cake script, it never actual seems to use the NuGetPackageInstaller.cs located below the install folder.

![image](https://user-images.githubusercontent.com/1905010/33357489-004f2b4e-d488-11e7-8e13-eee4079c03a0.png)

It always sees to be using the NuGetPackageInstaller.cs class at the root of the Cake.NuGet project (which shells out using the standard IProcessRunner)
![image](https://user-images.githubusercontent.com/1905010/33357569-6cb79186-d488-11e7-9e19-d438bee830be.png)

In the method that you showed me above, I was able to get the Framework References from the NuspecReader from the DownloadResourceResult. The Method just never seems to get called.

Am i doing something wrong? Any additional suggestions would be appreciated.

**Comment by mholo65** [comment]
@louisfischer the stuff in the Install folder is used when using In-Process NuGet client. Try passing `—nuget_useinprocessclient=true` to Cake.exe when debugging and it will work.

The correct package installer is registered in IoC here, based on that config value https://github.com/cake-build/cake/blob/develop/src/Cake.NuGet/NuGetModule.cs#L54.

**Comment by louisfischer** [comment]
@gep13 @mholo65  I think this issue can be canceled. I am not sure if this needed anymore.

**Comment by gep13** [comment]
@louisfischer happy to close it out.  Let us know if you want to re-visit this.
