### ISSUE TITLE
DotNetCoreRestore, DotNetCoreBuild & DotNetCoreTest Microsoft.Portable.CSharp.targets was not found

### ISSUE THREAD

**Issue by soydachi** [cake-build/cake#1702]
### What You Are Seeing?
I created a .net-standard 1.5 library with xunit pcl netcoreapp1.1
url: [https://github.com/soydachi/MeetupApi](https://github.com/soydachi/MeetupApi)

With vs4mac, it's compile and run test without problems, but on cake it throws this error always:

> /Users/dachibox/Projects/OpenSource/MeetupApi/src/Meetup.Api/Meetup.Api.csproj(101,3): error MSB4019: The imported project "/usr/local/share/dotnet/sdk/1.0.4/Microsoft/Portable/v5.0/Microsoft.Portable.CSharp.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

> /usr/local/share/dotnet/sdk/1.0.4/NuGet.targets(97,5): error : Unable to resolve '/Users/dachibox/Projects/OpenSource/MeetupApi/src/Meetup.Api/Meetup.Api.csproj' for '.NETCoreApp,Version=v1.1'. [/Users/dachibox/Projects/OpenSource/MeetupApi/src/MeetupApi.sln]

### What version of Cake are you using?
Cake.0.21.1
### Are you running on a 32 or 64 bit system?
64 bit
### What environment are you running on?  Windows? Linux? Mac?
Mac

### How Did You Get This To Happen? (Steps to Reproduce)

1. git clone [https://github.com/soydachi/MeetupApi.git](https://github.com/soydachi/MeetupApi)
2. `./build.sh --target "Default"`

**Comment by devlead** [comment]
As far as I know the .NET Core CLI only supports the new VS2017 project format and by the looks of it you're trying to build a VS2015 solution with some VS2017 elements added to it
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup>
    <MinimumVisualStudioVersion>10.0</MinimumVisualStudioVersion>
```

Here's a blog post about migrating csproj to vs2017 csproj
http://www.natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/

Here's an example of an converted CSPROJ
https://gist.github.com/devlead/061d64daf197148fca80f4e380c061ae/revisions#diff-d1bc79fc60221b81d0bc1a6a581e3efc

**Comment by soydachi** [comment]
Oh yes, that is true, it's an old project.

Sorry for the tome I stole you :)

Now it's working.

**Comment by devlead** [comment]
Ok, no worries, glad you got it sorted.

I'll go ahead and close this issue, please reopen or raise a new issue if issue isn't resolved.
