### ISSUE TITLE
Cannot build Cake locally in VS2017 without first running Cake build script

### ISSUE THREAD

**Issue by patridge** [cake-build/cake#1709]
### What You Are Seeing?

If you clone the Cake repo and try to build it in VS2017, you will get a bunch of errors restoring NuGet packages. (See Gist, linked below, for full output.)

> Restoring NuGet packages...
> Unable to resolve 'Microsoft.TargetingPack.NETFramework.v4.5 (>= 1.0.1)' for '.NETFramework,Version=v4.5'.
> Unable to resolve 'Microsoft.TargetingPack.NETFramework.v4.5 (>= 1.0.1)' for '.NETFramework,Version=v4.5 (centos.7-x64)'.
> Unable to resolve 'Microsoft.TargetingPack.NETFramework.v4.5 (>= 1.0.1)' for '.NETFramework,Version=v4.5 (debian.8-x64)'.
> …

### What is Expected?

Any necessary prerequisite steps should be handled when building the project in VS2017.

A simpler approach might be to have some docs on building/testing things locally that mention the build script requirement in the README docs.

### What version of Cake are you using?

As of commit #c9561feb

### Are you running on a 32 or 64 bit system?

64-bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

No

### How Did You Get This To Happen? (Steps to Reproduce)

1. Clone Cake Git repo to computer
2. Load Solution in VS2017
3. **Build > Build Solution** (default shortcut: Ctrl+Shift+B)

Or, if you have built the repo via Cake already, run `git clean -d --force` to nuke untracked files first.

### Output Log

https://gist.github.com/patridge/1ed25be0869a7acde8cdba82f4dc9cec

**Comment by devlead** [comment]
Think we could probably sort this by adding a nuget.config to repo. It's likely because it doesn't find the MyGet feeds.

**Comment by patriksvensson** [comment]
Hmm, the targeting packs should only be required when building on Mono (imported in `Shared.msbuild`). We're using the .NET4.6.2 targeting packs as well. Really strange.

**Comment by mholo65** [comment]
@patriksvensson but if `.NET 4.6.2 Targeting pack` isn't ticked in VS 2017 installer. It would exlplain behaviour.

![image](https://user-images.githubusercontent.com/7863439/28812809-2bef0fea-769f-11e7-9e61-3dc3c89486c7.png)

**Comment by mholo65** [comment]
Targeting pack is removed in PR #1725

**Comment by devlead** [comment]
@patridge is this still an issue?

**Comment by patridge** [comment]
@devlead I grabbed the latest from develop, and it built just fine from a clean clone. I'll close accordingly.
