### ISSUE TITLE
Add alias for simple sub-directory listing

### ISSUE THREAD

**Issue by patridge** [cake-build/cake#1710]
Rather than having to learn anything about the pattern syntax used in GlobbingAliases various methods (including its own [`GetDirectories`](https://github.com/cake-build/cake/blob/2595de795c56066eee8391641f3298082b4384cd/src/Cake.Common/IO/GlobbingAliases.cs#L97) method that can be used to similar effect with the right pattern), it seems like it would be nice to have a simplified method for getting a list of all sub-directories in any given DirectoryPath.

Goal syntax:

> `var directories = GetSubDirectories(someDirectoryPath);`

[Chat discussion start](https://gitter.im/cake-build/cake?at=597f4fe1210ac269203fe970) ([approved for issue/PR](https://gitter.im/cake-build/cake?at=597f7eb3c101bc4e3ad813b1))

**Comment by devlead** [comment]
Fixed by #1711
