### ISSUE TITLE
Query/possible bug with multiple arguments

### ISSUE THREAD

**Issue by DavidR91** [cake-build/cake#172]
If I invoke my build with the following arguments:

`"$(SolutionDir)cake/cake.exe" build.cake -verbosity=diagnostic -root="$(SolutionDir)" -scomDllConfiguration="$(ConfigurationName)"`

I have problems using the argument 'root' since it ends up as a string with the actual value of:

`C:\dev\squaredup-custbuild\v1" -scomDllConfiguration=Release`

Where C:\dev\squaredup-custbuild\v1 is the actual value I passed into 'root' and the remainder is the other argument.

What is the correct way to pass both of these arguments without ending up with an amalgamation of their values?

If the issue here is caused by quotes, what can I do to solve it? (Removing the quotes is not an option: This invocation can use absolute paths which contain spaces) 

**EDIT**:
Interestingly, if I only pass root (-root="$(SolutionDir)") the value is correct, but has an additional quote on the end, leading to 'illegal character in path'. 

If I omit the last quote, everything actually works fine (!!) (-root="$(SolutionDir)). Since I'm invoking cake from VS2013 post-build events I'm not sure if I'm looking at a cake bug here, or a VS bug?

**Comment by DavidR91** [comment]
OK, after testing this out directly from the command line, it's definitely Visual Studio being crap -_-

(http://stackoverflow.com/questions/11587394/how-to-put-double-quotes-in-vs2010-post-build-step#comment36704367_11620677)

You can close this issue - apologies, I had no reason VS was incapable of parsing double quotes properly

**Comment by patriksvensson** [comment]
I see. But more importantly, did you get it to work?
If quotes are a problem, would perhaps wrapping the task execution in a custom MSBuild task solve it?

**Comment by DavidR91** [comment]
Yes, although back to possibly being a cake bug :-1: 

This command works:

`"C:\dev\squaredup-custbuild\v1\cake/cake.exe" -verbosity=diagnostic -squaredUpRoot="C:\dev\squaredup-custbuild\v1" -scomDllConfiguration="Release"`

But this does not:

`"C:\dev\squaredup-custbuild\v1\cake/cake.exe" -verbosity=diagnostic -squaredUpRoot="C:\dev\squaredup-custbuild\v1\" -scomDllConfiguration="Release"`

Note the trailing slash on "C:\dev\squaredup-custbuild\v1\ for the non-working version

Is there something inside cake which is reinterpreting the \" as the escape sequence for double quote? 

(Note that the reason I'm getting the trailing slash is because that's what VS provides with ${SolutionDir})

**Comment by devlead** [comment]
Hi @DavidR91,

I tested the following script
```csharp
var squaredUpRoot        = Argument<string>("squaredUpRoot", "Argument missing");
var scomDllConfiguration = Argument<string>("scomDllConfiguration", "Argument missing");

Information("squaredUpRoot: {0}", squaredUpRoot);
Information("scomDllConfiguration: {0}", scomDllConfiguration);
```
called like this from PowerShell
```powershell
Cake.exe -verbosity=diagnostic -squaredUpRoot="C:\dev\squaredup-custbuild\v1\" -scomDllConfiguration="Release"
```
it outputs (truncated diagnostics)
```
Compiling build script...
squaredUpRoot: C:\dev\squaredup-custbuild\v1\
scomDllConfiguration: Release
```
Calling from like this from PowerShell
```powershell
Cake.exe -verbosity=diagnostic -squaredUpRoot="C:\dev\squaredup-custbuild\v1" -scomDllConfiguration="Release"
```
it outputs (truncated diagnostics)
```
Compiling build script...
squaredUpRoot: C:\dev\squaredup-custbuild\v1
scomDllConfiguration: Release
```
Added as post build step
```
"$(SolutionDir)cake/cake.exe" build.cake -verbosity=diagnostic -squaredUpRoot="$(SolutionDir)" -scomDllConfiguration="$(ConfigurationName)"
```
and got scomDllConfiguration missing.

Added an this to the script
```csharp
Information("CommandLine: {0}", System.Environment.CommandLine);
```
In visual studio output was:
```
CommandLine: "C:\temp\priv\caketest\cake/cake.exe"  build.cake -verbosity=diagnostic -squaredUpRoot="C:\temp\priv\caketest\" -scomDllConfiguration="Debug"
```
ran same code in PowerShell and it seems to change commandline
```
CommandLine: "C:\temp\priv\caketest\cake\cake.exe"  build.cake -verbosity=diagnostic -squaredUpRoot=C:\temp\priv\caketest\ -scomDllConfiguration=Debug
```
so I changed to command cmd.exe and got this
```
CommandLine: "C:\temp\priv\caketest\cake/cake.exe"   build.cake -verbosity=diagnostic -squaredUpRoot="C:\temp\priv\caketest\" -scomDllConfiguration="Debug"
squaredUpRoot: C:\temp\priv\caketest" -scomDllConfiguration=Debug
scomDllConfiguration: Argument missing
```

I would agree this is an issue with Cake and will look into it.
meanwhile what you could to as a work around would be to change postbuild to add a space after `$(SolutionDir)`
```
"$(SolutionDir)cake/cake.exe" build.cake -verbosity=diagnostic -squaredUpRoot="$(SolutionDir) " -scomDllConfiguration="$(ConfigurationName)"
```
And just do a 
```
var squaredUpRoot =  HasArgument("squaredUpRoot") ? Argument<string>("squaredUpRoot").TrimEnd() : "Argument missing"; 
```

We will take a look at the argument parsing an post back here when it's fixed.

**Comment by devlead** [comment]
Interesting it's an .Net console "issue" they are doing something smart;)
```
args
	[0]	"build.cake"                                                            string
	[1]	"-verbosity=diagnostic"                                                 string
	[2]	"-squaredUpRoot=C:\\temp\\priv\\caketest\" -scomDllConfiguration=Debug" string

System.Environment.CommandLine
        "\"C:\\temp\\dev\\github\\cake\\src\\Cake\\bin\\Debug\\Cake.vshost.exe\" \"build.cake\" -verbosity=diagnostic -squaredUpRoot=\"C:\\temp\\priv\\caketest\\\" -scomDllConfiguration=\"Debug\""	string
```

**Comment by DavidR91** [comment]
Yeah for the time being rather than adding a space, I've been adding an additional \ 

i.e.:

`-squaredUpRoot=&quot;$(SolutionDir)\&quot;`

so I end up getting stuff like this:

`-squaredUpRoot="C:\Program Files (x86)\Jenkins\jobs\Website v2.0\workspace\v1\\"`

This seems to work, so I'm presuming that's because it ends up evaluating \\ to be an escaped \ before it considers \" ? 

But yeah, seems to be a minor issue since I can workaround it for the time being.

**Comment by devlead** [comment]
@DavidR91 ah, what would work as the msbuild format is xml :+1: 

But I'm working on an solution, will post back here as soon as I have pushed some bits.

**Comment by devlead** [comment]
And thanks for reporting the issue @DavidR91 :+1: 

Be sure to let us know if you have any questions or feedback, you can also checkout our [#cake-build/cake](https://gitter.im/cake-build/cake) Gitter channel for more interactive discussions.

**Comment by patriksvensson** [comment]
@devlead Can I close this?

**Comment by devlead** [comment]
@patriksvensson nope, not fixed yet.

**Comment by patriksvensson** [comment]
@devlead Can I close this now? :wink:

**Comment by devlead** [comment]
@patriksvensson issue still remains, investigating now

**Comment by patriksvensson** [comment]
@DavidR91 Problem seems to be fixed now. Will appear in next released version.

**Comment by DavidR91** [comment]
Hi again,

Running 0.42 I'm still seeing issues with this kind of thing 

For example this command line:

`  "C:\Program Files (x86)\Jenkins\jobs\Website v2.1\workspace\v1\Website\..\cake\cake.exe" -verbosity=verbose -squaredUpRoot="C:\Program Files (x86)\Jenkins\jobs\Website v2.1\workspace\v1\Website\..\" -scomDllConfiguration="Release"`

Gives me back this:

    More than one build script specified.
    
    Could not find a build script to execute.
    Either the first argument must the build script's path,
    or build script should follow default script name conventions.
    
    Usage: Cake.exe [build-script] [-verbosity=value]
    [-showdescription] [-dryrun] [..]`

The file on disk is build.cake and specifying it explicitly yields the same error

Is this a further parsing issue, or am I making an error here? 

Note that previously (around 0.1.30) this kind of command worked provided I did the weird escaping trick (e.g. `-squaredUpRoot="C:\Program Files (x86)\Jenkins\jobs\Website v2.1\workspace\v1\Website\\..\\"`)

**Comment by DavidR91** [comment]
From what I can tell, this issue remains regardless of the arguments provided if you execute using an absolute path:

`C:\Program Files (x86)\Jenkins\jobs\Website v2.1\workspace\v1\cake\cake.exe`

always generates the same error, even if there is a build.cake in 
* the working directory of the caller
* the same directory as the cake.exe

Is it wrongly determining information based on the assembly path/location or something? (And that's why it's choking when run via an absolute path to the EXE?)

**Comment by DavidR91** [comment]
Hmm, there is something strange when cake resides in a directory with spaces in its name - perhaps specific to this machine?

For example:

`C:\>"C:\cake walk\cake.exe"`
`Error: Illegal characters in path.`

Working directory C:, cake.exe in C:\cake walk\  along with a build.cake in C:\cake walk

**But**

This works:

`C:\>C:\cake\cake.exe C:\cake\build.cake`

Is there is something related to spaces in paths that I need to investigate?

**Comment by DavidR91** [comment]
Are notifications still enabled for this closed issue, or should I raise a new bug?

This is a pretty serious problem for me and presumably anyone calling cake under folders such as "Program Files (x86)"

**Comment by patriksvensson** [comment]
Hello David,

Sorry for not answering until now. I'm going on vacation tomorrow and will take a look at your issue then. Sorry again for the delay.

Best regards
Patrik

**Comment by patriksvensson** [comment]
Hello David,

I've been able to recreate this behavior and I'm writing a fix for it now. I will try my best to have it ready as soon as possible.

/ Patrik

**Comment by patriksvensson** [comment]
@DavidR91 I have submitted a fix for the bug and it should (finally) be fixed in the next version.
