### ISSUE TITLE
Libraries should target netstandard

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#1721]
Libraries should target `netstandard1.3` (which is compatible with both `net46` and `netcoreapp1.0`). This way we don't need to multitarget, thus no need for a bunch of  `#if NETCORE...` in our code.

`Cake` exe should still be multitargeted. We keep that `net462` and `netcoreapp1.0`

**Comment by mholo65** [comment]
Nope, not happening until `netstandard2.0`. Too much yak shaving.

**Comment by zanseb** [comment]
`netstandard2.0` has been released. Are you going to change the targets soon?

**Comment by patriksvensson** [comment]
@zanseb Probably not for a while until things have settled down a little. We need to investigate what this will mean for the code base as well.

**Comment by urajkovic** [comment]
Are there any news on this? Does Cake support netstandard2.0 libraries?

**Comment by devlead** [comment]
©urajkovic yes since 0.26.0 it does and since 0.26.1 it also works on Mono (5.4 and up required though).

**Comment by mholo65** [comment]
Libraries targets `netstandard2.0` now. Closing this...
