### ISSUE TITLE
CopyFiles(ICakeContext, IEnumerable<FilePath>, DirectoryPath, bool) is buggy

### ISSUE THREAD

**Issue by robgha01** [cake-build/cake#1729]
### What You Are Seeing?
Im using true for preserve folder structure but what i see is files getting copied to destination without its
first level root folder "Umbraco_Client", "Umbraco" for some reson the "Umbraco_Client" gets copied outside of target folder while Umbraco files gets copied to the target but not whitin its root folder "Umbraco".

### What is Expected?
I expect that the files get copied to destination and retaining its structure also not getting copied outside of target dir.

### What version of Cake are you using?
**0.20.0** also tested with **0.21.1**
### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 10

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
Im including a repro project, run the **"BuildArtifact.bat"** in the **Build** folder
https://github.com/robgha01/CakeBuild-CopyFiles-Repro

### Output Log
https://gist.github.com/robgha01/d6fb52728e4d3e3c746ae62a0cea7e5b

**Comment by robgha01** [comment]
It may be so that it for some odd reason cant handle "../" as i have my build script in a build folder ? this should not be a problem as my other project builds fine...

**Comment by devlead** [comment]
Does it work if you first use MakeAbsolute on the paths?

**Comment by robgha01** [comment]
im already using MakeAbsolute path so no.

**Comment by mholo65** [comment]
@robgha01 tried with a small repro but could not reproduce.

However, in your repro project. Do you mind cleaning out the `.tools` folder, it's currently a whole lot to clone with git. When you've done that, I can take another look using your repro project. Thanks!
