### ISSUE TITLE
Enable security via HTTPS

### ISSUE THREAD

**Issue by matkoch** [cake-build/cake#1730]
There are several security flaws across all cake products when files are downloaded without using HTTPS protocol. Most severe issue is the download of _packages.config_ because there is no time between downloading and continuing code execution.

**Comment by devlead** [comment]
Duplicate of cake-build/website#40

We're in the middle of migration to new infrastructure, where both SSL and HSTS will be enabled.

**Comment by matkoch** [comment]
This is not a duplicate, it's about ensuring that in fact the correct bootstrapper is downloaded.

**Comment by gep13** [comment]
@matkoch it was marked as a duplicate due to the fact that you couldn't have one, without the other.  I believe that all necessary changes in this regard have now been made.

**Comment by matkoch** [comment]
Just to be correct, the other issue was closed _without_ fixing the issue I've described here.

**Comment by gep13** [comment]
@matkoch yes, it was, and you will notice as well that it was immediately opened again.

**Comment by matkoch** [comment]
@gep13 as far as I remember I've pointed out the issue in gitter 🤔 Anyways, great that you've fixed it.

**Comment by matkoch** [comment]
Still no public announcement on that?

**Comment by matkoch** [comment]
@gep13 @devlead  ?

**Comment by devlead** [comment]
@matkoch post is merged and will be out later today

**Comment by matkoch** [comment]
@devlead are you going to do anything else? Not everyone follows up on blog posts and twitter...

**Comment by gep13** [comment]
@matkoch what else would you suggest?

**Comment by devlead** [comment]
I'm going to have a beer and that's about it.

**Comment by matkoch** [comment]
@devlead enjoy your beer 👍
@gep13 following up here: https://github.com/cake-build/website/pull/398#issuecomment-325134731
