### ISSUE TITLE
GitLabCI variable changes.

### ISSUE THREAD

**Issue by phillipsj** [cake-build/cake#1731]
I stumbled across this [documentation](https://docs.gitlab.com/ce/ci/variables/README.html#9-0-renaming) today where the environment variables have had their names changed for the 9.0 release.  I don't know if this will effect anything currently, but worth putting on the radar.

**Comment by patriksvensson** [comment]
Hmm, it should be safe to look for both values I think unless I've missed something?

Great find @phillipsj!

**Comment by Roemer** [comment]
The Gitlab "wrapper" suffers the same issue the Jenkins one does: It has several "xxxInfo" classes. Now with the renaming, new classes should be introduced and properties should be moved between them. Would it be acceptable to reduce the classes to one or two and in the same time, add the new 9.0 names as alternative?

**Comment by phillipsj** [comment]
@devlead @gep13 @patriksvensson I will take this one if cool with you all.

**Comment by devlead** [comment]
Knock yourself out 👍

**Comment by phillipsj** [comment]
Linked to PR #1866

**Comment by patriksvensson** [comment]
Resolved via PR #1866.
