### ISSUE TITLE
Extend DownloadFile to allow AcceptEncoding gzip

### ISSUE THREAD

**Issue by Roemer** [cake-build/cake#1752]
DownloadFile should be extended (probably the ```DownloadFileSettings``` class) to allow setting the ```AcceptEncoding: gzip``` header. This allows to optimize the traffic in some cases (like when getting xmls or other texts).

Should not be a big deal.
It's probably enough to add ```AutomaticDecompression = DecompressionMethods.GZip | DecompressionMethods.Deflate``` to the ```HttpClientHandler``` in the ```GetHttpClient``` method.
We could even think to add this anyway as it should be able to not use compression if the webserver does not support it. What do you think?

**Comment by gep13** [comment]
@Roemer sounds like a good idea to me. Would you be in a position to do a PR for this?

**Comment by Roemer** [comment]
Yes I would.
