### ISSUE TITLE
XmlPoke always writes the xmldeclaration even if the original file didn't have one

### ISSUE THREAD

**Issue by Roemer** [cake-build/cake#1759]
As the title says, when using XmlPoke, it always writes the declaration.

There are two possibilities:
1. Add an OmitXmlDeclaration flag to XmlPokeSettings to define if the declaration should be written or not.
2. Check in XmlPoke if the original one has a declaration and either write it or not.

Which one should we prefer?

**Comment by gep13** [comment]
@Roemer of the two options, I think I prefer the second one.

@cake-build/cake-team ?

**Comment by Roemer** [comment]
I crated a PR with solution 2.
