### ISSUE TITLE
Local function using global variable does not compile

### ISSUE THREAD

**Issue by sandermvanvliet** [cake-build/cake#1769]
### What You Are Seeing?
When the build.cake script contains a local method that uses a variable global to the script it does not compile.
Given the following build.cake script:

```
var foo = "bar";

void Dwim()
{
	Verbose("foo: " + foo);
}

Task("Default")
	.Does(() => {
		Dwim();
	});

RunTarget("Default");
```
When running `./build.sh --verbosity=diagnostic` it reports the following error:

```
Compiling build script...
unknown.cake (2338,20): The name `foo' does not exist in the current context
```

### What is Expected?
The script compiles and the local function is able to use the variable `foo`.

### What version of Cake are you using?
0.21.1

### Are you running on a 32 or 64 bit system?
64 bit. 

### What environment are you running on?  Windows? Linux? Mac?
OS X 10.12.6 (16G29)
`mono --version` reports: `5.0.1.1 (2017-02/5077205 Wed May 31 14:47:04 BST 2017)`
`dotnet --info` reports: 
```
Version:            2.0.0
Commit SHA-1 hash:  cdcd1928c9
```
### Are you running on a CI Server?  If so, which one?
No.

### How Did You Get This To Happen? (Steps to Reproduce)
See build.cake script above.

### Output Log
```
Feeds used:
  /Users/sandervanvliet/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /Users/sandervanvliet/Projects/cake-method-repro/tools/packages.config are already installed.
unknown.cake (2338,20): The name `foo' does not exist in the current context
Error: An error occurred while executing build script.
```

### Remarks
If I change the script above to:
```
var foo = "bar";

void Dwim(string foo)
{
	Verbose("foo: " + foo);
}

Task("Default")
	.Does(() => {
		Dwim(foo);
	});

RunTarget("Default");
```
it works as expected.

I've also tested this with the 0.22.0-alpha0090 package off of MyGet, that apparently fixes the issue.
My **assumption** at this point is that probably this is because Roslyn got upgraded but I've not been able to validate that.

**Comment by devlead** [comment]
@sandermvanvliet it's fixed in the next version because it's using Roslyn, current and previous versions are using mono scripting on Mono (on .NET Core it's using Roslyn on all platforms already).

What will work xplat today is to use a delegate instead something like
```cake
Action<string> Dwim = foo=>{
    Verbose("foo: {0}", foo);
}
```
or using a static method
```cake
public class FooBar
{
    public static void Dwim(ICakeContext context, string foo)
    {
        context.Verbose("foo: {0}", foo);
    }
}
```
above accessed as `FooBar.Dwim(Context, foo);`

**Comment by sandermvanvliet** [comment]
I did see some reference that Mono scripting was already taken out of the current release build but I understand that is not the case?
Is there any documentation/guidance on how to make sure Cake runs using .Net Core?

**Comment by devlead** [comment]
It's taken out of the next upcoming release. 

We're working on better guidance around .NET Core, meanwhile here's an example of a project using it 
https://github.com/devlead/BitbucketPipelinesShield

**Comment by devlead** [comment]
Mono scripting no longer used so this can be closed.
