### ISSUE TITLE
Add aliases to check for file/directory existence

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#177]
Not sure why this doesn't exist in the common library already, but it would be nice with some cake aliases to check for existence of files and directories.

```csharp
if(DirectoryExist("./src"))
{
   if(FileExist("./src/temp.txt")
   {
      Information("Both directory and file exist.");
   }
}
```

**Comment by RichiCoder1** [comment]
Most people that'd be using Cake are probably coming from C# land. Wouldn't this be confusing vs the .Net way of just doing File.Exists & Directory.Exists?

**Comment by patriksvensson** [comment]
System.IO.File.Exist does not do all the nice things that's associated with `FilePath` and `DirectoryPath` such as making the provided path absolute to the script location :smile:

**Comment by vktr** [comment]
Grabbing.
