### ISSUE TITLE
NuGetHasSource call do not take care of ArgumentCustomization in NuGetSourcesSettings

### ISSUE THREAD

**Issue by hoffe86** [cake-build/cake#1773]
### What You Are Seeing?
When I am using NuGetHasSource with NuGetSourcesSettings including ArgumentCustomization like in the example below the ArgumentCustomization will not applied to the call of the nuget.exe.

```
var nugetSourceSettings = new NuGetSourcesSettings
{
	UserName = "VssSessionToken",
	Password = accessToken,
	IsSensitiveSource = true,
	Verbosity = NuGetVerbosity.Detailed,
	ArgumentCustomization = args => args.Append("-ConfigFile " + solutionDirectory + "/NuGet.config")
};

if (!NuGetHasSource(internalFeed, nugetSourceSettings))
{
	Information("Add internal feed '{0}' as nuget source", internalFeed);
	NuGetAddSource("Internal", internalFeed , nugetSourceSettings);
}
```

**Console Output:**
> 
Executing: "C:/Daimler/FB/fb-timemgmt-service/Build/tools/NuGet.exe" sources List
Registered Sources:

  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json
  2.  Microsoft Visual Studio Offline Packages [Enabled]
      C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
  3.  Microsoft Azure Service Fabric SDK [Enabled]
      C:\Program Files\Microsoft SDKs\Service Fabric\packages

### What is Expected?
What I expected is that the nuget.exe will be called like this:

> 
Executing: "C:/Daimler/FB/fb-timemgmt-service/Build/tools/NuGet.exe" sources List -ConfigFile C:/[Path to Repository]/[solutionDirectory]/NuGet.config
Registered Sources:
...

I already checked the implementation of [NuGetSources class](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/NuGet/Sources/NuGetSources.cs) and it seems the Run function call (L141+142) in the method 'HasSource' will be called with no valid ProcessArgumentBuilder (is null).

### What version of Cake are you using?
0.21.1
### Are you running on a 32 or 64 bit system?
64-Bit
### What environment are you running on?  Windows? Linux? Mac?
Windows
### Are you running on a CI Server?  If so, which one?
VSTS
### How Did You Get This To Happen? (Steps to Reproduce)
See above
### Output Log
No log

**Comment by devlead** [comment]
Correct looks like it works directly with the process arguments with HasSource, I'll take a look at correcting that.

**Comment by devlead** [comment]
@hoffe86 I've now raised PR #1774 to address this.

I've also added a ConfigFile property to NuGetSourcesSettings,
```cake
FilePath nuGetConfig = File("./NuGet.config");
var settings = new NuGetSourcesSettings {
    ConfigFile = nuGetConfig 
};
```

so in your case you shouldn't need ArgumentCustomization per say, but that should work too now.


If you want to test if it's addressed you can test with the artifacts avail at
https://ci.appveyor.com/project/cakebuild/cake/build/0.22.0-PullRequest.1774+86.build.3834/artifacts
