### ISSUE TITLE
Can't run netcoreapp1.x tests when .NET Core 2 is installed

### ISSUE THREAD

**Issue by ErikSchierboom** [cake-build/cake#1779]
### What You Are Seeing?

Can't run netcoreapp1.x tests when .NET Core 2 is installed. See also: https://github.com/xunit/xunit/issues/1412

### What is Expected?

netcoreapp1.x tests run when .NET Core 2 is installed

### What version of Cake are you using?

0.21.1

### Are you running on a 32 or 64 bit system?

64-bit system

### What environment are you running on?  Windows? Linux? Mac?

Windows and Mac

### Are you running on a CI Server?  If so, which one?

None

### How Did You Get This To Happen? (Steps to Reproduce)

Run the build.ps1 or build.sh script when having only .NET Core 2 installed.

**Comment by adamhathcock** [comment]
You can run both if you also install a 1.0 runtime.  But yes, it won't work because of: https://github.com/cake-build/cake/issues/1781

**Comment by devlead** [comment]
fixed by #1778
