### ISSUE TITLE
Add option to enable MSBuild binary logging

### ISSUE THREAD

**Issue by djdelaney** [cake-build/cake#1791]
Microsoft has added a binary logger to MS Build 15.3 that logs all build details to a structured binary log for easy debugging:

http://msbuildlog.com/

It would be useful to enable/control this log from MSBuildSettings in Cake.

**Comment by patriksvensson** [comment]
@djdelaney Sounds like a really useful idea! Do you want to send a PR for this? 😄

**Comment by mholo65** [comment]
Fixed in #1792
