### ISSUE TITLE
Is there a way to save a modified parsed project ?

### ISSUE THREAD

**Issue by scemino** [cake-build/cake#1795]
### What You Are Seeing?
ProjectAssemblyReference has a property "Private" which is writable.

### What is Expected?
If I modify this property, I expect to be able to save this modification.

### What version of Cake are you using?
Version 0.19.3+Branch.main.Sha.c8a44d4c031e5c9631ec3044536c6af70f3fb04f

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
```CSharp
var parsedProject = ParseProject("<your project path here>");
foreach(var asmRef in parsedProject.References){
    if(asmRef.HintPath==null) continue;
    asmRef.Private = true;
}
```

**Comment by augustoproiete** [comment]
(Moving to GitHub Discussions / Q&A)
