### ISSUE TITLE
NuGet Downloads (#addin) have a second sub folder

### ISSUE THREAD

**Issue by minimaltesty** [cake-build/cake#1797]
### What You Are Seeing?
Prior to v0.22 the #addin download was in ./tools/Addins/[MYPACKAGENAME].
Now, since v0.22 the path is: ./tools/Addins/[MYPACKAGENAME]/[MYPACKAGENAME]

Also the #tool download is behaving the same, now.
Prior v0.22: ./tools/7-Zip.CommandLine
Now: ./tools/7-zip.commandline/7-Zip.CommandLine
>> See the cases

### What is Expected?
Expected is behavior prio to v0.22

### What version of Cake are you using?
0.22

### Are you running on a 32 or 64 bit system?
64 Bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No, local

**Comment by patriksvensson** [comment]
This behavior have changed since version 0.22.0 and is by design. The reason for this is to be able to predict the installation path on case sensitive operating systems when a path is involved.

**Comment by minimaltesty** [comment]
Thanks for clarification. This is a breaking change, for me. I've to update all my build scripts. Reason is, that I've to copy dll files within the downloaded nuget packages. Mybe this is another issue/question.
I've a package that has dependencies to other packages (pkgA depends on pkgB, pkgC and pkgD). In cake-Script I download pkgA with #addin. Now, there are 4 folders within the ./tools dir:
- pkgA
- pkgB
- pkgC
- pkgD
But the dll in pkgA is not usable because the referenced dll's of the other three packages are "missing". To solve this, I've three CopyFiles method calls:
- pkgB/* to pkgA/
- pkgC/* to pkgA/
- pkgD/* to pkgA/

So because the paths have changed now, all scripts for all projects have to be changed.

**Comment by patriksvensson** [comment]
@minimaltesty I understand. However, I wouldn't rely on the location of downloaded packages since this is a subject to change either by us (like what just happened) or the nuget client. I would recommend of instead of using the #tool preprocessor directive (which only should be used when installing tools used by an alias) installing packages with the `NuGetInstall` alias and set the output directory.

**Comment by gep13** [comment]
@minimaltesty also remember that you can pin to an earlier version of Cake (https://cakebuild.net/docs/tutorials/pinning-cake-version) which would take you back to where you were before the release of 0.22.0.

**Comment by minimaltesty** [comment]
Thanks for your fast responses!

@gep13 yes - that was my short solution to that for one project. But also that needed to change repository (adding the packages.config to the ./tools dir)
@patriksvensson ok, I will try that.

**Comment by gep13** [comment]
@minimaltesty perfect!  Adding of the packages.config file, has been a long standing recommendation when using Cake: https://cakebuild.net/docs/tutorials/getting-started
