### ISSUE TITLE
Addin doesn't support latest cake 0.22.0

### ISSUE THREAD

**Issue by christamlyn-bridge** [cake-build/cake#1799]
### What You Are Seeing?
Error on build due to reference to 0.17.0 of cake
```
14:18:32.510 The addin Cake.Docker will reference Cake.Docker.dll.
14:18:32.527 Verifying assembly 'Cake.Docker, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
14:18:32.530 Error: Cake.Core.CakeException: The assembly 'Cake.Docker, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' 
14:18:32.530 is referencing an older version of Cake.Core (0.17.0). 
14:18:32.530 This assembly need to reference at least Cake.Core version 0.22.0
```
Are there plans to upgrade the references beyon 0.17.0?
### What version of Cake are you using?
0.22.0
### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
Windows
### Are you running on a CI Server?  If so, which one?
n/a

**Comment by gep13** [comment]
@christamlyn-bridge you can find more information about this in our blog post https://www.cakebuild.net/blog/2017/09/cake-v0.22.0-released along with a workaround. This issue would best be raised on the Cake.Docker repository.

**Comment by kmc059000** [comment]
I received a similar problem and read the comment from @gep13 

In addition, Cake recommends pinning the version of cake in your project so that you are required to opt-in to new releases. Pinning the version would have prevented this error.

**Comment by christamlyn-bridge** [comment]
yeah thanks, we pinned as well.  Pinned to 21.1 which isn't what the error suggests it needs but seemed to work OK.
