### ISSUE TITLE
Cake DSL '0.22.0' accidentally removed NUnit3Settings.ResultFormat property. How else do we specify v2 style test report xmls for nunit?

### ISSUE THREAD

**Issue by curiousdev** [cake-build/cake#1800]
### Sample DSL - That No Longer Compiles
```
Task("UnitTest")
    .Does(() =>
    {
	   NUnit3("./**/bin/" + configuration + "/*Test*.dll", new NUnit3Settings {
			Results = "./testresults/NUnitTestResults.xml",
			ResultFormat = "nunit2",     // <--------- THIS IS NO LONGER SUPPORTED
        });
    });
```

### What You Are Seeing?
Cake DSL no longer support NUnit3Settings.ResultFormat property. This property provided access to the NUnit3-Console.exe's results paramter. [doc](https://github.com/nunit/docs/wiki/Console-Command-Line)

Is there another Cake DSL property to specify NUnit report format.

We need this to force NUnit3-Console.exe to produce an legacy v2 xml report. Judging from the commit logs, I don't see why this property was removed. NUnit3-Console.exe still provides the -Result parameter to specify this information.

### What version of Cake are you using?
Worked in `0.21.0`
Broken in  `0.22.0`

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

**Comment by gep13** [comment]
As documented on the release notes, and release blog post (https://cakebuild.net/blog/2017/09/cake-v0.22.0-released) there were a number of breaking changes in 0.22.0 of Cake. We also mentioned this several times in the Gitter Chat room, but it is possible you missed this.  If you feel there is another way to communicate these changes we are open to suggestions.

As mentioned in that blog post, we highly recommend pinning to a specific version of Cake, that way these changes won't affect you until you are ready to upgrade Cake.

Please see the video in the linked documentation article from the blog post, and let us know if you have any questions.

**Comment by curiousdev** [comment]
Yep, I read through the blog post. Nothing indicated that this particular property needed to be removed. I am happy to introduce a pull-request to resurrect this property. The under-lying NUnit2-Console.exe still provides the -Result switch.

**Comment by gep13** [comment]
@curiousdev the release notes put at this issue: https://github.com/cake-build/cake/issues/1665 which is where the change was introduced.

**Comment by curiousdev** [comment]
Yeah, I am looking through that now to see if there another way specify the result format.

**Comment by gep13** [comment]
To get back to a working build, for now, you can pin specifically to use Cake 0.21.1.

**Comment by mholo65** [comment]
Unfortuneatly documentation broke on this one https://cakebuild.net/api/Cake.Common.Tools.NUnit/NUnit3Settings/5FA90E73 but it's a collection of these (https://cakebuild.net/api/Cake.Common.Tools.NUnit/NUnit3Result/) you need to add instead.

**Comment by curiousdev** [comment]
Yep, we've pinned to 0.21 and are now unblocked. Looking at [#1665](https://github.com/cake-build/cake/issues/1665) I can update my DSL to comply with the new apis.

**Comment by curiousdev** [comment]
Where may I submit a PR to provide an example documentation for others to be unblocked?

**Comment by mholo65** [comment]
@daveaglick any reason why wyam fails to render the above type as a link? `ICollection<NUnit3Result>`

**Comment by daveaglick** [comment]
@mholo65 There were recently several related issues dealing with generic types and open vs. closed (https://github.com/Wyamio/Wyam/issues/494). Those have all been resolved for the upcoming release, but this may not fall into that category.

In this case, `ICollection` isn't a type in any of the Cake assemblies we're generating docs for - Wyam doesn't know where to find it to generate a link. If the generic type param `NUnit3Result` were part of a type that we were documenting, then it would show up in a "Type Parameters" section with a link. Unfortunately, Wyma doesn't currently link individual generic type parameters of return types.

What would be the desired behavior here?

**Comment by mholo65** [comment]
@daveaglick makes sense! But in this case `NUnit3Result` is a type that is documented. See [here](https://cakebuild.net/api/Cake.Common.Tools.NUnit/NUnit3Result/).

We could also solve by adding a `cref` in the documentation for the property (which btw is quite bad :smile: I have no idea how that slipped review or `StyleCop.Analyzers`)

**Comment by mholo65** [comment]
@curiousdev documentation goes to https://github.com/cake-build/website

Altough, documentation about pinning Cake versions are already available [here](https://cakebuild.net/docs/tutorials/pinning-cake-version).

I'm closing this issue now, please reopen or resch out to us on gitter if you don't find a way to specify `nunit2` format for result output.

**Comment by gep13** [comment]
@mholo65 I think the suggestion here was to provide some updated documentation on how to use the NUnit Aliases as a result of these breaking changes. Perhaps via a `<code>` section in the correct xml documentation section. Or has that already been done?

**Comment by mholo65** [comment]
@gep13 ah, yes, that should be done! 

@daveaglick regarding documentation, that was a brainfart from my side. It was only the Value sectionbthat confused me.

**Comment by Roemer** [comment]
The change is documented here: https://github.com/cake-build/cake/pull/1666

As a quick summary, the results should now be defined like this:
```csharp
settings.Results = new[]
{
    new NUnit3Result { FileName = "NewTestResult.xml", Format = "nunit2", Transform = "nunit2.xslt" },
    new NUnit3Result { FileName = "NewTestResult2.xml", Format = "nunit3" }
};
```

**Comment by phillipsj** [comment]
Happy to take this and do the PR.  Just let me know.
