### ISSUE TITLE
NuGetVersion and CommitDate are null with 0.22.1

### ISSUE THREAD

**Issue by david-driscoll** [cake-build/cake#1807]
### What You Are Seeing?
GitVersion returns null for `NuGetVersion` and `CommitDate` 

### What is Expected?
GitVersion is returning proper values for `NuGetVersion` and `CommitDate` 

### What version of Cake are you using?
0.22.1

### Are you running on a 32 or 64 bit system?
x64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
GitLab Runner

**Comment by devlead** [comment]
Fixed by #1808
