### ISSUE TITLE
(build) Use tool resolution for SignClient in buildscript

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#1809]
or add it as a proper Cake.Common tool.

**Comment by devlead** [comment]
Currently fails because new version path 
Previously was
```
SignClient
```
Now will be something like
```
SignClient.0.5.0-beta4
```

**Comment by devlead** [comment]
Also update to latest version 0.8.1

**Comment by gep13** [comment]
There is already a Cake.SignClient addin, it just hasn't been finished, as we never came to a decision about how to actually call it. The repo lives under Cake-Contrib org.

**Comment by devlead** [comment]
Ok 👍 if it doesn't take account for the 0.8.0 and upwards have framwork monikers in tools folder, that's also something to watch out for.

**Comment by devlead** [comment]
Wonder if we should just sign something in normal builds too, even if we don't publish anything it's nice to know signing is still working without having to find out during release 😎

**Comment by devlead** [comment]
Oh and new versions have changed contract so zip command fails now... 🤷‍♂️

**Comment by devlead** [comment]
Yes I'm totally testing in production 😄

**Comment by gep13** [comment]
Ha ha! I haven't looked at the addin code in a while, so not sure what state it is in. Now that we have the DotNetToolExecutor, or whatever it is called, should be easy to finish that addin.

**Comment by devlead** [comment]
yip! 👍
