### ISSUE TITLE
(build) Update addins to ones compatible with 0.22.x>

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#1810]
So temporary assembly verification opt-out can be removed.

**Comment by devlead** [comment]
- [x] Cake.Coveralls - _RELEASED_
- [ ] Cake.Twitter - _PR EXISTS_
- [ ] Cake.Gitter - _PR EXISTS_

**Comment by devlead** [comment]
Haven't submitted the PR yet though ;)

**Comment by gep13** [comment]
@devlead ooops, my bad 😄
