### ISSUE TITLE
Add code sample to build system properties

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#1811]
As the build system properties go pretty deep it would be really helpful if the properties had code samples i.e.
[Jenkins BuildNumber](https://cakebuild.net/api/Cake.Common.Build.Jenkins.Data/JenkinsBuildInfo/CF72FD83)

Not super obvious that it's accessed like this
`BuildSystem.Jenkins.Environment.Build.BuildNumber`

**Comment by Roemer** [comment]
This comes back to my question when I did the PR for additional Jenkins variables:
Do we really need to have them that deep?
Stuff like the Workspace could be in Build or in Node, Changes are also related to Build or Repository, Job is also related to Build and and and. All in all if you need something it's always a search until you found what you need.
I suggest having only one `Environment` class which directly contains all environment variables.

**Comment by devlead** [comment]
Well they're what they are in a way, we don't want unnecessary break too many scripts out there if it's not for real benefit.

**Comment by phillipsj** [comment]
This one is hanging out here, I will take it.

**Comment by devlead** [comment]
@phillipsj Excellent I've assigned issue to you.
