### ISSUE TITLE
Exception Message should be shown rather than "One or more errors occurred."

### ISSUE THREAD

**Issue by joshclark** [cake-build/cake#1815]
### What You Are Seeing?
Exception messages are not displayed. Instead "One or more errors occurred." is shown as the error message.

### What is Expected?
When an exception is thrown with a specific error message, I would expect to see that that text in the console output.

### What version of Cake are you using?
Version 0.22.2+Branch.main.Sha.c8630875bc14ce11aa758e0dcd55f691da5f602b

### Are you running on a 32 or 64 bit system?
64 bit Windows

### What environment are you running on?  Windows? Linux? Mac?
64 bit Windows

### Are you running on a CI Server?  If so, which one?
No. Command line

### How Did You Get This To Happen? (Steps to Reproduce)
1.  test.cake:
```
Task("Default")
  .Does(() =>
{
  throw new Exception("Foo");
});

RunTarget("Default");
```

2. Run cake: `Cake test.cake`

3. Output:
```
========================================
Default
========================================
An error occurred when executing task 'Default'.
Error: One or more errors occurred.
```

**Comment by SIkebe** [comment]
I have same problem.
Exception is printed as below when you use `netcoreapp1.0` as `TargetFrameworks` of Cake.exe, but not when `net461`
![error-netcoreapp1 0](https://user-images.githubusercontent.com/17608272/30744724-633ec252-9fde-11e7-9453-490a37742f3d.png)
.

**Comment by patriksvensson** [comment]
The phrase `One of more errors occured` is the message part of an `AggregateException`, so I suspect this has to do with [this change](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/ActionTask.cs#L112) that was introduced recently.

**Comment by devlead** [comment]
Ah probably I can take a look at sorting that.

**Comment by dracan** [comment]
I've just been getting this, and wasn't sure what the exception actually was. So I temporarily handled it in a try catch block to dump out the output.

Obviously only a temporary solution until this issue is fixed, but I thought it worth pasting the code here in case anyone else saw this ticket and didn't know what their exception was either ...

    try
    {
        // Some code
    }
    catch(AggregateException aex)
    {
        aex.Handle(ex => { Console.WriteLine(ex.ToString()); return false; });
    }

Hopefully this'll be resolved soon, as that's obviously bloat in my Cake file! :)

**Comment by devlead** [comment]
@dracan running cake with diagnostic verbosity will give the full stack trace too.

**Comment by dracan** [comment]
@devlead Ah, cool - I had tried verbose, but not diagnostic.
