### ISSUE TITLE
Support task dependees (reverse dependencies)

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#1818]
It would be nice to let tasks specify that they are dependencies of other tasks. It would also be good if we could tell whether dependencies are required or not. This would open up for better extensibility and specialized build systems like `Cake.Recipe`.

We could call this method `IsDependeeOf` (suggestions for other names are greatly appreciated).
I would also suggest that we add support for optional dependencies while we're at it.

**Example:**

```csharp
Task("A");
Task("B").IsDependentOn("A", required: true);
Task("C").IsDependentOn("B").IsDependeeOf("D");
Task("D").IsDependeeOf("E", required: false);

RunTarget("D");
```

Woud result in the following task traversal.

`A` -> `B` -> `C` -> `D`

**Example 2:**

This would allow for custom build systems distributed via NuGet let their consumers add custom targets and tell Cake when to run them.

```csharp
#load nuget:?package=supercoolbuildsystem&version=1.0.0

Task("My-Unit-Tests")
  .IsDependeeOf("Run-Unit-Tests")
  .Does(() =>
{
  // Do stuff here
});

SuperCoolBuildSystem.Run();
```

Would result in the following hypothetical task traversal.

`Clean` -> `Build` -> `My-Unit-Tests` -> `Run-Unit-Tests` -> `RunStuff`

Using an optional dependency, `SuperCoolBuildSystem` could do the same thing, by adding an optional dependency on `My-Unit-Tests` and thus make it convention based.

**Comment by jnm2** [comment]
I would have suggested `IsDependencyOf`.

**Comment by Roemer** [comment]
I would have suggested `IsRequiredFor` which would make it easier to see very quickly what kind of depencendy it is. Now you need to read it really carefully and only the last characters diverge.
