### ISSUE TITLE
Missing Cake method for nuget list

### ISSUE THREAD

**Issue by bravecobra** [cake-build/cake#1821]
Although most NuGet cli commands are supported, the command `list` (https://docs.microsoft.com/en-us/nuget/tools/nuget-exe-cli-reference#list) is not.
Adding this one, will allow the investigate/list what packages a nuget server offers. All suboptions, as per nuget 4.3, are to be implemented offering support for semver 2.0

**Comment by mholo65** [comment]
@bravecobra Thanks! Are you in a position to send a PR?

**Comment by bravecobra** [comment]
Not at the moment, but I would guess the logic would be similar to the implementation NuGet.Client has, which implements the List command and prints out the found packages to the screen as implemented in https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Commands/ListCommand/ListCommandRunner.cs
Instead of outputting them, they would need to be returned as some sort of list.

**Comment by mholo65** [comment]
@bravecobra currently, NuGet aliases shell out to `nuget.exe`. So the implementation would probably just call `nuget.exe list` with correct parameters. Quite straightforward.

Here's the help for that command.
```
NuGet Version: 4.3.0.4406
usage: NuGet list [search terms] [options]

Displays a list of packages from a given source. If no sources are specified, all sources defined in %AppData%\NuGet\NuGet.config are used. If NuGet.config specifies no sources, uses the default NuGet feed.

     Specify optional search terms.

options:

 -Source +                     A list of packages sources to search.
 -Verbose                      Displays a detailed list of information for each package.
 -AllVersions                  List all versions of a package. By default, only the latest package version is displayed
                               .
 -Prerelease                   Allow prerelease packages to be shown.
 -IncludeDelisted              Allow unlisted packages to be shown.
 -Help                    (?)  help
 -Verbosity                    Display this amount of details in the output: normal, quiet, detailed.
 -NonInteractive               Do not prompt for user input or confirmations.
 -ConfigFile                   The NuGet configuration file. If not specified, file %AppData%\NuGet\NuGet.config is use
                               d as configuration file.
 -ForceEnglishOutput           Forces the application to run using an invariant, English-based culture.

examples:

nuget list

nuget list -verbose -allversions

For more information, visit http://docs.nuget.org/docs/reference/command-line-reference
```

**Comment by bravecobra** [comment]
Yes, but that'll just print the output to the screen, which is not what we want here. We would need to grab the output to put it in a list, which could then be used in the Cake script. The correct package is indirectly already referenced, so why not make use of it?

**Comment by bravecobra** [comment]
As @devlead just mentioned to me, Cake.NuGet was not the correct place to be looking for an entry point, thus my conclusion above is to be discarded ;) Tnx for the remark.
