### ISSUE TITLE
NUnit: Add support for /labels

### ISSUE THREAD

**Issue by richardgavel** [cake-build/cake#1833]
NUnit 2.x includes a "/labels" parameter, which is needed for the most detailed reporting when SpecFlow test are run thru the NUnit 2 test runner. http://specflow.org/documentation/Reporting/

**Comment by phillipsj** [comment]
@devlead @gep13 if this is okay with you all I will take it.

**Comment by patriksvensson** [comment]
@phillipsj Go ahead! 😄

**Comment by phillipsj** [comment]
References PR #1867

**Comment by devlead** [comment]
fixed by #1867
