### ISSUE TITLE
Fix Chocolatey Package

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#1840]
Since we are embedding assemblies into the Chocolatey Package, and the Package Validator rules have been increased, we need to include a verification.txt into the package.

**Comment by devlead** [comment]
So basically just add a file like below?
```txt
VERIFICATION
Verification is intended to assist the Chocolatey moderators and community
in verifying that this package's contents are trustworthy.

This package is published by the Cake Project itself. The binaries are 
identical to other package types published by the project, in particular
the Cake.Portable nuget package.
```

**Comment by gep13** [comment]
Yip, that pretty much covers it.

More information here:

https://github.com/chocolatey/package-validator/wiki/VerificationFileMissing

**Comment by devlead** [comment]
yeah read that, not über clear what the file should contain reading that wiki though :)

**Comment by devlead** [comment]
See that 
_Providing checksums in verification is helpful, but OPTIONAL_

So above and we should be good to go.

**Comment by gep13** [comment]
Any suggestions on how the wiki can be improved would be welcome :-)

**Comment by waynebrantley** [comment]
What does it take to get this approved?
https://chocolatey.org/packages/cake.portable/0.22.2

The problem is the addins - like https://github.com/cake-contrib/Cake.FileHelpers/issues/17 are requiring the 0.22 version.  

Chicken and egg!

**Comment by gep13** [comment]
@waynebrantley the fix is as described above. We need to add the verification.txt file to the package and re-push to chocolatey.org.

In the interim, so can install that version of the chocoatey package by specifying the version number in the command line. Or you can pin to earlier versions of both cake, and cake.filehelpers.
