### ISSUE TITLE
SignTool is not found with latest windows 10 SDK

### ISSUE THREAD

**Issue by bravecobra** [cake-build/cake#1855]
With the latest Windows 10 SDK installed on a Windows 10 mahcine, the signtool.exe is no longer found by Cake. The new installation path is `C:\Program Files (x86)\Windows Kits\10\bin\10.0.15063.0\(x86|x64|arm|arm64)`. Note the extra version number and the platform folders.  there is an extra signtool under `C:\Program Files (x86)\Windows Kits\10\App Certification Kit`. None of these paths as covered in `src/Cake.Common/Tools/SignTool/SignToolResolver.cs`.

**Comment by phillipsj** [comment]
@devlead @gep13 @bravecobra  happy to take this one.

**Comment by patriksvensson** [comment]
@phillipsj Don't let me stop you! 😉

**Comment by phillipsj** [comment]
@patriksvensson Any thoughts on the arm folders?  Seems like that would be a separate platform choice and right now only x86 and x64 are supported.

**Comment by devlead** [comment]
Fixed by  #1868 and #1925

**Comment by dskipper99** [comment]
I believe there is a recurrence of this particular issue.

Signing via ClickOnce is fine in Visual Studio, but when triggered from cake i receive the following:

  C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(4279,5): error MSB3482: An error occurred while signing: SignTool.exe was
 not found at path C:\Users\AG49101\OneDrive - Anthem\Documents\fep-m1cd-command-center\signtool.exe. [C:\Users\AG49101\OneDrive - Anthem\Documents\fep-m1cd-command-center\M1CD.vbproj]

Is there a workaround for this issue?
