### ISSUE TITLE
Simple token find/replace in file?

### ISSUE THREAD

**Issue by DavidR91** [cake-build/cake#186]
Kind of a feature suggestion: Is it possible to add an ultra-simple placeholder replacement to cake? (but not enforcing any particular style of placeholder/token - e.g. don't force {{token}} or whatever)

So far I've been using File.ReadAllText(<whatever>).Replace(...) but it's a bit dirty

I presume the [TextTransformation](http://cakebuild.net/api/cake.common.text/3aaa8599/) stuff might support this, but it's not very clear how to use it. So if it is already supported, is it possible to add better documentation/examples for the text transforms?

**Comment by patriksvensson** [comment]
Hello David,

Yes, the [TextTransformation](http://cakebuild.net/api/cake.common.text/3aaa8599/) alias need some examples. I will add some example code and documentation for it tonight. Thank you for bringing this to my attention!

Here is a short example of how to use the [TextTransform](http://cakebuild.net/api/cake.common.text/5e93c90a/8124a2e8/) and the [TransformTextFile](http://cakebuild.net/api/cake.common.text/5e93c90a/3af41228/) aliases:

```csharp
// Transform string template.
var text = TransformText("Hello <%subject%>")
   .WithToken("subject", "world")
   .ToString();

// Transform template found on disc.
text = TransformTextFile("./template.txt")
   .WithToken("subject", "world")
   .ToString();

// Save a transform to disc.
TransformText("Hello <%subject%>")
   .WithToken("subject", "world")
   .Save("./output.txt");
```

Thanks again! :smile:

**Comment by patriksvensson** [comment]
@DavidR91 Your suggestion about being able to assign the token is an interesting idea. Will take a look at this as well (since it's not supported at the moment).

**Comment by patriksvensson** [comment]
@DavidR91 Made an attempt add configurable placeholders in PR #187. Will appear in next version.

**Comment by DavidR91** [comment]
Awesome! And thanks for the text transform example too

**Comment by patriksvensson** [comment]
@DavidR91 You can use custom text transformation placeholders now as well in v0.1.34. You can read updated documentation here: http://cakebuild.net/api/cake.common.text/5e93c90a/48145e1f/
