### ISSUE TITLE
Impove error reporting with default verbosity

### ISSUE THREAD

**Issue by evil-shrike** [cake-build/cake#1865]
Normally when we encounter an error during executing a Cake script it's reported as:
"One or more error occurred"
To see all details we have to pass `-verbosity=Diagnostic`
Then the whole exception will be shown.
It's not very handy. Usually it's enough to see error message.
So why instead of wring a meaningless "One or more error occurred" write an actual error message?

**Comment by devlead** [comment]
This was fixed by #1824 and will be avail in the next release.
