### ISSUE TITLE
Method Array.Empty not found

### ISSUE THREAD

**Issue by lyze237** [cake-build/cake#1870]
### What You Are Seeing?

Can't build c# project since cake nuget packages don't get downloaded.

### What is Expected?

Cake should download it's dependencies.

### What version of Cake are you using?

~~~sh
$ ./build.sh
Restoring NuGet package Cake.0.22.2.
~~~

Installed dotnet core via: https://www.microsoft.com/net/core#linuxubuntu

~~~sh
$ dotnet --version
2.0.0
~~~

Installed mono via: sudo apt install mono-devel

~~~sh
$ mono --version
Mono JIT compiler version 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug
        LLVM:          supported, not enabled.
        GC:            sgen
~~~

### Are you running on a 32 or 64 bit system?

64

### What environment are you running on?  Windows? Linux? Mac?

Ubuntu 16.4.3 LTS Server

### Are you running on a CI Server?  If so, which one?

Custom Jenkins installation

### How Did You Get This To Happen? (Steps to Reproduce)

    git clone <project>
    chmod u+x build.sh
    ./build.sh

Can you point us to a project where this problem occurs?  i.e. a public GitHub Repo, where we can try to reproduce the problem, and help with debugging?

https://gitlab.com/lyze237/OwlPlugins

### Output Log

~~~sh
$ ./build.sh -verbosity=diagnostic
Downloading packages.config...
Downloading NuGet...
Feeds used:
  /var/lib/jenkins/.nuget/packages/
  https://api.nuget.org/v3/index.json

Restoring NuGet package Cake.0.22.2.
Adding package 'Cake.0.22.2' to folder '/var/lib/jenkins/jobs/OwlPlugins/workspace/tools'
Added package 'Cake.0.22.2' to folder '/var/lib/jenkins/jobs/OwlPlugins/workspace/tools'
Error: Method 'String.Format' not found.
Unhandled Exception:
System.MissingMethodException: Method 'Array.Empty' not found.
  at Cake.Core.Diagnostics.CakeBuildLog.Write (Verbosity verbosity, LogLevel level, System.String format, System.Object[] args) <0x40273eb0 + 0x002a3> in <filename unknown>:0
  at Cake.Core.Diagnostics.LogExtensions.Error (ICakeLog log, Verbosity verbosity, System.String format, System.Object[] args) <0x40273e60 + 0x00042> in <filename unknown>:0
  at Cake.Core.Diagnostics.LogExtensions.Error (ICakeLog log, System.String format, System.Object[] args) <0x40273e20 + 0x00023> in <filename unknown>:0
  at Cake.Program.Main () <0x41b0ad60 + 0x00637> in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Array.Empty' not found.
  at Cake.Core.Diagnostics.CakeBuildLog.Write (Verbosity verbosity, LogLevel level, System.String format, System.Object[] args) <0x40273eb0 + 0x002a3> in <filename unknown>:0
  at Cake.Core.Diagnostics.LogExtensions.Error (ICakeLog log, Verbosity verbosity, System.String format, System.Object[] args) <0x40273e60 + 0x00042> in <filename unknown>:0
  at Cake.Core.Diagnostics.LogExtensions.Error (ICakeLog log, System.String format, System.Object[] args) <0x40273e20 + 0x00023> in <filename unknown>:0
  at Cake.Program.Main () <0x41b0ad60 + 0x00637> in <filename unknown>:0

~~~

**Comment by devlead** [comment]
Hi,

Cake.0.22.0 targets .NET 4.6 which requires Mono 4.4.2 or later to work alternatively .NET Core 1.0.4.

And example of what's needed for a GitLab docker container (or Linux in general) can be seen in this Dockerfile

* https://github.com/devlead/gitlabs-dotnet/blob/master/Dockerfile

Example usage on GitLabs

*  https://github.com/cake-build/cake/blob/develop/.gitlab-ci.yml

**Comment by lyze237** [comment]
Hey!

Thanks, didn't see that, works now fine!

**Comment by lyze237** [comment]
For anybody trying this with ubuntu 17.04, you need to install some depenencies manually:

* libicu55
* libllvm3.6
* liblldb-3.6

E.g.:

    wget http://security.ubuntu.com/ubuntu/pool/main/i/icu/libicu55_55.1-7ubuntu0.2_amd64.deb
    sudo dpkg -i libicu55_55.1-7ubuntu0.2_amd64.deb
    wget http://mirrors.kernel.org/ubuntu/pool/main/l/llvm-toolchain-3.6/libllvm3.6v5_3.6.2-3ubuntu2_amd64.deb
    sudo dpkg -i libllvm3.6v5_3.6.2-3ubuntu2_amd64.deb
    wget http://mirrors.kernel.org/ubuntu/pool/main/l/llvm-toolchain-3.6/liblldb-3.6_3.6.2-3ubuntu2_amd64.deb
    sudo dpkg -i liblldb-3.6_3.6.2-3ubuntu2_amd64.deb

**Comment by johnkors** [comment]
Getting this error on macOS as well. Is it the same story with Mono, @devlead ..? What do I need to do to get 0.22+ working?

Cake.0.21.0 works fine at the moment.

**Comment by devlead** [comment]
Cake 0.22.0+ targets .NET 4.6, which means you'll need Mono 4.4.2 or later, Mono 5.4 was recently released, we currently build Cake with Cake and run integration tests on MacOS and Linux using Mono versions 4.4.2 and 5.2. If you're running an older version of mono, then I'll suggest you'll try a newer version.

**Comment by johnkors** [comment]
First time for me running Cake on macOS (only ran it on Win in the past), so not sure which version of Mono I'm running :-)

**Comment by devlead** [comment]
Try mono - -version
