### ISSUE TITLE
In Process NuGet Client fails to get packages from ProGet server.

### ISSUE THREAD

**Issue by toddstewart** [cake-build/cake#1877]
### What You Are Seeing?
The in process nuget client fails when attempting to get packages from a ProGet nuget server.

### What version of Cake are you using?
0.23.0

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 10

### Are you running on a CI Server?  If so, which one?
TeamCity

### How Did You Get This To Happen? (Steps to Reproduce)
Just use the in process nuget client against a ProGet server.

### Output Log
Error finding repository for 'http://pcapps.***.com:81/nuget/NuGet': An error occurred while retrieving package metadata for '' from source ' Local Nuget Server'.
A task was canceled.

**Comment by mholo65** [comment]
@toddstewart, hmm something fishy with V2 feed. Do you see same issue if you specify `—nuget_loaddependencies=true`?

**Comment by toddstewart** [comment]
I have installed the latest version of the ProGet server.  I still get the error listed above but now it seems to get the package downloaded and the build works.  It just looks bad not getting the error message in the output log.  This is true using the loaddependencies=true or not.

**Comment by wwwlicious** [comment]
FYI I am seeing the same thing also with proget.

**Comment by mholo65** [comment]
Need to investigate why in-process NuGet doesn’t like V2 feeds. It *should* work, since `nuget.exe` uses the same `NuGet.Client` libraries we use in `Cake.NuGet`.

@daveaglick, ever noticed same issues with Wyam?

**Comment by pascalberger** [comment]
We're unable to reproduce this issue. If you still have this error with latest Cake / ProGet version please reopen the issue.
