### ISSUE TITLE
Cake.CoreCLR dll versions differ from official Nuget offerings.

### ISSUE THREAD

**Issue by Ashthos** [cake-build/cake#1885]
### What You Are Seeing?

Using Cake.CoreCLR on Linux yields the following warnings:

`Error: Cake.Core.CakeException: Error occurred when compiling build script: (2471,12): warning CS1702: Assuming assembly reference 'System.Text.RegularExpressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Cake.FileHelpers' matches identity 'System.Text.RegularExpressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Text.RegularExpressions', you may need to supply runtime policy`

 

### What is Expected?

 

Cake executes normally

 

### What version of Cake are you using?

 

0.23.0

 

### Are you running on a 32 or 64 bit system?

 

64bit Ubuntu 16.04

 

### What environment are you running on?  Windows? Linux? Mac?

 

Linux

 

### How Did You Get This To Happen? (Steps to Reproduce)

 

Importing Cake.FileHelpers which has a non-explicit reference to System.Text.RegularExpressions. This resolves to 4.1.0.0. However the dlls shipped with Cake.CoreCLR 0.23.0 are versioned as 4.1.1.0.

 

Decompiled (via DotPeek) Cake.FileHelpers references

// System.Text.RegularExpressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

 

### Output Log

 

~~~sh

Compiling build script...

Error: Cake.Core.CakeException: Error occurred when compiling build script: (2471,12): warning CS1702: Assuming assembly reference 'System.Text.RegularExpressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Cake.FileHelpers' matches identity 'System.Text.RegularExpressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Text.RegularExpressions', you may need to supply runtime policy

(2483,12): warning CS1702: Assuming assembly reference 'System.Text.RegularExpressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Cake.FileHelpers' matches identity 'System.Text.RegularExpressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Text.RegularExpressions', you may need to supply runtime policy

(2495,12): warning CS1702: Assuming assembly reference 'System.Text.RegularExpressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Cake.FileHelpers' matches identity 'System.Text.RegularExpressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Text.RegularExpressions', you may need to supply runtime policy

(2501,12): warning CS1702: Assuming assembly reference 'System.Text.RegularExpressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Cake.FileHelpers' matches identity 'System.Text.RegularExpressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Text.RegularExpressions', you may need to supply runtime policy

(2507,12): warning CS1702: Assuming assembly reference 'System.Text.RegularExpressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Cake.FileHelpers' matches identity 'System.Text.RegularExpressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Text.RegularExpressions', you may need to supply runtime policy

(2513,12): warning CS1702: Assuming assembly reference 'System.Text.RegularExpressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Cake.FileHelpers' matches identity 'System.Text.RegularExpressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Text.RegularExpressions', you may need to supply runtime policy

(2519,12): warning CS1702: Assuming assembly reference 'System.Text.RegularExpressions, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' used by 'Cake.FileHelpers' matches identity 'System.Text.RegularExpressions, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' of 'System.Text.RegularExpressions', you may need to supply runtime policy

/opt/buildagent/work/26a5687b42ccd03b/base-versioning.cake(59,78): error CS1503: Argument 4: cannot convert from 'int?' to 'int'

   at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script)

   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)

   at Cake.Commands.BuildCommand.Execute(CakeOptions options)

   at Cake.CakeApplication.Run(CakeOptions options)

   at Cake.Program.Main()

~~~

**Comment by devlead** [comment]
What does this line look like?
`/opt/buildagent/work/26a5687b42ccd03b/base-versioning.cake(59,78): error CS1503: Argument 4: cannot convert from 'int?' to 'int'`

**Comment by Ashthos** [comment]
Line 59 of base-versioning.cake is `return semver;` which is returning a string from a function..

**Comment by Ashthos** [comment]
So I have done some manual hacking to try to isolate the issue here. It turns out that the line reported isn't actually where the issue is, but one a few lines below.

The offending line is returning a new System.Version utilising a fourth parameter.  In this case GitVersion.CommitsSinceVersionSource, which is a nullable int. This works fine when run via mono or from a Windows host using the standard cake runner. 

When I remove the reliance on the nullable int, or use .Value the warnings go away. Maybe this is a Rosyln flag that is causing this?

**Comment by devlead** [comment]
Assigning a nullable int to int generally won't fly unless doing .Value, something like `variable ?? 0` or casting it.

That commits since version being nullable was a breaking change introduced in 0.23.0.

If it's a Roslyn issue it could potentielly be sorted in latest pre-release of Cake on MyGet ( https://www.myget.org/feed/cake/package/nuget/Cake.CoreCLR ) which uses a newer version of Roslyn and .NET Core Runtime/SDK 1.0.7/1.1.4.

**Comment by Ashthos** [comment]
Unfortunately for us I think the Cake.CoreCLR is going to be a dead end for a while, as we use the GitVersion tool plugin. Unfortunately when running on Linux it just does a process.Execute() on the .Net executable which yields an error.  It either needs to reference the dlls or use mono to do the execution, something which I think is a significant change beyond the scope of me just doing a quick pull request.

For the moment we are going back to using mono on Linux.

**Comment by devlead** [comment]
I'm going ahead and going to close this issue, please feel free to reopen or create a new issue if you have any more questions.
