### ISSUE TITLE
DotNetCoreRestoreSettings: support option --force

### ISSUE THREAD

**Issue by evil-shrike** [cake-build/cake#1887]
If we compare 

[DotNetCoreRestoreSettings](https://www.cakebuild.net/api/Cake.Common.Tools.DotNetCore.Restore/DotNetCoreRestoreSettings/) and [dotnet restore](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-restore?tabs=netcore2x) we'll that there's no Property in `DotNetCoreRestoreSettings` for `--force` option. 

 dotnet restore         | Cake     
 -------------------- | ---------
 `--configfile <FILE>` | `ConfigFile`
 `--disable-parallel`   | `DisableParallel `
 `--force`                  |  **missing**
 `--ignore-failed-sources` | `IgnoreFailedSources` 
 `--no-cache`             | `NoCache` 
 `--no-dependencies` | `NoDependencies` 
 `--packages`             | `PackagesDirectory` 
 `--runtime`           | `Runtime` 
 `--source`             | `Sources` 

Also Restore aliases for DotNetCore [DotNetCoreRestore](https://www.cakebuild.net/api/Cake.Common.Tools.DotNetCore/DotNetCoreAliases/6E238F91) with string argument is stated that it's "root folder". But "dotnet restore" supports a solution file path also and it seems also supported by DotNetCoreRestore.

**Comment by devlead** [comment]
Force is a new option in version 2.0 of the .NET CLI, if added that should be clearly documented as it won't work with previous versions.
