### ISSUE TITLE
XmlPoke ignores BOM encoding settings

### ISSUE THREAD

**Issue by olsh** [cake-build/cake#1889]
### What You Are Seeing?
XmlPoke saves a file with BOM even if I choose UTF8 without BOM Encoding

### What is Expected?
XmlPoke saves an XML file without BOM

### What version of Cake are you using?
Cake 0.23.0

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 10

### How Did You Get This To Happen? (Steps to Reproduce)
1. Copy XML from the [example](https://www.cakebuild.net/api/Cake.Common.Xml/XmlPokeAliases/4B32572F) and save it as UTF8 file
```xml
    <?xml version="1.0" encoding="utf-8" ?>
<configuration>
    <appSettings>
        <add key="server" value="testhost.somecompany.com" />
    </appSettings>
</configuration>
```
2. Execute code from the example but with Encoding specified
```csharp
    var file = File("test.xml");
    XmlPoke(file, "/configuration/appSettings/add[@key = 'server']/@value", "productionhost.somecompany.com", new XmlPokeSettings { Encoding = new UTF8Encoding(false) });
```

3. The file encoding was changed to UTF8 with BOM

**Comment by devlead** [comment]
Would seem encoding is only used with XmlPokeString and should probably be used [here](https://github.com/cake-build/cake/blob/5192d7738ebd36ddf85d83eaee9a0814fe15409e/src/Cake.Common/Xml/XmlPokeAliases.cs#L589) too.

**Comment by Marusyk** [comment]
Hello, I'll try to fix it
