### ISSUE TITLE
Vake for Visual Studio 0.2.0.0 crashes constantly.

### ISSUE THREAD

**Issue by PradeepLoganathan** [cake-build/cake#1893]
### What You Are Seeing?
Cake extension is causing VS 2017 15.4.1 to crash constantly. It is replicable easily.

### What is Expected?
Cake extension should not crash.

### What version of Cake are you using?
Cake for Visual Studio 0.2.0.0

### Are you running on a 32 or 64 bit system?
I am running a 64 bit system.

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
None yet.

### How Did You Get This To Happen? (Steps to Reproduce)
After installing Cake for visual studio, I created a powershell bootstrapper and a cake.config file. I created a new build.cake file without any code. It crashes once this file is opened. I opened the file in notepad and it is empty.

### Output Log
I do not have any output log for the issue. Trying to check if VS2017 has a log.

**Comment by SIkebe** [comment]
There is a repository of Cake extension for Visual Studio.
https://github.com/cake-build/cake-vs

You should probably raise an issue there.

**Comment by PradeepLoganathan** [comment]
Will do thanks !!

**Comment by devlead** [comment]
Issue moved to [cake-build/cake-vs #84](https://github.com/cake-build/cake-vs/issues/84) via [**ZenHub**](https://www.zenhub.com/)
