### ISSUE TITLE
DotNetCoreVSTester: Add setting for --collect switch

### ISSUE THREAD

**Issue by davidreher** [cake-build/cake#1896]
To get code coverage in DotNetCore, you should use VSTest with the `--collect:"Code Coverage"` [switch](https://github.com/Microsoft/vstest-docs/blob/master/docs/analyze.md#coverage). This is not possible today. 

I tried using the `Arguments` dictionary (which use a `=` to separate the key and value?!) which is not working.
```
DotNetCoreVSTest(testLib.FullPath, new DotNetCoreVSTestSettings {
            Framework = ".NETCoreApp,Version=2.0",
            Arguments = new Dictionary<string, string> {
                {"--collect", "\"Code Coverage\""}
            }
        });
```
Output:
```
The test source file "C:\Users\...\--collect=Code" provided was not found.
```

We should either add a collection of `Collectors` to the settings or alter the way `Arguments` is used.

**Comment by devlead** [comment]
Before the feature is added, you could try adding arguments using [ArgumentCustomization](https://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8) and see if that sorts the acute issue.

Launching Cake with [diagnostic verbosity](https://stackoverflow.com/questions/38658660/how-to-enable-diagnostic-verbosity-for-cake) to see the actual command line the tool is launched with.

**Comment by davidreher** [comment]
@devlead Thanks for the tips, this is really helpful.
The command is 
```
"C:/Program Files/dotnet/dotnet.exe" vstest some/test/lib.dll --collect="Code Coverage"
```
I would have expected that `vstest.console.exe` is called directly. However the command itself is correct ... 
I have posted a comment to Microsoft/vstest#579 ... Let's see what they say. In the meantime I will close this and reopen, when required.
