### ISSUE TITLE
Support path concatenation with the `/` operator

### ISSUE THREAD

**Issue by ecampidoglio** [cake-build/cake#1899]
After reading a blog post by @maartenba titled ["Using operator overloads for concatenating file system paths in CSharp"](https://blog.maartenballiauw.be/post/2017/10/26/operator-overloads-concatenate-file-system-path.html), I thought that overloading the `/` operator for the `FilePath` and `DirectoryPath` types would be a nice addition to the Cake DSL.

So, while we can already do this today:

```csharp
var directory = Directory("C:\Some\Directory");
var file = directory + "subdirectory" + "file.txt";
```

Being able to do this would be even better:

```csharp
var directory = Directory("C:\Some\Directory");
var file = directory / "subdirectory" / "file.txt";
```

Of course, the resulting path would conform to the platform-specific format.

**Comment by patriksvensson** [comment]
This is an awesome idea 👍

**Comment by ecampidoglio** [comment]
Is it OK to start on a PR?

**Comment by devlead** [comment]
Sure 👍

**Comment by gep13** [comment]
Closing as per this comment here: https://github.com/cake-build/cake/pull/1905#issuecomment-475107060
