### ISSUE TITLE
DotNetCoreTestSettings missing a NoRestore option

### ISSUE THREAD

**Issue by daveaglick** [cake-build/cake#1901]
I've encountered lockups on restore when using `dotnet test`, so having the `--no-restore` option exposed as a setting would be nice. I can PR this.

**Comment by devlead** [comment]
Excellent 👍

**Comment by gabrielweyer** [comment]
@daveaglick Are you still working on this issue?

**Comment by daveaglick** [comment]
@gabrielweyer I totally forgot about it, TBH. I'll take a look today or tomorrow and add the option, thanks for the reminder!

**Comment by augustoproiete** [comment]
Closing this as implemented in the v0.25.0 milestone via [262a501](https://github.com/cake-build/cake/commit/262a50118084dbbf27424730b01f5a31f4a15bbb#diff-68e950e3862aae36fb79ded41dc5eddff81fd97854b674b5676a4299a1911af2)
