### ISSUE TITLE
Add WiX burn support

### ISSUE THREAD

**Issue by dealproc** [cake-build/cake#1902]
It's grand that heat; candle; and light are supported... but can burn get a little love for building bundles?

**Comment by gep13** [comment]
@dealproc this seems like a good idea to me.  Would you be interested in helping out with a PR?

**Comment by dealproc** [comment]
let me think about it... the last few times i tried providing PRs for things... it didn't go well.

**Comment by gep13** [comment]
>@dealproc said...
the last few times i tried providing PRs for things... it didn't go well.

How do you mean?

**Comment by dealproc** [comment]
I misunderstood how this was supposed to work...

http://wixtoolset.org/documentation/manual/v3/bundle/wixstdba/

I've only used bundles through visual studio.  You Candle/Light the wxs files like you do to create an msi flie.  This is a dead topic.
