### ISSUE TITLE
Dll not found while trying to get git version of a repo

### ISSUE THREAD

**Issue by johnnyasantoss** [cake-build/cake#1906]
### What You Are Seeing?
I'm having problems to get the git version of a repo using Cake.Git.
I think that the problem has something to do with the relative path for the `.so` file.

### What is Expected?
Get the latest tag of the repo.

### What version of Cake are you using?
- 0.22.1
### Are you running on a 32 or 64 bit system?
- 64

### What environment are you running on?  Windows? Linux? Mac?
I'm using a docker image to build my project (or trying to).
Image: `johnnyasantoss/dotnet-mono-docker:dotnet2.0-mono5.2-sdk`

### How Did You Get This To Happen? (Steps to Reproduce)
I tried to run a task and after compiling I got this error message.

### Output Log

Gist: https://gist.github.com/anonymous/592a7073ba70b570b1090c92a39545df

**Comment by johnnyasantoss** [comment]
This is the dockerfile that I'm using https://github.com/johnnyasantoss/JsonFluentMap/blob/testes-unitarios/Dockerfile

**Comment by patriksvensson** [comment]
@johnnyasantoss Cake.Git is not part of the cake-build organisation but is part of the @cake-contrib.

I've moved your issue there: https://github.com/cake-contrib/Cake_Git/issues/55

**Comment by johnnyasantoss** [comment]
Ops, sorry.
Thanks!
