### ISSUE TITLE
Octopus Deploy tool does not support list-deployments call for octo.exe

### ISSUE THREAD

**Issue by CRuppert** [cake-build/cake#1908]
### What You Are Seeing?
missing feature for list-deployments implementation for octo.exe
### What is Expected?
implementation with filter support for octo.exe list-deployments
### What version of Cake are you using?
Current
### Are you running on a 32 or 64 bit system?
All
### What environment are you running on?  Windows? Linux? Mac?
Windows
### Are you running on a CI Server?  If so, which one?
Jenkins

### How Did You Get This To Happen? (Steps to Reproduce)

used the product. ;)

Feature request, See Above
Discussed in the gitter w/ @gep13 

PR forthcoming.

**Comment by gep13** [comment]
Gitter discussion was here: https://gitter.im/cake-build/cake?at=59fcd032e44c43700ab46105

**Comment by devlead** [comment]
@CRuppert I've added this to the v0.27.0 milestone. The next release v0.26.0 will basically be focused on .NET Core 2.0, asap after that's released I'll review your PR and if all's ok pull it in.
