### ISSUE TITLE
Support for DotCover Process Filter

### ISSUE THREAD

**Issue by rdehuyss** [cake-build/cake#1912]
### What You Are Seeing?
I can not specify processfilters for dotcover

### What is Expected?
I can specify processfilters for dotcover

### What version of Cake are you using?
Latest and greatest, v0.23
### Are you running on a 32 or 64 bit system?
N/A

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
Yes, teamcity

### How Did You Get This To Happen? (Steps to Reproduce)
NA

### Output Log
NA

**Comment by devlead** [comment]
fixed by #1913
