### ISSUE TITLE
Ability to look ahead for tasks that will be executed

### ISSUE THREAD

**Issue by mdesousa** [cake-build/cake#1914]
I would like to run certain tasks differently depending on which tasks will be executed later in the build. This would allow me to optimize the execution by looking ahead at what will be required.
For example, if I have a "Build" task that is going to invoke MSBuild, I would like to default the configuration to "Release" if I see that later the build needs to execute a "Publish" task. If that won't be the case, the MSBuild can run in "Debug" mode which in our case executes a lot faster.
I figured that I could achieve this if I could get access to the execution graph... then do something like this:

if (targetTask.DependsOn(publishTask)) configuration = "Release" else configuration = "Debug";

Maybe this is possible already? I could not find a way to query the dependency graph. Thanks!

**Comment by jnm2** [comment]
I've been asking for exactly this kind of thing: https://github.com/cake-build/cake/issues/1772

**Comment by mdesousa** [comment]
Looks like #1172 has been resolved, thanks!
