### ISSUE TITLE
Signtool resolver should choose the newest version found

### ISSUE THREAD

**Issue by Thealexbarney** [cake-build/cake#1926]
When there are multiple Windows SDK versions installed, Cake should use the most recent signtool version found. Older versions can cause issues in some cases.

I don't know exactly which signtool versions will cause the issues I'm hitting. I have the Windows 8.1 SDK and Windows 10.0.16299.0 SDKs installed. If I build an appx package with the 10.0.16299.0 SDK, the 8.1 signtool will error when signing the appx, but the 10.0.16299.0 signtool will have no issues.

**Comment by devlead** [comment]
fixed by #1925
