### ISSUE TITLE
Allow passing a nuget.config as environment variable or in cake.config

### ISSUE THREAD

**Issue by Cheesebaron** [cake-build/cake#1931]
### What You Are Seeing?
When trying to use tools in a private NuGet feed such as one in VSTS, NuGet.exe needs a config with credentials. Currently we need to rely on NuGet.exe or the in-process NuGet client to figure out which nuget.config to use.
It seems to be very hit and miss.

### What is Expected?
I want to be able to either set which nuget.config should be used through cake.config or an Environment Variable. Similar to what can be done with `Source` using `CAKE_NuGet_Source` and `CAKE_NUGET_USEINPROCESSCLIENT` etc.

### What version of Cake are you using?
0.23.0

**Comment by devlead** [comment]
fixed by #1932
