### ISSUE TITLE
NuGetPackSettings.Properties does not support whitespaces.

### ISSUE THREAD

**Issue by robsammons** [cake-build/cake#1933]
### What You Are Seeing?

Issue using "Properties" field on NuGetPackSettings. the properties are not being enclosed in " when being resolved into a command line
i.e.

**pack "/Working/existing.csproj" -Properties Configuration=Release;Foo=Bar**

Should be

**pack "/Working/existing.csproj" -Properties "Configuration=Release;Foo=Bar"**

### What is Expected?

**pack "/Working/existing.csproj" -Properties "Configuration=Release;Foo=Bar"**

### What version of Cake are you using?

0.23.0

### Are you running on a 32 or 64 bit system?

64-bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### How Did You Get This To Happen? (Steps to Reproduce)

Created "NuGetPack" with NuGetPackSettings.Properties used.

Currently forcing the quotes into my build code as a work around i.e.
```
var nuGetPackSettings = new NuGetPackSettings
    {
        Version = version,
        BasePath = nugetPackageDir,
        OutputDirectory = nugetPackageDir,
        Properties = new Dictionary<string, string>()
        {
            {"\"buildinfo", $"Build branch {branchName}"},
            {"result", buildResultsUrl + "\""}
        }
    };
```

**Comment by RaringCoder** [comment]
I just ran into this issue and manually wrapping the first argument and the last parameter in quotes as detailed here did the trick. Easy thing to get fixed too.
