### ISSUE TITLE
Bug - TypeExtensions.GetFullName doesn't handle nested types correctly

### ISSUE THREAD

**Issue by kcamp** [cake-build/cake#1939]
While fixing GH-1930 the other night, some of the tests for `ParameterEmitter` caught my eye (seemed to be asserting the wrong "expected" values).  With fresh eyes, I wrote some red/green tests against the `MethodAliasGenerator` to prove what I was seeing was in fact wrong.

### What You Are Seeing?
The code generation for _some_ nested types is being emitted with the + sign in the type name.  i.e., `My.Namespace.ParentType+NestedType`.

Upon reviewing the code, I see that some of the work I did for GH-1566 accounted for this (presence of `+`) in the `GenericParameterConstraintEmitter` implementation;  this should have rightfully been made part of the `TypeExtensions.GetFullName` extension method, instead.

### What is Expected?
Valid, compilable code to be emitted for all types via the `TypeExtensions.GetFullName` method.

### What version of Cake are you using?
0.23

I will have a PR for this shortly.

**Comment by devlead** [comment]
Fixed by #1940
