### ISSUE TITLE
Chocolatey package dependencies cannot be set using the ChocolateyPackSettings

### ISSUE THREAD

**Issue by RichardJFoster** [cake-build/cake#1943]
This problem affects Cake 0.23.0

The ChocolateyPackSettings class does not contain any mechanism to add package dependencies.

The expected operation is that the ChocolateyPackSettings has a Dependencies property that mirrors the Dependencies property already present in the NuGetPackSettings.

This problem was first observed on a 64 bit Windows system, but an examination of the source suggests this issue is not dependent on OS or build server type.

**Comment by RichardJFoster** [comment]
So... I was looking at implementing this so I could submit a PR. The implementation is easy, but I am having difficulty working out how to unit test the change. It looks as if the unit tests are based on the abstract ChocolateyFixture (by way of the ChocolateyPackerFixture), but neither the ChocolateyPackerWithNuSpecFixture or the ChocolateyPackerWithoutNuSpecFixture currently appear to contain any test assertions at all. Am I looking in the right place?

**Comment by gep13** [comment]
@RichardJFoster The Chocolatey Pack tests are here:

https://github.com/cake-build/cake/blob/develop/src/Cake.Common.Tests/Unit/Tools/Chocolatey/Pack/ChocolateyPackerTests.cs

Seems like you are looking in the Fixtures folder, which contains the setup logic for running the actual tests.

**Comment by gep13** [comment]
If you look at this file:

https://github.com/cake-build/cake/blob/develop/src/Cake.Common.Tests/Unit/Tools/NuGet/Pack/NuGetPackerTests.cs

You will find the where the dependencies are tested in the NuGet version.

**Comment by RichardJFoster** [comment]
Aha! Excellent. I was looking in the wrong place. :-) Thanks for the pointers.

**Comment by gep13** [comment]
@RichardJFoster you are very welcome!  Let us know if you have any questions!

**Comment by RichardJFoster** [comment]
No questions for now. Just waiting on the contribution license email, but if there are comments on the PR in the mean time I'm all ears. :-)

**Comment by devlead** [comment]
Fixed by #1945
