### ISSUE TITLE
Add option to pack files into the NuGet tool directory

### ISSUE THREAD

**Issue by djdelaney** [cake-build/cake#1946]
The Cake NuGet pack tool doesn't expose the "-Tool" option to output files into the nuget "tool" directory. This is useful when building packages designed for delivering tools (such as cake tools).

https://docs.microsoft.com/en-us/nuget/tools/cli-ref-pack

**Comment by gep13** [comment]
@djdelaney this seems like a good addition. Are you in a position to do a PR?

**Comment by gep13** [comment]
Today, it would be possible to add this option using the ArgumentCustomization method, but direct support for the argument also makes sense.

**Comment by djdelaney** [comment]
I'll submit a PR shortly :-)

**Comment by devlead** [comment]
Fixed by #1947
