### ISSUE TITLE
Add Products prop to VSWhereSettings

### ISSUE THREAD

**Issue by sm-g** [cake-build/cake#1973]
To use cake on build agent without installed VS (only with Build Tools), I have to use ArgumentCustomization:

```
var latestInstallationPath = VSWhereLatest(new VSWhereLatestSettings {
        Requires = "Microsoft.Component.MSBuild",
        ReturnProperty = "installationPath",
        ArgumentCustomization = args=>args.Append("-products *")
});
```

**Comment by devlead** [comment]
There's a [VSWhereProducts](https://cakebuild.net/api/Cake.Common.Tools.VSWhere/VSWhereAliases/71480628)  alias available for this use case

```cake
var latestInstallationPaths = VSWhereProducts("Microsoft.VisualStudio.Product.BuildTools");
```

**Comment by sm-g** [comment]
Sorry, did not notice this.

It returns `DirectoryPathCollection`, how to get single path of latest tool then?

**Comment by phillipsj** [comment]
It should only return one of you ask for latest.  Just pull out the first
item.

**Comment by sm-g** [comment]
Why you think VSWhereProducts will return latest version in first position in collection? [Docs](https://www.cakebuild.net/api/Cake.Common.Tools.VSWhere.Product/VSWhereProduct/) does not mention that.

**Comment by jnm2** [comment]
Please add this to `VSWhereLatestSettings`. It's logical to want to use `VSWhereLatest` which returns a single path and access vswhere's product filtering on its `latest` command.

**Comment by tbertenshaw** [comment]
Has/is this being done? ☝️
