### ISSUE TITLE
ToDictionary on Mono causes "The type 'Dictionary<,>' is defined in an assembly that is not referenced"

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#1974]
Verified sample repro:
```cs
var d = Array.Empty<int>().ToDictionary(i => i);
```

If I use any overload of `System.Linq.Enumerable.ToDictionary`, Cake 0.22–0.24 (on Travis using Mono 5.2.0 on both Ubuntu Trusty and OS X 10.12) gives this error:

> error CS0012: The type 'Dictionary<,>' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Collections, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

Code that initially triggered it: https://github.com/nunit/nunit/commit/5d3fe04d65889729e9529a93624992d0f0e16ddd#diff-a81006b28a9970a7e6644efe520431a5R9

Failing build log:
https://travis-ci.org/nunit/nunit/jobs/322775654#L1909 (Ubuntu)
https://travis-ci.org/nunit/nunit/jobs/322775656#L728 (OS X)

**Comment by gep13** [comment]
@jnm2 based on the Cake version range that you provided, does this mean that in Cake 0.21.0 this was known to be working?

**Comment by jnm2** [comment]
@gep13 Ah, sorry! I didn't check anything earlier than 0.22.

**Comment by gep13** [comment]
@jnm2 Gotcha.  Was just trying to understand if this is a regression, or whether this has never worked.

**Comment by mholo65** [comment]
Pre 0.22 works on Mono because we had separate Mono Scripying enhine back then. Now with Roslyn, we’d probably need a similar hack as [here](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Scripting/ScriptConventions.cs#L86) for System.Collection

**Comment by jnm2** [comment]
Does it make sense to cover this with a regression test?

**Comment by devlead** [comment]
@jnm2 I've submitted PR #1979 to address this.
