### ISSUE TITLE
Context is not accessible from local functions

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#1978]
Cake 0.24, .NET Framework 4.7.1.
I'm getting this error on `Context` inside a local function:

> error CS0120: An object reference is required for the non-static field, method, or property 'ScriptHost.Context'

Is there any reason this shouldn't work?

```cake
Task("Build")
    .Does(() =>
    {
        // Use CreateSettings() multiple times
        // ...

        MSBuildSettings CreateSettings()
        {
            var settings = new MSBuildSettings { /* ... */ };

            if (IsRunningOnWindows())
                settings.ToolVersion = MSBuildToolVersion.VS2017;
            else
                settings.ToolPath = Context.Tools.Resolve("msbuild");

            return settings;
        }
    });
```

The workaround is obviously to not use local functions.

**Comment by gep13** [comment]
You would need to pass `Context` as a parameter to your function.

**Comment by jnm2** [comment]
That's another workaround, but I'm trying to understand why I should have to do that. Everything that's automatically captured by a lambda should be automatically captured by a local function.

**Comment by devlead** [comment]
@jnm2 it's a scripting scoping issue.

Change your code to 
```cake
Task("Build")
    .Does(context =>
    {
        // Use CreateSettings() multiple times
        // ...

        MSBuildSettings CreateSettings()
        {
            var settings = new MSBuildSettings { /* ... */ };

            if (IsRunningOnWindows())
                settings.ToolVersion = MSBuildToolVersion.VS2017;
            else
                settings.ToolPath = context.Tools.Resolve("msbuild");

            return settings;
        }
    });
```

```diff
-        .Does(() =>
+        .Does(context =>

-                    settings.ToolPath = Context.Tools.Resolve("msbuild");
+                    settings.ToolPath = context.Tools.Resolve("msbuild");
```

**Comment by jnm2** [comment]
That's a nice workaround too. I looked into it and it seems that the problem doesn't lie with Cake. Closing in favor of https://github.com/dotnet/roslyn/issues/23996.
