### ISSUE TITLE
The docs need to detail how Cake uses the tools folder.

### ISSUE THREAD

**Issue by RaringCoder** [cake-build/cake#1980]
A user from the gitter channel highlighted an issue whereby they performed an update to the Cake version. This causes the bootstrapper to flush the tools folder and re-fetch all packages. Unfortunately, there were things in the tools folder (that existed prior to Cake being used) that weren't under control of Cake scripts and were deleted.

This exclusivity over the tools folder (being a sibling of the `build.ps1` script), isn't _necessarily_ a problem, but in the very least it needs to be made clear that the current implementation of the bootstrapping script assumes exclusivity.

Personally I feel this would be best placed in the Getting Started guide, where the tools directory is listed. 

Further to this, better ways to assert tool versions could be investigated to make the "delete all" approach more granular. It may also be beneficial to make the tools directory more obviously configurable.

**Comment by gep13** [comment]
@RaringCoder this is probably best moved to the website repository, as that is where most of the top level documentation is located.

**Comment by RaringCoder** [comment]
@gep13 Can you migrate tickets or is it a close and recreate job?

**Comment by gep13** [comment]
Issue moved to [cake-build/website #468](https://github.com/cake-build/website/issues/468) via [**ZenHub**](https://www.zenhub.com/)
