### ISSUE TITLE
.travis.yml uses outdated version of dotnet core SDK

### ISSUE THREAD

**Issue by SIkebe** [cake-build/cake#1981]
### What You Are Seeing?
.travis.yml uses dotnet core SDK 1.0.4 but 1.0.8 in other places.
### What is Expected?
.travis.yml should use dotnet core SDK 1.0.8.

**Comment by devlead** [comment]
1.0.8 isn't available on Travis(or anywhere) , but 1.1.5 which also contains 1.0.8 is installed via the bootstrapper (build.sh) and is used today when building on Travisci. 

Recently tried and travisci didn't have anything newer available, but they've might have corrected that now.

**Comment by jnm2** [comment]
It's also not necessary to wait for Travis support if you don't mind adding the two or three .NET Core SDK installation commands to the yml.

**Comment by devlead** [comment]
@jnm2 .NET Core SDK already installed via build.sh

**Comment by devlead** [comment]
I've verified 1.1.5 is now available on Travis which means yml can be cleaned up a bit.

**Comment by devlead** [comment]
This will be fixed by  #1812
