### ISSUE TITLE
Cake core fails to install addins on Linux

### ISSUE THREAD

**Issue by trondhindenes** [cake-build/cake#1984]
### What You Are Seeing?
When using addins in a cake script running on Linux, Cake attempts to restore packages using `<path_to_nuget.exe>` instead of calling `mono <path_to_nuget.exe>`. This results in `exit code 13` as the linux os cannot execute nuget.exe directly

### What is Expected?
Cake should query the underlying os and prepend `mono ` to the nuget command, or fall back using `mono ` if calling nuget.exe results in exit code 13

### What version of Cake are you using?
`Cake.CoreCLR.0.24.0`

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Ubuntu Linux

### How Did You Get This To Happen? (Steps to Reproduce)
```
#addin nuget:?package=Cake.Docker&version=0.8.3

var target = Argument("target", "Default");

Task("Default")
  .Does(() =>
{
  Information("Hello World!");
});

RunTarget(target);
```

### Output Log
```
An error occured while installing package Cake.Docker.
Deleting package directory /home/trond/Documents/projects/RiksTV.Demo.Cake.CoreCLR/tools/Addins/cake.docker.0.8.3...
Error: Cake.Core.CakeException: Failed to install addin 'Cake.Docker'.
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

**Comment by devlead** [comment]
Does it work if you set environment variable CAKE_NUGET_USEINPROCESSCLIENT="true"?

**Comment by trondhindenes** [comment]
It does! I wasn't aware of that switch.

**Comment by devlead** [comment]
It's in preview, so opt-in now, but will be default in future releases of Cake.

**Comment by trondhindenes** [comment]
Awesome, thanks for the quick answer! Closing this.
