### ISSUE TITLE
Confusing Error from Bad Format String to `Information()`

### ISSUE THREAD

**Issue by WalkerCodeRanger** [cake-build/cake#1987]
### What You Are Seeing?

`Information("    Line {1} didn't match", i);`
Prints:
```
    Line
An error occurred when executing task 'Test-Current'.
Error: One or more errors occurred.
        Index was outside the bounds of the array.
```
### What is Expected?
A format error like from `string.Format` making it clear that there was something wrong with the format string.
### What version of Cake are you using?
0.23.0
### Are you running on a 32 or 64 bit system?
64 Bit
### What environment are you running on?  Windows? Linux? Mac?
Windows
### Are you running on a CI Server?  If so, which one?
No
### How Did You Get This To Happen? (Steps to Reproduce)
In your `build.cake` file, have a line where the format string passed to `Information()` is invalid.  Like:
`Information("    Line {1} didn't match", i);`

**Comment by devlead** [comment]
Fixed by #1990
