### ISSUE TITLE
Add the --trace option to the NUnit3Settings class.

### ISSUE THREAD

**Issue by WayneHiller** [cake-build/cake#1997]
NUnit3 - Can we add in the --trace option to the NUnit3Setting class and to the Runner? Now that --verbose is gone there is no way to turn on detailed logging.

**Comment by kcamp** [comment]
I can make a pass over this & have a PR in the next day or so.

**Comment by gep13** [comment]
@kcamp thank you very much!

**Comment by devlead** [comment]
Fixed by #2001
