### ISSUE TITLE
Expose the `-products` filter override in VSWhereLatestSettings

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#2002]
You need `-products *` if you want to locate the VS Build Tools (`BuildTools`) or the VS Test Agent (`TestAgent`) installations along with the others; by default, `-products` only locates the names `Community`, `Professional` and `Enterprise`. The [wiki](https://github.com/Microsoft/vswhere/wiki/Find-VSTest) recommends using `-products *` to locate the newest installation that has VSTest.

Would you make this a loose string property like `Requires` is, or would you do something fancier? It can be multivalued and can support `*` though that's not the default. A loose string seems to be most flexible.

**Comment by agc93** [comment]
@jnm2 this looks like the same issue as #1973 ?

**Comment by jnm2** [comment]
Yes. Thanks!
