### ISSUE TITLE
Add entries for Setup/Teardown in report

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2005]
Would be nice to have timings for Setup/Teardown in the report (if they're implemented).

![image](https://user-images.githubusercontent.com/357872/34935508-6b9e82a2-f9de-11e7-910c-424bd765a354.png)

**Comment by devlead** [comment]
Agreed 👍

**Comment by wozzo** [comment]
@devlead mind if I take a look at this one?

**Comment by devlead** [comment]
Sure go nuts

**Comment by wozzo** [comment]
@devlead I noticed in ExecuteTaskAsync that the following has been done. Is it ok to change to `stopWatch.Restart()` instead. The S[topWatch class reference source](http://referencesource.microsoft.com/#System/services/monitoring/system/diagnosticts/Stopwatch.cs,ceb0ba9cc88de82e) states it is an equivalent convenience method.

```
stopWatch.Reset();
stopWatch.Start();
```

**Comment by devlead** [comment]
@wozzo sure
