### ISSUE TITLE
Failed to install addin Cake.IIS

### ISSUE THREAD

**Issue by TerraVenil** [cake-build/cake#2011]
### What You Are Seeing?
`
Error: Cake.Core.CakeException: Failed to install addin 'Cake.IIS'.
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection``1 addins, DirectoryPath installPath)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary``2 arguments)
   at Cake.Commands.DebugCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
`
### What is Expected?
Install addin Cake.IIS 0.3.1.

### What version of Cake are you using?
`Version 0.25.0+Branch.main.Sha.05b4d3f596defbdf5baecdb3712c9bc17f849b55`

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 10 (VS Code (1.19.2))

### How Did You Get This To Happen? (Steps to Reproduce)
- add `#addin nuget:?package=Cake.IIS` to `build.cake` file;
- go to src folder;
- dotnet restore;
- press F5 (Debug)
- https://github.com/TerraVenil/cake/tree/Issue/C-2011/src/Cake

### Output Log
`Loaded 'C:\Users\testuser\.nuget\packages\system.xml.readerwriter\4.3.0\lib\netstandard1.3\System.Xml.ReaderWriter.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.xml.xdocument\4.3.0\lib\netstandard1.3\System.Xml.XDocument.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.threading.thread\4.3.0\lib\netstandard1.3\System.Threading.Thread.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.security.cryptography.algorithms\4.3.0\runtimes\win\lib\netstandard1.6\System.Security.Cryptography.Algorithms.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.security.cryptography.primitives\4.3.0\lib\netstandard1.3\System.Security.Cryptography.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.9\System.Text.Encoding.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.9\System.Runtime.Handles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.9\System.Private.Uri.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.9\System.Text.Encoding.Extensions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.text.regularexpressions\4.3.0\lib\netstandard1.6\System.Text.RegularExpressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\nuget.packaging.core\4.3.0\lib\netstandard1.3\NuGet.Packaging.Core.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\nuget.resolver\4.3.0\lib\netstandard1.3\NuGet.Resolver.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\nuget.projectmodel\4.3.0\lib\netstandard1.3\NuGet.ProjectModel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.net.http\4.3.0\runtimes\win\lib\netstandard1.3\System.Net.Http.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.9\System.Net.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.9\System.Threading.Overlapped.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\newtonsoft.json\9.0.1\lib\netstandard1.0\Newtonsoft.Json.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.dynamic.runtime\4.3.0\lib\netstandard1.3\System.Dynamic.Runtime.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.runtime.serialization.primitives\4.3.0\lib\netstandard1.3\System.Runtime.Serialization.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.9\System.Diagnostics.Tracing.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.diagnostics.diagnosticsource\4.3.0\lib\netstandard1.3\System.Diagnostics.DiagnosticSource.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.security.cryptography.x509certificates\4.3.0\runtimes\win\lib\netstandard1.6\System.Security.Cryptography.X509Certificates.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.9\Microsoft.Win32.Primitives.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.security.cryptography.encoding\4.3.0\runtimes\win\lib\netstandard1.3\System.Security.Cryptography.Encoding.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.runtime.numerics\4.3.0\lib\netstandard1.3\System.Runtime.Numerics.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\system.io.compression\4.3.0\runtimes\win\lib\netstandard1.3\System.IO.Compression.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Loaded 'C:\Users\testuser\.nuget\packages\nuget.commands\4.3.0\lib\netstandard1.3\NuGet.Commands.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'Cake.Core.CakeException' in Cake.Core.dll
Error: Failed to install addin 'Cake.IIS'.
The program '[59920] Cake.dll' has exited with code 1 (0x1).
 `

**Comment by devlead** [comment]
Doesn't look like that package is available for .NET Core
![image](https://user-images.githubusercontent.com/1647294/35228813-f151e75a-ff91-11e7-8d8f-e2b8b6f498e2.png)

I suggest you raise an issue at
https://github.com/SharpeRAD/Cake.IIS/

**Comment by TerraVenil** [comment]
If you use `NuGet Version: 4.4.1.4656` and run `.\nuget.exe install cake.iis` you will get two folders
![image](https://user-images.githubusercontent.com/6068068/35229407-072b8838-ff9c-11e7-890b-55cc20257eb1.png). Second one contains netstandard1.6.

**Comment by devlead** [comment]
Interesting I downloaded and unzipped the Cake.IIS.0.3.1 nuget package and only saw a ne461 moniker.
![image](https://user-images.githubusercontent.com/1647294/35230030-40e8017a-ff95-11e7-9632-8b9d7f0f0a6e.png)

Also checked in NuGet explorer
![image](https://user-images.githubusercontent.com/1647294/35230006-2f99d3e4-ff95-11e7-87a0-7a7e8066628b.png)

**Comment by TerraVenil** [comment]
What version of nuget client are you using?

**Comment by devlead** [comment]
I used the download link on https://www.nuget.org/packages/Cake.IIS/0.3.1
![screenshot_20180122-171956](https://user-images.githubusercontent.com/1647294/35231271-a6e7261a-ff98-11e7-8426-46527ac5fe03.jpg)

**Comment by TerraVenil** [comment]
Am I right understand that currently Cake.IIS does't support NETStandard?

**Comment by TerraVenil** [comment]
@devlead, @SharpeRAD could you expalin why `NuGet.exe` load 'Cake.IIS' with supported .Net Core build? Currently it's confused behaviour for me.
@SharpeRAD do you need help with building `Cake.IIS` under .Net Core locally :smile:?

**Comment by SharpeRAD** [comment]
It doesn't. There is no .net core package for Cake.IIS hosted on nuget.

Cake.IIS builds, but there are reference issues within "Microsoft.Web.Administration" that prevent it running locally or on AppVeyor. Feel free to try the current TestSuite out for yourself, I will accept any PR's that resolve the issue.

**Comment by gep13** [comment]
I am going to go ahead and close this issue, as it is best discussed in the Cake.IIS repository.

**Comment by TerraVenil** [comment]
@gep13 I think error message `Failed to install addin 'Cake.IIS'` it's not obvious at least for me what is going on. If current exception related to .NET Core but addin currently supported ONLY net461 that error message should be more informative for example, `Failed to install addin 'Cake.IIS' because target framework should be netstandard1.6`.
