### ISSUE TITLE
In-process NuGet don’t support multiple feeds through config

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#2014]
Simple fix, put a `string.Split(’;’,..)` here https://github.com/cake-build/cake/blob/develop/src/Cake.NuGet/Install/NuGetSourceRepositoryProvider.cs#L37

**Comment by Insire** [comment]
I actually ran into this issue earlier this week. I'd be willing to PR this. Is this up for grabs?

**Comment by mholo65** [comment]
@Insire, sure! Go nuts! :smile:

**Comment by Insire** [comment]
Cool, going for it:)
