### ISSUE TITLE
Cake 0.25 cannot install addins

### ISSUE THREAD

**Issue by harry-cpp** [cake-build/cake#2037]
### What You Are Seeing?

Adding any addin to the cake script results in it failing to run.

### What is Expected?

It runs.

### What version of Cake are you using?

0.25, downgrading to 0.24 solves the problem for me.

### Are you running on a 32 or 64 bit system?

64 bit

### What environment are you running on?  Windows? Linux? Mac?

Linux

### Are you running on a CI Server?  If so, which one?

Running locally on Fedora 27.

### How Did You Get This To Happen? (Steps to Reproduce)

Add an addin to the build.cake script and try to run it.

### Output Log

~~~sh
Feeds used:
  /home/harry/.nuget/packages/
  https://api.nuget.org/v3/index.json

All packages listed in /mnt/Data/GitHub/GtkSharp/tools/packages.config are already installed.
Analyzing build script...
Processing build script...
Installing addins...
Install failed. Rolling back...
Error: One or more errors occurred.
	Could not load type 'NuGet.Packaging.PackageArchiveReader' from assembly 'NuGet.Packaging, Version=4.3.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
~~~

**Comment by coder2000** [comment]
I am getting the same issue on every version since 0.24.0 on Ubuntu 18.04

**Comment by catafest** [comment]
Same error with Fedora 29 (when I try to build Librelancer game)
```
[root@desk Librelancer]# ./build.sh 
Feeds used:
  https://api.nuget.org/v3/index.json

All packages listed in /home/mythcat/Librelancer/tools/packages.config are already installed.
Install failed. Rolling back...
Error: One or more errors occurred.
	Could not load type 'NuGet.Packaging.PackageArchiveReader' from assembly 'NuGet.Packaging, Version=4.7.0.5, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

```

**Comment by devlead** [comment]
@catafest running Mono or .NET Core?
Which version of the Mono or .NET Core?
If on Mono does it work if you launch Cake with `cake.exe --nuget_useinprocessclient=false` (read more at https://cakebuild.net/docs/fundamentals/default-configuration-values#in-process-nuget-installation)

**Comment by augustoproiete** [comment]
It's been a long time and I'm just triaging issues. Addins work well on all runners in recent versions of Cake. Closing this as stale. Feel free to reopen if needed.
