### ISSUE TITLE
Cake page has two Nugets options in Addins List.

### ISSUE THREAD

**Issue by nikhilagrawaldotnet** [cake-build/cake#2043]
### What You Are Seeing?<br>
In http://cakebuild.net/addins/, there are two Nugets options in Addin's List namely 'Nuget' and 'NuGet'. Both takes us to same location - http://cakebuild.net/addins/nuget/.

![cake_issue](https://user-images.githubusercontent.com/26463468/36365604-467791c8-1570-11e8-8a30-37478021eb6f.jpg)

### What is Expected?
Single option. Two options confuse users.

### What version of Cake are you using?
N/A

### Are you running on a 32 or 64 bit system?
N/A

### What environment are you running on?  Windows? Linux? Mac?
N/A

### Are you running on a CI Server?  If so, which one?
N/A

### How Did You Get This To Happen? (Steps to Reproduce)
N/A

### Output Log
N/A

GIST LINK - Please create a gist and link to that gist here
N/A

OR

PLACE LOG CONTENT HERE
N/A

**Comment by gep13** [comment]
@daveaglick is there anything that we can do here?   Obviously, other than go to the addin's and ensure that there is consistency.

**Comment by devlead** [comment]
Feels like potential ordinal ignore case fix, which is fine in this case but in other cases like C# thingies are case sensitive. But Categories most likely shouldn't be.

**Comment by devlead** [comment]
Issue moved to [cake-build/website #489](https://github.com/cake-build/website/issues/489) via [**ZenHub**](https://www.zenhub.com/)
