### ISSUE TITLE
Specify version during Nuget Updating

### ISSUE THREAD

**Issue by nikhilagrawaldotnet** [cake-build/cake#2047]
### What You Are Seeing?
During updating nuget via Cake, there is no option to specify version. It always updates to latest version. What if I want penultimate version?

### What is Expected?
An option to take version. If not specified, should update to latest version.

### What version of Cake are you using?
0.25.0

### Are you running on a 32 or 64 bit system?
x64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
Will use TeamCity in future. However ATM, using  VSCode for creating cake scripts.

### How Did You Get This To Happen? (Steps to Reproduce)
I want to update specific packages to a desired version. I was able to specify Id's but not their version. Cake code confirmed my suspicion. The `NuGetUpdateSettings` does hot have property to specify version and therefore `NuGetUpdater` does not add version parameter to `nuget.exe` parameters whereas `Nuget.CommandLine` do provide such option.

![cake1](https://user-images.githubusercontent.com/26463468/36409619-830c2d8e-1632-11e8-851b-a13c7690fda4.JPG)

![test](https://user-images.githubusercontent.com/26463468/36409702-15ad16f8-1633-11e8-9288-d6631f21927e.jpg)

**Comment by mholo65** [comment]
Closed #2046
