### ISSUE TITLE
DotNetCoreToolSettings.WorkingDirectory is not respected when running DotNetCoreTool

### ISSUE THREAD

**Issue by derwasp** [cake-build/cake#2048]
### What You Are Seeing?
Working directory is taken from [here](https://github.com/cake-build/cake/blob/edd75e172fccd18de5801b82446c103e040d4ff8/src/Cake.Common/Tools/DotNetCore/Tool/DotNetCoreToolRunner.cs#L60), while it seems like `DotNetCoreToolSettings` should override it.

### What is Expected?
`DotNetCoreToolSettings.WorkingDirectory is respected`

### What version of Cake are you using?
0.25.0

### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
Windows

### How Did You Get This To Happen? (Steps to Reproduce)
```
void PackageLambda(FilePath project, string outputFile)
{
    var lambdaCmd = string.Format("package --output-package {0} --configuration Release --framework netcoreapp1.0", outputFile);
    var settings
        = new DotNetCoreToolSettings{
            WorkingDirectory = "my @@ random ## invalid //// directory",
            DiagnosticOutput = true
        };
    DotNetCoreTool(project, "lambda", lambdaCmd, settings);
}
```
The code above should fail, because the working dir is invalid, but it works just fine.

**Comment by GeertvanHorrik** [comment]
Running into this as well with 0.30.0, but just checked the source code and it's still the same on the latest main branch.

**Comment by GeertvanHorrik** [comment]
A workaround for now is to pass in `null` for the first argument, like this:

```
var arguments = new List<string>();

arguments.Add("--dry-run");

if (failOnChanges)
{
    arguments.Add("--check");
}

DotNetCoreTool(null, "format", string.Join(" ", arguments),
    new DotNetCoreToolSettings
    {
        WorkingDirectory = "./src/"
    });
```

**Comment by kashifsoofi** [comment]
Can I please work on this?
