### ISSUE TITLE
Cake fails to respect that packages are already installed in the tools folder

### ISSUE THREAD

**Issue by sgrassie** [cake-build/cake#2049]
### What You Are Seeing?
Cake does not respect the fact that packages in `\tools` are already installed and tries to download them again, causing an error resolving `api.nuget.org` on a build server with no connection to the internet.

The decision to commit the `\tools` and `\packages`  folders to source control is mandated and outside my control, despite my protestations, using an internal nuget feed is not an option.

### What is Expected?
With a `cake.config` set to `UseInProcessClient=false`, I expected the previous behaviour from earlier versions of Cake to resume, such that it found that packages where already installed in `\tools` and continued execution of the script.

### What version of Cake are you using?
0.25.0

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows Server 2012 R2

### Are you running on a CI Server?  If so, which one?
TeamCity

### How Did You Get This To Happen? (Steps to Reproduce)
1. Have a normal Cake script with an Addin, e.g. `xunit.runner.console`
2. Have a cake.config set to UseInProcessClient=false
3. Run the script in an online environment to populate the tools/packages folder
4. Run the script in an offline environment

### Further info
I see that there is work in progress in #1938 to address this and there is also #2009 which is similar, but not quiet what I'm seeing.

**Comment by sgrassie** [comment]
Here I am four years later to close this, after eventually learning what was causing this. 

When a source control system's ignore file is set to ignore *.nupkg files in a project, and that project is then built in an offline build server, it causes NuGet (and thus Cake) to decide that despite all the rest of a particular NuGet package existing on disk (e.g. the dll and config files), the lack of a .nupkg file means that the package is invalid, and it must attempt to redownload it. Which then fails.

Now we can debate the merits of checking in packages into source control as much as you like (hint: I do not like it, no sir), that decision was and still is beyond me.

**Comment by pascalberger** [comment]
@sgrassie Thanks for reporting your findings back 👍
