### ISSUE TITLE
Add support for msbuild.exe /restore option

### ISSUE THREAD

**Issue by sanderaernouts** [cake-build/cake#2051]
Recently the /restore option was added to msbuild.exe to ensure the Restore target is invoked before any other target. This behaviour is required for new style CSPROJ files to ensure the necessary files, such as project.assets.json, are generated before the Build target is invoked. See https://github.com/Microsoft/msbuild/pull/2414 for more details.

Normally NuGet restore would take care of this as well or dotnet CLI (dotnet build) but if you use an alternate NuGet client such as Paket the Restore target must still be invoked to generate these files.

The current work around for this would be:
> msBuildSettings.ArgumentCustomization = args =>
>     args.Append("/consoleloggerparameters:ForceConsoleColor")

There is no option to add the "/restore" directly from the MSBuildSettings class.

**Comment by devlead** [comment]
Fixed by  #2050
