### ISSUE TITLE
NuGetPack overwrites `developmentDependency` and `requireLicenseAcceptance` from nuspec.

### ISSUE THREAD

**Issue by williamb1024** [cake-build/cake#2061]
### What You Are Seeing?

Builtin NuGetPack always replaces `developmentDependency` and `requireLicenseAcceptance` values when transforming a nuspec file.

Only `developmentDependency` and `requireLicenseAcceptance` operate in this manner.

### What is Expected?

NuGetPack would not replace any setting within the nuspec, unless that setting has been specifically configured within the NuGetPackSettings instance. 

### What version of Cake are you using?
0.25.0+Branch.main.Sha.05b4d3f596defbdf5baecdb3712c9bc17f849b55

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
Occurs for any call to NuGetPack when provided with a nuspec file with the `developmentDependency` setting configured as `true`.

**Comment by mattleibow** [comment]
Any progress on this? I am getting this and luckily we have a step to verify that this was set.
