### ISSUE TITLE
Referencing an older version of Cake.Core

### ISSUE THREAD

**Issue by nowakpiotr** [cake-build/cake#2064]
https://github.com/MihaMarkic/Cake.Docker/issues/29

Hi,

Cake 0.26.0 was released which finally runs on .Net Core 2.0 and doesn't need .Net Core 1.x anymore to build.

I tried to update our projects to Cake 0.26.0 where we use your plugin but I get the following error message:

Downloading NuGet.exe...
Installing Cake...
Running build script...
Analyzing build script...
Processing build script...
Installing addins...
Error: The assembly 'Cake.Docker, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
It seems to me, that Cake.Docker needs to reference the new Cake version to work properly.

**Comment by gep13** [comment]
@nowakpiotr yes, this is expected.  There were a number of breaking changes in the 0.26.0 release, and as a result, we are trying to ensure that there are no errors are run time.  You may be able to use the suggested workaround in the above error message until Cake.Docker is updated.

I would suggest you raise an issue on the Cake.Docker repository here:

https://github.com/MihaMarkic/Cake.Docker

I am going to go ahead and close this issue, as it is not specific to Cake itself.
