### ISSUE TITLE
cake.coreclr help information error

### ISSUE THREAD

**Issue by linianhui** [cake-build/cake#2066]
### What You Are Seeing?
cake.coreclr help information error
### What is Expected?
Example: dotnet Cake.dll
Example: dotnet Cake.dll build.cake --verbosity=quiet
Example: dotnet Cake.dll build.cake --showdescription
### What version of Cake are you using?
0.26.1
### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
windows
### Are you running on a CI Server?  If so, which one?
no
### How Did You Get This To Happen? (Steps to Reproduce)
dotnet cake.dll
### Output Log
dotnet .\Cake.dll --help

Usage: Cake.exe [script] [--verbosity=value]
                [--showdescription] [--dryrun] [..]

Example: **Cake.exe**
Example: **Cake.exe** build.cake --verbosity=quiet
Example: **Cake.exe** build.cake --showdescription

Options:
    --verbosity=value    Specifies the amount of information to be displayed.
                         (Quiet, Minimal, Normal, Verbose, Diagnostic)
    --debug              Performs a debug.
    --showdescription    Shows description about tasks.
    --dryrun             Performs a dry run.
    --version            Displays version information.
    --help               Displays usage information.

**Comment by augustoproiete** [comment]
This has been fixed by https://github.com/cake-build/cake/pull/3031 and will be available in Cake v1.0.0 RTM
