### ISSUE TITLE
AddIn updated to Cake 0.26.1 raise exception after install

### ISSUE THREAD

**Issue by akordowski** [cake-build/cake#2068]
I have updated the [Cake.Compression](https://github.com/akordowski/Cake.Compression) AddIn to Cake 0.26.1. The AddIn is installed correctly, but raises after installation an exception.

### What You Are Seeing?
`Cake.Core.CakeException: Failed to install addin 'Cake.Compression'.`

### What is Expected?
No exception.

### What version of Cake are you using?
0.26.1

### Are you running on a 32 or 64 bit system?
x64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### How Did You Get This To Happen? (Steps to Reproduce)
```
#addin "nuget:?package=Cake.Compression&version=0.1.5"

Task("Build")
    .Does(() => { });

Task("Default")
    .IsDependentOn("Build");

RunTarget("Default");
```

### Output Log
```
Preparing to run build script...
Running build script...
Module directory does not exist.
NuGet.config not found.
Analyzing build script...
Analyzing D:/Projects/Cake Test/build.cake...
Processing build script...
Installing addins...
Retrieving package 'Cake.Compression 0.1.5' from 'https://www.nuget.org/api/v2/'.
Adding package 'Cake.Compression.0.1.5' to folder 'D:\Projects\Cake Test\tools\Addins'
Added package 'Cake.Compression.0.1.5' to folder 'D:\Projects\Cake Test\tools\Addins'
Added package 'Cake.Compression.0.1.5' to folder 'D:\Projects\Cake Test\tools\Addins' from source 'https://www.nuget.org/api/v2/'
Successfully installed 'Cake.Compression 0.1.5' to D:/Projects/Cake Test/tools/Addins
Executing nuget actions took 120,59 ms
Error: Cake.Core.CakeException: Failed to install addin 'Cake.Compression'.
   bei Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath)
   bei Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   bei Cake.Commands.BuildCommand.Execute(CakeOptions options)
   bei Cake.CakeApplication.Run(CakeOptions options)
   bei Cake.Program.Main()
```

**Comment by gep13** [comment]
@akordowski could you please run the same again using Diagnostic Verbosity, and post the output here?  Thanks!

**Comment by akordowski** [comment]
@gep13 This is the diagnostic output.

**Comment by gep13** [comment]
@akordowski seems like you addin is targetting 4.6.2.  Cake targets 4.6.1.

**Comment by akordowski** [comment]
@gep13 Yes, thats the case. Thank you for the hint, I will fix it.

**Comment by gep13** [comment]
@akordowski let us know if that resolves the issue, and we can get this issue closed.

**Comment by akordowski** [comment]
I changed the framework target to 4.6.1 and it works now as expected. Thanks a lot for your help and time!
