### ISSUE TITLE
Issue with context.arguments in script alias

### ISSUE THREAD

**Issue by timschps** [cake-build/cake#2071]
### What You Are Seeing?
I'm trying to create a script alias that uses the context.arguments property (to enable some context aware logic in the alias), but for some reason it is empty... 

This can be seen here (debugging session): ![2018-03-08 07_31_37-buildsupport debugging - microsoft visual studio](https://user-images.githubusercontent.com/13098307/37137165-ea7f80dc-22a4-11e8-9a79-ed3a07c7b5e8.png)

### What is Expected?
The context.arguments property should contain (at least) the arguments that have been specified in the build.cake file (and preferably other arguments that have been defined in other script aliases) (cross alias information)
### What version of Cake are you using?
0.25.0
### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
win 10
### Are you running on a CI Server?  If so, which one?
Currently not, but should end up on Teamcity

### How Did You Get This To Happen? (Steps to Reproduce)
in build.cake:
-->in the header:
`var granularversion = Argument("granularversion", "somerandomvalue"); `

--> in the Task
`var granularversions = demoMethod();`

And then in the csproj file containing the script alias:

`
using Cake.Common.Build;
using Cake.Core;
using Cake.Core.Annotations;

namespace BuildSupport
{
    public static class CakeTasks
    {
       
 [CakeMethodAlias]
        public static void demoMethod(this ICakeContext context)
        {
            if (context.Arguments.HasArgument("granularversion")) //-->always returns false (arguments is always empty)
            {
                context.TeamCity().WriteStatus("Granular version exits");
                var granularVersion = context.Arguments.GetArgument("granularversion"); //always returns nullreferenceexception (if not placed in if statement of course)
            }
        }
    }
}

 `

### Output Log
https://gist.github.com/timschps/65fd9f16a430a0d6c855b58ca199a29d

**Comment by augustoproiete** [comment]
(Moving to GitHub Discussions)
