### ISSUE TITLE
Default sources not loaded if nuget_source is empty

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#2079]
#2014 introduced a bug where default sources would not be loaded if `nuget_source` config was null or empty.

Providing PR...

**Comment by Insire** [comment]
I wonder how your proposed changes are fixing the default sources not being loaded when nuget_source is empty.

From what i can gather from your commit 9d0450e, is that you inverted the previous check on NullorEmpty for nuget_source and moved the loop over the sources into that if statement.

My assumption would be to use a default value of a nuget source to submit to CreateRepository, in the case that nuget_sources is empty.

What am i missing here?

**Comment by mholo65** [comment]
@Insire I've inverted the check and replaced the `return` with the `foreach`loop which was previously after the if statement (this is exactly same behaviour with regards of parsing `nuget_source` config variable).

What this however fixes, is that it removes the `return`, which previously stopped us from hitting [this](https://github.com/cake-build/cake/commit/9d0450efb87e5773b5f467f878207aa736af588b#diff-0cc73d66d65f4fb481c687bade855dc5L66), i.e. the default sources from the `PackageSourceProvider`.
