### ISSUE TITLE
Cake does not load dependencies in correct order

### ISSUE THREAD

**Issue by Jericho** [cake-build/cake#2084]
My addin (Cake.Email) which targets `netstandard2.0` in order to be used with Cake 0.26.0 is dependent on the MimeKit nuget package which targets multiple .NET frameworks, including netstandard2.0. Mailkit depends on the BouncyCastle.

When you execute a `build.cake` that references my addin, cake successfully downloads all the dependent packages but it doesn't seem to be loading in memory the version targeting the right framework (the desired framework in this case is netstandard2.0). 

**Steps to reproduce**

1. Create a folder called `Testing` and save a copy of cake's latest `build.ps1`
2. Create a sub folder called `tools`
3. Create a file called packages.config in the `tools` folder with the following content:
```xml
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Cake" version="0.26.0" />
</packages>
```
4. Create a file called `Email.cake` in the `Testing` folder with the following content
```csharp
#addin nuget:?package=Cake.Email&version=0.6.0&loaddependencies=true

using Cake.Email.Common;

var smtpHost = "smtp.gmail.com";
var port = 465;
var enableSsl = true;
var username = "<your_gmail_username>@gmail.com";
var password = "<your_gmail_password>";

var recipients = new[]
{ 
    new MailAddress("<your_email_address>")
};

try
{
    var result = Email.SendEmail(
            senderName: "Bob Smith", 
            senderAddress: "bob@example.com",
            recipients: recipients,
            subject: "This is a test",
            htmlContent: "<html><body>This is a HTML test<br/><img src=\"http://www.msnbc.com/sites/msnbc/themes/leanforward/images/site-header/msnbc-logo-small.png\"/><img src=\"cid:abc123\"/></body></html>",
            textContent: "This is a TEXT test",
            attachments: null,
            settings: new EmailSettings 
            {
                SmtpHost = smtpHost,
                Port = port,
                EnableSsl = enableSsl,
                Username = username,
                Password = password
            }
    );

    if (result.Ok)
    {
        Information("Email succcessfully sent");
    }
    else
    {
        Error("Failed to send email: {0}", result.Error);
    }
}
catch(Exception ex)
{
    Error("{0}", ex);
}
```
5. Replace `<your_gmail_username>`, `<your_gmail_password>` and `<your_email_address>` with appropriate values. If you don't have a gmail account, don't worry about it: gmail will return a ` Username and Password not accepted` error message when you run the script which you can disregard. You will still be able to witness the issue I am describing.
6. Execute the script like so: `.\build.ps1 -script email.cake`

**Expected result**
You should expect the script to complete without any errors.

**Observed result**
You will see the following log in the console window:
```
Preparing to run build script...
Running build script...
Could not load E:\_build\Cake.Email\tools\Addins\MimeKit.2.0.1\lib\net45\MimeKit.dll (missing BouncyCastle.Crypto, Version=1.8.1.0, Culture=neutral, PublicKeyToken=0e99375e54769942)
```

Notice the path of the MimeKit DLL says `net45` which is surprising, I would have expected `netstandard2.0`. This leads me to conclude that Cake is not loading the appropriate version of this nuget package into memory.

Also, notice that it complains about not finding BouncyCastle.Crypto despite the fact that it was successfully downloaded and is present in the `tools\Addins` sub folder.

**Comment by mholo65** [comment]
The fact that `net45` is loaded instead of `netstandard2.0` is completely ok when `Cake.exe` targets `net461`. This is the best match according to NuGet. This can be reproduced by creating a new `dotnet` project, target `net461` and add `Cake.Email` as a package rreference. After running `dotnet restore`, you'll see that `obj\projects.assets.json` contains the following:

```Json
{
  "version": 3,
  "targets": {
    ".NETFramework,Version=v4.6.1": {
      "BouncyCastle/1.8.1": {
        "type": "package",
        "compile": {
          "lib/BouncyCastle.Crypto.dll": {}
        },
        "runtime": {
          "lib/BouncyCastle.Crypto.dll": {}
        }
      },
      "Cake.Email/0.6.0": {
        "type": "package",
        "dependencies": {
          "Cake.Email.Common": "0.2.0",
          "MailKit": "2.0.1"
        },
        "compile": {
          "lib/netstandard2.0/Cake.Email.dll": {}
        },
        "runtime": {
          "lib/netstandard2.0/Cake.Email.dll": {}
        }
      },
      "Cake.Email.Common/0.2.0": {
        "type": "package",
        "dependencies": {
          "MimeTypesMap": "1.0.2"
        },
        "compile": {
          "lib/netstandard2.0/Cake.Email.Common.dll": {}
        },
        "runtime": {
          "lib/netstandard2.0/Cake.Email.Common.dll": {}
        }
      },
      "MailKit/2.0.1": {
        "type": "package",
        "dependencies": {
          "BouncyCastle": "1.8.1",
          "MimeKit": "2.0.1"
        },
        "frameworkAssemblies": [
          "System",
          "System.Core",
          "System.Data",
          "System.Net.Http"
        ],
        "compile": {
          "lib/net45/MailKit.dll": {}
        },
        "runtime": {
          "lib/net45/MailKit.dll": {}
        }
      },
      "MimeKit/2.0.1": {
        "type": "package",
        "dependencies": {
          "BouncyCastle": "1.8.1"
        },
        "frameworkAssemblies": [
          "System",
          "System.Core",
          "System.Data",
          "System.Net.Http",
          "System.Security"
        ],
        "compile": {
          "lib/net45/MimeKit.dll": {}
        },
        "runtime": {
          "lib/net45/MimeKit.dll": {}
        }
      },
      ...
```

What however is a bug, is that dependencies are not loaded in correct order. In this case, we'd need to make sure `BouncyCastle.Crypto` is loaded before `MimeKit`.
