### ISSUE TITLE
Unable to set 'no-build' and 'no-restore' when executing DotNetCoreRun

### ISSUE THREAD

**Issue by Jericho** [cake-build/cake#2092]
The `DotNetCoreRunSettings` class does not have properties that would allow us to set these two values. 

To make matters worse, we can't use the usual workaround (which would look like this:  `ArgumentCustomization = args => args.Append("--no-restore --no-build")`) because the position is important: these settings cannot be appended at the end due to the fact the last position is reserved for arguments passed to the process being invoked.

**Comment by patriksvensson** [comment]
@Jericho Sounds like something that should be supported.

To solve your issue until this is implemented, have you tried using `ArgumentCustomization = args => args.Prepend("--no-restore --no-build")`?

**Comment by Jericho** [comment]
Unfortunately pretending the argument s is not an option either because the first position is reserved for the “run” command.

**Comment by patriksvensson** [comment]
@Jericho Ah, that's true. As a last resort you could always rewrite the Arguments completely until this have been fixed.
