### ISSUE TITLE
Add support for executing a single task without dependencies

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2094]
Sometimes you just want to execute a single task, without executing its dependencies. It would be nice to be able to tell Cake to just execute the task as it is.

```
> Cake.exe --target Foo --exclusive
```

**Comment by gep13** [comment]
@patriksvensson this sounds like a good idea to me.  I "think" @jnm2 might have created a related issue.

**Comment by patriksvensson** [comment]
@gep13 I looked for an issue, but couldn't find one when I wrote it.

I assume you're thinking about https://github.com/cake-build/cake/issues/1341, but that's not the same thing.

**Comment by gep13** [comment]
@patriksvensson yip, that is the one that I was thinking of.  Certainly related to this one.  Could both be tackled at the same time?

**Comment by patriksvensson** [comment]
@gep13 I don't know. I see them as two different features.

**Comment by jnm2** [comment]
You know, I think Patrik's idea would give me most of the benefit I was hoping for.
Especially if this is coupled with the ability to specify multiple tasks to run, which I hope we get to use with or without the --exclusive switch.
