### ISSUE TITLE
Make possibility to set Process Exit Code

### ISSUE THREAD

**Issue by Gargony** [cake-build/cake#2104]
Currently cake process can return exit code 0 or 1 only.
Will useful if I can return custom Process Exit Code from task.
e.g. `throw CakeExitCodeException(-1)`

**Comment by devlead** [comment]
Yip that could be useful, as a workaround you could currently use `System.Environment.Exit(-1);`

![image](https://user-images.githubusercontent.com/1647294/38080740-8ff4f1f2-3342-11e8-8787-19614957b23b.png)

**Comment by patriksvensson** [comment]
This doesn't have to be a new exception btw. We could add a constructor overload to the CakeException to contain an exit code, since it's always used to indicate a problem within Cake (that will lead to an exit if not handled)

**Comment by devlead** [comment]
@patriksvensson exactly just an overload constructor with 1 as default.
