### ISSUE TITLE
DoesForEach should evaluate compile time

### ISSUE THREAD

**Issue by Duracell1989** [cake-build/cake#2117]
### What You Are Seeing?
It looks like the "DoesForEach" of Task is pre-compiled, and isn't doing the "GetFiles" during runtime.

### What is Expected?
The "GetFiles" inside the ForEach should be evaluated at runtime and not during compile time. Because I want to ForEach over files which aren't available (yet) during compile time.

### What version of Cake are you using?
0.26.1
### Are you running on a 32 or 64 bit system?
64-bits
### What environment are you running on?  Windows? Linux? Mac?
Windows
### Are you running on a CI Server?  If so, which one?
Doesn't matter.

### How Did You Get This To Happen? (Steps to Reproduce)
Example:
I have 3 tasks:
1. Clean "/artifacts".
2. DotNetCorePack; which creates and saves multiple *.nupkg-files into /artifacts/pack  (with a unique timebased version).
3. DotNetCoreNuGetPush which uses the .DoesForEach(GetFiles("./artifacts/pack/*.nupkg"), (nugetFile) => <snip>

On the first (local) run; the directory doesn't exists; and the "DotNetCoreNuGetPush" tasks finishes without doing anything (thus: /artifacts was empty during compile-time).
On the second (local) run; the directory does exists during compile time (with the 'old' artifacts). My first tasks cleans the directory; and the second task creates new nupkg-files; (with a new unique timebased version).
Then; the third task does the ForEach but fails because it can find the **old** nupkg-file!

### Output Log
**First run:**
```
========================================
Pack
========================================
Successfully created package '<snip>\artifacts\pack\<snip>-201804061416.nupkg'.

========================================
Push-NuGet-Packages
========================================
<empty>
----------------------------------------
Teardown
----------------------------------------
```

**Second run:**
```
========================================
Pack
========================================
Successfully created package '<snip>\artifacts\pack\<snip>-201804061418.nupkg'.

========================================
Push-NuGet-Packages
========================================
error: File does not exist (<snip>/artifacts/pack/<snip>-201804061416.nupkg).
An error occurred when executing task 'Push-NuGet-Packages'.

----------------------------------------
Teardown
----------------------------------------
Error: One or more errors occurred.
        .NET Core CLI: Process returned an error (exit code 1).
```

**Comment by YakhontovYaroslav** [comment]
@devlead Unfortunately, even lambda version is not truly lazy:

```
var list = new List<string>();
Task("Default")
    .Does(() => {
        list.Add("test");
    })
    .DoesForEach(list, item => {
        Information("From DoesForEach: {0}", item);
    })
    .DoesForEach(() => list, item => {
        Information("From lazy DoesForEach: {0}", item);
    })
    .Does(() => {
        foreach (var item in list)
        {
            ForEach(item);
        }

        void ForEach(string item)
        {
            Information("From Does with foreach: {0}", item);
        }
    });

RunTarget("Default");
```

Note that information output will be printed only from last Does() using Cake.CoreCLR 0.28.1 on win-x64.
At first i`ve encountered this behavior trying to use Globber like this:
```
Task("Default")
    .Does(() => {
        // Create some directories with files
    })
    .DoesForEach(() => Context.GetDirectories("pattern"), item => {
       // More work
    })
```

That`s happening because lambda actually gets evaluated before first "Does" completes. It`s not blocking, because you can write foreach manually, but this indeed confusing and not very straightforward to use.
