### ISSUE TITLE
MSBuild doesn't resolve VS preview build tools

### ISSUE THREAD

**Issue by MichaelSL** [cake-build/cake#2128]
### What You Are Seeing?
VS Preview build tool is not resolved
### What is Expected?
Should be resolved after regular VS, before common build tool
### Are you running on a 32 or 64 bit system?
64 bit
### What environment are you running on?  Windows? Linux? Mac?
Windows

Found this when investigating question from cake gitter chat. Will create a patch for it.

`VSWhere` could be used as an alternative solution, but if you download the project from github and you have only VS Preview installed then you can't build the project without cake file modification.

**Comment by jnm2** [comment]
Outside of Cake, I use vswhere and fall back to using the `-prerelease` parameter if the first try didn't find anything.

**Comment by jnm2** [comment]
This affects all folks that have VS2019 RC or Preview and not VS2017. Here's what I'm doing:

```cs
// Workaround for https://github.com/cake-build/cake/issues/2128
var vsInstallation =
    VSWhereLatest(new VSWhereLatestSettings { Requires = "Microsoft.Component.MSBuild" })
    ?? VSWhereLatest(new VSWhereLatestSettings { Requires = "Microsoft.Component.MSBuild", IncludePrerelease = true });

if (vsInstallation != null)
{
    settings.ToolPath = vsInstallation.CombineWithFilePath(@"MSBuild\Current\Bin\MSBuild.exe");
    if (!FileExists(settings.ToolPath))
        settings.ToolPath = vsInstallation.CombineWithFilePath(@"MSBuild\15.0\Bin\MSBuild.exe");
}
```

**Comment by gep13** [comment]
Closing, VSWhere should be used for resolving Visual Studio Preview installations. See @jnm2's comment above.

**Comment by valuator18** [comment]
I had this same issue with the current, non-preview installation of VS2019. Cake was not using MSBuild 16.0 until I used @jnm2's workaround above.
