### ISSUE TITLE
Add exceptions thrown to TaskTeardownContext

### ISSUE THREAD

**Issue by joeharrison714** [cake-build/cake#2130]
I would like to be able to tell if a Task was successful in TaskTeardown. Currently there is no way to do it.  The solution suggested multiple times in the chat does not work.  (https://gitter.im/cake-build/cake?at=59e5f58c210ac26920f84026). The issue with that is that TaskTeardown always gets called even when it failed.

If the Exception thrown could be added to TaskTeardownContext, then it would be easy to tell if the task had failed.

**Comment by gep13** [comment]
@joeharrison714 I have added the `Breaking change` label to this issue, since there is a change to an interface in the associated PR.
