### ISSUE TITLE
Problems with loading certain assemblies (0.27.0)

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2132]
Reminder for @mholo65 to investigate https://github.com/SharpeRAD/Cake.Powershell/issues/55

**Comment by mholo65** [comment]
Hmmm.. Looked at logs again, seems like infinite recursion is coming from the ScriptAssemblyResolver https://github.com/cake-build/cake/blob/develop/src/Cake/Scripting/Roslyn/ScriptAssemblyResolver.cs

@daveaglick, ping!

**Comment by daveaglick** [comment]
Yep, I broke it - will get a fix in the next couple hours, suggest it gets merged and released ASAP. Sorry!
