### ISSUE TITLE
Enabling initializer syntax for all collection properties

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#2146]
It's intuitive to try this super clean C#:

```cs
new FooToolSettings
{
    EnvironmentVariables = { ["FOO"] = "foo" }
}
```

`EnvironmentVariables`, like (almost?) every Cake settings collection property, is not initialized in the constructor. Thus, this code results in NullReferenceException.

The workaround doesn't leave me with the sense of happiness I expect from a mutable C# API:
```cs
new FooToolSettings
{
    EnvironmentVariables = new Dictionary<string, string> { ["FOO"] = "foo" }
}
```

### Proposal

Please initialize all collection properties (including dictionary properties) either on construction or lazily in the getter. [For example](https://github.com/cake-build/cake/blob/52bd7efc142f47887bdd8d73ef8f508e12c5d654/src/Cake.Core/Tooling/ToolSettings.cs#L69):

```cs
public IDictionary<string, string> EnvironmentVariables { get; set; } =
    new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
```

### Recommending not to use the setters

Due to backwards compatibility the setters must remain, but is there room to add XML docs or maybe even an obsoletion warning recommending that you use the pre-initialized instance?
To me there seems to be an abstraction issue with allowing this property to be set: what is the difference in meaning between these two lines, and why should I be offered this control as a user of Cake?

```cs
EnvironmentVariables = new Dictionary<string, string>(StringComparer.CurrentCulture) { ["FOO"] = "foo" }
EnvironmentVariables = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase) { ["FOO"] = "foo" }
```

-----

If this sounds good to you, I'm willing to add the tests and do the PR.
I'd add cross-cutting tests that dynamically locate each class assignable to `ToolSettings`, instantiate it, get the value of each `ICollection<>` property, and assert that it is not null. There could be a whitelist of properties to ignore if the need ever arises.

**Comment by mholo65** [comment]
I’m completely ok with this! How about rest of @cake-build/cake-team

**Comment by patriksvensson** [comment]
Yes, me too!

**Comment by jnm2** [comment]
Awesome! Here's the PR: https://github.com/cake-build/cake/pull/2147

Turns out it's not possible to obsolete specific accessors, so here's a question. Does it make sense to log a warning in all the setters that it's recommended to use the initialized instance? That opens the door for a 0.28 or future version down the road in which you might decide to remove the getters.
