### ISSUE TITLE
try resolve vstest.console.exe before guessing it

### ISSUE THREAD

**Issue by paulomorgado** [cake-build/cake#2152]
Visual Studio Test Runner is not part of the [Visual Studio Build Tools](https://docs.microsoft.com/en-us/visualstudio/install/workload-component-id-vs-build-tools "Visual Studio Build Tools 2017 component directory") but is available on NuGet as [Microsoft.TestPlatform](https://www.nuget.org/packages/Microsoft.TestPlatform).

If the user installs the `Microsoft.TestPlatform`, that should be used instead of trying to guess the path.

**Comment by mholo65** [comment]
Closed by #2151
