### ISSUE TITLE
Problem with loading abolute path scripts with #load preprocessor

### ISSUE THREAD

**Issue by Kemyke** [cake-build/cake#2154]
### What You Are Seeing?
Loading a script with absolute path is only working if the full definition is applied: `#load \"local:?path=c:/utils.cake\"`. It is not working with legacy format `#load \"c:/utils.cake\"`.

### What is Expected?
It should work for both syntaxes.

### What version of Cake are you using?
0.27.1

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No.

The problem is with the `ParseUriFromTokens` method in `UriDirectiveProcessor` class. It first tries to create `Uri` from the token. If it is a relative path the creation will fail and the `CreateUriFromLegacyFormat` will be applied because of the `UriKind.Absolute` parameter in `TryCreate` call. But if the token is an absolute path, the Uri creation will success and the `Uri` will be `file:///c:/CakeScripts/utils.cake`. But this `Uri` won't be processed because in `FileLoadDirectiveProvider` class the `CanLoad` method will return false because the `Scheme` will be `file` and not `local` as expected.
Maybe the `Uri.TryCreate` is not the best way to decide if the `CreateUriFromLegacyFormat` should be applied or not. Maybe it would be better to have a previous step which check if the token is match with the appropriate regexp. (somtehing like `[local|nuget]:\?`)

**Comment by devlead** [comment]
fixed by #2155
