### ISSUE TITLE
Add newer nuspec properties to NuGetPackSettings

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#2156]
`NuGetPackSettings` (and related classes) should implement the newer properties documented in https://docs.microsoft.com/en-au/nuget/reference/nuspec (and https://github.com/NuGet/NuGet.Client/blob/dev/src/NuGet.Core/NuGet.Packaging/compiler/resources/nuspec.xsd)

In particular the PackageReference-related properties like contentFiles etc

**Comment by daveMueller** [comment]
Here is a pull request for this #2516 . Would be cool if somebody will review.
