### ISSUE TITLE
NuGetPack with nuspec that contains contentFiles becomes invalid

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#2157]
### What You Are Seeing?

The wrong <files> element(s) are being updated by NuspecTransformer

### What is Expected?

Only the /package/metadata/files section should be updated

### What version of Cake are you using?
0.26.1
### What environment are you running on?  Windows? Linux? Mac?
Windows
### How Did You Get This To Happen? (Steps to Reproduce)

Run NuGetPack against a nuspec file that contains <contentfiles><files /></contentFiles>, passing in a NuGetPackSettings object that contains Files.

Looks like https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs#L73 will match all `files` elements, rather than just the correct one.

**Comment by piamay** [comment]
Today I stumbled about this, too. Following small correction inside the develop branch fixes the bug:

`diff --git a/src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs b/src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs
index 32e78033..b945b3b2 100644
--- a/src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs
+++ b/src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs
@@ -110,7 +110,7 @@ namespace Cake.Common.Tools.NuGet.Pack
             if (settings.Files != null && settings.Files.Count > 0)
             {
                 var filesPath = string.Format(CultureInfo.InvariantCulture,
-                    "//*[local-name()='package']//*[local-name()='files']");
+                    "//*[local-name()='package']/*[local-name()='files']"); // removed one slash
                 var filesElement = document.SelectSingleNode(filesPath, namespaceManager);
                 if (filesElement == null)
                 {`

I hope some of the devs could fix it.

**Comment by flcdrg** [comment]
Hi Pia,
Can you create a pull request with your changes?

David

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by piamay** [comment]
Pull request done. The first i've made ;)

Pia

**Comment by devlead** [comment]
Fixed by #2550
