### ISSUE TITLE
The CLA link in readme seems invalid or broken.

### ISSUE THREAD

**Issue by AraHaan** [cake-build/cake#2188]
### What You Are Seeing?
The CLA link on the readme.md file seems to be invalid or broken.

### What is Expected?
To get linked to the actual CLA page.

### What version of Cake are you using?
None yet.

### Are you running on a 32 or 64 bit system?
x64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
- Read the readme on github down the the CLA part.
- Click the CLA word.
- Get linked to a webpage that never loads.

### Output Log

I do not have a log yet as cake is not installed yet and seen this issue on github only.

**Comment by gep13** [comment]
@AraHaan thank you for pointing this out!
