### ISSUE TITLE
Cake Process Hanging and Failing to Exit

### ISSUE THREAD

**Issue by RehanSaeed** [cake-build/cake#2189]
### What You Are Seeing?

My Cake script completes but the process does not exit, causing my AppVeyor build to time out after an hour. Here is my script:

https://ci.appveyor.com/project/RehanSaeed/templates/build/433

### What is Expected?

The cake process should exit at the end of the script.

### What version of Cake are you using?

0.28.0

### Are you running on a 32 or 64 bit system?

64 bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

AppVeyor

https://ci.appveyor.com/project/RehanSaeed/templates/build/433

### How Did You Get This To Happen? (Steps to Reproduce)

I'm building the cake script here on AppVeyor:

https://github.com/Dotnet-Boxed/Templates

### Output Log

https://ci.appveyor.com/project/RehanSaeed/templates/build/433

**Comment by daveaglick** [comment]
A search in the Roslyn issue turned up this which sounds similar/same: https://github.com/dotnet/roslyn/issues/27566

The suggestion there is to set the `UseSharedCompilation` MSBuild property to `false` (there are some other suggested MSBuild property settings as well, but that one looks like the most promising place to start).

**Comment by RehanSaeed** [comment]
One thing I've learned as a developer is that 99.99999% of the time it's your fault. This is one of the 0.000001% of times when it's not. Hurrah!

I've been using this workaround successfully using Cake to kill all extraneous processes:

```
Teardown(context =>
{
    // Appveyor is failing to exit the cake script.
    if (AppVeyor.IsRunningOnAppVeyor)
    {
        foreach (var process in Process.GetProcessesByName("dotnet"))
        {
            process.Kill();
        }
    }
});
```

**Comment by gep13** [comment]
It could be that AppVeyor is monitoring all processes spawned as part of the build?

**Comment by mholo65** [comment]
Also, in your AppVeyor script, you could call `Get-Process dotnet | Stop-Process` after calling `build.ps1`

**Comment by RehanSaeed** [comment]
I opened a thread with AppVeyor [here](https://help.appveyor.com/discussions/problems/14580-build-hanging-even-after-script-exits). According to them:

> If any of steps in pipeline return exit code other than 0, build fails. Otherwise succeed.
AppVeyor has custom implementation of PowerShell's PSHost in which commands like Cake script runs. What happened here is those handing processes do not let it exit command execution.

**Comment by patriksvensson** [comment]
@RehanSaeed Since this is outside of Cake's control, I'm going to close this issue. Please feel free to reopen it if you feel that this has been done in error.
