### ISSUE TITLE
Supress NuGet dependency warnings related to Cake.Core

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2190]
This warning should be outputted with `Verbose` or `Diagnostic` verbosity instead of being a warning.

![image](https://user-images.githubusercontent.com/357872/41334938-74cec674-6ee7-11e8-9693-05c101afea50.png)

**Comment by gep13** [comment]
@patriksvensson were you planning on putting this out with the upcoming hotfix release?  Or with the next release?

**Comment by patriksvensson** [comment]
I think this could be part of the hotfix release if it's an easy fix.
