### ISSUE TITLE
WithCriteria<DataObject> does not work with 'DryRun' (WhatIf flag)

### ISSUE THREAD

**Issue by jpdavid** [cake-build/cake#2208]
### What You Are Seeing?

"The context data has not been setup"

### What is Expected?

Build script completes without error, respecting any custom data provided in the 'Setup' tasks.

### What version of Cake are you using?

0.28.0

### Are you running on a 32 or 64 bit system?

64-bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

No

### How Did You Get This To Happen? (Steps to Reproduce)

Using the following in the build.cake file:

public class TestConfig
{
    public bool SomeVar { get; set; }
}

Setup<TestConfig>((context) =>
{
    return new TestConfig() { SomeVar = false };
});

Task("A")
    .Does<TestConfig>((context, data) =>
{
    Information($"SomeVar = {data.SomeVar}");
});

Task("B")
    .IsDependentOn("A")
    .WithCriteria<TestConfig>((context, data) => data.SomeVar)
    .Does<TestConfig>((context, data) =>
{
    Information($"SomeVar = {data.SomeVar}");
});

Task("Default").IsDependentOn("B");

RunTarget("Default");

Run build.ps1 -WhatIf

### Output Log

Preparing to run build script...
Running build script...
Performing dry run...
Target is: Default

1. A
Error: One or more errors occurred.
        The context data has not been setup.

**Comment by jpdavid** [comment]
@devlead I have had some thoughts on this.

I understand that with the DryRun execution, you don't want to run any task action code, including setup tasks. This makes perfect sense.

Would it be a good idea to move the Data Object setup code into its own type of Setup task?

e.g.

public class MyBuildData
{
}

DataSetup<MyBuilkdData>(dataSetupContext =>
{
  return new MyBuildData();
});

Setup(setupContext => {
  // Do some stuff
});

DataSetup tasks can always run (regardless of whether it is a dry run) and Setup tasks can remain as they are.

**Comment by patriksvensson** [comment]
@jpdavid I'm taking a look at this one.

**Comment by patriksvensson** [comment]
@jpdavid I submitted a pull request. Setup and Teardown should be executed when running a dry run strategy. Setup and Teardown should never contain any code with side effects, and should be idempotent.
