### ISSUE TITLE
FEATURE REQUEST: Allow to install dotnetcore global tools like tool

### ISSUE THREAD

**Issue by farodin91** [cake-build/cake#2209]
I'm trying to use `sonnarscanner` as global tool.

Current steps to install: `build.sh`
```
dotnet tool install --global dotnet-sonarscanner
```
Expected: `build.cake`
```
#tool "dotnet-sonarscanner"
```
https://cakebuild.net/docs/tools/installing-tools

**Comment by mholo65** [comment]
Need to figure out how to know if a `nupkg` contains a .NET Core Global Tool or not. Hopefully it’s doable by only querying packaga metada (i.e. registration) from a NuGet V3 source. Will look in NuGet Gallery source for some clues...

**Comment by gep13** [comment]
@farodin91 I have just released the Cake.DotNetTool.Module, which will allow you to do what you have asked for.

The introduction blog post about this can be found here:

https://www.gep13.co.uk/blog/introducing-cake.dotnettool.module

For now, I am going to close this issue.  Please let us know if you have any questions about it.
