### ISSUE TITLE
Describe what Cake is actually able to do out-of-the-box

### ISSUE THREAD

**Issue by johan-boule** [cake-build/cake#2212]
I've looked around the documentation, but I haven't found any description about what Cake is really able to do out-of-the-box. For example, given some C/C++ source code, would Cake be a viable build tool, or would I have to re-implement the wheel, i.e. handle all the tool-chain details ?

**Comment by devlead** [comment]
@johan-boule Cake in general orchestrates existing tools/SDKs, so for C/C++ Cake would would use something like MSBuild / CMake. MSBuild is supported out of the box, and believe there's an addin for CMake.

Currently I would say Cake is mostly been focused on the .NET developer, so there's not any alias geared to working directly with the C/C++ compiler, although that could certainly be possible through i.e. a community addin.

**Comment by johan-boule** [comment]
Thank you. This answers my question.
