### ISSUE TITLE
Cake.CoreCLR can't handle whitespace in path

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#2214]
Steps to reproduce:
```powershell
C:\temp> mkdir "some path"
C:\temp> cd '.\some path\'
C:\temp\some path> nuget install Cake.CoreCLR -o tools
C:\temp\some path> echo 'Information("Hello World");' > build.cake
C:\temp\some path> dotnet .\tools\Cake.CoreCLR.0.29.0\Cake.dll
Error: Could not find a part of the path 'C:\temp\some path\path\tools\Cake.CoreCLR.0.29.0'.
```

Notice how the `path` is duplicated in the above path.

//cc @gep13

**Comment by mholo65** [comment]
Fun fact, if you have more than one whitespace in your path, you'll get another error message.

```powershell
C:\temp\some other path> dotnet .\tools\Cake.CoreCLR.0.29.0\Cake.dll
More than one build script specified.
For usage, use parameter --help
```

**Comment by mholo65** [comment]
I believe issue is this https://github.com/cake-build/cake/blob/a49462f9cd812a13255122220f9a4b954ea829b4/src/Cake/Polyfill/EnvironmentHelper.cs#L15

**Comment by jnm2** [comment]
Related to https://github.com/cake-build/cake/issues/1272.

**Comment by gep13** [comment]
@mholo65 did you have a plan for how this one can get fixed?
