### ISSUE TITLE
Enhancement: Add a ContinueFrom option to task running

### ISSUE THREAD

**Issue by wozzo** [cake-build/cake#2215]
In a chain of long running tasks on a dev machine if one fails and is repaired the ability to restart from a specific task while maintaining the original target would be pretty useful imho.

e.g. Task chain of a-> b -> c -> d -> e
c fails
run

```
.\build.ps1 -target e -continuefrom=c
```

which would then just run c, d, and e.

**Comment by wozzo** [comment]
What I've done in my fork will work, but it seems like a lot of logic around task choice going into the CakeEngine. What do you reckon to moving the task selection logic into the CakeGraph? This would make the code to get ordered tasks in the CakeEngine something like this I think.
Any other suggestions?

```
var graph = CakeGraphBuilder
    .Create(tasks)
    .SetTarget(settings.Target)
    .SetExclusiveMode(settings.Exclusive)
    .ContinueFrom(settings.ContinueFromTask)
    .Build();
var orderedTasks = graph.Traverse();
```

**Comment by augustoproiete** [comment]
Moving to GitHub discussions
