### ISSUE TITLE
Incorrect documentation for InnoSetup Alias

### ISSUE THREAD

**Issue by SIkebe** [cake-build/cake#2220]
https://github.com/cake-build/cake/blob/ba349daeec063946ecdef2076804b1c0a9e0a2f7/src/Cake.Common/Tools/InnoSetup/InnoSetupAliases.cs#L47-L49

There is no property named `OutputDir` on `InnoSetupSettings ` class.
That should be `OutputDirectory`.
```cs
InnoSetup("./src/Cake.iss", new InnoSetupSettings {
    OutputDirectory = outputDirectory
    });
```

**Comment by devlead** [comment]
Fixed by #2221
