### ISSUE TITLE
TLS 1.2 for dotnet-install.ps1

### ISSUE THREAD

**Issue by SharpeRAD** [cake-build/cake#2222]
Just an FYI that I started to receive this exception on our build server this morning:

```
 (New-Object System.Net.WebClient).DownloadFile($DotNetInstallerUr ...  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
The term 'C:\Tools\DotNet\dotnet-install.ps1' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

I had a hunch it was due to TLS changes on the download server and appended this line to the powershell script which solved the issue:

```
[System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12;
```

Could be worth adding it to the default script as its a quick fix. Keep up the awesome work 🍰 team.

**Comment by patriksvensson** [comment]
Issue moved to [cake-build/resources #59](https://github.com/cake-build/resources/issues/59) via [**ZenHub**](https://www.zenhub.com/)
