### ISSUE TITLE
CakeTaskExtensions are no longer accessible

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#2228]
### What You Are Seeing?

`CakeTaskExtensions` are no longer accessible.

### What is Expected?

`CakeTaskExtensions` to be accessible; as before upgrading.

### What version of Cake are you using?

0.29.0

### Are you running on a 32 or 64 bit system?

64-bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

TeamCity

### How Did You Get This To Happen? (Steps to Reproduce)

I recently updated from Cake 0.23.0 to 0.29.0 and hit the following breaking change:
[commit/105eb540d1958f11d7953000ace4377042f192a6#diff-f817cf6c892a63876e9847920aae68eaR8](https://github.com/cake-build/cake/commit/105eb540d1958f11d7953000ace4377042f192a6#diff-f817cf6c892a63876e9847920aae68eaR8)

The `CakeTaskExtensions` class accessibility was changed from `public` to `internal` and we have lots of builds scripts using it; for example using `AddCriteria` to disable a task in order to override its behaviour:

```c#
Tasks.First(x => x.Name == "Zip-DataStore")
    .AddCriteria(() => false);
```
I can hack around it but it's not pretty:
```c#
((CakeTask)Tasks.First(x => x.Name == "Zip-DataStore"))
    .Criterias.Add(new CakeTaskCriteria(_ => false, null));
```

**Comment by patriksvensson** [comment]
@gitfool This seems to have been overlooked. I'm OK with making the extensions public.
Would you mind submitting a pull request for this? 👍
