### ISSUE TITLE
Cake 0.29.0 hangs on restoring packages

### ISSUE THREAD

**Issue by GeertvanHorrik** [cake-build/cake#2230]
### What You Are Seeing?

I am expanding my existing build scripts, and everything is / was really working well. However, whenever I added a reference to the OctopusTools, the script no longer continues but hangs at "Running build script" (and taking a lot of CPU). When checking the .nuget folder, I see octopustools/4.39.2/ with a temp file named "osibrj3r.pfl", but it never gets extracted. I tried deleting the folder / rebooting, nothing so far.

### What is Expected?

Cake running as usual.

### What version of Cake are you using?

0.29.0

### Are you running on a 32 or 64 bit system?

64-bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

-

### How Did You Get This To Happen? (Steps to Reproduce)

Reference a pinned tool version to this package:

https://www.nuget.org/packages/OctopusTools/4.39.2

I tried https://www.nuget.org/packages/OctopusTools/4.39.1, that works fine.

### Output Log

-

**Comment by devlead** [comment]
This could be solved by #2227

Could you try the latest version on MyGet
https://www.myget.org/gallery/cake

**Comment by gep13** [comment]
@geertvanhorrik is the new package version signed? Are you working in an offline scenario? If so, there is a known “issue” with NuGet and how it does the package certificate verification.

**Comment by GeertvanHorrik** [comment]
@gep13 Yup, it's signed:

![image](https://user-images.githubusercontent.com/1246444/44156693-d02628dc-a0b0-11e8-97dc-0b0a7e3b9340.png)

**Comment by gep13** [comment]
Are you running in an offline scenario?

**Comment by GeertvanHorrik** [comment]
Nope.

**Comment by gep13** [comment]
Okay, so shouldn’t be the issue that I thought it was. Can you try @devlead suggestion?

**Comment by GeertvanHorrik** [comment]
Just checked out the commit, I am pretty sure that fixes it, thanks!
