### ISSUE TITLE
Add repository metadata to NuGet packages

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#2238]
Cake NuGet packages currently don't contain [repository metadata](https://docs.microsoft.com/en-us/nuget/reference/nuspec#repository).

It would be nice to have repository metadata in all Cake NuGet packages as nuget.org now makes use of them to show a link to the GitHub repository.

**Comment by gep13** [comment]
@pascalberger I was totally going to suggest this as well!  Great idea!

**Comment by gep13** [comment]
@pascalberger you in a position to take this?

**Comment by pascalberger** [comment]
@gep13 I want to finish some stuff in Cake.Issues first, but can have a look at it later

**Comment by gep13** [comment]
@pascalberger no immediate rush, just wanted to check to see if this is something that you would be in a position to look at, at some point.
