### ISSUE TITLE
Add NuGet projectUrl to nuspec/csproj packages

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#2246]
https://docs.microsoft.com/en-us/nuget/reference/nuspec#projecturl
https://docs.microsoft.com/en-us/nuget/reference/msbuild-targets#pack-target

**Comment by patriksvensson** [comment]
Isn't this in the `Shared.msbuild` file?

**Comment by gep13** [comment]
Based on the last PR for something similar, there are a few nuspec's:

https://github.com/cake-build/cake/pull/2240/files
