### ISSUE TITLE
Unhelpful error when #loading a missing nuget package

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#2249]
### What You Are Seeing?

```
Preparing to run build script...
Running build script...
C:/tmp/caketest/build.cake:1: One or more errors occurred.
Error: Errors occured while analyzing script.
```

### What is Expected?

A specific error message that tells the end user what is wrong. In this case, the fact that the NuGet package that build.cake is trying to #load doesn't exist (because the version number is no longer available).

We had this problem happen recently where our own internal Recipe package (maintained on a TeamCity build server) had incremented to newer versions and the version referenced from a project no longer existed in the NuGet feed. The developer was confused as to what they'd done wrong (nothing at all as it turns out - someone else had probably forgot to pin the version build), and the error message didn't give any clues.

### What version of Cake are you using?

0.3.0

### Are you running on a 32 or 64 bit system?

64

### What environment are you running on?  Windows? Linux? Mac?

Windows

### How Did You Get This To Happen? (Steps to Reproduce)

Create build.cake with the following content

```
#load nuget:?package=Cake.Recipe&version=0.1.0
```

Run standard build.ps1 bootstrapper

### Output Log

Preparing to run build script...
Running build script...
Module directory does not exist.
NuGet.config not found.
Analyzing build script...
Analyzing C:/tmp/caketest/build.cake...
Missing C:\Users\David\.nuget\packages\cake.recipe\0.1.0\cake.recipe.0.1.0.nupkg
  CACHE https://api.nuget.org/v3/registration3-gz-semver2/cake.recipe/index.json
Missing C:\Users\David\.nuget\packages\cake.recipe\0.1.0\cake.recipe.0.1.0.nupkg
C:/tmp/caketest/build.cake:1: One or more errors occurred.
Error: Cake.Core.CakeException: Errors occured while analyzing script.
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()

**Comment by AlbertoMonteiro** [comment]
When I add `&version=0.1.0` parameter is start to fail

**Comment by flcdrg** [comment]
@AlbertoMonteiro that's correct. If the version number doesn't actually exist (or it used to exist, but no longer does) on the relevant NuGet package feed, then that's the scenario that I'm describing.

**Comment by fseegraeber** [comment]
The "One or more errors occurred." message comes from an AggregateException here, where an async method is called syncronously and the underlying exception gets wrapped.

https://github.com/cake-build/cake/blob/80d8b3c50a001b55f73a8bf33e9a9468e5dd5a5c/src/Cake.NuGet/Install/NuGetPackageInstaller.cs#L128-L137

To actually provide the message from the exception thrown in the called async method, that call could be made with `.ConfigureAwait(false).GetAwaiter().GetResult();`

**Comment by flcdrg** [comment]
Sounds good.. Not sure if [AggregateException.Flatten()](https://docs.microsoft.com/en-us/dotnet/api/system.aggregateexception.flatten) could be useful here too.

**Comment by flcdrg** [comment]
Just tried @fseegraeber's suggestion, and it works a treat.. Here's the output with that change:

```
C:/dev/git/cake-version-test/build.cake:1: Unable to find version '1.2.3' of package 'Cake.Foo'.
Error: Errors occurred while analyzing script.
```
