### ISSUE TITLE
Show warning when referenced package is missing version number

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2255]
If a version number is missing for a package reference in a preprocessor directive, a warning should be displayed in the console output.

**Examples of package references that should emit warnings:**

```csharp
#addin nuget:?package=Foo
#tool nuget:?package=Bar
#module nuget:?package=Qux
```

**Comment by Marusyk** [comment]
I will prepare a PR. Could you please suggest what error message should be displayed?

"Missing version number for referenced package 'Foo'" ?

**Comment by devlead** [comment]
Not a native English speaker myself but we should probably provide a link to https://cakebuild.net/docs/tutorials/pinning-cake-version in the warning message. providing not just warning but a suggested solution similar to assembly verifier
https://github.com/cake-build/cake/blob/a0f142af2dfbf18eecc240789529da428cb0d82a/src/Cake.Core/Reflection/AssemblyVerifier.cs#L39-L47

**Comment by gep13** [comment]
I would go with something like:

```
"The '{0}' directive is attempting to install the '{1}' package \r\n" +
"without specifying a package version number.  \r\n" +
"More information on this can be found at \r\n" +
"https://cakebuild.net/docs/tutorials/pinning-cake-version" +
"It's not recommended, but you can explicitly override this warning \r\n" + 
"by configuring the Skip Package Version Check setting to true\r\n" + 
"(i.e. command line parameter \"--settings_skippackageversioncheck=true\", \r\n" + 
"environment variable \"CAKE_SETTINGS_SKIPPACKAGEVERSIONCHECH=true\", \r\n" + 
"read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)"; 
```

**Comment by gep13** [comment]
This would obviously require the addition of another Configuration Value into Cake to allow people to override this warning, as I know that there are some who "need" to always use the latest version, and will not want to see this warning.

**Comment by mholo65** [comment]
@jnm2, so basically a command for Cake that works like `dotnet-outdated`, could solve your problems?

**Comment by gep13** [comment]
> @jnm2 said...
but with pinning there's no warning to remind us when we're out of date. 

I would consider that a separate, valid issue.  Regardless of whether you are "ok" with not pinning a tool/addin/module, the recommendation from the Cake Team has always been, and will always be, to pin your versions.  That way, you get the most reliable, and repeatable build.  This new warning is an additional mechanism to make people aware of this recommendation.

**Comment by gep13** [comment]
> @jnm2 said...
If &prerelease does not suppress the warning, why would you ever use &prerelease rather than just pinning the prerelease version?

That is a valid question.

**Comment by jnm2** [comment]
@mholo65 Yes, exactly (and it is a separate issue than this one). But I want people to see it who aren't thinking about checking for upgrades, so I'd want it to be noticeable during any script execution.

**Comment by jnm2** [comment]
> I would consider that a separate, valid issue.

Yes, thanks! Moved to https://github.com/cake-build/cake/issues/2260 and https://github.com/cake-build/cake/issues/2261.
