### ISSUE TITLE
Add cake to homebrew

### ISSUE THREAD

**Issue by nitrocode** [cake-build/cake#2263]
Would love to run a `brew` command to install this app!

```
brew install cake-build
```

Created from a comment coming from [this thread](https://github.com/cake-build/cake/pull/772)

**Comment by gep13** [comment]
We already publish Cake to home brew:

https://github.com/Homebrew/homebrew-core/blob/master/Formula/cake.rb

😄

**Comment by devlead** [comment]
It's already on brew as formula `cake`

**Comment by gep13** [comment]
You can find more information here:

https://formulae.brew.sh/formula/cake

**Comment by gep13** [comment]
@nitrocode I am going to go ahead and close this, as I believe that this is covered.  Let us know if you have any follow up.
