### ISSUE TITLE
Allow to listen and modify redirected standard output of a process

### ISSUE THREAD

**Issue by AntonPetrov83** [cake-build/cake#2270]
Currently `ProcessAliases` do not allow to receive and modify (or filter) other process's outputs in real time while the process is running.

I am implementing wrappers for command line tools like SVN, xcodebuild and it would be great to have an opportunity to pipe outputs of tools or modify it for better build logs.

After a short Gitter discussion there is a suggestion to add following output handlers to `ProcessSettings`:

```
public Func<string, string> RedirectedStandardOutputHandler;
public Func<string, string> RedirectedStandardErrorHandler;
```

By @devlead:
> if one would want to filter out sensitive information i.e. one could retract that from the buffer and null if it should be totally omitted.

**Comment by devlead** [comment]
Referencing gitter discussion:
https://gitter.im/cake-build/cake?at=5b8e8400f5402f32aad7be6f
https://gitter.im/cake-build/cake?at=5b8e8fb34be56c5918de8b06
https://gitter.im/cake-build/cake?at=5b8faa6511b41f69dbc3039a
