### ISSUE TITLE
Allow to redirect standard input of a process

### ISSUE THREAD

**Issue by AntonPetrov83** [cake-build/cake#2271]
Suggested modifications:

```
public sealed class ProcessSettings
{
    ...
    public bool RedirectStandardInput { get; set; }
}
```

```
public interface IProcess
{
    ...
   System.IO.StreamWriter GetStandardInput();
}
```

Referencing gitter discussion:
https://gitter.im/cake-build/cake?at=5b8fc27c1d3a5711b6ea156f
https://gitter.im/cake-build/cake?at=5b8fc39ad8d36815e5dcfa1d

**Comment by augustoproiete** [comment]
Thanks @jnm2

Closing as duplicate of #1480
