### ISSUE TITLE
Update in-process NuGet client to support offline environments

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#2272]
NuGet.exe 4.8.1 supports possibility to [disable revocation check](https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu3028#revocation-check-mode) to avoid timeouts in revocation checks which takes approximately 4 minutes. Cakes in-proc NuGet client should also support environments in networks with access to internet blocked by a firewall.

**Comment by pascalberger** [comment]
In NuGet CLI verification behavior can be controlled by setting `NUGET_CERT_REVOCATION_MODE` environment variable to `offline`. Probably it would make sense that Cake checks the same environment variable?

**Comment by pascalberger** [comment]
Upstream NuGet fix was done with this PR: https://github.com/NuGet/Home/issues/7173

**Comment by pascalberger** [comment]
And released with https://github.com/NuGet/NuGet.Client/tree/4.8.1.5435

**Comment by pascalberger** [comment]
NuGet packages containing this fix are now available (4.9.1+1087884b300ec9f7d83a92b5b0957e4ec1d40e6b)

**Comment by mholo65** [comment]
@pascalberger https://github.com/aelij/NuGet.Client/pull/2
