### ISSUE TITLE
OpenCoverRunner always adds the -register switch

### ISSUE THREAD

**Issue by wozzo** [cake-build/cake#2276]
### What You Are Seeing?
When running the DotNetCore-Test task the following is seen after the tests run

```
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
```

### What is Expected?
Not this message, and that the xml is generated correctly

### What version of Cake are you using?
0.28.0

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
Run DotNetCore-Test task - definitely happening for cake build in https://github.com/wozzo/Cake.TeamCityCoverageReporter

### Output Log

~~~sh
========================================
DotNetCore-Test
========================================
Executing task: DotNetCore-Test
Executing: "D:/repos/cake.TeamCityCoverageReporter/tools/OpenCover.4.6.519/tools/OpenCover.Console.exe" -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test \"D:/repos/cake.TeamCityCoverageReporter/src/Cake.TeamCityCoverageReporter.Tests/Cake.TeamCityCoverageReporter.Tests.csproj\" --configuration Release --no-build" -filter:"+[*]* -[xunit.*]* -[Cake.Core]* -[Cake.Testing]* -[*.Tests]* -[Moq*]* -[AutoFixture*]* " -excludebyattribute:"*.ExcludeFromCodeCoverage*" -excludebyfile:"*/*Designer.cs;*/*.g.cs;*/*.g.i.cs" -oldStyle -register:user -returntargetcode:0 -output:"D:/repos/cake.TeamCityCoverageReporter/BuildArtifacts/TestCoverage/OpenCover.xml"
Executing: C:\Program Files\dotnet\dotnet.exe
Test run for D:\repos\cake.TeamCityCoverageReporter\src\Cake.TeamCityCoverageReporter.Tests\bin\Release\netcoreapp2.1\Cake.TeamCityCoverageReporter.Tests.dll(.NETCoreApp,Version=v2.1)
Microsoft (R) Test Execution Command Line Tool Version 15.8.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...

Total tests: 1. Passed: 1. Failed: 0. Skipped: 0.
Test Run Successful.
Test execution time: 3.1695 Seconds
Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.
~~~

**Comment by wozzo** [comment]
In the OpenCoverRunner class the following is always called

```
builder.AppendSwitch("-register", ":", settings.Register);
```
and the default value for settings.Register is "user".
According to https://github.com/OpenCover/opencover/issues/821 it should just use `-register` instead of `-register:user`

**Comment by patriksvensson** [comment]
By looking at the command line parsing in OpenCover, it looks like they default to `normal` (see https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Framework/CommandLineParser.cs#L112) even though the docs say it default to `user` (see https://github.com/OpenCover/opencover/blob/master/main/OpenCover.Framework/CommandLineParser.cs#L132).

This might be a breaking change and/or bug in open cover so I'm hesitant to change it unless we know for sure that omitting `user` doesn't affect users of Cake that uses an older version of OpenCover than `4.6.519` since this should be acceptable input according to the documentation.

**Comment by wozzo** [comment]
Agreed, and I've just tried using "Normal" but now I get a different error so doesn't look like that is the solution either
```
Failed to register(user:False,register:True,is64:False):5 the profiler assembly; you may want to look into permissions or using the -register:user option instead. C:\WINDOWS\system32\regsvr32.exe /s   "D:\repos\cake.teamcitycoveragereporter\tools\OpenCover.4.6.519\tools\x86\OpenCover.Profiler.dll"
If you are unable to resolve the issue please contact the OpenCover development team
see https://www.github.com/opencover/opencover/issues
An error occurred when executing task 'DotNetCore-Test'.
```

**Comment by devlead** [comment]
Using portable pdb:s?

**Comment by wozzo** [comment]
Not sure. Do you know how to check? Or make sure they are using cake.recipe?
________________________________

**Comment by devlead** [comment]
It's a setting in your csproj, example
https://github.com/cake-build/cake/blob/5e7716a04a0751ccf8e4cdf117a3120264ec6fc2/src/Shared.msbuild#L29

**Comment by wozzo** [comment]
Brilliant thanks. Didn't realise OpenCover didn't support portable pdb's. Have changed the setting in my csproj to pdbonly and it works like a charm. Cheers

**Comment by devlead** [comment]
@wozzo great that you got that sorted!

**Comment by devlead** [comment]
There's an issue to follow for OpenCover supporting .NET Core at OpenCover/opencover#595
