### ISSUE TITLE
Cake.Tool fails to install as dotnet tool under WSL

### ISSUE THREAD

**Issue by YakhontovYaroslav** [cake-build/cake#2282]
### What You Are Seeing?
Cake.Tool fails to install on WSL Ubuntu with error 
```
The settings file in the tool's NuGet package is invalid: Settings file 'DotnetToolSettings.xml' was not found in the package.
Tool 'cake.tool' failed to install. Please contact the tool author for assistance.
```
### What is Expected?
Successful installation.

### What version of Cake are you using?
Cake.Tool 0.30.0

### Are you running on a 32 or 64 bit system?
x64

### What environment are you running on?  Windows? Linux? Mac?
WSL Ubuntu 18.04, dotnet --info output:

```
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

### How Did You Get This To Happen? (Steps to Reproduce)
dotnet tool install -g Cake.Tool --version 0.30.0

###Proposed fix
Issue is fixed by manually repacking as NuGet package with id 'cake-tool'. Same fix applies for example for Octopus.DotNet.Cli package see this [issue](https://github.com/OctopusDeploy/OctopusClients/issues/155). Please consider renaming package as FAKE tool did [FAKE NuGet Package](https://www.nuget.org/packages/fake-cli/).

**Comment by devlead** [comment]
So I've tried the tool on
* Windows
* Mac
* WSL Ubuntu 16.04
* WSL openSuse Leap 42
* Docker 
  - microsoft/dotnet:2.1-sdk
  - ubuntu:18.04
  - ubuntu:16.04
  - fedora:28

All works, however I am able to repro your issue on WSL and Ubuntu 18.04.

Checking the package it does have the required xml manifest
![image](https://user-images.githubusercontent.com/1647294/45327994-1f343780-b55a-11e8-8ba9-73fe58d3832e.png)

and it does conform do what's documented
https://github.com/dotnet/cli/blob/master/Documentation/general/tool-nuget-package-format.md

IMHO feels more like an issue with the .NET Core CLI with WSL and Ubuntu 18 than the packaging, and an issue should be raised at https://github.com/dotnet/cli as it works on all but one specific platform.

**Comment by YakhontovYaroslav** [comment]
@devlead 
Thanks for quick reaction. I have references this (and Octopus) issue in dotnet/cli issue about tooling bug, but it is unclear when it will be fixed and for example how it will affect for example CentOS which we use as actual build environment.

**Comment by devlead** [comment]
Did a `docker run -it --rm centos:centos7 bash` and seems to work fine on CentOS for me
```bash
.NET Core SDK (reflecting any global.json):
 Version:   2.1.401
 Commit:    91b1c13032

Runtime Environment:
 OS Name:     centos
 OS Version:  7
 OS Platform: Linux
 RID:         centos.7-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.401/

Host (useful for support):
  Version: 2.1.3
  Commit:  124038c13e

.NET Core SDKs installed:
  2.1.401 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download


dotnet tool install -g Cake.Tool

You can invoke the tool using the following command: dotnet-cake
Tool 'cake.tool' (version '0.30.0') was successfully installed.
```

**Comment by devlead** [comment]
Might be worth raising an issue in https://github.com/Microsoft/wsl/issues too, as this issue so far only manifests itself under WSL. Therefor might be unrelated to the issue you commented on.

**Comment by devlead** [comment]
@YakhontovYaroslav I've raised an separate issue for this as I feel it's unrelated to nuget v2 feeds casing.
https://github.com/dotnet/cli/issues/9974

**Comment by YakhontovYaroslav** [comment]
@devlead Thanks for that, but I still believe it is casing issue as doing as repacking as “cake-tool” works. I will post details on repacking as soon as I reach my pc. I will also fire new isssue in WSL repo, as You suggested.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by gep13** [comment]
@YakhontovYaroslav we would be familiar with how to re-pack the NuGet package, so that wouldn't be an issue, the question is really why it works on 8 other systems, and only fails on this one.  That speaks to it being a bug in the dotnet cli, rather than a need for changing the name of the package.

**Comment by devlead** [comment]
We don't want forked packages on nuget until root cause is confirmed. I see this as a tooling bug and not package. You can't remove packages from nuget only unlist.

**Comment by YakhontovYaroslav** [comment]
@gep13 I understood that. Just wanted to add more info for someone (ex. dotnet cli members)    who might read this. Maybe I will write this into one of the issues in cli repo for it to be more noticeable.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by mholo65** [comment]
@YakhontovYaroslav, remember that repacking the tool also removes the package signatures. The one you get from NuGet is both a) repository signed by NuGet.org and b) package signed by .NET foundation.

We have seen issues in the past with package signing (and repo signing) and this might be equally related.

**Comment by YakhontovYaroslav** [comment]
Closing as it is fixed on recent SDKs
