### ISSUE TITLE
--version should only return sem/nuget version

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#2284]
![image](https://user-images.githubusercontent.com/1647294/45498356-22a60980-b77a-11e8-806c-b9c9bd916805.png)

**Comment by gep13** [comment]
@devlead I had actually thought about this as well.  The original PR to separate the `--version` and `--info` command simply took what was there, and split them.  I thought additional work would be required to make it work the way that it was intended.

**Comment by devlead** [comment]
@gep13 makes it a complex string to compare in bootstrappers though.  Submitted #2288 as a proposed solution.
