### ISSUE TITLE
NUnit: Incorrect xml report with multiple assemblies

### ISSUE THREAD

**Issue by matdube** [cake-build/cake#230]
When passing multiple assembiles to NUnit, the runner is called once per assembly.  This means the xml report is overwritten and doesn't contain the results of all the test assemblies.

Here's an example taken from my project's build script : 
```
Task("NUnitTests")
    .IsDependentOn("Build")
    .Does(() =>
{
    NUnit(GetFiles("./**/bin/debug/*.Tests.dll"), new NUnitSettings {
            ToolPath = "./packages/NUnit.Runners/tools/nunit-console.exe"
            ResultsFile = "NUnit-Results.xml"
        });
});
```
NUnit-Results.xml only has the results of the last assembly found.

**Comment by patriksvensson** [comment]
Fixed in #231.
