### ISSUE TITLE
RFC-0001: Rewrite Cake CLI

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2333]
As described in [RFC-0001](https://github.com/cake-build/rfcs/blob/master/text/0001-client-rewrite.md).

**Comment by adamhathcock** [comment]
I was coming back in to look at something like this.  I think this is a good idea.  I just want it to still play nice with the dotnet global tool installation as well!

**Comment by patriksvensson** [comment]
@adamhathcock The goal is that we should be 100% backwards compatible after this change, but have some more fine grained commands (and a cleaner architecture and code base in the Cake CLI).

Is there anything in particular that you're thinking about? All feedback is very appreciated here 😄

**Comment by adamhathcock** [comment]
The usage of `--target=something` isn't discoverable and I was wanting to change that.  I'm glad you already on top it

**Comment by patriksvensson** [comment]
Ah, you mean adding target as a first class citizen of the CLI?

**Comment by adamhathcock** [comment]
I just realized the mistake in my thinking. `target` is just a suggested argument to the script.  I guess understanding that was my fault but I wasn't sure there was a better way to present that in the CLI help

**Comment by gep13** [comment]
>@patriksvensson said...
as a first class citizen of the CLI?

Actually, I hadn't realised that it wasn't.  Yes, I would say that it should be.  Is there a reason that it isn't?

**Comment by gep13** [comment]
Since `--exclusive` is there, and it requires a named target to be exclusive on, I would say that `--target` should be there as well.

**Comment by adamhathcock** [comment]
maybe there should be `--task` to specify a task directly instead of having to manually have an argument for the Default task?  I guess that's a separate issue and change.

**Comment by patriksvensson** [comment]
> @gep13  said...
> Actually, I hadn't realised that it wasn't. Yes, I would say that it should be. Is there a reason that it isn't?

Well, right now we require the user to get the target from the provided arguments and pass it to `RunTarget`. I think this only makes sense if we remove RunTarget and does this implicitly for the user, but that is a completely different issue (and probably a RFC).

**Comment by devlead** [comment]
> I think this only makes sense if we remove RunTarget and does this implicitly for the user, but that is a completely different issue (and probably a RFC).

If doing that we should have a --no-target option too, to opt out of task implicit RunTarget. And target should almost be an configuration so it/default can be supplied via environment/argument/config without needing to parse script first.

**Comment by SUMUKHA-PK** [comment]
Hello all, I found this as an interesting exercise to do in my freetime (and I have loads of it currently), although I'd be needing help in familiarising myself with the codebase. Please do provide me some pointers to start myself with. 
Thanks.

**Comment by patriksvensson** [comment]
@SUMUKHA-PK I'm already working on a PR for this here: https://github.com/cake-build/cake/pull/2334

**Comment by SUMUKHA-PK** [comment]
Thanks for letting me know @patriksvensson
