### ISSUE TITLE
Add support for JUnit Output Format

### ISSUE THREAD

**Issue by bqstony** [cake-build/cake#2341]
### What You Are Seeing?
XUnit2Settings is missing setting for output results to JUnit XML file

### What is Expected?
Setting Property like `JUnitReport`

The xUnit Console Runner v2.4.0 has the following argument
Result formats: (optional, choose one or more)
  -junit <filename>      : output results to JUnit XML file

**Comment by ricfre** [comment]
I'm missing this as well

**Comment by gep13** [comment]
@bqstony @ricfre are either of you in a position to submit a PR to get this functionality added?

In the meantime, it is possible to customise the arguments that are used by the `XUnit2Settings` class.  See here:

https://github.com/cake-contrib/Cake.Recipe/blob/eed2a052755dbd47e777796b0d7f13276cb5542c/Cake.Recipe/Content/nuget.cake#L30-L34

For an example of how this is done for the `DotNetCorePackSettings` class.  The approach would be similar for what you are trying to do here.

**Comment by bqstony** [comment]
@gep13 thx for response.

When i find time the next days i will try to create a pr.

**Comment by devlead** [comment]
fixed by #2359
