### ISSUE TITLE
Allow NuGetRestoreSettings to opt out of setting -NonInteractive

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#2345]
### What You Are Seeing?
`NuGetRestoreSettings` always sets `-NonInteractive`

### What is Expected?
Under certain circumstances, I'd like nuget to not run run with the `-NonInteractive` parameter - for example when NuGet is run in combination with the Azure Artifacts CredentialProvider.VSS.exe. In that case, when used at an interactive command prompt, I'd want the credential provider to prompt the user for credentials. Currently NuGet passes through the `-NonInteractive` parameter to CredentialProvider.VSS.exe and so it just fails (rather than prompting the user).

(In my case, I would check `System.Environment.UserInteractive` to determine whether `-NonInteractive` should be set or not)

### What version of Cake are you using?
0.30

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows
### Are you running on a CI Server?  If so, which one?
TeamCity and Azure Pipelines

### How Did You Get This To Happen? (Steps to Reproduce)

1. Use Azure Artifacts NuGet feed
2. Copy CredentialProvider.VSS.exe and put it in tools directory (alongside Cake's NuGet.exe)
3. Use NuGetRestore("myproject.sln") in Cake script
4. Note that script fails to create authentication token and no user prompt is shown.

**Comment by devlead** [comment]
Fixed by #2451
