### ISSUE TITLE
urgent : nugetpack with cake not working ubuntu

### ISSUE THREAD

**Issue by eleite77** [cake-build/cake#2347]
### What You Are Seeing?

```
.NET Core SDK v2.1.4 is already installed locally (wanted v2.1.4).
Cake.CoreClr (0.30.0) is already installed.
Executing script (dotnet)...
========================================
Pack
========================================
Packaging pack Release
An error occurred when executing task 'Pack'.
Error: One or more errors occurred. (NuGet: Process returned an error (exit code 8).)
        NuGet: Process returned an error (exit code 8).
```

### What is Expected?

NuGetPack is supposed to create a package

### What version of Cake are you using?

0.30

### Are you running on a 32 or 64 bit system?

64

### What environment are you running on?  Windows? Linux? Mac?

Ubuntu 18.04

### Are you running on a CI Server?  If so, which one?

gocd

### How Did You Get This To Happen? (Steps to Reproduce)

I am using cakeup bootstrapper 

### Output Log

```
[go] Task: /bin/bash -c "chmod +x build.sh && ./build.sh"took: 2m 9.957sexited: 1
Downloading cakeup...
Downloading NuGet...
Downloading https://dot.net/v1/dotnet-install.sh...
Installing .NET Core SDK v2.1.4...
Verifying installation...
Dotnet SDK v2.1.4 has been installed.
Installed Cake.CoreClr (0.30.0).
Executing script (dotnet)...

========================================
Pack
========================================

Packaging pack Release
An error occurred when executing task 'Pack'.
Error: One or more errors occurred. (NuGet: Process returned an error (exit code 8).)
	NuGet: Process returned an error (exit code 8).
[go] Task status: failed, took: 2m 9.957s, exited: 1
[go] Current job status: failed
[go] Start to create properties gocd/111/Release/1/Release on a0b6c614a9d6 [/go]
[go] Start to upload gocd/111/Release/1/Release on a0b6c614a9d6 [/go]
[go] Job completed gocd/111/Release/1/Release on a0b6c614a9d6 [/go]
```

**Comment by eleite77** [comment]
sorry my message was deleted..

here is the output
i am using cakeUp & NugetPack with a nuspec file


[go] Task: /bin/bash -c "chmod +x build.sh && ./build.sh"took: 2m 9.957sexited: 1
Downloading cakeup...
Downloading NuGet...
Downloading https://dot.net/v1/dotnet-install.sh...
Installing .NET Core SDK v2.1.4...
Verifying installation...
Dotnet SDK v2.1.4 has been installed.
Installed Cake.CoreClr (0.30.0).
Executing script (dotnet)...

========================================
Pack
========================================
Packaging pack Release
An error occurred when executing task 'Pack'.
Error: One or more errors occurred. (NuGet: Process returned an error (exit code 8).)
	NuGet: Process returned an error (exit code 8).
[go] Task status: failed, took: 2m 9.957s, exited: 1
[go] Current job status: failed
[go] Start to create properties gocd/111/Release/1/Release on a0b6c614a9d6 [/go]
[go] Start to upload gocd/111/Release/1/Release on a0b6c614a9d6 [/go]
[go] Job completed gocd/111/Release/1/Release on a0b6c614a9d6 [/go]

**Comment by gep13** [comment]
Are you able to share the Cake script that is causing this issue?

**Comment by eleite77** [comment]
I put a try/catch.
Here is what i got 

Cake.Core.CakeException: NuGet: Process returned an error (exit code 8).
   at Cake.Core.Tooling.Tool`1.ProcessExitCode(Int32 exitCode) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 139
   at Cake.Core.Tooling.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, ProcessSettings processSettings, Action`1 postAction) in C:\projects\cake\src\Cake.Core\Tooling\Tool.cs:line 119
   at Cake.Common.Tools.NuGet.Pack.NuGetPacker.Pack(NuGetPackSettings settings, Func`1 process) in C:\projects\cake\src\Cake.Common\Tools\NuGet\Pack\NuGetPacker.cs:line 123
   at Submission#0.NuGetPack(FilePath filePath, NuGetPackSettings settings)
   at Submission#0.<<Initialize>>b__0_0()

**Comment by devlead** [comment]
What does `mono nuget.exe` give you? Which version of nuget.exe are you running?

4.4.2 is the minimal supported version of Mono for Cake atm.


Depending on what version of nuget.exe your using their requirements might be higher.

**Comment by eleite77** [comment]
@devlead thanks for your reply
I am using cakeup bootstrap script and i used the script found in github to install nuget because it was not included in
here is the script
# Download NuGet if it does not exist.
nuget_exe=$tools_dir/nuget.exe
nuget_cfg=$tools_dir/nuget.config
nuget_url=https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
if [ ! -f "$nuget_exe" ]; then
    echo "Downloading NuGet..."
    curl -Lsfo "$nuget_exe" $nuget_url
	chmod +x $nuget_exe
    if [ $? -ne 0 ]; then
        echo "An error occurred while downloading nuget.exe."
        exit 1
    fi
fi
when i do inside the build.sh script a **exec mono $nuget_exe**  i have : 
Unhandled Exception:
System.MissingMethodException: Method 'Array.Empty' not found.
  at NuGet.Common.ExceptionUtilities.DisplayMessage (System.Exception exception, Boolean indent) <0x40b5dad0 + 0x000af> in <filename unknown>:0 
  at NuGet.Common.ExceptionUtilities.DisplayMessage (System.Exception exception) <0x40b5daa0 + 0x00013> in <filename unknown>:0 
  at NuGet.Common.ExceptionUtilities.LogException (System.Exception ex, ILogger logger, Boolean logStackAsError) <0x40b5d790 + 0x00133> in <filename unknown>:0 
  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) <0x40b34860 + 0x008db> in <filename unknown>:0 
  at NuGet.CommandLine.Program.Main (System.String[] args) <0x40b30d50 + 0x00037> in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Array.Empty' not found.
  at NuGet.Common.ExceptionUtilities.DisplayMessage (System.Exception exception, Boolean indent) <0x40b5dad0 + 0x000af> in <filename unknown>:0 
  at NuGet.Common.ExceptionUtilities.DisplayMessage (System.Exception exception) <0x40b5daa0 + 0x00013> in <filename unknown>:0 
  at NuGet.Common.ExceptionUtilities.LogException (System.Exception ex, ILogger logger, Boolean logStackAsError) <0x40b5d790 + 0x00133> in <filename unknown>:0 
  at NuGet.CommandLine.Program.MainCore (System.String workingDirectory, System.String[] args) <0x40b34860 + 0x008db> in <filename unknown>:0 
  at NuGet.CommandLine.Program.Main (System.String[] args) <0x40b30d50 + 0x00037> in <filename unknown>:0

**Comment by devlead** [comment]
@eleite77 `System.MissingMethodException: Method 'Array.Empty' not found.` indicates you're using a too old version of Mono.

You can get a newer version of mono from 
https://www.mono-project.com/download/stable/#download-lin-ubuntu

**Comment by eleite77** [comment]
@devlead  many thanks.
I tried many times to install it but i have a lot of exceptions when trying to install the latest one.
where can i find what cake version is compatible with the version of mono i have 4.2.1 ?

**Comment by devlead** [comment]
There should be several versions avail as snapshots i.e.
"deb http://download.mono-project.com/repo/debian wheezy/snapshots/5.4.1 main" will give you 5.4.1 for Debian
Example ubuntu:16.04 [dockerfile](https://github.com/devlead/bitrise-dotnet/blob/master/Dockerfile)

Don't use Ubuntu 18.04 myself yet, but it's snapshots should be under
http://download.mono-project.com/repo/debian/dists/bionic/snapshots/

Which should translate to something like 
"deb http://download.mono-project.com/repo/debian bionic/snapshots/5.16 main"

If your still having issues it might make sense to raise an issue at https://github.com/mono/mono/issues

**Comment by eleite77** [comment]
i tried to install it on an azure ubuntu 16.04 server it is the same issue with docker container
i can't have it working.

root@c210fec74e07:/# sudo apt install mono-complete
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mono-devel : Depends: libc6 (>= 2.27) but 2.23-0ubuntu10 is to be installed or
                       libc6.1 (>= 2.27) but it is not installable or
                       libc0.1 (>= 2.27) but it is not installable
              Depends: libglib2.0-0 (>= 2.56.1) but 2.48.2-0ubuntu4.1 is to be installed
              Depends: mono-mcs (= 5.16.0.179-0xamarin1+ubuntu1804b1) but 4.2.1.102+dfsg2-7ubuntu4 is to be installed
              Depends: mono-roslyn (= 5.16.0.179-0xamarin1+ubuntu1804b1) but it is not going to be installed
              Depends: mono-gac (= 5.16.0.179-0xamarin1+ubuntu1804b1) but 4.2.1.102+dfsg2-7ubuntu4 is to be installed
              Depends: mono-xbuild (= 5.16.0.179-0xamarin1+ubuntu1804b1) but 4.2.1.102+dfsg2-7ubuntu4 is to be installed
              Depends: libmono-cil-dev (= 5.16.0.179-0xamarin1+ubuntu1804b1) but it is not going to be installed
              Depends: libmono-2.0-dev (>= 5.16.0.179-0xamarin1+ubuntu1804b1) but 4.2.1.102+dfsg2-7ubuntu4 is to be installed
              Recommends: referenceassemblies-pcl but it is not going to be installed
              Recommends: msbuild but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by devlead** [comment]
Bionic isn't for 16.04, Xenial is for Ubuntu 16.04.
