### ISSUE TITLE
Use new license format in published nupkg’s

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#2358]
See specs here:
https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg-(Technical-Spec)#license-expression-pack

**Comment by devlead** [comment]
Says `Status: Reviewing` is it supported in the tooling now?

**Comment by mholo65** [comment]
@devlead, it’s in VS 15.9 https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes

**Comment by devlead** [comment]
I'll address this is in a PR, if you don't fix it you'll get an build warning 
```diff
- error NU5125: The 'licenseUrl' element will be deprecated. Consider using the 'license' element instead.
```
