### ISSUE TITLE
Add Support for New snupkg Symbol Packages

### ISSUE THREAD

**Issue by RehanSaeed** [cake-build/cake#2362]
NuGet [added support](https://blog.nuget.org/20181116/Improved-debugging-experience-with-the-NuGet-org-symbol-server-and-snupkg.html) for the new snupkg symbol package format. There is a new parameter for the `dotnet`, `nuget` and `msbuild` CLI tools:

```
using dotnet
> dotnet pack MyAwesomeLib.csproj --include-symbols -p:SymbolPackageFormat=snupkg

using nuget
> nuget pack MyAwesomeLib.nuspec -Symbols -SymbolPackageFormat snupkg

using msbuild
> msbuild /t:pack MyAwesomeLib.csproj /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg
```

**Comment by devlead** [comment]
@RehanSaeed we've just updated Cake itself to use SDK 2.1.500, MSBuild 15.9 and NuGet 4.9.0 (still RC), so infrastructure should be in place to support it. 

Are you're willing to take a stab at a PR adding this?

Meanwhile people can already today do this woth a workaround using [ArgumentCustomization](https://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8) on [DotNetCorePackSettings](https://cakebuild.net/api/Cake.Common.Tools.DotNetCore.Pack/DotNetCorePackSettings/), [MSBuildSettings](https://cakebuild.net/api/Cake.Common.Tools.MSBuild/MSBuildSettings/) and [NuGetPackSettings](https://cakebuild.net/api/Cake.Common.Tools.NuGet.Pack/NuGetPackSettings/).
