### ISSUE TITLE
Change PathHelper to be publicly accessible

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#2377]
If not the whole class then at least the `Combine` methods should be publicly accessible.

This would be useful when combining a user configured directory with globbing patterns such that path separators are cleaned up and ensured. e.g.

```c#
packagesPattern1 = "/**/*.nupkg";
packages = GetFiles(Build.Directories.ArtifactsNuGet + packagesPattern1); // ok
packagesPattern2 = "**/*.nupkg";
packages = GetFiles(Build.Directories.ArtifactsNuGet + packagesPattern2); // fails
```
... could be cleanly and safely handled using:
```c#
packagesPattern1 = "/**/*.nupkg";
packages = GetFiles(PathHelper.Combine(Build.Directories.ArtifactsNuGet.FullPath, packagesPattern1));
packagesPattern2 = "**/*.nupkg";
packages = GetFiles(PathHelper.Combine(Build.Directories.ArtifactsNuGet.FullPath, packagesPattern2));
```
... or another alternative might be to keep `PathHelper` internal but provide a Cake alias named something like `CombinePath` and that calls `PathHelper.Combine`:
```c#
packagesPattern1 = "/**/*.nupkg";
packages = GetFiles(CombinePath(Build.Directories.ArtifactsNuGet.FullPath, packagesPattern1));
packagesPattern2 = "**/*.nupkg";
packages = GetFiles(CombinePath(Build.Directories.ArtifactsNuGet.FullPath, packagesPattern2));
```

... or maybe it's as simple as another method on `DirectoryPath`:
```c#
public string CombineWithPattern(string pattern)
{
    if (pattern == null)
    {
        throw new ArgumentNullException(nameof(pattern));
    }

    return PathHelper.Combine(FullPath, pattern);
}

packagesPattern1 = "/**/*.nupkg";
packages = GetFiles(Build.Directories.ArtifactsNuGet.CombineWithPattern(packagesPattern1));
packagesPattern2 = "**/*.nupkg";
packages = GetFiles(Build.Directories.ArtifactsNuGet.CombineWithPattern(packagesPattern2));
```

Thoughts? Happy to submit a PR.

**Comment by patriksvensson** [comment]
@gitfool PathHelper is a new, internal utility that hasn't been released yet. 

In 0.31 you will be able to do `Build.Directories.ArtifactsNuGet.CombineWithFilePath("/**/*.nupkg").FullPath` since we no longer do validation of paths and leave that part to the operating system.

I would prefer if we kept `PathHelper` internal for now and instead use `FilePath` and `DirectoryPath` for path manipulation.

**Comment by gitfool** [comment]
@patriksvensson Awesome! Keeping `PathHelper` internal is fine with me if combining `DirectoryPath`, `FilePath` and globbing patterns works as expected without throwing a validation exception. Specifically, leading and trailing [back]slashes, whether provided or not, should be normalized to a single [back]slash separator.

So the following should all be equivalent with the resulting `FilePath.FullPath` == `./**/*.nupkg`:
```c#
DirectoryPath dir1 = ".";
dir1.CombineWithFilePath("**/*.nupkg");
dir1.CombineWithFilePath("/**/*.nupkg");

DirectoryPath dir2 = "./";
dir2.CombineWithFilePath("**/*.nupkg");
dir2.CombineWithFilePath("/**/*.nupkg");
```
(This should also apply whether or not the directories were absolute and rooted.)

**Comment by gitfool** [comment]
@patriksvensson For the record, I tested the above with Cake 0.31.0 and the following were all equivalent with the resulting `FilePath.FullPath == **/*.nupkg` (with no leading `./`):

```c#
DirectoryPath dir1 = ".";
dir1.CombineWithFilePath("**/*.nupkg");
dir1.CombineWithFilePath("./**/*.nupkg");
//dir1.CombineWithFilePath("/**/*.nupkg");

DirectoryPath dir2 = "./";
dir2.CombineWithFilePath("**/*.nupkg");
dir1.CombineWithFilePath("./**/*.nupkg");
//dir1.CombineWithFilePath("/**/*.nupkg");
```
... and the last two in each set instead threw an exception `System.InvalidOperationException: Cannot combine a directory path with an absolute file path`. Not quite what I was expecting but makes sense and catches input errors immediately, so good enough!
