### ISSUE TITLE
Allow support for the InternalsVisibleTo attribute.

### ISSUE THREAD

**Issue by cgourlay** [cake-build/cake#240]
Can the AssemblyInfoCreator support the InternalsVisibleTo attribute? This is something I need to allow internals to be testable.

I am happy to make a pull request for this - is it right to assume that the change(s) are made in the Cake.Common.Solution.Project.Properties namespace?

**Comment by patriksvensson** [comment]
Hello @cgourlay,

You're more than welcome to give it a try :smile: 

I would suggest adding a `ICollection<string>` to `AssemblyInfoSettings.cs` so you can provide multiple assemblies to be ignored.

**Comment by cgourlay** [comment]
Thanks for the suggestion @patriksvensson - I'll look at this today.

**Comment by cgourlay** [comment]
Hi @patriksvensson 

I've an initial implementation in my own fork here: b2486ff874d0177180a3d2e652b5ebe3a9dbdf46

I've looked at the sample 'build.cake' file and I'm not really following why there is a need to ignore multiple assemblies. Would you be able to expand on what you are looking for?

**Comment by devlead** [comment]
Well you can expose your internals to multiple assemblies:
```csharp
[assembly:InternalsVisibleTo("Friend1a")]
[assembly:InternalsVisibleTo("Friend1b")]
```
https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.internalsvisibletoattribute(v=vs.110).aspx

**Comment by cgourlay** [comment]
Of course! I've latched on to the suggestion of assemblies being ignored. 

Are we saying that it's enough to alter my implementation to handle an `ICollection<string>` of assembly names?

**Comment by devlead** [comment]
Correct, `ICollection` is great as many inherit from it I.e. List, Array etc.

**Comment by cgourlay** [comment]
Nice one! Thanks for clarifying. I'll get this sorted in a moment and submit a pull request.

**Comment by cgourlay** [comment]
Mmmm. The `AssemblyInfoRegistration.cs` is using a Dictionary and preventing multiple entries from being added and I can see why this is desired behaviour for all the other attributes.

`private void Add(string name, string @namespace, string value)
        {
            if (Attributes.ContainsKey(name))
            {
                Attributes[name] = value;
            } ...`

Not being overly familiar with the codebase I'd welcome views on how best to proceed - rather than just jump in.

**Comment by patriksvensson** [comment]
Hello @cgourlay,

Maybe something like:

```csharp
using (var stream = _fileSystem.GetFile(absoluteOutputPath).OpenWrite())
using (var writer = new StreamWriter(stream, System.Text.Encoding.UTF8))
{
    // Write header.
    writer.WriteLine("//------------------------------------------------------------------------------");
    writer.WriteLine("// <auto-generated>");
    writer.WriteLine("//     This code was generated by Cake.");
    writer.WriteLine("// </auto-generated>");
    writer.WriteLine("//------------------------------------------------------------------------------");

    if (registration.Attributes.Count > 0)
    {
        // Write namespaces.
        var namespaces = registration.Namespaces.Select(n => string.Concat("using ", n, ";"));
        if(settings.InternalsVisibleTo.Count > 0)
        {
            // Add namespace for InternalsVisibleTo to the set.
            registration.Namespaces.Add("System.Runtime.CompilerServices");
        }
        foreach (var @namespace in namespaces)
        {
            writer.WriteLine(@namespace);
        }

        writer.WriteLine();

        // Write attributes.
        foreach (var attribute in registration.Attributes)
        {
            writer.WriteLine(string.Concat("[assembly: ", attribute.Key, "(", attribute.Value, ")]"));
        }

        // Write the internals visible to attributes.
        if(settings.InternalsVisibleTo.Count > 0)
        {
            writer.WriteLine();

            // Write attributes.
            foreach (var attribute in settings.InternalsVisibleTo)
            {
                writer.WriteLine(string.Concat("[assembly: InternalsVisibleTo(", attribute, ")]"));
            }
        }        
    }
}
```

I wrote this in Notepad so I have no idea if it compiles :smile:
It doesn't have to be efficient as long as there are tests so it's easy to refactor later on.

**Comment by cgourlay** [comment]
Hi @patriksvensson 

It was the modification to the implementation of 'GetRegistrations(settings);' that I was looking for a view on. As far as I can tell, the use of a `Dictionary` is preventing multiple InternalsVisibleTo attributes being added. I can change this to use a different collection type to allow duplicate InternalsVisibleTo but this will also allow, say, duplicate `CLSCompliant` entries.

Would it help if I committed a change for your review?

**Comment by patriksvensson** [comment]
Hi @cgourlay,

Sure! Submit a pull request with `WIP: ` in the title (so it doesn't get accidentally merged) and we'll continue the discussion there.

**Comment by cgourlay** [comment]
Nice one - I will do that later today. Thanks for all your help @patriksvensson

**Comment by devlead** [comment]
#265 fixed this.
