### ISSUE TITLE
Add support for MSBuild options to enable RestoreLockedMode

### ISSUE THREAD

**Issue by SIkebe** [cake-build/cake#2415]
Recently NuGet introduced `packages.lock.json` to enable repeatable package restore and added options to enable locked mode.
https://blog.nuget.org/20181217/Enable-repeatable-package-restores-using-a-lock-file.html
```
dotnet.exe restore --locked-mode
msbuild.exe /t:restore /p:RestoreLockedMode=true
```
It'd be great if Cake support those options natively.

**Comment by devlead** [comment]
@SIkebe agreed, marking as ip for grabs 👍 
Sidenote, remarks on property should be documented minimal supported MSBuild / .NET CLI version.

* Visual Studio 2017 version 15.9 and above.
* .NET SDK version 2.1.500 and above.

**Comment by devlead** [comment]
@fseegraeber sure go ahead, I'll remove up-for-grabs / help wanted tags.
