### ISSUE TITLE
Chocolatey pack regression in Cake 0.32.0

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#2426]
2caa01812ec232efc0758b3589ecd8c16d04e413 introduced a bug with Chocolatey pack, null checks need to be converted to Any()

**Comment by patriksvensson** [comment]
@devlead We should probably add tests to other tools as well that this PR touched to make sure we didn't break any of them as well.

**Comment by devlead** [comment]
@patriksvensson yip

**Comment by jnm2** [comment]
Oops, I'm sorry! 😞
