### ISSUE TITLE
UploadFile should support option of username/password

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#2431]
### What You Are Seeing?

UploadFile() doesn't allow you to provide credentials

### What is Expected?

Have settings (like DownloadFile() has `DownloadFileSettings`) so that credentials can be supplied

### What version of Cake are you using?
0.31.0

### Are you running on a 32 or 64 bit system?
64

### What environment are you running on?  Windows? Linux? Mac?
Windows

**Comment by franciscomoloureiro** [comment]
Hello, I had a look and I think I can take this one.
Thanks
