### ISSUE TITLE
Windows Glob with Predicate is not working

### ISSUE THREAD

**Issue by maldworth** [cake-build/cake#2434]
Windows Glob with Predicate is not working (I was targeting 0.32.1, on Appveyor VS 2017 image)

I verified it's not working by creating a unit test.

Go to [this file](https://github.com/cake-build/cake/blob/develop/src/Cake.Core.Tests/Unit/IO/Globbing/WindowsGlobberTests.cs):

Add this test at the bottom:

```csharp
[WindowsFact]
public void Should_Return_Windows_Predicate_File()
{
	// Given
	var fixture = GlobberFixture.Windows();

	// When
	var result = fixture.Match("C:/Working/**/*.dll", file => file.Path.FullPath.EndsWith("A.Test.dll"));

	// Then
	Assert.Single(result);
	AssertEx.ContainsFilePath(result, "C:/Working/Project.A.Test.dll");
}
```

**Comment by kcamp** [comment]
@maldworth If it helps, this is behaving as designed/implemented.  The predicate is only used to include/exclude directory paths from being traversed.  See [GlobVisitorContext.cs, line 72](https://github.com/cake-build/cake/blob/49a7c51d9f3088a1d6f8b3c6502d0a5dc63f12b3/src/Cake.Core/IO/Globbing/GlobVisitorContext.cs#L72)

The use of `IFileSystemInfo` in the fixture might be a bit misleading.  In your test, the `GlobberFixture` is setting up a working directory of `C:\Working`, so the initial call to your predicate returns `false`, excluding further directory/file path traversal.

I have an open issue/PR to extend this behavior in include the ability to provide a predicate in the globbing traversal - GH-1384.

The best solution for your issue as currently implemented is apt to be a combination of the glob pattern and a `Where` predicate.
```cs
fixture.Match("C:/Working/**/*.dll").Where(x => x.FullPath.EndsWith("A.Test.dll"))
```

**Comment by maldworth** [comment]
Okay, makes sense, I'll use your suggestion. Thank you. Closing this issue
