### ISSUE TITLE
Erroneous "Target path must be an absolute path" when preserveFolderStructure is used with CopyFiles

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#2443]
Tested with 0.30.0 and 0.32.0. Entire repro:

##### build.cake

```cs
CopyFiles(
    new[]
    {
        new FilePath("CommonPath/File1.txt"),
        new FilePath("CommonPath/File2.txt")
    },
    "Destination", // Even though this should work, try `MakeAbsolute(Directory("Destination"))`
                   // for full effect
    preserveFolderStructure: true);
```

(Make sure the paths actually exist, or Cake will stop before the repro.)

##### Console

```
> .\build.ps1
Error: One or more errors occurred.
        Target path must be an absolute path.
```

If I attach Visual Studio, the debugger highlights this line: https://github.com/cake-build/cake/blob/f551284cf90694f40affe1ae51eba89d25981552/src/Cake.Core/IO/RelativePathResolver.cs#L24

The `from` and `to` arguments are both `Common`.

**Comment by jnm2** [comment]
Ah, the message is misleading. the workaround is to manually calculate the absolute paths of all the input files. This is something I would expect Cake to take care of.

```cs
CopyFiles(
    new[]
    {
        MakeAbsolute(new FilePath("CommonPath/File1.txt")),
        MakeAbsolute(new FilePath("CommonPath/File2.txt"))
    },
    "Destination",
    preserveFolderStructure: true);
```

**Comment by coder2213** [comment]
I debugged this a bit and found that there are issues only with copying more than 1 file.
Single file copy works fine.

Interesting observation is copying files from two different folders, gives below error:
An error occurred when executing task 'Copy'.

Console
```
> .\build.ps1
Error: One or more errors occurred. (The path is empty. (Parameter 'path'))
        The path is empty. (Parameter 'path')
```
Build.cake file
```
CopyFiles(
    new[]
    {
        new FilePath("CommonPath/File1.txt"),
        new FilePath("source/file10.txt")
    },
    "Destination", // Even though this should work, try `MakeAbsolute(Directory("Destination"))`
                   // for full effect
    preserveFolderStructure: true);
```

Is the above mentioned use case correct?

What is the importance of preserveFolderStructure? I am confused on the code written in that condition which is actually trying to find a commonpath for files that are being copied.

**Comment by ToMee99** [comment]
Hi, I would like to contribute on this project. Is this issue still available?
