### ISSUE TITLE
Add OnError<TData>

### ISSUE THREAD

**Issue by NooNameR** [cake-build/cake#2445]
Would be nice to see `OnError<TData>` as well
And consider to have `OnError(Action<ICakeContext>)` and `OnError<TData>(Action<TData,ICakeContext>)`

**Comment by devlead** [comment]
Relates to Gitter discussion https://gitter.im/cake-build/cake?at=5c385c932e25e453d76409f9
> Is there any plans to do OnError<BuildData>?

Suggested current workaround https://gitter.im/cake-build/cake?at=5c3883d883c7e37765510bc9

> Example:
> ```cake
> public class BuildData
> {
>     public bool HasError { get; set; }
> }
> 
> Setup(context=>new BuildData());
> 
> Task("Boom")
>     .Does(()=>throw new Exception("Boom"))
>     .OnError(exception => {
>             Error(exception);
>             var data = Context.Data.Get<BuildData>();
>             data.HasError = true;
>         });
> 
> Teardown<BuildData>((teardownContext, data) =>
> {
>     if (data.HasError)
>     {
>         Error("There was errors.");
>     }
>     else
>     {
>         Information("There was no errors");
>     }
> });
> 
> RunTarget("Boom");
> ```
> Will output
> ![image](https://user-images.githubusercontent.com/1647294/51033338-62072a00-15a3-11e9-8072-8bb57af9661d.png)

**Comment by yansklyarenko** [comment]
@devlead Could you please elaborate on this one?

As far as I understand, when the requested method overload is implemented, the sample above will transform to this:

```
public class BuildData
{
    public bool HasError { get; set; }
}

Setup(context=>new BuildData());

Task("Boom")
    .Does(()=>throw new Exception("Boom"))
    .OnError<BuildData>((exception, data) => {
            Error(exception);
            data.HasError = true;
        });

Teardown<BuildData>((teardownContext, data) =>
{
    if (data.HasError)
    {
        Error("There was errors.");
    }
    else
    {
        Information("There was no errors");
    }
});

RunTarget("Boom");
```

It means there must be a method `OnError<TData>(this CakeTaskBuilder builder, Action<Exception, TData> errorHandler)`, which should end up setting `ErrorHandler` property of the `CakeTask` to some value of type `Action<Exception>`. But where do I get the `data` from? There's no _global_ `Context` like in the sample above, nor there's a parameter of type `ICakeContext`.

I investigated the `Does` functionality which looks similar and has the necessary overload. However, it also has `ICakeContext` parameter and gets `TData` from there when it's needed.

I might be missing something obvious, but it doesn't match in my head right now... I would appreciate some hint. Thanks!

**Comment by devlead** [comment]
There's a global `ICakeContext` `Context` property available in non static methods and delegates in scripts.

So `Context.Data.Get<BuildData>();` will work as long as your not in a class or static method/delegate.

But to sort a `OnError<BuildData>` it would require a little bit more work internally.

**Comment by yansklyarenko** [comment]
> But to sort a `OnError<BuildData>` it would require a little bit more work internally.

Yep, that's clear. I'd like to take over this challenge and would appreciate some hint regarding what that work internally could be. Is there a similar logic in the project I can leverage to understand what should be changed?

**Comment by yansklyarenko** [comment]
@devlead I think I got your point. I would appreciate your review.
