### ISSUE TITLE
Add MSBuildPath to NuGetRestoreSettings

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2459]
The argument in question should be a `DirectoryPath` accepting the path to where `MSBuild.exe` can be found.

From https://docs.microsoft.com/en-us/nuget/tools/cli-ref-restore:

MSBuildPath | (4.0+) Specifies the path of MSBuild to use with the command, taking precedence over -MSBuildVersion.
-- | --

**Comment by daveMueller** [comment]
I made pull request for this #2480. Would be cool if somebody will review and approve or reject.

**Comment by devlead** [comment]
Fixed by #2480.
