### ISSUE TITLE
ParseAssemblyInfo does not support .NET Core generated assembly info 

### ISSUE THREAD

**Issue by Joev-** [cake-build/cake#2473]
### What You Are Seeing?
When parsing an AssemblyInfo file generated by the .NET Core SDK on build no information is returned. e.g. AssemblyInformationalVersion returns the default value of 1.0.0 rather than my specified version.

### What is Expected?
The correct information is returned.

### What version of Cake are you using?
0.32.1

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
Parse the generated AssemblyInfo file using `ParseAssemblyInfo`

```
var assemblyInfo = ParseAssemblyInfo("obj/Debug/netcoreapp2.2/win-x64/MyProject.AssemblyInfo.cs");
Information("Version: {0}", assemblyInfo.AssemblyVersion);
Information("File version: {0}", assemblyInfo.AssemblyFileVersion);
Information("Informational version: {0}", assemblyInfo.AssemblyInformationalVersion);   
```

### Output Log
Not necessary

The reason this is not working is that the generated AssemblyInfo in .NET Core projects uses the full attribute type name rather than the typically shortened type name. Cake uses the shorter name as seen [here](https://github.com/cake-build/cake/blob/main/src/Cake.Common/Solution/Project/Properties/AssemblyInfoParser.cs) whereas .NET core Projects will have `System.Reflection.AssemblyInformationalVersionAttribute` in the generated file. 

An alternative regex that would work for all cases would be this: https://regex101.com/r/Teupyl/1 and modified to allow for the string format substitution:

```
^\s*\[assembly: (?:System\.Reflection\.)?{0}(?:Attribute)?\("(?<attributeValue>.*)"\)
```

**Comment by gep13** [comment]
@Joev- this is known to be the case.

While there was a LOT of churn with the new project format, a parser was created here:

https://github.com/cake-contrib/Cake.Incubator

Which correctly handles the new project format.

At some point, this will be moved into Cake proper.

**Comment by Joev-** [comment]
No problem Gary, I figured that this was the case but spent a while searching and did not come across any other references. I'll check out the Incubator.

**Comment by gep13** [comment]
@Joev- actually, I might have misread your issue....

I thought you were referring to the new csproj format, not an AssemblyInfo file.  I am not sure if there is a new parser for that in Incubator or not.  If not, come back here and we can investigate.

Sorry to mess you around!

**Comment by Joev-** [comment]
Not a problem at all, I did just have a look through the incubator and as you say, I didn't see anything for the AssemblyInfo file.
