### ISSUE TITLE
Lock file arguments for NuGet and dotnet restore

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#2478]
There are additional arguments supported by more recent versions of `nuget restore` and `dotnet restore` for lock file support.

Also,  `dotnet restore` has  --interactive

These are documented [here](https://github.com/NuGet/Home/issues/5602), [here](https://github.com/NuGet/Home/wiki/Enable-repeatable-package-restore-using-lock-file) and announced [here](https://blog.nuget.org/20181217/Enable-repeatable-package-restores-using-a-lock-file.html)

- [ ] `nuget restore`
- [ ] `dotnet restore`

**Comment by devlead** [comment]
fixed by #2479

**Comment by fowl2** [comment]
Did the argument for nuget.exe get forgotten or is this on purpose?

**Comment by flcdrg** [comment]
I realised part way through that it would be better to break it down into
two parts (and do the dotnet bit first). I think I'll raise a separate
issue for the nuget part.
