### ISSUE TITLE
FilePath and DirectoryPath implicit conversions throw for null

### ISSUE THREAD

**Issue by jnm2** [cake-build/cake#2481]
Cake 0.30.0

This is the code I would like to write. It uses a conditional expression to keep it short and sweet:

```cs
        VSTest(testAssembly, new VSTestSettings
        {
            SettingsFile = keepWorkspaces ? "KeepWorkspaces.runsettings" : null
        });
```

If `keepWorkspaces` is false, that causes this error:

> Value cannot be null.
> Parameter name: path

Presumably `SettingsFile` is already null to start with, representing the option to not use a settings file, so null should be a valid option when setting the property.

As a workaround, I have to introduce two new statements and break the order that I'd prefer:

```cs
        var settings = new VSTestSettings();
        if (keepWorkspaces) settings.SettingsFile = "KeepWorkspaces.runsettings";
        VSTest(testAssembly, settings);
```

**Comment by devlead** [comment]
Is it `VSTest` or `new VSTestSettings` that gives you the error issue?

Maybe an helper method could be convenient, something like this (atm you could put it in a cake script):

```cake
public static T If<T>(this T value, Func<T, bool> predicate, Action<T> action)
{
    if (predicate == null || !predicate(value))
    {
        return value;
    }

    action?.Invoke(value);

    return value;
}
```

used like
```cake
new VSTestSettings{
}.If(_=>keepWorkspaces, settings => settings.SettingsFile = "KeepWorkspaces.runsettings");
```

**Comment by jnm2** [comment]
It's hard to tell from the console output (https://ci.appveyor.com/project/CharliePoole/nunit3-vs-adapter/builds/22469410#L1339), but looking at https://github.com/cake-build/cake/blob/v0.30.0/src/Cake.Common/Tools/VSTest/VSTestSettings.cs#L19...

Ah, I just figured it out! The problem is that the implicit conversion operator from `(string)null` to `FilePath` is throwing an exception. I would have said that an implicit operator that throws is a contradiction in terms, since implicit operations are semantically supposed to be guaranteed to succeed at compile time just by knowing the types.

https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/implicit:

> In general, implicit conversion operators should never throw exceptions and never lose information so that they can be used safely without the programmer's awareness. If a conversion operator cannot meet those criteria, it should be marked `explicit`.

Therefore, these operators should check to return null for null input:

https://github.com/cake-build/cake/blob/9419aa4ea96856034043e1609a36f8e63bfb97f4/src/Cake.Core/IO/FilePath.cs#L171-L174

https://github.com/cake-build/cake/blob/9419aa4ea96856034043e1609a36f8e63bfb97f4/src/Cake.Core/IO/DirectoryPath.cs#L144-L147

**Comment by jnm2** [comment]
This is what is implied, according to the C# language:

```cs
VSTest(testAssembly, new VSTestSettings
{
    SettingsFile = (FilePath)(keepWorkspaces ? "KeepWorkspaces.runsettings" : null)
});
```

So my workaround for now will be:


```cs
VSTest(testAssembly, new VSTestSettings
{
    SettingsFile = keepWorkspaces ? (FilePath)"KeepWorkspaces.runsettings" : null
});
```

**Comment by devlead** [comment]
Agreed null should return null.

**Comment by jnm2** [comment]
Are there implicit operators in Cake besides these two?

**Comment by devlead** [comment]
A quick search gives these places

https://github.com/cake-build/cake/blob/a0f142af2dfbf18eecc240789529da428cb0d82a/src/Cake.Common/IO/Paths/ConvertableFilePath.cs#L39-L42

https://github.com/cake-build/cake/blob/a0f142af2dfbf18eecc240789529da428cb0d82a/src/Cake.Common/IO/Paths/ConvertableDirectoryPath.cs#L134-L137

https://github.com/cake-build/cake/blob/a0f142af2dfbf18eecc240789529da428cb0d82a/src/Cake.Core/IO/ProcessArgumentBuilder.cs#L109-L112

https://github.com/cake-build/cake/blob/7a6244a5390b06f58d683dee5a0d6b6fbf4e37fe/src/Cake.Core/IO/DirectoryPath.cs#L144-L147

**Comment by jnm2** [comment]
So that makes three total places that should be fixed: the two above and then ProcessArgumentBuilder. Good enough to put up for grabs?

**Comment by devlead** [comment]
@jnm2 sounds good to me.

**Comment by jnm2** [comment]
I don't see any way ProcessArgumentBuilder's `FromString` can throw, so it's just FilePath and DirectoryPath.

**Comment by jnm2** [comment]
It wasn't the operators that were throwing after all. What actually was happening was that `new FilePath(null)` was returned from the operator. `new FilePath(null)` is a time bomb that causes the ArgumentNullException to happen much later:

https://github.com/cake-build/cake/blob/020d6d3324bf7f35004ccbd3bfcb1d95e9cdfc8d/src/Cake.Common/Tools/VSTest/VSTestRunner.cs#L70-L72

https://github.com/cake-build/cake/blob/020d6d3324bf7f35004ccbd3bfcb1d95e9cdfc8d/src/Cake.Core/IO/FilePath.cs#L125-L132

https://github.com/cake-build/cake/blob/020d6d3324bf7f35004ccbd3bfcb1d95e9cdfc8d/src/Cake.Core/IO/DirectoryPath.cs#L60-L64
