### ISSUE TITLE
Octopus Deploy 2019.1 and Spaces feature

### ISSUE THREAD

**Issue by kcamp** [cake-build/cake#2484]
With the introduction of the "Spaces" feature in Octopus 2019.1, the APIs (and concsequently, `Octo.exe`) support scoping to a respective space.  The `OctopusDeployCommonToolSettings` implementation (or appropriate descendants) should be updated so that all of our aliases provide a more complete coverage.

As noted in GH-1587, the appropriate workaround at present is via `ArgumentCustomization`.

I can submit a PR for this in the next day or two.

**Comment by kcamp** [comment]
Also note that this will require >= OctopusTools.5.2.0
`#tool "nuget:?package=OctopusTools&version=5.2.0"`

**Comment by devlead** [comment]
Fixed by #2485
