### ISSUE TITLE
Add additional Azure DevOps (TFBuild) properties

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#2491]
There's a few missing properties on the TFBuild classes for Azure DevOps Pipeline build variables, documented in https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml

Working on a PR to add these in

**Comment by flcdrg** [comment]
I just noticed that @gitfool has done a couple of these recently (eg. Reason)

**Comment by gitfool** [comment]
I was more focused on laying the foundation for identifying a pull request, across multiple providers, rather than capturing every last detail.

**Comment by flcdrg** [comment]
Probably good timing then that I come after your commit and can add on to your work, given you've looked at the other providers as well.

👍

**Comment by devlead** [comment]
fixed by  #2492
