### ISSUE TITLE
Not able to run dotnet-cake tool on .Net core 3.0

### ISSUE THREAD

**Issue by iAmBipinPaul** [cake-build/cake#2497]
![image](https://user-images.githubusercontent.com/9201481/54250110-929b1e00-456a-11e9-841b-a7c130b48184.png)

**Comment by per-samuelsson** [comment]
We see this too, but only on Linux, while it works on Windows. Any idea why? And anything are being done to resolve it?

We're using Cake 0.33.

**Comment by patriksvensson** [comment]
@per-samuelsson @iAmBipinPaul .NET Core 3.0 has not been released yet so we're currently not building Cake for it, but we will once it reach general availability.

As a work around you can install the .NET Core 2.1 runtime.

**Comment by augustoproiete** [comment]
This has been fixed with the release of Cake v0.35.0 which multi-targets `netcoreapp2.1;netcoreapp3.0`.

Cake v1.0.0 also multi-targets `net5.0` - starting with 1.0.0-rc0001.
