### ISSUE TITLE
Cake should make it easier to change the mono version on mac

### ISSUE THREAD

**Issue by david-driscoll** [cake-build/cake#2506]
### What You Are Seeing?
It's difficult to define the mono version on mac outside of changing the ToolPath directly.  It seems for Azure Pipelines they use this for changing mono versions locally.

### What is Expected?
It should be easier to modify the mono path used when running a build on macos.

### What version of Cake are you using?
0.32.1

### Are you running on a 32 or 64 bit system?
Maybe ?  🤣 

### What environment are you running on?  Windows? Linux? Mac?
Mac

### Are you running on a CI Server?  If so, which one?
Azure Pipelines

https://dev.azure.com/omnisharp/Builds/_build/results?buildId=116

### How Did You Get This To Happen? (Steps to Reproduce)
Trying to build something on Azure Pipelines that requires the latest C# features (7.3) and getting a failure.

https://github.com/OmniSharp/omnisharp-roslyn/

**Comment by david-driscoll** [comment]
Azure Pipelines docs:
https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted?view=azure-devops&tabs=yaml#mono

**Comment by gep13** [comment]
@david-driscoll where would you want to "set" this?  In your Cake script, config file, somewhere else?

**Comment by david-driscoll** [comment]
As discussed, looking for a convention similar to [`NUGET_EXE` in the `NuGetToolResolver`](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/IO/NuGet/NuGetToolResolver.cs#L82).

Thinking a name like `MONO_PATH` or something similar.

**Comment by mholo65** [comment]
Isn't it so, that when Cake runs on Mono, and if you execute an exe, then the same version of Mono that's used to run Cake is also used to run the exe. (@devlead ?). So basically you'd like to specify the mono version when calling cake.exe (which is a responsibility of the bootstrapper).

**Comment by augustoproiete** [comment]
Closing this one as `wont-fix` given that modern versions of Cake no longer run in Mono
