### ISSUE TITLE
OpenCover stoped working

### ISSUE THREAD

**Issue by Jugalio** [cake-build/cake#2510]
Hi guys,

i configurated my cake build script a while ago and open cover worked as expected. I did not touch the project for something like 2 months. When i tried to rerun the build script today open cover was not able to create results with the following msg:

Committing...
No results, this could be for a number of reasons. The most common reasons are:
    1) missing PDBs for the assemblies that match the filter please review the
    output file and refer to the Usage guide (Usage.rtf) about filters.
    2) the profiler may not be registered correctly, please refer to the Usage
    guide and the -register switch.

-> I checked the bin folder and the pdb file exists

My test task looks like this (I already removed the filters to make sure they are not the problem):

		var coverSettings = new OpenCoverSettings()
		{
			Register = "user",
			SkipAutoProps = true,
		};

		var reportGeneratorSettings = new ReportGeneratorSettings();

		var reportGeneratorSettingsCobertura = new ReportGeneratorSettings()
		{
			ArgumentCustomization = args => args.Append("-reporttypes:Cobertura" ),
		};

		foreach (var testProject in unitTests)
		{
			string projectName = testProject.GetFilename().ToString().Replace(".Tests.csproj", string.Empty);
		
			string testDir = "./TestResults";
			EnsureDirectoryExists(testDir);
		
			string openCoverDir = $"{testDir}/OpenCover/{projectName}";
			EnsureDirectoryExists(openCoverDir);
		
			string resultsFileName = $"{testDir}/{projectName}_TestResults.xml";
			var openCoverFilePath = new FilePath($"{openCoverDir}/_results.xml");

			var unitSettings = new NUnit3Settings 
			{ 
				ShadowCopy = false,
				Results = new[] { new NUnit3Result { FileName = resultsFileName } }, 
			};

			OpenCover(tool => 
				{ 
					tool.NUnit3(testProject.ToString(), unitSettings); 
				}, 
				openCoverFilePath, 
				coverSettings					
			);
			ReportGenerator(openCoverFilePath, openCoverDir, reportGeneratorSettingsCobertura);
			ReportGenerator(openCoverFilePath, $"{openCoverDir}/html", reportGeneratorSettings);
		}

Output File:

![grafik](https://user-images.githubusercontent.com/33733301/54904307-738f7b00-4ede-11e9-9095-ad71d2490ef8.png)

**Comment by gep13** [comment]
Is this a public project? Can you share a link? Are you pinning to a specific version of tools/addins/Cake?

**Comment by Jugalio** [comment]
No its not public. I tried the versions 4.6.519 and 4.7.922 of open cover.
None worked yesterday. Today though its working again.
The only thing, that changed was the company proxy, which was blocking nuget yesterday and the problem seems to be connected to that problem, which is strange, cause the binaries were already loaded.
Either way the problem is solved.
