### ISSUE TITLE
XmlTransform support for xsl arguments

### ISSUE THREAD

**Issue by dnperfors** [cake-build/cake#2524]
The XmlTransform aliases seem to be a bit restricted for our scenario. We have some advanced xsl scripts that expect xslt arguments to be passed to the transformer. Using the .NET libraries that would be the `System.Xml.Xslt.XsltArgumentList` which can be passed to the `Transform` method of `XslCompiledTransformation`. (which is used by the XmlTransform alias)
Any change for getting an update with support for transfromation arguments?

**Comment by deqenq** [comment]
Could I work on it?
