### ISSUE TITLE
Publish Cake.Testing.Xunit package

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#2532]
Following up from cake-contrib gitter chat, it would be nice to publish `Cake.Testing.Xunit` as a NuGet package since it has some useful attributes like `WindowsFact` and `WindowsTheory`.

Note: should also update to `xunit` 2.4.1 before publishing.

**Comment by gep13** [comment]
Gitter conversation was here: https://gitter.im/cake-contrib/Lobby?at=5cbd7f80990feb4518e1b0c2

**Comment by Marusyk** [comment]
As I understand, for this issue there should exists the Cake.Testing.Xunit repository here https://github.com/cake-contrib. Could you please create it and I will try to move Cake.Testing.Xunit?

**Comment by devlead** [comment]
No we should just update xunit and adjust Cake's own build script so Cake.Testing.XUnit is packed and punlished.

**Comment by devlead** [comment]
Frixed by  #2631
