### ISSUE TITLE
Setting SecurityRules with CreateAssemblyInfo

### ISSUE THREAD

**Issue by dnperfors** [cake-build/cake#2533]
### What You Are Seeing?
When I want to use the CreateAssemblyInfo to set the `[assembly: SecurityRules(SecurityRuleSet.Level2)]` attribute (which is [recommended](docs.microsoft.com/en-us/dotnet/framework/misc/security-transparent-code-level-2?view=netframework-4.7.2) to do by Microsoft) I get a compile error that I can't convert a string to a SecurityRuleSet.

The code I use is:
```
    CreateAssemblyInfo("./code/SharedAssemblyInfo.cs", new AssemblyInfoSettings
    {
        CustomAttributes = new List<AssemblyInfoCustomAttribute>
        {
            new AssemblyInfoCustomAttribute { Name = "SecurityRules", NameSpace = "System.Security", Value ="SecurityRuleSet.Level2" }
        },
    });
```

And generates:
```
[assembly: SecurityRules("SecurityRuleSet.Level2")]
```

### What is Expected?
I would expect to be able to give any type of value to AssemblyInfoCustomAttribute, for example a generic:
```
    CreateAssemblyInfo("./code/SharedAssemblyInfo.cs", new AssemblyInfoSettings
    {
        CustomAttributes = new List<AssemblyInfoCustomAttribute>
        {
            new AssemblyInfoCustomAttribute<SecurityRuleSet> { Name = "SecurityRules", NameSpace = "System.Security", Value =SecurityRuleSet.Level2 }
        },
    });
```

And generates:
```
[assembly: SecurityRules(SecurityRuleSet.Level2)]
```

### What version of Cake are you using?
0.33.0

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

**Comment by devlead** [comment]
Fixed by  #2648
