### ISSUE TITLE
DeferOnError with Dependents

### ISSUE THREAD

**Issue by elmankross** [cake-build/cake#2552]
_I was trying to find a solution in official docs / so / sources and found nothing._
Let's imagine some cake config like this one:
```
Task("Tests")
	.IsDependentOn("CreateEnvDatabase")
	.IsDependentOn("Migration::Up")
	.IsDependentOn("Tests::Integration")
	.IsDependentOn("DropEnvDatabase");
```
What we are doing here? -
1) Prepare databases _(start localdb server / create database/ etc)_ for test environment
2) Apply migrations to databases
3) Start tests
4) Drop databases and stop localdb server if needs

So, what is **DropEnvDatabase** task? - 
```
Task("DropEnvDatabase")
	.IsDependentOn("DropEnvDatabase::MsSql")
	.IsDependentOn("DropEnvDatabase::Mongo");

Task("DropEnvDatabase::MsSql")
	.Does<BuildState>((state) => {
	        var (server, database) = state.GetMsSqlEnvDbOptions(envConfiguration);
		DropDatabase(server, database);
	});

Task("DropEnvDatabase::Mongo")
	.Does<BuildState>((state) => {
		state.DisposeMongoDbRunner();
	});
```
Ok, for this flow we need something like **DeferOnError** but applied to all task's chain includes **IsDependentOn** statement because of **Tests::Integration** task may throw exceptions after which needs to clean up a test environment. I was trying to achieve this one via task's state _(catch exceptions in "Tests::Integration". Write it to state's variable and process it in next steps)_  but it seems like incorrect way.

Is there a chance to implement DeferOnError for full task's chain?
```
Task("Tests")
	.DeferOnError()
	.IsDependentOn("CreateEnvDatabase")
	.IsDependentOn("Migration::Up")
	.IsDependentOn("Tests::Integration")
	.IsDependentOn("DropEnvDatabase");
``` 
Or maybe is different way for this flow...

**Comment by gep13** [comment]
@elmankross any reason that you can't use the finally block to do any final processing, as per Cake's own build script here:

https://github.com/cake-build/cake/blob/f48c6a9a253e62334474f5053cd6a23b8b520c23/build.cake#L682-L696

**Comment by elmankross** [comment]
@gep13, Thank you for your reply.

The reason I can't use a Final() block is I need some logic in task representation for development reason and keep it reusable.
So, maybe something like this:
```
 Task("AppVeyor1") 
   .IsDependentOn("1") 
   .IsDependentOn("2") 
   .FinalTask("PostError"); 

 Task("AppVeyor2") 
   .IsDependentOn("2") 
   .IsDependentOn("3") 
   .FinalTask("PostError"); 
```
will be helpful.

**Comment by gep13** [comment]
> @elmankross said...
My main goal is to complete a Task chain even one of dependency has an error and throw this error in the end оf Task.

That is exactly what the sample that I showed you is doing. All publishing tasks are attempted, even though one of them fails, and if anyone of them fail, the overall build fails.

**Comment by elmankross** [comment]
@gep13 
I got your solution.
So I need something like 
```
var target = Argument("target", "3");
var isError = false;

Task("1")
  .Does(() => {
	  throw new Exception("Exception in task 1");
  })
  .OnError(ex => {
	  isError = true;
  });

Task("2")
  .DeferOnError()
  .Does(() => {
	  throw new Exception("Exception in task 2.1");
  })
  .Does(() => {
	  Information("Task 2.2 completed!");
  })
  .OnError(ex => {
	  isError = true;
  });

Task("3")
  .IsDependentOn("1")
  .IsDependentOn("2")
  .Finally(() => {
	  Information("Chain complete!");
	  if(isError)
	  {
		  Information("There is an error");
	  }
  });
	
RunTarget(target);
```
instead of
```
var target = Argument("target", "3");

Task("1")
  .Does(() => {
	  throw new Exception("Exception in task 1");
  });

Task("2")
  .DeferOnError()
  .Does(() => {
	  throw new Exception("Exception in task 2.1");
  })
  .Does(() => {
	  Information("Task 2.2 completed!");
  });

Task("3")
  .IsDependentOn("1")
  .IsDependentOn("2")
  .Finally(() => {
	  Information("Chain complete!");
  });
	
RunTarget(target);
```
It's a working version but not convenient in a situation when we need only throw an exception at the end of a chain without some custom logic. Like **DeferOnError()** for Task **Does()** statements.
Instead of use 
```
Exception exception = null;
Task("1")
  .Does(() => {
    try
    {
      // Some work can throw exceptions
     throw new Exception("Error during executing");
    }
    catch(Exception ex)
    {
      exception = ex;
    }
  })
  .Does(() => Information("Some logic"))
  .Finally(() => {
    if(exception != null)
    {
       throw exception;
    }
  });
```
we just do equivalent
```
Task("1")
  .DeferOnError()
  .Does(() => {
      // Some work can throw exceptions
     throw new Exception("Error during executing");
  })
  .Does(() => Information("Some logic"));
```
