### ISSUE TITLE
error MSB1008 when MSBuildBinaryLogSettings.FileName has spaces

### ISSUE THREAD

**Issue by FroggieFrog** [cake-build/cake#2558]
### What You Are Seeing?
MSBuild error MSB1008 when using a BinaryLogger and a path with space
### What is Expected?
no error
### What version of Cake are you using?
0.33
### Are you running on a 32 or 64 bit system?
32 bit
### What environment are you running on?  Windows? Linux? Mac?
Windows 10 1903
### Are you running on a CI Server?  If so, which one?
No
### How Did You Get This To Happen? (Steps to Reproduce)
Add a BinaryLogger and specify a path with space.
```csharp
var msBuildSettings = new MSBuildSettings()
{
            ...
            BinaryLogger = new MSBuildBinaryLogSettings
            {
                Enabled = true,
                FileName = "Path with\spaces in between\log.binlog"
            },
            ...
        };
```

### Output Log
![unknown](https://user-images.githubusercontent.com/6222752/58357152-08303e00-7e7a-11e9-8727-07416bdbf437.png)

**Comment by augustoproiete** [comment]
This was resolved by https://github.com/cake-build/cake/pull/2559 and released with Cake v1.1.0
