### ISSUE TITLE
Cake Version 0.34.0 dynamic not more supported

### ISSUE THREAD

**Issue by Xoroles** [cake-build/cake#2580]
Hello, with the newest Version of Cake (0.34.0) dynamic Usage ist not more Supported. 

I get the following error Message:

Error: D:/bamboo-home/...../build.cake(130,33): error CS0656: Missing compiler required member 'Microsoft.CSharp.RuntimeBinder.CSharpArgumentInfo.Create'
--

With Version 0.33.0 we have no problem.

**Comment by devlead** [comment]
Hi this was addressed in 0.34.1 which was released yesterday
https://cakebuild.net/blog/2019/07/cake-v0.34.1-released
