### ISSUE TITLE
Cake.Tool - How in the world do I run a specific task?

### ISSUE THREAD

**Issue by VictorioBerra** [cake-build/cake#2585]
```
PS C:\Source\Templates> dotnet cake --help

Usage: Cake.exe [script] [--verbosity=value]
                [--showdescription] [--dryrun] [..]

Example: Cake.exe
Example: Cake.exe build.cake --verbosity=quiet
Example: Cake.exe build.cake --showdescription

Options:
    --verbosity=value    Specifies the amount of information to be displayed.
                         (Quiet, Minimal, Normal, Verbose, Diagnostic)
    --debug              Performs a debug.
    --showdescription    Shows description about tasks.
    --showtree           Shows the task dependency tree.
    --dryrun             Performs a dry run.
    --exclusive          Execute a single task without any dependencies.
    --bootstrap          Download/install modules defined by #module directives
    --version            Displays version information.
    --info               Displays additional information about Cake execution.
    --help               Displays usage information.
```

I see no way here on how I can specify the task to run.

Not mentioned here either https://cakebuild.net/blog/2018/08/cake-v0.30.0-released

**Comment by VictorioBerra** [comment]
I just answered my question, I had to open the build.ps1 file and find the `-target="whatever"` which worked. Should this be documented somewhere at least?

**Comment by Insire** [comment]
it is [here](https://cakebuild.net/docs/fundamentals/running-targets)

**Comment by VictorioBerra** [comment]
@Insire Yes but the dotnet CLI global tool Cake.Tool bootstrap wrapper for cake does not have any documentation on those.

**Comment by Roadrunner67** [comment]
I've just made  a PR #2605

**Comment by Roadrunner67** [comment]
@VictorioBerra The answer you should have had to your issue post is something like this:

Target is a term unknown to Cake itself.

It is something we usually build into our Cake scripts, beginning with:
`var target = Argument("target", "Default");
`
..and ending with:

`RunTarget(target);
`
So you can choose the target from outside by adding -target=value to your command line.
If you don't, the target 'Default' will be executed (where you can place your own instruction to the user to select a specific task, if there is no logical default).

build.ps1/build.sh should only in very rare cases need modification.
