### ISSUE TITLE
DotNetCorePublish not producing web publish method of Package

### ISSUE THREAD

**Issue by bigswede74** [cake-build/cake#2596]
### What You Are Seeing?
When running DotNetCorePublish the project publish profile is being ignored and no WebDeploy .zip file is created.
### What is Expected?
There should be a parameter for the web deploy profile.
### What version of Cake are you using?
0.34.1.0
### Are you running on a 32 or 64 bit system?
64
### What environment are you running on?  Windows? Linux? Mac?
Windows 10

**Comment by bigswede74** [comment]
I was able to use the ArgumentCustomication to pass the publish profile.

`    var publishSettings = new DotNetCorePublishSettings
    {
        Configuration = configuration,
        OutputDirectory = publishPath,
		ArgumentCustomization = args => args.Append("/p:PublishProfile=MyPublishProfile"),
    };
	 
	DotNetCorePublish(myProject, publishSettings);`

**Comment by devlead** [comment]
@bigswede74 great you got it sorted, MSBuild properties can also be added through the MSBuild setttings property i.e.

```csharp
var publishSettings = new DotNetCorePublishSettings
{
     Configuration = configuration,
     OutputDirectory = publishPath,
     MSBuildSettings = new DotNetCoreMSBuildSettings()
                                    .WithProperty("PublishProfile", "MyPublishProfile")
};
	 
DotNetCorePublish(myProject, publishSettings);
```
