### ISSUE TITLE
NuGet nuspec dependency

### ISSUE THREAD

**Issue by Eldadc** [cake-build/cake#2620]
Hi,

Is it possible to create an example of adding  NuGet nuspec dependency,

Thanks

**Comment by devlead** [comment]
For which alias?

Do you mean for [NuGetPack](https://cakebuild.net/api/Cake.Common.Tools.NuGet/NuGetAliases/EF4ED944) [NuGetPackSettings](https://cakebuild.net/api/Cake.Common.Tools.NuGet.Pack/NuGetPackSettings/) parameter [Dependencies](https://cakebuild.net/api/Cake.Common.Tools.NuGet.Pack/NuGetPackSettings/A6EE5D60) property which takes an ICollection of [NuSpecDependency](https://cakebuild.net/api/Cake.Common.Tools.NuGet.Pack/NuSpecDependency/)?

Setting the [Dependencies](https://cakebuild.net/api/Cake.Common.Tools.NuGet.Pack/NuGetPackSettings/A6EE5D60) property could look something like this
```cake
var nugetPackSettings = new NuGetPackSettings {
    Dependencies = new [] {
        new NuSpecDependency {
            Id = "Cake.Core",
            Version = "0.34.1"
        }
    }
};
```

If so, a code sample for that would go either here
https://github.com/cake-build/cake/blob/a28a6f2e697dc2ce94b88e3004a1b2546c6e76b0/src/Cake.Common/Tools/NuGet/Pack/NuGetPackSettings.cs#L216
and/or here
https://github.com/cake-build/cake/blob/a28a6f2e697dc2ce94b88e3004a1b2546c6e76b0/src/Cake.Common/Tools/NuGet/NuGetAliases.cs#L41-L67
https://github.com/cake-build/cake/blob/a28a6f2e697dc2ce94b88e3004a1b2546c6e76b0/src/Cake.Common/Tools/NuGet/NuGetAliases.cs#L93-L118
https://github.com/cake-build/cake/blob/a28a6f2e697dc2ce94b88e3004a1b2546c6e76b0/src/Cake.Common/Tools/NuGet/NuGetAliases.cs#L144-L168

**Comment by Eldadc** [comment]
Hi,
Thanks on the quick response.
I tried excatlly same format.
Getting the following error:

'Cake.Nuget.Pack.Nuspec.Dependency does not contain a definition for id'

Thanks

**Comment by devlead** [comment]
C# is case sensitive, it's `Id` with an capital `I`, example 
```cake
new NuSpecDependency {
    Id = "Cake.Core",
    Version = "0.34.1"
}
```

**Comment by Eldadc** [comment]
Hi,

Tried also upper and lower case.

I added it like here:

var nuGetPackSettings = new NuGetPackSettings {
/// Id = "TestNuGet",
/// Version = "0.0.0.1",
/// Title = "The tile of the package",
/// Authors = new[] {"John Doe"},
/// Owners = new[] {"Contoso"},
/// Description = "The description of the package",
/// Summary = "Excellent summary of what the package does",
/// ProjectUrl = new Uri("https://github.com/SomeUser/TestNuGet/"),
/// IconUrl = new Uri("
http://cdn.rawgit.com/SomeUser/TestNuGet/master/icons/testNuGet.png"),
/// LicenseUrl = new Uri("
https://github.com/SomeUser/TestNuGet/blob/master/LICENSE.md"),
/// Copyright = "Some company 2015",
/// ReleaseNotes = new [] {"Bug fixes", "Issue fixes", "Typos"},
/// Tags = new [] {"Cake", "Script", "Build"},
/// RequireLicenseAcceptance= false,
/// Symbols = false,
/// NoPackageAnalysis = true,
/// Files = new [] {
/// new NuSpecContent {Source = "bin/TestNuGet.dll", Target = "bin"},
/// },
/// BasePath = "./src/TestNuGet/bin/release",
/// OutputDirectory = "./NuGet"

  Dependencies = new [] { NuSpecDependency {

    Id = "Cake.Core",
    Version = "0.34.1"
} }

/// };

**Comment by gep13** [comment]
@Eldadc can you please provide a complete example build script that isn't currently working for you?  Also, can you please confirm what version of Cake you are using?

**Comment by devlead** [comment]
`NuSpecDependency` is a class so 
```cake
Dependencies = new [] { NuSpecDependency {

    Id = "Cake.Core",
    Version = "0.34.1"
} }
```
needs to be something like
```cake
 Dependencies = new [] {
        new NuSpecDependency {
            Id = "Cake.Core",
            Version = "0.34.1"
        }
    }
```

**Comment by Eldadc** [comment]
Hi

Installed new version. Case resolved.
Thanks
