### ISSUE TITLE
DotNetCoreTestSettings Can Have Multiple Logger's

### ISSUE THREAD

**Issue by RehanSaeed** [cake-build/cake#2623]
With .NET Core 3.0 and with the latest `Microsoft.NET.Test.Sdk` `16.3.0` NuGet package installed in your test project, you can now create HTML reports as well as TRX XML files like so:

```bash
dotnet test --logger trx;LogFileName=foo.trx --logger html;LogFileName=foo.html
```

The [DotnetCoreTestSettings.Logger](https://github.com/cake-build/cake/blob/e3550d249da09388c573e5af6206bb98ebf79b8f/src/Cake.Common/Tools/DotNetCore/Test/DotNetCoreTestSettings.cs#L35) property is currently a `string` and needs to be an `IEnumerable<string>`.

**Comment by devlead** [comment]
Fixed by #2867
