### ISSUE TITLE
Since this morning '-ScriptArgs' does not work anymore

### ISSUE THREAD

**Issue by SebastienHo** [cake-build/cake#2642]
### What You Are Seeing?
```
build.ps1 -Script './.cicd/cake/build.cake' -Target 'CIProcess' -ScriptArgs '--settings_skipverification=true --BUILD_NUGET_SOURCE="https://pkgs.dev.azure.com/
dev-traceparts-com/_packaging/Nuget-Packages/nuget/v3/index.json" --SYSTEM_ACCESSTOKEN=*** --BUILD_SOURCEBRANCHNAME="development" --BUILD_DOCKER_LOGIN="TracePartsDockerRepo" --BUILD_DOCKER_PASSW
ORD="***" --BUILD_DOCKER_ADDRESS="tracepartsdockerrepo.azurecr.io" --BUILD_SONAR_LOGIN="tp_services" --BUILD_SONAR_PASSWORD="***" --BUILD_SONAR_ADDRESS="https://sonar.traceparts.com" --BUILD_DES
CRIPTION="Tracks solution" --BUILD_SONAR_BUILDBREAKERQUERYMAXATTEMPS=600 --BUILD_SONAR_BREAKIFQUALITYFAILS=false --BUILD_PROJECT_NAME="TraceParts.tracks.get.api" --BUILD_VERSION="2019.289.624.43
" --BUILD_DB_CONNECTION_STRINGS="./connectionstring.json"'
```
The script failed stating 

Preparing to run build script...
Running build script...
Solution file C:/agent/_work/1/s/TraceParts.Tracks.sln
Error: One or more errors occurred.
        The target 'CIProcess--settings_skipverification=true' was not found.

### What is Expected?

Script should be running adn succeed

### What version of Cake are you using?

Cake.exe : 0.35.0.0

### Are you running on a 32 or 64 bit system?

x64

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

Self hosted Windows Core 2016 1803

### How Did You Get This To Happen? (Steps to Reproduce)

running the folliwng command : build.ps1 -Script './.cicd/cake/build.cake' -Target 'CIProcess' -ScriptArgs ' --settings_skipverification=true --BUILD_NUGET_SOURCE="https://pkgs.dev.azure.com/
dev-traceparts-com/_packaging/Nuget-Packages/nuget/v3/index.json" --SYSTEM_ACCESSTOKEN=*** --BUILD_SOURCEBRANCHNAME="development" --BUILD_DOCKER_LOGIN="TracePartsDockerRepo" --BUILD_DOCKER_PASSW
ORD="***" --BUILD_DOCKER_ADDRESS="tracepartsdockerrepo.azurecr.io" --BUILD_SONAR_LOGIN="tp_services" --BUILD_SONAR_PASSWORD="***" --BUILD_SONAR_ADDRESS="https://sonar.traceparts.com" --BUILD_DES
CRIPTION="Tracks solution" --BUILD_SONAR_BUILDBREAKERQUERYMAXATTEMPS=600 --BUILD_SONAR_BREAKIFQUALITYFAILS=false --BUILD_PROJECT_NAME="TraceParts.tracks.get.api" --BUILD_VERSION="2019.289.624.43
" --BUILD_DB_CONNECTION_STRINGS="./connectionstring.json"'

### Output Log

~~~
Preparing to run build script...
Running build script...
Solution file C:/agent/_work/1/s/TraceParts.Tracks.sln
Error: One or more errors occurred.
        The target 'CIProcess--settings_skipverification=true' was not found.


I have tested to add ' ' after SriptArgs first argument nd it works again

```
build.ps1 -Script './.cicd/cake/build.cake' -Target 'CIProcess' -ScriptArgs ' --settings_skipverification=true --BUILD_NUGET_SOURCE="https://pkgs.dev.azure.com/
dev-traceparts-com/_packaging/Nuget-Packages/nuget/v3/index.json" --SYSTEM_ACCESSTOKEN=*** --BUILD_SOURCEBRANCHNAME="development" --BUILD_DOCKER_LOGIN="TracePartsDockerRepo" --BUILD_DOCKER_PASSW
ORD="***" --BUILD_DOCKER_ADDRESS="tracepartsdockerrepo.azurecr.io" --BUILD_SONAR_LOGIN="tp_services" --BUILD_SONAR_PASSWORD="***" --BUILD_SONAR_ADDRESS="https://sonar.traceparts.com" --BUILD_DES
CRIPTION="Tracks solution" --BUILD_SONAR_BUILDBREAKERQUERYMAXATTEMPS=600 --BUILD_SONAR_BREAKIFQUALITYFAILS=false --BUILD_PROJECT_NAME="TraceParts.tracks.get.api" --BUILD_VERSION="2019.289.624.43
" --BUILD_DB_CONNECTION_STRINGS="./connectionstring.json"'
```

**Comment by augustoproiete** [comment]
(Moving to GitHub Discussions/Q&A)
