### ISSUE TITLE
Cake cannot Activate Instance in Addin

### ISSUE THREAD

**Issue by markofranjic** [cake-build/cake#2656]
Hi Team,

I use C# Cake 0.35 version. I want to Activate Instance of some object. When I use .Net core 3.0 in my console application everything works as excepted.
![instance](https://user-images.githubusercontent.com/15909773/68225264-76178e80-fff0-11e9-8034-9ea4a6e02283.png)

But when I call same code from Cake I got error message “An exception of type 'System.ArgumentNullException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Value cannot be null.'
at System.Activator.CreateInstance(Type type, Boolean nonPublic) at System.Activator.CreateInstance(Type type) 
”
![2](https://user-images.githubusercontent.com/15909773/68225347-921b3000-fff0-11e9-830f-f8bda395b2ff.png)

I use it like C# cake addin on which I work. But code is same like in visual studio.

**Comment by devlead** [comment]
Can you create a small gist or repo with just code needed to repro the issue you're seeing?

**Comment by markofranjic** [comment]
Absolutely, I will let you know when I prepare for git

**Comment by markofranjic** [comment]
Hi DevLead you can download file from https://drive.google.com/file/d/1OlhNYll2x-r4sP2rFFnF2a7DeLiHcYYO/view?usp=sharing

Regards,
Marko

**Comment by markofranjic** [comment]
> Can you create a small gist or repo with just code needed to repro the issue you're seeing?

Hi,

I have changed my common.cake to common.cs and everything works as excepted. Could you please explain me how Cake works with .cake and cs file?

**Comment by markofranjic** [comment]
Hi,

Do you have any update regarding this case?

**Comment by augustoproiete** [comment]
Hi @markofranjic it's been a long time, but I'd like to take a closer look at this one. Would you be able to restore access to the file in your Google Drive, or post the file somewhere else?

![image](https://user-images.githubusercontent.com/177608/107096474-3afe9f00-67e1-11eb-8b77-ff5a4b257902.png)

**Comment by augustoproiete** [comment]
Closing this due to no response from issue creator. Feel free to reopen if still relevant
