### ISSUE TITLE
Rename TFBuild alias to AzurePipelines

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#2658]
### What You Are Seeing?
With the rename of Visual Studio Team Services / Team Foundation Server to Azure DevOps, the [TFBuild](https://cakebuild.net/api/Cake.Common.Build/BuildSystemAliases/09F94647) alias doesn't fit anymore.

### What is Expected?
The alias should be called `AzurePipelines` instead. Classes should also be renamed. To be backwards compatible we can mark the existing `TFBuild` alias as obsolete. Additionaly we might want to remove obsolete members from the new alias / classes.

### What version of Cake are you using?
0.35.0

### Are you running on a 32 or 64 bit system?
N/A

### What environment are you running on?  Windows? Linux? Mac?
N/A

### Are you running on a CI Server?  If so, which one?
Azure Pipelines

**Comment by Marusyk** [comment]
Can I take this one?

**Comment by patriksvensson** [comment]
@Marusyk Sure! Make sure that you keep the existing aliases and mark them as obsolete so we're backwards compatible and doesn't break anyone's builds. You can find other examples of this in the code base. If you got any questions, feel free to reach out.

**Comment by Marusyk** [comment]
Hello @patriksvensson 
Could you please give me some clarification?

1. Copy `TFBuild` alias folder and rename it to  `AzurePipelines`
2. The `TFBuild` don't remove, just mark it as obsolete
3. Add the  `AzurePipelines`  to `BuildSystem` and `BuildSystemAliases`
4. All tests duplicate to  `AzurePipelines`

What do you think about it?
Thank you in advance

**Comment by Marusyk** [comment]
Hello @patriksvensson
it would be great to have any comments from you

**Comment by patriksvensson** [comment]
@Marusyk Sorry for the late reply. Missed this somehow...

Yes, sounds like a good idea!
