### ISSUE TITLE
Build not stopped when rethrowing exception in OnError

### ISSUE THREAD

**Issue by GeertvanHorrik** [cake-build/cake#2661]
### What You Are Seeing?

As described in the [docs](https://cakebuild.net/docs/fundamentals/error-handling), I am using `OnError` to catch an exception and log something.

I do expect the build to fail though when I throw another (same) exception).

### What is Expected?

Build to fail and exit code of cake to be != 0.

### What version of Cake are you using?

0.35.0

### Are you running on a 32 or 64 bit system?

64-bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

Irrelevant

### How Did You Get This To Happen? (Steps to Reproduce)

Here is an example code:

```csharp
.OnError<BuildContext>(async (ex, buildContext) => 
{
    await buildContext.SourceControl.MarkBuildAsFailedAsync("Build");

    Error(ex);

    throw ex;
});
```

**Comment by GeertvanHorrik** [comment]
I think I found the reason. There are no task overloads in https://github.com/cake-build/cake/blob/develop/src/Cake.Core/CakeTaskBuilder.Errors.cs, so async methods are not allowed.

Would you be open to a PR that adds Func<Task> as well?

**Comment by patriksvensson** [comment]
@GeertvanHorrik Absolutely. I think that async should be supported for this as well.

@cake-build/cake-team Any objections to this?

**Comment by devlead** [comment]
> @cake-build/cake-team Any objections to this?

No objection from me.
