### ISSUE TITLE
C# 8 Using Statement produces compile error

### ISSUE THREAD

**Issue by richardnagle** [cake-build/cake#2665]
### What You Are Seeing?
When using the new C#8 `using var...` statement, the cake script produces compile errors.

### What is Expected?
This script should compile successfully.

### What version of Cake are you using?
0.35.0

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 10

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)

```
Task("C#8-Using-Statement")
    .Does(() =>
    {
        using var file = System.IO.File.Create(@".\temp.txt");
    });
```

### Output Log
```
> .\build.ps1 -target C#8-Using-Statement

Preparing to run build script...
Running build script...
(5,11): error CS1002: ; expected
(5,7): error CS0825: The contextual keyword 'var' may only appear within a local variable declaration or in script code
(5,11): error CS0103: The name 'file' does not exist in the current context
```

**Comment by devlead** [comment]
I believe this is likely an issue with the script per-processing.

To unblock you for this specific use case as it's an stream that implements async disposable you can adjust your code to 
```cake
Task("C#8-Using-Statement")
    .Does(async () =>
    {
        await using var file = System.IO.File.Create(@".\temp.txt");
    });
```

**Comment by devlead** [comment]
Just FYI Cake has a built in IO abstraction layer that handles OS/Environment specific things for you. i.e. path normalization. It will also mean you can take advantage of any module that enhances the filesystem i.e. long path, there's a fake file system in Cake.Testing etc.

Utilizing Cake FileSystem could i.e. look something like 
```cake
Task("C#8-Using-Statement")
    .Does(async context =>
    {
        await using var file = context.FileSystem.GetFile("./temp.txt").OpenWrite();
    });
```

**Comment by gitfool** [comment]
I stumbled across this just now while trying the latest shiny C# with Cake version `2.0.0-rc0002`: 😞 

![image](https://user-images.githubusercontent.com/750121/143691122-ac299e1f-57a2-463d-be04-2e88e6da4887.png)

(Example from [using statement (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement))

**Comment by devlead** [comment]
> I stumbled across this just now while trying the latest shiny C# with Cake version `2.0.0-rc0002`: 😞 
> 
> ![image](https://user-images.githubusercontent.com/750121/143691122-ac299e1f-57a2-463d-be04-2e88e6da4887.png)
> 
> (Example from [using statement (C# Reference)](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/using-statement))

Fix would be somewhere around here
https://github.com/cake-build/cake/blob/0de2adc821dd65bc7c003d16c03878971c2698e6/src/Cake.Core/Scripting/Processors/UsingStatementProcessor.cs#L35


Some conditional to return false. 

Maybe line contains `(` and `)` or something similar.
