### ISSUE TITLE
NuGet Install doesn't allow to set NonInteractive to false

### ISSUE THREAD

**Issue by Diogomrol** [cake-build/cake#2671]
### What You Are Seeing?
When I call NuGetInstall, Cake forces passing the argument -NonInteractive by default without allowing the developer to force otherwise.

### What is Expected?
Like it happens in NuGetRestore, I expect to be able to set NonInteractive to false in NuGetInstall.

(I added no more information because this looks good enough).

Thanks,
Diogo

**Comment by Diogomrol** [comment]
If this seems to make sense, I may start working on a PR to fix this issue.

**Comment by devlead** [comment]
Yes enabling to have that on `NuGetInstallSettings` makes sense to me.

**Comment by patriksvensson** [comment]
Closed via #2672
