### ISSUE TITLE
DotNetCorePublishSettings should support new .NET Core 3 features

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#2673]
New publishing features in .NET Core 3 to that would be nice to support:

- PublishSingleFile
- PublishTrimmed
- TieredCompilationQuickJit
- TieredCompilation
- PublishReadyToRun

**Comment by gep13** [comment]
@flcdrg are you in a position to submit a PR for this?

**Comment by flcdrg** [comment]
Yes, I can do that.

David

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by flcdrg** [comment]
And adding some other new .NET Core 3 publishing options..

**Comment by devlead** [comment]
Fixed by #2674
