### ISSUE TITLE
InspectCode: Add support for InspectCode.x86.exe tool

### ISSUE THREAD

**Issue by fafanoulele** [cake-build/cake#2675]
In order to use InspectCode (aka Resharper InspectCode Command-Line Tool) against Visual Studio C++ project, it is required to use the command/tool `InspectCode.x86.exe` instead of `InspectCode.exe` It is mentioned in the followed link: https://www.jetbrains.com/help/resharper/InspectCode.html.

It would be good to add support for this tool `InspectCode.x86.exe`.

**Comment by fafanoulele** [comment]
FYI, I've submitted the following PR https://github.com/cake-build/cake/pull/2676.

**Comment by devlead** [comment]
Fixed by #2676
