### ISSUE TITLE
Add GitHub Actions build provider

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#2677]
I've migrated my repositories to build with GitHub Actions.

Cake needs a build provider to surface workflow and pull request information.

**Comment by RehanSaeed** [comment]
Looks like there is a slight oversight. This works:

```c#
BuildSystem.GitHubActions.IsRunningOnGitHubActions
```

However, this produces a compiler error:

```c#
GitHubActions.IsRunningOnGitHubActions
```

In theory this should work because I also use:

```c#
TFBuild.IsRunningOnAzurePipelinesHosted
AppVeyor.IsRunningOnAppVeyor
```

**Comment by devlead** [comment]
@RehanSaeed you're correct there's a alias property missing and should be added to 
[BuildSystemAliases.cs](https://github.com/cake-build/cake/blob/12c79ceb2e6a47387e014bb99cb4572b31a77b03/src/Cake.Common/Build/BuildSystemAliases.cs#L28)

Could you raise a separate issue for this? so we can have that addressed.

**Comment by RehanSaeed** [comment]
Done in https://github.com/cake-build/cake/issues/2691
