### ISSUE TITLE
Ability to  change working Directory for build cake

### ISSUE THREAD

**Issue by Eldadc** [cake-build/cake#2687]
Hi,

Is it possible to run build.cake from different directory and to point it to the solution directory ?
I want to maintain my scripts ( Jenkins file , build cake from different repo then my solution repo )
Is there a parameter that will apply for script task for working directory , i.e. solution directory

Thanks

**Comment by patriksvensson** [comment]
@Eldadc You could use something like this:

```C#
var working = Argument<string>("working");
Environment.WorkingDirectory = working ?? Environment.WorkingDirectory
```

**Comment by Eldadc** [comment]
Hi,

Thanks for your reply.
Where do I need to put 

Environment.WorkingDirectory = working ?? Environment.WorkingDirectory

Thanks

**Comment by patriksvensson** [comment]
@eldadc at the very start of your script.

**Comment by Eldadc** [comment]
Hi,

Can you please send an example , I am getting issue implementing it , error while compiling "...No definition for Environment ..."

Thanks

**Comment by devlead** [comment]
Try `Context.Environment.WorkingDirectory`
