### ISSUE TITLE
Consider adding some kind of "GetArguments()" alias, similar to the EnvironmentVariables() one

### ISSUE THREAD

**Issue by xforever1313** [cake-build/cake#2690]
Right now, there is a way to get all of the Environment Variables using the [EnvironmentVariables](https://cakebuild.net/api/Cake.Common/EnvironmentAliases/97336C76) alias.  It returns an IDictionary<string, string>.

However, there does not seem to be one to get all of the arguments (unless I am missing something, in which case I apologize).

If the alias is to be consistent with EnvironmentVariables() it should probably return a copy of a dictionary, not a direct reference to the underlying dictionary Cake uses.

**Example Use Case:**
The use case for this could be if one wants to call [CakeExecuteScript](https://cakebuild.net/api/Cake.Common.Tools.Cake/CakeAliases/5FCD85B6) and pass-through the current process's arguments to it (or append arguments of its own), there's no way to do this right now.

```C#
// Arguments() does not exist right now.
// To be consistent with EnvironmentVariables() it should probably a new dictionary
// that is safe to be modified, not a reference to Cake's underlying one.
IDictionary<string, string> currentArgs = Arguments();
currentArgs["additionalArg"] = "myOtherArg";

CakeSettings settings = new CakeSettings
{
    Arguments = currentArgs,
    EnvironmentVariables = EnvironmentVariables()
};

CakeExecuteScript( "somewhereElse/build.cake", settings );
```

**Comment by augustoproiete** [comment]
Related discussion https://github.com/cake-build/cake/discussions/3054

**Comment by sunshykin** [comment]
Tried to solve that issue with #3388
