### ISSUE TITLE
Missing GitHubActions Alias

### ISSUE THREAD

**Issue by RehanSaeed** [cake-build/cake#2691]
Following on from https://github.com/cake-build/cake/issues/2677:

> There's a alias property missing and should be added to [BuildSystemAliases.cs](https://github.com/cake-build/cake/blob/12c79ceb2e6a47387e014bb99cb4572b31a77b03/src/Cake.Common/Build/BuildSystemAliases.cs#L28)
@devlead

### What You Are Seeing?

This produces a compiler error:

```c#
GitHubActions.IsRunningOnGitHubActions
```

### What is Expected?

In theory this should work because I also use:

```c#
TFBuild.IsRunningOnAzurePipelinesHosted
AppVeyor.IsRunningOnAppVeyor
```

### What version of Cake are you using?

0.36.0

**Comment by devlead** [comment]
Alias property example
https://github.com/cake-build/cake/blob/12c79ceb2e6a47387e014bb99cb4572b31a77b03/src/Cake.Common/Build/BuildSystemAliases.cs#L64-L87

BuildSystem has an GitHubActions property
https://github.com/cake-build/cake/blob/12c79ceb2e6a47387e014bb99cb4572b31a77b03/src/Cake.Common/Build/BuildSystem.cs#L601-L613

Namespaces
https://github.com/cake-build/cake/blob/12c79ceb2e6a47387e014bb99cb4572b31a77b03/src/Cake.Common/Build/GitHubActions/GitHubActionsProvider.cs#L9

https://github.com/cake-build/cake/blob/12c79ceb2e6a47387e014bb99cb4572b31a77b03/src/Cake.Common/Build/GitHubActions/Data/GitHubActionsWorkflowInfo.cs#L7

Marking as up for grabs / good first issue.

**Comment by gitfool** [comment]
@RehanSaeed good catch. It was indeed an oversight due to me not using it that way.
