### ISSUE TITLE
Upgrade Cake Alias support for GitReleaseManager

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#2696]
With the release of version 0.10.x of GitReleaseManager, some new commands were created:

* discard
* open

And it would be good to have support for these commands via Cake Aliases.

In addition, a number of new base options were added which should also be supported via the base Settings class:

* Debug
* NoLogo
* Verbose

And finally, support for Username and Password authentication has been deprecated in this release of GitReleaseManager, and the Cake Aliases should also be updated to reflect this.

**Comment by gep13** [comment]
@admiringworm did I miss anything in the above?  Thanks!

**Comment by AdmiringWorm** [comment]
@gep13 nope, you got them all

**Comment by gep13** [comment]
@AdmiringWorm perfect!  Thanks for the sanity check! 😄
