### ISSUE TITLE
OctoCreateRelease needs example.

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#270]
[OctopusDeployAliases​.OctoCreateRelease](http://cakebuild.net/api/cake.common.tools.octopusdeploy/5d0a790a/df806e63) needs an example.

**Comment by Meberem** [comment]
I have used that command recently so I have added some documentation in a commit in my fork [here](https://github.com/Meberem/cake/commit/25716e0447a42ad9d11226b95806940228f59710) would this be useful to you?

**Comment by patriksvensson** [comment]
@Meberem That looks fine :smile: 
Would probably want to remove the `<packages>` part, but other than that it looks good to me.

**Comment by Meberem** [comment]
Ok not a problem, I included it as I forgot/got confused with which package to use but that is not relevant for this part of the documentation. 
Shall I remove that and send you a pull request?

**Comment by patriksvensson** [comment]
Yes. That would be great! :+1:

**Comment by gep13** [comment]
This has been taken care of here: https://github.com/cake-build/cake/issues/750
