### ISSUE TITLE
OpenCover is missing hideskipped setting

### ISSUE THREAD

**Issue by Roemer** [cake-build/cake#2703]
Opencover allows hiding skipped modules by providing a `hideskipped parameter. Would be great to add this.
See https://github.com/OpenCover/opencover/wiki/Usage#console-application-usage for details.

**Comment by adison88** [comment]
I can take this up as my 1st issue.

**Comment by adison88** [comment]
@devlead @Roemer Please review [PR](https://github.com/cake-build/cake/pull/2827)
