### ISSUE TITLE
Error: The assembly name is invalid

### ISSUE THREAD

**Issue by ShankarAnush** [cake-build/cake#2705]
![image](https://user-images.githubusercontent.com/35295991/73378838-8a062000-42c1-11ea-80f3-046531871a21.png)

I am trying to build cake scripts in Ubuntu. 
After installing the necessary packages, when I run ./build.sh I get the above error.
Could you please help me on this?

**Comment by devlead** [comment]
@ShankarAnush this is probably related to: https://github.com/cake-build/cake/issues/2695

**Comment by devlead** [comment]
Duplicate of  #2695
