### ISSUE TITLE
Add DotNetCore NuGet Push -SkipDuplicate Flag

### ISSUE THREAD

**Issue by Kemyke** [cake-build/cake#2732]
### What You Are Seeing?
nuget push added a new -SkipDuplicate flag. See [NuGet/Home#1630](https://github.com/NuGet/Home/issues/1630)

### What is Expected?
The `SkipDuplicate` flag should exist on `DotNetCoreNuGetPushSettings`.

**Comment by gitfool** [comment]
@Kemyke I also want this as a first class option. See pending PR #2716. 😉

**Comment by Kemyke** [comment]
Great, looks like what exactly i am looking for. But the PR has been already pending for weeks without any comment. Did you get any feedback what else they need to merge? Or you should ping the team on gitter, eg. It would be great to have these modifications in the next release. :)

**Comment by devlead** [comment]
@Kemyke unplanned breaking changes in VSCode and Azure DevOps kept us quite busy lately both sorted now though, we'll try to get to it as soon as possible, unfortunately, also the majority of the team is affected by COVID, working from home, conferences canceled, etc. so might take week so more before we're back on top of things. Until then [ArgumentCustomization](https://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/50AAB3A8) available for all tools is always an option to unblock with the current version of Cake.

**Comment by Kemyke** [comment]
No problem, we are also affected and sent the whole company to home office. 
Anyway, we can use the workaround as long as this is released.
Thanks!

**Comment by augustoproiete** [comment]
This has been resolved via #2716 and `SkipDuplicate` is available on Cake v0.38.4.

**Comment by devlead** [comment]
@augustoproiete correct, thanks👍
