### ISSUE TITLE
Extend XmlPeekSettings with FileShare.* option

### ISSUE THREAD

**Issue by Asemirski** [cake-build/cake#2745]
### What You Are Seeing?
Using xmlpeek from different builds at the same time causes "The process cannot access the file ecause it is being used by another process.

### What is Expected?
It is possible to work with file while cake xmlpeeks in there

### What version of Cake are you using?
0.37.0

### Are you running on a 32 or 64 bit system?
x64
### Are you running on a CI Server?  If so, which one?
Jenkins

### How Did You Get This To Happen? (Steps to Reproduce)
Run a large number of builds simultaneously.

**Comment by devlead** [comment]
Fixed by #2747
