### ISSUE TITLE
Globber performance

### ISSUE THREAD

**Issue by marcosnz** [cake-build/cake#275]
I am working with a largish repo and have found that the GetFiles method of the Globber is significantly slower than the MSBuild equivalent I am trying to replace..
If you take a look at [this Gist](https://gist.github.com/marcosnz/74285d2e7dd14048fb47) you will see that I am just getting a count of assembly info files. The MSBuild example does it in less than a second where as the cake version takes about a minute.

**Comment by patriksvensson** [comment]
I'm baking a PR that solves this. Will need more time to make sure it's stable enough.

**Comment by khellang** [comment]
Why not use something like [Shabse's Minimatch port](https://github.com/SLaks/Minimatch)? Dunno if it's very fast, but it's at least a nice start? I've submitted a PR to include a source package so you don't have to add an external dependency, https://github.com/SLaks/Minimatch/pull/4 :wink:
