### ISSUE TITLE
Can the .Net installation be remove from the GitHub actions workflow

### ISSUE THREAD

**Issue by SeanFarrow** [cake-build/cake#2751]
### Output Log

GIST LINK - Please create a gist and link to that gist here

OR

~~~sh
PLACE LOG CONTENT HERE
~~~

**Comment by SeanFarrow** [comment]
Given the GitHub actions virtual environment has been updated to support .net core Sdk 3.1.201, do we need to install it when building?
I'm happyto make hte change if required.

**Comment by augustoproiete** [comment]
(Moving to GitHub Discussions / Q&A)
