### ISSUE TITLE
Provide property to return parent directory on DirectoryPath

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#2763]
Currently getting the parent directory of a `DirectoryPath` requires some additional steps. Having a `DirectoryPath.Parent` property would be helpful.

**Comment by patriksvensson** [comment]
Sounds good, but should be a method unless we construct this at the point that the directory is created.

**Comment by LagunaElectric** [comment]
Hello! I'm new to this and would like to try tackling this issue :)

**Comment by LagunaElectric** [comment]
Wow that was fast!

**Comment by LagunaElectric** [comment]
Mind if I ask for directions to DirectoryPath declaration?

**Comment by augustoproiete** [comment]
Sounds good. Probably something like:

```csharp
public DirectoryPath GetParent()
{
    // ...
}
```
?

Don't forget to include unit tests in the PR! :wink: 
- https://github.com/cake-build/cake/blob/v1.1.0/src/Cake.Core.Tests/Unit/IO/DirectoryPathTests.cs
