### ISSUE TITLE
Improve Tool Discovery

### ISSUE THREAD

**Issue by Redth** [cake-build/cake#278]
By default right now most aliases that require external tools seem to look for the tool in `./tools/`, so the tools folder always relative to the executing script.  

While I understand the original intention the way to use cake is to install it in a given directory where you need it, I think it's desirable to have Cake (and its tools) optionally located in a central location on a system. For one, this would mean less duplication of executables (both cake and tools) and for complicated setups where there are cake scripts at various levels in a given directory tree, we wouldn't need to install cake in each level.

I think it's possible to allow discovery of tools beyond the `./tools/` folder without disrupting the behaviour when that folder actually exists.

I think the discovery process could go something like this:

1. Add a `-toolpath=` parameter to Cake for the user to specify the tool path
2. Look for tool in `./tools/` (exactly how it currently works)
3. Look in all the directories within the system `PATH` variable for the tool
4. On certain operating systems, some tools might be commonly placed in one location, look to see if it exists here (for example on Mac, nuget is available at `/usr/bin/nuget`)

**Comment by Redth** [comment]
For the last part, where a tool may have a specific location on a given OS, there should be some sort of `Func` exposed by the tool that can do the tool specific work of looking in a tool specific path for the tool.  This would only be invoked if the tool wasn't found in the other locations first.

**Comment by patriksvensson** [comment]
Note: PATH variable lookup implemented.

**Comment by SharpeRAD** [comment]
I second this :+1:

You can achieve shared a shared tools location by passing in the directory to the build script but it means you can't use the "#tools" directive :disappointed: 

```c#
var tools = Argument("tools", "./tools");

Setup(() =>
{
	//Executed BEFORE the first task.
	Information("Building version {0} of {1}.", semVersion, appName);
    
	NuGetInstall("NUnit.Runners", new NuGetInstallSettings
	{
		ExcludeVersion  = true,
		OutputDirectory = tools
    });
});

Task("Run-Unit-Tests")
    .IsDependentOn("Build")
    .Does(() =>
{
    CreateDirectory(testResultsDir);

    NUnit3("./src/**/*.Tests.dll", new NUnit3Settings
	{
        ToolPath = tools + "NUnit.Console/tools/nunit3-console.exe",
        Framework = "4.0",

        OutputFile = testResultsDir + "tests.xml",
        ErrorOutputFile = testResultsDir + "error.xml",
        Results = testResultsDir + "results.xml"
    });
});
```

What I was proposing in #647 solves the problem with environment variables :smile:

**Comment by gep13** [comment]
@Redth for information on how this can be achieved, have a look at the documentation here:

http://cakebuild.net/docs/fundamentals/default-configuration-values

Let us know if you have any questions.
