### ISSUE TITLE
0.38.0 introduces TFBuild obsolete warning for everyone not just users of property

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#2786]
In 0.38.0, everyone will get this wanting in 0.38.0, regardless if they're using it or not as it's a cached property it's invoked in the code gen.

```
 (2783,24): warning CS0618: 'BuildSystemAliases.TFBuild(ICakeContext)' is obsolete: 'Use AzurePipelines instead.'
````

**Comment by gep13** [comment]
Just ran a test locally, and confirmed that this is indeed an issue:

![image](https://user-images.githubusercontent.com/1271146/83338192-b787c800-a2b9-11ea-8626-dc4ee71d0f85.png)
