### ISSUE TITLE
build.ps1 and dotnet cake do not behave the same with the same build.cake file

### ISSUE THREAD

**Issue by StefanOssendorf** [cake-build/cake#2795]
### What You Are Seeing?
The new `dotnet cake` tool fails to run the build script where the `build.ps1` file works as expected.

### What is Expected?
Both ways of executing the `build.cake` file should be equivalent.

### What version of Cake are you using?
Tested with 0.38.1 and 0.38.1

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 10 latest updates

### How Did You Get This To Happen? (Steps to Reproduce)
[Minmal working example](https://github.com/StefanOssendorf/mwe-buildps1-vs-dotnet-cake-tool-not-equal)

build.cake content where the 2nd line causes the problem.
```
#addin nuget:?package=SimpleExec&version=6.2.0
#addin nuget:?package=Cake.Powershell&version=0.4.8

var target = Argument("target", "Default");

Task("Default")
    .Does(() =>
    {
        Information($"The script was executed!");
    });
    
RunTarget(target);
```

### Output Log

~~~sh
Analyzing C:/Github/mwe-buildps1-vs-dotnet-cake-tool-not-equal/build.cake...
Processing build script...
Installing addins...
The addin SimpleExec will reference SimpleExec.dll.
Error: Cake.Core.CakeException: Failed to install addin 'Cake.Powershell'.
   at Cake.Core.Scripting.ScriptProcessor.InstallAddins(IReadOnlyCollection`1 addins, DirectoryPath installPath) in C:\projects\cake\src\Cake.Core\Scripting\ScriptProcessor.cs:line 114
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments) in C:\projects\cake\src\Cake.Core\Scripting\ScriptRunner.cs:line 152
   at Cake.Commands.BuildCommand.Execute(CakeOptions options) in C:\projects\cake\src\Cake\Commands\BuildCommand.cs:line 41
   at Cake.CakeApplication.Run(CakeOptions options) in C:\projects\cake\src\Cake\CakeApplication.cs:line 45
   at Cake.Program.Main() in C:\projects\cake\src\Cake\Program.cs:line 81
~~~

**Comment by gep13** [comment]
@StefanOssendorf I believe I am right in saying that this is working as expected (at least from my point of view).  Let me try to explain...

If you run the default bootstrapper, which is located here:

https://github.com/cake-build/resources/blob/develop/build.ps1#L255

You will see that it is running Cake.exe which uses .Net Framework.

Invoking `dotnet cake` uses the .Net Core runtime.  As a result, although the cake script is exactly the same, they are running on a different runtime.

The Cake.PowerShell addin is only compiled to work on .Net Framework, or Mono, not on .Net Core.  As a result, you are seeing the error that you are seeing.

Currently, we don't have an official example build.ps1 which invokes the .Net Core version of Cake, but there are examples out there, including in Cake's own repository here: 

https://github.com/cake-build/cake/blob/develop/build.ps1

If you are looking to run Cake with .Net Core, I would suggest that you replace your current build.ps1 with the above.

However, doing this, will mean that you can't use Cake.PowerShell addin.

Does this make sense?

**Comment by gep13** [comment]
To know which add is work with which framework, you can have a look here:

https://github.com/cake-contrib/Home/blob/master/Audit_for_Cake_0.33.0.md

**Comment by StefanOssendorf** [comment]
@gep13  Thanks for this great explanation. Yeah that makes a lot of sense. Did not think about that possibility.
I'll try to get in touch with the Powershell author to update it to netstandard if possible. So I'll close this.
Thanks again!
