### ISSUE TITLE
Cake-tool errors are not properly reported in an azure pipeline

### ISSUE THREAD

**Issue by StefanOssendorf** [cake-build/cake#2808]
### What You Are Seeing?

Powershell returned an error instead of the actual error.
```
========================================
RaiseExceptionForPipelineError
========================================
dotnet.exe : An error occurred when executing task 'RaiseExceptionForPipelineError'.
At D:\a\1\s\build.ps1:5 char:5
+     & dotnet cake ./build/build.cake $args
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (An error occurr...PipelineError'.:String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
 
##[error]PowerShell exited with code '1'.
```
This is a minimal working example to see the error. Since I can't share the stuff from my work but the output and usage is identical.
[Azure Pipelines error log](https://sossendorf.visualstudio.com/Cake%20Azure%20Pipelines%20Error%20not%20propagated/_build/results?buildId=81&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=24311d03-63ec-5098-c8e5-7df09da2b6d4)
### What is Expected?
In the error above I am just doing an `throw new InvalidOperationException("Just an exception to see if error propagation is properly done.");` so I expect to see that an IOE exception was thrown with the message.

### What version of Cake are you using?
0.38.2

### Are you running on a 32 or 64 bit system?
64bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
Azure Pipelines on a hosted agent with windows-2019 image.

### How Did You Get This To Happen? (Steps to Reproduce)

MWE: https://github.com/StefanOssendorf/MWE-cake-errorPropagationInAzurePipelines

### Output Log

~~~sh
--------------------------------------------------------------------------------------
Tool 'cake.tool' (version '0.38.2') was restored. Available commands: dotnet-cake
Tool 'minver-cli' (version '2.3.0') was restored. Available commands: minver

Importing namespace Cake.Common.Tools.MSTest...
Importing namespace Cake.Common.Tools.NSIS...
Importing namespace Cake.Common.Tools.NuGet...
Importing namespace Cake.Common.Tools.NuGet.Add...
Importing namespace Cake.Common.Tools.NuGet.Delete...
Importing namespace Cake.Common.Tools.NuGet.Init...
Importing namespace Cake.Common.Tools.NuGet.Install...
Importing namespace Cake.Common.Tools.NuGet.List...
Importing namespace Cake.Common.Tools.NuGet.Pack...
Importing namespace Cake.Common.Tools.NuGet.Push...
Importing namespace Cake.Common.Tools.NuGet.Restore...
Importing namespace Cake.Common.Tools.NuGet.SetApiKey...
Importing namespace Cake.Common.Tools.NuGet.SetProxy...
Importing namespace Cake.Common.Tools.NuGet.Sources...
Importing namespace Cake.Common.Tools.NuGet.Update...
Importing namespace Cake.Common.Tools.NUnit...
Importing namespace Cake.Common.Tools.OctopusDeploy...
Importing namespace Cake.Common.Tools.OpenCover...
Importing namespace Cake.Common.Tools.ReportGenerator...
Importing namespace Cake.Common.Tools.ReportUnit...
Importing namespace Cake.Common.Tools.Roundhouse...
Importing namespace Cake.Common.Tools.SignTool...
Importing namespace Cake.Common.Tools.SpecFlow...
Importing namespace Cake.Common.Tools.SpecFlow.StepDefinitionReport...
Importing namespace Cake.Common.Tools.SpecFlow.TestExecutionReport...
Importing namespace Cake.Common.Tools.TextTransform...
Importing namespace Cake.Common.Tools.VSTest...
Importing namespace Cake.Common.Tools.VSWhere...
Importing namespace Cake.Common.Tools.VSWhere.All...
Importing namespace Cake.Common.Tools.VSWhere.Latest...
Importing namespace Cake.Common.Tools.VSWhere.Legacy...
Importing namespace Cake.Common.Tools.VSWhere.Product...
Importing namespace Cake.Common.Tools.WiX...
Importing namespace Cake.Common.Tools.WiX.Heat...
Importing namespace Cake.Common.Tools.XBuild...
Importing namespace Cake.Common.Tools.XUnit...
Importing namespace Cake.Common.Xml...
Importing namespace Cake.Compression...
Importing namespace Cake.Core...
Importing namespace Cake.Core.Diagnostics...
Importing namespace Cake.Core.IO...
Importing namespace Cake.Core.Scripting...
Importing namespace System...
Importing namespace System.Collections.Generic...
Importing namespace System.IO...
Importing namespace System.Linq...
Importing namespace System.Text...
Importing namespace System.Threading.Tasks...
Compiling build script...
D:/a/1/s/build/build.cake(73,13): warning CS0219: The variable 'ourLibrariesFeed' is assigned but its value is never used

========================================
RaiseExceptionForPipelineError
========================================
Executing task: RaiseExceptionForPipelineError
dotnet.exe : An error occurred when executing task 'RaiseExceptionForPipelineError'.
At D:\a\1\s\build.ps1:5 char:5
+     & dotnet cake ./build/build.cake $args
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (An error occurr...PipelineError'.:String) [], RemoteException
+ FullyQualifiedErrorId : NativeCommandError
 
##[error]PowerShell exited with code '1'.
Finishing: Execute Cake-Script

~~~

**Comment by StefanOssendorf** [comment]
Addition: This behavior only shows for a windows host agent. E.g. Ubuntu works as expected.

**Comment by devlead** [comment]
That does your Azure Pipelines Yaml look like?

**Comment by StefanOssendorf** [comment]
I am using the classic azure pipeline editor but it makes no difference.
This is a repo I've forked from someone from the gitter chat:
https://github.com/StefanOssendorf/cake-build-test-devops
The initial image was ubuntu which worked as expected (https://sossendorf.visualstudio.com/nilsa-cake-test-help/_build/results?buildId=82&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7dae026f-9e99-5d65-075e-3f7579577f94) and atfer that I changed the vm to windows which produced the already mentioned error output (https://sossendorf.visualstudio.com/nilsa-cake-test-help/_build/results?buildId=85&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=7dae026f-9e99-5d65-075e-3f7579577f94).
Same yaml-file except vm-image.

**Comment by devlead** [comment]
Well one difference is that Ubuntu is using a newer version of PowerShell, and Windows-latest and old version.

Setting `pwsh: true` seems to ensure consistency 

See this PR:
https://github.com/StefanOssendorf/cake-build-test-devops/pull/1
https://github.com/StefanOssendorf/cake-build-test-devops/pull/1/commits/7f5ad0049808a6c35661768edcdda777be82ac7a

**Comment by StefanOssendorf** [comment]
That fixes it. Thank you very much :-)
