### ISSUE TITLE
Add Support For Fixie

### ISSUE THREAD

**Issue by ChrisMissal** [cake-build/cake#281]
I'd like to see support added so I can use [Fixie](http://fixie.github.io/) as easily as I can the other test frameworks.

I don't mind working on this eventually, but if somebody else gets to it before me, I won't complain. :smile:

**Comment by patriksvensson** [comment]
Great idea. Fixie should definitely be supported. :+1:

**Comment by patriksvensson** [comment]
Merged :+1:
