### ISSUE TITLE
Cake uses wrong MSBuild verbosity parameter

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#282]
When using the extension method [MSBuildSettings.SetVerbosity(Verbosity.Verbose)](http://cakebuild.net/api/cake.common.tools.msbuild/949206fc/ba92223e), MSBuild is called with `/v:verbose` instead of `/v:detailed`.

```csharp
MSBuild("./Project.sln", settings =>
    settings.SetVerbosity(Verbosity.Verbose));
```

**Correct mapping should be:**

* Quiet => `quiet`
* Minimal => `minimal`
* Normal => `normal`
* Verbose => `detailed`
* Diagnostic => `diagnostic`

**Comment by ChrisMissal** [comment]
@patriksvensson Should this change keep the Cake enum, or should it define a new type to match MSBuild?

**Comment by patriksvensson** [comment]
@ChrisMissal No, I think it's OK to keep Cake's enum since they represent the same thing. At least for now :smile:

**Comment by ChrisMissal** [comment]
Ok, sounds good. That approach will also prevent a breaking change for existing scripts. :+1:

**Comment by patriksvensson** [comment]
@ChrisMissal Exactly :+1:
