### ISSUE TITLE
Add support of ReportGenerator global tool

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#2822]
At the minute, Cake support for ReportGenerator only includes the full .net framework version.  Similar to what has been done for GitVersion and GitReleaseManager, we should add support for running the global tool version as well.

**Comment by prochnowc** [comment]
@mholo65 Any chance to get a release with this improvement soon? ReportGenerator fails now on Azure DevOps hosted linux agents.

**Comment by mholo65** [comment]
v1.0.0 should be released soonish, but I can't promise an exact date. In the meantime I'd recommend pulling an pre-release version from our Azure Artifacts feed. https://dev.azure.com/cake-build/Cake/_packaging?_a=feed&feed=cake
