### ISSUE TITLE
Add option to ignore tool exit code

### ISSUE THREAD

**Issue by flcdrg** [cake-build/cake#2825]
The current default behaviour in `Tool.ProcessExitCode()` is to throw an exception if the exit code is non-zero.

There may be occasions where ignoring the exit code is preferred as additional processing is needed before the underlying error is handled. 

For example, when running unit tests with `dotnet test` (via `DotNetCoreTest`) in a CI pipeline, rather than failing immediately upon test failure, it might be that uploading the test results would be the way the pipeline recognises the failing tests and then fails the build.

As such, I think it would be useful to have a property in `Settings` that can be set to enable ignoring exit codes

**Comment by bagavan44** [comment]
Yes, it will be very much useful. Facing the issue with same problem. Whenever one of the test is failed then process stopped there it self.

**Comment by devlead** [comment]
Fixed by #2826
