### ISSUE TITLE
ParseAssemblyInfo does not detect lines with extra spaces

### ISSUE THREAD

**Issue by karlroyle** [cake-build/cake#2831]
Loss of AssemblyInfo data when reading from an AssemblyInfo with spaces at the end of lines (outside the quotes)

When parsing the AssemblyInfo files, a regular expression is used, which reads in the lines, such as InternalsVisibleTo()
If a line has a space at the end, but outside the quotes, that line is not read in (and subsequently lost on re-write).

This is on Window 10, Cake 0.38, 64 bit.

I suspect that it just needs an adjustment to the Regex in order to identify lines with additional whitespace.

![image](https://user-images.githubusercontent.com/64926141/87804643-109cc280-c84c-11ea-8613-3f1ea7f62ba5.png)

**Comment by daveMueller** [comment]
I'm working on this.

**Comment by daveMueller** [comment]
@karlroyle As you suspected it just needed some adaptions to the regex. In the referenced PR I also extended the unit tests to cover additional whitespaces.

**Comment by karlroyle** [comment]
That's great.  Many thanks for your help Dave.
