### ISSUE TITLE
Add new GitHub Actions URL environment variables

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#2847]
See [default environment variables](https://docs.github.com/en/actions/configuring-and-managing-workflows/using-environment-variables#default-environment-variables):
* `GITHUB_API_URL`. Returns the API URL. For example: https://api.github.com.
* `GITHUB_GRAPHQL_URL`. Returns the GraphQL API URL. For example: https://api.github.com/graphql.
* `GITHUB_SERVER_URL`. Returns the URL of the GitHub server. For example: https://github.com.

**Comment by patriksvensson** [comment]
Sounds like a good idea! 👍
