### ISSUE TITLE
Add Support For Roundhouse

### ISSUE THREAD

**Issue by ChrisMissal** [cake-build/cake#285]
As an avid user of [Roundhouse](https://github.com/chucknorris/roundhouse) for database migrations, I'd like to see it supported as a Cake tool.

**Comment by gep13** [comment]
:+1:  @ferventcoder might be interested in hearing about this :smile_cat:

**Comment by ferventcoder** [comment]
:+1:

**Comment by ferventcoder** [comment]
This could possibly be what UppercuT uses for it's next engine, provided it runs on mono.

**Comment by RichiCoder1** [comment]
It's dated at this point, but I'd imagine that support would probably be best added through an addon like https://github.com/RichiCoder1/Cake.AliaSql.

@ferventcoder I'd have to double check with @patriksvensson, but Mono support was recently added and is being stabilized and expanded. Would probably love testers and users :)

**Comment by ferventcoder** [comment]
UC supports a ton of different tools though - how is the plugin engine for this @patriksvensson ?

**Comment by gep13** [comment]
>@ferventcoder said...
This could possibly be what UppercuT uses for it's next engine, provided it runs on mono.

The grunt work has been done here:
https://github.com/cake-build/cake/pull/280

I have been thinking about using it on a couple projects, just need to get the cycles...

**Comment by ferventcoder** [comment]
Perhaps I can get @drusellers excited about cake?

**Comment by RichiCoder1** [comment]
@ferventcoder Cake has the notions of [Aliases](http://cakebuild.net/docs/fundamentals/aliases), which usually provide an excellent starting point for third party tools an extensions. Cake itself uses them to implement most of it support, as most of Cake.Common is simply commonly used aliases.

The more the merrier :D

@gep13 Been chewing on introducing Cake to Gui for a while. Already use it extensively at my company. About the only problem we've had is poor editing experience and it's something I've been bugging the omnisharp team about.

**Comment by gep13** [comment]
>@RichiCoder1 said...
Been chewing on introducing Cake to Gui for a while

I have been thinking the same.  Will be sorry to see psake leave, it has served me very well!

**Comment by patriksvensson** [comment]
@ferventcoder Plugins is mainly supported via script aliases (like @RichiCoder1 already said). There is also some pre-processor directives that can be used to import tools and assemblies directly from NuGet. Now when I think about it, I should probably add more documentation around extensibility :smile: 

@gep13 Come to the dark side, we have :cake:

**Comment by gep13** [comment]
Ha ha, like I say, I am very tempted.  From what I have seen of Cake, there is nothing in the ChocolateyGUI build script that it wouldn't be able to do, it is just a case of sitting down and making the switch, or even better, getting @RichiCoder1 to make the switch, and looking at what he did :-P

**Comment by patriksvensson** [comment]
@gep13 If @RichiCoder1 doesn't have time, I'll do it myself. &#42;rolling up shirt sleeves&#42;

**Comment by RichiCoder1** [comment]
I actually converted Choco's scripts once, but ended up reverting because I was afraid for maintainability and churn. Would be happy to do it again :)

**Comment by patriksvensson** [comment]
@RichiCoder1 Yay! :smile:

**Comment by gep13** [comment]
Happy to review changes from either of you :smile_cat:

**Comment by ferventcoder** [comment]
I'm lurking - maybe at some point I might spike flipping the bits on uppercut from nant to cake. If anyone wants to play - it might be an insane amount of work but it could identify gaps of where cake can go. :)

**Comment by ChrisMissal** [comment]
I would imagine this will be implemented similar (basically the same) as the other test runner tools are implemented. I took a similar approach when adding the original RoundhouseHelper in FAKE. Is that a correct assumption @patriksvensson?

**Comment by patriksvensson** [comment]
@ChrisMissal I don't know how Roundhouse works, but that is a correct assumption :smile: I would prefer to keep the helper implementations as similar as possible.

**Comment by ChrisMissal** [comment]
Roundhouse can be used via console app or a class library. My recommendation is to use the console app just like I did with Fixie last week. Since this is all fresh in my mind, I can get started on it in the next day or two.

**Comment by patriksvensson** [comment]
@ChrisMissal Yes, that is probably the best way to go since we want to keep dependencies to zero in Cake.Common and Cake.Core. Great :+1:

**Comment by ferventcoder** [comment]
:+1:

**Comment by patriksvensson** [comment]
Merged! :smile:
