### ISSUE TITLE
Terminal output colours

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#2852]
I'm using [Windows Terminal](https://github.com/microsoft/terminal) with [PowerShell 7](https://github.com/PowerShell/PowerShell), which normally has a black background, but I've configured it to use the now classic blue background:

![image](https://user-images.githubusercontent.com/750121/92587981-7fe2e000-f2ec-11ea-889e-5b3591ca7251.png)

The text with black background looks a little jarring. Are the terminal output colours looking as expected / intended?

**Comment by patriksvensson** [comment]
@gitfool I've also noticed this. Will take a look at it.

**Comment by gitfool** [comment]
@pascalberger could this issue be added to the [`v1.0.0`](https://github.com/cake-build/cake/milestone/55) milestone?

**Comment by pascalberger** [comment]
@gitfool We currently only add issues which are blocking the release in 1.0.0 since we really want to get it out. I would not classify this not as blocking. If we get a PR in time we can add, but otherwise probably in a 1.0.0 bugfix release. I added it  therefore to the 1.1.0 milestone.
