### ISSUE TITLE
Fix error output in 1.0 preview

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2861]
Error output looks strange in some cases:

![image](https://user-images.githubusercontent.com/357872/93939125-9a747a80-fd2a-11ea-8a96-ceec93df694a.png)

**Comment by devlead** [comment]
For reference, this is how it used to look
```
PATH_TO_SCRIPTbuild.cake:0: Could not find script 'PATH_TO_SCRIPTbuild.cake'.
Error: Errors occurred while analyzing script.
```
this is how it looks in develop now
```

Error: Bootstrapping failed for 'PATH_TO_SCRIPTbuild.cake'.
build.cake, line #0: Could not find script
'PATH_TO_SCRIPTbuild.cake'.
```

@cake-build/cake-team How do we want it do look?

**Comment by patriksvensson** [comment]
@devlead Going to add an error handler in the CLI lib so we can control this ourselves.
