### ISSUE TITLE
Add support for GitHub Action workflow commands

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#2863]
### What You Are Seeing?

The [IGitHubActionsProvider](https://cakebuild.net/api/Cake.Common.Build.GitHubActions/IGitHubActionsProvider/) currently gives access to some environment values.

### What is Expected?

It should also provide [Workflow commands](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions)

### What version of Cake are you using?

0.38.5

### Are you running on a 32 or 64 bit system?

64 bit

### What environment are you running on?  Windows? Linux? Mac?

N/A

### Are you running on a CI Server?  If so, which one?

GitHub Actions

### How Did You Get This To Happen? (Steps to Reproduce)

N/A

### Output Log

N/A

**Comment by devlead** [comment]
Is this related to #2609?

**Comment by pascalberger** [comment]
Yes. 

The question is what the scope of #2609 is? Part is already done in [IGitHubActionsProvider](https://cakebuild.net/api/Cake.Common.Build.GitHubActions/IGitHubActionsProvider/) (access to environment variables), another with the Cake Action, support of workflow commands is another part where this issues overlaps with #2609, and having additional helpers for stuff like uploading artifacts, which is not supported by workflow commands is the third part.
 
Wouldn't it be better to close #2609 and create individual issues for the remaining issues instead?

**Comment by ecampidoglio** [comment]
I started working on #2609 already and I was actually thinking about implementing this, as well.

Adding support for interacting with GitHub Actions could still be tracked in #2609, but I'll create separate PRs for each area (environment, commands etc). Would that be fine or would you rather track them as individual issues?

**Comment by devlead** [comment]
As we use issues for or release notes, if it's separate features enough to warrant multiple PRs, then I think we should split into multiple issues.

**Comment by ecampidoglio** [comment]
The way I see it, adding complete support for interacting with GitHub Actions is one feature. But I'm fine with splitting it up, if you prefer.

**Comment by pascalberger** [comment]
The confusing thing is, that part of it already has shipped with current version of Cake and remaining parts probably might ship in different versions. Therefore I'm with @devlead on this, that separate issues make sense in this case, since we're using them for release notes.

**Comment by ecampidoglio** [comment]
Since I'm already working on #2609, I'll take on this one, as well.
