### ISSUE TITLE
Add helpers for adding multiple strings to ProcessArgumentBuilder

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#2870]
[`ProcessArgumentBuilder`](https://github.com/cake-build/cake/blob/7ca5a28479cc7b7deb9a8e02ca495397c344f8e6/src/Cake.Core/IO/ProcessArgumentBuilder.cs#L16) has a [FromString](https://github.com/cake-build/cake/blob/7ca5a28479cc7b7deb9a8e02ca495397c344f8e6/src/Cake.Core/IO/ProcessArgumentBuilder.cs#L119) helper and implicit conversion [operator](https://github.com/cake-build/cake/blob/7ca5a28479cc7b7deb9a8e02ca495397c344f8e6/src/Cake.Core/IO/ProcessArgumentBuilder.cs#L109) that makes it trivial to work with a _single_ string but has no helpers for another common case of adding _multiple_ strings, assuming they should be handled homogeneously - either all naked or all quoted. Also, the single string case could use a helper that quotes its argument too, so overall I propose the following additional helpers:
* `FromStringQuoted`
* `FromStrings`
* `FromStringsQuoted`
* `ToProcessArguments` (extension)

**Comment by gitfool** [comment]
Example usage in [Cake.Dungeon/scripts/tasks.cake](https://github.com/gitfool/Cake.Dungeon/blob/81a9064155946870724e0fd0036c832b178872f7/scripts/tasks.cake#L128) where [`Build.ToolSettings.UnitTestRunSettings`](https://github.com/gitfool/Cake.Dungeon/blob/81a9064155946870724e0fd0036c832b178872f7/scripts/toolsettings.cake#L73) is a simple `string[]`.

@pascalberger could this issue be added to the [`v1.0.0`](https://github.com/cake-build/cake/milestone/55) milestone?

**Comment by pascalberger** [comment]
Added to 1.0.0 milestone since we have an open PR
