### ISSUE TITLE
(Frosting) IFrostingContext should not inherit ICakeContext

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2891]
Perhaps add the `ICakeContext` as a property on `IFrostingContext`?
Would give better intellisense and it would be easier to discover things defined in lifetimes.

**Comment by gep13** [comment]
@patriksvensson did you decide against this?  Can you provide some information here?

**Comment by patriksvensson** [comment]
@gep13 Yes, it's a bad idea that really doesn't bring any value + it will require too much work.
