### ISSUE TITLE
(Frosting) Align command line parsing with Cake

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2893]
That means that arguments should be passed in the following format:

`dotnet cake --verbosity diagnostic --target default`

Once [System.CommandLine](https://github.com/dotnet/corefxlab/tree/master/src/System.CommandLine) is publicly available, we should switch to that one.

**Comment by patriksvensson** [comment]
Duplicate of #2886?

**Comment by devlead** [comment]
@patriksvensson yes can probably be closed in favor of #2886

**Comment by pascalberger** [comment]
Closing as duplicate of https://github.com/cake-build/cake/issues/2886
