### ISSUE TITLE
(Frosting) Tool installer should respect configuration

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#2904]
Frosting should support [configuration](https://cakebuild.net/docs/running-builds/configuration/set-configuration-values).

**Comment by dieterv** [comment]
@gep13 Frosting uses an internal `ToolInstaller` which does not respect the [tools path configuration option](https://cakebuild.net/docs/running-builds/configuration/default-configuration-values#tools-path).
Instead it is currently hardcoded to place tools into `_environment.WorkingDirectory.Combine("tools").MakeAbsolute(_environment)` which usually ends up being somthing like `project-root/tools/`.

[Something like this](https://github.com/dieterv/cake/commit/53b244fbad5d7c7112b91710103a683e72b27cb0) might be a first step to solve this. I did notice that `Cake.Core.Constants` is not accessible though and have no idea what would be preferred, making the constants public or duplicating them in the Cake.Frosting project somewhere?

Note that this would also require the `NuGetModule` changes from the `release/1.0.0` branch, commit daf0142d8a18a52c8c29e05c387f92239a7c94c5 I think, to be actually useful. Without that, we're stuck creating our own `NuGetModule` in our `Program.Configure` using an emtpy `CakeConfiguration` object for now, as mentioned [here](https://github.com/cake-build/cake/discussions/2931).

**Comment by patriksvensson** [comment]
@dieterv This has been fixed in #2946 which will be merged shortly.

**Comment by devlead** [comment]
Fixed by #2946

**Comment by dieterv** [comment]
@patriksvensson upgraded to 1.0.0-rc0002 and it looks like Frosting does not yet respect the settings from the [Paths] section of my cake.config file. Digging a bit deeper and it looks like the internal ToolInstaller still uses a hardcoded `_environment.WorkingDirectory.Combine("tools").MakeAbsolute(_environment);` path, see
https://github.com/cake-build/cake/blob/main/src/Cake.Frosting/Internal/ToolInstaller.cs#L30

Additionally, it no longer seems to take the working directory change into account as configured on the CakeHost instance as was the case in rc0001.
```
        // Create and run the host.
        return new CakeHost()
            .UseWorkingDirectory("../..")
            .UseContext<Context>()
            .UseLifetime<Lifetime>()
            .Run(args);
```

**Comment by pascalberger** [comment]
> Additionally, it no longer seems to take the working directory change into account as configured on the CakeHost instance as was the case in rc0001.

@dieterv Do you have an example where working directory fails? I just tried with a following simple example with the build script in a `build` folder and the solution in a `src` folder and setting working directory: https://github.com/pascalberger/cake-frosting-example

**Comment by dieterv** [comment]
> @dieterv Do you have an example where working directory fails? I just tried with a following simple example with the build script in a `build` folder and the solution in a `src` folder and setting working directory: https://github.com/pascalberger/cake-frosting-example

@pascalberger sure, I've modified your example to show that ToolInstaller does not use the working directory that was configured on CakeHost, see https://github.com/dieterv/cake-frosting-example/commit/76e6518939fd3a75777d334fd6500a6d374b2ee3

Now, interesting as this is, the [Paths][Tools] setting from the cake.config file should be used instead, when available, which is not the case unfortunately.

**Comment by augustoproiete** [comment]
Closing as resolved by #3048. Added to 1.0.0-rc0003 milestone

**Comment by pascalberger** [comment]
> @dieterv wrote:
> @pascalberger sure, I've modified your example to show that ToolInstaller does not use the working directory that was configured on CakeHost, see [dieterv/cake-frosting-example@76e6518](https://github.com/dieterv/cake-frosting-example/commit/76e6518939fd3a75777d334fd6500a6d374b2ee3)

We created https://github.com/cake-build/cake/issues/3058 for tracking this.

> Now, interesting as this is, the [Paths][Tools] setting from the cake.config file should be used instead, when available, which is not the case unfortunately.

`cake.config` is currently not supported in Frosting. We updated documentation to mention this: https://cakebuild.net/docs/running-builds/configuration/set-configuration-values.

We don't want to go with a quick implementation to add support for reading configuration from `cake.config` in Frosting, but instead evaluate first whats the best way for configuration in Frosting. Beside technical reasons, `cake.config` also comes with a lot of configuration settings which don't make sense in the context of Frosting.

**Comment by gep13** [comment]
@pascalberger to be fair... The Configuration system can handle *.ini files, so there is no reason that we "couldn't" also consume the values in the `cake.config` file, once we switch to use the configuration system.

https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/?view=aspnetcore-3.1#file-configuration-provider

**Comment by pascalberger** [comment]
> @pascalberger to be fair... The Configuration system can handle *.ini files, so there is no reason that we "couldn't" also consume the values in the `cake.config` file, once we switch to use the configuration system.

Sure, but keeps the problem that most of current settings don't make sense for Frosting:

- CAKE_NUGET_LOADDEPENDENCIES
- CAKE_PATHS_ADDINS
- CAKE_NUGET_USEINPROCESSCLIENT
- CAKE_PATHS_MODULES
- CAKE_NUGET_CONFIGFILE
- CAKE_NUGET_SOURCE

Leaving these settings which can make sense in Frosting:

- CAKE_SETTINGS_SHOWPROCESSCOMMANDLINE
- CAKE_SETTINGS_SKIPVERIFICATION
- CAKE_PATHS_TOOLS

**Comment by gep13** [comment]
Frosting could just ignore them though, right? And only use the ones that it needs.

**Comment by devlead** [comment]
I've submitted #3059 as a proposed fix which support both config via cake.config/environment variables/args and a UseToolPath method in frosting.

**Comment by devlead** [comment]
> Sure, but keeps the problem that most of current settings don't make sense for Frosting:
>     * CAKE_NUGET_LOADDEPENDENCIES
>     * CAKE_PATHS_ADDINS
>     * CAKE_NUGET_USEINPROCESSCLIENT
>     * CAKE_PATHS_MODULES
>     * CAKE_NUGET_CONFIGFILE
>     * CAKE_NUGET_SOURCE
 
At least the `CAKE_NUGET_*` ones are used in Frosting though as it uses Cake.NuGet now.

**Comment by pascalberger** [comment]
> > Sure, but keeps the problem that most of current settings don't make sense for Frosting:
> > * CAKE_NUGET_LOADDEPENDENCIES
> > * CAKE_PATHS_ADDINS
> > * CAKE_NUGET_USEINPROCESSCLIENT
> > * CAKE_PATHS_MODULES
> > * CAKE_NUGET_CONFIGFILE
> > * CAKE_NUGET_SOURCE
> 
> At least the `CAKE_NUGET_*` ones are used in Frosting though as it uses Cake.NuGet now.

But only for tools and not for addins and modules which are added through PackageReferences.

**Comment by dieterv** [comment]
@pascalberger wrote:
> `cake.config` is currently not supported in Frosting. We updated documentation to mention this: https://cakebuild.net/docs/running-builds/configuration/set-configuration-values.
> 
> But 1.0.0-rc003 will add a `SetToolPath` method on the Cake host which can be used to set the tool path.

Fair enough, my projects where migrated from older build.cake files.
Guess I just assumed settings in the cake.config files would be used.
Thanks for updating the docs, that will surely help people migrating in the future!

Ah, yes, `SetToolPath` method would be great and allow us to remove our config files altogether, thank you 🙏

**Comment by gep13** [comment]
>@dieterv said...
Fair enough, my projects where migrated from older build.cake files.
Guess I just assumed settings in the cake.config files would be used.

This is the really the scenario that I was thinking about when I said:

> Frosting could just ignore them though, right? And only use the ones that it needs.

Folks that are moving from Cake Scripting to Frosting would expect that any existing configuration to be applied, where it makes sense.  That is why I think going forward Frosting should recognise if there is a `cake.config` file, and take out what is useful and ignore the rest.

**Comment by devlead** [comment]
> But only for tools and not for addins and modules which are added through PackageReferences.

I was just correcting the fact that they didn't make sense at all. There're code-paths that're used in `release/1.0.0` branch.

So correct list configuration used by Forsting is:

- SETTINGS_SHOWPROCESSCOMMANDLINE
- SETTINGS_NOMONOCOERSION *<-- needs to be documented*
- PATHS_TOOLS
- NUGET_LOADDEPENDENCIES
- NUGET_USEINPROCESSCLIENT
- NUGET_CONFIGFILE
- NUGET_SOURCE

+ any addin/module that potentially uses `ICakeConfiguration`.

Not used by frosting today
- SETTINGS_SKIPVERIFICATION
- PATHS_ADDINS
- PATHS_MODULES

All above can already be configured with Frosting in  `release/1.0.0` using ` IServiceCollection UseCakeSetting(this IServiceCollection services, string key, string value)`, just not aligned with Cake/Cake.Tool/Cake.CoreCLR, which allows things to be configured through command-line, environment variables, and config file.


> But 1.0.0-rc003 will add a SetToolPath method on the Cake host which can be used to set the tool path.

#3059 adds an `UseToolPath(this IServiceCollection services, DirectoryPath toolPath)` which namping more aligned with rest of frosting extensions IMHO
