### ISSUE TITLE
Incorrect link for ReSharper's Open Source webpage in Cake readme

### ISSUE THREAD

**Issue by MrCull** [cake-build/cake#2918]
### What You Are Seeing?
The link on the Cake main Readme page for JetBrains "Open Source License" is pointing to: https://www.jetbrains.com/community/user-groups/#section=open-source 

The page this resolves to is titled "User Groups" and this is not the intended page.

### What is Expected?
The correct link should be: https://www.jetbrains.com/community/opensource/#support

That page is titled "Open Source Licenses" and is the intended.

(Assuming the link was once correct and the website has been restructured)

**Comment by devlead** [comment]
Fixed by #2919
