### ISSUE TITLE
Increase potential breaking change property

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#2930]
@cake-build/cake-team shouldn't this be `1.0.0`?

https://github.com/cake-build/cake/blob/a719007789de9a0fac884a5634e0a31098972ef0/src/Cake.Core/Constants.cs#L11-L12

**Comment by patriksvensson** [comment]
Yes I think it should!

**Comment by mholo65** [comment]
Yes

**Comment by devlead** [comment]
Fixed by #2940
