### ISSUE TITLE
Add dotnet test --blame Flag to DotNetCoreTestSettings

### ISSUE THREAD

**Issue by RehanSaeed** [cake-build/cake#2932]
The `dotnet test` command has a `--blame` flag that is missing from `DotNetCoreTestSettings`. This should be added as it is very usefule for when the test process crashes. I turn it on on in all my CI test runs. Here is the documentation for the flag:

```
--blame

Run the tests in blame mode. This option is helpful in isolating a problematic test causing the test host to crash.
Outputs a 'Sequence.xml' file in the current directory that captures the order of execution of test before the crash.
```

**Comment by Marusyk** [comment]
I would prepare PR for this if nobody minds

**Comment by gep13** [comment]
@Marusyk no objections here, thanks for your help with this!
