### ISSUE TITLE
Add Task Descriptions to Frosting

### ISSUE THREAD

**Issue by pitermarx** [cake-build/cake#2935]
Cake frosting has a TaskName Attribute but no Description.

**Comment by jakubsuchybio** [comment]
Hi, I can already see `TaskDescriptionAttribute` in `Cake.Frosting`
I think this can be closed.
![image](https://user-images.githubusercontent.com/6567287/116897241-54bf4f00-ac35-11eb-82a2-94266e650d59.png)

**Comment by patriksvensson** [comment]
@jakubsuchybio Correct. This has been added since the issue was opened.
Closing the issue.
