### ISSUE TITLE
Error NU1202 installing tool in .NET 5 project

### ISSUE THREAD

**Issue by suleyth** [cake-build/cake#2944]
Hello! I believe this is a typo issue somewhere in the prerelease.

### What are you seeing?
I tried to install the Cake tool in a .NET 5 project (with `<TargetFramework>net5.0</TargetFramework>`) and I get this error:
```
error NU1202: Package Cake.Tool 1.0.0-rc0001 is not compatible with net50 (.NETFramework,Version=v5.0) / any. Package Cake.Tool 1.0.0-rc0001 supports:
error NU1202:   - net5.0 (.NETCoreApp,Version=v5.0) / any
error NU1202:   - netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
error NU1202:   - netcoreapp3.0 (.NETCoreApp,Version=v3.0) / any
The tool package could not be restored.
Tool 'cake.tool' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

For more reasons, including package naming enforcement, visit https://aka.ms/failure-installing-tool
```
### What is expected?
The Cake tool should be installed correctly.
### What version of Cake are you using?
Prerelease `1.0.0-rc0001`.
### Are you running on a 32 or 64 bit system?
64 bit
### What environment are you running on?  Windows? Linux? Mac?
Windows
### Are you running on a CI Server?  If so, which one?
No, this is just a local project
### How did you get this to happen? (Steps to reproduce)
This is reproducible in a very simple way, at least on my machine. With the latest .NET 5 SDK installed, run:
```
dotnet new console -o TestThing
cd .\TestThing\
dotnet new tool-manifest
dotnet tool install Cake.Tool --version 1.0.0-rc0001
```

And you get the error.
### Output Log
None!

**Comment by pascalberger** [comment]
I tried to reproduce it with .NET 5.0 SDK 5.0.100 which works fine. What version of .NET SDK do you have installed? Are other .NET tools working?

**Comment by suleyth** [comment]
I have exactly the same version, only `.NET Core 3.1.402` installed too. Err, this is probably my issue then, since other tools have the same problem for me, and you say it works fine. Sorry for the bother! I'll close this and post if I find a solution.

**Comment by pascalberger** [comment]
> I have exactly the same version, only `.NET Core 3.1.402` installed too. 

This shouldn't be an issue, I also have `3.1.302` and `3.1.401` installed in parallel. Seems like something with your installation is not fine if other tools are also not working.

**Comment by devlead** [comment]
Could be a NuGet cache being corrupt issue

Try
`dotnet nuget locals all --clear`

**Comment by suleyth** [comment]
I just found out! It's an environment variable issue. I set `MSBuildSDKsPath` to `C:\Program Files\dotnet\sdk\5.0.100\Sdks` and everything went back to working normally. It's always a pain switching .NET versions, hm...
