### ISSUE TITLE
Allow setting MSBuild target via MSBuildSettings using a string

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#2953]
Currently when calling the `MSBuild` alias with an `MSBuildSettings`, we need to set the target using the `WithTarget` extension method.

```
MSBuild("./my-app.sln", new MSBuildSettings
{
    Configuration = "Release",
    ToolVersion = MSBuildToolVersion.VS2019,
}.WithTarget("Build")); // <<<###
```

It would be nice if we could use a property, with a string, which would make it more natural when using properties for everything else:

```
MSBuild("./my-app.sln", new MSBuildSettings
{
    Target = "Build",  // <<<###
    Configuration = "Release",
    ToolVersion = MSBuildToolVersion.VS2019,
});
```

This property should also understand semicolons as separator for multiple targets and call `Targets.Add` accordingly.

```
MSBuild("./my-app.sln", new MSBuildSettings
{
    Target = "Clean;Build",  // <<<###
    Configuration = "Release",
    ToolVersion = MSBuildToolVersion.VS2019,
});
```

### What version of Cake are you using?
1.0.0-rc0001

### Would you be willing to send a PR?
Yes!

**Comment by ManasviGoyal** [comment]
can you help me get started? @augustoproiete

**Comment by augustoproiete** [comment]
@ManasviGoyal In [`MSBuildSettingsExtensions`](https://github.com/cake-build/cake/blob/v1.1.0/src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs#L23) you can see how the `WithTarget` method works today, and in [`MSBuildSettings`](https://github.com/cake-build/cake/blob/v1.1.0/src/Cake.Common/Tools/MSBuild/MSBuildSettings.cs#L29) you can see that `Targets` is a read-only property of type `ISet<string>`.

The way I probably would approach this would be:

- Introduce a new `MSBuildTarget` type that implements `ISet<string>` to represent a collection of targets and maintain compatibility with existing Cake scripts that might inspect the `Targets` property
- Modify the `Targets` property of `MSBuildSettings` to use this new `MSBuildTarget` type
- Modify the `Targets` property of `MSBuildSettings` to be read/write (i.e. add a setter)
- Implement an implicit string operator on `MSBuildTarget` that can parse strings delimited by `;`
- Write unit tests for all the above
- Write integration tests to make sure the conversion operator works

Hope that helps!

**Comment by MariaSolOs** [comment]
@augustoproiete I'm preparing a PR to address this, but when running the tests in `Cake.Common.Tests` I get a bunch of `Code should not contain trailing whitespace` errors :( 
The weird thing is that all of these refer to lines with documentation comments... I would appreciate some insight on how to fix this! (see my implementation [here](https://github.com/MariaSolOs/cake/blob/string-targets/src/Cake.Common/Tools/MSBuild/MSBuildTarget.cs))

**Comment by augustoproiete** [comment]
@MariaSolOs It's exactly what the error message says. Your documentation comments have trailing spaces on them that should be removed.

e.g.
![image](https://user-images.githubusercontent.com/177608/132276372-cdb6b6ce-5aee-41ed-a6bd-488e00ce3567.png)

**Comment by MariaSolOs** [comment]
@augustoproiete thank you! 
What about `Constructor summary documentation should begin with standard text`? What's the standard text? I've been trying to find a reference for it in the contribution and documentation docs...

**Comment by augustoproiete** [comment]
@MariaSolOs https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1642.md

**Comment by MariaSolOs** [comment]
Thank you @augustoproiete! I apologize for all the newbie questions.

**Comment by MariaSolOs** [comment]
Okay now I'm not getting any errors in the code that I wrote, but when building I encounter the following:
![image](https://user-images.githubusercontent.com/62502207/132393860-4591be78-7c16-4c5c-ba73-edc61b738a2e.png)
I'm more than happy to submit a separate PR that addresses this ([it seems like the tests are following a deprecated practice](https://xunit.net/xunit.analyzers/rules/xUnit2017)).

**Comment by augustoproiete** [comment]
Do these warnings also appear in the `develop` branch? If yes, then it's not something you have to worry about for this particular PR - though we'd welcome a separate PR in the future to improve that, of course.

If these warnings only appear in your new branch, it probably means that something in your code requires the test to be adapted - the test might not even be valid anymore as-is.

**Comment by MariaSolOs** [comment]
Right, that makes a lot of sense. 
Thank you for your help!

**Comment by sbwaggoner** [comment]
Going to give this is a shot, assuming it's not yet been resolved.
