### ISSUE TITLE
Add Build Start Date & Time to TeamCity build information

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#2955]
TeamCity provides additional information about the build through an officially supported plugin called [Groovy plug](https://confluence.jetbrains.com/display/TW/Groovy+plug). After installing this plugin a few environment variables become automatically available on every build, including the ones below:

| Environment Variable | Format | Example |
| --- | --- | --- | 
| `BUILD_START_DATE` | yyyyMMdd | 20201123 |
| `BUILD_START_TIME` | HHmmss | 145129 |

Why JetBrains decided to have this as a separate plugin as opposed to having it out-of-the-box beats me :shrug:, but anyway, I suggest we add a new property to [`TeamCityBuildInfo`](https://github.com/cake-build/cake/blob/a0f142af2dfbf18eecc240789529da428cb0d82a/src/Cake.Common/Build/TeamCity/Data/TeamCityBuildInfo.cs) of type `DateTimeOffset?` providing the value of these two environment variables combined if they are available (otherwise `null`).

Knowing the exact date/time of when the build started in TeamCity is useful in scenarios where the date/time is used as part of the version number of build artifacts and must be consistent across different build steps.

The workaround today is to read the environment variables yourself in the Cake script and parse them, thus adding it to `TeamCityBuildInfo` is just for convenience.

### What version of Cake are you using?
1.0.0-rc0001

### Would you be willing to send a PR?
Yes!

**Comment by pascalberger** [comment]
@augustoproiete Sounds like a useful enhancement
