### ISSUE TITLE
Wrong Cake version in build.config

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#2956]
### What You Are Seeing?
When creating a new Frosting project from a template a `build.config` file is included in the bootstrapping scripts, based on the [build.config file used to build Cake](https://github.com/cake-build/cake/blob/develop/build.config).

### What is Expected?
Cake version in the generated `build.config` should match the version of the template (e.g. for Cake.Frosting template 1.0 it should use Cake version 1.0)

### What version of Cake are you using?
1.0 RC1

### Are you running on a 32 or 64 bit system?
64-Bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
- Install latest Cake Frosting Template
- Create a new project

**Comment by devlead** [comment]
The the template build config for frosting shouldn't have cake version as that's implied, that's an side effect of beeing merged into cake repo.

In frostings case we probably should skip `build.config` and just use `global.json`.
Obtain scripts now have an `-JSonFile|--jsonfile <JSONFILE>` option which can be pointed to `global json`.
https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-install-script
And Cake version could be picked up from tool manifest or in Frosting's case csproj

**Comment by devlead** [comment]
I believe this will be fixed by #2946 ?

**Comment by devlead** [comment]
Fixed by #2946
