### ISSUE TITLE
Update dotnet cake usage instructions (dotnet cake --help)

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#2961]
When running `dotnet cake --help` to see usage instructions, the usage and example display `Cake.dll [...]` instead of `dotnet cake [...]`

### What You Are Seeing?

```cmd
C:\augustoproiete>dotnet cake --help
USAGE:
    Cake.dll [SCRIPT] [OPTIONS]

EXAMPLES:
    Cake.dll
    Cake.dll build.cake --verbosity quiet
    Cake.dll build.cake --showtree

ARGUMENTS:
    [SCRIPT]    The Cake script. Defaults to build.cake

// ...
```

### What is Expected?

```cmd
C:\augustoproiete>dotnet cake --help
USAGE:
    dotnet cake [SCRIPT] [OPTIONS]

EXAMPLES:
    dotnet cake
    dotnet cake build.cake --verbosity quiet
    dotnet cake build.cake --showtree

ARGUMENTS:
    [SCRIPT]    The Cake script. Defaults to build.cake

// ...
```

### What version of Cake are you using?
1.0.0-rc0001

### Are you running on a 32 or 64 bit system?
64-bit

### What environment are you running on?  Windows? Linux? Mac?
Windows 10.0.18363 / win10-x64

### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)

```cmd
dotnet new tool-manifest --force
dotnet tool install Cake.Tool --version 1.0.0-rc0001
dotnet cake --help
```

### Output Log
N/A

**Comment by pascalberger** [comment]
We should also update [bootstrapper](https://github.com/cake-build/resources/blob/master/dotnet-framework/build.ps1#L263_L268) to use `--` syntax

**Comment by augustoproiete** [comment]
Comment from @pascalberger:

> 
> Another thing here is that it should use `--parameter=value` syntax since this is what we decided to use in our docs
> But this would also be something which needs to be done upstream
>

**Comment by pascalberger** [comment]
Fixed with https://github.com/cake-build/cake/pull/3031
