### ISSUE TITLE
Add support for opting out of ANSI coloring via NO_COLOR env. variable

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#2975]
Cake is able to [detect if ANSI coloring is supported](https://github.com/cake-build/cake/blob/4214b5201ccb35f76b49ae77eb7180875006282f/src/Cake.Core/Diagnostics/Console/AnsiDetector.cs#L43) in a number of cases, but once it detects that color _is_ supported, there's no way of opting out of it at the moment.

Some ideas:
- Check for the existence of an environment variable ([`NO_COLOR`](https://no-color.org) seems to be a standard) to opt out of ANSI coloring
- Add a new command-line switch e.g. `--no-color` and/or `--color=false` to opt out of ANSI coloring

---

Common options used to determine if ANSI coloring should be disabled used by some apps on GitHub:

- Command-line arguments:
    - `--no-color`
    - `--no-colors`
    - `--color=false`
    - `--color=never`

- Environment variables:
    - `TERM=dumb`
    - `FORCE_COLOR=false`
    - `FORCE_COLOR=0`

**Comment by pascalberger** [comment]
Configuration should IMHO be possible as [other configuration options](https://cakebuild.net/docs/running-builds/configuration/set-configuration-values) through environment variable, configuration file and argument.

@patriksvensson Is this something which should be done in Spectre.CLI?

**Comment by patriksvensson** [comment]
@pascalberger Makes sense to respect `NO_COLOR` since that's a pretty common convention. Other than that, the rest could be done in Cake.

**Comment by augustoproiete** [comment]
Sounds good.

For the configuration options, I suggest adding a new configuration value under `Settings` called `Color`, which can be one of the following values:

- **`auto`** - Let AnsiDetector decide if color is supported or not based on environment (**_default_**)
- **`never`** - **opt out** of coloring, regardless of environment (_skip_ the logic to detect if color is supported or not)
- **`always`** - **opt in** on coloring, regardless of environment (_skip_ the logic to detect if color is supported or not)

The `color` option would be available as ...
- An argument passed into Cake: `--color <value>`
- A configuration file value: `Color=value` (under the `Settings` section)
- An environment variable: `CAKE_SETTINGS_COLOR=value`

... and follow the [same priority order as other configuration values](https://cakebuild.net/docs/running-builds/configuration/set-configuration-values).

---

As for `NO_COLOR` I'm thinking this would be an exception to the prioritization rule for environment variables, in the sense that it overrides the `Color` setting even if defined in the configuration file or passed in as a command-line argument. What do you guys think?

**Comment by augustoproiete** [comment]
The scope of this issue was reduced to the `NO_COLOR` env. variable which was implemented via #2998 and will be released with Cake v1.1.0.

The second part (command-line switch & config optipn) is being tracked via #3138 for a future release
