### ISSUE TITLE
Migrate to Spectre.Console

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#3020]
Spectre.Cli has been moved into Spectre.Console library. We should also [migrate](https://spectresystems.github.io/spectre.console/cli/migration).

With Spectre.Console additional console features are made available, some of which can replace existing addins ([Figlet](https://spectresystems.github.io/spectre.console/widgets/figlet). We should make use of the additional console features provided by Spectre.Console by providing new or enhance existing aliases.

**Comment by devlead** [comment]
Fixed by  #3028

**Comment by pascalberger** [comment]
The second part of this issue has not been implemented yet:

> With Spectre.Console additional console features are made available, some of which can replace existing addins (Figlet. We should make use of the additional console features provided by Spectre.Console by providing new or enhance existing aliases.

I created https://github.com/cake-build/cake/issues/3135 as follow up issue
