### ISSUE TITLE
Add ICakeArguments.GetArgument extension

### ISSUE THREAD

**Issue by pascalberger** [cake-build/cake#3029]
1.0 RC 1 removed `Cake.Core.ICakeArguments.GetArgument(System.String)` since we now support multiple arguments with the same name. To avoid a breaking change (e.g. when called from an addin) we could add an extension to `GetArgument` extension to ICakeArguments.

**Comment by devlead** [comment]
For reference see the discussion https://github.com/cake-build/cake/discussions/3026

**Comment by pascalberger** [comment]
Fixed with https://github.com/cake-build/cake/pull/3049
