### ISSUE TITLE
Package ID Prefix Reservation for Cake.* on nuget.org for cake-build organization

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3040]
nuget.org allows projects to apply for [Package ID Prefix Reservation](https://docs.microsoft.com/en-us/nuget/reference/id-prefix-reservation) which, for open-source projects is useful to help developers identify the packages published by the core maintainers of a project (visual indicator), and packages published by the community.

![image](https://user-images.githubusercontent.com/177608/105128929-6469bc00-5aba-11eb-999b-7a87593e1096.png)

I suggest we apply for the prefix reservation for the `Cake.*` prefix and owner [`cake-build`](https://www.nuget.org/profiles/cake-build), but make the prefix `public`, which means that packages owned by the [`cake-build`](https://www.nuget.org/profiles/cake-build) organization will have the visual indicator showing that the package originates from a reserved prefix, but it will not block future package submissions on the prefix for any other owner.

![image](https://user-images.githubusercontent.com/177608/105129550-afd09a00-5abb-11eb-901e-aff919c1c324.png)

**Comment by gep13** [comment]
@augustoproiete I have no objections for this to proceed.

**Comment by devlead** [comment]
@augustoproiete no objection from me neither.

**Comment by augustoproiete** [comment]
This is now done. The NuGet team reserved the namespaces `Cake` and `Cake.*` to the `cake-build` organization, and [all packages in the org](https://www.nuget.org/profiles/cake-build) now have the :large_blue_circle: checkmark.

![image](https://user-images.githubusercontent.com/177608/107582692-40d4f580-6bd0-11eb-9072-4a5c76cf02eb.png)

---

Devs can continue to publish packages using the `Cake.` prefix as before, no changes there... The only difference is that they don't get the :large_blue_circle: checkmark.

**Comment by gep13** [comment]
This is great news! Thanks for getting that done!
