### ISSUE TITLE
Boolean Arguement not working

### ISSUE THREAD

**Issue by igloo15** [cake-build/cake#311]
Hello 

I have been trying to make a script with a boolean arguement and it does not appear to be working below is my script.

    var target = Argument<string>("target", "Default");
    var configuration = Argument<string>("configuration", "Release");
    var platform = Argument<string>("platform", "x86");
    var annotateNugetTime = Argument<bool>("nugettime", false);

    var nugetVersion = "4.0.0-dev";
    var semVer = "";
    var assemblyVer = "";
    double unixTimestamp = 0;

    Setup(() =>
    {
    // Executed BEFORE the first task.
    Information("Running tasks...");
	unixTimestamp = Math.Floor((DateTime.UtcNow.Subtract(new DateTime(1970, 1, 1))).TotalSeconds);
	Information("Unix Time : {0}", unixTimestamp);
    });

    Teardown(() =>
    {
    // Executed AFTER the last task.
    Information("Finished running tasks.");
    });

    Task("Clean")
    .Does(() =>
    {
	CleanDirectories("./Deploy");
    });

    Task("Default")
    .IsDependentOn("Clean");

    RunTarget(target);

When i run it like so "Cake.exe build.cake -nugettime" I get the following error
Error:   is not a valid value for a Boolean.

Am I doing something wrong with my script?

**Comment by RichiCoder1** [comment]
Cake doesn't, as far as I'm aware, support using boolean's as switchs. You have to do `Cake.exe build.cake -nugettime true`. That's an interesting idea though @patriksvensson.

**Comment by patriksvensson** [comment]
`Argument<T>` method uses `TypeConverter` under the hood and I don't think there's a conversion between an empty string and a bool.

Try this instead:

```
Cake.exe build.cake -nugettime=true
```

Or change your script to use the `HasArgument`:

```csharp
var annotateNugetTime = HasArgument("nugettime");
```

**Comment by igloo15** [comment]
My mistake when I was looking at http://cakebuild.net/docs/cli/usage

I thought the Arguement bit was being used as a switch

**Comment by patriksvensson** [comment]
Hmm, that's actually a typo!

I'm going to change that asap.
Thanks! :+1:
