### ISSUE TITLE
All old bootstrapper scripts are now broken

### ISSUE THREAD

**Issue by kjbartel** [cake-build/cake#3119]
### What You Are Seeing?
Breaking changes introduced in cake 1.0.0 affect all old build.ps1 scripts because the packages.config fetched targets 1.0.0. All of the older build.ps1 scripts do not work with new cake 1.0.0. This has broken a lot of automated builds and we now need to go to old branches to get them building again.

### What is Expected?
build.ps1 script should continue to work without any modification. If you introduce a breaking change then the path to packages.config which is fetched for 1.0.0 should be a different path. Old scripts should then get the old (still compatible) version (0.38.5) of the nuget package.

### What version of Cake are you using?
Well everyone who doesn't have a packages.config file will automatically use 1.0.0.

### Are you running on a 32 or 64 bit system?
64-bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
TeamCity

### How Did You Get This To Happen? (Steps to Reproduce)
Use any old script which uses single dashes for the arguments and don't have a packages.config file under tools, and then run the script.

**Comment by augustoproiete** [comment]
Hi @kjbartel just a heads-up that I'm transferring this to our GitHub discussions area and because of that GitHub will send you a notification saying this issue is closed, but don't fret... It's because of the transfer.
