### ISSUE TITLE
Add NPM Support

### ISSUE THREAD

**Issue by RichiCoder1** [cake-build/cake#312]
Add NPM Tool Runner.

* [x] Install
* [x] Update
* [x] Uninstall
* [ ] Test Coverage

Let me know if you want any other commands added!

**Comment by RichiCoder1** [comment]
Underway

**Comment by gep13** [comment]
@RichiCoder1 did you have an implementation of this?

In the 0.8.0 release, @patriksvensson will be adding agnostic tool support, which will make implementing this far more easy.

You can take a look here: https://github.com/cake-build/cake/issues/616

**Comment by RichiCoder1** [comment]
Only very bare bones, do two things support. Nothing exhaustive






On Sun, Jan 10, 2016 at 8:15 AM -0800, "Gary Ewan Park" <notifications@github.com> wrote:





@RichiCoder1 did you have an implementation of this?

In the 0.8.0 release, @patriksvensson will be adding agnostic tool support, which will make implementing this far more easy.

You can take a look here: https://github.com/cake-build/cake/issues/616

---

**Comment by gep13** [comment]
>@RichiCoder1 said...
Only very bare bones, do two things support. Nothing exhaustive

Do you have a branch somewhere with the initial working in it?  This is something I would like to see added, so happy to pick up the completion of it, if you have some code lying around.

**Comment by RichiCoder1** [comment]
Nope, it's kicking around in a utility cake file. I can post that if it helps






On Sun, Jan 10, 2016 at 9:58 AM -0800, "Gary Ewan Park" <notifications@github.com> wrote:





>@RichiCoder1 said...
Only very bare bones, do two things support. Nothing exhaustive

Do you have a branch somewhere with the initial working in it?  This is something I would like to see added, so happy to pick up the completion of it, if you have some code lying around.

---

**Comment by gep13** [comment]
>@RichiCoder1 said...
Nope, it's kicking around in a utility cake file. I can post that if it helps

Sure, anything is better than nothing :smile:

**Comment by patriksvensson** [comment]
Would love this to test with the new package manager provider system :smile:

**Comment by gep13** [comment]
@RichiCoder1 there now exists a Cake.Npm Addin: https://www.nuget.org/packages/Cake.Npm/ which I think covers most of the required functionality.  As a result, I am going to go ahead and close this issue.  If you think some additional work is required, then feel free to re-open the issue.
