### ISSUE TITLE
Add ability to pull any TeamCity build parameters

### ISSUE THREAD

**Issue by BlythMeister** [cake-build/cake#3141]
A lot of TeamCity build parameters are stored in files.
There is an environment variable which points to configuration (and also file pointers within the files to other files!)

The key parameter I would like to access is the build branch.

But it would be nice to have access to any parameter by the parameter key.

**Comment by augustoproiete** [comment]
@BlythMeister Perhaps we can repurpose this one instead? https://github.com/cake-build/cake/issues/2967

I suggested parsing TeamCity's `.properties` file, and your PR is parsing the `.xml` instead which is fine.

**Comment by BlythMeister** [comment]
:facepalm: yep...that's exactly what I have done....
