### ISSUE TITLE
Get a dictionary from a `ICakeArguments` instance

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#315]
Add `AsDictionary` method that returns a `IDictionary<string, string>`.

``` csharp
var dictionary = Context.Arguments.AsDictionary();
```

**Comment by ChrisMissal** [comment]
@patriksvensson should it be IDictionary<string, object> to support ints and bools for example?

**Comment by patriksvensson** [comment]
@ChrisMissal Good catch.

`ICakeArguments` are just a backing store for the arguments passed to the cake script (key/value as strings). The conversion is done in the script aliases `HasArgument` and `Argument<T>`.

Since there is no way of knowing what type different arguments have (except the built in ones), we cannot provide anything other than `IDictionary<string, string>`.

Guess this issue need some more thought :smile:

**Comment by ChrisMissal** [comment]
@patriksvensson Can you explain how this will be used? I haven't come across a need for it (because I'm still a newbie with it), so I don't understand the goal.

**Comment by patriksvensson** [comment]
@ChrisMissal I haven't come across a need for it either. It was a request on Gitter, but I'm starting to question the need for it as well. Maybe we've been thinking about the problem this would solve in the wrong way.

I will check with @RichiCoder1 and @Redth to see if they have any input on this.

**Comment by augustoproiete** [comment]
Implemented via https://github.com/cake-build/cake/issues/2690 and released with Cake v1.2.0
