### ISSUE TITLE
Add support for Engine event hooks after execution as well as before

### ISSUE THREAD

**Issue by BlythMeister** [cake-build/cake#3151]
Currently the CakeEngine will fire events before running:

* Setup
* TaskSetup
* TaskTeardown
* Teardown

Add support for event hooks after each of these methods have fired.

This is to allow Modules (such as Cake.BuildSystems.Module) to provide a custom engine which performs an action after the method has fired as well as before.

**Comment by pascalberger** [comment]
@BlythMeister There are different ways how this could be implemented and before we can proceed with this we need to have a little bit more information. Can you please explain the use-cases you have in mind which would consume this events.

Questions which should be discussed before implementation are for example if the after events are expected to be also triggered when an exception has occurred or not? What are the expected event arguments for the after event? Is there some information needed if method was successful or not? Any error messages? etc

**Comment by BlythMeister** [comment]
The use case is for this https://github.com/cake-contrib/Cake.BuildSystems.Module/issues/49


The problem I experienced is that for TeamCity the nice task begin and end service messages that print for a standard task have no way to execute on a setup or teardown.

This change introduces the same logic for hooking logic into the setup and teardown tasks as all other cake tasks.

Therefore, once the ability has been added the TeamCity module can be updated to send the begin and end service messages as part of the setup and teardown tasks (meaning build logging is correctly grouped)
