### ISSUE TITLE
Enable Specifying Target without Switch

### ISSUE THREAD

**Issue by RichiCoder1** [cake-build/cake#316]
Currently Cakes command line arguments are structured like so:
`Usage: Cake.exe [build-script] [-switch=value]`
This requires you to specify your Target by passing in `-Target=Default`.

I'd like to be able to specify the target without the prefix like so:
`Usage: Cake.exe [build-script] [target] [-switch=value]`

Allowed:
- `cake`
- `cake build.cake`
- `cake install`
- `cake build.cake install`
- `cake build.cake -Target=Install`` (mostly for back compat)

Disallowed:
- `cake install build.cake`
- `cake build.cake build.stuff`
- `cake install -Target=SomethingElse`
- `cake build.cake install -Target=SomethingElse`

**Comment by devlead** [comment]
Closed due to inactivity
