### ISSUE TITLE
Cake does not work with github

### ISSUE THREAD

**Issue by musictopia2** [cake-build/cake#3184]
I created the most simple .net project.  The build processes works perfectly when using visual studio code and using the terminal to type in the command dotnet cake.  However, when running on github, does not work at all.
My repository is here
https://github.com/musictopia2/Solution1 

You can see if you go to build actions, you can see that even though I have all the code necessary, it still will not work with github.  I hope there is a way to make it work somehow with github.

**Comment by augustoproiete** [comment]
(moving to GitHub discussions Q&A)
