### ISSUE TITLE
Better Design around Fixie's TeamCity output

### ISSUE THREAD

**Issue by ChrisMissal** [cake-build/cake#320]
When the `--TeamCity` option is specified, Fixie will use that value to produce TeamCity styled formatting in its output. When the value is omitted, Fixie checks for an environment variable. This part isn't of any concern to Cake, but this should be better documented in the `FixieRunner` usage.

Also, for better discoverability and ease of use, the `TeamCityOutput` enum could be simplified to `Nullable<bool>`.

**Comment by RichiCoder1** [comment]
Sounds good to me! Thinking on it now, is this something that should be true when `TeamCity.IsRunningOnTeamCity == true`?

**Comment by patriksvensson** [comment]
:+1:

**Comment by patriksvensson** [comment]
I'm grabbing this issue :smile:

**Comment by patriksvensson** [comment]
@RichiCoder1 Good catch, but it looks like Fixie automatically do this if running on TeamCity by looking for the `TEAMCITY_PROJECT_NAME` environment variable, so I don't think we need to do that.
