### ISSUE TITLE
Add ability to redirect console output when executing aliases for tools...

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3203]
... such as DotNetCore aliases, MSBuild aliases, etc. basically any alias that has support for settings that directly or indirectly inherits from [`ToolSettings`](https://cakebuild.net/api/Cake.Core.Tooling/ToolSettings/) could expose the ability to configure settings to the `Process` that will be executed - or at least offer the ability to capture the output.

At the moment, the workaround is to resort to `StartProcess` and handle the features that the aliases provide.

---

Based on feedback from this discussion: https://github.com/cake-build/cake/discussions/3202

**Comment by gitfool** [comment]
Related to #2460.

**Comment by augustoproiete** [comment]
Thank you @gitfool ! Your comment led me to another linked issue https://github.com/cake-build/cake/issues/2461 which proposes an implementation for what I described above, so I'm closing this as duplicate of #2461 and added both #2460 and #2461 to the same milestone and with the labels/tags.
