### ISSUE TITLE
DotNetTool Module: Cake.DotNetTool.Module signing owner to dotnetfoundation

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3211]
I've sent an invite to the `dotnetfoundation` user to be an owner of the `Cake.DotNetTool.Module` package, so that we can set it as the signing owner.

![image](https://user-images.githubusercontent.com/177608/109402841-7e0ae880-792f-11eb-978b-3da92c03526c.png)

**Comment by devlead** [comment]
Are they really signing owner on the other packages, thought we signed and pushed using cake-build org. Think that's where i added the thumbprint at least.

**Comment by augustoproiete** [comment]
That's what NuGet shows for me :man_shrugging:

https://www.nuget.org/account/Packages

![image](https://user-images.githubusercontent.com/177608/109410118-656df300-796e-11eb-835a-55e42e9f827a.png)

**Comment by devlead** [comment]
Ok great, then probably all in order, next release will be signed as part of released with Cake.

**Comment by augustoproiete** [comment]
Package `Cake.DotNetTool.Module` was signed as part of the build, which is the most important part.

![image](https://user-images.githubusercontent.com/177608/110198344-2fc28180-7e28-11eb-99e9-9a1df8a51ec1.png)

---

`dotnetfoundation` is not the signing owner just yet:

![image](https://user-images.githubusercontent.com/177608/110198372-5ed8f300-7e28-11eb-8a84-15a1e1b88490.png)

I suspect it will happen once the invite to become an owner of the package is accepted (currently still pending).

![image](https://user-images.githubusercontent.com/177608/110198400-9b0c5380-7e28-11eb-870f-d0c3c8fa3b5a.png)

**Comment by augustoproiete** [comment]
The `dotnetfoundation` user accepted the invite to become owner of the `Cake.DotNetTool.Module` package and it's now the signing owner as expected.

![image](https://user-images.githubusercontent.com/177608/112712908-240b2d80-8eb1-11eb-9792-328879ea2790.png)
