### ISSUE TITLE
Add iconUrl fallback to Cake and Cake.CoreCLR packages

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3213]
The Cake and Cake.CoreCLR packages have an embedded icon, but don't have the `iconUrl` set, which means that clients that don't support the embedded icon don't have an icon to fallback to, and display the default NuGet icon.

**Comment by Jericho** [comment]
I see the PR has already been merged so I may be too late but the recommendation for icon url is `https://cdn.jsdelivr.net/gh/cake-contrib/graphics/png/cake-contrib-medium.png` rather than the `raw.githubusercontent.com`.

**Comment by augustoproiete** [comment]
I copied from [Cake.Portable](https://github.com/cake-build/cake/blame/develop/nuspec/Cake.Portable.nuspec#L20), so I'll I blame @gep13 :eyes: :stuck_out_tongue_winking_eye:

**Comment by augustoproiete** [comment]
@Jericho `https://cdn.jsdelivr.net/gh/cake-contrib/graphics/png/cake-contrib-medium.png` is for Cake-Contrib logo though. Is there an equivalent for the Cake logo?

**Comment by Jericho** [comment]
Yes there is: `https://cdn.jsdelivr.net/gh/cake-build/graphics/png/cake-medium.png`
