### ISSUE TITLE
Feature request: Environment variable substitution in cake.config

### ISSUE THREAD

**Issue by epaulsen** [cake-build/cake#3223]
Given that [nuget.config supports environment variable substitution ](https://docs.microsoft.com/en-us/nuget/consume-packages/configuring-nuget-behavior#environment-variables-in-configuration), adding the same to cake.config would help out in scenarios where you have more than one package repository(we have a separate package repository for an off-shore contractor).

We would like to control which package repository is used via environment variables, but cannot for cake build, because cake.config does not support this.  

I'd be happy to create a PR for this if needed.

**Comment by gep13** [comment]
@epaulsen can you elaborate on exactly what you are trying to achieve here?

What options are you attempting to control within the cake.config file?  Cake already supports providing parameters via command line argument, cake.config and also environment variables.

**Comment by epaulsen** [comment]
Here's what we are trying to do:
```
[Nuget]
Source=nuget/local;https://packages.nuget.org/api/v2;https://%PACKAGE_HOME%/api/nuget/InternalNugetTools
UseInProcessClient=true

```
`https://%PACKAGE_HOME%/api/nuget/InternalNugetTools` point to one of two internal internal artifact repositories, we would like to control which via environment variable.  

But if there is another and perhaps better way of doing this please let me know.

**Comment by gep13** [comment]
The NuGet Source parameter can be controlled, in it's entirity, through a single environment variable called `CAKE_NUGET_SOURCE`.

https://cakebuild.net/docs/running-builds/configuration/default-configuration-values#nuget-download-url

But you can set it to whatever you want.  You can read more about this here:

https://cakebuild.net/docs/running-builds/configuration/set-configuration-values

**Comment by epaulsen** [comment]
Thanks for the links, I must have missed that in the docs.  
I've resolved our problem by adding two environment variables, `CAKE_NUGET_SOURCE` and another one with just the hostname (`PACKAGE_HOME` in my example above).
We needed both because the format in nuget.config is different from cake.config.

Not as elegant as it would have been if cake.config supported environment variable substitution(like nuget does), so I'll leave this issue open for now.  Feel free to close it if this is not something you would like to support.

Thanks for the help!

**Comment by augustoproiete** [comment]
Thanks @epaulsen we're considering adding environment variable expansion to `cake.config` values in a future release. Would you be interested in sending a PR?

**Comment by epaulsen** [comment]
@augustoproiete Yes absolutely!  We're using cake extensively, and I'd be happy contribute 😄 
I'll give it a go, pullrequest coming hopefully by end of week.

**Comment by augustoproiete** [comment]
@epaulsen Awesome! Assigned to you then! :+1:
