### ISSUE TITLE
Allow setting MSBuildToolVersion using custom string - Part 1

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3237]
The `MSBuildSettings` extension [`UseToolVersion`](https://github.com/cake-build/cake/blob/v1.0.0/src/Cake.Common/Tools/MSBuild/MSBuildSettingsExtensions.cs#L33-L47) expects a valid value from the [MSBuildToolVersion](https://cakebuild.net/api/Cake.Common.Tools.MSBuild/MSBuildToolVersion/) enumeration.

```csharp
public static MSBuildSettings UseToolVersion(this MSBuildSettings settings, MSBuildToolVersion version)
{
    // ...
}
```

Add an overload which accepts a custom string, to make it easier for using newer versions of MSBuild before a new version of Cake is released, including an updated version of the enumeration.

```csharp
public static MSBuildSettings UseToolVersion(this MSBuildSettings settings, string version)
{
    // ...
}
```

**Comment by Marusyk** [comment]
Could you please clarify how custom string can be interpreted to `MSBuildToolVersion`?
```
public MSBuildToolVersion ToolVersion { get; set; }
```
and how base on a custom sring we can return MSBuild path?

**Comment by augustoproiete** [comment]
Hey @Marusyk, thanks for looking into this one.

Good question. When I created this issue, I was thinking of tackling this in two parts:

1. :green_circle: (This issue) Add an overload of `UseToolVersion` that can accept a string and stop there - i.e. Leaving the `ToolVersion` property using the enum as it is today, and **release in Cake v1.x** (as it's brand new extension method, so non-breaking)

2. :orange_circle: (Your question, Future issue) Change the `ToolVersion` to use a "smart" enum that can be converted to/from `string`, and **release in Cake v2.x** (as it's changing the public API, so it's breaking)

What do you think?

To do item 1 :green_circle:, we could add an internal `string` backing field to `MSBuildSettings`, change the implementation of the `ToolVersion` to read/write from this field converting the values to/from the enum using the [existing translations](https://github.com/cake-build/cake/blob/8bc15841e97944291946a89f335562244965247e/src/Cake.Common/Tools/DotNetCore/MSBuild/MSBuildArgumentBuilderExtensions.cs#L233-L254) (but keeping the enum in the public API), and then implement the `UseToolVersion` overload that simply sets the value to the internal string backing field to any value the user wants.

For item 2 :orange_circle: I imagine we would have to change `MSBuildToolVersion` from being an enum, to being a class that emulates an enum (with static properties for the possible values, etc), and then implement an implicit conversion operator from string.
