### ISSUE TITLE
Add Chocolatey Support

### ISSUE THREAD

**Issue by RichiCoder1** [cake-build/cake#325]
Add support for chocolatey.

* [ ] Install
* [ ] Uninstall
* [ ] Pack
* [ ] Publish
* [ ] Test Coverage

**Comment by gep13** [comment]
:+1: 

What about ```upgrade```

**Comment by patriksvensson** [comment]
:+1: :smile:

**Comment by patriksvensson** [comment]
@gep13 has taken this. Good luck! :+1:

**Comment by RichiCoder1** [comment]
:tada:
