### ISSUE TITLE
Support C# 6 features in Cake script

### ISSUE THREAD

**Issue by thomaslevesque** [cake-build/cake#326]
I thought Cake was based on Roslyn, so I was surprised to realize that C# 6 features are not supported (e.g. string interpolation, null conditional operator...)

Is this going to be supported?

**Comment by patriksvensson** [comment]
Cake supports both released Roslyn versions (version `1.2.20906.2` and the latest bits `1.0.0-rc2`). The old Roslyn (pre C# 6) is the default one.

To use the latest bits (with C# 6), pass the flag `-experimental` to `Cake.exe`.

**Comment by thomaslevesque** [comment]
Thanks, it works

Since C# 6 is now stable, is there a reason to keep this "experimental" ? Do you intend to switch to the latest stable Roslyn version ?

**Comment by RichiCoder1** [comment]
See: https://github.com/cake-build/cake/issues/293

While Roslyn is stable, it's scripting features were hidden and removed in the final version.

**Comment by patriksvensson** [comment]
Well, the scripting bits are not out of beta yet and things have been changing before so we'll wait until after the 1.0 release to make it the default script engine.

Thanks for your feedback. I'll add some clarification in the documentation about this.

**Comment by thomaslevesque** [comment]
OK, thanks. I had not realized that the scripting part had not been released yet.
