### ISSUE TITLE
Using alias directives not supported

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#328]
To solve conflicting type names C# supports using aliases i.e:
`using ClassAlias = N1.N2.Class;`
[MSDN reference](https://msdn.microsoft.com/en-us/library/aa664765(v=vs.71).aspx)

Currently this gets treated as an namespace in Cake and fails.

Haven't looked into details yet if this is doable or not.

**Comment by patriksvensson** [comment]
Shouldn't be a problem as long as Roslyn supports it. We should take a look at the using line processor and make sure it understands thst it should not process those lines. If using aliases need to appear at the top of the script, we might need some additional processing.

**Comment by patriksvensson** [comment]
Should be resolved by #339 when merged.
