### ISSUE TITLE
Add InspectCode support

### ISSUE THREAD

**Issue by yvschmid** [cake-build/cake#334]
Add support for InspectCode which is part of the Resharper Command Line Tools:
https://confluence.jetbrains.com/display/NETCOM/Introducing+InspectCode

Interested or should I move it into an extension?

**Comment by ChrisMissal** [comment]
I would actually like to see this. Could it be implemented as a [Tool](https://github.com/cake-build/cake/tree/369e8425ffe9ea6866559400f9e7268fa0069b1a/src/Cake.Common/Tools)?

**Comment by yvschmid** [comment]
Some of the options are missing but it's basically done. Have a look: #335

**Comment by gep13** [comment]
This is great! I would also be using this, and would love to see dupfinder support as well :+1:

**Comment by patriksvensson** [comment]
Merged
