### ISSUE TITLE
Epic: Introduce DotNet aliases (synonyms to DotNetCore aliases)

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3341]
## Background

Cake has many [`DotNetCore***`](https://cakebuild.net/dsl/dotnetcore/) aliases for executing `dotnet` such as `DotNetCoreBuild`, `DotNetCoreTest`, etc.

The `Core` part in the name exists for historical reasons when .NET Core was first introduced and lasted until v3.1.

[With .NET 5, Microsoft dropped the "Core" from the name](https://devblogs.microsoft.com/dotnet/introducing-net-5/), and it's time we start working towards doing the same in Cake.  i.e. `DotNetCoreBuild` becomes `DotNetBuild`, `DotNetCoreTest` becomes `DotNetTest`, etc.

### Cake 2.0.0 - Introduce new DotNet aliases & mark DotNetCore aliases as obsolete

- Move implementation of `DotNetCore***` aliases and settings to `DotNet***`
   - New `DotNet***` aliases have their own `DotNet***Settings`
   - Forward `DotNetCore***` to `DotNet***` aliases
   - The `DotNetCore***Settings` should _inherit_ from `DotNet***Settings` so that old code continues to compile
- Mark all `DotNetCore***` aliases as obsolete
- (optional) Update website docs to redirect URLs to `DotNetCore***` aliases to `DotNet***` aliases

### Cake 3.0.0 - Sunset DotNetCore aliases

- Remove all `DotNetCore***` aliases from the codebase
- (_If not done in 2.0.0_) Update website docs to redirect URLs to `DotNetCore***` aliases to `DotNet***` aliases

---

|                          |       | DotNetCore alias                |               | DotNet alias / synonym      |
|:------------------------:|:-----:| ------------------------------- |:-------------:| --------------------------- |
| :white_check_mark:       | #3523 | `DotNetCoreMSBuild`             | :arrow_right: | `DotNetMSBuild`             |
| :white_check_mark:       | #3542 | `DotNetCoreTool`                | :arrow_right: | `DotNetTool`                |
| :white_check_mark:       | #3543 | `DotNetCoreRun`                 | :arrow_right: | `DotNetRun`                 |
| :white_check_mark:       | #3544 | `DotNetCoreExecute`             | :arrow_right: | `DotNetExecute`             |
| :white_check_mark:       | #3545 | `DotNetCoreClean`               | :arrow_right: | `DotNetClean`               |
| :white_check_mark:       | #3546 | `DotNetCoreRestore`             | :arrow_right: | `DotNetRestore`             |
| :white_check_mark:       | #3547 | `DotNetCoreBuild`               | :arrow_right: | `DotNetBuild`               |
| :white_check_mark:       | #3548 | `DotNetCoreBuildServerShutdown` | :arrow_right: | `DotNetBuildServerShutdown` |
| :white_check_mark:       | #3549 | `DotNetCoreTest`                | :arrow_right: | `DotNetTest`                |
| :white_check_mark:       | #3550 | `DotNetCoreVSTest`              | :arrow_right: | `DotNetVSTest`              |
| :white_check_mark:       | #3551 | `DotNetCorePublish`             | :arrow_right: | `DotNetPublish`             |
| :white_check_mark:       | #3552 | `DotNetCorePack`                | :arrow_right: | `DotNetPack`                |
| :white_check_mark:       | #3553 | `DotNetCoreNuGetPush`           | :arrow_right: | `DotNetNuGetPush`           |
| :white_check_mark:       | #3554 | `DotNetCoreNuGetDelete`         | :arrow_right: | `DotNetNuGetDelete`         |
| :white_check_mark:       | #3555 | `DotNetCoreNuGetAddSource`      | :arrow_right: | `DotNetNuGetAddSource`      |
| :white_check_mark:       | #3639 | `DotNetCoreNuGetDisableSource`  | :arrow_right: | `DotNetNuGetDisableSource`  |
| :white_check_mark:       | #3640 | `DotNetCoreNuGetEnableSource`   | :arrow_right: | `DotNetNuGetEnableSource`   |
| :white_check_mark:       | #3641 | `DotNetCoreNuGetHasSource`      | :arrow_right: | `DotNetNuGetHasSource`      |
| :white_check_mark:       | #3642 | `DotNetCoreNuGetListSource`     | :arrow_right: | `DotNetNuGetListSource`     |
| :white_check_mark:       | #3643 | `DotNetCoreNuGetRemoveSource`   | :arrow_right: | `DotNetNuGetRemoveSource`   |
| :white_check_mark:       | #3644 | `DotNetCoreNuGetUpdateSource`   | :arrow_right: | `DotNetNuGetUpdateSource`   |

|                          |       |  DotNetCore alias setting        |               | DotNet alias setting /synonym         |
|:------------------------:|:-----:|  ------------------------------- |:-------------:| ------------------------------------- |
| :white_check_mark:       | #3523 | `DotNetCoreMSBuildSettings`     | :arrow_right: | `DotNetMSBuildSettings`               |
| :white_check_mark:       | #3542 | `DotNetCoreToolSettings`        | :arrow_right: | `DotNetToolSettings`                  |
| :white_check_mark:       | #3543 | `DotNetCoreRunSettings`         | :arrow_right: | `DotNetRunSettings`                   |
| :white_check_mark:       | #3544 | `DotNetCoreExecuteSettings`     | :arrow_right: | `DotNetExecuteSettings`               |
| :white_check_mark:       | #3545 | `DotNetCoreCleanSettings`       | :arrow_right: | `DotNetCleanSettings`                 |
| :white_check_mark:       | #3546 | `DotNetCoreRestoreSettings`     | :arrow_right: | `DotNetRestoreSettings`               |
| :white_check_mark:       | #3547 | `DotNetCoreBuildSettings`       | :arrow_right: | `DotNetBuildSettings`                 |
| :white_check_mark:       | #3548 | `DotNetCoreBuildServerSettings` | :arrow_right: | `DotNetBuildServerShutdownSettings`   |
| :white_check_mark:       | #3549 | `DotNetCoreTestSettings`        | :arrow_right: | `DotNetTestSettings`                  |
| :white_check_mark:       | #3550 | `DotNetCoreVSTestSettings`      | :arrow_right: | `DotNetVSTestSettings`                |
| :white_check_mark:       | #3551 | `DotNetCorePublishSettings`     | :arrow_right: | `DotNetPublishSettings`               |
| :white_check_mark:       | #3552 | `DotNetCorePackSettings`        | :arrow_right: | `DotNetPackSettings`                  |
| :white_check_mark:       | #3553 | `DotNetCoreNuGetPushSettings`   | :arrow_right: | `DotNetNuGetPushSettings`             |
| :white_check_mark:       | #3554 | `DotNetCoreNuGetDeleteSettings` | :arrow_right: | `DotNetNuGetDeleteSettings`           |
| :white_check_mark:       | #3555 | `DotNetCoreNuGetSourceSettings` | :arrow_right: | `DotNetNuGetSourceSettings`           |

---

DotNetCore aliases - https://cakebuild.net/dsl/dotnetcore/

**Comment by Marusyk** [comment]
I'm interested in creating PR for this. Could you assign it to me?

**Comment by augustoproiete** [comment]
Hey @Marusyk Thanks for looking into this one!

This particular issue is a big one and I'd like to break it into smaller chunks to make PR reviews manageable otherwise we risk having a PR that is too large to review and it stays behind like some of the ones we have today where it's hard to find the time to properly look at it and test it.

Do you think you can take a first look at the code and suggest a few different steps to get there on the items for Cake v1.0?

We get those issues created and you can knock some PRs out of each of those (and we leave this big one open until Cake 3.0 is out).

Some questions that comes to mind:

- Does it make sense do a separate PR for each individual alias (e.g. 1 PR for `DotNetCoreBuild`, separate PR for `DotNetCoreClean`, etc.? Or do we need to group PRs in a different way? (e.g. Start with `DotNetCoreTool`, then `DotNetCoreMSBuild`,  etc.)? Or something else?

- Should we create the new `DotNet***` aliases first, using the old `DotNetCore***Settings` as a first step, and then move to using the settings as `DotNet***Settings`?

- Should we leave the tests exactly as they are for Cake v1.0 (knowing that the calls will be redirected, so if they pass, we're good)?

What do you think @Marusyk & @cake-build/cake-team?

**Comment by Marusyk** [comment]
Hi @augustoproiete 
Sorry for the late response.

> Does it make sense do a separate PR for each individual alias (e.g. 1 PR for DotNetCoreBuild, separate PR for DotNetCoreClean, etc.? Or do we need to group PRs in a different way? (e.g. Start with DotNetCoreTool, then DotNetCoreMSBuild, etc.)

- Yeah, I think it would be easier: for implementing and fore review.

> Should we create the new DotNet*** aliases first, using the old DotNetCore***Settings as a first step, and then move to using the settings as DotNet***Settings?

- Let's create the new `DotNet***` from the beginning.

> Should we leave the tests exactly as they are for Cake v1.0 (knowing that the calls will be redirected, so if they pass, we're good)?

- it is also looks ok (to avoid many duplication)

**Comment by augustoproiete** [comment]
This epic is now complete (see all issues closed above and corresponding pull requests merged) and will be released with Cake v2.0.0 🎉
