### ISSUE TITLE
VSTest alias documentation contains holdover from <v0.17.0

### ISSUE THREAD

**Issue by yschmid-levi** [cake-build/cake#3355]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake runner for .NET Framework

### Cake version

1.1.0

### Operating system

Windows

### Operating system architecture

64-Bit

### What are you seeing?

The documentation of the VSTest alias still contains `VSTestLogger.Trx` which was removed in v0.17.0 ( #1138).

https://github.com/cake-build/cake/blob/a1893a2bba26f49e089d66beeb78421cedf6126d/src/Cake.Common/Tools/VSTest/VSTestAliases.cs#L49-L61

### What is expected?

`/// VSTest("./Tests/*.UnitTests.dll", new VSTestSettings() { Logger = "trx" });`

### Steps to Reproduce

na

**Comment by himanshu007-creator** [comment]
HI, i would like to work on this issue.
