### ISSUE TITLE
Typo in documentation of NuGetAdd alias

### ISSUE THREAD

**Issue by yschmid-levi** [cake-build/cake#3365]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake runner for .NET Framework

### Cake version

1.1.0

### Operating system

Windows

### Operating system architecture

64-Bit

### What are you seeing?

https://github.com/cake-build/cake/blob/a1893a2bba26f49e089d66beeb78421cedf6126d/src/Cake.Common/Tools/NuGet/NuGetAliases.cs#L1013-L1029

### What is expected?

```
/// NuGetAdd("MyNuGetPackage", new NuGetAddSettings {
///     Source = "//bar/packages/"
///     });
```

### Steps to Reproduce

n/a

**Comment by augustoproiete** [comment]
Thanks @yschmid-levi let us know if you're going to send a PR for this one

**Comment by yschmid-levi** [comment]
can do 👍
