### ISSUE TITLE
OpenCover support

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#340]
Just remembered to add an issue for this.
I'm currently working on an implementation for this.

**Comment by sawilde** [comment]
:+1:

**Comment by gep13** [comment]
Aw sweet! Just saw that you added this!  This was next on my list :-D  Have you got an implementation of this ready to be pulled in?

**Comment by RichiCoder1** [comment]
:+1:

**Comment by jrnail23** [comment]
@patriksvensson, I'm looking to introduce OpenCover into my cake build (w/ NUnit)... do you have some code written already that I can refer to for some ideas on how to go about this (not necessarily using your addin yet)?

**Comment by patriksvensson** [comment]
@jrnail23 I have a prototype, but I will try to finish it this week.

I've been implementing an `ICakeContext` that intercept calls to the `IProcessRunner`. This will enable us to reuse any aliases with tools like *OpenCover* and *Coverity*. This will also make it possible for us to use the existing functionality in Cake without reimplementing tool support for OpenCover.

Since the `IInterceptor` is just an implementation of `ICakeContext`, all existing aliases will be available, ergo we support all tools that Cake support.

```csharp
OpenCover(this ICakeContext context, 
          IInteceptor interceptor, 
          OpenCoverSettings settings);
```

Which could be invoked like the following:

```csharp
OpenCover(i => i.NUnit("Test.dll", new NUnitSettings { NoShadow=true }), 
          new OpenCoverSettings { .. });
```

This will result in a command line such as this:

```
OpenCover.Console.exe -target:"C:\tools\nunit-console.exe" 
  -targetargs:"/noshadow C:\Test.dll"
```

Where the `-target` is the intercepted process that is started and `-targetargs` the intercepted arguments.

**Comment by gep13** [comment]
Ooo, that is very cool!  I was wondering how you were going to solve the chaining of tools, very nice :+1:

**Comment by patriksvensson** [comment]
@gep13 Thanks! :smile: I think this solution will be OK. The important thing is that we don't have to maintain two implementations of every tool that we want to chain.

**Comment by gep13** [comment]
Agreed! From initial glance, this seems perfect! Look forward to checking it out!

**Comment by patriksvensson** [comment]
Was thinking something like this:

```
public sealed class InterceptingCakeContext : ICakeContext
{
   public InterceptingCakeContext(ICakeContext context)
   {
      ...
   }

   public string GetInterceptedFilename()
   {
      ...
   }

   public string GetInterceptedArguments()
   {
      ...
   }   
}
```

Problem with this approach is the name (not really happy with that) and the fact that there's nothing stopping a tool from intercepting several calls. Maybe the filename and arguments should be added to a queue that we expose. Haven't ironed out the details yet... :smile:

**Comment by patriksvensson** [comment]
Also don't know if we should suppress other stuff like logging for this since the tools won't do anything.

**Comment by RichiCoder1** [comment]
I'm going to be contrarian and say I'd rather duplicate or abstract code and have something like `OpenCover(TestMethod.Xunit, new Xunit2Settings())` than try and fight with a potentially unyiely abstraction layer around the tool.

**Comment by jrnail23** [comment]
:+1: for @patriksvensson's design.  I think it's pretty elegant, and while I understand @RichiCoder1's concerns, I think this is a pretty clean abstraction.  It's not like this is contriving a concept where none already exists.  Rather, analysis tools like this are intended to wrap/piggyback on top of another process.  IMHO, it fits pretty well here.

**Comment by devlead** [comment]
Agree with you @jrnail23, think the by @patriksvensson suggested design makes perfect sense.

**Comment by sawilde** [comment]
:+1:
