### ISSUE TITLE
Can we make IProcess disposable or give it a stop method, etc.?

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#342]
Last night I sat down to write a Cake add-on for IIS Express.
The use case I'm trying to enable is that in one build task I can start one or more IIS express instances (as new processes), then in subsequent tasks, I would run acceptance tests, then I'd kill the IIS Express process in a `Teardown` block.

To implement my add-in, I figured I'd use `IProcessRunner` to start my IIS Express processes, returning the process to be managed by the consuming script (to be stopped, disposed, etc.).  Then I realized that the existing `IProcess` interface doesn't actually expose any way to stop or dispose a process.

First of all, is there a better way to achieve this? And second, is it feasible to extend `IProcess` to enable this behavior? I realize that would be a breaking change, so it wouldn't be trivial to manage.

**Comment by jrnail23** [comment]
OK, so upon further review, I do see that calling `IProcess.WaitForExit(0)` is probably the same as calling `Kill()`.  That's workable, but perhaps not the most semantically clear API.

**Comment by patriksvensson** [comment]
Hello @jrnail23,

You're right about the `WaitForExit` method actually killing the process...
I'm seriously considering a breaking change, because this doesn't feel right. I can't remember why we implemented it this way, but it should probably be changed.

I think it would be OK to add a `Kill` method to `IProcess` and that would be a lot more intuitive and cleaner.

/ Patrik

**Comment by jrnail23** [comment]
@patriksvensson, thanks for the quick reply!
I'm also currently digging into the `Tool<T>` class, looking to implement my `IISExpressRunner` following the same basic approach taken by all the other tools/addons I've seen, and I see that the core `Run` method only returns `void`.  
Would it make sense to introduce an overload of `Run` that returns an `IProcess`?  Perhaps the existing `void` method could be refactored to use that process, where it would then wait for exit, etc.

**Comment by patriksvensson** [comment]
@jrnail23 This sounds as a reasonable idea. As long as the overload is protected and that other tools behave as normal I'm not opposed to this in any way :smile:

**Comment by jrnail23** [comment]
Yep, that's exactly what I was thinking.  It's just an additional convenience method, but I want to make sure that returning `IProcess` behaves the same way as the `void` method.
I'll get to work on it! :smile:

**Comment by patriksvensson** [comment]
Implemented in PR #344
