### ISSUE TITLE
Add ContinuousIntegrationBuild to DotNetCoreMSBuildSettings

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#3447]
### Discussed in https://github.com/cake-build/cake/discussions/3437

<div type='discussions-op-text'>

<sup>Originally posted by **RehanSaeed** August 29, 2021</sup>
`ContinuousIntegrationBuild` is Documented in https://devblogs.microsoft.com/dotnet/producing-packages-with-source-link/#deterministic-builds and is important for creating deterministic builds on different machines and operating systems. Suggested API:

```cakescript
new DotNetCorePackSettings()
{
    ContinuousIntegrationBuild = true
};
```
</div>

Relates to https://github.com/cake-build/cake/issues/3449 and could be done together in the same PR

**Comment by augustoproiete** [comment]
This parameter is an MSBuild property that needs to be present during build (not pack) e.g. via `DotNetCoreBuild` unless, of course, when `DotNetCorePack` causes a build to be triggered first, so in both cases, it seems `DotNetCoreMSBuildSettings` would be a more appropriate place for adding this property.

**Comment by devlead** [comment]
> This parameter is an MSBuild property that needs to be present during build (not pack) e.g. via `DotNetCoreBuild` unless, of course, when `DotNetCorePack` causes a build to be triggered first, so in both cases, it seems `DotNetCoreMSBuildSettings` would be a more appropriate place for adding this property.

Agreed 👍
