### ISSUE TITLE
Equality members for DirectoryPath, FilePath

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#345]
I've experienced a bit of pain when writing tests involving `FilePath`s and `DirectoryPath`s, particularly when trying to compare them for equality.

Would anyone object to having those types implement `IEquatable<T>` to address this issue?

**Comment by ChrisMissal** [comment]
Are you comparing a `FilePath` instance to a `DirectoryPath` instance? Or just asserting that a `FilePath` instance is located in the directory?

My first reaction is an extension method to do the assert, but I might be missing the intended use.

**Comment by jrnail23** [comment]
@ChrisMissal , I'm trying to set up mock/stub expectations using a `FilePath` arg, also just asserting on equality of an actual `FilePath` against an expected one.

**Comment by ChrisMissal** [comment]
Ahh, understood. Since they already have an implicit conversion, I'd say yes, :+1: .

**Comment by patriksvensson** [comment]
@jrnail23 I understand your dilemma, but there's actually a reason paths don't implement the IEquatable interface. How we compare a `FilePath` and a `DirectoryPath` depends on whether or not the file system is case sensitive.

I would recommend using the [PathComparer](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/IO/PathComparer.cs) for testing.

You could also add a custom `Equal` assert in the Cake.Testing project that accepts a `FilePath` or `DirectoryPath` and perhaps a `StringComparison` enum.

**Comment by jrnail23** [comment]
Hmm... interesting point.  This is where having worked exclusively in Windows does me absolutely no favors.

**Comment by ChrisMissal** [comment]
Funny, I was just talking about file name order differences in Windows vs Mac today. I should have recognized that! :stuck_out_tongue:

**Comment by patriksvensson** [comment]
Yes. I got a Windows background myself so it's not obvious to always think about those things :smile:
