### ISSUE TITLE
Add alias for dotnet format command

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3479]
`dotnet format` - Formats code to match editorconfig settings. Introduced with .NET 6 SDK.

`dotnet format` is a code formatter that applies style preferences to a project or solution. Preferences will be read from an .editorconfig file, if present, otherwise a default set of preferences will be used. For more information, see the [EditorConfig documentation](https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/configuration-files#editorconfig).

Docs: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-format

**Comment by Marusyk** [comment]
assign it to me please

**Comment by twenzel** [comment]
@augustoproiete  assign it to me please
