### ISSUE TITLE
Is RunTarget actually necessary?

### ISSUE THREAD

**Issue by olivier-spinelli** [cake-build/cake#348]
Hello to every contributors of this great project!

I read the existing issues to look for an answer but I may missed it. IMHO, the fact that RunTarget is accessible from within the script is a weakness (calling RunTarget from everywhere except the very last step SHOULD nearly always result in a rather strange behavior... at best).

Shouldn't the "target" simply be handled at the host level? And the Task named "Default" be the default when no target name is provided?

**Comment by RichiCoder1** [comment]
Correct me if I'm wrong @patriksvensson, but that's because Cake itself doesn't have a way of kicking off the "Target" when the script is done executing. You have to manually kick it off. Cake files are just C# scripts. All cake does is provide some pre-processing smarts and a global helper object that aliases can be merged with.

**Comment by olivier-spinelli** [comment]
Yes, I have been thinking this.... before. But the fact is I can't see any way of using a build script without:
1 - specifying a target (exactly like I specify a script name): then there is no need to RunTarget from the script itself.
2 - not specifying a target: in such case the name "Default" is provided by the script itself as the default value to the target argument...

The fact is that CakeEngine.RunTarget needs a "target": The only benefit I can see is that the actual "Default" name is chosen by the script itself...
To conclude, i'd say that acting that the default entry point is "Default":
1 - Unifies the "interface" of a script.
2 - Removes these two lines (the first one and the last one of the current scripts).
3 - Removes the risk (from a beginner) of a call to RunTarget in the middle of the script.

It seems as simple as implementing that in CakeOptions/ArgumentParser: "Default" is automatically set when no "target" is specified on the arguments.

Did I miss something?

**Comment by patriksvensson** [comment]
I agree. I've actually been thinking about renaming `RunTarget` to `SetTarget` and change the semantics for some time. Cake would then do the running automatically with 'Default' as target if no target was explicitly set.

**Comment by RichiCoder1** [comment]
Would go nicely with my changes to make target a positional parameter, as we could just auto set the Target to "Default" if none is specified.

**Comment by patriksvensson** [comment]
I have some code for this lying around so I can spike this out in  a PR if no one oppose it :)

**Comment by RichiCoder1** [comment]
Nope. One more step towards the Just run `cake` dream :)

**Comment by patriksvensson** [comment]
:D 

Or did @oliver-spinelli want to take this?

**Comment by olivier-spinelli** [comment]
With pleasure!
May I propose : 
- A CakeOption.Target property (and the modification of the ArgumentParser). 
- A SetDefaultTarget( "XXXX" ) (greatly optional ;)) to keep the feature?
- A "temporary" (ie. "obsolete") implementation of RunTarget with a warning that actually calls SetDefaultTarget ?

**Comment by patriksvensson** [comment]
@olivier-spinelli I think a good first step would be to get the SetTarget functionality to work and get the ScriptRunner (probably the right place) to perform execution for us.

A PR for this so we have something to discuss would be valuable before putting in too much work into it.

**Comment by olivier-spinelli** [comment]
@patriksvensson I submitted a PR yesterday morning (Paris time) that does not break anything and supports the SetTarget. Now waiting for your comments!

**Comment by patriksvensson** [comment]
@olivier-spinelli Absolutely. I haven't forgotten. Didn't have as much time as I wished I had yesterday but will try to take a good look at it at soonest tomorrow. Sorry about this.

**Comment by RyannosaurusRex** [comment]
Just chiming in with a use case that I have for using an explicit RunTarget.  I've created a "watcher" task with Cake.Watch.  I effectively run this task to watch the build.cake file and then re-build when it changes so that I can debug faster.  I'm planning on expanding the watch to the entire project directory to build/test/etc outside VS and give me feedback on another monitor.  Here's the task I use:

```
Task("Watch")
    .Does(() => {
        Watch("*.cake", (changed) => {
            RunTarget("Release");
        });
    });
```

I'm new to Cake, so this may be a code smell, but that's what I'm doing. :smile:

**Comment by devlead** [comment]
Closed due to inactivity.

**Comment by RichiCoder1** [comment]
Alas ye poor issue, I knew thee well.

**Comment by nawfalhasan** [comment]
I support this. 

Currently what I am doing: 

var step1 = "Build Application";
Task(step1)
    .Does(() =>
    {
        // msbuild...
    });
RunTarget(step1);

It should be just: 

Task("Build Application")
    .Does(() =>
    {
        // msbuild...
    });

**Comment by devlead** [comment]
@nawfalhasan even though this would be very convinient, I don't see us focusing in the near future as this would break every existing script out there today and it would also eliminate a few other currently supported and useful scenarios.

**Comment by nawfalhasan** [comment]
@devlead Thanks for prompt reply. You're right, it wouldnt be a good move now. Could you tell me what are the useful scenarios the current approach would be useful in?

Your answers on SO are helpful! :)
