### ISSUE TITLE
Add alias for dotnet workload repair command

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3483]
`dotnet workload repair` - Repairs workloads installations. Introduced with .NET 6 SDK.

The `dotnet workload repair` command reinstalls all installed workloads. Workloads are made up of multiple workload packs and it's possible to get into a state where some installed successfully but others didn't. For example, a `dotnet workload install command` might not finish installing because of a dropped internet connection.

Docs: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-repair

**Comment by Marusyk** [comment]
Please assign it to me
