### ISSUE TITLE
Add alias for dotnet workload update command

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3487]
`dotnet workload update` - Updates installed workloads. Introduced with .NET 6 SDK.

The `dotnet workload update` command updates all installed workloads to the newest available versions. It queries Nuget.org for updated workload manifests. It then updates local manifests, downloads new versions of the installed workloads, and removes all old versions of each workload.

Docs: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-workload-update

**Comment by Marusyk** [comment]
Well, I can take all of `dotnet workload ...` commands. After approving of #3790 or #3791
Assign it to me please if nobody doesn't mind

**Comment by gep13** [comment]
@Marusyk done, thank you for your help with all these changes!
