### ISSUE TITLE
Add alias for dotnet store command

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3488]
`dotnet store` - Stores the specified assemblies in the runtime package store. Introduced with .NET Core 2.x SDK.

`dotnet store` stores the specified assemblies in the runtime package store. By default, assemblies are optimized for the target runtime and framework. For more information, see the runtime package store topic.

Docs: https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-store

**Comment by Marusyk** [comment]
Please assign it to me

**Comment by pascalberger** [comment]
After discussion in the team we came to the conclusion that we don't want to add support for `dotnet store` to Cake as the feature seems no longer to be shipped with .NET 6 and we don't see an actual demand for it to be supported in Cake, beside for completeness of supporting all `dotnet` commands.
