### ISSUE TITLE
Enable Derek bot to help with Hacktoberfest

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3495]
Identical configuration as we have in the website.

Main goal is to automatically close pull requests for developers without prior contributions during the Hacktoberfest month to help avoid spam PRs - we can always reopen valid ones as needed. In November we can switch the `no_newbies` off

**Comment by pascalberger** [comment]
> In November we can switch the no_newbies off

This won't be required, as it is only considered during October.

**Comment by augustoproiete** [comment]
At the moment Derek is no longer activated for cake-build org, as they switched to a sponsorship model.

_Originally posted by @pascalberger in https://github.com/cake-build/cake/pull/3496#pullrequestreview-769529072_
