### ISSUE TITLE
DupFinder Support

### ISSUE THREAD

**Issue by yvschmid** [cake-build/cake#350]
I'm working on support for Jetbrains [DupFinder](https://confluence.jetbrains.com/display/NETCOM/Introducing+dupFinder). Does anybody need some specific options?

**Comment by gep13** [comment]
:+1: woot!

The main one for me would be the ability to pass a config file into the alias so that all the configuration can be stored in that file.

**Comment by patriksvensson** [comment]
:+1:

**Comment by patriksvensson** [comment]
Merged
