### ISSUE TITLE
XmlTransformationTests not passsing due to CRLF issues

### ISSUE THREAD

**Issue by yvschmid** [cake-build/cake#351]
I'm having issues running the following unit tests:
- `Cake.Common.Tests.Unit.XML.XmlTransformationTests+TheTransformMethod.Should_Transform_Xml_File_And_Xsl_File_To_Result_File`
- `Cake.Common.Tests.Unit.XML.XmlTransformationTests+TheTransformMethod.Should_Transform_Xml_String_And_Xsl_String_To_Result_String_With_Xml_Declaration`
- `Cake.Common.Tests.Unit.XML.XmlTransformationTests+TheTransformMethod.Should_Transform_Xml_String_And_Xsl_String_To_Result_String`

Result
````
Expected: ···old">Belgian Waffles\n
Actual:   ···old">Belgian Waffles\r\n
````

Any ideas how to fix this?

**Comment by patriksvensson** [comment]
Hmm. What OS do you run?

Does a `Assert.Equal(expected, actual, false, true, false)` assertion fix the problem?

**Comment by yvschmid** [comment]
I'm running Windows 8.1 Pro. And yes `Assert.Equal(expected, actual, ignoreLineEndingDifferences: true)` does fix the problem. But I'm still confused what's causing it.

**Comment by yvschmid** [comment]
btw: What line ending convention are we using on this project?

**Comment by patriksvensson** [comment]
Not at a computer, but normally we normalize line endings in tests. Maybe it's forgotten here but doesn't explain why it doesn't work for you (unless it's a Windows setting). Can take a look at it when I get home.

**Comment by devlead** [comment]
Sounds like a GIT clone issue. Do you have core.autocrlf=true? Often needed for got to handle like endings correct on Windows.

**Comment by patriksvensson** [comment]
Yup, that might be the issue. But we should normalize line endings in tests anyway I think.

**Comment by devlead** [comment]
Issue could be GIT doesn't touch resource content line endings but normalize cs files.

**Comment by yvschmid** [comment]
Cloning the repo again with `-c core.autocrlf=true' solved it.

**Comment by patriksvensson** [comment]
Perfect :+1:
Leaving this issue here so we'll remember to fix the tests :smile:
