### ISSUE TITLE
Standardize order of release notes sections across GitHub and Blog

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3561]
The release notes is automatically generated for both the GitHub release and for the release announcement blog post, however the sections appear in a different order in each.

#### GitHub Release notes sections (in order):

- Feature
- Bugs
- Improvements
- Documentation
- ~~Build~~ (not auto-generated, see https://github.com/cake-build/cake/issues/3560)

#### Blog Post Release notes sections (in order):

- Feature
- Improvement
- Documentation
- Build
- Bug

#### Suggested new Release notes sections and order for both above:

- New Features
- Improvements
- Bug Fixes
- Documentation
- ~~Build / Deployment~~ (do not include, as per @pascalberger's suggestion below)

**Comment by devlead** [comment]
As an initial step changed the sort order to below, not renamed any labels

1. Breaking change
1. Feature
1. Improvement
1. Bug Fixes
1. Documentation

**Comment by gep13** [comment]
Does this match the order in the GRM tank file, or does this need updated?

**Comment by devlead** [comment]
Just in the blog generator, not looked at GRM yet.
