### ISSUE TITLE
Add some documentation about unit test framework dependencies

### ISSUE THREAD

**Issue by thomaslevesque** [cake-build/cake#358]
I had a hard time finding how to make NUnit and xUnit work in Cake... I kept getting errors saying that the executable couldn't be found, and I had no idea where Cake was looking for it.

I finally understood that I had to add dependencies in the tools/packages.config (NUnit.Runners, xunit.runner.console), but this isn't documented anywhere, as far as I could tell. By the way, is it the correct way to do it?

It would be nice to add some explanations in the DSL documentation.

**Comment by patriksvensson** [comment]
@thomaslevesque You're absolutely right and this is great feedback. When working on something you become blind to what not obvious for newcomers to the project. I appreciate that you took the time to open an issue about this! :+1: 

To answer your question, Cake use conventions for finding tools.

1. If the user provided a tool path, use that.
2. Check if ./tools/**/tool.exe exist.
3. Look at the PATH environment variable to see if the tool exist in any of the paths there.
4. Ask the tool itself for alternative tool paths.

**Comment by thomaslevesque** [comment]
OK, thanks for the explanation.

**Comment by patriksvensson** [comment]
Added some information about installing tools and the conventions used to locate tools at http://cakebuild.net/docs.

**Comment by thomaslevesque** [comment]
Looks good to me. I really like the `#tool` approach :)

Thanks!

**Comment by YauhenPyl** [comment]
Can we add this information in the exception message? I mean to expand "xUnit.net (v2): Could not locate executable." to "xUnit.net (v2): Could not locate executable. Perhaps there is missed #tool directive."
