### ISSUE TITLE
MSBuild Platform target misspelled

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#359]
The MSBuild Platform target produces the literal `AnyCPU` in [MSBuildRunner.cs](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/MSBuild/MSBuildRunner.cs#L107) which should be `Any CPU` (notice the space).

**Workaround:**

Append a `WithProperty` as specified below, and remove the `SetPlatformTarget` call until this is fixed.

```csharp
MSBuild(solution, new MSBuildSettings()
    .WithProperty("Platform", "Any CPU")
    .SetConfiguration(configuration));
```

**Comment by devlead** [comment]
I'll grab this one as I'm affected :) Will hopefully have PR ready by today or tomorrow.
