### ISSUE TITLE
Add `EnableCompressionInSingleFile` to `DotNetCorePublishSettings`

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3607]
`EnableCompressionInSingleFile` is not yet included in `DotNetCorePublishSettings`.

>## Compress assemblies in single file app
>Starting with .NET 6, single file apps can be created with compression enabled on the embedded assemblies. Set EnableCompressionInSingleFile property to true to achieve this. The produced single-file will have all of the embedded assemblies compressed which can significantly reduce the size of the executable. Compression comes with a performance cost. On application start, the assemblies must be decompressed into memory, which takes some time. It's recommended to measure both the size impact and startup cost impact of enabling compression before using it as the impact varies a lot between different applications.
https://docs.microsoft.com/en-us/dotnet/core/deploying/single-file#compress-assemblies-in-single-file-app

_Originally posted by @SIkebe in https://github.com/cake-build/cake/discussions/3606_

**Comment by connor-marchand** [comment]
I can give this a shot

**Comment by SIkebe** [comment]
@connor-marchand @augustoproiete I've already implemented here.  https://github.com/SIkebe/cake/commit/38da45ebd82bd7ffc08cccc3926fb374715feac2_
Can I take this one myself?

**Comment by augustoproiete** [comment]
@SIkebe Sure, go for it.

@connor-marchand Thanks for offering, but @SIkebe already wrote the code, so easier to bring his implementation and tests in. There a few more [hacktoberfest](https://github.com/cake-build/cake/labels/hacktoberfest) issues open you can pick from, though!
