### ISSUE TITLE
Create Cake Contrib Repository

### ISSUE THREAD

**Issue by RichiCoder1** [cake-build/cake#361]
We should create a Cake Contrib repository to allow for officially support aliases that take a dependency on third party packages. Cake.Common is great, but it has the restriction that no external package may be references.

See these for reference:
https://github.com/psake/psake-contrib
http://nantcontrib.sourceforge.net/

**Comment by ChrisMissal** [comment]
I like this idea! Rather than one project (like the referenced links) for all the extensions, what about more of a package approach? Just based on past experience, the "big-utility-drawer" project is difficult to maintain and contribute to. It's much easier to set up and hook together, but I think it would be more powerful if pieces could be installed and used a la carte.

**Comment by RichiCoder1** [comment]
Yup, that's what I was thinking. One repository, but multiple projects. Or multiple repositories under a cake-contrib organization.

**Comment by ChrisMissal** [comment]
I was imagining it a step further, like yeoman generators or hubot scripts. The repository lives under whoever wants to maintain it, but it follows a set of guidelines and implements an interface/API. Then Cake.Contrib would just point to them all.

We did multiple repos under one organization for WebApiContrib and it's tough. The maintainers don't use them all all the time, so they can get ignored for long stretches.

**Comment by RichiCoder1** [comment]
I think I understand. I'm actually vaguely reminded of NPM's package.json, though they have it easier since there's no compilation step largely :)

**Comment by SharpeRAD** [comment]
Whats wrong with individual repositories / nuget packages?

If the Aliases and public classes are commented correctly in each package then it would be possible to create automatic documentation using the same tools that the main cake-build site uses by just pulling in the nuget package for each addin.

**Comment by SharpeRAD** [comment]
@patriksvensson has done all the hard work with the automatic documentation features of the main site so I can't imagine scanning a few extra nuget packages would be that difficult. You could even integrate it into the main sites build process such that it detected missing comments and only referenced addins that had complete documentation.

**Comment by phillipsj** [comment]
@gep13 @devlead @patriksvensson Just noticed this one why looking through some of the open issues.  Would you all call this one closed?

**Comment by gep13** [comment]
The cake-control organisation has been created https://github.com/cake-contrib which I believe fits the bill for what was described in this issue.
