### ISSUE TITLE
Incorrect parameter "/result" passed when executing nunit tests

### ISSUE THREAD

**Issue by garethbudden** [cake-build/cake#367]
Hi, I believe that the NUnitSetting for ResultsFile may be setting an incorrect parameter when passing to nunit console runner, for example...

```c#
var settings = new NUnitSettings
{
    ResultsFile = new FilePath("./src/build/TestResults.xml")
};

NUnit("./My.Test.dll", settings);
```
Will pass the results file parameter as ``` /result:"./src/build/TestResults.xml" ```, this doesn't work for me and the [docs](http://www.nunit.org/index.php?p=consoleCommandLine&r=2.5) appear to say it should be ``` /xml:"./src/build/TestResults.xml" ```. 

Am I using an outdated or too recent version of the nunit runners?

**Comment by patriksvensson** [comment]
Hello @garethbudden,

The `/xml:` parameter is used for version 2.5 and below. Since version 2.6, the `/result` parameter is used. Not sure why NUnit breaks their own API like this, but Cake's NUnit runner is targeting 2.6 and above. 

Sorry for the inconvenience.

/ Patrik

**Comment by patriksvensson** [comment]
I read the configuration again, and NUnit 2.6 also recognize the `/xml` parameter, so obviously they don't break their own API; they've just extended it. Nevertheless this won't be of any help to you and the only solution I see is to upgrade to the latest version of NUnit. Another option would be to add a legacy mode to the NUnit runner to make it use the correct parameters.

**Comment by garethbudden** [comment]
ok thanks, I've updated and all works fine.
