### ISSUE TITLE
NuGet restore for .NET 6 Android project seems to ignore fallback frameworks

### ISSUE THREAD

**Issue by leonluc-dev** [cake-build/cake#3670]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake .NET Tool

### Cake version

1.3.0

### Operating system

Windows

### Operating system architecture

64-Bit

### What are you seeing?

I have .NET 6 project targeting `net6.0-android` I want to build using cake. This works fine using a simple command line build like `dotnet build MyProject.csproj`, however when I build the same project in cake using `DotNetCoreBuild` I get the following error during the restore phase:

`NU1202: Package Xamarin.Google.Guava.ListenableFuture 1.0.0.2 is not compatible with net6.0-android31.0 (.NETCoreApp,Version=v6.0) / android-arm64. Package Xamarin.Google.Guava.ListenableFuture 1.0.0.2 supports: monoandroid50 (MonoAndroid,Version=v5.0)`

### What is expected?

The net6.0-android target supports monodroid packages and NuGet is supposed restore them appropriately.

### Steps to Reproduce

1. Create a .NET 6 project with target framework `net6.0-android`
2. Add a monodroid based NuGet package to it (for example Xamarin.Google.Guava.ListenableFuture 1.0.0.2).
    No other code should be required to reproduce the issue
3. Try to build it using the `DotNetCoreBuild` method in cake
4. The error mentioned above should occur

**Comment by augustoproiete** [comment]
(moving to GitHub discussions)
