### ISSUE TITLE
Program Files (x86) not working

### ISSUE THREAD

**Issue by melcloud** [cake-build/cake#368]
Hello,

Not sure if I used it incorrectly, but var files = GetFiles("C:/Program Files (x86)MyApps/Test.*"); throws unknown token error.

Regards

**Comment by patriksvensson** [comment]
Looks like a bug to me. Will take a look at this later today.

**Comment by patriksvensson** [comment]
Thanks for reporting this btw! :+1:

**Comment by melcloud** [comment]
You are welcome! :)

**Comment by patriksvensson** [comment]
@melcloud Wrote a quick fix for this during my lunch: #369
Will be included in the next release. Sorry for any inconvenience.

**Comment by patriksvensson** [comment]
@melcloud You can temporarily use the AppVeyor artifact until this is merged: https://ci.appveyor.com/project/cakebuild/cake/build/0.5.2-build-699/artifacts
