### ISSUE TITLE
Use DotNetMSBuildSettings instead of DotNetCoreMSBuildSettings on new dotnet aliases settings

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3683]
_As per discussion comment https://github.com/cake-build/cake/discussions/3680#discussioncomment-1603329 by @gitfool_

**Comment by gitfool** [comment]
I just noticed [build.cake](https://github.com/cake-build/cake/blob/develop/build.cake) and [parameters.cake](https://github.com/cake-build/cake/blob/develop/build/parameters.cake) should probably be moved over too?

**Comment by augustoproiete** [comment]
> I just noticed [build.cake](https://github.com/cake-build/cake/blob/develop/build.cake) and [parameters.cake](https://github.com/cake-build/cake/blob/develop/build/parameters.cake) should probably be moved over too?

Sure thing: https://github.com/cake-build/cake/issues/3685 though this one is a chicken-and-egg kind of thing... We needed RC1 to be out first and [now we can start using it](https://github.com/cake-build/cake/commit/52df129ae453667c7cb4cf5e8b46dcea3a306c23) :relaxed:
