### ISSUE TITLE
Use cake build language in classes

### ISSUE THREAD

**Issue by Sam13** [cake-build/cake#371]
I'd like to structure my build scripts into different classes. E.g one for default directory definitions.
I noticed that I'm not able to use the cake build language there e.g.
```cs
public class DefaultDirectories
{	
	public static DirectoryPath WorkingCopyRoot = MakeAbsolute(Directory(".")) 
    public static DirectoryPath Binaries = WorkingCopyRoot.Combine(new DirectoryPath("bin"));
 ...
}

```
_MakeAbsolute_ and _Directory_ cannot be interpreted correctly by CAKE.

For now I created a workaround but that may be not possible for other cases

```cs
public class DefaultDirectories
{	
	public static DirectoryPath WorkingCopyRoot = new DirectoryPath(System.IO.Directory.GetCurrentDirectory());
	public static DirectoryPath Binaries = WorkingCopyRoot.Combine(new DirectoryPath("bin"));
    ...
}
```

Do I miss something or is that not intended to be done like that?

Another newbie question: How do you edit your build scripts, can this be done somehow in Visual Studio where compilation errors might be shown as under normal C# development?

**Comment by RichiCoder1** [comment]
For reference, you can also do this:
```csharp
public class DefaultDirectories
{   
    public static DirectoryPath WorkingCopyRoot = Context.MakeAbsolute(Directory(".")) 
    public static DirectoryPath Binaries = WorkingCopyRoot.Combine(new DirectoryPath("bin"));
 ...
}
```
Or at least in theory. Not sure how well statics play with them.
I've wondered about this myself too though. Causes a very weird disconnect between the main build script and the tooling scripts.

**Comment by jrnail23** [comment]
I might suggest that this could be related (in a sense) to #356.

**Comment by Sam13** [comment]
@RichiCoder1

Tried your suggestion, but that gives the following error:
```cs
Error: D:/Project/Directories.cs(3,69): error CS0120: An object reference is required for the non-static field, method, or property 'Cake.Core.Scripting.ScriptHost.Context'

```

**Comment by patriksvensson** [comment]
Alas, there are no plans of supporting Cake alias methods in classes.
A workaround for your problem would be something like this:

```csharp
public class DefaultDirectories
{
    public static DirectoryPath WorkingCopyRoot;
    public static DirectoryPath Binaries;

    public static void Initialize(ICakeContext c)
    {
      WorkingCopyRoot = c.MakeAbsolute(c.Directory("./"));
      Binaries = WorkingCopyRoot.Combine(new DirectoryPath("bin"));
    }
}

// Initialize default directories.
DefaultDirectories.Initialize(Context);

Task("DoMagic")
  .Does(() =>
{
  var temp = DefaultDirectories.WorkingCopyRoot.Combine("tmp");
  Information(temp.FullPath);
});

RunTarget("DoMagic");
```

**Comment by Sam13** [comment]
That's fine, didn't know how to adress the context...
