### ISSUE TITLE
Support other assembly info relevant information for ParseAssemblyInfo

### ISSUE THREAD

**Issue by Sam13** [cake-build/cake#372]
_CreateAssemblyInfo_ supports all commonly used assembly info settings (http://cakebuild.net/api/cake.common.solution.project.properties/8f09cb16), but parsing an existing assembly info can only read assembly version numbers (http://cakebuild.net/api/cake.common.solution.project.properties/aa3585e3).
For normal cases which the assembly info is created by a Cake script this might be sufficent. But in my case I have to read an existing assembly info file which is not created by Cake.

**Comment by RichiCoder1** [comment]
:+1:

**Comment by gep13** [comment]
@Sam13 this functionality was added in Cake 0.6.0: http://cakebuild.net/blog/2015/11/cake-v0-6-0-released please give this a try, and let us know if you have any further questions.

Thanks again for your suggestion! :+1:

**Comment by Sam13** [comment]
Thanks, I'll test it as soon as I have time to update to the latest Cake version...
