### ISSUE TITLE
Syntax highlighting for .cake files in VisualStudio Code! 

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#374]
I just did some digging, and I figured out how to enable syntax highlighting for .cake files in Visual Studio Code (Windows).
(I wasn't sure where else might be best to share this, so I just created an issue)

Under your VS Code app folder (for me, running version 0.7.10, it's `c:\users\MyUserName\AppData\Local\Code\app-0.5.2` ), open up `\resources\app\plugins\vs.language.csharp\ticino.plugin.json`

It'll look like this:

```json
{
	"pluginId": "vs.language.csharp",
	"activationEvents": ["textModel:csharp"],
	"mainModule": "./csharpMain",
	"contributes": {
		"language": [{
			"id": "csharp",
			"extensions": [ ".cs", ".csx" ],
			"aliases": [ "C#", "csharp" ]
		}]
	},
	"scripts": {
		"compile": "node ../../node_modules/gulp/bin/gulp.js --gulpfile ../gulpfile.js compile --dir vs.language.csharp"
	},
	"_bundling": [
		{ "name": "./csharpMain" }
	]
}
```

Simply add `".cake"` to that `extensions` array like this: 
```json
    "extensions": [ ".cs", ".csx", ".cake" ]
```
Save the file, restart VS Code, and you're all set.

One quick word of warning though, notice that app folder (`app-0.5.2`) has an affinity to a particular version.  I'm quite sure that when VS Code updates itself to a newer version, your edits may get lost, and you'll probably have to do this again under the newer app folder.

**Comment by Sam13** [comment]
Why don't you name them with the extension _.cs_ then you have the syntax highlighting for free?

**Comment by patriksvensson** [comment]
You could also use Atom which has built in support fot Cake :)

**Comment by jrnail23** [comment]
@Sam13, I think it would be confusing to others if I used the *.cs extension because cake files aren't really c# files.  On the other hand, the *.csx extension also "just works," and it's closer to the truth of what cake files are (although they're also not really ScriptCS files either).

@patriksvensson, I had no idea about Cake support in Atom.  I'll give that a try too!

**Comment by patriksvensson** [comment]
@jrnail23 I'm going to the the VS code approach as well :)

You are also correct. The Cake DSL is a superset of C# and not plain C#. Therefore we decided to use our own extension. Will make itneasier for tooling in the future (i.e Omnisharp integration).

**Comment by RichiCoder1** [comment]
"Full" is a stretch, but it does have pretty good syntax highlighting :)

And yup! Omnisharp is a steadly progressing work in progress: https://github.com/OmniSharp/omnisharp-roslyn/issues/208
I believe VS Code also uses Omnisharp.

**Comment by gep13** [comment]
>@RichiCoder1 said...
I believe VS Code also uses Omnisharp

Yes, that is correct.

**Comment by gep13** [comment]
@patriksvensson is this something that should make it's way onto the main cakebuild.net site?

**Comment by gep13** [comment]
@jrnail23 is this still the same for the latest version of VS Code?  Looks like things might have changed since you posted this issue.

**Comment by jrnail23** [comment]
@gep, I think it has changed, but not a whole lot -- I think just under a different version-specific folder now.

**Comment by gep13** [comment]
@jrnail23 I think there might be a bit more to it than that :cry: For instance, Visual Studio Code is now installed to `C:\Program Files (x86)\Microsoft VS Code` rather than in the local user folder, and I also can't see an equivalent folder in the resources folder that you mentioned above.  There is mention here:

https://code.visualstudio.com/docs/customization/overview

of using a yeoman generator for adding customizations into code, but I haven't read dug into that properly to figure out what is going on there.

**Comment by jrnail23** [comment]
@gep13 , look here: C:\Program Files (x86)\Microsoft VS Code\resources\app\plugins\vs.language.csharp

**Comment by gep13** [comment]
Hmm, I don't have that folder...

![image](https://cloud.githubusercontent.com/assets/1271146/10588123/5880703a-769c-11e5-8c07-b9493c115aa0.png)

Any ideas how I would get it? :-D

**Comment by jrnail23** [comment]
@gep13, which version of VS code are you running? I'm running v0.8.0, and everything looks good.

**Comment by gep13** [comment]
@jrnail23 0.9.1

![image](https://cloud.githubusercontent.com/assets/1271146/10588238/0abe50e6-769d-11e5-9723-1920d483379e.png)

**Comment by jrnail23** [comment]
hmmm... I just checked for updates to Code, and it told me there were none.  I got lied to!

**Comment by gep13** [comment]
Ah, that could be because I am on the developer preview of Code. Are you part of that as well?

**Comment by jrnail23** [comment]
no, just looks like my automatic update detection isn't working.  probably my company's stupid security junk.

**Comment by gep13** [comment]
ah, that old chestnut :smile_cat:

**Comment by jrnail23** [comment]
ok, I just downloaded the update -- now it looks like it's moved to C:\Program Files (x86)\Microsoft VS Code\resources\app\extensions\csharp\package.json

**Comment by gep13** [comment]
Ah, that did it! Thanks for sticking with me through that :smiley_cat:

**Comment by jrnail23** [comment]
@gep13, glad to help :smile:

**Comment by gep13** [comment]
@jrnail23 I have just suggested an edit to the cake website to include steps on how to add syntax highlighting in VS Code.  After a short discussion with the VSCode Twitter account here:

https://twitter.com/code/status/656253877931511808

I was able to make this change in a way that won't get blown away the next time an update to VS Code happens.  Let me know what you think.

**Comment by gep13** [comment]
And it's live:

http://cakebuild.net/docs/editors/vscode

I think this issue can be closed.  Thoughts?

**Comment by jrnail23** [comment]
Nice job, @gep13!
