### ISSUE TITLE
SemVersion class crashes if compared to `null`

### ISSUE THREAD

**Issue by nikola-nignite** [cake-build/cake#3743]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake .NET Tool

### Cake version

2.0.0

### Operating system

Windows

### Operating system architecture

64-Bit

### What are you seeing?

I used `SemVersion` class of Cake to handle versioning (due to inability to use NuGet.Versioning package; unrelated bug in Cake.Bakery).

At one point I compared a `SemVersion` variable to `null`, which causes it to crash with `ObjectNullReferenceException`. I resolved it by using `SemVersion.Zero` instead so far.

### What is expected?

Comparing a `SemVersion` object to `null` returns `false`.

### Steps to Reproduce

SemVersion version = null;
if (version == null) // Here script crashes
   version = new ....

**Comment by devlead** [comment]
Hi, this is a bug and I'll send a PR to address it.

Meanwhile you can write
```csharp
if (semVersion is null)
```
