### ISSUE TITLE
Make TextTransform handle Regex Special Characters

### ISSUE THREAD

**Issue by RichiCoder1** [cake-build/cake#380]
If I were to set the delimiters for TextTransform to `$`, it will break, as `$` is a regex special character. TextTransform should handle this.

**Comment by devlead** [comment]
Wondering if it's just about escaping `. $ ^ { [ ( | ) * + ? \` in the inputed key data?

**Comment by patriksvensson** [comment]
Yes, that will probably work. We could always make sure that we escape the data for the user, but as a work around this should work.

**Comment by devlead** [comment]
@patriksvensson i agree think we should fix it in the code, basically when key added to expression we should escape like we do with quoting etc. in other areas.
