### ISSUE TITLE
Wrap NuGet Pack Release Notes in CDATA

### ISSUE THREAD

**Issue by RichiCoder1** [cake-build/cake#381]
Wrap the release notes in NuGet Pack with `<![CDATA[]]>`. This will allow for rich release notes.

**Comment by patriksvensson** [comment]
Good point! :+1:

**Comment by gep13** [comment]
@RichiCoder1 what exactly did you mean by this?  Was looking to clean this one up just now.

Are you referring to here:

https://github.com/cake-build/cake/blob/5426a07c672ac2c81534d4cc2883ee7e59e7277f/src/Cake.Common/Tools/NuGet/NuGetAliases.cs#L43

**Comment by RichiCoder1** [comment]
https://github.com/cake-build/cake/blob/5426a07c672ac2c81534d4cc2883ee7e59e7277f/src/Cake.Common/Tools/NuGet/Pack/NuspecTransformer.cs

**Comment by RichiCoder1** [comment]
Specifically make it so the transformer detects if the context needs to be wrapped in CData, and do so. Especially for CData which often contains arbitrary markup.

**Comment by gep13** [comment]
Ah, I see what you are getting add with regard to adding the CDATA attribute.

What would the criteria be for detecting whether this was required though?

**Comment by patriksvensson** [comment]
Not sure about how NuGet works, but wouldn't it be OK to always wrap this in a CDATA attribute? Will it break something if it doesn't need to have a CDATA attribute?

**Comment by gep13** [comment]
Not that I am aware of no.  There is nothing to stop you having a CDATA attribute, but then just having standard XML contained within it, so I agree, just always put CDATA around the release notes section.

Agreed?

**Comment by RichiCoder1** [comment]
I'd be fine with that. Just thought it might be overkill :P

**Comment by devlead** [comment]
Well it's less complex doing it just one way. Also less write prone.

**Comment by devlead** [comment]
PR #465 fixed this.
