### ISSUE TITLE
PostAction is not setable on DotNetSettings

### ISSUE THREAD

**Issue by twenzel** [cake-build/cake#3821]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake .NET Tool, Cake Frosting, Cake runner for .NET Core

### Cake version

2.1

### Operating system

Windows

### Operating system architecture

64-Bit

### What are you seeing?

It's not possible to set an `Action<IProcess>` on the DotNetSettings.
In my use case it's required to the the StandardOutput from the started dotnet tool process.

### What is expected?

A new option on DotNetSettings object

### Steps to Reproduce

See above

**Comment by augustoproiete** [comment]
Looks like you do need to access the `IProcess` to get the standard output, otherwise I would suggest a workaround using the `HandleExitCode` e.g.

```cakescript
DotNetRestore("test.csproj",
    new DotNetRestoreSettings
    {
        HandleExitCode = exitCode =>
        {
            Console.WriteLine($"dotnet restore exit code: {exitCode}");
            return true;
        },
    });
```

**Comment by twenzel** [comment]
I've updated the PR so that it's now possible to configure and handle the process.
