### ISSUE TITLE
Enhancement: TaskSetup and TaskTeardown

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#389]
I think it would be useful to have actions that could be executed before and after each task, particularly if those blocks receive an instance of the current task (or metadata about the task).

For example, that would make it easy to report progress to TeamCity, or maybe add blocks around each task in TeamCity's output to make its build logs more readable.

**Comment by patriksvensson** [comment]
@jrnail23 Sounds like a good idea :+1:

**Comment by RichiCoder1** [comment]
:+1:

**Comment by jrnail23** [comment]
ok then, I'll get started on it :smile:

**Comment by jrnail23** [comment]
@patriksvensson, @RichiCoder1, I wanted to get some quick feedback here.
I'm thinking for my TaskSetup/TaskTeardown actions, I want to pass in the Task and the ICakeContext as args, to be available for use by the user's code.
I want ICakeContext to get access to the Log, Environment, etc.
I only really want the Task info to get access to things like Name & Description, etc. -- I don't think it would be advisable to allow the task to be mutated or executed or anything like that.

That suggests at least two alternate approaches:
1) Create an immutable TaskInfo object that only has the Task's descriptive properties.
2) Define an ITaskInfo interface that only exposes getters for those descriptive properties, and have CakeTask implement it using its existing members.

What do you guys think?

**Comment by patriksvensson** [comment]
@jrnail23 I agree with what you're saying.

I would go with option 2. Maybe call it `ICakeTaskInfo` and expose `Name`/`Description`/`Criterias` and `Dependencies`.

However, I don't think that you need to provide the ICakeContext for this.

**Comment by RichiCoder1** [comment]
I'd vote two. ITaskInfo sounds like a more testable and future proof solution.
So they'd end up looking like this?:
```csharp
TaskSetup((context, taskInfo) => {
    Information(context is ICakeContext); // true
    Information(taskInfo.Name); // MyTask    
    Information(taskInfo.Description); // MyTask does this thing.
    Information(taskInfo.Dependencies); // IReadOnlyList<string>.Count = 1
    Information(taskInfo.Criterias); // IReadOnlyList<Func<bool>>.Count = 1
});

TaskSetup((context, taskInfo, taskResult) => {
    Information(context is ICakeContext); // true
    Information(Task.Name); // MyTask    
    Information(taskResult.RunTime); // TimeSpan (5 seconds)
    Information(taskResult.RanToCompletion); // True    <---- 
    Information(taskResult.Exception); // null   <------------------  These two are probably redundant with the existing task error reporting extensions.
});
```

**Comment by jrnail23** [comment]
@patriksvensson, the Context would already just be available, right?  The reason I thought to include it is that the `CakeTaskBuilder.Does()` extension has an overload that provides `ICakeContext`.  

Can you please explain when that overload is intended to be used, as opposed to the one that doesn't provide the context?

**Comment by jrnail23** [comment]
@RichiCoder1, that's pretty much what I was thinking.  Good call on including the taskResult in the TaskTeardown.  I hadn't considered that!

**Comment by RichiCoder1** [comment]
Or possible do what places like Roslyn or Auth does and have an `ICakeTaskSetupContext` and `ICakeTaskTeardownContext`. The former would just have information about the task, while the later also contains task completion information information.

Also, should they really be called Setup and Teardown? Maybe something like BeforeStart and Completed would be more appropriate?

>@patriksvensson, the Context would already just be available, right? The reason I thought to include it is that the  CakeTaskBuilder.Does()  extension has an overload that provides  ICakeContext . 
>
>Can you please explain when that overload is intended to be used, as opposed to the one that doesn't provide the context?

Hmm, I'm not exactly sure. That's a good point. Gut feeling says we should pass it in.

**Comment by patriksvensson** [comment]
@jrnail23 You're right. Include `ICakeContext` there as well.

@RichiCoder1 What would `taskResult` contain?

**Comment by RichiCoder1** [comment]
>@RichiCoder1 What would  taskResult  contain?

Run time, exception information if and error was thrown, as well as whether or not the Task was even run (all task criterias were met). That last one might not be obvious information, so I'd be ok with leaving that out.

**Comment by patriksvensson** [comment]
@RichiCoder1 I think `TaskSetup`/`TaskTeardown` would go well together with `Setup`/`Teardown`.

**Comment by jrnail23** [comment]
@patriksvensson, are you saying I should overload it (one method with `ICakeContext` and one without), or only one with the context?

**Comment by patriksvensson** [comment]
@jrnail23 Have just one with `ICakeContext`.

I just realized we already have a `Finally` handler for tasks. Not sure if `TaskTeardown` would provide any value.

**Comment by jrnail23** [comment]
I also think the task result should probably include the task's duration.

**Comment by patriksvensson** [comment]
@jrnail23 @RichiCoder1 Maybe we could call the `TaskTeardown` method `Finally` instead.

**Comment by jrnail23** [comment]
@patriksvensson, the `Finally` handler is defined per task, right?  `TaskTeardown` would be defined once and apply to all tasks.

**Comment by patriksvensson** [comment]
@jrnail23 You're right! Sorry! :smile:

**Comment by patriksvensson** [comment]
@jrnail23 Should definitly be called `TaskSetup` and `TaskTeardown` then.

**Comment by RichiCoder1** [comment]
Yup. That was my argument. Finally is for specific tasks and only takes specific information. TaskTeardown is purely for reporting purposes and receives a lot more general and diagnostic information.

**Comment by jrnail23** [comment]
@RichiCoder1, it sounds like you and I are definitely on the same page here.  I also look at this as a way to possibly provide richer feedback/interaction with CI systems like TeamCity.

**Comment by patriksvensson** [comment]
@jrnail23 @RichiCoder1 Yup. Sounds good to me.

A good thing is to keep things as simple as possible in the first implementation. Less is more until we're absolutely sure about how stuff should be.

**Comment by jrnail23** [comment]
@patriksvensson, agreed.  I'll put up a prototype of the implementation ASAP for review and feedback.

**Comment by patriksvensson** [comment]
@jrnail23 Sounds good :+1: :smile:

**Comment by RichiCoder1** [comment]
Yup. TeamCity is the biggest thing I have in mind, for the exact reasons you mention. Taking of build log blocks would be an easy win with this.

@patriksvensson Yup. I think what we've outlined here should be good.

Rough sketch of possible interfaces @jrnail23 
```csharp
public interface ITaskInfo
{
    public string Name { get; }

    public string Description { get; }
    
    public IReadOnlyList<string> Dependencies { get; } // Should this be something more concrete? Like ITaskInfos?

    public IReadOnlyList<Func<bool>> Criterias { get; } // Maybe something more concrete too? So we're not re-evaluating criteries that Cake has already evalutated?
}
```

```csharp
public interface ITaskSetupContext 
{
    public ITaskInfo Task { get; set; }

     public bool MeetsCriteria { get; set; } // Yes/no?
}
```

```csharp
public interface ITaskTeardownContext
{
    public ITaskInfo Task { get; set; }
    
    public TimeSpan Elapsed { get; set; }

    public bool RanSucessfully { get; set; }

    public Exception? ExceptionInfo { get; set; }
}
```

**Comment by jrnail23** [comment]
@RichiCoder1, if the task doesn't meet the criteria, should its task setup even be performed?
(I can imagine arguments both for and against this one)

Also, for the `ITaskTeardownContext`, `RanSuccessfully` could be a little confusing.  I think  there may be two questions to ask there:  

1. Did the task run at all?
2. If it did run, was it successful?

**Comment by RichiCoder1** [comment]
In theory, if `ITaskSetupContext.MeetsCriteria` is false, then `ITaskTeardownContext.RanSuccessfully` would be false and `ITaskTeardownContext.ExceptionInfo` would be null. We could make that more explicit though, I agree that it's vague. An enum of states could possibly work. `ITaskStatus` with `Success`, `Skipped`, `Error` might work. I *would* like setup and teardown to be run even if the task itself isn't, if only to allow for custom reporting of skipped tasks.

**Comment by patriksvensson** [comment]
Like I said before it's probably wise to include as little information as
possible and let this grow organically. We can't change this once we
release it...

**Comment by jrnail23** [comment]
I think I agree with reporting skipped tasks.  The only downside I can think of there is additional noise in your logs, but the user can always decide not to log anything if the task was skipped.

**Comment by RichiCoder1** [comment]
I also don't want to release something that's hamstringed. That being said the most simple and straight forward implementation would be to remove `ExceptionInfo` and `RanSuccesfully` from teardown`, `MeetsCriteria` from Setup, and add `Skipped` to teardown. Would allow you to report Start, Header, Skipped Or Not, and Footer.

**Comment by jrnail23** [comment]
Also in the interest of preserving our ability to add additional info over time, I think `ITaskSetupContext` and `ITaskTeardownContext` are a good idea, even if they start out pretty threadbare.
With those in place, we can add new methods and properties without modifying the signatures, thereby preserving reverse compatibility.

**Comment by RichiCoder1** [comment]
Absolutely.

**Comment by patriksvensson** [comment]
Yes I agree. The two contexts are a really good idea :smile:

**Comment by jrnail23** [comment]
in the teardown context, do you guys prefer `Elapsed` or `Duration`?  (I like `Duration` myself, but if `Elapsed` is already used elsewhere, I want to stay consistent with your existing vocabulary)

**Comment by RichiCoder1** [comment]
Engine used Elapsed, but Report uses Duration, so I'd say `Duration`.

**Comment by RichiCoder1** [comment]
Revised interfaces:
```csharp
public interface ITaskInfo
{
    public string Name { get; }

    public string Description { get; }
    
    public IReadOnlyList<string> Dependencies { get; } 

    public IReadOnlyList<Func<bool>> Criterias { get; }
}
```

```csharp
public interface ITaskSetupContext 
{
    public ITaskInfo Task { get; set; }
}
```

```csharp
public interface ITaskTeardownContext
{
    public ITaskInfo Task { get; set; }
    
    public TimeSpan Duration { get; set; }

    public bool Skipped { get; set; }
}
```

And in IScriptHost:
```csharp
void TaskSetup(Action<ICakeContext, ITaskSetupContext> action);

void TaskTeardown(Action<ICakeContext, ITaskTeardownContext> action);
```

**Comment by patriksvensson** [comment]
Isn't Duration what we use?

**Comment by jrnail23** [comment]
I'd like to omit `Criterias` from `ICakeTaskInfo` for the first iteration.
I think it could introduce some unwanted complexity up front.
You guys cool with that?

**Comment by RichiCoder1** [comment]
I'm abiveliant to criterias to be honest, just included it for completeness. @patriksvensson ?

And yes, re-searching the case, `Duration` is was `CakeReportEntry` uses, which is the defacto way that Cake is currently storing that information.

**Comment by jrnail23** [comment]
ok, now on to the next question.... what should we do with these things when using a `DryRunExecutionStrategy`?

**Comment by patriksvensson** [comment]
Agree. "Duration" is probably best. Engine stuff is internal I think.

**Comment by RichiCoder1** [comment]
> ok, now on to the next question.... what should we do with these things when using a  DryRunExecutionStrategy ?

Huh. My gut says no, but I'll also defer to @patriksvensson  on this one.

**Comment by jrnail23** [comment]
the existing Setup and Teardown actions are no-ops in a dry run, FYI.

**Comment by jrnail23** [comment]
You wouldn't really perform a dry run in a CI environment, right?

**Comment by devlead** [comment]
No, very unlikely.

**Comment by jrnail23** [comment]
and I guess there's no telling what the user might choose to do in those actions anyway.  They could, in theory, manipulate the file system.  Having a dry run actually execute those manipulations would violate principle of least surprise.

**Comment by devlead** [comment]
Indeed, go with noop for now.

**Comment by jrnail23** [comment]
@devlead :+1:

**Comment by patriksvensson** [comment]
The dry run execution strategy shouldn't execute any tasks or anything similar at all.

**Comment by jrnail23** [comment]
Just posted my initial prototype --
Some of the complexity or "lack of elegance" is probably a result of me trying to stay consistent with the behavior of the script-level Setup & Teardown actions (if setup fails, don't run the task, but still run the teardown). 

Not sure if that's really the desired behavior -- any opinions on that?
