### ISSUE TITLE
Guard against null Console instance on InfoFeature

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#3894]
By @Jon-Kjar

> _Just noticed that one of the features had a null check but no tests associated. And that there was another feature that did not have that null check so added that with an associated check_

**Comment by FreshKhalifa** [comment]
Great,  your AirDrop tokens bonus is generated and ready to be sent out to
your wallet as your share is being  accumulated already
You’re to send the gas fee of

$500 bnb/btc for 2.0    Airdrop
$1000 bnb/btc for 5.0  Airdrop

 bnb to the bot generated address from the wallet you’re to receive your
bonuse.
