### ISSUE TITLE
GetDirectories globbing issues

### ISSUE THREAD

**Issue by JoshSchreuder** [cake-build/cake#390]
Hi guys. Interesting project!

I'm trying to use `GetDirectories` and globbing patterns to match all my `bin` folders to clean them up. It doesn't seem to be working as I would expect. I'm probably doing something really stupidly wrong, so help would be appreciated :smile: 

Directory structure:
```
/Build
   /cakebuild.ps1
   /tools
       /Cake
       /NUnit.Runners
/Test
   /MyProject.A
       /bin
   /MyProject.B
       /bin
   /MyProject.C
       /bin
```

I would like to match all the `bin` folders inside of `MyProject.*`

I have tried a variety of globbing patterns:
* `GetDirectories("../Test/MyProject.*/**/bin")`
* `GetDirectories("../Test/**/bin")`
* `GetDirectories("../Test/MyProject.*/bin")`

And none seem to capture the bin folders.

`GetDirectories("../Test/MyProject.*")` does capture the project folders, so I feel like I am on the right track.

What is the correct way to do this?

**Comment by patriksvensson** [comment]
@JoshSchreuder Hello and thank you!

I can't see anything obviously wrong with your example but I might be missing something as well. Going to take a look at this later today and see if I can find a solution to the problem you're experiencing.

**Comment by patriksvensson** [comment]
@JoshSchreuder I tracked the bug down. Will send a PR today for this.

**Comment by JoshSchreuder** [comment]
> I tracked the bug down. Will send a PR today for this.

Phew, so it wasn't just me! Thanks, looking forward to trying cake out.

**Comment by patriksvensson** [comment]
@JoshSchreuder I'm so sorry but I haven't had time to send the PR yet. In the meanwhile (as a temporary workaround), you can put your build script, bootstrapper and tools directory in the repository root and it should work as expected. Will try to submit the PR as soon as possible.

**Comment by patriksvensson** [comment]
@JoshSchreuder Actually, another workaround is to append the absolute root to your glob pattern (and remove the `..`).

**Example:**

```csharp

var root = MakeAbsolute(Directory("..")).FullPath;

// Get directories
var dirs = GetDirectories(root + "/Test/MyProject.*/**/bin");
foreach(var dir in dirs)
{
  Information(dir.FullPath);
}
```

**Comment by bjmarte** [comment]
The same problem exists when using GetFiles.  Just FYI.

**Comment by patriksvensson** [comment]
@bjmarte Yes. Will provide fix ASAP. Did the workaround work for you?

**Comment by mormegil-cz** [comment]
Probably the same issue, but to be sure: `GetFiles("../**/*.csproj")` throws `ArgumentOutOfRangeException` for me:
```
System.ArgumentOutOfRangeException: startIndex cannot be larger than length of string.
Parameter name: startIndex
   at System.String.Substring(Int32 startIndex, Int32 length)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitRecursiveWildcardSegment(RecursiveWildcardSegment node, GlobVisitorContext
context)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitSegment(PathSegment node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.VisitRelativeRoot(RelativeRoot node, GlobVisitorContext context)
   at Cake.Core.IO.Globbing.GlobVisitor.Walk(GlobNode node, Func`2 predicate)
   at Cake.Core.IO.Globber.Match(String pattern, Func`2 predicate)
   at Cake.Common.IO.GlobbingAliases.GetFiles(ICakeContext context, String pattern)
   at Submission#0.GetFiles(String pattern)
   at Submission#0..ctor(Session session, Object& submissionResult)
```
Anyway, the workaround of resolving the relative path prior to calling `GetFiles` works.

**Comment by patriksvensson** [comment]
@mormegil-cz Thanks for reporting this. It will be fixed in the next version of Cake. Sorry about this.

**Comment by bjmarte** [comment]
The workaround did work for me in one example I tried, but I am affected by this issue in several places in my scripts and I don't want to make a bunch of changes if a future version will fix it.  So I am waiting to upgrade until this is fixed.

**Comment by patriksvensson** [comment]
@JoshSchreuder @mormegil-cz @bjmarte PR #423 has been submitted that will resolve this bug.

Note that glob patterns like `./hello/**/../world` (a parent reference after a recursive wildcard) isn't supported. Not sure it will ever be, but just a heads up.
