### ISSUE TITLE
Zip compression improvements

### ISSUE THREAD

**Issue by Sam13** [cake-build/cake#392]
Add ZIP compression options which include:
- ZIP level
- Ability to provide source - target path transformation when adding items

Example: you add directory C:\Test\Sub123 from C:\ as root. Then the ZIP file contains that in Test\Sub123 but maybe you want to place that data into another folder in the ZIP archive. Currently you can do this only by creating the desired folder structure beforehand with copying files around which costs performance. As far as I have seen in the source it is possible to provide a new path when adding items to the archive.

**Comment by patriksvensson** [comment]
@Sam13 Great idea.

How would you propose that the API would look like?

**Comment by Sam13** [comment]
Add `ZipSettings`class which can be passed to the *Zip* alias which includes the zip level and other related settings in future.

For the mapping I can think of a lambda which provides the path and / or file name in the zip file based on the original path? I did not thought much about that so far, so maybe there are better alternatives for that...

**Comment by devlead** [comment]
Closed due to inactivity.
