### ISSUE TITLE
Remove .NET 5 TFM

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#3949]
.NET 5 is now out of support and should be removed next major release of Cake

**Comment by devlead** [comment]
@Marusyk need a reply in this issue from you before GitHub lets me assign you.
You can do #3972 and this in one PR but two commits after #3990 is merged and #3950 closed.

**Comment by Marusyk** [comment]
ok

**Comment by devlead** [comment]
> ok

Excellent issue now assigned to you, and .NET 7 support already merged.
