### ISSUE TITLE
Update Spectre.Console to 0.45.0

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#3969]
Remark: This change will need to be done in next major console no longer contains command-line parsing breaks ABI, also needs to explicitly reference [Spectre.Console.Cli](https://www.nuget.org/packages/Spectre.Console.Cli/0.45.0).

**Comment by viraj2252** [comment]
Could you please assign this to me?

**Comment by devlead** [comment]
@viraj2252 issue has now been assigned to you, let us know if you need any assistance or have anything to review

**Comment by devlead** [comment]
@viraj2252 please let us know if anything around this is unclear or if you've got any questions. We aim to be ready with milestone 3.0 by November 8th, no worries if you don't have the cycles to do this by then - we'll just assign the issue to someone in the team.

**Comment by devlead** [comment]
@viraj2252 Thanks for stepping up, much appreciated, but as we're closing up on a deadline and need to start 3.0 testing soon, we're going to unassign you from the issue, please have a look at one of our other issues to see if any of them feels like a good fit
https://github.com/cake-build/cake/issues
