### ISSUE TITLE
Better error message while cake nuget task or msbuild taks is trying to execute wrapped exe

### ISSUE THREAD

**Issue by wallymathieu** [cake-build/cake#398]
If the nuget exe is missing you will get:

```
An error occured when executing task.
Error: Path cannot be empty.
Parameter name: path
```

Perhaps something along the lines of "cant find exe nuget, searched in system PATH and in ./tools"

Similar thing occurs when executing msbuild task (and the specific msbuild is missing)

**EDIT** (by @patriksvensson):
Repository exist at https://github.com/wallymathieu/cake-build-test

**Comment by jrnail23** [comment]
:+1:

**Comment by patriksvensson** [comment]
Actually, I've been looking at this and it will actually say `NuGet: Could not locate executable.` so I guess that the error must be something else.

I tried the repository you provided in #396 and I cannot reproduce this error. Is there anything missing in your reproduction steps?

**Comment by wallymathieu** [comment]
Remove the tools folder and don't have nuget in path? Maybe this is already fixed in dev?

**Comment by patriksvensson** [comment]
This behavior has been there forever. Just tried deleting the tools folder in your repository and I get the `NuGet: Could not locate executable` message.

![Screenshot](http://i.imgur.com/DOb2cIz.png?1)

**Comment by wallymathieu** [comment]
That's weird. I'll close this since you cant reproduce it.

**Comment by patriksvensson** [comment]
@wallymathieu My guess is that the error is the result of something else. Normally the `Path cannot be empty.` is thrown when creating a `FilePath` or `DirectoryPath` with an empty string. :/

**Comment by wallymathieu** [comment]
Indeed. That's why it's so confusing.

**Comment by patriksvensson** [comment]
I would like to find the cause of this so we can fix it. Can you reproduce it now somehow?

**Comment by wallymathieu** [comment]
after making sure that there definitelly is no nuget in path i try running Cake on a windows 10 machine:
```
D:\projects\cake-build-test [what_happens_when_there_is_no_nuget]> .\packages\Cake.0.5.3\Cake.exe

========================================
Clean
========================================

========================================
Restore-NuGet-Packages
========================================
An error occured when executing task.
Error: Path cannot be empty.
Parameter name: path
```
If I switch to the master branch where nuget.exe is in the ./tools folder, then I don't get any errors.

I have vs 2013 community edition, vs 2015 community edition and windows sdk installed. I have msbuild in path, but that shouldn't change anything.

**Comment by patriksvensson** [comment]
Ok, will take a look at this later tonight. Thanks!

**Comment by patriksvensson** [comment]
There is no packages folder. How do you restore the packages.config in .nuget?

**Comment by wallymathieu** [comment]
I used nuget exe from another lib:
```
> ..\some_other_dotnet_lib\src\.nuget\NuGet.exe restore
```

**Comment by wallymathieu** [comment]
I tried debugging with the source, but it crashed vs2015.

**Comment by patriksvensson** [comment]
Ok. Can you try doing a `git clean -xdf` in the repository and then (after restoring packages like you did) go to the Cake directory and enter the following:

```
C:\git\cake-build-test\.nuget\Cake.0.5.3 [what_happens_when_there_is_no_nuget]> .\Cake.exe ../../build.cake -verbosity=diagnostic
```

And paste the output here.

**Comment by wallymathieu** [comment]
```
Compiling build script...

========================================
Clean
========================================
Executing task: Clean
Creating directory D:/projects/cake-build-test/test_cake/bin/Release
Finished executing task: Clean

========================================
Restore-NuGet-Packages
========================================
Executing task: Restore-NuGet-Packages
An error occured when executing task.
Error: System.ArgumentException: Path cannot be empty.
Parameter name: path
   at Cake.Core.IO.Path..ctor(String path)
   at Cake.Core.Utilities.Tool`1.GetToolPath(TSettings settings, FilePath toolPath)
   at Cake.Core.Utilities.Tool`1.RunProcess(TSettings settings, ProcessArgumentBuilder arguments, FilePath toolPath, Pro
cessSettings processSettings)
   at Cake.Core.Utilities.Tool`1.Run(TSettings settings, ProcessArgumentBuilder arguments, FilePath toolPath, ProcessSet
tings processSettings, Action`1 postAction)
   at Cake.Common.Tools.NuGet.Restore.NuGetRestorer.Restore(FilePath targetFilePath, NuGetRestoreSettings settings)
   at Submission#0.<.ctor>b__2()
   at Cake.Core.ActionTask.Execute(ICakeContext context)
   at Cake.Core.DefaultExecutionStrategy.Execute(CakeTask task, ICakeContext context)
   at Cake.Core.CakeEngine.ExecuteTask(ICakeContext context, IExecutionStrategy strategy, Stopwatch stopWatch, CakeTask
task, CakeReport report)
   at Cake.Core.CakeEngine.RunTarget(ICakeContext context, IExecutionStrategy strategy, String target)
   at Cake.Scripting.BuildScriptHost.RunTarget(String target)
   at Submission#0..ctor(Session session, Object& submissionResult)
   at Submission#0.<Factory>(Session session)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, DiagnosticBag diagnostics, Session sessio
n, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(IEnumerable`1 args)
D:\projects\cake-build-test\packages\Cake.0.5.3 [what_happens_when_there_is_no_nuget]>
```

**Comment by wallymathieu** [comment]
The text before this section is describing how it's downloading roslyn and importing namespaces.

**Comment by patriksvensson** [comment]
Ok, perfect. Will take a look at this tonight/tomorrow. Thanks.

**Comment by wallymathieu** [comment]
No problem. Hope it helps.

**Comment by devlead** [comment]
@patriksvensson how did go? 😉

**Comment by devlead** [comment]
Closed due to inactivity.
