### ISSUE TITLE
Globbing is missing some documentation.

### ISSUE THREAD

**Issue by nils-a** [cake-build/cake#4043]
Currently, the only documentation seems to be https://cakebuild.net/blog/2018/12/cake-v0.31.0-released#globber-improvements

The Documentation should get its own section, containing examples and descriptions of what does, and what does not, work.

Also, the API (probably at https://cakebuild.net/api/Cake.Core.IO/GlobPattern/) should contain at least some hints and/or a reference to the above described section.

**Comment by pascalberger** [comment]
Seems to be a duplicate of https://github.com/cake-build/website/issues/1224
