### ISSUE TITLE
Feature Request: StartProcess overload

### ISSUE THREAD

**Issue by Redth** [cake-build/cake#406]
I find myself using `StartProcess (“Some.exe”, new ProcessSettings { Arguments = “-a” })` a lot which is a bit verbose.

Could we have an overload that does the same thing but has this signature instead? `StartProcess (FilePath filename, string arguments)`

**Comment by patriksvensson** [comment]
Sounds good to me! :+1:

**Comment by danielrozo** [comment]
I'd like to work on this. I just took a look and the only changes that seem to be involved would be adding the overload in `ProcessAliases` that would call the existing method constructing a new `ProcessSettings` with the supplied argument.

On the unit test side, it would be replicating the `StartProcess(ICakeContext,FilePath,ProcessSettings)` meaningful tests.

Does this sound correct/make sense?

**Comment by patriksvensson** [comment]
@danielrozo Yes, this sounds good to me. It's yours! :wink:

**Comment by patriksvensson** [comment]
Implemented in #427
