### ISSUE TITLE
GitHub Actions group commands not accessible from task setup and teardown

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#4075]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake .NET Tool

### Cake version

3.0.0

### Operating system

Linux

### Operating system architecture

64-Bit

### CI Server

GitHub Actions

### What are you seeing?

After I updated [gitfool/Cake.Dungeon](https://github.com/gitfool/Cake.Dungeon) for Cake v3, I tried to [change](https://github.com/gitfool/Cake.Dungeon/commit/9298d94c2f239a7fceddda9fdf7585bd6f7e3715) it to use the GitHub Actions group commands from task setup and teardown but this [fails](https://github.com/gitfool/Cake.Dungeon/actions/runs/3504824702/jobs/5870754206#step:5:24) with an unexpected error:
```
Compiling build script...
/home/runner/work/Cake.Dungeon/Cake.Dungeon/scripts/bootstrap.cake(24,52): error CS0119: 'CommandAliases.Command(ICakeContext, ICollection<string>, ProcessArgumentBuilder, int, Func<CommandSettings, CommandSettings>)' is a method, which is not valid in the given context
/home/runner/work/Cake.Dungeon/Cake.Dungeon/scripts/bootstrap.cake(25,55): error CS0119: 'CommandAliases.Command(ICakeContext, ICollection<string>, ProcessArgumentBuilder, int, Func<CommandSettings, CommandSettings>)' is a method, which is not valid in the given context
```

### What is expected?

Unless I'm missing something, this should compile and behave the same as the previous code that writes information directly to output.

### Steps to Reproduce

See the code change referenced above.

**Comment by devlead** [comment]
Think the issue is that the referenced code calls

```csharp
BuildSystem.GitHubActions.Command.StartGroup
```

But the provider property is called `Commands` (plural). 

https://github.com/cake-build/cake/blob/9828d7b246d332054896e52ba56983822feb3f05/src/Cake.Common/Build/GitHubActions/IGitHubActionsProvider.cs#LL37C40-L37C40

**Comment by gitfool** [comment]
Doh! I need more coffee.
