### ISSUE TITLE
NUnit runner does not throw if glob pattern matched nothing

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#408]
The call to the NUnit runner with a glob pattern that will not find any files will try to execute NUnit without arguments. We should throw if this is the case.

```csharp
NUnit("this_matches_nothing/**/*.Tests.dll");
```

**Comment by RichiCoder1** [comment]
Xunit too. Really, all the test runners.

**Comment by patriksvensson** [comment]
I'm the real tool here... :smile: 
Will fix ASAP!
