### ISSUE TITLE
`DotNetPublishSettings` is missing a way to set the `--os` option

### ISSUE THREAD

**Issue by sfwester** [cake-build/cake#4107]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake Frosting

### Cake version

3.0.0

### Operating system

Windows

### Operating system architecture

64-Bit

### What are you seeing?

Using dotnet version:
```sh
$ dotnet --version
6.0.404
```
when I run
```sh
$ dotnet publish --help
Description:
  Publisher for the .NET Platform

Usage:
  dotnet publish [<PROJECT | SOLUTION>...] [options]

Arguments:
  <PROJECT | SOLUTION>  The project or solution file to operate on. If a file is not specified, the command will search the current directory for one.

Options:
...
  --os <os>                            The target operating system.
...
```

I get an option to set the the target operating system.

However, [DotNetPublishSettings.cs](https://github.com/cake-build/cake/blob/ca6699c4c0b3a57c9ca04bdfc687158fe112215e/src/Cake.Common/Tools/DotNet/Publish/DotNetPublishSettings.cs) does not provide access to the option. ([DotnetMSBuildSettings.cs](https://github.com/cake-build/cake/blob/ca6699c4c0b3a57c9ca04bdfc687158fe112215e/src/Cake.Common/Tools/DotNet/MSBuild/DotNetMSBuildSettings.cs) does not either).

### What is expected?

I should be able to set the target OS using the `DotNetPublishSettings`. e.g,

```cs
var publishSettings = new DotNetPublishSettings
{
    Os = "win"
};
```

### Steps to Reproduce

```cs
var publishSettings = new DotNetPublishSettings
{
    Os = "win"
};
```
does not compile.

### Output log

```txt
'DotNetPublishSettings' does not contain a definition for 'Os'
```

**Comment by Kuldeep-kd** [comment]
My question is, why is it relevant to add `--os` in the settings? And what are your expectations from this setting?
If you need to use particular target os for the build, you might as well run build.ps1 or build.sh accordingly.

**Comment by sfwester** [comment]
Just to be sure we are are on the same page I am advocating adding the option to the `DotNetPublishSettings` class. [The dotnet CLI already supports this option](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-build).

> Specifies the target operating system (OS). This is a shorthand syntax for setting the [Runtime Identifier (RID)](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog), where the provided value is combined with the default RID. For example, on a win-x64 machine, specifying --os linux sets the RID to linux-x64. If you use this option, don't use the -r|--runtime option. Available since .NET 6.

We use this option to output a windows executable even though we build on a unix box so I don't think calling build.ps1 will help me in this case.

However, reading the docs quoted above, it looks like I can get away with using the `Runtime` option in `DotNetPublishSettings`. May still be worth adding `Os` to get feature parity with the CLI.
