### ISSUE TITLE
Call multiple tasks from CLI in Frosting

### ISSUE THREAD

**Issue by juwens** [cake-build/cake#4122]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake Frosting

### Cake version

3.0.0

### Operating system

Linux, Windows, macOS

### Operating system architecture

64-Bit

### What are you seeing?

Feature introduced with issue #2470 and PR #4054 was not implemented for frosting.

when i do `build.ps1 --target=A --target=B` only B gets executed.

### What is expected?

A and B are executed

### Steps to Reproduce

`build.ps1 --target=A --target=B`

**Comment by juwens** [comment]
@devlead @FrankRay78

**Comment by FrankRay78** [comment]
Thank you for this PR @juwens , my bad in that I didn't also include it in Frosting.  My PR was done early on in my FOSS career and I didn't know the cake codebase well enough.  The omission also wasn't picked up on review.

**Comment by juwens** [comment]
hey @FrankRay78, no need to excuse. That you contributed a cool feature (several people were looking for) to a FOSS project is awesome. 🙂  
I, for example, do it way too rarely.  
Oversight happen to everyone, no matter if junior or senior developer. Especially in complicated scenarios like cake, where two cli "frontends" exist for one core logic.  
I'm not sure either if my PR is technically correct. It's more of a: basis for discussion.  
I guess i'm in your position now ^^

**Comment by augustoproiete** [comment]
Resolved by https://github.com/cake-build/cake/pull/4123
