### ISSUE TITLE
Caching the build script fails if multiple processes try to run a cake target

### ISSUE THREAD

**Issue by FlorianWDP** [cake-build/cake#4127]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched [issues](https://github.com/cake-build/cake/issues) to ensure it has not already been reported

### Cake runner

Cake .NET Tool

### Cake version

3.0.0

### Operating system

Windows

### Operating system architecture

64-Bit

### What are you seeing?

I have a solution with 100+ projects that i want to build. I hooked cake targets to MSBuild so i can execute builds from Visual Studio. Now every project would run 2 cake targets during their build.
Obviously, the overhead of the compilation of the build script gets rather high with that many calls (~2-3 seconds per call) and i wanted to cache the script for faster builds.

Now multiple projects call a compilation of the script at the same time and all of them want to write the cache, but fail due to concurrency access restriction.

### What is expected?

I would want to safely create the build script cache, even when multiple processes try to create one.

### Steps to Reproduce

Have a solution where multiple projects get built at the same time. So that they call cake targets at the same time.
Set EnableScriptCache=true.

**Comment by devlead** [comment]
Could you have a "PreCompile" target / empty task that you invoke once before going parallel? Then the concurrent calls would have existing assemblies and no compilation will be done.

**Comment by FlorianWDP** [comment]
From my research on how to configure MSBuild for Visual Studio, i only found how to define targets on a project level, not a solution level. So i don't know where to place a hook that would be called once before all projects start to build.

**Comment by devlead** [comment]
This seems like an edge case, potentially you could have an project that all other depend on, then that would be build first before others.

**Comment by FlorianWDP** [comment]
Yeah that would have been my last step, will try to search for more, thanks for the help
