### ISSUE TITLE
Add File APIs for setting timestamps (creation time, last write time, last access time)

### ISSUE THREAD

**Issue by augustoproiete** [cake-build/cake#4132]
We currently don't expose the APIs in `System.IO.File` for setting the timestamps in files:

- SetCreationTime
- SetCreationTimeUtc
- SetLastAccessTime
- SetLastAccessTimeUtc
- SetLastWriteTime
- SetLastWriteTimeUtc

**Comment by DurveshKumarPal** [comment]
hey, @augustoproiete I would like to work on Issue could you Assigned to me.

**Comment by augustoproiete** [comment]
@DurveshKumarPal Thanks for the offer, but [the work for this ticket is already done](https://github.com/cake-build/cake/pull/4133) - just awaiting review & merge.

I assigned https://github.com/cake-build/cake/issues/2056 to you though as that one is still open and no work has been done yet
