### ISSUE TITLE
XUnit2: add support for additional command line switches

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#414]
The following command line switches are among those missing from Cake's XUnit2 support:

- [x] `-parallel`
- [x] `-maxthreads`
- [x] `-trait`
- [x] `-notrait`

**Comment by patriksvensson** [comment]
Yes, this should be supported! :+1: 
Interested in grabbing this issue? :smile:

**Comment by jrnail23** [comment]
Sure, I'll take it.  I can probably get to it sometime this week.
