### ISSUE TITLE
Create Cake.Infrastructure Package

### ISSUE THREAD

**Issue by RichiCoder1** [cake-build/cake#417]
Create a Cake.Infrastructure package (or extend Cake.Core) in such a way that external applications can utiltize Cake's defaults and preprocessing outside of Cake (ex: OmniSharp).
Should include:
### Cake Defaults
* [ ] Usings
* [ ] Assembly References

### Script File Preprocessing:
* [ ] `#r` assemblies
* [ ] `#l` script files
* [ ] `#addin` target assemlbies

### Cake Alias Generation:
* [ ] Method and Property Aliases (should this be runtime type generated, or a script file like Cake currently does?)

**Comment by patriksvensson** [comment]
@RichiCoder1 At the moment we will return the `Cake.Core.dll`, `Cake.Common.dll` and `Cake.exe` assemblies as part of the default assemblies. You will have to provide a root (where those assemblies reside) since we normally use the Cake application folder for this. Since you're not getting those files as part of executing a script (and doesn't know the folder where those reside from the executable path), will you be able to find the Cake folder yourself from Omnisharp?

**Comment by patriksvensson** [comment]
Here's a first draft of the functionality you want: https://github.com/cake-build/cake/pull/420

There is a new class called `ScriptConventions` that will return default namespaces and default assemblies.

You won't get the target assemblies per se, but you could always download them yourself using the `ScriptProcessor.InstallAddins` method that accepts a `ScriptAnalyzerResult`. Will probably have to add a possibility to provide a directory where the addins/tools should be installed when I think about it.

**Comment by patriksvensson** [comment]
@RichiCoder1 Here's a first draft of the functionality you want: https://github.com/cake-build/cake/pull/420

There is a new class called `ScriptConventions` that will return default namespaces and default assemblies.

You won't get the target assemblies per se, but you could always download them yourself using the `ScriptProcessor.InstallAddins` method that accepts a `ScriptAnalyzerResult`. Will probably have to add a possibility to provide a directory where the addins/tools should be installed when I think about it.

**Comment by RichiCoder1** [comment]
As I said in the PR, very awesome work! I'll see what I can put together with this asap :)
