### ISSUE TITLE
Allow setting `/testsettings:` file for MSTest runner

### ISSUE THREAD

**Issue by vktr** [cake-build/cake#421]
`MSBuildSettings` should expose a property to set the `/testsettings:` argument. This file is used to set various settings for the `mstest.exe` runner.

**Comment by devlead** [comment]
More info [here](https://msdn.microsoft.com/en-us/library/ms182489.aspx#testsettings)

Usage: `/testsettings:[ file name ]`

**Comment by marcosnz** [comment]
This looks easy enough for me to take a look at :)
Will take a look today
