### ISSUE TITLE
Issue with globbing using dot character in conjunction with wildcard

### ISSUE THREAD

**Issue by molehillrocker** [cake-build/cake#431]
We currently face an issue with globbing using wildcards in conjunction with a dot character.

**Scenario:**
We have multiple unit test projects that all end with ``.Test`` and one integration test project that ends with ``IntegrationTest``. Using ``src/**/*.Test.dll`` as seach pattern finds all unit test projects but also the integration test project.

**Solution structure:**
src
|-- Project.A
|-- Project.A.Test
|-- Project.B
|-- Project.B.Test
|-- Project.IntegrationTest

I guess this is a bug, but if I'm doing something wrong please direct me to a proper way of doing this. :smile: 

The current workaround is to specify all unit test projects manually, but obviously this enforces us to adjust the build file to for every unit test project we add.

**Comment by molehillrocker** [comment]
I wrote a test case that shows the error. I currently have no Git available, which is why I post it here.

```
[Fact]
public void Should_Return_Files_For_Pattern_Ending_With_Character_Wildcard_And_Dot()
{
	// Given
	var fixture = new GlobberFixture(true);
	fixture.FileSystem.CreateFile("C:/Working/Project.A.Test.dll");
	fixture.FileSystem.CreateFile("C:/Working/Project.B.Test.dll");
	fixture.FileSystem.CreateFile("C:/Working/Project.IntegrationTest.dll");

	// When
	var result = fixture.Match("C:/Working/*.Test.dll");

	// Then
	Assert.Equal(2, result.Length);
	Assert.ContainsFilePath(result, "C:/Working/Project.A.Test.dll");
	Assert.ContainsFilePath(result, "C:/Working/Project.B.Test.dll");
}
```

**Comment by molehillrocker** [comment]
I managed to install Git over here and made a PR: #433

**Comment by patriksvensson** [comment]
I've merged the associated PR and will close this issue.
Thank you! :smile:
