### ISSUE TITLE
Add DotNetRemoveReference alias for dotnet remove reference command 

### ISSUE THREAD

**Issue by Marusyk** [cake-build/cake#4352]
`dotnet remove reference` - Removes project-to-project (P2P) references

The `dotnet remove reference` command provides a convenient option to remove project references from a project.

Docs: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-remove-reference

**Comment by Marusyk** [comment]
Pls assign it to me

**Comment by devlead** [comment]
@Marusyk issue assigned to you.
