### ISSUE TITLE
Add DotNetListReference alias for dotnet list reference command

### ISSUE THREAD

**Issue by Marusyk** [cake-build/cake#4353]
`dotnet list reference` - Lists project-to-project references.

The `dotnet list reference` command provides a convenient option to list project references for a given project.

Docs: https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-list-reference

**Comment by Marusyk** [comment]
Please assign the issue to me

**Comment by devlead** [comment]
@Marusyk issue assigned to you.
