### ISSUE TITLE
Minimum required PowerShell version

### ISSUE THREAD

**Issue by molehillrocker** [cake-build/cake#437]
Today we ran into an issue that some colleagues could not run the build tasks I defined. After some investigation we found out that they had an older PowerShell version (``v2.0``) installed which failed to run the ``build.ps1``. My PowerShell version is ``3.0``.
Does it make sense to add a check for the PowerShell version on the startup of a build script and fail the build with a proper error message that hints the user to install an up-to-date version of PowerShell, or at least print the required version to the output?

After upgrading to ``v3.0``, everything works as expected. :+1:

**Comment by patriksvensson** [comment]
@molehillrocker Yes, that would make sense. What was the error message that your colleague got?

**Comment by molehillrocker** [comment]
Here is the stacktrace (localized in German :see_no_evil:):

```
Preparing to run build script...
Join-Path : Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.
Bei D:\my\little\project\build\build.ps1:52 Zeichen:23
+ $TOOLS_DIR = Join-Path <<<<  $PSScriptRoot "tools"
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

Join-Path : Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.
Bei D:\my\little\project\build\build.ps1:53 Zeichen:23
+ $NUGET_EXE = Join-Path <<<<  $TOOLS_DIR "nuget.exe"
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

Join-Path : Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.
Bei D:\my\little\project\build\build.ps1:54 Zeichen:22
+ $CAKE_EXE = Join-Path <<<<  $TOOLS_DIR "Cake/Cake.exe"
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

Join-Path : Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.
Bei D:\my\little\project\build\build.ps1:55 Zeichen:29
+ $PACKAGES_CONFIG = Join-Path <<<<  $TOOLS_DIR "packages.config"
    + CategoryInfo          : InvalidData: (:) [Join-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.JoinPathCommand

Test-Path : Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.
Bei D:\my\little\project\build\build.ps1:78 Zeichen:15
+ if ((Test-Path <<<<  $PSScriptRoot) -and !(Test-Path $TOOLS_DIR)) {
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand

Test-Path : Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.
Bei D:\my\little\project\build\build.ps1:84 Zeichen:16
+ if (!(Test-Path <<<<  $PACKAGES_CONFIG)) {
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand

Test-Path : Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.
Bei D:\my\little\project\build\build.ps1:92 Zeichen:16
+ if (!(Test-Path <<<<  $NUGET_EXE)) {
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand

Test-Path : Das Argument kann nicht an den Parameter "Path" gebunden werden, da es NULL ist.
Bei D:\my\little\project\build\build.ps1:102 Zeichen:16
+ if (!(Test-Path <<<<  $NUGET_EXE)) {
    + CategoryInfo          : InvalidData: (:) [Test-Path], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.TestPathCommand

Set-Location : Das Argument kann nicht verarbeitet werden, da der Wert des Arguments "path" NULL ist. Ändern Sie den Wert des Arguments "path" in einen Wert ungleich NULL.
Bei D:\my\little\project\build\build.ps1:117 Zeichen:17
+     Set-Location <<<<  $TOOLS_DIR
    + CategoryInfo          : InvalidArgument: (:) [Set-Location], PSArgumentNullException
    + FullyQualifiedErrorId : ArgumentNull,Microsoft.PowerShell.Commands.SetLocationCommand

Der Ausdruck nach "&" in einem Pipelineelement hat ein ungültiges Objekt erzeugt. Ergebnis muss ein Befehlsname, ein Skriptblock oder ein CommandInfo-Objekt sein.
Bei Zeile:1 Zeichen:2
+ & <<<< "" install -ExcludeVersion -OutputDirectory ""
    + CategoryInfo          : InvalidOperation: (:String) [], RuntimeException
    + FullyQualifiedErrorId : BadExpression
```

**Comment by patriksvensson** [comment]
Luckily, I studied German for three years in high school :wink:

The problem is that `$PSScriptRoot` was introduced in PowerShell 2. We could probably do something like this to overcome this problem.

```powershell
if([string]::IsNullOrEmpty($PSScriptRoot)) {
  $PSScriptRoot = split-path -parent $MyInvocation.MyCommand.Definition;
}
```

Or, as you said warn about PowerShell 3 is needed for the bootstrapper script. I will take a look at this after work and see if I can find a good solution. Input is welcome :smile:

**Comment by patriksvensson** [comment]
@molehillrocker Actually, maybe you can verify that the above solution works since I don't have access to Powershell 2 (if you still have a colleague with PowerShell 2 that is).

**Comment by molehillrocker** [comment]
Unfortunately now everybody upgraded to a newer PowerShell version, so we cannot test it anymore. :tired_face:

**Comment by patriksvensson** [comment]
@molehillrocker I see. No problem, I'll just spin up a virtual machine tonight.

**Comment by phillipsj** [comment]
So I just implemented this fix and I received an error:

    The term 'Invoke-WebRequest' is not recognized as the name of a cmdlet, function, script file, or 
    operable program. Check the spelling of the name, or if a path was included, verify that the path is 
    correct and try again.
    At C:\Users\XXXXX\code\XXXXX\build.ps1:36 char:22
    +     Invoke-WebRequest <<<<  -Uri http://nuget.org/nuget.exe -OutFile $NUGET_EXE
    + CategoryInfo          : ObjectNotFound: (Invoke-WebRequest:String) [],   
    CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

    Could not find NuGet.exe
    At C:\Users\jphillips\code\ifb-blue-orchard\build.ps1:41 char:10
    +     Throw <<<<  "Could not find NuGet.exe"
    + CategoryInfo          : OperationStopped: (Could not find NuGet.exe:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find NuGet.exe

**Comment by devlead** [comment]
@phillipsj think Invoke-WebRequest came in PowerShell 3, version 5 is the most recent version.

You could probably leverage .net web client instead like this:
`(New-Object System.Net.WebClient).DownloadFile("https://www.nuget.org/nuget.exe", $NUGET_EXE)`

 Typed on mobile so might contain errors, but hope you get the gist of it.

**Comment by phillipsj** [comment]
@devlead Yep I just discovered it was version 3.  Thanks for the quick response.
