### ISSUE TITLE
Support NuGet 3 new parameters

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#438]
* Restore
  * `-MSBuildVersion` Specifies the version of MSBuild to be used with this command. Supported values are 4, 12, 14. By default the MSBuild in your path is picked, otherwise it defaults to the highest installed version of MSBuild.
  * `-FallbackSource` A list of packages sources to use as fallbacks for this command.
* Install
  * `-FallbackSource` A list of packages sources to use as fallbacks for this command.
* Pack
  * `-MSBuildVersion` Specifies the version of MSBuild to be used with this command. Supported values are 4, 12, 14. By default the MSBuild in your path is picked, otherwise it defaults to the highest installed version of MSBuild.
* Update
  * `-MSBuildVersion` Specifies the version of MSBuild to be used with this command. Supported values are 4, 12, 14. By default the MSBuild in your path is picked, otherwise it defaults to the highest installed version of MSBuild.

**Comment by patriksvensson** [comment]
We should probably add some information in the documentation that these only are available in NuGet 3.

**Comment by devlead** [comment]
@patriksvensson agree, and they're optional, any enums/strucs/etc. nullable.
