### ISSUE TITLE
Add ReportGenerator Support

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#462]
Add an alias around this:

https://www.nuget.org/packages/ReportGenerator/

To allow easy creation of code coverage reports for OpenCover, NCover, etc.

**Comment by yvschmid** [comment]
I'll give this one a go.

**Comment by gep13** [comment]
@yvschmid sweet! :+1: 

I was literally just starting to look at this, only spent amount 10 minutes on it though, and didn't get much further than creating the required classes, so happy to pass this over to you :smile_cat: 

Let me know if you want me to test anything for you.

**Comment by gep13** [comment]
I was having a chat with @patriksvensson in gitter about this one, that is why I didn't get much done on it, as I was a little confused about how to approach the glob pattern in the mandatory parameter, as I haven't really done much with that.  The suggestion that was come up with was to have some chained aliases, similar to this:

```
public static void ReportGenerator(ICakeContext context, string pattern, ReportGeneratorSettings settings)
{
  var reports = context.Globber.GetFiles(pattern);
  ReportGenerator(context, reports, settings);
}

public static void ReportGenerator(ICakeContext context, FilePath report, ReportGeneratorSettings settings)
{
  ReportGenerator(context, new[] { report }, settings);
}

public static void ReportGenerator(ICakeContext context, IEnumerable<FilePath> reports, ReportGeneratorSettings settings)
{
  // Call the report generator tool.
}
```

Which I think makes a lot of sense.  What are your thoughts?

**Comment by gep13** [comment]
Sorry, meant to mention you above @yvschmid

**Comment by yvschmid** [comment]
I'm more or less done - just the globbing thing left. :grin: Your solution looks great. I'll add it.

**Comment by gep13** [comment]
This was added in Cake 0.6.0: http://cakebuild.net/blog/2015/11/cake-v0-6-0-released
