### ISSUE TITLE
Add Coveralls.io support

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#464]
Add an alias for uploading reports to Coveralls.io, by supporting either:

https://www.nuget.org/packages/coveralls.io/
https://www.nuget.org/packages/coveralls.net/

or by directly interacting with the Coveralls end point.

**Comment by patriksvensson** [comment]
If this would be a Cake.Common addition, we should interact with the Coveralls end point directly and avoid taking a dependency on a third party library.

**Comment by gep13** [comment]
@patriksvensson how would this work?  As technically, it wouldn't be a tool then, as there is no exe for it to find and execute.  Are there any examples in the code base of doing things directly in an alias?

**Comment by patriksvensson** [comment]
@gep13 You're right, it wouldn't be a tool per se. I would say that you have the perfect opportunity to set an example for how this kind of stuff is done :smile:

**Comment by gep13** [comment]
Ha ha, I walked into that one! :stuck_out_tongue:  Let me see what I can come up with...

**Comment by gep13** [comment]
This has been created as an addin, which is available here: https://github.com/gep13/Cake.Coveralls
