### ISSUE TITLE
All tools should have an optional tool path

### ISSUE THREAD

**Issue by yvschmid** [cake-build/cake#469]
> @patriksvensson said...
> All tools should have an optional tool path. Not everyone has one, but they should :)¨

**Comment by patriksvensson** [comment]
Since I already started with this I'll assign this to me. Thanks for adding an issue!

**Comment by gep13** [comment]
:+1:

**Comment by gep13** [comment]
Let me know if/when this is going to land, and I can update the addin that I currently have, and any future ones that are on my radar, currently two others :smile_cat:

**Comment by patriksvensson** [comment]
Closed. Implemented in v0.6.0.
