### ISSUE TITLE
Add NUnit 3 support

### ISSUE THREAD

**Issue by rprouse** [cake-build/cake#471]
NUnit 3 is close to final release and it is incompatible with NUnit 2. It would probably be easiest to add a new NUnit3 tool. I assume pull requests are welcome? :smile: 

Another option is that NUnit 3 has a driver to run 2.x tests. Some of the settings may need to change, but a single tool would probably be easiest to use. Do you have a preference on the approach?

**Comment by patriksvensson** [comment]
@rprouse That's great news! 

The best approach is probably to add a `NUnit3` tool. This to make sure that we don't break scripts for people (this is what we did with `xUnit` and `xUnit2` and it has worked well so far). Would this be OK?

@devlead What is your opinion on this?

**Comment by devlead** [comment]
I agree with @patriksvensson new alias would be best.

**Comment by rprouse** [comment]
I think a new alias would be best too. I am concentrating on getting NUnit
3 out the door, but will try to fit this in.

**Comment by rprouse** [comment]
The RC for NUnit 3 should be out by the weekend :pray: I will circle back to this as soon after that as possible.

I renamed nunit-console.exe to nunit3-console.exe so we can tell which version is installed for the new alias.

**Comment by gep13** [comment]
@rprouse just wanted to follow up with this to see how things are progressing.  Do you need any help in getting the new alias created for NUnit 3?

**Comment by rprouse** [comment]
No, it looks pretty easy, but I've been concentrating on getting NUnit 3.0
out. I still need to get our Xamarin runners out and maybe our template
pack, then I can look at this.

**Comment by gep13** [comment]
Perfect! Just give us a shout if you run into any issues, here to help :smile:
