### ISSUE TITLE
Support OctoPack

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#472]
I'm thinking this would be done via extensions to the existing MSBuild settings & fluent interface DSL, as it just involves adding OctoPack-specific properties to your MSBuild command.

http://docs.octopusdeploy.com/display/OD/Using+OctoPack

**Comment by RichiCoder1** [comment]
Something like:
```C#
Task("Package")
	.Description("Package the website for Octopus")
	.Does(() =>
{
    MSBuild("./Dashboard.sln", settings =>
        settings
            .SetConfiguration(configuration)
            .WithTarget("Rebuild")
            .PublishPackageToHttp("http://my.server.com/api/v2")
            .PublishApiKey("903840932840spsda-sdasdasdas"));
});
```

**Comment by gep13** [comment]
Sounds like a great addition to me :+1:

**Comment by jrnail23** [comment]
@RichiCoder1, yeah, something like that, although there are several options and properties that can be set, so that might merit its own OctoPackSettings object and DSL builders.

**Comment by patriksvensson** [comment]
@jrnail23 @RichiCoder1 Sounds good to me.

So something like this then?

```csharp
Task("Package")
    .Description("Package the website for Octopus")
    .Does(() =>
{
    MSBuild("./Dashboard.sln", settings =>
        settings
            .SetConfiguration(configuration)
            .WithTarget("Build")
            .WithOctoPack(new OctoPackSettings()
                 .SomeOctoPackThing()
                 .SomeOtherOctoPackThing());
});
```

**Comment by jrnail23** [comment]
@patriksvensson, yeah, that's pretty much what I was thinking :smile:

**Comment by arri-cc** [comment]
Is anyone working on this issue?  If not I would like to get it done

**Comment by gep13** [comment]
@arri-cc I don't think anyone in the core team is looking at this yet, so unless @jrnail23 is currently looking at this, I would suggest that it is up for grabs.  Were you thinking about doing this as an Addin for Cake, or as a contribution into Cake directly?

**Comment by arri-cc** [comment]
@gep13 I think targeting an enhancement in either `Cake.Common.Tools.MSBuild` or `Cake.Common.Tools.OctopusDeploy` so that would be direct right?  Are there any rules regarding dependencies between tools?

**Comment by patriksvensson** [comment]
@arri-cc Would prefer if this was solved without involving MSBuild. Preferably this would be a wrapper around `Octo.exe`

**Comment by RichiCoder1** [comment]
OctoPack is literally an msbuild intergration :). That being said, an Octo tool wrapper would be cool too.

**Comment by patriksvensson** [comment]
@RichiCoder1 Yes I know. Was more thinking about what I would prefer :) As long as stuff doesn't touch the MSBuild tools in any way and is done by extension methods I'm fine with that as well.

**Comment by gep13** [comment]
For what is worth, my immediate thoughts were an addin around `octo.exe`, with some extension methods for the additional MSBuild arguments of packing NuGet packages, etc.

**Comment by arri-cc** [comment]
@gep13 An add-in `octo.exe` wrapper makes sense.  I just came across this gap last night when I started using Cake on a project, so I'm still coming up to speed with how this is architected.  I'll do some research and come back with some ideas to pitch.

**Comment by gep13** [comment]
@arri-cc perfect!  Feel free to have a look at this: https://github.com/gep13/Cake.ReSharperReports as an example of how to create an addin.

**Comment by cpx** [comment]
Since this has been lying around for a while, I could take a stab at it. Was thinking to implement it in the same way as the existing OctoPack and OctoCreateRelease aliases. Does that sound good?

**Comment by cpx** [comment]
I've started to look into this. Here is my suggestion so far.

octo pack takes the following arguments:
```
Basic options:

      --id=VALUE             The ID of the package; e.g. MyCompany.MyApp
      --format=VALUE         Package format. Options are: NuPkg, Zip.
                             Defaults to NuPkg, though we recommend Zip going
                             forward.
      --version=VALUE        [Optional] The version of the package; must be a
                             valid SemVer; defaults to a timestamp-based
                             version
      --outFolder=VALUE      [Optional] The folder into which the generated
                             NUPKG file will be written; defaults to '.'
      --basePath=VALUE       [Optional] The root folder containing files and
                             folders to pack; defaults to '.'

NuGet packages:

      --author=VALUE         [Optional, Multiple] Add an author to the
                             package metadata; defaults to the current user
      --title=VALUE          [Optional] The title of the package
      --description=VALUE    [Optional] A description of the package;
                             defaults to a generic description
      --releaseNotes=VALUE   [Optional] Release notes for this version of the
                             package
      --releaseNotesFile=VALUE
                             [Optional] A file containing release notes for
                             this version of the package

Advanced options:

      --include=VALUE        [Optional, Multiple] Add a file pattern to
                             include, relative to the base path e.g. /bin/-
                             *.dll - if none are specified, defaults to **
      --overwrite            [Optional] Allow an existing package file of the
                             same ID/version to be overwritten
```
This can be quite nicely built in the same style as the existing OctoCreateRelease and OctoPush methods:
```csharp
Task("Package")
    .Description("Packages the project")
    .Does(() =>
    {
        OctoPack("MyPackage", new OctopusPackSettings
        {
            Version = "1.2.3",
            OutFolder = "./octopacked/",
            BasePath = "./",
            Include = new[]
            {
                "bin/*.dll",
                "css/*",
                "js/*"
            },
            Overwrite = true,
            Format = OctopusPackFormat.NuPkg, // or OctopusPackFormat.Zip
            Author = "someone",
            Description = "my sweet package",
            ReleaseNotes = "good stuff was built",
            ReleaseNotesFile = "releasenotes.md",
        });
```

Thoughts?

**Comment by gep13** [comment]
@cpx looks good to me.  Which, if any of those properties are mandatory?  All mandatory parameters should be into arguments to the alias, not contained within the Settings class.

**Comment by cpx** [comment]
@gep13 Only the package ID is mandatory.

Another aspect is that author, description and release notes are only valid if the format is NuPkg. Should the tool have any special handling if you provide any of them for Zip packages? Throw exception?

**Comment by gep13** [comment]
@cpx ok, good to know.

With regard to the parameters, and when they used be used.... Does Octo handle the situation when parameters are passed in when they aren't required?  If so, I think it would be safer just to let it handle the issues, rather than trying to replicate the issue in the addin.  The thought process being that if octo, for some reason changes in a future release, we would need to update the logic as well, which feels wrong to me.

**Comment by cpx** [comment]
@gep13 Just tried out a few combos and octo ignores the NuGet-specific parameters when creating a Zip-package. As you say, this behavior could change in the future, so adding parameter validation to Cake that octo doesn't currently care about also feels wrong to me. Should we then stick to only validating the package ID parameter? That one seems unlikely to become optional.

**Comment by agc93** [comment]
Now we've got another Octopus tool with another set of parameter questions probably means we should revisit #1022  as well..

**Comment by cpx** [comment]
@agc93 Yeah I was thinking the same while I was implementing this. Pack is a bit special though, since it doesn't interact with the server it doesn't take apiKey or server parameters.

**Comment by patriksvensson** [comment]
Merged via #1218.

**Comment by nimendra** [comment]
Hi,
```
 Include = new[]
            {
                "bin/*.dll",
                "css/*",
                "js/*"
            },
```

doesnt work for me - 

> System.InvalidOperationException: Cannot create a package that has no dependencies nor content.

If I use specific paths, instead of bin/* it does create the nupkg.
Any ideas? Thanks

**Comment by patriksvensson** [comment]
@nimendra It would be better if you created a new issue or reached out in our Gitter channel than posting on a closed issue. Makes it impossible to track potential fixes over releases. Thanks!
