### ISSUE TITLE
Support MSBuild logger switches

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#473]
See "Switches for Loggers" section of [MSBuild Command-Line Reference](https://msdn.microsoft.com/en-us/library/ms164311.aspx)

**Comment by gep13** [comment]
Big thumbs up on this one! This is something that I have been thinking about, as I have a need to create a custom MSBuild Logger for something I am thinking about, so would be good to get OOTB support here! :+1:

**Comment by patriksvensson** [comment]
Sounds like a good addition to me! :+1:
