### ISSUE TITLE
Include links to software pages in the summary

### ISSUE THREAD

**Issue by ferventcoder** [cake-build/cake#475]
Wouldn't it be nice if https://github.com/cake-build/cake/blob/f44c6ae6b83f4115075a07ec2b1e3a081f4f7c5d/src/Cake.Common/Tools/ILRepack/ILRepackAliases.cs#L9-L11 included a link to the software so when I'm browsing along and come accross http://cakebuild.net/dsl/ilrepack, I can have a url to click on for more information in the summary? :)

**Comment by gep13** [comment]
This was included here: https://github.com/cake-build/cake/pull/931

This was also related to this: https://github.com/cake-build/cake/issues/927

The end result can be seen here, as asn example: http://cakebuild.net/dsl/chocolatey
