### ISSUE TITLE
ParseAssemblyInfo does not ignore commented information

### ISSUE THREAD

**Issue by molehillrocker** [cake-build/cake#476]
Scenario: The SolutionInfo.cs to parse looks like the following:

```
using System.Reflection;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.

[assembly: AssemblyCompany("Wild company")]
[assembly: AssemblyProduct("Wild product")]
[assembly: AssemblyCopyright("Copyright © 2015 Wild company")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers 
// by using the '*' as shown below:
// [assembly: AssemblyVersion("1.0.*")]

[assembly: AssemblyVersion("1.2.3.4")]
[assembly: AssemblyFileVersion("1.2.3.4")]
```

After parsing, the AssemblyInfoParseResult contains the commented assembly version ``1.0.*`` instead of the real ``1.2.3.4``. I think all lines that start with ``//`` resp. stuff between ``/* ... */`` should be ignored.

Unfortunately I have no time to fix the issue ATM, the simple workaround is to delete the commented assembly version. :see_no_evil:

**Comment by patriksvensson** [comment]
Great. Thanks for reporting this :+1:

**Comment by gep13** [comment]
I "think" I should be able to fix this in my open PR for parsing the entire AssemblyInfo file:

https://github.com/cake-build/cake/pull/457

I should be able to make the Regex for AssemblyVersion's stricter, i.e. be at the start of the line, and not include comments.

**Comment by molehillrocker** [comment]
@gep13 That would be great, since I'm likely not able to send you guys a PR until the middle of next week. :unamused:

**Comment by gep13** [comment]
@molehillrocker I have just created a PR which I think fixes this issue.

**Comment by molehillrocker** [comment]
:+1:

**Comment by gep13** [comment]
@molehillrocker not a problem at all.  Let me know if you run into any problems with it.
