### ISSUE TITLE
Support Chutzpah

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#477]
Chutzpah is a javascript test runner that we use on one of my work projects.

I actually already have a working addin written for it ([Cake.Chutzpah](https://github.com/jrnail23/Cake.Chutzpah)), but if there's any interest, I'd be happy to bring it into Cake.Common.

**Comment by patriksvensson** [comment]
Cool! :smile:
I have nothing against it being included in Cake.Common, but since you're creating an addin, we can always pull it in later when you're ready with it.

**Comment by phillipsj** [comment]
@jrnail23 @patriksvensson I was going to sit down and create this exact addin today.  Glad I found this.

**Comment by gep13** [comment]
@jrnail23 what are your thoughts on this?  Do you want to bring it into Cake.Common, or are you happy with it being a 3rd Party Addin?  If you want to keep it as an Addin, you might want to think about sending a PR similar to this one (https://github.com/cake-build/website/pull/20) to allow the documentation for your addin to be included within the Cake Website. Note, this relies on the necessaries attributes being added to your classes.

**Comment by patriksvensson** [comment]
@jrnail23 I think this would be more suitable as an addin.

**Comment by gep13** [comment]
@jrnail23 I am going to go ahead and close this, as it is not an issue for this repository, as the suggestion is to create a 3rd Party Addin for Cake.
