### ISSUE TITLE
Improve AddIn authoring experience

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#478]
Just an idea here -- perhaps we can put together some kind of guidance and even some scaffolding to help devs get started writing their own Cake add-ins.

Maybe someone could write a yeoman generator (@gep13? I know you did the VS Code syntax highlighting stuff in Yeoman) for this, or maybe a visual studio extension of some kind.

I'm thinking it could include things like:
- basic repo structure
- nuspec file
- default cake build script (maybe with AppVeyor CI built in?)
- dummy tool project, with references to the latest Cake nugets
- a dummy tool implementation with corresponding settings and basic aliases.
- a test project referencing Cake.Testing, optionally xunit, NSubstitute, etc.
- Some dummy tests that generally demonstrate the kinds of tests most addins should exercise.
- possibly a todo list in the form of a readme.md that covers the things that addin authors should generally do.
- any resources associated with addin documentation (the things you need to do to get your addin listed on http://cakebuild.net/addins)
- possibly Resharper settings and stylecop / fxcop settings to help ensure consistency with Cake's conventions.

**Comment by patriksvensson** [comment]
This is a great idea! We should definitely follow this up.
Yeoman generator would be nice (and xplat) but maybe also a VS project template?

**Comment by gep13** [comment]
@jrnail23 I think that this is a great idea!  I would love to be able to say that I know more about Yeoman to help out, but I literally followed some instructions, and did what was necessary for getting the Cake files working in VS Code, I have no idea where to start with making a new template.

In terms of moving forward with this, do we need to start creating a repo, somewhere, that this example project and folder structure could be created, and worked on?

As for the Visual Studio Template, would using SideWaffle be a way to go?

**Comment by DevWouter** [comment]
One of the things I love about Gem (Ruby NuGet tool) is that you can reference a git repository (including branch/tag/hash) and it would pull that repo, resolve the dependencies and optionally perform an install script. (see: http://guides.rubygems.org/publishing/#sharing-source-code about the git idea).

The idea of @jrnail23 is an awesome idea. It increases the likelyhood of good add-ins (we need a cooler name then add-ins) and makes it easy for everyone to extend the tool without a high learning curve.

Although I would avoid Visual Studio Templates, as supporting those is a nightmare and not everybody uses it, but you might take look at `C:\Program Files (x86)\Microsoft Visual Studio 11.0\Common7\IDE\ProjectTemplates`. Personally I think it would be cooler if we had `.\cake --create-new-egg=my_plugin` which then aids you in creating your own plug-in. Same argument goes for SideWaffle.

In addition I think that adding additional flavor/egg/add-in needs to be simpeler if you want this to be really taking off, however we might want that to be another issue all together ;)

However all things considered I think that this can simply be moved forward by creating a repo that can be considered the base template for all add-ins. Using VS templates, SideWaffle, Yeoman can then be based on that and can be considered an extra service.

**Comment by jrnail23** [comment]
@DevWouter, I think a "template" repo is probably the easiest starting point for this.  Maybe include a script that would loop through the repo and replace a token with your actual addin's name in all the files, etc.
That initial workflow pretty much automates what I did the other day when beginning my latest add-in (which is what gave me the idea in the first place).

**Comment by DevWouter** [comment]
@jrnail23 Agreed on the "template" repo, that will however we look at it always be the first step. 

Personally the most important thing is that it is easy to get a result. Remember your first time writing "Hello world"? That is the level of ease I would look for. With that in mind I have some doubts about the value of StyleCop. I don't mind being told that I break style, but only when I ask for it. Maybe it's because I change my coding style whenever I feel the need (I currently favor `if` in the K&R style). This might be a barrier for some people when they just need a quick add-in.

**Comment by jrnail23** [comment]
@DevWouter, I personally don't care about StyleCop at all :wink:
I only included it in there to promote consistency with the core Cake code.  I definitely wouldn't consider it a "hard" requirement.

**Comment by DevWouter** [comment]
@jrnail23 Good to know I'm not the only one that doesn't care about StyleCop :smiley: 

But it does rise an intresting question: Should we care about the style of people and projects that we don't control?

**Pros of dictating style**:
* Every add-in coder can skip the learning curve of another add-in
* Promoting an add-in to Cake.Core demands a whole lot less adjustment
* More likely to create a quality eco-system (We should call it a kitchen, not an eco-system!)

**Cons of dictating**
* Higher initial learning curve
* Conflicting coding-style (for example a tool that can be used in Cake, but also in something else)
* Less add-ins/eggs/cutery/flavor in the eco-system/kitchen
* More difficult to change coding style
* Raises questions about style in unsupported language (think javascript, VB (kill-me-please) or XML)

--- 

As for this issue, I think someone should just start and then go the iterative way. The repo should be something along the lines of _"The fastest way to give your cake that missing quality flavor"_ and the goal should be that it becomes the starting-point for everyone that wants to create an add-in.

> That shouldn't be too hard...&trade;

When the repository reaches a certain level of maturnity we should just ask the cake-build-team to adopt the project. 

@patriksvensson and @devlead: How would you like to see this done?

PS: I'm not saying we should start right now, but rather discus the proces

**Comment by gep13** [comment]
If you are looking to go the templating route, you might want to take a look at warmup:

https://github.com/chucknorris/warmup

which could do some of the initial heavy lifting for you.

**Comment by devlead** [comment]
There's now visual studio and vscode addins, that provide some templating, so if they lack anything please raise an issue in respective repo:
https://github.com/cake-build/cake-vs
https://github.com/cake-build/cake-vscode
