### ISSUE TITLE
BUG: CopyFile logs incorrect targetFilePath

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#486]
The log message written by `FileCopier.CopyFileCore` reports the source file path as the target file path:
```c#
context.Log.Verbose("Copying file {0} to {1}", absoluteFilePath.GetFilename(), absoluteFilePath);
```
So the log message makes it look like the file is just getting copied to itself (although the copy actually works correctly).

**Comment by patriksvensson** [comment]
Whoopsie. This is my fault... Sorry!
