### ISSUE TITLE
TeamCity: add ImportCoverageData method

### ISSUE THREAD

**Issue by jrnail23** [cake-build/cake#499]
Currently `ITeamCityProvider` has `void ImportData(string type, FilePath path)`, but when importing coverage data, an additional `tool` attribute is required ([TeamCity docs](https://confluence.jetbrains.com/display/TCD9/Manually+Configuring+Reporting+Coverage)):

> `##teamcity[importData type='dotNetCoverage' tool='<tool name>' path='<path to the results file>']`
> where tool name can be dotcover, partcover, ncover or ncover3.

**Comment by gep13** [comment]
This would be another great addition! :+1:

**Comment by patriksvensson** [comment]
I agree :+1:

**Comment by mholo65** [comment]
Duplicate of #723 and PR pending in #714 

(Sorry for not noticing this when I created issue #723)

**Comment by devlead** [comment]
Fixed by #714
