### ISSUE TITLE
Refactor ICakeEnvironment

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#502]
Right now, `ICakeEnvironment` is kind of a mess, mixing properties and methods for things.

I'm also not a fan of IsUnix-property which I think could be more fine grained i.e. we could add a OperatingSystem enum that gives more information such as Windows, OSX, Linux etc. We could even make this a flags enum and add additional more finegrained information such as what operating system, but not sure if that would be useful.

I would suggest that we make some changes.

It would make sense to introduce something like `IPlatform` that could keep information about OS and hardware. The ICakeEnvironment have a tendency to become a dumping ground for everything environment related and this would mean that we would keep platform specific stuff isolated.

* Move `bool Is64BitOperativeSystem()` to `IPlatform`
* Move `bool IsUnix()` to `IPlatform`
* Change `DirectoryPath GetApplicationRoot();` to `DirectoryPath ApplicationRoot { get; }`
* Add `IPlatform Platform { get; }`

```csharp
public interface IPlatform
{
  OperatingSystem OperatingSystem { get; }
  bool Is64Bit { get; }
  bool IsUnix { get; } // Could be an extension method for IPlatform
}
```

```csharp
public enum OperatingSystem
{
  Unknown = 0,
  Windows = 1,
  Linux = 2,
  OSX = 3
}
```

Not sure if we should expose the enum directly, or expose a class that 
contains information about the operating system (type/flavor, name, version) etc. 
Not sure if this information would be of interest to Cake users. 

**NOTE: Since this is a breaking change, we wouldn't actually remove the methods but mark them as obsolete and remove them sometime in the future.**

I will glady do this changes if you let me :smile:

**Comment by gep13** [comment]
This sounds like a good idea to me, your reasoning seems sound to me.

Agree with the breaking change, and would think this would bump to 0.7.0, not as a patch version.

**Comment by khellang** [comment]
It might be worth looking at the [CoreFX APIs](https://github.com/dotnet/corefx/blob/61449e6f36725f82bff2cf95bf24915775b8996d/src/System.Runtime.InteropServices.RuntimeInformation/ref/System.Runtime.InteropServices.RuntimeInformation.cs#L32-L39) to get this information. A lot of the APIs that are used currently doesn't existing in this new world.

This might be a place where you'd have to #ifdef and have two implementations of `IPlatform(Information?)`, one for full CLR and one for core...

**Comment by devlead** [comment]
System.Runtime.InteropServices and many others are on NuGet so those bridge the gap between Core & Standard CLR features sets.

Probably worth obsoleting stuff and then later remove if no one compains :wink:

**Comment by khellang** [comment]
> System.Runtime.InteropServices and many others are on NuGet so those bridge the gap between Core & Standard CLR features sets.

Sure, if you don't mind that dependency on full CLR :smile:

**Comment by devlead** [comment]
AFAIK you'd on .NETCore 5.0 add dependencies to
* System.Runtime (≥ 4.0.0)
* System.Reflection (≥ 4.0.0)
* System.Reflection.Primitives (≥ 4.0.0)
* System.Runtime.Handles (≥ 4.0.0)

**Comment by devlead** [comment]
As discussed on [Gitter](https://gitter.im/cake-build/cake?at=57456e7ecd96cbcf4f7082dc)

For child processes we could probably add an environment dictionary property to [ToolSetting](http://cakebuild.net/api/cake.core.tooling/d75cd243) and [ProcessSettings](http://cakebuild.net/api/cake.core.io/fbbd6704)  that optionally passed along to [ProcessStartInfo.Environment ](hhttps://msdn.microsoft.com/en-us/library/system.diagnostics.processstartinfo.environment.aspx)

Something we could look at during the `ICakeEnvironment` refactoring.

**Comment by gep13** [comment]
A related issue which should be tackled at the same time... https://github.com/cake-build/cake/issues/902
