### ISSUE TITLE
Add tests for AssemblyInfoParser

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#504]
AssemblyInfoParser seems to be missing tests for some attributes.

**Comment by gep13** [comment]
@patriksvensson interesting! I wonder why the bug I just fixed wasn't picked up by these tests.  Just reading over them quickly just now, looks like it should have?!?

**Comment by patriksvensson** [comment]
@gep13 I was looking through the tests, and I couldn't see that all attributes were covered. I might have missed something though.

**Comment by gep13** [comment]
The bug I just fixed, should have been covered by this:

https://github.com/cake-build/cake/blob/3cd377e2121d042371fbfeca702b26807444ce77/src/Cake.Common.Tests/Unit/Solution/Project/Properties/AssemblyInfoParserTests.cs#L105

But I haven't dug into why it didn't work.

**Comment by patriksvensson** [comment]
It never broke since ClsCompliant always had a value. As long as ClsCompliant is specified, the ComVisible should work. Nasty bug :smile:

**Comment by patriksvensson** [comment]
I'm closing this since I was clearly wrong. All attributes have test coverage.

**Comment by gep13** [comment]
Ah, gotcha :+1:
