### ISSUE TITLE
Create Chocolatey Package for Cake

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#505]
To allow people to install Cake globally, and run from everywhere.

**Comment by patriksvensson** [comment]
:+1: to this :smile:

**Comment by gep13** [comment]
Now that we have the Chocolatey Alias, it should be a breeze :-D

**Comment by gep13** [comment]
@patriksvensson I was actually keeping this one open, as a reminder to change to use the new OutputDirectory setting that the ChocoPack command exposes, but that wasn't ready until the latest release.  Now I will be able to do that again, or should I create another issue to cover that?

**Comment by patriksvensson** [comment]
Sorry! I didn't know. A new issue might be better for that but you decide :)

**Comment by gep13** [comment]
It's all good.  The fact that it wasn't clear why it was still open, is enough of a reason to have a separate issue. Will create one just now :-)
