### ISSUE TITLE
Decide on approach for NuGet and Chocolatey Pack

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#511]
Currently, the strategy that is used for creating NuGet and Chocolatey Packages is to store the nuspec file in source control.  Then, within build.cake, the NuGetPack and ChocolateyPack commands are used, to provide additional information, like version, releasenotes, files, etc.

However, the nuspec file is not actually required, as NuGetPack and ChocolateyPack can both create temp files, which are then used to do the actual creation of the nupkg's.

The first approach means some duplication of properties, like Copyright, Owners, etc, which could be made into consts within the build.cake file.

We need to make a decision about how to move forward with this.

**Comment by patriksvensson** [comment]
I prefer to use nuspecs, but if we move this to code then I think we at least should put it in another .cake file to reduce clutter.

**Comment by gep13** [comment]
This can now be closed.  We have settled on the approach, i.e. use a nuspec so that things are consistent.
