### ISSUE TITLE
NullReferenceException when using Information alias

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#521]
This issue is continuing the issue at Nunit/Nunit#930.

Some information about this issue (by @CharliePoole):

```
I'm running it on Windows 7.
I'm using the 0.6.0 zip from github cake-build/cake
My build file is the sample file shown here: https://github.com/cake-build/cake#2-create-a-cake-script

So here is what I just did, starting from scratch...
1. Created a temp directory
2. Made sure that the security setting on the zip was cleared
3. Unzipped, creating a temp\Cake directory
4. Began typing in the script a bit at a time, running it after each change.

All the results were as expected until I filled in the last bit, which I already suspected. 
That was the line
Information("Hello World!");
It gave me a null reference error.

I tried setting verbosity. It ran without error but still didn't produce the "Hello" output. If I used different settings I got more or less info from Cake but still no "Hello World!"

Finally, after running with verbosity set a few times, I removed that setting from the command line. It still didn't display anything but also didn't give an error.

So it seems to be something that only occurs right after install up to the point where you use a verbosity argument. Is it remembering that argument? Is it initializing something?

And of course, it's still not saying hello to me :-(

Next I'll try the bootstrapper.
```

**Comment by CharliePoole** [comment]
Here you go...

D:\temp>Cake\Cake.exe build.cake -verbosity=Diagnostic
Analyzing build script...
Analyzing D:/temp/build.cake...
Processing build script...
Creating script session...
Adding reference to mscorlib.dll...
Adding reference to System.dll...
Adding reference to System.Core.dll...
Adding reference to System.Data.dll...
Adding reference to System.Xml.dll...
Adding reference to System.Xml.Linq.dll...
Adding reference to Cake.Core.dll...
Adding reference to Cake.Common.dll...
Adding reference to Cake.exe...
Importing namespace Cake.Common...
Importing namespace Cake.Common.Build...
Importing namespace Cake.Common.Diagnostics...
Importing namespace Cake.Common.IO...
Importing namespace Cake.Common.IO.Paths...
Importing namespace Cake.Common.Net...
Importing namespace Cake.Common.Security...
Importing namespace Cake.Common.Solution...
Importing namespace Cake.Common.Solution.Project...
Importing namespace Cake.Common.Solution.Project.Properties...
Importing namespace Cake.Common.Solution.Project.XmlDoc...
Importing namespace Cake.Common.Text...
Importing namespace Cake.Common.Tools...
Importing namespace Cake.Common.Tools.Cake...
Importing namespace Cake.Common.Tools.Chocolatey...
Importing namespace Cake.Common.Tools.Chocolatey.ApiKey...
Importing namespace Cake.Common.Tools.Chocolatey.Config...
Importing namespace Cake.Common.Tools.Chocolatey.Features...
Importing namespace Cake.Common.Tools.Chocolatey.Install...
Importing namespace Cake.Common.Tools.Chocolatey.Pack...
Importing namespace Cake.Common.Tools.Chocolatey.Pin...
Importing namespace Cake.Common.Tools.Chocolatey.Push...
Importing namespace Cake.Common.Tools.Chocolatey.Sources...
Importing namespace Cake.Common.Tools.Chocolatey.Upgrade...
Importing namespace Cake.Common.Tools.DupFinder...
Importing namespace Cake.Common.Tools.Fixie...
Importing namespace Cake.Common.Tools.GitReleaseManager...
Importing namespace Cake.Common.Tools.GitReleaseManager.AddAssets...
Importing namespace Cake.Common.Tools.GitReleaseManager.Close...
Importing namespace Cake.Common.Tools.GitReleaseManager.Create...
Importing namespace Cake.Common.Tools.GitReleaseManager.Export...
Importing namespace Cake.Common.Tools.GitReleaseManager.Publish...
Importing namespace Cake.Common.Tools.GitReleaseNotes...
Importing namespace Cake.Common.Tools.GitVersion...
Importing namespace Cake.Common.Tools.ILMerge...
Importing namespace Cake.Common.Tools.ILRepack...
Importing namespace Cake.Common.Tools.InspectCode...
Importing namespace Cake.Common.Tools.MSBuild...
Importing namespace Cake.Common.Tools.MSTest...
Importing namespace Cake.Common.Tools.NSIS...
Importing namespace Cake.Common.Tools.NuGet...
Importing namespace Cake.Common.Tools.NuGet.Install...
Importing namespace Cake.Common.Tools.NuGet.Pack...
Importing namespace Cake.Common.Tools.NuGet.Push...
Importing namespace Cake.Common.Tools.NuGet.Restore...
Importing namespace Cake.Common.Tools.NuGet.SetApiKey...
Importing namespace Cake.Common.Tools.NuGet.SetProxy...
Importing namespace Cake.Common.Tools.NuGet.Sources...
Importing namespace Cake.Common.Tools.NuGet.Update...
Importing namespace Cake.Common.Tools.NUnit...
Importing namespace Cake.Common.Tools.OctopusDeploy...
Importing namespace Cake.Common.Tools.OpenCover...
Importing namespace Cake.Common.Tools.ReportGenerator...
Importing namespace Cake.Common.Tools.ReportUnit...
Importing namespace Cake.Common.Tools.Roundhouse...
Importing namespace Cake.Common.Tools.SignTool...
Importing namespace Cake.Common.Tools.WiX...
Importing namespace Cake.Common.Tools.XBuild...
Importing namespace Cake.Common.Tools.XUnit...
Importing namespace Cake.Common.Xml...
Importing namespace Cake.Core...
Importing namespace Cake.Core.Diagnostics...
Importing namespace Cake.Core.IO...
Importing namespace Cake.Core.Scripting...
Importing namespace System...
Importing namespace System.Collections.Generic...
Importing namespace System.IO...
Importing namespace System.Linq...
Importing namespace System.Text...
Importing namespace System.Threading.Tasks...
Compiling build script...
Error: System.NullReferenceException: Object reference not set to an instance of
 an object.
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.InitializerDimensions(BoundA
rrayInitialization init)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitAllElementInitializers(A
rrayTypeSymbol arrayType, BoundArrayInitialization inits, Boolean skipConstants)

   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitVectorInitializers(Array
TypeSymbol arrayType, BoundArrayInitialization inits)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArrayCreationExpression(
BoundArrayCreation expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpressi
on expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArgument(BoundExpression
 argument, RefKind refKind)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitArguments(ReadOnlyArray`
1 arguments, ReadOnlyArray`1 parameters)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitCallExpression(BoundCall
 call, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitExpression(BoundExpressi
on expression, Boolean used)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement
 statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitBlockStatement(BoundBloc
k block)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.EmitStatement(BoundStatement
 statement)
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.Generate()
   at Roslyn.Compilers.CSharp.CodeGen.CodeGenerator.Run(MethodSymbol meth, Bound
Statement block, ILBuilder builder, Module module, DiagnosticBag diagnostics, Bo
olean optimize, Boolean emitSequencePoints)
   at Roslyn.Compilers.CSharp.Compiler.GenerateMethodBody(TypeCompilationState c
ompilationState, MethodSymbol method, BoundStatement block, DiagnosticBag diagno
stics, Boolean optimize, Boolean emitSequencePoints, Func`2 mapFileNameToDebugDo
c, ReadOnlyArray`1 namespaceScopes)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.ProcessGeneratedMethods(TypeCom
pilationState compilationState)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileNamedType(NamedTypeSymbo
l symbol)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.<>c__DisplayClass6.<VisitNamedT
ype>b__4()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.WaitForWorkers()
   at Roslyn.Compilers.CSharp.MethodBodyCompiler.CompileAllMethodBodies(Compilat
ion compilation, Module moduleBeingBuilt, Boolean generateDebugInfo, DiagnosticB
ag diagnostics, CancellationToken cancellationToken)
   at Roslyn.Compilers.CSharp.Compiler.CompileAllMethodBodies(Compilation compil
ation, Module moduleBeingBuilt, Boolean generateDebugInfo, DiagnosticBag diagnos
tics, CancellationToken cancellationToken)
   at Roslyn.Compilers.CSharp.Compilation.Emit(ModuleBuilder moduleBuilder, IAss
emblyLoader assemblyLoader, Func`2 assemblySymbolMapper, CancellationToken cance
llationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyImage)
   at Roslyn.Compilers.CSharp.Compilation.CommonEmit(ModuleBuilder moduleBuilder
, IAssemblyLoader assemblyLoader, Func`2 assemblySymbolMapper, CancellationToken
 cancellationToken, Boolean recoverOnError, ReadOnlyArray`1& compiledAssemblyIma
ge)
   at Roslyn.Scripting.CommonScriptEngine.TryEmitSubmission(CommonCompilation co
mpilation, DiagnosticBag diagnostics, Type delegateType, Boolean collectible, Ca
ncellationToken cancellationToken, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.Compile(String code, String path, Diag
nosticBag diagnostics, Session session, Type delegateType, Type returnType, Canc
ellationToken cancellationToken, Boolean isInteractive, Boolean isExecute, Commo
nCompilation& compilation, Delegate& factory)
   at Roslyn.Scripting.CommonScriptEngine.Execute[T](String code, String path, D
iagnosticBag diagnostics, Session session, Boolean isInteractive)
   at Roslyn.Scripting.Session.Execute(String code)
   at Cake.Scripting.Roslyn.Stable.RoslynScriptSession.Execute(Script script)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath
, IDictionary`2 arguments) in c:\Source\Git\cake-build\cake\src\Cake.Core\Script
ing\ScriptRunner.cs:line 175
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(IEnumerable`1 args)

D:\temp>

**Comment by patriksvensson** [comment]
@CharliePoole Are you running this on a 32 or 64-bit OS?

**Comment by CharliePoole** [comment]
@patricksvensson 32

**Comment by patriksvensson** [comment]
@CharliePoole 

Ok, this is actually a known Roslyn issue (see #241) when running on 32-bit platforms with .NET 4.6 installed. This was a problem for 64-bit OS as well since we compiled with `Prefer 32-bit` enabled and we solved this in #247 by compiling for MSIL (Any CPU).

Good news is that there is are two workarounds for this. One that should work without problem, and another one that might work (depending on your preferences). Let us know if any of this worked for you.

### Workaround 1

The first workaround, is to use the Mono script engine. You do this by appending the `-mono` flag. This should work without problem.

```
D:\temp>Cake\Cake.exe build.cake -verbosity=Diagnostic -mono
```

### Workaround 2

The second (potential) workaround (if you really want to use the Roslyn script engine) is to use the experimental Roslyn bits. I'm not 100% sure this will work, but it's worth a try. You do this by appending the `-experimental` flag.

```
D:\temp>Cake\Cake.exe build.cake -verbosity=Diagnostic -experimental
```

**Comment by CharliePoole** [comment]
Both workarounds work for me, so I think you can close this. Is there any kind of environment variable where I can set up -mono as standard for all commands?

**Comment by gep13** [comment]
@CharliePoole glad to hear that you got this working!  I will close this issue.  We will update our documentation to mention this issue with 32bit Operating Systems.

I am not aware of any global flags or environment variables that you can use, but perhaps @devlead and @patriksvensson might be able to suggest something.
