### ISSUE TITLE
How do I specify the version in the #tool directive?

### ISSUE THREAD

**Issue by thomaslevesque** [cake-build/cake#525]
I'm using the `#tool` directive to reference the `NUnit.Runners` package:

    #tool "NUnit.Runners"

Currently it picks version 2.6.4, which is what I want, so it's OK. But Is there a way to specify the version explicitly? Because when NUnit 3.0 is released (if this day ever comes), I might not want to update immediately...

**Comment by patriksvensson** [comment]
@thomaslevesque

We've been talking (briefly) about introducing an URI for tools and addins i.e. `nuget://NUnit.Runners?version=2.6.4`. This would standardize arguments to tools and addins and also let us add handlers for other protocols (chocolatey, http, ftp, rsync etc).

No progress yet, but great that you created an issue for this so we have somewhere to discuss this.

**Comment by thomaslevesque** [comment]
I had something simpler in mind (perhaps `#tool "NUnit.Runners: 2.6.4"`), but a custom URI scheme is a good approach too.

**Comment by patriksvensson** [comment]
@thomaslevesque Yes, that was the initial idea, but we realized that there's going to be problems when we need to add more arguments such as source, excludeversion, nocache or prerelease. Using an URI scheme let us be more flexible in the future. Nothing's been decided yet though.

**Comment by DaveSenn** [comment]
Another option could be to get rid of the *#tool* directive and implement a method for specifying tool dependencies. Something like this:

```
Tool("NUnit.Runners")
	.Version("2.6.4") /*.Version("*"), "^1.2.3", "~1.2.3", ">1.2.3" ...etc. */
	.Protocol("NuGet")
	.Source("https://www.nuget.org") // .Sources(new[]{"https://www.nuget.org"})
	.Cache(true);
	 //…some other options
```

**Comment by thomaslevesque** [comment]
If we go this way, an even better alternative would be to automatically infer the dependencies based on usage ;)
e.g. if NUnit is used in the script, automatically add a dependency on NUnit.Runners.

It's probably not trivial to do, but it would be ideal, because currently it isn't documented anywhere that you need NUnit.Runners to use the [NUnit DSL methods](http://cakebuild.net/dsl/nunit)

**Comment by DaveSenn** [comment]
@thomaslevesque  And which version of the dependency should get resolved?
Your solution lakes the support for specifying some options like the version or caching.

**Comment by thomaslevesque** [comment]
>And which version of the dependency should get resolved?   
> Your solution lakes the support for specifying some options like the version or caching.

It would still be possible to specify a version explicitly (with the `#tool` directive or something else); if the version is not specified, it would just pick the latest version.

**Comment by devlead** [comment]
No need for a tool alias, you could just use the [ NuGetInstall(string packageId, NuGetInstallSettings settings)](http://cakebuild.net/api/cake.common.tools.nuget/bdfa6572/2451be66) alias to install what ever NuGet package you want.
The [NuGetInstallSettings](http://cakebuild.net/api/cake.common.tools.nuget.install/babcb33c) will allow you to configure version, source etc.

The [Tool directive](http://cakebuild.net/docs/fundamentals/preprocessor-directives) is for pre processing, analysis and gives us an opportunity reason about script dependencies.

Regarding specifying version and parameters in the `#tool`, `#addin` `#l` &`#r` directives I think think supporting existing, but also an URI like syntax would be an good option i.e.`nuget://package?version=xx&....and so on` (could allow for other protocols like http/sftp/ftp/ssh/rsync/etc).

**Comment by rprouse** [comment]
@thomaslevesque, now that NUnit 3 has been released, I think a workaround for people who want to install 2.6.4 of the nunit.runner is to specify the specific version in your packages.config, not in the build script. See http://cakebuild.net/docs/tools/installing-tools

An NUnit 3 alias will hopefully be out soon, see #532. It will run v2 and v3 NUnit tests. You should change your tool statement to `#tool "NUnit.Console"` and use the new NUnit3 option once it is available.

**Comment by thomaslevesque** [comment]
@rprouse , yes, I was using packages.config before. It's when I wanted to switch to using the `#tool` directive that I realized it didn't let me specify the version. I wasn't looking for a workaround, just suggesting an improvement ;)

**Comment by thomaslevesque** [comment]
I just realized that Cake scripts using `#tool "NUnit.Runners"` no longer work. They try to install the latest version of the package (3.0.1), but this package doesn't actually contain anything, it just has a dependency on NUnit.Console. When Cake looks for tool executables, it doesn't find any in NUnit.Runners, and says that it failed to install the package...

It's easy to fix (just use `#tool "NUnit.Console"` as suggested by @rprouse), but it's unfortunate that an update to NUnit broke the build for anyone using Cake and NUnit...

**Comment by rprouse** [comment]
@thomaslevesque it is unfortunate, but NUnit 3 is a total rewrite from NUnit 2. People upgrading to NUnit 3 will have to make changes like using the new NUnit 3 task introduced in 0.6.1 for Cake. It is unfortunate that it is not a seamless upgrade, but it is the price of progress. The new new NUnit 3 runner will continue to run Nunit 2 tests, so hopefully it will only require a few minor changes to build scripts to get up and running again.

If this isn't the case, please head over to the NUnit repo and file an issue with your use case. NUnit 3 is a breaking change, but we want to help people make the transition as painlessly as possible.

**Comment by thomaslevesque** [comment]
@rprouse I have no issue with the fact that NUnit 3 introduces breaking changes. What I meant is that it broke the build even for people who had no intention to upgrade right now, because the latest version is picked up automatically (since the `#tool` directive doesn't allow to specify a version).

**Comment by gep13** [comment]
@thomaslevesque I believe that the core requirement within this issue has now been met, as you can specify the version number that you want to use within both the #addin and #tool directive.  You can see more information about this here: http://cakebuild.net/docs/fundamentals/preprocessor-directives

I am going to close this issue, but feel free to re-open if required.

**Comment by thomaslevesque** [comment]
> I believe that the core requirement within this issue has now been met

Absolutely. Thanks!
