### ISSUE TITLE
Problem with running GitVersion on Build Server through Cake

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#526]
When running GitVersion using:

`gitversion /output buildserver`

the idea is that GitVersion will assert the semantic version of your git repository, and it will then create a number of Environment Variables, which can then be later used within your build script.

You can see GitVersion creating these environment variables in the log file here:

https://ci.appveyor.com/project/GaryEwanPark/resharperreports/build/0.3.0-PullRequest.16+7%20(Build%2028)#L169

Now, before I started using Cake, I used psake, and when executing GitVersion (using the `buildserver` flag) from my psake script, I was immediately able to consume the environment variables, as you can see here:

https://github.com/chocolatey/ChocolateyGUI/blob/develop/BuildScripts/default.ps1#L440

i.e. GitVersion is called here:

https://github.com/chocolatey/ChocolateyGUI/blob/develop/BuildScripts/default.ps1#L439

and the environment variables are immediately consumed.  Now, this "magic" was made possible on AppVeyor thanks to some work that was done by @FeodorFitsner which allowed the psake (PowerShell) calling script to immediately "see" the environment variables created by GitVersion.  i.e.

PowerShell -> GitVersion = works!

However, in the case of running GitVersion through Cake, we have:

PowerShell -> Cake -> GitVersion != works

So my question is, what needs to happen to allow this process to also work?

Is it a change to GitVersion?
Is it a change to Cake?
Is it a change to AppVeyor?

Is it not even possible?

There is a workaround, which is to call GitVersion twice.  Once with the `/output buildserver` flag, which normalizing the Git Repository, and sets build number, etc, and once without that flag, to simply return the version number, but that feels like a bit of a hack.

There is also an open issue on GitVersion to also return the JSON result, when running with the `buildserver` flag, https://github.com/GitTools/GitVersion/issues/675, but not sure if this is going to get implemented or not.

Just wanted to put this out there to see what the thoughts were.

**Comment by FeodorFitsner** [comment]
The "rule of thumb" with environment variables is that they are passed from parent process to child processes only.

The magic in "PowerShell -> GitVersion" scenario is possible because for each variable GitVersion calls AppVeyor Build Agent (parent process) REST API and modifies its environment variables. The command (child process) called next to "GitVersion" executable inherits modified parent process variables.

When you use the same technique in "PowerShell -> Cake -> GitVersion" scenario GitVersion still modifies "PowerShell" environment variables, but "Cake" is unaffected as it continues running with previously set environment.

Feels like something can be implemented in Cake consuming say JSON produced by GitVersion and adjusting Cake environment before calling the next command.

**Comment by gep13** [comment]
@FeodorFitsner said...
Feels like something can be implemented in Cake consuming say JSON produced by GitVersion and adjusting Cake environment before calling the next command.

Yes, this had occurred to me as well, however, this would rely on GitVersion being modified to return the JSON response, when being called with `/output buildserver`, which currently it does not.

Thanks for getting back to me about this!

**Comment by RichiCoder1** [comment]
Yup. The way I have it setup at my work is to have GitVersion output JSON and then parse that. Never got env vars working.

**Comment by devlead** [comment]
@RichiCoder1 indeed JSON sounds like the way to go.

**Comment by gep13** [comment]
>@RichiCoder1 said...
Yup. The way I have it setup at my work is to have GitVersion output JSON and then parse that. Never got env vars working.

>@devlead said...
indeed JSON sounds like the way to go.

Unfortunately, that alone isn't going to work :cry: 

In order for GitVersion to correctly assert the semantic version number, it needs to know the entire history of the repository.  However, this is counter to what most CI systems want, because they want to checkout only what is required to do the build.  As a result, the first thing that GitVersion does is to `normalise` the missing branches, by fetching them from the remote repository.  You can see this happening here:

https://ci.appveyor.com/project/GaryEwanPark/resharperreports/build/0.3.0-PullRequest.16+7%20(Build%2028)#L127

With all the branch information in place, GitVersion can then, with all certainty, asset the semantic version number of the repository.  Running GitVersion alone (i.e. outputting the JSON) doesn't do that.  In addition, running with `/output buildserver` does other "stuff" like setting the version number of the build and outputting environment variables (as discussed).  So, in order to work correctly on the build server, I would need to do:

```
gitversion /output buildserver /updateassemblyinfo
gitversion
```

where the second call to GitVersion is required to retrieve the version number in JSON format, to then consume later in the build script.

**Comment by JakeGinnivan** [comment]
The good news is that the next release of GitVersion will cache the version it calculates, so the second call will be almost instant.

**Comment by gep13** [comment]
@JakeGinnivan sweet! Do you know when you are planning the next release?  There are now a few things in the next version that I would like to start using :smile:

**Comment by JakeGinnivan** [comment]
Pretty soon, maybe today or tomorrow. Think I have closed off most of the bugs I want then can focus on v4 which will fix some larger scale stuff

**Comment by gep13** [comment]
This will be implemented here: https://github.com/cake-build/cake/issues/1128
