### ISSUE TITLE
Create a Visual Studio Code extension for Cake

### ISSUE THREAD

**Issue by rprouse** [cake-build/cake#530]
I followed the steps in your docs to add Cake support to Visual Studio Code and it works great. My copy is at https://github.com/rprouse/vscode-cake

I'd also created a theme for Visual Studio Code. When they announced extensions for VSCode today, I took my theme and had it converted to an extension, packaged and uploaded to the [Visual Studio Marketplace](https://marketplace.visualstudio.com/#VSCode) in less than an hour.

It would be just as easy to do the same for the Cake support, but it likely should be owned and published by the Cake team rather than me.

Docs are at https://code.visualstudio.com/docs/extensions/overview

The page on publishing is at https://code.visualstudio.com/docs/tools/vscecli

To save some digging, an easy approach would be,

- Take my code at https://github.com/rprouse/vscode-cake
- [Generate a hello world extension](https://code.visualstudio.com/docs/extensions/example-hello-world)
- Update my project.json by looking at the one in the generated extension. Publisher should be a lowercase name like cake-team. A human readable name is attached to the token created when publishing.
- Copy the .vscode directory from the generated extension so you can F5 test from VSCode
- Add an icon. Not sure if it needs to be svg.
- Test and publish.

**Comment by gep13** [comment]
@rprouse this is a great idea!  Thanks for the heads up!

@patriksvensson can we get a repo added to the cake-build organisation so that we can have somewhere to put this, assuming you think it is a good idea?

**Comment by patriksvensson** [comment]
Very cool! Great job!

We already have a publisher for the VSO extensions, so I think we can use that one. Will set up a repo once I get home!

**Comment by rprouse** [comment]
Feel free to push the code from my repo into it as a starting point. You could also try running through the steps in your docs again with the updated yo generator. They might just give you 90% of what you need compared with what I created with VSCode 0.9.1.

**Comment by gep13** [comment]
@RichiCoder1 said...
All of the above in theory.

Cool!  Do you know how that is progressing then?  Has the plugin model been rolled out?

**Comment by gep13** [comment]
@rprouse just realised that the theme that you were referring to is the Son of Obsidian theme, which is the one that I use everywhere else!  Thanks for getting that created! :+1:

**Comment by patriksvensson** [comment]
@rprouse We now have a Visual Studio Code extension for Cake. Thank you!

@gep13 Just realize that we didn't credit @rprouse in the blog post. Is this something that can be updated? :smile:

**Comment by gep13** [comment]
@patriksvensson very good point! https://github.com/cake-build/website/pull/32

**Comment by gep13** [comment]
http://cakebuild.net/blog/2015/11/cake-extensions
