### ISSUE TITLE
StartProcess hangs sometimes with large input

### ISSUE THREAD

**Issue by Redth** [cake-build/cake#535]
If the process you are running is redirecting standard output and it has a lot of output, it can cause cake to hang on the end of the process.

Take for instance this script: https://gist.github.com/Redth/a6dbe4fa5ad287759eb2

(Assuming a large file `data.txt` exists on unix for testing this)

```cake
var TARGET = Argument ("target", Argument ("t", "Default"));

Task ("Default").Does (() =>
{
	IEnumerable<string> stdout = new List<string> ();

	if (IsRunningOnWindows ()) {
		StartProcess ("dir", new ProcessSettings { 
			Arguments = "C:\\Windows\\System32",
			RedirectStandardOutput = true,
		}, out stdout);
	} else {
		StartProcess ("cat", new ProcessSettings { 
			Arguments = "data.txt",
			RedirectStandardOutput = true,
		}, out stdout);
	}
});

RunTarget (TARGET);
```

**Comment by devlead** [comment]
@Redth question as stdout is an enumerable, your list assignment won't be used.
Does it still hang for you if you enumerate the enumerable something like below?
```cake
var TARGET = Argument ("target", Argument ("t", "Default"));

Task ("Default").Does (() =>
{
    IEnumerable<string> stdout;

    if (IsRunningOnWindows ()) {
        StartProcess ("dir", new ProcessSettings {
            Arguments = "C:\\Windows\\System32",
            RedirectStandardOutput = true,
        }, out stdout);
    } else {
        StartProcess ("cat", new ProcessSettings {
            Arguments = "data.txt",
            RedirectStandardOutput = true,
        }, out stdout);
    }
    var result = new List<string> (stdout);
});
```

**Comment by devlead** [comment]
@Redth let me know if that doesn't work, I have some ideas to optimize the method that we could try.

**Comment by patriksvensson** [comment]
@devlead [I took a look at this a month or so back](https://gitter.im/cake-build/cake?at=56562946f59a8f0758a6e597), and it looks like the internal stdout/err buffer is getting full, but there are workarounds for this: http://stackoverflow.com/a/7608823/936

**Comment by devlead** [comment]
Yes, also as enumerable is lazy ave you need to poll from it it won't pop the stream until you iterate over it leaving it full until disposed.
You can use the events in an otherwise single threaded app it might lead to dead locks.

**Comment by devlead** [comment]
I'll submit an PR for this shortly.
