### ISSUE TITLE
FXCop support

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#54]

**Comment by cgourlay** [comment]
I would be interested in picking this up. What sort of support for FxCop was in mind?

**Comment by patriksvensson** [comment]
@cgourlay: Thanks for your interest in helping out with Cake! Much appreciated! :smile:

To be honest, I don't know... FXCop usage is normally defined as a MSBuild task, and only require FXCop to be installed on the computer (if VS2010 or higher is not installed), so I'm not certain what kind of support would be needed. Perhaps this issue should be closed.

What do you think?

**Comment by cgourlay** [comment]
@patriksvensson - I've no strong feelings either way. I just happened to stumble across this project yesterday, think it is terrific and am keen to contribute to it. I was looking to add some other metrics (e.g. code coverage output) but figured this existing issue would be a good starting point to allow me familiarise myself with the code.

**Comment by patriksvensson** [comment]
@cgourlay: Glad to hear that!

Code coverage is actually something that would be really sweet to have support for, preferably something open like [OpenCover](https://github.com/OpenCover/opencover) which probably will gain more traction now since it's used in the CoreFX project.

Feel free to open an issue if there's something specific you would want support for and contribute to, and we can continue the discussion. If you have questions in general, you could also come by the [Gitter room](https://gitter.im/cake-build/cake).

**Comment by phillipsj** [comment]
@patriksvensson @gep13 This is one that I was curious if still valid. There is DotCover and OpenCover support and as stated above FxCop can just be part of the build task and really isn't widely used anymore.

**Comment by gep13** [comment]
@phillipsj agreed.  Think this one can be closed out.
