### ISSUE TITLE
Adding support for Atlasssian Bamboo Build Server 

### ISSUE THREAD

**Issue by krippz** [cake-build/cake#544]
We use the Atlasssian build server called Bamboo, I'd like the niceness of being able to do  ` if(BuildSystem.IsRunningOnBamboo() == true)
{
 ... 
}`  among other things. 

This would probably improve my build scripts :) a bit.

I could take a look at what would be possible with the Bamboo API, see how it compares to the TeamCityProvider and AppVeyorProvider API:s

**Comment by patriksvensson** [comment]
@krippz This sounds like a great idea. Can't have too many CI server integrations :+1:

**Comment by devlead** [comment]
Indeed :+1:

**Comment by devlead** [comment]
@krippz Hi,
Just FYI @atlassian have granted us an OSS license for Bamboo and I've setup an environment so we can test any new Cake Bamboo features with.
I'ts publicly accessible using below url
[cakebuild.atlassian.net/builds/browse/CAKE-CAKE ](https://cakebuild.atlassian.net/builds/browse/CAKE-CAKE)
[![Bamboo Cake](https://bambooshield.azurewebsites.net/planstatus/Flat/CAKE-CAKE.svg)](https://cakebuild.atlassian.net/builds/browse/CAKE-CAKE)
Below's some environment variables that might be useful for provider, `bamboo_buildNumber` would probably be an good indicator for `BuildSystem.IsRunningOnBamboo()`, also `bamboo_planKey` and `bamboo_buildKey` are very useful when working with Bamboo builds (i.e. api uses them heavily)

|Name        |Value|
|-------------:|-------|
|`bamboo_agentId`|688148|
|`bamboo_agentWorkingDirectory`|C:\build|
|`bamboo_build_working_directory`|C:\build\CAKE-CAKE-JOB1|
|`bamboo_buildKey`|CAKE-CAKE-JOB1|
|`bamboo_buildNumber`|28|
|`bamboo_buildPlanName`|Cake - Cake - Build Cake|
|`bamboo_buildResultKey`|CAKE-CAKE-JOB1-28|
|`bamboo_buildResultsUrl`|https://cakebuild.atlassian.net/builds/browse/CAKE-CAKE-JOB1-28|
|`bamboo_buildTimeStamp`|2015-12-04T14:43:49.152+01:00|
|`bamboo_capability_system_agent_environment_ebs_optimised`|false|
|`bamboo_capability_system_builder_msbuild_MSBuild_v4_0__32bit_`|C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe|
|`bamboo_capability_system_builder_msbuild_MSBuild_v4_0__64bit_`|C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe|
|`bamboo_capability_system_git_executable`|C:\opt\git-2.6\bin\git.exe|
|`bamboo_capability_system_hg_executable`|C:\opt\mercurial\hg.exe|
|`bamboo_planKey`|CAKE-CAKE|
|`bamboo_planName`|Cake - Cake|
|`bamboo_repository_branch_name`|develop|
|`bamboo_repository_git_branch`|develop|
|`bamboo_repository_git_repositoryUrl`|https://github.com/cake-build/cake.git|
|`bamboo_repository_git_username`|devlead|
|`bamboo_repository_name`|Cake/Develop|
|`bamboo_repository_previous_revision_number`|d4a3a4cb304548450e3cab2ff735f778ffe58d03|
|`bamboo_repository_revision_number`|b8926004869448c0df7ac589f86ed42e3d6e3001|
|`bamboo_resultsUrl`|https://cakebuild.atlassian.net/builds/browse/CAKE-CAKE-JOB1-28|
|`bamboo_shortJobKey`|JOB1|
|`bamboo_shortJobName`|Build Cake|
|`bamboo_shortPlanKey`|CAKE|
|`bamboo_shortPlanName`|Cake|
|`bamboo_working_directory`|C:\build\CAKE-CAKE-JOB1|

**Comment by krippz** [comment]
Sweet! 
I was thinking of exposing the bamboo env vars 😀 
I'll check what more might be possible without having a bamboo plug in but I'll start with the env vars.

**Comment by krippz** [comment]
So I've started to implement bamboo support, And I'd like to reuse some of 'AppVeyorInfo' because the environment parts are a good fit, you mind if I restructure 'AppVeyorInfo'  a bit?

**Comment by patriksvensson** [comment]
@krippz I think it's better if you create new structures for Bamboo than to try to make something generic to be honest. Code duplication is not an issue for us in this case.

**Comment by devlead** [comment]
@krippz don't refactor AppVeyor classes first, do a WIP (work in progress) PR and we'll review. Easier for us to review, test, give feedback and merge if it doesn't affect existing code.
We can always refactor in a separate PR later.

**Comment by krippz** [comment]
Sweet! I'd thought to ask first, haven't contributed in this way before :) 
I'll do a WIP PR later when I get home.

**Comment by gep13** [comment]
@krippz your PR should be targetting the develop branch of this repository!

Thanks in advance for your contributions to Cake! :+1:
