### ISSUE TITLE
Chocolatey Package doesn't have correct Copyright information

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#548]
Either the nuspec needs to change:

https://github.com/cake-build/cake/blob/develop/nuspec/Cake.Portable.nuspec#L19

Or the build.cake needs to change:

https://github.com/cake-build/cake/blob/develop/build.cake#L163

or overwrite what is in the nuspec.

**Comment by devlead** [comment]
@gep13 start with https://github.com/cake-build/cake/blob/develop/nuspec/Cake.Portable.nuspec#L19 so it's same across files.

Then step 2 we can look at refactoring build script reusing common data like copyright and so on.

**Comment by gep13** [comment]
:+1:

**Comment by patriksvensson** [comment]
I've fixed this and pushed package to Chocolatey this morning. Will push code fix during my lunch.

**Comment by gep13** [comment]
Cool, I was putting this issue here so I wouldn't forget about it :smile:

**Comment by gep13** [comment]
This was corrected here: https://github.com/cake-build/cake/commit/d1ddf90c2457f55c55d2cab309fda42bb11eb733
