### ISSUE TITLE
CakeEnvironment.GetTargetFramework throws on Mono

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#549]
For some reason [AppDomainSetup.TargetFrameworkName](https://github.com/mono/mono/blob/b7a308f660de8174b64697a422abfc7315d07b8c/mcs/class/corlib/System/AppDomainSetup.cs#L300) returns null on Mono which causes [CakeEnvironment.GetTargetFramework](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/CakeEnvironment.cs#L130) to throw.

We should return a default framework, preferably .NET 4.5 if we can not resolve the current framework as we're supposed to. We might need to find a more permanent fix in the future though.

**Comment by jrnail23** [comment]
ugh... sorry this one was on me.  I didn't have access to a Mono environment to test. :frowning:

**Comment by patriksvensson** [comment]
@jrnail23 Not your fault. Bugs happen :smile:
