### ISSUE TITLE
NuGetPack support for csproj files

### ISSUE THREAD

**Issue by gertjvr** [cake-build/cake#551]
I had a quick look at the NuGetPacker source and seem it would be easy to include a conditional check if your passing a csproj or nuspec file and take to appropriate action. 

Happy to submit a pull request if this feature is something your interesting in.

**Comment by luisgoncalves** [comment]
This is [supported by now](http://cakebuild.net/api/cake.common.tools.nuget/bdfa6572/f4bfefe4). This issue can be closed.

**Comment by gep13** [comment]
@luisgoncalves agreed, thanks for catching this!

This actually seems to be a duplicate of this: https://github.com/cake-build/cake/issues/637
