### ISSUE TITLE
Compiler error using -mono

### ISSUE THREAD

**Issue by CharliePoole** [cake-build/cake#555]
When the following script is run using the -mono option, it results in a compiler error with the message "The name 'message' is not known in the current context"

```
var message = "Hello";

void SendMessage()
{
    Console.WriteLine(message);
}

Task("Default")
    .Does(() =>
    {
        SendMessage();
    });

RunTarget("Default");
```

This is pretty inconvenient, because it limits the ability to refactor a script using methods that access global variables.

**Comment by devlead** [comment]
Hi @CharliePoole ,

This is unfortunately an known issue with mono, there's a work around though, by using a delegate you can achieve refactoring in a similar way:

```cake
var message = "Hello";

Action SendMessage = ()=> Console.WriteLine(message);

Task("Default")
    .Does(() =>
    {
        SendMessage();
    });

RunTarget("Default");
```

will see if we can document this better or come up with some code generation magic,
We're also looking in to providing a standard way of sharing state, meanwhile suggested code above should work.

**Comment by CharliePoole** [comment]
While you're documenting, I have also been bitten by the fact that the mono compiler requires those "global" var declarations to appear before any references. That's a small change, of course.

It seems that folks wanting to run their scripts cross-platform should probably use -mono all the time, so that the scripts actually behave the same way on all platforms. Unfortunately, that's not how I did it. :-(

**Comment by devlead** [comment]
Yes variables indeed need to be declared before they're used, as they're currently in the same scope. 
Hopefully they'll release an xplat Roslyn soon, would make it allot simpler to support only one engine.
By we'll keep trying to mediate any variations between the runtime as much as we can.

Thanks for your feedback, it's really valuable for us and we'll try to see if we can make usage more clear, any suggestions are welcome and we do accept issues & pull requests( [cake-build/website](https://github.com/cake-build/website) ) if any obvious errors on the web site are found.

**Comment by devlead** [comment]
Closed due to inactivity.
