### ISSUE TITLE
Compilation Issue with ternary operator and arrays

### ISSUE THREAD

**Issue by CharliePoole** [cake-build/cake#561]
The declaration of z in the following causes an error on Linux. I haven't had the chance to try on Windows yet.

```
var x = new string[] { "WINDOWS", "LINUX" };
var y = IsRunningOnWindows() ? "WINDOWS" : "LINUX";
var z = IsRunningOnWindows() ? new string[] { "WINDOWS" } : new string[] { "LINUX" };
```

**Comment by patriksvensson** [comment]
@CharliePoole Might be a Mono compiler issue. Will take a look at it later today. Thanks for reporting it!

**Comment by devlead** [comment]
@CharliePoole there's indeed some Mono issue here, works on Roslyn. Could be an issue with the Mono codegen too.
If you add parenthesis is will compile though.
```csharp
var x = new string[] { "WINDOWS", "LINUX" };
var y = IsRunningOnWindows() ? "WINDOWS" : "LINUX";
var z = IsRunningOnWindows() ? (new string[] { "WINDOWS" }) : (new string[] { "LINUX" });
```

**Comment by devlead** [comment]
Closed due to inactivity.

**Comment by CharliePoole** [comment]
Doesn't the bug still exist?
