### ISSUE TITLE
Feature: Add support for SSH and SFTP

### ISSUE THREAD

**Issue by louisfischer** [cake-build/cake#562]
Great OSS. Not sure if any one has requested this feature or if it is even possible. How possible would it be to add Core support for SSH and SFTP?

**Comment by patriksvensson** [comment]
@louisfischer Thank you!

We will probably not support SSH and SFTP as core support since there isn't any SSH/SCP/SFTP protocol wrappers in the .NET-framework and no default tool to wrap. As an addin it would be possible though.

**Comment by MihaMarkic** [comment]
Here it is, support for [Pscp](https://www.nuget.org/packages/Cake.Pscp/1.0.0) (Putty's SCP)

**Comment by MihaMarkic** [comment]
Implemented also plink (ssh) in v1.1.

**Comment by gep13** [comment]
@MihaMarkic should this now be here: https://www.nuget.org/packages/Cake.Putty/

**Comment by MihaMarkic** [comment]
Yes, I changed it already. Sorry for that, I first implemented Pscp and than got an idea to implement Plink as well. Hence I merged them to single addin.

**Comment by gep13** [comment]
@MihaMarkic not a problem at all, just wanted to check!  That you for your contributions to the Cake community! :+1:

**Comment by MihaMarkic** [comment]
Hey, you're welcome. It is a pleasure to extend Cake. (FYI I created also Cake.Docker)

**Comment by gep13** [comment]
>@MihaMarkic said...
(FYI I created also Cake.Docker)

Yip, that one I was already aware of :+1:

**Comment by gep13** [comment]
@louisfischer I think we can go ahead and close this issue, as this seems to be covered in the Putty Addin: https://www.nuget.org/packages/Cake.Putty/  Feel free to re-open if required.
