### ISSUE TITLE
Better Contribution Guidelines

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#563]

**Comment by gep13** [comment]
To include things like:

- start with addin's
- coding style
- document aliases

Examples:
https://github.com/dotnet/corefx/blob/master/Documentation/coding-guidelines/coding-style.md
http://www.mono-project.com/community/contributing/coding-guidelines/

**Comment by patriksvensson** [comment]
@cake-build/team I think this could be closed. Agree?

**Comment by devlead** [comment]
@patriksvensson agree.

**Comment by patriksvensson** [comment]
@devlead Perfect. @gep13 If you disagree, feel free to reopen this.
