### ISSUE TITLE
Add Gitter and Twitter Notifications

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#568]
- for when builds pass/fail

**Comment by gep13** [comment]
This is related to this: https://github.com/cake-build/cake/issues/553

Combine into one issue.  So we want Gitter/Slack notifications when publishing happens to:

>When a push to Nuget and MyGet happens.

**Comment by gep13** [comment]
This issue would require having access to the overall build success/failure within the TearDown method.  However, this information is not currently available, so going to delay this task.

**Comment by gep13** [comment]
This is on hold until this issue is resolved https://github.com/cake-build/cake/issues/686

**Comment by gep13** [comment]
Actually, this is on hold until this issue is resolved: https://github.com/cake-build/cake/issues/743

**Comment by gep13** [comment]
Now that #743 has been completed.  We can look to getting this added in again :-)

**Comment by patriksvensson** [comment]
@gep13 Hmm, we never added a context to Teardown that holds the state of the build. Not sure if we need to add this somehow.

**Comment by gep13** [comment]
@patriksvensson oh, really, I thought we had.  Is there a reason that we can't add it there?

**Comment by gep13** [comment]
@patriksvensson so what exactly is required to be passed into TearDown in order to have access to whether a build passed/failed?

**Comment by gep13** [comment]
This requires https://github.com/cake-build/cake/issues/1089 to be completed first

**Comment by devlead** [comment]
@gep13 #1099 seems to be completed now.

**Comment by gep13** [comment]
@devlead yes, this is one of the things I want to add into our build process for the next release, I.e. Knocking off some of the manual tasks we do as part of the release process.

**Comment by gep13** [comment]
Decided to go with only Gitter and Twitter notifications just now.  Other notifications are handled through existing integrations.

**Comment by devlead** [comment]
Fixed by #1418
