### ISSUE TITLE
Rename main branch to master

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#570]
Is this possible?  What are the side effects?

**Comment by devlead** [comment]
Will take side effect notes as I see them
- [ ] AppVeyor only builds main / dev https://github.com/cake-build/cake/blob/develop/appveyor.yml#L17
- [ ] Release notes https://github.com/cake-build/cake/blob/develop/build.cake#L326
- [ ] Forks
- [x] Links - Googled & search thru code couldn't find any important references to main branch, also develop is default.
- [ ] Released

To rename could just be something like
```
git push -u origin main:master
git branch -m main master
```

A safer way would be to just checkout main into master branch and then add an protected branch [status check](https://developer.github.com/v3/repos/statuses/) for main that including administrators so no one could even by accident push to main.
Then a couple of released in delete and deprecate the main branch,

**Comment by ferventcoder** [comment]
Okay - renaming a long lived branch could have other unintended side effects - I would recommend finding someone that has done it and see if they can provide good feedback into the costs versus benefits

For instance, I can think of a couple of things you may be missing here:

- All current PRs at the time of the change may need to be rerouted (achievable but something to understand)
- You did mention forks - but understanding that may mean folks may submit something off of main thinking that still exists and they are on latest and will later find that they are way behind. Documentation here is helpful :)

**Comment by gep13** [comment]
After discussion, going to leave this the way it is. It ain't broke, so leave it alone.
