### ISSUE TITLE
NuGetPack and (un)portable nuspec files

### ISSUE THREAD

**Issue by bilke** [cake-build/cake#572]
I am on Mac OS and would like to create a nuget package with `NuGetPack`. The nuspec file contains a file-element:

```
<file src=".\bin\Debug\MyLib.dll" target="lib" />
```

When doing `./build.sh` it complains `File not found: '.\bin\Debug\MyLib.dll'.`. This issue originates from nuget/home#913. It will be (hopefully) fixed in nuget 3.4 so you can close this issue once the nuget issue is resolved.

**Comment by patriksvensson** [comment]
Back slashes are not valid file separators on *nix. Try changing `\` to `/` and see if that help.

You might also have to provide a base path for NuGetPack through NuGetPackSettings.

**Comment by bilke** [comment]
Thanks, specifying everything inside a `NuGetPackSettings` and don't using a `.nuspec`-file works!
