### ISSUE TITLE
Run unit tests on Travis

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#575]
Investigate if the XUnit console runner problems have been solved and run the build on Travis in that case.

**Comment by devlead** [comment]
We're currently running XUnit 2.0.0 and 2.1.0 is now avail, so that would a good place to start.

**Comment by devlead** [comment]
Affected package.configs if we would go all in 2.1.0
* [tools/packages.config](https://github.com/cake-build/cake/blob/develop/tools/packages.config#L4)
* [src/Cake.Common.Tests/packages.config](https://github.com/cake-build/cake/blob/develop/src/Cake.Common.Tests/packages.config#L4)
* [src/Cake.Core.Tests/packages.config](https://github.com/cake-build/cake/blob/develop/src/Cake.Core.Tests/packages.config#L4)
* [src/Cake.Testing.Xunit/packages.config](https://github.com/cake-build/cake/blob/develop/src/Cake.Testing.Xunit/packages.config#L3)
* [src/Cake.Tests/packages.config](https://github.com/cake-build/cake/blob/develop/src/Cake.Tests/packages.config#L6)
