### ISSUE TITLE
DownloadFile not working

### ISSUE THREAD

**Issue by superlogical** [cake-build/cake#580]
I'm getting the following error:

````
Error: build.cake(149,5): error CS0103: The name 'DownloadFile' does not exist in the current context
```

**Comment by patriksvensson** [comment]
What platform are you running this on and what does the call look like?

**Comment by devlead** [comment]
I've tried below code on Windows without issue
```cake
var url = "https://raw.githubusercontent.com/cake-build/example/master/build.cake";

FilePath tempFile = DownloadFile(url);
string tempFileName = tempFile.GetFilename().ToString();

Information("Name: {0}, Exists: {1}", tempFileName, FileExists(tempFile));

DeleteFile(tempFile);

DownloadFile(url, tempFile);

Information("Name: {0}, Exists: {1}", tempFileName, FileExists(tempFile));

DeleteFile(tempFile);

Information("Name: {0}, Exists: {1}", tempFileName, FileExists(tempFile));
```

It outputs something like below:
```bash
> .\Cake.exe .\test.cake
Name: l2a22l2q.dgr, Exists: True
Name: l2a22l2q.dgr, Exists: True
Name: l2a22l2q.dgr, Exists: False
```

Could you try and see if above gives you same error?

As @patriksvensson stated would be great if you could supply sample how your calling DownloadFile and we'll try to see if we can reproduce.

Also which version of Cake are you running? Below will print out Cake version.
```bash
.\Cake.exe -version
```
Latest is `0.6.4`

**Comment by superlogical** [comment]
Sorry for the vague explanation I'll send some details when I'm back on my computer, on my mobile at the moment

**Comment by devlead** [comment]
@superlogical great :+1:  no worries.

**Comment by devlead** [comment]
Hi @superlogical,
I'm closing this now, if your still having this issue please re-open or submit a new issue.
Thanks for your feedback :+1: 
/Mattias
