### ISSUE TITLE
MSBuild fails for PlatformTarget.x86

### ISSUE THREAD

**Issue by kopparam** [cake-build/cake#585]
I have a solution with multiple .net projects and multiple Silverlight projects. I was using Cake 0.5.0 till now with MSBuild task as follows:

```
var buildSettings = new MSBuildSettings()
                .SetConfiguration(configuration)
                .UseToolVersion(MSBuildToolVersion.NET40)
                .SetPlatformTarget(PlatformTarget.x86)
                .WithProperty("OutputPath", outputPath);
        solutionFiles.ForEach(solutionFile =>
            MSBuild(solutionFile, buildSettings));
```

This would work perfectly, but now I upgraded Cake to 0.6.4.
After the upgrade I get the error "Debug|x86" is invalid."

I changed the PlatformTarget to PlatformTaget.MSIL (any CPU). Now, all .net projects would build but Silverlight projects would fail with "The Silverlight 4 SDK is not installed."

@patriksvensson suggested me to use build settings as so
```
var buildSettings = new MSBuildSettings()
                .SetConfiguration(configuration)
                .UseToolVersion(MSBuildToolVersion.NET40)
                .SetPlatformTarget(PlatformTarget.MSIL)
                .SetMSBuildPlatform(MSBuildPlatform.x86)
                .WithProperty("OutputPath", outputPath);
```

With the above settings all projects build successfully.

**Comment by patriksvensson** [comment]
@kopparam This is not a problem with Cake but a missing build configuration (Debug|x86) that hasn't been specified in your csproj/vbproj file. Silverlight also needs to be built using x86 version of MSBuild (which is not used by default in Cake on a x64 machine).

To build with x86 configuration you would need to add this to your project file:

```
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x86' ">
  <!-- Configuration here -->
</PropertyGroup>
```

You can also add the configuration in the "Configuration Manager" in Visual Studio (which also will set sensible defaults).
