### ISSUE TITLE
Add -debug flag

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#587]
Add -debug flag parameter to Cake for `Debugger.Attach` feature.

**Comment by patriksvensson** [comment]
Should do this after #474 and change it to `--debug`.

**Comment by ErikSchierboom** [comment]
#474 has been closed, so I could look into this. Where in the could would the `Debugger.Attach` call be made? 

By the way, if I look at the [documentation of the `Debugger` class](https://msdn.microsoft.com/en-us/library/system.diagnostics.debugger(v=vs.110).aspx), ther is not `Attach` method, only a `Launch` method. Is that the correct one?

**Comment by mholo65** [comment]
@patriksvensson @devlead maybe this can be closed?

**Comment by gep13** [comment]
@mholo65 agreed, this was covered by your PR.

**Comment by gep13** [comment]
https://github.com/cake-build/cake/pull/858
