### ISSUE TITLE
Is there a plan to make builds with cake itself?

### ISSUE THREAD

**Issue by poxu** [cake-build/cake#590]
I'm new to C# and I'm currently trying to find a build system, which fits my tastes and needs.
Cake looks really good, but after a quick investigation I have discovered, that it uses msbuild task to do an actual build.

The idea of editing xml files doesn't look charming for me and I was looking for something, which would allow me to write build scripts with DSL and then would utilize compiler to do the build. Not something, which requires to write a script, using other build system language first.

It would be really cool if you had plans to to move in that direction. Have you thought about it?

**Comment by patriksvensson** [comment]
@poxu 

Thank you for your feedback :smile:

Cake is not a build system in the sense that it tries to do something that MSBuild or XBuild do, but is simply a set of DSLs to invoke other tools to orchestrate the build process. Cake is written in C# and uses a C# DSL, but it's not built with only C# in mind. Trying to replace MSBuild for this is nothing that we think is within scope for this project.

If you don't use an IDE such as Visual Studio or MonoDevelop, and don't want to hand write csproj files yourself, you could probably use a generator such as CMake for this.

**Comment by devlead** [comment]
We also support the DNU CoreCLR build tools, (you find avail aliases [here](http://cakebuild.net/dsl/dnu) )

DNU uses a project.json file, it's a little more lightweight than MSBuild, a minimal project structure would be
```
-MyApp (folder)
--project.json
--Program.cs
```

The tools for each platform are available here:
https://www.nuget.org/packages?q=dnx-coreclr

You can read more about project.json at https://github.com/aspnet/Home/wiki/Project.json-file and se an example file [here](https://github.com/aspnet/Home/wiki/Project.json-file#example-projectjson-from-one-of-the-ef-projects) .

**Comment by poxu** [comment]
@patriksvensson , @devlead 

Thanks for a quick response!
----------------------------------
Also thank you for pointing at DNU.
I had hoped to find something like gradle, but eventually found something like npm :). Not what I was dreaming about, but still better, than xml.

But could I take a little bit more of your time and ask another question.

What is cake designed for?
----------------------------------
You are saying, that it is not supposed to be used as a replacement of msbuild or DNU or anything like that. But you have actually reimplemented a lot of things those tools do, right?

I am not sure, but I suppose msbuild and DNU can do everything cake can. Except for cake does it using C# DSL, which by the way is awesome. I thought you were going to add new functionality, until there is no need in using msbuild, but apparently it is not the case.

So, to use cake I would have to learn how to write scripts for msbuild or DNU and then learn how to write cake scripts. And, since those tools have similar functionality, I'd want to use mostly one of them.

And I suppose it's going to be the one I absolutely have to use - msbuild in our case. 

So why would I use cake at all? My answer is C# DSL. I love the idea. But why not use C# DSL for everything. If you told me you didn't have enough resources for that, I'd understand. But you're telling me it's by design. So I think maybe I don't understand cake's mission at all.

Could you explain?

**Comment by gep13** [comment]
@poxu when you say:

>So, to use cake I would have to learn how to write scripts for msbuild

What exactly do you mean?  

The default csproj or vbproj file, which contains the auto generated MSBuild constituent parts, very rarely needs to be edited.  Unless you have certain criteria that you haven't documented yet.  As a result, having created the Visual Studio solution file, with all your projects in it, all you need to do is then call the MSBuild Alias in Cake, point it at your Solution File, and it will take care of the rest.  As you can see, I haven't had to "write" any MSBuild scripts to get the job done.

Take as an example this project (which is mine) which uses Cake:

https://github.com/gep13/ReSharperReports

I haven't "written" any MSBuild scripts.  All I have done is create the solution and projects through Visual Studio, and then written the Cake build script to get it all compiled, packaged, etc.

**Comment by poxu** [comment]
@gep13 

> I haven't "written" any MSBuild scripts. All I have done is create the solution and projects through Visual Studio, and then written the Cake build script to get it all compiled, packaged, etc.

And that is exactly what I meant :). First you have to use graphical configurator (Visual Studio) to create a bunch of human unreadable and vcs unfriendly xml, and then you use it as a black box to build the project and do the rest with cake. Wouldn't it be better, if you could describe build process using cake also?

**Comment by devlead** [comment]
Then CoreCLR and the DNU toolset is probably more up your alley, but it's still in beta and not as feature complete as MSBuild.

Simplified the new project.json is more a config file which states which frameworks to build for and which external there are.

**Comment by gep13** [comment]
>@poxu said...
First you have to use graphical configurator (Visual Studio) to create a bunch of human unreadable and vcs unfriendly xml, and then you use it as a black box to build the project and do the rest with cake. Wouldn't it be better, if you could describe build process with cake as you describe packaging etc. ?

What are you using to then develop the application you are creating?  If you are using notepad, or some editor to write the application, then I could see why maintaining the csproj file would be a problem.  But assuming you are using Visual Studio, I personally don't see what the major issues.  Some of my colleagues don't even know what the csproj file is even for, let alone how to go about editing it. :smile:

**Comment by poxu** [comment]
@gep13 
My background is mostly java and a little bit of nodejs. And I'm used to having human readable builds, which don't require an IDE to write. I use IDEA for java and vim for nodejs. But I don't commit any of IDEA project files to vcs.

**Comment by poxu** [comment]
@devlead 
Thanks again for pointing at DNU! I still don't get why you don't want to do actual builds with cake, but I get, that it was a choice. So, please tell me if I got it right. 
The supposed way is using underlying build system to fetch dependencies and perform builds and use cake for everything else, even if you could do some of that stuff with the underlying build system?

**Comment by gep13** [comment]
>@poxu said...
My background is mostly java and a little bit of nodejs. And I'm used to having human readable builds, which don't require an IDE to write. I use IDEA for java and vim for nodejs. But I don't commit any of IDEA project files to vcs.

So this is a clear difference between how the development stacks work.

>@poxu said...
I still don't get why you don't want to do actual builds with cake, but I get, that it was a choice.

It wasn't so much a choice, as a pragmatic decision.  MSBuild is a complex beast, which there is little point in re-inventing.  Rather, utilize MSBuild (via the Cake Alias) to do the core compilation of the csproj file (which again, is typically autogenerated and maintained for you by the IDE, so little work for you to do there) and then use Cake to do all the other parts of your build process.  i.e. the packaging, the versioning, the deployment, etc, which typically you would have had to hand craft into an MSBuild file, which is not pleasant.

**Comment by devlead** [comment]
@poxu first goal historically the majority of C# developers have been using an IDE like VisualStudio or XamarinStudio, which both use the MSBuild xml format.
So with MSBuild we covered automating 90% of all C# projects.

That said this is now changing with the Microsoft OSS efforts where more XPlat tools are available and enable lighter workflows.

You can use other tools to i.e. cmake files a project that uses that approach is [litjson](https://github.com/lbv/litjson/blob/master/build/make/Makefile)
There's an Alias available via an add-in to cake [CMake](http://cakebuild.net/api/cake.cmake/6b75b85f/9f06acd8)

You could also generate your files with a tool called [Yeoman](https://libraries.io/search?keywords=yeoman-generator&languages=C%23).

You could just use that [StartProcessAlias](http://cakebuild.net/dsl/process) and just use the C# compiler, we haven gotten around to make an alias for that one yet. it's usage is basically
`.\csc.exe" /debug /target:library /out:MyDll.dll /pdb:MyDll.pdb /recurse:*.cs`

It's not a matter of not wanting to support your scenario we haven't had the time or the need enough to prioritize such a use case.

**Comment by devlead** [comment]
I'm closing this issue now, If there are there any other questions raised you feel not answered in this issue please re-open or submit a new issue.
Thanks for your feedback.
