### ISSUE TITLE
How to get ILRepack executable?

### ISSUE THREAD

**Issue by AnderssonPeter** [cake-build/cake#601]
I just tried to run the ILRepack executable but its giving me the error `ILRepack: Could not locate executable.` my first thought was that it could not find the `primaryAssembly` so I tested different variations for about an hour, but my current guess is that it can't find the ILRepack under tools? but how do I get it there?

Note: I get the exact same error if I try `ILMerge` and I have installed ILMerge on my computer?

**Comment by devlead** [comment]
You can fetch ILRepack via the [#tool](http://cakebuild.net/docs/fundamentals/preprocessor-directives) directive which fetches it from Nuget.

I.e.
```cake
#tool "ILRepack"

```

**Comment by devlead** [comment]
You can read more about tool resolution here:
http://cakebuild.net/docs/tools/tool-resolution

**Comment by Petoj87** [comment]
Thanks that solved my problem, maybe it would be a good idea to add this information to http://cakebuild.net/dsl/ilrepack and http://cakebuild.net/dsl/ilmerge ?

**Comment by patriksvensson** [comment]
You can read more about tool resolution here: http://cakebuild.net/docs/tools/tool-resolution

**Comment by devlead** [comment]
Fixed by #632
