### ISSUE TITLE
Prompt for upgrade when using Powershell <3.0

### ISSUE THREAD

**Issue by adamrodger** [cake-build/cake#602]
When trying to run the default Powershell bootstrapper on a version of Powershell <3.0, the [`Invoke-WebRequest`](https://technet.microsoft.com/en-us/library/hh849901(v=wps.620).aspx) cmdlet is missing.

Since the default version of Powershell on Windows 7 (still heavily used) is v2.0, the Powershell bootstrapper script should probably check first and prompt the user to upgrade if necessary, e.g.:

    if ($PSVersionTable.PSVersion.Major -lt 3) {
        Write-Host "You need to upgrade dude"
        Exit
    }

**Comment by devlead** [comment]
Or perhaps support v2 as we do it in Cake's [build.ps1](https://github.com/cake-build/cake/blob/develop/build.ps1#L40)

**Comment by gep13** [comment]
Looks like there is a open PR for at least part of this: https://github.com/cake-build/bootstrapper/pull/23

**Comment by gep13** [comment]
@adamrodger all default bootstrapper's now support PowerShell 2, so I am going to go ahead and close this.  Please feel free to open this again if you think additional work is required.
