### ISSUE TITLE
Check for Git Bash/Cygwin in build.sh bootstrapper

### ISSUE THREAD

**Issue by adamrodger** [cake-build/cake#603]
When using Git Bash or Cygwin on Windows and using `build.sh`, `cake.exe` is executed under mono by default whereas mono probably isn't installed.

The script should probably check for the environment and only execute `cake.exe` under mono if necessary, otherwise invoke directly.

**Comment by devlead** [comment]
Don't think we'll do anything special for cygwin perhaps could provide an alternative cygwin bootstrapped in the resources repo, so I'm going a head and closing this issue.
Thanks for your feedback, much appreciated.
