### ISSUE TITLE
/noisolation argument for MSTest is always true

### ISSUE THREAD

**Issue by adnangohar** [cake-build/cake#615]
The /noisolation flag for MSTest is set true by default. Would be good to have a settings option which can be passed in build.cake file to set arguments for MSTest. Similar functionality already exists for MSBuild where we can pass settings in build.cake file.

I have implemented settings for MSTest same as MSBuild, if this issue is important and my fix is needed I can send a pull request.

**Comment by johnxjcheng** [comment]
I had similar issue with the default setting of /noisolation. After thought about it again I think the default value should be false. This seems to be the default value used by Visual Studio.

**Comment by devlead** [comment]
@cake-build/team thoughts?

**Comment by gep13** [comment]
@devlead happy to extend the settings to include the ability to change this.  Changing the current default would be a breaking change, so I would prefer to leave it as is, but with the ability to change it if/when required.

**Comment by devlead** [comment]
@gep13 agree, as there is a settings ( `new MSTestSettings { NoIsolation = false };` ) for this I'll go ahead and close this issue
