### ISSUE TITLE
Support for executing specific targets from the command line

### ISSUE THREAD

**Issue by theonlylawislove** [cake-build/cake#618]
Most build environments allow you to do "build clean", or "build test" or "build compile".

This could probably be supported by passing in custom arguments, but those arguments would have to be manually interpreted and wired up.

For example, we should be able to do:
```build -targets Clean```

**Comment by theonlylawislove** [comment]
Do! I spoke to soon!

```c#
var target = Argument("target", "Default");
...
RunTarget(target);
```

I think this should be called out in the documentation, even though it is implement in the .cake file, and not in the build system itself.

**Comment by patriksvensson** [comment]
@theonlylawislove

Not sure if I misunderstand your question, but the information you are looking for can be found in the documentation: [http://cakebuild.net/docs/fundamentals/running-targets](http://cakebuild.net/docs/fundamentals/running-targets).

**Comment by theonlylawislove** [comment]
I didn't see how to provide the ```target``` argument from the command line. I found out how after checking the ps1 file.

```./build.ps1 -Target Build```
