### ISSUE TITLE
Add GitLink Alias

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#619]
In the same way that we have GitReleaseManager, GitReleaseNotes and GitVersion aliases, we should really complete the set and add an alias for GitLink:

https://github.com/gittools/gitlink

All the command line arguments can be found here:

https://github.com/GitTools/GitLink/blob/develop/src/GitLink/HelpWriter.cs

**Comment by ghuntley** [comment]
Can't wait - thanks for working on this.

**Comment by gep13** [comment]
>@ghuntley said...
Can't wait - thanks for working on this.

Not a problem at all, adding this completes the set of GitTools i.e. GitVersion, GitReleaseNotes, GitReleaseManager and GitLink, so happy to see it getting added :+1:
