### ISSUE TITLE
DNUPackSettings OutputDirectory should be a DirectoryPath

### ISSUE THREAD

**Issue by reicheltp** [cake-build/cake#624]
The OutputDirectory property in DNUPackSettings should be a DirectoryPath not a FilePath. Thus I get an error if I wanna do the following code:

```csharp
var output = Directory("./output");

Task("pack")
    .Does(() => DNUPack(src, new DNUPackSettings 
    { 
        OutputDirectory = output,
        Configurations = new [] {configuration}
    }));
```

Responding file:
https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/DNU/Pack/DNUPackSettings.cs

**Comment by devlead** [comment]
@reicheltp totally correct, thanks for reporting :+1:

**Comment by reicheltp** [comment]
Same for DNUBuildSettings 
https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/DNU/Build/DNUBuildSettings.cs

**Comment by devlead** [comment]
@reicheltp something you would like to submit a PR for? Otherwise I'll take a look at fixing this.

**Comment by reicheltp** [comment]
I can do it later today. :)

**Comment by devlead** [comment]
@reicheltp superb :+1: , just create a PR referencing that it fixes this issue in commit & pr message using the fixes [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/).
