### ISSUE TITLE
Drop DNU/DNX support in favor of dotnet CLI

### ISSUE THREAD

**Issue by reicheltp** [cake-build/cake#627]
As Microsoft is slowly dropping the support for DNU and DNX in favor of the dotnet CLI we should migrate the DNU Aliases to the new dotnet CLI.

As you can read here https://github.com/dotnet/cli/blob/master/Documentation/intro-to-cli.md the transaction from DNX/DNU to the new CLI is achieved with RC2.

Since the new dotnet/cli is already available (http://dotnet.github.io/) we can switch over with a clear conscience.

If you agree with me I will implementing this and create a pull request.

Best regards,
Paul

PS: this is also fixing my issue #626 :smile:

**Comment by RichiCoder1** [comment]
:+1:

**Comment by gep13** [comment]
I believe that this was always going to be the plan going forward.  We have the option to mark aliases as Obselete, so once the transition to CLI is complete, and people "shouldn't" be using DNU/DNX anymore, we can reflect that in the Alias definition.

**Comment by phenixdotnet** [comment]
Hi.

I worked on DNU/DNx/DNVM support in cake (PR is https://github.com/cake-build/cake/pull/591) and I currently looking at dotnet cli. I can work on dotnet cli too if you want.

**Comment by gep13** [comment]
@cake-build/team once if/when #674 is merged in, I think we need to look to marking the existing DNU aliases as obselete.

**Comment by patriksvensson** [comment]
Closed via #914.
