### ISSUE TITLE
Investigate CLA

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#635]
I spoke with @ferventcoder the other day, and he suggested that we add a [CLA](https://en.wikipedia.org/wiki/Contributor_License_Agreement) to Cake.

We would need to get sign off from existing contributors as well, and if they don't want to sign, remove their code or rewrite it. Would also need some kind of CLA bot to enforce new contributors to sign before merging.

https://julien.ponge.org/blog/in-defense-of-contributor-license-agreements/

**Comment by ferventcoder** [comment]
:+1:

**Comment by RichiCoder1** [comment]
:+1:

**Comment by devlead** [comment]
:+1:

**Comment by gep13** [comment]
Well, if everyone else is doing it... :+1:

**Comment by devlead** [comment]
This is done with the DNF work.
