### ISSUE TITLE
Task Summary should include skipped tasks

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#638]
As part of a build, you might see something like this:

![image](https://cloud.githubusercontent.com/assets/1271146/12338366/26ab430a-bb07-11e5-9077-21b109b88e88.png)

But there is no mention of it in the task summary:

![image](https://cloud.githubusercontent.com/assets/1271146/12338386/38fd3f5e-bb07-11e5-9579-2f4fff5989cc.png)

This should be included in the summary, but in gray and with no time associated with it, to indicate that it was skipped.

Should this be an optional flag to include this information, or always enabled?

**Comment by patriksvensson** [comment]
@gep13 I think it should always be enabled. Really useful to see what tasks that were skipped and good for debugging.

**Comment by gep13** [comment]
:+1:

**Comment by patriksvensson** [comment]
Closed via #648

**Comment by gep13** [comment]
Woot! Thanks for the contribution @ErikSchierboom

**Comment by ErikSchierboom** [comment]
@gep13 My pleasure!
