### ISSUE TITLE
Add Bitrise CI build system support

### ISSUE THREAD

**Issue by ghuntley** [cake-build/cake#644]
There will be a bit of demand from Xamarin developers to add support for https://www.bitrise.io/ who support building Xamarin.iOS, Xamarin.Droid and Xamarin.Mac (after doing a manual homebrew install).

I /may/ be able to take lead on adding support for this depending on time commitment but for now consider it `up-for-grabs`.

**Comment by patriksvensson** [comment]
@ghuntley Thanks for bringing this up :+1: 

If you want to give this a go, tell us and we'll mark this issue as taken.

**Comment by RLittlesII** [comment]
@patriksvensson This isn't marked as up for grabs.  If this is simliar to #693, I can take a look at it this weekend.  I am evaluating Bitrise for Xamarin CI.

**Comment by gep13** [comment]
@RLittlesII Sorry, just realised that this issue was closed, and credit wasn't given for your contribution on the release notes!  Please accept our apologies on this, we REALLY appreciate all the work that you do on Cake!
