### ISSUE TITLE
Add Module Support

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#646]

**Comment by RichiCoder1** [comment]
Awesome! Looking forward to using this (pending docs)!

**Comment by gep13** [comment]
@RichiCoder1 we have discussed this, and we want to try this out "internally" once it is released, so it will be a "dark" feature, until we have taken it for a ride, and make any improvements that we think are required, and then the documentation will follow.  All the information required to test it out is in the PR associated with this issue, but you likely won't see any documentation appear until the next release.  Would love to hear any feedback you have on it though, and if you need any help then feel free to jump into gitter and we can help out.
