### ISSUE TITLE
Can't resolve add-ins when custom nuget feed is added

### ISSUE THREAD

**Issue by tlycken** [cake-build/cake#652]
I've added a custom feed to NuGet.config on our build server, with the following contents:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="private" value="https://our.private.nuget.feed/nuget" />
    <add key="nuget.org" value="https://api.nuget.org/v3/index.json" protocolVersion="3" />
  </packageSources>
</configuration>
```

Since I did that, add-in resolution fails. My build script starts with (after declaring a few arguments) `#addin Cake.Json` and the build fails there with 

> Unable to find package 'Cake.Json'.
> Error: Failed to install addin 'Cake.Json'.

I assume this is because Cake is unable to find it in our private feed - but why doesn't it look in both feeds?

Earlier in the build output (from `InitializeDNXEnvironment.ps1`), I see output like

>NuGet Config files used:
>    C:\Users\tfsbuild\AppData\Roaming\NuGet\nuget.config
>Feeds used:
>    https://our.private.nuget.feed/nuget/
>    https://api.nuget.org/v3-flatcontainer/

so I'm pretty certain the `NuGet.config` contents are OK.

What could be wrong here?

**Comment by patriksvensson** [comment]
@tlycken 

Currently, the way to reference addins via the script is to write your NuGet package dependency like this:

```
#addin nuget:https://our.private.nuget.feed/nuget/?package=Cake.Json
```

If you want to resolve using the NuGet config, this is probably better to restore packages in your bootstrapper.

**Comment by devlead** [comment]
Similar for fetching the addin from nuget would be
```cake
#addin nuget:https://nuget.org/api/v2/?package=Cake.Json
```

**Comment by devlead** [comment]
This requires `Cake v0.8.0` though.

**Comment by tlycken** [comment]
Thanks for the prompt replies. I tried

     #addin nuget:https://www.nuget.org/api/v2/?package=Cake.Json

which worked fine locally, but failed with the same error still on the build server.

**Comment by devlead** [comment]
Which version of Cake & Nuget is running on the build server? Which build server are you using?

**Comment by patriksvensson** [comment]
Would also help if you could post part of the build log for the failing NuGet retrieval (with diagnostic verbosity).

**Comment by devlead** [comment]
`.\Cake.exe -Version` will give you version.

`.\Cake.exe build.cake -verbosity=Diagnostic` will give you a more detailed log

**Comment by tlycken** [comment]
Hm. This is very odd. To start with, `Cake.exe -Version` shows I'm running `0.8.0`.

I ran the build script manually on the build server (which is running TFS 2015), and then it worked. I then started a build from the web interface in TFS, and it worked too.

I don't know what didn't work before - perhaps it was building a stale version from source control or something - but now it works. Thanks for helping me troubleshoot and for your swiftness, anyway!

**Comment by patriksvensson** [comment]
@tlycken No problem! Glad that it worked out for you :smile:

**Comment by Rkeerthivasan** [comment]
**Reg:**Failed to install Cake.HockeyApp addins.

 We have tried to upload "zip"   file of WPF sample exe to Hockeyapp. So, We need to use     "Cake.HockeyaPP" addin. While using this addin , we are facing the below issue(refer to the screenshot).     Please share your inputs to resolve the error. 
![image](https://user-images.githubusercontent.com/33143080/32087423-416f8bf8-baf9-11e7-832f-24dc8ca76754.png)
