### ISSUE TITLE
Add support for dotCover

### ISSUE THREAD

**Issue by Sam13** [cake-build/cake#658]
Add support for coverage tool: dotCover
https://www.nuget.org/packages/JetBrains.dotCover.CommandLineTools/

Command line reference:
https://www.jetbrains.com/dotcover/help/dotCover__Console_Runner_Commands.html#analyse

Add in same way as OpenCover which enables to pass another tool (e.g. Nunit3) for execution

**Comment by gep13** [comment]
@Sam13 thank you for the suggestion!  While we think that dotCover would be a great addition to Cake, we don't think that we are in a position to bring this directly into Cake.Common.  Instead, we suggest that this would be a great candidate as an Addin for Cake, similar to Cake.VsCode, Cake.Gitter, or Cake.Kudu.

All of the current Cake Addin's can be found on NuGet here:  https://www.nuget.org/packages?q=cake

Would creating an Addin for Cake be something that you are interested in?

**Comment by patriksvensson** [comment]
@gep13 @Sam13 The reason for this is that dotCover is a proprietary product and testing this could be difficult for us.

**Comment by Sam13** [comment]
@patriksvensson What do you mean by testing? 
dotCover is a commercial product but free of charge, isn't it?
See https://blog.jetbrains.com/dotnet/2015/10/14/details-on-dottrace-dotcover-dotmemory-licensing-changes/#clt

You can download the NuGet which contains the  command line tools and run dotCover console to create XML coverage reports which can be processed e.g. by ReportGenerator.
For this dotCover console I'd like to have Cake support as for OpenCover...

**Comment by patriksvensson** [comment]
@Sam13 I stand corrected. I was under the impression that dotCover required a license to run from Jetbrains.

**Comment by gep13** [comment]
@Sam13 oh! This is indeed very interesting!  I knew that you could use the ReSharper Command Line Tools, but I didn't know about dotCover being under the same license structure!

**Comment by gep13** [comment]
@Sam13 thanks for the link to that blog post, this really is great news!

**Comment by mholo65** [comment]
I could really see myself needing this in a not so distant future. I could start looking into this if no one else have already started this task?

Short-term goal: get **analyze** command working
Long-term goal: add support for other commands, eg: **cover**, **merge**, **report** and **delete**

**Comment by mholo65** [comment]
Yes, analyze works in most scenarios while the others is needed for more complex setup, e.g. running coverage for multiple projects in separate steps.

**Comment by phrusher** [comment]
I have made an addin for Cake with dotCover and the analyze command. Unfortunately I don't have access to the source for a couple of days but if there is no big hurry I could convert to a tool and send a PR next week.

**Comment by gep13** [comment]
@phrusher that sounds like a great plan to me! :+1:

**Comment by patriksvensson** [comment]
Closed via #691.
