### ISSUE TITLE
Custom working directory for any tool

### ISSUE THREAD

**Issue by Sam13** [cake-build/cake#661]
As part of #653:
I'd should be possible to pass a custom working directory to any tool.
E.g. Specify another working directory for NUnit3 task. So far I couldn't find any option to pass that to the custom tool. By now I do it like that:

```
var previousCurrentDir = System.IO.Directory.GetCurrentDirectory();
Environment.CurrentDirectory = "path\to\bin";
try
{   
    NUnit3("path\to\bin\*UnitTest.dll", settings);    
}
finally
{
    Environment.CurrentDirectory =  previousCurrentDir;
}   
```
I suggest adding a property ```WorkingDirectory``` to ```ToolSettings``` (http://www.cakebuild.net/api/cake.core.tooling/d75cd243)

**Comment by Sam13** [comment]
Duplicate of  #844 - closing

**Comment by patriksvensson** [comment]
There is a WorkingDirectory property of the ToolSettings base class that does this.

**Comment by Sam13** [comment]
@patriksvensson Thanks
