### ISSUE TITLE
NuGetPack alias requires settings

### ISSUE THREAD

**Issue by ErikSchierboom** [cake-build/cake#664]
I noticed that the `NuGetPack` method in the `NuGetAliases` class requires a `NuGetPackSettings`. Most other methods provide overloads without a setting. Is there a specific reason for this?

**Comment by gep13** [comment]
@devlead would you be in a position to comment on this issue? Thanks

**Comment by devlead** [comment]
It's true, guess initial intent that at least some information like i.e. version would be supplied, we've got an overload that takes just a `NuGetPackSettings` eliminating all need for a nuspec, which has been the route I've personally taken.
An overload taking only `FilePath` for nuspec would certainly be possible, but would also make same package each time unless you preprocess nuspec before, but that's kinda counterintuitive as that's what supplying settings does in a typed way.

**Comment by devlead** [comment]
I'm going to go ahead an close this due inactivity, if it's still an issue please reopen.
