### ISSUE TITLE
C# 6 support

### ISSUE THREAD

**Issue by ErikSchierboom** [cake-build/cake#668]
At the moment, the codebase doesn't use any C# 6 features. Is that intentional?

**Comment by RichiCoder1** [comment]
It's a side effect of Cake's dated version of Roslyn. Technically you can use some C#6 features that were finalized early on. There is a plan, however, to move to the new Roslyn scripting engine once its stable and cross-platform, and this will light up all the missing C#6 bits.

**Comment by ErikSchierboom** [comment]
@RichiCoder1 Thanks for explaining. How to see the new Roslyn scripting engine soon then.

**Comment by patriksvensson** [comment]
You can use the latest stable Roslyn by passing the"-experimental" flag to Cake.exe which will give you access to C# 6 features in your scripts.

**Comment by JakeGinnivan** [comment]
Any plans on making the newest versions the default?

**Comment by gep13** [comment]
@JakeGinnivan we are pretty much waiting until the Roslyn Scripting Engine becomes stable and cross platform, at which point, we can use the same Scripting Engine for everything, rather than taking the dependency on the Mono Compiler.

**Comment by thomaslevesque** [comment]
Maybe I'm missing something, but it seems to me that `Microsoft.CodeAnalysis.Scripting` has been stable for a while... it's currently in version 1.3.2. Why is Cake still using 1.0.0-rc2?

**Comment by devlead** [comment]
@thomaslevesque the CoreCLR work will bring a newer version of Roslyn. One issue was that later versions of Roslyn required latest version of .Net, that's becoming less of an issue with time.

**Comment by jnm2** [comment]
String interpolation will be one of the most valuable paradigms for DSLs. Disappointed that I can't use them yet.

**Comment by devlead** [comment]
@jnm2 you can use String interpolation,, specify the experimental flag or use the CoreCLR version of cake.

**Comment by gep13** [comment]
@jnm2 there is nothing stopping you using them today.  Passing in the `-Experimental` flag to the bootstrapper will cause the newer version of Roslyn to be used.

**Comment by jnm2** [comment]
@devlead @gep13 Can I do it from the task runner? I'd also hope for syntax highlighting.

**Comment by gep13** [comment]
@jnm2 yes, I believe that should be possible, but not until the next release of the VS Extension.
