### ISSUE TITLE
Add a .gitattributes file to the repo

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#669]
- And do a one time rationalisation of the line endings for the project

**Comment by ErikSchierboom** [comment]
I'm quite interested in this. At work I want to do something similar. Could you write down what you did to make this happen? It would be quite informative.

**Comment by gep13** [comment]
@ErikSchierboom yip, I can do that.  I will let you know once this is completed :+1:

**Comment by devlead** [comment]
@gep13 we're we at with this, still an issue?

**Comment by gep13** [comment]
@devlead haven't started looking at this yet.  I know what I "need" to do, but just haven't done it yet 😢

**Comment by devlead** [comment]
@gep13 no worries assigned issue to you.

**Comment by devlead** [comment]
Fixed by #1420
