### ISSUE TITLE
Support Paket as an alternative package manager for #tool and #addin

### ISSUE THREAD

**Issue by kibiz0r** [cake-build/cake#673]
Now that we have #616, I'd like to have support for using Paket rather than NuGet for `#tool` and `#addin`.

There are a few advantages for us (my organization), in being able to use Paket:

Since we are all on OS X, and there is no Homebrew package for `nuget` (and the official Mono distribution ships an ancient version that doesn't work with our MyGet feed), we opt to use Paket across the board.

We have some addins stored in private MyGet feeds, which requires us either to commit credentials to our repos by encoding them into the `#addin` directives or to force each dev to alter their `NuGet.Config` to pull from MyGet. Requiring NuGet just for configuring Cake's package sources is a little much, and storing an ad-hoc `tools/NuGet.exe` feels weird and adds complexity to setting up a new repo.

Paket allows you to configure package sources in a file that can be checked into the repo, and can rely on env vars to provide credentials to those sources so you don't have to commit credentials along with the source configuration.

It may make sense to use Paket's "groups" feature here.

**Comment by patriksvensson** [comment]
@kibiz0r There is currently no plans for adding Paket as a provider for #addin or #tool. Since Paket relies on external files in repository such as `packet.lock`, `paket.references` and `packet.dependencies`, I see little benefit from trying to synchronize this with the script code. I think the best solution here would be to fetch packages via Paket from your Cake bootstrapper script.

We could however add support for adding templating support for the `#addin` and `#tool` directives that could get values from environment variables or arguments.

```csharp
// A proposition for how this could work.
#addin "nuget:https://{user}:{password}@myget.com/f/Owner/?package=Foo.Bar"
```

**Comment by kibiz0r** [comment]
> I think the best solution here would be to fetch packages via Paket from your Cake bootstrapper script.

How would that work? It seems like a chicken-and-egg problem, but I might be missing something crucial here...

**Comment by RichiCoder1** [comment]
See https://github.com/cake-build/cake/blob/develop/build.ps1

Essential, use the cake bootstrap to download paket and run it against a seperatetly defined `.dependencies` file, and then reference anything cake needs to good old fashion way.

**Comment by kibiz0r** [comment]
So, wrap Cake? Idk about that... We're using Cake via Homebrew right now, and this was in an effort to reduce the number of components involved in our project automation setup, so I'm inclined to leave Homebrew in control of `cake`.

**Comment by patriksvensson** [comment]
@kibiz0r Yes. Having a bootstrapper script responsible for getting Cake (and dependencies not retrievable via the `#addin`/`#tool` directive) for you will ensure that the build experience will look the same regardless of if you're building locally on your own computer or running the build on a CI server.

If you want to use something like Paket, I think the best way would be to bootstrap the build process via a shell script that downloads things that you need. You could even do that to ensure that Cake is installed via homebrew if it for some reason would be missing (perhaps a new colleague that's unaware of how your build works).

**Comment by larzw** [comment]
@kibiz0r

In case you are still interested, I have an example project [Example Cake Build Using Paket](https://github.com/larzw/Cake.Paket.Example) that uses Cake and paket. As mentioned in the previous threads, the trick was to modify the bootstrapper.

**Comment by phillipsj** [comment]
@gep13 This seems to have a solution, is this something you want to keep open?

**Comment by patriksvensson** [comment]
@gep13 @phillipsj Yes, I think this one can be closed. Since paket relies on paket.dependencies, there is little reason to write a provider for individual packages. Unless I've missed something that is.

**Comment by gep13** [comment]
@patriksvensson @phillipsj if this were going to be done, I think it would be best implemented in a Cake.Paket.Module, but that would be external to Cake core.  The infrastructure is all there in Cake to allow the implementation of this, it would just need to be created.  Ideally, this would be created as a repo in the cake-contrib organisation.
