### ISSUE TITLE
Add Jenkins CI build system support

### ISSUE THREAD

**Issue by ghuntley** [cake-build/cake#693]
I /may/ be able to take lead on adding support for this but for now consider it up-for-grabs.

**Comment by patriksvensson** [comment]
@ghuntley Good suggestion. I use Cake in Travis to build some stuff and having access to Jenkins specific stuff would be very nice indeed. :+1:

**Comment by rtyler** [comment]
Apologies for air dropping into this ticket; I noticed this in my usual Googlings about. I'm assuming this ticket is about integrating Cake into Jenkins in some form or fashion.

Might I suggest some potential routes:

1. Jenkins has tool auto-installers which you could implement in a Jenkins plugin to auto-install Cake. See [this document on how to write them](https://wiki.jenkins-ci.org/display/JENKINS/Adding+tool+auto-installer)
1. Implement a Build Step ([CMake plugin](https://wiki.jenkins-ci.org/display/JENKINS/CMake+Plugin) ro the [Gradle plugin](https://wiki.jenkins-ci.org/display/JENKINS/Gradle+Plugin) might be good sources of techniques or information on how to accomplish this.
1. Check out the [Warnings plugin](https://wiki.jenkins-ci.org/display/JENKINS/Warnings+Plugin) which already has support for aggregating build warnings from MSBuild and could be extended to include warnings generated out of Cake



If the goal is to drive Jenkins from Cake, that's a whole other can of worms :)

**Comment by gep13** [comment]
@rtyler the intention for this Addin would really be to provide access to Jenkins functionality and properties, during the execution of a Cake Build.

We already have a number of Build Systems that Cake can talk to (http://cakebuild.net/dsl/build-system) and the hope would be to include Jenkins in that as well.  Take for example the AppVeyor alias that ships with Cake (http://cakebuild.net/api/cake.common.build.appveyor/855a6067) this provides us access to things like `IsRunningOnAppVeyor`.  We can use this setting in a build script to perhaps do different tasks, compared to when the build is running locally, or on another CI Server.

We also have extension methods like UpdateBuildVersion (http://cakebuild.net/api/cake.common.build.appveyor/855a6067/d14592e8), which does exactly what it says on the tin.

Now, most of these things are just wrappers around things that can be done in a different way.  For example, reading an Environment Variable, or calling an available API.  Wrapping those things up in the Cake Alias means that there is some consistency across the CI Systems that we offer, but also makes it much more easier to call into.

On the other side of the equation, we probably would also want to provide an easy on-boarding to running a Cake build through Jenkins.  In the initial instance, this will likely just be a set of steps on how to do it, but in the future, we could see adding a Build Step specifically for Jenkins that does some of the "heavy-lifting" for you.  We already have this for VSTS, and I for one would like to see it for all common CI Servers, but one thing at a time :smile:

**Comment by rtyler** [comment]
@gep13 Interesting, Jenkins provides a ton of environment variables that can be interrogated (plugins like the Gerrit Trigger plugin also add their own). As far as accessing or modifying the build as it's running in some form or fashion, this can typically be done via the [Jenkins CLI](https://wiki.jenkins-ci.org/display/JENKINS/Jenkins+CLI) or a plugin (of course).

Reading state: easy peasy, writing state, more challenging :)

**Comment by gep13** [comment]
@rtyler thanks for all the information, and thanks for joining this discussion.

If either @ghuntley or someone else picks this up, I am sure we might be throwing some questions your way :+1:

**Comment by RLittlesII** [comment]
@gep13 I am looking at some of the [Jenkins environment variables](https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-below) we have access to.
Are you envisioning primarily read only access through the environment variables provided?  Or are you thinking more a wrapper around the cli?

**Comment by patriksvensson** [comment]
@RLittlesII We're mostly looking at reading environment variables. There are some examples of other build system providers in [Cake.Common.Build](https://github.com/cake-build/cake/tree/develop/src/Cake.Common/Build) if you want to look more into this :smile:

**Comment by RLittlesII** [comment]
@patriksvensson Okay.  I was just making sure before I go off and write a cli wrapper.  I am looking at this today.

**Comment by patriksvensson** [comment]
@RLittlesII Ok, I'm marking this as taken then.

**Comment by devlead** [comment]
PR #715 proposed to fix this.

**Comment by devlead** [comment]
This is fixed by issue #715
