### ISSUE TITLE
Add SpecFlow support

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#695]
Add support for [SpecFlow](https://github.com/techtalk/SpecFlow). Commands should contains features like running tests (via NUnit/MSTest/xUnit) and generating reports.

I'm willing to implement and send a PR if it's suitable for Cake.Common.

**Comment by gep13** [comment]
@mholo65 thanks for reaching out!

Yes, we agree that this would be a good addition for Cake.Common.  If you are in a position to get that working, we would gladly accept a PR for this.

**Comment by devlead** [comment]
Fixed by #727

**Comment by mholo65** [comment]
Thanks for merging. What about adding label and milestone to issue?

**Comment by devlead** [comment]
@mholo65 added :+1:  It's merged so it'll be in the next one :wink:
