### ISSUE TITLE
Nuget push is broken on mono

### ISSUE THREAD

**Issue by andycmaj** [cake-build/cake#706]
## Symptom

`NuGetPush` fails when trying to publish packages on mono.

### Cake Task
```csharp
Task("Publish")
    .Does(() =>
{
    Information($"WorkingDir: {Context.Environment.WorkingDirectory}");
    foreach (var packageFile in GetFiles(OutputPath + "**/*.nupkg"))
    {
        Information($"FullPath: {packageFile.FullPath}");
        NuGetPush(p, settings);
    }
});
```

### Result

```bash
========================================
Publish
========================================
Executing task: Publish
WorkingDir: /Workspaces/appature/git/ImsHealth.Automation
FullPath: /Workspaces/appature/git/ImsHealth.Automation/.artifacts/Debug/ImsHealth.Automation.1.1.2.nupkg
Directory '/Workspaces/appature/git/ImsHealth.Automation/Workspaces/appature/git/ImsHealth.Automation/.artifacts/Debug' not found.
An error occured when executing task 'Publish'.
Error: NuGet: Process returned an error (exit code 1).
```

## Cause

[NuGetPusher.GetArguments](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/NuGet/Push/NuGetPusher.cs#L55) currently generates an absolute path to the `.nupkg` file to be pushed.

```csharp
55:            builder.AppendQuoted(packageFilePath.MakeAbsolute(_environment).FullPath);
```

Apparently, this is a problem when running nuget on mono (tested with both 2.8.5 and 3.X.X).

### Running Nuget With Absolute Package Path

```bash
$ mono .tools/nuget.exe push "/Workspaces/appature/git/ImsHealth.Automation/.artifacts/Debug/ImsHealth.Automation.1.1.2.nupkg"
Directory '/Workspaces/appature/git/ImsHealth.Automation/Workspaces/appature/git/ImsHealth.Automation/.artifacts/Debug' not found.
```

Notice how it tries to append the absolute path it's given to the current working directory:

> '**/Workspaces/appature/git/ImsHealth.Automation/**Workspaces/appature/git/ImsHealth.Automation/.artifacts/Debug' not found.

### Running Nuget With Relative Package Path

```bash
$ mono .tools/nuget.exe push "./.artifacts/Debug/ImsHealth.Automation.1.1.2.nupkg"
Pushing ImsHealth.Automation 1.1.2 to the NuGet gallery (https://www.nuget.org)...
```

Great success!

### File a bug in Nuget

I did this: https://github.com/NuGet/Home/issues/2167

### Workaround in Cake

Fumbling around in `NuGetPusher.cs` trying to figure out how to pass a relative path when on Unix.
This isn't really working, so i'm hoping someone has suggestions about how to work around this.

```csharp
            FilePath envSpecificPackageFilePath;
            if (_environment.IsUnix())
            {
                // BUG: Nuget on mono doesn't work with absolute file paths.
                envSpecificPackageFilePath =
                    packageFilePath.GetRelativePath(_environment.WorkingDirectory).GetFilePath(packageFilePath);
            }
            else
            {
                envSpecificPackageFilePath = packageFilePath.MakeAbsolute(_environment);
            }

            builder.AppendQuoted(envSpecificPackageFilePath.FullPath);
```

**Comment by gep13** [comment]
@andycmaj this was recently discussed in the Gitter Chat Room: https://gitter.im/cake-build/cake?at=56a88fdb80ad69394a7ab567

With a potential workaround here: https://gitter.im/cake-build/cake?at=56aa2119586242210ae01122 suggested by @Redth 

The workaround will depend on whether you are using a nuspec, or driving everything from NuGetPackSettings.

Thanks for filing the issue with NuGet though, hopefully something will come from that.

**Comment by gep13** [comment]
Hmm, actually, what I linked to above was with the NuGetPack command, and I have just realised that you are talking about NuGet Push.  Sorry, I saw the similarity in the comments, and didn't read properly.

**Comment by andycmaj** [comment]
no problem... actually the response i got on the nuget bug was, "use nuget.exe 3.4 from the CI feed".
so i did that, and it works.

the next problem i ran into was that 3.4 tries to automatically push your .sybmols.nupkg along with a push of a normal package, and this seems to fail... so still following up on https://github.com/NuGet/Home/issues/2167. i'll close this one and feel free to follow that issue
