### ISSUE TITLE
Caching might break CI builds when new Cake releases are pushed

### ISSUE THREAD

**Issue by tlycken** [cake-build/cake#707]
As of today, our Cake builds are broken in some hard-to-pin-down circumstance. Here's our setup:

We have `/build.ps1` and `/build.cake` checked into source control, but `/tools` is created when the build is run. Up until at least Monday (22/2 2016) everything worked, but today builds started failing (no builds have been run between Monday and today, since work has been focused on other projects) with the following error message:

```
Preparing to run build script...
VERBOSE: Creating tools directory...
VERBOSE: Downloading packages.config...
VERBOSE: GET http://cakebuild.net/bootstrapper/packages with 0-byte payload
VERBOSE: received 105-byte response of content type text/xml; charset=utf-8
VERBOSE: Trying to find nuget.exe in path...
VERBOSE: Downloading NuGet.exe...
VERBOSE: GET http://nuget.org/nuget.exe with 0-byte payload
VERBOSE: received 1686528-byte response of content type application/octet-stream
VERBOSE: Restoring tools from NuGet...
Unable to find version '0.9.0' of package 'Cake'.
```

I've connected to the build machine and run `build.ps1` manually with no problems, but when TFS runs the script it invariably fails. This indicates of course that this failure is unrelated to Cake but instead caused by TFS, but since these failures appeared on the very first build that attempted to use Cake 0.9.0 and since haven't gone away, I thought I'd ask anyway:

Has anything changed to version 0.9.0 that could cause a failure like this when using an un-updated `build.ps1`?

**Comment by tlycken** [comment]
I can verify that it's at least partly related; if I check in `tools/packages.config` specifying version `0.8.0`, everything works as expected also when TFS triggers the build.

**Comment by gep13** [comment]
@tlycken I saw this error initially when specifying 0.9.0 in the packages.config file for the Cake build.cake.  This was due to an indexing issue on NuGet.org.  I was asking specifically for Cake 0.9.0, and this technically didn't exist on NuGet.org `yet` even though I had pushed that package version.

Do you know if the TFS infrastructure has some sort of mirror for NuGet, where the new 0.9.0 package hasn't been copied over to yet, or something like that?  This is a bit of a clutch, but it is the only thing I can think of.  It would make sense that TFS has some sort of mirror, so that it isn't directly coupled to NuGet.org.

**Comment by tlycken** [comment]
That's very possible, and worth investigating. I'll look into it and get back.

**Comment by patriksvensson** [comment]
@tlycken I'm 99% certain this is a problem with getting the package from NuGet. 
Are you using an internal NuGet server where the package hasn't been uploaded?

Easiest way to check this is RDP:ing into the server and check the available [NuGet sources](https://docs.nuget.org/consume/command-line-reference#sources-command).

**Comment by tlycken** [comment]
I don't know if TFS has some internal under-the-hood cache that comes into play here (my search results so far have been *very* noisy...) but we've not specified any internal feeds explicitly.

This is the result of running the downloaded `nuget.exe` from the `tools` directory, i.e. executing the same version of nuget with the same working directory as the TFS build:

```
PS D:\Build\agent\_work\8\s\WK\Atlantis\Main\Nuggets\tools> .\nuget.exe sources
Registered Sources:

  1.  https://www.nuget.org/api/v2/ [Enabled]
      https://www.nuget.org/api/v2/
```

I have yet to figure out where, if at all, the index for this feed is cached.

**Comment by devlead** [comment]
@tlycken you could add -Source to the nuget install command in your bootstrapper.
You're using nuget v2 exe then the source is `https://www.nuget.org/api/v2/`
For nuget v3 then the  source is `https://api.nuget.org/v3/index.json`

One thing I've seen is that if you have updated your client/server to nugetv3 then it might change your nuget sources to the v3 json endpoint which won't work with nuget v2 console. The reason v0.8.0 is working could be that that is in the local nuget cache.

What we've done internally at work is that our bootstrapper downloads the v3 version of nuget, v3 has better handling for transient errors.

Difference against standard boorstrapper is just the url i.e.
```powershell
if (!(Test-Path $NUGET_EXE)) {
    Invoke-WebRequest -Uri https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile $NUGET_EXE
}
```

**Comment by tlycken** [comment]
@devlead Thanks, that might too be a valuable lead. We're using 2.8 though:

```
PS D:\Build\agent\_work\8\s\WK\Atlantis\Main\Nuggets\tools> .\nuget.exe help
NuGet Version: 2.8.60717.93
```

**Comment by devlead** [comment]
@tlycken FYI nuget v3 also has an extra option for fallback datasource so you could try, which is nice.
`nuget install Cake -Source "https://api.nuget.org/v3/index.json" -FallbackSource "https://www.nuget.org/api/v2/"`

**Comment by devlead** [comment]
You can also as a test to debug try to install using our "nightly" builds nuget feed.
For v2 the source is `https://www.myget.org/F/cake/api/v2`
For v3 the source is `https://www.myget.org/F/cake/api/v3/index.json`

As these are pre-release packages you have to specify the `-Prerelease` flag i.e.
`nuget install Cake -Source https://www.myget.org/F/cake/api/v2 -Prerelease`

**Comment by patriksvensson** [comment]
Might (probably not but worth mentioning) also be a firewall issue.

**Comment by devlead** [comment]
@patriksvensson true, as nuget.exe & package.config is downloaded it looks like there's basic http connectivity, though ssl isn't used in that case so a different port (443 vs. 80), but ssl is used in the nuget source.

**Comment by tlycken** [comment]
Re: HTTP/HTTPS and other networking issues, note that it works if I execute the build script manually - it's *only* when I trigger the script from TFS that it doesn't work. (And yes, I've made sure to pass the same flags everywhere etc.)

**Comment by devlead** [comment]
@tlycken you could add `-Verbosity` flag with a `detailed` level to see if you get a better lead what's happening. (i.e. if it runs as a different user it could be a corrupt nuget config etc.)
I.e. 
`nuget install Cake -Source "https://www.myget.org/F/cake/api/v2" -PreRelease -Verbosity Detailed`
this will give a log similar to below
```
Feeds used:
  https://www.myget.org/F/cake/api/v2

Attempting to gather dependencies information for package 'Cake.0.9.0-build-1544' with respect to project 'C:\temp\cake', targeting 'Any,Version=v0.0'
Attempting to resolve dependencies for package 'Cake.0.9.0-build-1544' with DependencyBehavior 'Lowest'
Resolving actions to install package 'Cake.0.9.0-build-1544'
Resolved actions to install package 'Cake.0.9.0-build-1544'
Adding package 'Cake.0.9.0-build-1544' to folder 'C:\temp\priv\cake'
Added package 'Cake.0.9.0-build-1544' to folder 'C:\temp\priv\cake'
Successfully installed 'Cake 0.9.0-build-1544' to C:\temp\priv\cake
```
if it's a nuget config error you could add a nuget.config in the tools folder or specify with the `-ConfigFile` option and it'l be used instead.

A basic nuget config could look something like this
```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </packageSources>
  <disabledPackageSources />
  <activePackageSource>
    <add key="nuget.org" value="https://www.nuget.org/api/v2/" />
  </activePackageSource>
</configuration>
```

**Comment by gep13** [comment]
@tlycken I "think" I am right in saying that this has been resolved, so going to go ahead and close it.  Please feel free to re-open if required.
