### ISSUE TITLE
Add MSTest test category options

### ISSUE THREAD

**Issue by brettkc** [cake-build/cake#716]
Add ability to provide the MSTest tool with a test category filter (see: https://msdn.microsoft.com/en-us/library/ms182489.aspx#category)

**Comment by gep13** [comment]
@brettkc that seems like a good suggestion.  We would gladly accept a PR to add this functionality.

in the interim, you should be able to use the ArgumentCustomization on the MSBuildSettings class, to provide that additional argument into Cake.

**Comment by brettkc** [comment]
PR #712

**Comment by robertmuehsig** [comment]
It seems this is already implemented: https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/MSTest/MSTestSettings.cs#L29

Close?

**Comment by gep13** [comment]
@robertmuehsig Yes, I think you are right.  This was not correctly assigned to the 0.11.0 milestone.  Thanks for pointing this out!
