### ISSUE TITLE
TypeScript compiler support

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#72]

**Comment by RichiCoder1** [comment]
I may chew on this for unrelated reasons. Adding an addendum that with the upcoming TS 1.5, there's now a tsconfig.json which can contain many of these settings.

**Comment by devlead** [comment]
Cool @RichiCoder1 I would suggest you start as an addin to try out the concept.

**Comment by RichiCoder1** [comment]
Absolutely. I've got something prototyped out.

**Comment by RichiCoder1** [comment]
Probably will grab this with my Node and NPM items.

**Comment by klaus-liebler** [comment]
I am stronly interested in this feature. Does anybody plan to implement this (soon)?

**Comment by jducobu** [comment]
I'm using this build task to transpile typescript file using the config file tsconfig.json

Task("Build")
	.Does(() =>
{
	var settings = new DotNetCoreBuildSettings
    {
		//OutputDirectory = config.Path.Output,
		ToolPath = dotnet,
		Configuration = "Release",
		NoRestore = true,
		NoIncremental = true // force to rebuild solution and compile ts file
		//Framework = "netcoreapp2.1"
    };

	DotNetCoreBuild(config.Solution, settings);
});
