### ISSUE TITLE
Copy files from network location.

### ISSUE THREAD

**Issue by justkao** [cake-build/cake#720]
I would like to copy files from new twork location by calling 
`CopyFiles("\\server\directory\*.*,` `"c:\temp");`
However this use case is not supported and I am getting "UNC paths are not supported." error. 

Any reason why are you not allowing file operations over the network ?

**Comment by patriksvensson** [comment]
The reason is that no one ever implemented it :smile:

The copy mechanism supports UNC paths, but the globber do not (for good reasons) and neither does `FilePath` or `DirectoryPath` (i think).

Adding this would be a big change and require some work (and a lot of tests) but it's possible.

**Comment by devlead** [comment]
Not a bad idea, not currently imminent priority. If someone wants to contribute please ping us and we can discuss details.

**Comment by joro550** [comment]
Hey, I think I mentioned that i would like to take a shot at this.

I guess I have a few question before taking it too far
* You say that the globber doesn't work with UNC paths for good reason, do you remember what those reason are?
* Should this be grouped under the current Copy Files implementation or be it's own method i.e. Copy Remote files?

**Comment by Tdue21** [comment]
This is something that really needs looking at. +1 from me.

**Comment by devlead** [comment]
As it's potentially a large internal change, IMHO this would best if possible be implemented as a Cake module replacing the standard Cake Globber / FileSystem , that way it would be opt-in and could be tested out of bound with Cake.

**Comment by nikhilagrawaldotnet** [comment]
@justkao : Ran into this issue today in `CopyFiles`, however `CopyDirectory` was working fine.

So, as a workaround using `CopyDirectory` I first copied directory to a local directory (probably %temp%) and then copied files from there.
