### ISSUE TITLE
Support NUnit output format for XUnit2 runner

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#729]
Add argument *-nunit \<filename\>* to XUnit2 runner.

Needed by SpecFlow #727 

Current workaround is to add argument via **ArgumentCustomization**

**Comment by gep13** [comment]
@mholo65 thanks to a PR from @phillipsj this has now been implemented.

**Comment by mholo65** [comment]
@gep13, nice! As with the MSTest, I'll update the tests for SpecFlow to use this setting instead.
