### ISSUE TITLE
GitHub support

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#73]
Would be nice to be able to be able to communicate with GitHub directly from the build script. For example to create a release and to upload release assets.
- [ ] Create release.
- [ ] Upload release asset. 

This obviously need some more thought.

**Comment by ChrisMissal** [comment]
I imagine this would use Octokit.net, yes?

**Comment by patriksvensson** [comment]
@ChrisMissal For creating and uploading releases, GitHub's REST API would suffice to avoid taking a dependency. I know that I'm a little bit reluctant to include third party dependencies in Cake, but it's a slippery slope :)

Here is an example of how this could be done: https://github.com/hadouken/hadouken/blob/develop/win32/build.cake#L280

**Comment by RichiCoder1** [comment]
My intention was to use octokit. This might be the point we consider cake contrib for functionality that takes a third party dependency, but is maintained by cake.

**Comment by ChrisMissal** [comment]
For sure, I was thinking it would work like https://github.com/WCOMAB/Cake.Slack for example. If Cake could just expose Octokit, then script builds could do whatever they wanted.

**Comment by patriksvensson** [comment]
@RichiCoder1 @ChrisMissal Yes. I like the idea of maintaining `official` plugins seperate from the Cake package itself.

I'm not opposed to including third party libraries. [libgit2sharp](https://github.com/libgit2/libgit2sharp) for example is probably something we need to take a dependency on later for Git support.

**Comment by patriksvensson** [comment]
@ChrisMissal I agree. Exposing OctoKit would probably be better than writing Wrappers around everything (if I understand you correctly).

This could be done with the `#addin` pre-processor which would download Octokit from NuGet and add a reference to it in the project.

Would be nice though with support for creating releases and uploading artifacts out of the box.

**Comment by gep13** [comment]
I was just thinking...

Would it make sense to encapsulate GitReleaseManager to do this work, rather than re-invent the wheel?  We have already created, using Octokit, the ability to create a release, upload assets, close milestones, publish a release, etc.

GitReleaseManager is a standalone exe, which could easily be created as an alias in Cake.

https://gitreleasemanager.readme.io/docs/create

Just a thought :smile_cat:

**Comment by RichiCoder1** [comment]
That could work if we want it built in :)

**Comment by devlead** [comment]
Regardless GitReleaseManager could be an excellent addin, Cake addins is a great way to extend the DSL, also makes it easy to test/release out of band and super easy to move into Cake later.

**Comment by gep13** [comment]
Since GitReleaseManager Aliases have just been pulled in, I think we can go ahead and close this issue?  Thoughts?

**Comment by patriksvensson** [comment]
I actually want wrappers around GitHubs API:s as well in the future so I think we could leave this open for now.

**Comment by gep13** [comment]
No worries, just thought I would check.

**Comment by patriksvensson** [comment]
Great that you did :)

**Comment by ChrisMaddock** [comment]
I wanted the functionality to create GitHub pull requests/issues, so have thrown together an add-in to wrap Octokit and provide that. It's not pretty yet, but hopefully will become sharable at some point!

What I'm not sure about, is what other parts of the API would be worth including. The release functionality seems to be taken care of by the GitReleaseManager add-in, and I'm not sure of the value of much else in the API, for a build script.

Did you have any particular ideas of what else you thought should be included @patriksvensson? Anyone else?

**Comment by pascalberger** [comment]
There's now a [Cake.GitHub addin](https://cakebuild.net/extensions/cake-github/) available using OctoKit and which can be extended with additional features if required. There exists also a [Cake.OctoDeploy](https://cakebuild.net/extensions/cake-octodeploy/) addin providing some addins for working with GitHub releases. 

Closing this since requests for additional features should be done to the addin repos.
