### ISSUE TITLE
Support results file for MSTest runner

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#730]
Add argument */resultsfile:\[ file name \]* to MSTest runner.

Needed by SpecFlow #727

Current workaround is to add argument via ArgumentCustomization

**Comment by gep13** [comment]
@mholo65 thanks to @robertmuehsig this will be in the next version of Cake :smile:

**Comment by mholo65** [comment]
@gep13 nice! I'll update the tests to use this setting instead of ArgumentCustomization at some point...
