### ISSUE TITLE
[HOLD] Tidy up source code

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#735]
This is really bugging me and we should fix this.
- [x] Compiler warnings in XBuild (tool version 14 is not supported)
  - We can solve this by downgrading projects to use tool version 4.0.
- [x] Resharper inspection warnings
- [ ] Add InspectCode in build script
- [ ] Add DupFinder to build script
- [x] Fix StyleCop not running in VS anymore.

Anything else I've missed?

**Comment by gep13** [comment]
@patriksvensson what about DupFinder, in addition to InspectCode?

**Comment by patriksvensson** [comment]
@gep13 Added! Good suggestion :+1:

**Comment by gep13** [comment]
@patriksvensson how are you getting on with adding the InspectCode and DupFinder?  Are you still having problems?

**Comment by patriksvensson** [comment]
@gep13 Yeah, had some problems with it but will look at it again asap. Another issue is that both DupFinder and InspectCode are really slow.

**Comment by gep13** [comment]
@patriksvensson ok, not a problem at all.  I can help look at it, if you are still having issues.  Yeah, it can take a while to run.  Might be something that we want to put into a scheduled build, one that we run every night, for example, rather than on each CI.

**Comment by devlead** [comment]
@gep13 @patriksvensson sounds reasonable to run it and integration test on a nightly build target.

**Comment by gep13** [comment]
@devlead agreed.

**Comment by gep13** [comment]
Going to go ahead and pull this from the 0.16.0 milestone for now.

Looks like DupFinder and InspectCode don't currently support running against .Net Core Projects just yet:

https://youtrack.jetbrains.com/issue/RSRP-460535
https://youtrack.jetbrains.com/issue/RSRP-460534

Will come back to this one once the tools have been updated.
