### ISSUE TITLE
Unified tool resolution

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#736]
We need a common way of registering and resolving tools/addins in Cake. There are some addins that require this functionality, and it would be nice to actually have a proper tool resolution strategy in place that we can use outside of tools.

* Should allow a user to globally set a tool path from the script.
* Should be able to register tools by their file name.
* Should be able to resolve tools by their file name.
* The `IPackageInstaller` implementations should be able to:
  * Register paths to downloaded tools.
  
This would allow us to version tools correctly.

### Proposition (API)

```csharp
// Not super happy about this name.
public interface IToolService
{
  void Register(FilePath path);
  FilePath Resolve(string tool);
}

public interface ICakeContext
{
  IToolService Tools { get; }
}
```

### Proposition (implementation)

Someone who wants to override this behavior could easily use
the default implementation and only provide a new `IToolResolutionStrategy`.

Of course we need to have a mechanism to register services before 
the Cake container has been fully built but that's a problem for 
another issue.

```csharp
public interface IToolRepository
{
  void Register(FilePath path);
  IEnumerable<FilePath> Find(string tool);
}

public interface IToolResolutionStrategy
{
  FilePath Resolve(IToolRepository registry, string tool);
}

public sealed class ToolResolver : IToolService
{
  private readonly IToolRepository _repository;
  private readonly IToolResolutionStrategy _strategy;

  public ToolResolver(IToolRepository repository, IToolResolutionStrategy strategy)
  {
    _repository = repository;
    _strategy = strategy;
  }
  
  public void Register(FilePath path)
  {
    _repository.Register(path);
  }

  public FilePath Resolve(string tool)
  {
    _strategy.Resolve(_repository, tool);
  }
}
```

### Usage

```csharp
// Register a tool.
context.Tools.Register("C:/Temp/xunit-console.exe");

// Later in the xUnit tool wrapper, we resolve it like this.
var path = context.Tools.Resolve("xunit-console.exe");
```

**Comment by stffabi** [comment]
Would it be possible at the same time the support of "Tools" which don't need to provide ".exe" Files? We have for example another NuGet Package which includes MsBuild Loggers we would like to use. If that would be supported, we could do something like the following in order to resolve the path to the logger.

`
var path = context.Tools.Resolve("MsBuildXmlLogger.dll");
`

**Comment by patriksvensson** [comment]
@stffabi Thanks for your feedback! Add an issue about that you want tools to be able to consist of *.dll as well and we can continue the discussion there.
