### ISSUE TITLE
Cake does not find it's own nuget.exe on Linux

### ISSUE THREAD

**Issue by hal-ler** [cake-build/cake#737]
"Error: Could not locate nuget.exe.".

Changing:
NUGET_EXE=$TOOLS_DIR/nuget.exe

To:

NUGET_EXE=$TOOLS_DIR/NuGet.exe

in bootstrap script solves the problem.

**Comment by RichiCoder1** [comment]
This should probably be posted in the issues for https://github.com/cake-build/bootstrapper

**Comment by hal-ler** [comment]
I did not see the Linux shell script in the bootstrapper repo.

Also an alternative fix is in:
NuGetToolResolver.cs

            // Check if tool exists in tool folder
            const string expression = "./tools/**/NuGet.exe";
            var toolsExe = _globber.GetFiles(expression).FirstOrDefault();

This file also has:
path.Path.CombineWithFilePath("nuget.exe"))

So there is an inconsistency of naming for Unix systems anyway.

**Comment by patriksvensson** [comment]
@hal-ler Yes, there is a fix in the making takes care of the tool resolution that hopefully will be released in v0.10.

**Comment by devlead** [comment]
The standard Posix  bootstrapped is here : [bootstrapper/blob/master/res/scripts/build.sh](https://github.com/cake-build/bootstrapper/blob/master/res/scripts/build.sh) it downloads to nuget.exe so guess casing isn't an issue there?

**Comment by patriksvensson** [comment]
@RichiCoder1 Agree. This affects https://github.com/cake-build/bootstrapper/blob/master/res/scripts/build.sh

**Comment by devlead** [comment]
@patriksvensson as it downloads to lower case nuget.exe and Cake looks for lower case nuget.exe it should find it in Cake right?

Both Travis &  local Linux works for me with the standard bootstrapper.

**Comment by patriksvensson** [comment]
@devlead Depends. It might be in 'Path' under a different name but not sure since I don't have the code in front of me.

**Comment by devlead** [comment]
https://github.com/cake-build/cake/blob/develop/build.sh#L10 downloads to lower case too so just changing the script would break the build currently right?
As envvariable is set it should work, unless someone manually put a NuGet.exe in tools, or doesn't curl preserve filename given in some cases?

It shouldn't be inconsistent though, it should be same throughout the code. Perhaps tool resolution should be case insensitive. List files an pick best match :wink:

**Comment by hal-ler** [comment]
As mentioned above (sorry for my confusing text), NuGetToolResolver.cs looks for "NuGet.exe" instead of "nuget.exe", but it seems like the only instance in the code. Changing the script was a short-term solution for myself, but it makes more sense to have tool resolution consistent with the script.

**Comment by RichiCoder1** [comment]
Most everyone I've seen that has to deal with case-sensitivity has standardized on NuGet.exe.

**Comment by devlead** [comment]
nuget.org has standardized with lower case now though.:wink:
https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
https://dist.nuget.org/win-x86-commandline/v2.8.6/nuget.exe
https://dist.nuget.org/win-x86-commandline/v3.3.0/nuget.exe

**Comment by RichiCoder1** [comment]
True enough. I actually prefer the all lower case version. The issue with switching to lowercase by default is there is more than a little code (but not much) that assumes `NuGet`. You might break build scripts with the old naming of nuget if you switch. Would be worth standardizing it either way :)
