### ISSUE TITLE
Use NuGet packages with reference directive

### ISSUE THREAD

**Issue by Sam13** [cake-build/cake#748]
As far as I have read in the documentation it is currently only possible to gather Cake addins or tools directly from NuGet?
For me it would make sense to have that also for references.

Example: I would like to parse a CSV file with the NuGet package _CsvTools_
My script:
```
#r nuget://CsvTools
...
DataAccess.DataTable.New.ReadLazy(@"C:\Test\SomeCsv.csv");
...
```

The only thing which might be considered is to locate the assembly to load inside the NuGet package. Maybe this can be added to the _nuget:_ directive?

**Comment by devlead** [comment]
You can use `#addin` pre-processor to reference any assembly from nuget feed, you just have to add , unfortunately `CsvTools` seems to have an issue, but below is a working sample with another nuget package.
```csharp
#addin nuget:?package=CsvHelper
using CsvHelper;

using(var stream = Context.FileSystem.GetFile("C:/Temp/SomeCsv.csv").OpenRead())
{
    using(var sr = new StreamReader(stream))
    {
        var csv = new CsvReader(sr);
        while( csv.Read() )
        {
            var baseName = csv.GetField<string>( "BaseName" );
            var fullName = csv.GetField<string>("FullName");
            Information("BaseName: {0}\tFullName: {1}", baseName, fullName);
        }
    }
}
``` 

The `CsvTools` issue can be because they're assembly isn't in a framework folder which isn't an recommended way of packaging nugets, but think Cake should support it.

**Comment by Sam13** [comment]
@devlead Thanks for your quick help. It works, CsvHelper is more powerful I think :+1: , So I have to use the #addin directive to grab binaries from NuGet directly?

**Comment by devlead** [comment]
@Sam13 addin will download if needed and reference any assembly from nuget, so you use it instead of `#r`

**Comment by Sam13** [comment]
@devlead Ok that's exactly what I was looking for and just tried with an incompatible package
