### ISSUE TITLE
Add example documentation to aliases

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#750]
**This ___do not___ have to be done in a single PR.** Make sure to reference this issue if you submit example documentation and we'll cross it off the list once it's merged.

An example of how example documentation could look like can be found here: https://github.com/cake-build/cake/blob/develop/src/Cake.Common/IO/FileAliases.cs#L20-L29

**Aliases without example documentation:**

- [x] `Cake.Common​.StartProcess(FilePath, ​ProcessSettings, ​out IEnumerable)​`
- [x] `Cake.Common.IO​.Unzip(FilePath, ​DirectoryPath)​`
- [x] `Cake.Common.Net​.DownloadFile(string)​`
- [x] `Cake.Common.Net​.DownloadFile(Uri)​`
- [x] `Cake.Common.Net​.DownloadFile(string, ​FilePath)​`
- [x] `Cake.Common.Net​.DownloadFile(Uri, ​FilePath)​`
- [x] `Cake.Common.Tools​.DotNetBuild(FilePath)​`
- [x] `Cake.Common.Tools​.DotNetBuild(FilePath, ​Action<DotNetBuildSettings>)​`
- [x] `Cake.Common.Tools.MSBuild​.MSBuild(FilePath)​`
- [x] `Cake.Common.Tools.MSBuild​.MSBuild(FilePath, ​Action<MSBuildSettings>)​`
- [x] `Cake.Common.Tools.MSBuild​.MSBuild(FilePath, ​MSBuildSettings)​`
- [x] `Cake.Common.Tools.MSTest​.MSTest(string)​`
- [x] `Cake.Common.Tools.MSTest​.MSTest(string, ​MSTestSettings)​`
- [x] `Cake.Common.Tools.MSTest​.MSTest(IEnumerable<FilePath>)​`
- [x] `Cake.Common.Tools.MSTest​.MSTest(IEnumerable<FilePath>, ​MSTestSettings)​`
- [x] `Cake.Common.Tools.NuGet​.NuGetSetApiKey(string, ​string, ​NuGetSetApiKeySettings)​`
- [x] `Cake.Common.Tools.NuGet​.NuGetSetApiKey(string, ​string)​`
- [x] `Cake.Common.Tools.NuGet​.NuGetSetProxy(string, ​string, ​string, ​NuGetSetProxySettings)​`
- [x] `Cake.Common.Tools.NuGet​.NuGetSetProxy(string, ​string, ​string)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit3(string)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit3(string, ​NUnit3Settings)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit3(IEnumerable<string>)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit3(IEnumerable<FilePath>)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit3(IEnumerable<string>, ​NUnit3Settings)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit3(IEnumerable<FilePath>, ​NUnit3Settings)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit(string)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit(string, ​NUnitSettings)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit(IEnumerable<string>)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit(IEnumerable<FilePath>)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit(IEnumerable<string>, ​NUnitSettings)​`
- [x] `Cake.Common.Tools.NUnit​.NUnit(IEnumerable<FilePath>, ​NUnitSettings)​`
- [x] `Cake.Common.Tools.Roundhouse​.RoundhouseMigrate(RoundhouseSettings)​`
- [x] `Cake.Common.Tools.Roundhouse​.RoundhouseDrop(RoundhouseSettings)​`
- [x] `Cake.Common.Tools.WiX​.WiXCandle(string, ​CandleSettings)​`
- [x] `Cake.Common.Tools.WiX​.WiXCandle(IEnumerable<FilePath>, ​CandleSettings)​`
- [x] `Cake.Common.Tools.WiX​.WiXLight(string, ​LightSettings)​`
- [x] `Cake.Common.Tools.WiX​.WiXLight(IEnumerable<FilePath>, ​LightSettings)​`
- [x] `Cake.Common.Tools.XBuild​.XBuild(FilePath)​`
- [x] `Cake.Common.Tools.XBuild​.XBuild(FilePath, ​Action<XBuildSettings>)​`
- [x] `Cake.Common.Tools.XBuild​.XBuild(FilePath, ​XBuildSettings)​`
- [x] `Cake.Common.Tools.XUnit​.XUnit2(string)​`
- [x] `Cake.Common.Tools.XUnit​.XUnit2(string, ​XUnit2Settings)​`
- [x] `Cake.Common.Tools.XUnit​.XUnit2(IEnumerable<string>)​`
- [x] `Cake.Common.Tools.XUnit​.XUnit2(IEnumerable<FilePath>)​`
- [x] `Cake.Common.Tools.XUnit​.XUnit2(IEnumerable<string>, ​XUnit2Settings)​`
- [x] `Cake.Common.Tools.XUnit​.XUnit2(IEnumerable<FilePath>, ​XUnit2Settings)​`
- [x] `Cake.Common.Tools.XUnit​.XUnit(string)​`
- [x] `Cake.Common.Tools.XUnit​.XUnit(string, ​XUnitSettings)​`
- [x] `Cake.Common.Tools.XUnit​.XUnit(IEnumerable<string>)​`
- [x] `Cake.Common.Tools.XUnit​.XUnit(IEnumerable<FilePath>)​`
- [x] `Cake.Common.Tools.XUnit​.XUnit(IEnumerable<string>, ​XUnitSettings)​`
- [x] `Cake.Common.Tools.DupFinder​.DupFinder(FilePath)​`
- [x] `Cake.Common.Tools.DupFinder​.DupFinder(FilePath, ​DupFinderSettings)​`
- [x] `Cake.Common.Tools.DupFinder​.DupFinder(IEnumerable<FilePath>)​`
- [x] `Cake.Common.Tools.DupFinder​.DupFinder(IEnumerable<FilePath>, ​DupFinderSettings)​`
- [x] `Cake.Common.Tools.DupFinder​.DupFinder(string)​`
- [x] `Cake.Common.Tools.DupFinder​.DupFinder(string, ​DupFinderSettings)​`
- [x] `Cake.Common.Tools.DupFinder​.DupFinderFromConfig(FilePath)​`
- [x] `Cake.Common.Tools.Fixie​.Fixie(string)​`
- [x] `Cake.Common.Tools.Fixie​.Fixie(string, ​FixieSettings)​`
- [x] `Cake.Common.Tools.Fixie​.Fixie(IEnumerable<string>)​`
- [x] `Cake.Common.Tools.Fixie​.Fixie(IEnumerable<FilePath>)​`
- [x] `Cake.Common.Tools.Fixie​.Fixie(IEnumerable<string>, ​FixieSettings)​`
- [x] `Cake.Common.Tools.Fixie​.Fixie(IEnumerable<FilePath>, ​FixieSettings)​`
- [x] `Cake.Common.Tools.InspectCode​.InspectCode(FilePath)​`
- [x] `Cake.Common.Tools.InspectCode​.InspectCode(FilePath, ​InspectCodeSettings)​`
- [x] `Cake.Common.Tools.InspectCode​.InspectCodeFromConfig(FilePath)​`
- [x] `Cake.Common.Tools.NSIS​.MakeNSIS(FilePath)​`
- [x] `Cake.Common.Tools.NSIS​.MakeNSIS(FilePath, ​MakeNSISSettings)​`
- [x] `Cake.Common.Xml​.XmlTransform(string, ​string)​`
- [x] `Cake.Common.Xml​.XmlTransform(string, ​string, ​XmlTransformationSettings)​`
- [x] `Cake.Common.Xml​.XmlTransform(FilePath, ​FilePath, ​FilePath)​`
- [x] `Cake.Common.Xml​.XmlTransform(FilePath, ​FilePath, ​FilePath, ​XmlTransformationSettings)​`
- [x] `Cake.Common.Xml​.XmlPeek(FilePath, ​string)​`
- [x] `Cake.Common.Xml​.XmlPeek(FilePath, ​string, ​XmlPeekSettings)​`

**Comment by luisgoncalves** [comment]
@patriksvensson @gep13 `Cake.Common​.StartProcess(FilePath, ​ProcessSettings, ​out IEnumerable)​` [already has the example](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/ProcessAliases.cs#L88), but it's not showing on the site. Was added [here](https://github.com/cake-build/cake/commit/1bc3113e0403a010b9e51da84726a60ea71a0d1b).

**Comment by gep13** [comment]
@luisgoncalves you are right, this does seem a little strange.

@devlead @patriksvensson any thoughts on why this wouldn't be showing up?

**Comment by phillipsj** [comment]
@patriksvensson @gep13 Looks like NUnit3 can be marked on the list as completed.

**Comment by gep13** [comment]
>@phillipsj said...
@patriksvensson @gep13 Looks like NUnit3 can be marked on the list as completed.

Yip, I think you are right :+1:

**Comment by gep13** [comment]
Huge thanks to everyone who helped out in getting this documentation effort completed! :smile:
