### ISSUE TITLE
Better document ToolSettings ArgumentCustomization property

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#758]
ArgumentCustomization  need better help and sample code, to make it's purpose clear and how it's used.

ArgumentCustomization is in general the exception and not the rule, as it's used when Cake alias / settings don't provide what's necessary, i.e. when a tool adds an parameter before Cake knows about it.

Code:
* https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Tooling/ToolSettings.cs#L21 

Documentation:
* http://cakebuild.net/api/cake.core.tooling/d75cd243/60ae911b

**Comment by patriksvensson** [comment]
Merged!
