### ISSUE TITLE
TeamCity ImportDotCoverCoverage tests fail when running on TeamCity

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#766]
TeamCityProvider [WriteServiceMessage](https://github.com/cake-build/cake/blob/77430f25a454424650240ea3522cf3814e4c8abd/src/Cake.Common/Build/TeamCity/TeamCityProvider.cs#L253) works directly with the Console, this isn't very _"mockable"_, because this the [TheImportDotCoverCoverageMethod](https://github.com/cake-build/cake/blob/77430f25a454424650240ea3522cf3814e4c8abd/src/Cake.Common.Tests/Unit/Build/TeamCity/TeamCityProviderTests.cs#L64) hi-jacks the console stream.

This works an all build systems except TeamCity were these service messages have a meaning.

I'll shorty submit a PR with a suggested fix for this.

**Comment by mholo65** [comment]
@devlead Hmm, why is it failing on TeamCity? I mean [TheImportDotCoverCoverageMethod](https://github.com/cake-build/cake/blob/77430f25a454424650240ea3522cf3814e4c8abd/src/Cake.Common.Tests/Unit/Build/TeamCity/TeamCityProviderTests.cs#L69) resets the console stream on dispose?

A solution with a "mockable" output for WriteServiceMessage sounds like a less "hacky" solution though.

**Comment by devlead** [comment]
@mholo65 It fails because XUnit is TeamCity aware and does a little magic so test is already within a service message basically.

**Comment by mholo65** [comment]
..of course, and since **Console** is static, we're hijacking all output.
