### ISSUE TITLE
Add StorePasswordInClearText to NuGetSoiurceAdd NuGetSourcesSettings

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#774]
Some build server environments impersonate users or in other ways limit so unprotect/protect .Net API:s can't be used.

The `-StorePasswordInClearText` parameter works around this problem by storing passwords in plaintext.

**Comment by patriksvensson** [comment]
Related to #775.

**Comment by patriksvensson** [comment]
Merged and closed! Awesome :+1:
