### ISSUE TITLE
Expected EOT error

### ISSUE THREAD

**Issue by Alcruz** [cake-build/cake#796]
Hey, 

My building is working ok on my machine, but when my partner or the CI clone the repository an try to run the build, the are getting an error "Expected EOT".

![error](https://cloud.githubusercontent.com/assets/2265826/14063144/e6d63154-f391-11e5-973a-32a0bf302d40.PNG)

**Comment by Alcruz** [comment]
I Solved the problem, It was due line endings.

Thanks.

**Comment by olivier-spinelli** [comment]
I have the same issue but can't find where the EOT is mising :(
May you explain yours?

**Comment by devlead** [comment]
AppVeyor keeps same line endings as repo, you could try overriding that with something like this:
https://github.com/cake-build/cake/blob/develop/appveyor.yml#L1-L3

**Comment by RehanSaeed** [comment]
What about if you have a `.gitattributes` file with this in it:

```
# Set default behavior to automatically normalize line endings.
* text=auto
```
