### ISSUE TITLE
Svn Support

### ISSUE THREAD

**Issue by Nysosis** [cake-build/cake#80]
Would be nice to be able to export/checkout repositories.

**Comment by mholo65** [comment]
I might be needing export functionality in the future.

@patriksvensson do you prefer an addin using [SharpSVN](https://sharpsvn.open.collab.net/) or a Tool in Cake.Common using the svn exe?

**Comment by devlead** [comment]
@mholo65 An SharpSVN addin would be a excellent place to start.

**Comment by gep13** [comment]
@mholo65 I was just away to say the same thing as @devlead :smile:

**Comment by mholo65** [comment]
Yep, figured that since Git is available as an Addin, it would be rude to add SVN into Cake.Common :smile:

**Comment by gep13** [comment]
@mholo65 that is not to say that one, or both of them, won't be pulled into Common at some point in the future.  However, addin's are a good place to incubate extensions of Cake, and allow them to mature.

**Comment by mholo65** [comment]
Addin work started [here](https://github.com/mholo65/Cake.Svn), can't say when it will be ready.

**Comment by AnderssonPeter** [comment]
@mholo65 any news on this? I would like to check that everything is checked into the svn server before doing a produktion release!

**Comment by mholo65** [comment]
@AnderssonPeter sorry, havent touched this in a looong while

Did only need svn export, but currently running it using **Process.Start()**

I have something done in this branch https://github.com/mholo65/Cake.Svn/tree/wip/export
If you would like to continue on it, I could have @gep13 transfer it to cake-contrib.

**Comment by gep13** [comment]
@mholo65 @AnderssonPeter if you want, happy to move that repo under the Cake-Contrib organisation, and to get you both added to the team associated with it.

**Comment by gep13** [comment]
A Cake.Svn addin has now been released.  You can find it here:

https://www.nuget.org/packages/Cake.Svn/
