### ISSUE TITLE
BOM Problem in XmlPoke 

### ISSUE THREAD

**Issue by MohsenAra** [cake-build/cake#800]
hi
if call XmlPoke with Source Of Xml 
then if Call again XmlPoke with result of above Operation 
then failed with this error 
Result Message:	System.Xml.XmlException : Data at the root level is invalid. Line 1, position 1.

Because when Generate result (in save XmlDocument) in  Previous Step Added Bom To Result

**Comment by devlead** [comment]
Hi @MohsenAra,
Sorry to hear you're having issues.
Are you passing the contents of the file or the filename?
Could you create a gist or repository with a repo that we can use for troubleshooting?
Thanks, 
/M

**Comment by MohsenAra** [comment]
thank you for attention 

I Add Test To My Fork Of cake 

Shuold_Sourcec_Same_At_End() in file 
[https://github.com/MohsenAra/cake/blob/develop/src/Cake.Common.Tests/Unit/XML/XmlPokeTests.cs](url)
and add these methods 

string ReadSource()
string PokeSource(string source, string xpath, string value)

https://github.com/MohsenAra/cake/blob/develop/src/Cake.Common.Tests/Fixtures/XmlPokeFixture.cs](url)
for check

**Comment by MohsenAra** [comment]
i want pull request for some other thing 
then must make decision about this !

any plan ?

**Comment by MohsenAra** [comment]
thanks
