### ISSUE TITLE
Parse multiple InternalsVisibleTo attributes from AssemblyInfo

### ISSUE THREAD

**Issue by appakz** [cake-build/cake#801]
It's awesome that the AssemblyInfoCreator / AssemblyInfoSettings classes allow for creating AssemblyInfo files with multiple InternalsVisibleTo attributes, but the AssemblyInfoParseResult only exposes a single string property which pulls in the first InternalsVisibleTo defined in the file. I'm using Cake to read in AssemblyInfo files that are under version control, parse them, rev the versions, inject some company/trademark info, then copy that info into a new Cake-generated AssemblyInfo using AssemblyInfoCreator. I'd like to be able to use the built-in AssemblyInfo parsing, but I have a few AssemblyInfo files that define multiple InternalsVisibleTo attributes.

Am I missing some obvious way to accomplish this, or is this a good candidate for an update to AssemblyInfoParseResult?

**Comment by patriksvensson** [comment]
@appakz Sorry for not responding until now but I completely missed this issue for some reason.
I went ahead and fixed this for you in #825 and it will hopefully be available in the 0.11.0 release.
