### ISSUE TITLE
Build.ps1 file from "Setting up a new project" page broken

### ISSUE THREAD

**Issue by kjohann** [cake-build/cake#802]
I tried to follow the instructions from http://cakebuild.net/docs/tutorials/setting-up-a-new-project to set up a new project using Cake. However, when I run the build.ps1 script I get the following error: 

```
.\build.ps1 : A parameter with the name 'Verbose' was defined multiple times for the command
At line:1 char:1
+ .\build.ps1
+ ~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (:) [], MetadataException
    + FullyQualifiedErrorId : ParameterNameAlreadyExistsForCommand
```

The file located at http://cakebuild.net/bootstrapper/windows seems to be out of date and should be updated with a new version that works out of the box. The current works fine if the Verbose switch is removed.

**Comment by RLittlesII** [comment]
I ran into this issue with a newer version of Windows PowerShell.  I am not sure this is something that can be changed. I believe the script is written for the lowest supported version of PowerShell.  So to make this change, would break PowerShell V2 for sure.

**Comment by adamrodger** [comment]
The problem at the moment is it's completely broken. Powershell adds a few switches by default and `-Verbose` is one of them [(see here)](https://technet.microsoft.com/en-us/library/dd315352.aspx).

The Powershell script either needs to stop using the same name as the default one added by Powershell, or just use the one Powershell provides. As @kjohann says, if you manually remove the `Verbose` flag from the `Params` section then it works fine because instead the one provided by Powershell is used.

**Comment by kjohann** [comment]
Who's using Powershell pre V2 anyways? ;)

A possible solution would be to update the script with the `Verbose` flag removed, and then add a note on the "Setting up a new project" page to use a different url to get the bootstrapper if you are using Powershell V1. This url can be something like http://cakebuild.net/bootstrapper/legacyPS

**Comment by gep13** [comment]
@kjohann @adamrodger @RLittlesII can you all please try the sample script again?  I have just completed the work necessary to complete the Pull Request that was done here:

https://github.com/cake-build/bootstrapper/pull/33

And this issue should now be corrected.  Please let me know if this is now the case, and we can get this issue closed out.  Thanks, and apologies for any inconvenience this might have caused.

**Comment by kjohann** [comment]
@gep13: It's working now :)

**Comment by gep13** [comment]
@kjohann that is great news!
