### ISSUE TITLE
Exception running InspectCode and then directly after TeamCity.ImportData

### ISSUE THREAD

**Issue by laurentkempe** [cake-build/cake#805]
Here is the exception 

> [17:00:11][Step 1/1] Importing data from 'artifacts/_ReSharperReports/inspectcode-report.xml' (45.71 KB) with 'ReSharperInspectCode' processor
> [17:00:11][Step 1/1] Caught exception while running service process importData
> [17:00:11]
> [Step 1/1] java.io.FileNotFoundException: C:\Temp\buildAgent1\work\ab9b99833ae569b1\artifacts\_ReSharperReports\inspectcode-report.xml (The process cannot access the file because it is being used by another process)
>     at java.io.FileInputStream.open0(Native Method)
>     at java.io.FileInputStream.open(FileInputStream.java:195)
>     at java.io.FileInputStream.<init>(FileInputStream.java:138)
>     at jetbrains.buildServer.dotnetTools.agent.inspectCode.InspectCodeFileProcessor.processReport(InspectCodeFileProcessor.java:54)
>     at jetbrains.buildServer.dotnetTools.agent.inspectCode.InspectCodeDataProcessor.processData(InspectCodeDataProcessor.java:38)
>     at jetbrains.buildServer.agent.impl.inspections.DataImportServiceMessage$1.run(DataImportServiceMessage.java:93)
>     at jetbrains.buildServer.agent.impl.serviceProcess.impl.ThreadedServiceProcessFactory$1.run(ThreadedServiceProcessFactory.java:31)
>     at java.lang.Thread.run(Thread.java:745)

This is due to [this line](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/InspectCode/InspectCodeRunner.cs#L81) which does `resultsFile.Open(FileMode.Open)`

Looks like there is the same problem here https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/DupFinder/DupFinderRunner.cs#L193 cc @gep13

**Comment by devlead** [comment]
Yeah that stream should be wrapped ina using statement so it's disposed directly.

**Comment by gep13** [comment]
Or, should the FileAccess be changed to FileAccess.Read, so it doesn't lock the file?

**Comment by gep13** [comment]
i.e.

```
var xmlDoc = XDocument.Load(resultsFile.OpenRead());
```

**Comment by gep13** [comment]
or it could even be `ReadLines()` which handles the disposing for us, assuming we know what the Encoding is.

**Comment by devlead** [comment]
Well it could be read, but important part probably the dispose part, on phone now, but should be something like. 
```csharp
XDocument xmlDoc;
using(var stream = resultsFile.OpenRead())
{
    xmlDoc = XDocument.Load(stream);
}
```

**Comment by laurentkempe** [comment]
I would go with the using!

**Comment by devlead** [comment]
Perhaps xml load alias so it can be reused :wink:

**Comment by lionelplessis** [comment]
Why not simply ```XDocument.Load(filePath);```?

**Comment by patriksvensson** [comment]
@lionelplessis Not possible to write unit tests for that path so stream is preferred.

**Comment by lionelplessis** [comment]
Thanks @patriksvensson, I had the feeling I was missing something but still I had to ask just in case :smiley:. Makes sense.

**Comment by gep13** [comment]
@laurentkempe @lionelplessis can you please give the 0.10.1 version of Cake a run, and confirm that the issue that you raised has been resolved?  Thanks!

**Comment by laurentkempe** [comment]
@gep13 I will and let you know asap. Currently I am rebuilding our whole build infrastructure. But that should be done till tonight

**Comment by gep13** [comment]
@laurentkempe perfect, thank you!

**Comment by laurentkempe** [comment]
[![selfie-0](http://i.imgur.com/956r9nw.png)](https://github.com/thieman/github-selfies/)

:+1: Works perfectly! well done @gep13

**Comment by gep13** [comment]
@laurentkempe glad to hear it!  Please let us know if you run into any other issues, or if you have further questions!

**Comment by laurentkempe** [comment]
@gep13 don't worry I will do so :smiley:
