### ISSUE TITLE
Mono support

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#81]

**Comment by diegobfernandez** [comment]
Is there anything I could do to help this to move on?
I'm kind of desperate for an alternative build system for .NET, but I'm using mono.

**Comment by patriksvensson** [comment]
Hello @diegobfernandez!

We absolutely need help with this one! I actually had a conversation about this with @devlead just a couple of days ago, so the timing is perfect.

However, we're not sure if we should add support for Mono via something like [Mono.CSharp](http://docs.go-mono.com/index.aspx?link=N:Mono.CSharp) (available on NuGet as well) or try to get this working with CoreClr using Roslyn. Maybe the `Mono.CSharp` approach would be the best one for now until CoreClr "settled" a little more.

I think the easiest approach would be to create a new [IScriptSessionFactory](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Scripting/IScriptSessionFactory.cs) and [IScriptSession](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/Scripting/IScriptSession.cs), and configure the container in [Program.cs](https://github.com/cake-build/cake/blob/develop/src/Cake/Program.cs) to use those if running on Mono.

If you want to give this a shot, we would appreciate it! :+1:

**Comment by patriksvensson** [comment]
*This is a brain dump for the Mono.CSharp support.*

Let's say we have the following Cake script.

```csharp
public class Test
{
	public int MagicNumber
	{
		get { return 42; }
	}

	public void DoMagic()
	{
		Console.WriteLine("Hello from {0}", MagicNumber);
	}
}

public int MagicNumber()
{
	return 99;
}

public void DoStuff(Action<int> stuff)
{
	Console.WriteLine("Doing stuff");
}

Task("Hello")
   .Does(() =>
{
	new Test().DoMagic();
});
```


To get this to run using Mono.CSharp, we would have to evaluate the different blocks individually. We would also need to rewrite the methods to something that could be executed individually outside a class scope, such as a delegate variable.

**1) Extract and evaluate the class.**

```csharp
public class Test
{
	public int MagicNumber
	{
		get { return 42; }
	}

	public void DoMagic()
	{
		Console.WriteLine("Hello from {0}", MagicNumber);
	}
}
```

**2) Rewrite the MagicStuff method to a delegate.**

```csharp
Func<int> MagicNumber = delegate() {
	return 99;
}
```

**3) Rewrite the DoStuff method to a delegate.**

```csharp
Action<Action<int>> DoStuff = delegate(Action<int> stuff) {
	Console.WriteLine("Doing stuff");
}
```

**4) Invoke the Task as usual.**

```csharp
Task("Hello")
   .Does(() =>
{
	new Test().DoMagic();
});
```

Properties are tricky, since we would need to rewrite the invocation to a delegate invocation as well. We could probably support this for alias properties, but I'm not sure how to go about this for script defined properties. I personally never had a use for a property in a script so I think we could ignore this for now.
