### ISSUE TITLE
Add NuGetPacker support for IncludeReferencedProjects

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#818]
[NuGetPacker.cs](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Tools/NuGet/Pack/NuGetPacker.cs) is missing support for `IncludeReferencedProjects`.

I need this now and there's no escape hatch to pass arbitrary command-line parameters.

References:
* [NuGet Pack](https://docs.nuget.org/consume/command-line-reference#pack-command)

**Comment by gep13** [comment]
>@gitfool said...
I need this now and there's no escape hatch to pass arbitrary command-line parameters.

This is incorrect.

As per the documentation [here](http://cakebuild.net/api/cake.common.tools.nuget.pack/88db3dc2) all base settings classes derive from `ToolSettings` http://cakebuild.net/api/cake.core.tooling/d75cd243 which includes the option to specify a specific path for where the Tool in question is located, and also to allow full customization of the arguments that are being passed to it.  Whether this is adding additional parameters (that have not as yet been included in the Cake Tool) or to allow augmenting of the existing arguments.

Although we still require a documented example of how this can be used, in your case, you should be able to do something like:

```
var settings = new NuGetPackSettings ();
settings.ArgumentCustomization = args => args.Append("-IncludeReferencedProjects");
NuGetPack(pathToNugetFile, settings);
```

Hope that helps!

**Comment by gitfool** [comment]
@gep13 An escape hatch is essential, so really good to know. Thanks!

Meanwhile, this should only be needed for 'uncommon' parameters or as a last resort, so it would be preferable to have my PR accepted. :wink:

**Comment by gep13** [comment]
>@gitfool said...
Meanwhile, this should only be needed for 'uncommon' parameters or as a last resort, so it would be preferable to have my PR accepted. :wink:

Agreed.  However, it should be understood that the time between a PR, review, and ultimately a new release of Cake is not something that happens immediately, and since you said you need to **now** I was providing a mechanism to continue with the build script until the next release of Cake.

**Comment by gitfool** [comment]
Much appreciated too.

**Comment by daveaglick** [comment]
I came here after searching for an issue about this, ready to open my own, only to discover it was already fixed! Yay community :+1: Thanks @gitfool
