### ISSUE TITLE
Log tools command-line at higher log level (preferably default)

### ISSUE THREAD

**Issue by gitfool** [cake-build/cake#820]
I'm used to and prefer being able to see the command-line of all tools being run by default. This is also the behavior in TeamCity. Obviously subjective though.

References:
- [ProcessRunner.cs#L63](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/IO/ProcessRunner.cs#L63)
- [ProcessWrapper.cs#L61](https://github.com/cake-build/cake/blob/develop/src/Cake.Core/IO/ProcessWrapper.cs#L61)

**Comment by petriashev** [comment]
see my answer: https://stackoverflow.com/questions/50826394/how-to-print-tool-command-line-in-cake/50826495#50826495

**Comment by devlead** [comment]
Fixed by #2486
