### ISSUE TITLE
Add an EnsureDirectoryExists Alias to CreateDirectory and not fail if it exists

### ISSUE THREAD

**Issue by Redth** [cake-build/cake#821]
Currently using `CreateDirectory ("./tmp")` throws an error if it already exists.

I'm finding a lot of times I end up with this code in my scripts:
```
if (!DirectoryExists ("./tmp"))
    CreateDirectory ("./tmp");
```

It would be very helpful to have an alias that does this for us:
```
EnsureDirectoryExists ("./tmp");
```

**Comment by gitfool** [comment]
I'm 'away from compiler' so I can't check, but ideally that should work for multiple levels of missing directories.

**Comment by gep13** [comment]
Fixed via https://github.com/cake-build/cake/commit/674420b165f7d50d2cfa4c6a4c882c42ee5fd397
