### ISSUE TITLE
#reference cannot be used effectively with System references

### ISSUE THREAD

**Issue by hal-ler** [cake-build/cake#827]
`#reference` expects the path to the given reference, thus it cannot be used effectively to load other `System.*` libraries (especially in a cross-platform scenario).

Interestingly `Assembly.LoadFrom` works with only the assembly name on Windows, but it does not work on Mono. Would it break something to try `Assembly.Load` first if the given string contains no extension and no path delimiter?

**Comment by hal-ler** [comment]
Easy way to reproduce, just put the following at the start of a Cake script:

`#reference "System.IO.Compression.FileSystem"`

It works on Windows, but fails on Linux.

**Comment by patriksvensson** [comment]
@hal-ler What happens if you write `#reference "System.IO.Compression.FileSystem.dll"`?

**Comment by patriksvensson** [comment]
@hal-ler Also, could you paste the log of the build here (with diagnostic verbosity on) so we can see the actual error and stack trace? Thanks!

**Comment by hal-ler** [comment]
Sorry for not responding earlier.

With diagnostic verbosity on :
`Error: System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Compression.FileSystem.dll' or one of its dependencies`
`File name: 'System.IO.Compression.FileSystem.dll'`
`  at (wrapper managed-to-native) System.Reflection.Assembly:LoadFrom (string,bool)`
`  at System.Reflection.Assembly.LoadFrom (System.String assemblyFile) <0x40b7bb70 + 0x0000f> in <filename unknown>:0 `

The same without the `dll` extension or even when trying `System.Core`.

**Comment by hal-ler** [comment]
Output of `gacutil -l System.IO.Compression.FileSystem`:

`The following assemblies are installed into the GAC:`
`System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089`
`Number of items = 1`

**Comment by kentcb** [comment]
This bit me today, a couple of years on. Trying to load `System.Runtime.Serialization` so that I can use `EnumValueAttribute` to parse some JSON. Haven't found a workaround yet.

**Comment by augustoproiete** [comment]
Closing as `wont-fix` given that [Cake v2.0.0 only supports the .NET Tool runner on .NET Core 3.1 or higher](https://cakebuild.net/blog/2021/11/cake-v2.0.0-released#supported-runners-and-required.net-version)
