### ISSUE TITLE
Add generic optional tool timeout

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#830]
Currently some tools can hang with no chance of recovery, the ability to optionally set a timeout for would allow to take action in script and do retry or just abort on timeout.

**Comment by daveaglick** [comment]
Is the timeout opt-in or opt-out (I.e., will there be a default timeout for tools that don't specify an alternative)?

**Comment by devlead** [comment]
@daveaglick it's opt-in.

**Comment by devlead** [comment]
@daveaglick didn't wanna change any semantics in #831, could be a bigger discussion later if we should change default behavior or not.

**Comment by daveaglick** [comment]
:+1: Cool, this is a good addition. Doesn't really make a difference one way or the other, just wanted to be sure I'm following the correct semantics since I've got some fairly long-running processes.

**Comment by devlead** [comment]
@daveaglick personally it will solve many mono issues where tools in sometimes takes 2 tries to work, i.e. nuget restore which is safe to run again :wink:

**Comment by patriksvensson** [comment]
Closed via #831.
