### ISSUE TITLE
Signtool: Add support for certificates from the certificate store based on thumbprint

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#832]

**Comment by thomaslevesque** [comment]
Any idea when this feature will be released? I'm building on a CI server where the certificate is installed in the store; I don't have access to the pfx file. So I'm wondering if it's worth spending time on a workaround, or if I should just wait for the next release :wink:

Thanks!

**Comment by devlead** [comment]
@thomaslevesque soon :tm: :wink: we have some more testing to do, meanwhile you can install Cake prerelease from our MyGet feed.
https://www.myget.org/gallery/cake

**Comment by thomaslevesque** [comment]
Thanks @devlead!
