### ISSUE TITLE
Bootstrapper fails if $env:path has empty strings

### ISSUE THREAD

**Issue by twwilliams** [cake-build/cake#842]
Due to faulty installers, many PATH environment variables end up with consecutive semicolons, which turns into a blank line with `$env:path -split ';'`. While `Test-Path` returns False when given non-empty strings, it throws an error when it encounters the empty string. This causes the build.ps1 script to fail on machines where $env:path has consecutive semicolons.

It happens in the section that checks for nuget.exe on the path.

**Comment by luisgoncalves** [comment]
Just to point out that this was fixed by cake-build/resources#5.

**Comment by gep13** [comment]
@luisgoncalves good catch!
