### ISSUE TITLE
Cannot convert from 'Cake.Common.Tools.MSBuild.MSBuildSettings' to 'Cake.Common.Tools.DotNetBuildSettings'

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#849]
Steps to reproduce:

``` csharp
Task("Default")
    .Does(() => 
{
    new MSBuildSettings()
        .WithProperty("foobar", MakeAbsolute(Directory(".")));

});
```

This will output error message:

```
error CS1929: Instance argument: cannot convert from 'Cake.Common.Tools.MSBuild.MSBuildSettings' to 'Cake.Common.Tools.DotNetBuildSettings'
```

Workaround add **ToString()**

``` csharp
Task("Default")
    .Does(() => 
{
    new MSBuildSettings()
        .WithProperty("foobar", MakeAbsolute(Directory(".")).ToString());

});
```

**Comment by devlead** [comment]
WithPropery takes string/strings as value parameter, you're passing a FilePath to it.
MakeAbsolute(..).FullPath should work too.

Could be some implicit thing that happens when wrong type is supplied.

**Comment by mholo65** [comment]
Yep, for some reason the compiler want's to use the DotNetBuildSettings extension instead.

I though the **MakeAbsolute** alias returned a **ConvertableDirectoryPath/ConvertableFIlePath**, hence the no string conversion. But after checking source, I was wrong :smile:

**Comment by devlead** [comment]
@mholo65 you could try launching cake.exe with the -Experimental flag which will launch a newer version of Roslyn, might be an issue that's sorted, if it's an compiler issue.

**Comment by mholo65** [comment]
@devlead Same error, slightly different error message:
```
error CS1929: 'MSBuildSettings' does not contain a definition for 'WithProperty' and the best 
extension method overload 'DotNetBuildSettingsExtensions.WithProperty(DotNetBuildSettings, 
string, params string[])' requires a receiver of type 'DotNetBuildSettings'
```

I would however call this an compiler issue. It may be solved by moving DotNetBuildSettings (and aliases) to another namespace than **Cake.Common.Tools**

**Comment by mholo65** [comment]
Same issue with **XBuild**. But when switching to **DotNetBuild**, the compiler gives correct error message:
```
error CS1503: Argument 3: cannot convert from 'Cake.Core.IO.DirectoryPath' to 'string'
```

**Comment by patriksvensson** [comment]
@mholo65 Excellent finding this. If you have time, could you check if your theory about moving DotNetBuild to another namespace would solve the problem?

**Comment by mholo65** [comment]
@patriksvensson np. So I tried moving to namespace **Cake.Common.Tools.DotNet** still same issue. Which makes sense in a way, because that namespace is loaded before **Cake.Common.Tools.MSBuild/Cake.Common.Tools.XBuild** in cake-script. If moving to namespace **Cake.Common.Tools.ZotNet** I'll get the correct error for MSBuild
```
error CS1503: Argument 3: cannot convert from 'Cake.Core.IO.DirectoryPath' to 'string'
```

But then again XBuild reports 
```
error CS1929: Instance argument: cannot convert from 'Cake.Common.Tools.XBuild.XBuildSettings' to 'Cake.Common.Tools.MSBuild.MSBuildSettings'
```
Becouse the MSBuild namespace is loaded before XBuild.

Now if I add an extension method ```public static CakeSettings WithProperty(this CakeSettings settings, string name, params string[] values)``` to CakeSettings, I'll get the error message:
```
error CS1929: Instance argument: cannot convert from 'Cake.Common.Tools.MSBuild.MSBuildSettings' to 'Cake.Common.Tools.Cake.CakeSettings'
```

Soo, the bottom line is: We are importing unnecessary namespaces. Might be difficult to fix, would still say that this is an Compiler issue (finding other methods with same name but slightly different signature and trying to implicitly cast.). Root cause is user error (trying to cast **DirectoryPath/FilePath** to **string**), but It would be great to get the correct error message.

 The **MSBuild/XBuild/DotNetBuild** could be easy to fix using inheritance though.

**Comment by daveaglick** [comment]
FYI, just hit this so problem still exists in 0.23.0

**Comment by mholo65** [comment]
I think we was ready to remove `DotNetBuild` aliases soon, that is the ultimate fix :smile:

**Comment by daveaglick** [comment]
That'll do it :smile:

**Comment by mholo65** [comment]
DotNetBuild was obsoletet here https://github.com/cake-build/cake/issues/1796 and will be removed with this issue https://github.com/cake-build/cake/issues/2292
