### ISSUE TITLE
Support environment variables in paths

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#85]
Paths should support environment variables (on Mono and Windows).

Segments surrounded by `%` tokens are not technically valid paths (on Windows), but we're going to make an exception for this. This means that we should no longer throw an exception when creating an illegal path, but mark the path as invalid. The `$` token is valid on *nix systems, so a path like that will still be considered valid.

A path containing environment variables will be considered invalid. Tools and script aliases that work with paths will have to take this into consideration and act accordingly.

**Path**
- `bool Path.ContainsEnvironmentVariables()`
- `bool IsValidPath { get; }`

**FilePath**
- `FilePath ExpandEnvironmentVariables(ICakeEnvironment environment)`

**DirectoryPath**
- `DirectoryPath ExpandEnvironmentVariables(ICakeEnvironment environment)`

**Comment by fleed** [comment]
Any update on supporting string interpolation (`$` sign in front of strings)?

**Comment by devlead** [comment]
@fleed It's already supported if you pass the `-Experimental` flag to Cake or use the CoreCLR version of Cake.

**Comment by devlead** [comment]
@fleed CoreCLR was recently released along the v0.16.0 version, there's been some fixes required and we're today releasing v0.16.2 

Biggest limitation is that addins need to be .NET Core compatible assemblies, tools work usual as long as their dependencies exist on the machine they're executing, but if you're i.e. running in a CoreCLR only environment like Nano Server tools requiring desktop .NET framework won't work.

In the v0.17.0 time frame we'll focus on delivering documentation, examples and guidance around CoreCLR, An really basic example using Cake CoreCLR can be found [here](https://github.com/devlead/BitbucketPipelinesShield)

**Comment by patriksvensson** [comment]
Superseded by #2312
