### ISSUE TITLE
-Mono parameter is not documented in Program.cs output

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#852]
![image](https://cloud.githubusercontent.com/assets/1271146/14912518/c009ef3e-0df4-11e6-824b-7e218b747253.png)

And it should be.

**Comment by patriksvensson** [comment]
Note: this should only be visible on Windows.

**Comment by devlead** [comment]
Well potentially going forward we could try Roslyn on mono 😉

**Comment by patriksvensson** [comment]
Merged in #862.
