### ISSUE TITLE
Hello World Example Generates Warnings

### ISSUE THREAD

**Issue by brock555** [cake-build/cake#864]
### What You Are Seeing?
unknown.cake (1595,43): `Cake.Common.Xml.XmlPokeAliases.XmlPoke(this Cake.Core.ICakeContext, string, string, string)' is obsolete: `Please use XmlPokeString(string, string, string) instead.'
unknown.cake (1602,43): `Cake.Common.Xml.XmlPokeAliases.XmlPoke(this Cake.Core.ICakeContext, string, string, string, Cake.Common.Xml.XmlPokeSettings)' is obsolete: `Please use XmlPokeString(string, string, string, XmlPokeSettings) instead.'
unknown.cake (1725,45): `Cake.Core.Scripting.IScriptHost.Setup(System.Action)' is obsolete: `Please use Setup(Action<ICakeContext>) instead.'
unknown.cake (1726,47): `Cake.Core.Scripting.IScriptHost.Teardown(System.Action)' is obsolete: `Please use Teardown(Action<ICakeContext>) instead.'

### What is Expected?
No warnings

### What version of Cake are you using?
Cake.0.11.0.
### Are you running on a 32 or 64 bit system?
64 bit
### What environment are you running on?  Windows? Linux? Mac?
Mac
### Are you running on a CI Server?  If so, which one?
No

### How Did You Get This To Happen? (Steps to Reproduce)
Followed Hello World Example

### Output Log

https://gist.github.com/brock555/0477e86600222b751d84b5da2312a593

**Comment by gep13** [comment]
Issue was recreated here: https://github.com/cake-build/example/issues/15
