### ISSUE TITLE
Tool path is wrong when calling cake file in sub directory

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#867]
### What You Are Seeing?

When passing a relative path to a script file not relative to the bootstrapper location, the paths to tools get messed up when using the `#tool` directive.

### What is Expected?

The tool path to be relative to the executing script.

### What version of Cake are you using?

0.11.0

### Are you running on a 32 or 64 bit system?

64-bit

### What environment are you running on?  Windows? Linux? Mac?

Windows

### Are you running on a CI Server?  If so, which one?

No

### How Did You Get This To Happen? (Steps to Reproduce)

1) Create the following folder structure:

```
build.ps1
SubFolder
  - build.cake
```

2) Where `build.cake` looks like this:

```csharp
#tool "nuget:?package=XamarinComponent"
```

3) Then you should see that the tool will be downloaded to the wrong location when running the script with a relative path:

```
./build.ps1 -Script "./SubFolder/build.cake"
```

**Comment by gep13** [comment]
@Redth when you have a minute, and are able to, can you pull the latest MyGet build, and verify that the problem that you noted has been resolved?  Thanks!
