### ISSUE TITLE
Add possiblity to launch debugger

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#876]
Once PR #858 is merged, it might be useful to have the possibility to let Cake.exe launch a debugger using **System.Diagnostics.Debugger.Launch()** instead of waiting for debugger to be attached.

Maybe waiting for debugger to be attached could be canceled by user, and then on **#debug** pre-processor directive (as mentioned in issue #869) we could do Debugger.Launch() if debugger isn't attached...

**Comment by gep13** [comment]
@mholo65 is this something that you will be in a position to look at, or would you like one of us to take it?  Thanks!

**Comment by mholo65** [comment]
@gep13 yes, I can look at this. But to make this is as elegant as possible, then at least some bit of Cake.Core (e.g. ICakeEnvironment) needs to know if we are running debug or not. Hence the reference to #902

By doing this we could use same pre-processor directive and the change these [BreakDirectiveProcessor.cs](https://github.com/cake-build/cake/blob/d35a5f697aaf53cf9997058df35dd4d1adb3be83/src/Cake.Core/Scripting/Processors/BreakDirectiveProcessor.cs#L24-32) lines to:
```csharp
replacement = null;

if (!line.Trim().Equals("#break", StringComparison.Ordinal))
{
    return false;
}

if(_environment.IsDebug)
{
    replacement = @"if (System.Diagnostics.Debugger.IsAttached) { System.Diagnostics.Debugger.Break(); } else { System.Diagnostics.Debugger.Launch(); }";
}

return true;
```

Result will be that ```#break``` directive will be commented out if ```--debug``` flag was not supplied to Cake.exe, otherwise debugger will break or launch depending on if it's attached or not.

What's your opinion on this?

**Comment by gep13** [comment]
@mholo65 I agree, I think we need that before attempting this.  @patriksvensson were you planning on attempting #502 in the 0.13.0 release, or should we bump this particular issue onto the next milestone?

**Comment by patriksvensson** [comment]
@mholo65 What would the non-elegant solution look like until we've fixed the environment refactoring?

**Comment by mholo65** [comment]
@patriksvensson well, it's probably by adding a new directive ```#debug-launch```, or similar

All other solutions would require refactoring of the Autofac module registrations, we have an chicken-egg problem because Core module is loaded first, and then arguments are parsed. A **not-so-elegant** solution would be to just check arguments for ```--debug|-debug|-d``` prior to creating the Core module (somewhere about [here](https://github.com/cake-build/cake/blob/e6095bd0dec860c023d776d0fa0afd99f2610ce5/src/Cake/Program.cs#L32))

**Comment by patriksvensson** [comment]
@mholo65 I have a submitted PR that should solve that. Did some refactoring gor the module support. However, checking if --debug is present should be ok for now. We can always refactor later.

**Comment by mholo65** [comment]
@patriksvensson @gep13 ok, then I'll try to get something done... What's the schedule for v0.13.0?

**Comment by gep13** [comment]
@mholo65 we are hoping to get something out before Thursday, which is when I am doing a talk at NDC.  If that is unrealistic, please don't feel any pressure to try to get this done.

**Comment by patriksvensson** [comment]
Maybe we can move this to v0.14.0 so there's no stress.

**Comment by mholo65** [comment]
yep, move to v0.14.0, even if I start working on it today, Thursday is a bit unrealistic when taking review + testing into account.

**Comment by gep13** [comment]
@mholo65 done. Thanks again for helping out!

**Comment by gep13** [comment]
@mholo65 given the work that @patriksvensson has been doing on getting the CoreClr port of Cake to where it is, I am going to defer this work until after that is released.  Hope that makes sense.

**Comment by mholo65** [comment]
Not needed.
