### ISSUE TITLE
New Setup(Action<ICakeContext>)  fails on mono

### ISSUE THREAD

**Issue by devlead** [cake-build/cake#883]
### What You Are Seeing?
New Setup(Action<ICakeContext>) gives an `Delegate `System.Action' does not take `1' arguments` error on mono
### What is Expected?
For it to not give an error
### What version of Cake are you using?
0.11.0
### Are you running on a 32 or 64 bit system?
64 bit
### What environment are you running on?  Windows? Linux? Mac?
Fails on both Windows & Linux

### Are you running on a CI Server?  If so, which one?
Travis 
https://travis-ci.org/cake-build/cake/jobs/129951741

### Output Log
```
build.cake (21,7): Delegate `System.Action' does not take `1' arguments
Error: An error occured while executing build script.
```

**Comment by patriksvensson** [comment]
Funny, but don't get this when defining a Setup(Action<ICakeContext>). Although, it looks like it warns about obsoleted method although they aren't used in the build script!

```
PS> .\build.ps1
Bootstrapping Cake...
Running build script 'build.cake'...
Analyzing build script...
Processing build script...
Installing tools...
Installing addins...
Compiling build script...
unknown.cake (1595,43): `Cake.Common.Xml.XmlPokeAliases.XmlPoke(this Cake.Core.ICakeContext, string, string, string)' is obsolete: `Please use XmlPokeString(string, string, string) instead.'
unknown.cake (1602,43): `Cake.Common.Xml.XmlPokeAliases.XmlPoke(this Cake.Core.ICakeContext, string, string, string, Cake.Common.Xml.XmlPokeSettings)' is obsolete: `Please use XmlPokeString(string, string, string, XmlPokeSettings) instead.'
unknown.cake (1773,45): `Cake.Core.Scripting.IScriptHost.Setup(System.Action)' is obsolete: `Please use Setup(Action<ICakeContext>) instead.'
unknown.cake (1774,47): `Cake.Core.Scripting.IScriptHost.Teardown(System.Action)' is obsolete: `Please use Teardown(Action<ICakeContext>) instead.'
```

**Comment by devlead** [comment]
@cake-build/team found the issue will submit an PR shortly.
