### ISSUE TITLE
SemanticVersion

### ISSUE THREAD

**Issue by waynebrantley** [cake-build/cake#885]
For batteries built in, it would be good to have a semantic version processor.
Fake has a SemVerInfo class.
For now, I have loaded the nuget.core package and use their implementation.
https://github.com/NuGet/NuGet2/blob/2.12/src/Core/SemanticVersion.cs

**Comment by gep13** [comment]
@waynebrantley I "think" I am right in saying that @redth has you covered here with his addin: https://www.nuget.org/packages/Cake.SemVer/  I am going to go ahead and close this issue, but if you feel more work is required, then please re-open.

**Comment by Redth** [comment]
Nice catch ;) just published this yesterday as I needed it too. 

If you feel like anything is missing from it feel free to open an issue on the GitHub repo for it!
