### ISSUE TITLE
Extending the Sign command  

### ISSUE THREAD

**Issue by krippz** [cake-build/cake#887]
Need to sign our files but we have our certs installed on the build machines, not possible to extract to files. 

I suggest that the Sign command could be extended to do `signtool sign /n "SomeCertInMyCertStore" somefile.dll` and possibly to create the `signtool verify` command

I would be happy to help in doing this.

**Comment by devlead** [comment]
@krippz cool feel free to add such a PR :+1: , meanwhile #813 added sign by thumbprint from the certificate store via the `SignToolSignSettings` `CertThumbprint` property. Which could solve the immediate issue for you.

**Comment by krippz** [comment]
Great! I'll try to put something together asap, I'll look at #813 :) thanks

**Comment by thomaslevesque** [comment]
@krippz you can also use the `CertThumbprint` property to specify the certificate thumbprint rather than the name.

**Comment by thomaslevesque** [comment]
Seeing my previous comment again, I realize using `CertThumbprint` won't work for you if you don't have the certificate on your dev machine.

Anyway, I made a PR (#1325) to add support for using the certificate subject name.

**Comment by devlead** [comment]
Fixed by #1325
