### ISSUE TITLE
Add support for the vstest.console.exe unit test runner

### ISSUE THREAD

**Issue by pvwichen** [cake-build/cake#894]
### What You Are Seeing?
Visual Studio 2012 and newer includes a newer unit test runner that is used for unit and coded UI tests. For more information, refer to: https://msdn.microsoft.com/en-us/library/jj155800.aspx

Also supports the ability to execute unit tests in a 64-bit assembly.

### What is Expected?
The ability to execute unit and coded UI tests using the vstest.console.exe runner.
Example: `VSTest("src/**bin/Release/*.Test.dll", new VSTestSettings { Logger = VsTestLogger.Trx });`

### What version of Cake are you using?
`Version 0.11.0`

### Are you running on a 32 or 64 bit system?
64-bit system.

### What environment are you running on?  Windows? Linux? Mac?
Windows and Linux, although this runner would only apply to Windows currently.

### Are you running on a CI Server?  If so, which one?
Jenkins, Teamcity

**Comment by devlead** [comment]
fixed by #890
