### ISSUE TITLE
Add DevelopmentDependency to NuGetPackSettings

### ISSUE THREAD

**Issue by daveaglick** [cake-build/cake#897]
Related to #895, add a flag for `DevelopmentDependency` to `NuGetPackSettings` and use it when creating the temporary .nuspec for the pack alias. I'll submit a PR for this shortly, but figured I should create a separate issue to track it.

**Comment by gep13** [comment]
@daveaglick perfect! Thank you :smile:

**Comment by gep13** [comment]
@daveaglick I have assigned this issue to you.
