### ISSUE TITLE
CopyFiles doesn't respect source directory structure

### ISSUE THREAD

**Issue by thomaslevesque** [cake-build/cake#899]
### What You Are Seeing?

If I have a directory structure like this:

    root
    -- subdir1
    ---- bar.dll
    -- subdir2
    ---- baz.dll
    -- foo.exe

When I execute this:

    CopyFiles("root/**/*", outputDir);

The files are copied to a flat directory structure, instead of preserving the original structure:

    outputDir
    -- foo.exe
    -- bar.dll
    -- baz.dll

### What is Expected?

The same structure as in the source folder

    outputDir
    -- subdir1
    ---- bar.dll
    -- subdir2
    ---- baz.dll
    -- foo.exe

### What version of Cake are you using?

0.11

### Are you running on a 32 or 64 bit system?

64 bit

### What environment are you running on?  Windows? Linux? Mac?

Windows 8.1

### Are you running on a CI Server?  If so, which one?

Not at this point, just testing locally (but eventually it will run on Jenkins)

### How Did You Get This To Happen? (Steps to Reproduce)

As described above

### Output Log
    ...
    ========================================
    PublishArtifacts
    ========================================
    Executing task: PublishArtifacts
    Copying file foo.exe to D:/path/to/outputDir/foo.exe
    Copying file bar.dll to D:/path/to/outputDir/foo.exe
    Copying file baz.dll to D:/path/to/outputDir/foo.exe
    Finished executing task: PublishArtifacts
    ...

I realize this may be the intended behavior, but I don't think it makes much sense... especially since there doesn't seem to be an easy way to manually list and copy the files.

**Comment by devlead** [comment]
@thomaslevesque Hi, this is by design, but we have discussed it before so think we should add an overload with something like _bool preserveFolderStructure_ or similar.

**Comment by thomaslevesque** [comment]
> think we should add an overload with something like _bool preserveFolderStructure_ or similar.

That would be awesome!

In the meantime, I'll find a workaround

**Comment by devlead** [comment]
Superb, if it's a good workaround you should submit a 😉 
You could probably use same globber with [GetFiles](http://cakebuild.net/api/cake.common.io/b6f866f7/796bd28f) and the upcoming [EnsureDirectoryExists](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/IO/DirectoryAliases.cs#L301) validating relatively that each files parent exist.

**Comment by thomaslevesque** [comment]
Here's my (ugly) workaround:

```
    void CopyFilesPreservingStructure(string pattern, DirectoryPath destinationDir)
    {
        int firstWildcardIndex = pattern.IndexOf('*');
        var patternRootRelativePath = firstWildcardIndex < 0
          ? System.IO.Path.GetDirectoryName(pattern)
          : pattern.Substring(0, firstWildcardIndex);
        
        var patternRoot = MakeAbsolute(Directory(patternRootRelativePath));
  
        var files = GetFiles(pattern);
        foreach (var file in files)
        {
          var relativeFile = patternRoot.GetRelativePath(file);
          var destinationFile = destinationDir.CombineWithFilePath(relativeFile);
          var parent = destinationFile.GetDirectory();
          if (!DirectoryExists(parent))
            CreateDirectory(parent);
          CopyFile(file, destinationFile);
        }
    }
```

**Comment by danielfrancora** [comment]
Hello thomaslevesque.
I'm working with the same issue as you. How did you invoke this function you created? I'm trying to use it but with no luck.
Thx for the help.

**Comment by thomaslevesque** [comment]
> How did you invoke this function you created?

Something like this:

    CopyFilesPreservingStructure($"src/MyProject/bin/{configuration}/**/*.exe", "artifacts");

**Comment by robgha01** [comment]
I tested this workaround method with the following but it wont work same output as CopyFiles(pattern

```
var root = "../";
var projectRoot =  MakeAbsolute(Directory(root));
var projectName =  Argument("projectName", ((DirectoryPath)(MakeAbsolute(Directory(root)).FullPath)).GetDirectoryName());
var buildDir = projectRoot + Directory($"/{projectName}");
var files = new [] {
        $"{buildDir}/bin/*.dll",
        $"{buildDir}/DataServices/*.svc",
        $"{buildDir}/scripts/**",
        $"{buildDir}/*.config",
        $"{buildDir}/*.aspx",
        $"{buildDir}/*.ico",
        $"{buildDir}/*.html"
    };
	
    foreach(var pattern in files) {
        CopyFilesPreservingStructure(pattern, targetOutput);
    }
```

**Comment by thomaslevesque** [comment]
@robgha01, it's just a quick and dirty workaround, I haven't tested it thoroughly... it works well enough for my needs, but I can't guarantee anything beyond that.

**Comment by RyannosaurusRex** [comment]
I could totally be missing something here, but is what you want actually CopyDirectory instead of Copy files?  I ran into a similar thing where I tried to use CopyFiles to copy a directory and ended up using CopyDirectory, which worked for me.

**Comment by thomaslevesque** [comment]
> I could totally be missing something here, but is what you want actually CopyDirectory instead of Copy files? I ran into a similar thing where I tried to use CopyFiles to copy a directory and ended up using CopyDirectory, which worked for me.

From what I can see in the documentation, it's absolutely possible that I should be using `CopyDirectory`... I'll give it a try, thanks.

**Comment by thomaslevesque** [comment]
Actually... maybe not. I use globbing to specify which files to copy, and `CopyDirectory` just copies all files.

**Comment by RyannosaurusRex** [comment]
Good point.  I didn't need any pattern matching in mine.  An overload in this case to preserve directory structure would definitely help.

**Comment by maddin2016** [comment]
Hi there, i want to ask if this issue is still present. I have created some overloads where you  can select to keep the folder structure for `CopyFiles`. Should i create a pull request to show?
