### ISSUE TITLE
Wrong platform "Any CPU" for project file (expects "AnyCPU")

### ISSUE THREAD

**Issue by thomaslevesque** [cake-build/cake#900]
### What You Are Seeing?

If I use the `MSBuild` method to build a .csproj (rather than a solution) with `PlatformTarget = PlatformTarget.MSIL`, the wrong value is passed for the `Platform` property: for a solution, the correct value is `"Any CPU"`, but for a project it's `"AnyCPU"` (no space). See [this article](http://kynosarges.org/WeirdDotNet.html#AnyCPU) for the explanation.

### What is Expected?

When the file to build is a project rather than a solution, Cake should pass "AnyCPU" as the platform.

### What version of Cake are you using?

0.11

### Are you running on a 32 or 64 bit system?

64 bit

### What environment are you running on?  Windows? Linux? Mac?

Windows 8.1

### Are you running on a CI Server?  If so, which one?

Not right now

### How Did You Get This To Happen? (Steps to Reproduce)

By building a .csproj with `PlatformTarget = PlatformTarget.MSIL`

### Output Log

> "D:\path\to\the\project\MyProject.csproj" (build target) (1) ->
> (_CheckForInvalidConfigurationAndPlatform target) ->
>   C:\Program Files (x86)\MSBuild\14.0\bin\Microsoft.Common.CurrentVersion.targets(723,5): error : The OutputPath property is not set for project 'MyProject.csproj'.  Please check to make sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Release'  Platform='Any CPU'.  You may be seeing this message because you are trying to build a project without a solution file, and have specified a non-default Configuration or Platform that doesn't exist for this project. [D:\path\to\the\project\MyProject.csproj]

**Comment by thomaslevesque** [comment]
Looking at the code, it seems to be a documentation issue rather than a bug... `GlobbingAliases.GetFiles` accepts a `Func<IFileSystemInfo, bool>` and passes it to `IGlobber.Match`, but `IGlobber.Match` actually accepts a `Func<IDirectory, bool>`. Because of contravariance, a `Func<IFileSystemInfo, bool>` is a valid `Func<IDirectory, bool>`, but the signature of `GetFiles` seems to imply that the predicate will receive either files or directories, when it will actually receive only directories.

Looking at the doc, my understanding was that the predicate was a filter applied to the items found during the scan; but actually it's a filter on which directories will be scanned. The doc should be updated to make that clear.

(for my use case, what I really needed was Linq's `Where` method, but when I saw an overload of `GetFiles` with a predicate, I tried to use it instead)

**Comment by patriksvensson** [comment]
@thomaslevesque Sorry for not getting back to you sooner about this. Everything looks fine at first glance. Sorry again. Will take a look at this tomorrow.

**Comment by thomaslevesque** [comment]
No problem @patriksvensson, there's no rush ;)

**Comment by thomaslevesque** [comment]
I realize now that a better way to fix it would be to add a `Project` property to `MSBuildSettings`, rather than relying on the extension to determine if it's a solution or project. If you prefer this approach, I'll update my PR.

**Comment by patriksvensson** [comment]
@thomaslevesque I think the current implementation is good :smile: Not at a computer now but will take a look at it tonight.
