### ISSUE TITLE
Add IsDebug to ICakeEnvironment

### ISSUE THREAD

**Issue by mholo65** [cake-build/cake#902]
Add runtime info to ICakeEnvironment to know if performing debug.

**Comment by mholo65** [comment]
Discussed here #869 with @patriksvensson

**Comment by mholo65** [comment]
Needed by #876 if we would like to use same directive for launch and break..

**Comment by gep13** [comment]
Related to https://github.com/cake-build/cake/issues/502

**Comment by gep13** [comment]
@mholo65 given the work that @patriksvensson has been doing on getting the CoreClr port of Cake to where it is, I am going to defer this work until after that is released.  Hope that makes sense.

**Comment by mholo65** [comment]
@gep13 np, looking forward to CoreCLR support

**Comment by mholo65** [comment]
Not needed
