### ISSUE TITLE
Extend SolutionParserResult with solution folders information

### ISSUE THREAD

**Issue by endrton** [cake-build/cake#919]
### What You Are Seeing?
SolutionParser doesn't parse solution folders.

### What is Expected?
SolutionParserResult should contain information about solution folders and the projects they contain.
It would be better if somehow the relationship between solution folders and projects is visible. So it should be more than just another collection property containing a list of solution folders.
Any suggestion?

### What version of Cake are you using?
0.11.0

### Are you running on a 32 or 64 bit system?
64 bit

### What environment are you running on?  Windows? Linux? Mac?
Windows

### Are you running on a CI Server?  If so, which one?
Not yet.

**Comment by endrton** [comment]
I have taken a look into the affected code.
**Current**
`SolutionParserResult `contains a readonly collection of `SolutionProject` (line 42 - [link](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Solution/SolutionParserResult.cs)) and `SolutionParser` explicitly ignores projects with `SolutionFolder` type (line 76 - [link](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Solution/SolutionParser.cs)).

**Suggestion**
A new class would be introduced (`SolutionFolder`) and it would be inherited from `SolutionProject` as it's actually is and would have a collection of `SolutionProject` as child items. `SolutionProject` would be extended with a Parent property pointing to the `SolutionFolder` if any.
`SolutionParserResult` would contain instances of both `SolutionProject` and `SolutionFolder`, either in one collection or separately.

**Comment by devlead** [comment]
@endrton could bea nice addition 👍, if you have the opportunity to do a pr, please do and we can continue discussion there.

**Comment by gep13** [comment]
This issue is being worked on by @endrton

**Comment by gep13** [comment]
@endrton thanks again!
