### ISSUE TITLE
Add Summary Documentation for all aliases

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#927]
Similar to what is seen here:

https://github.com/cake-build/cake/blob/dfae6c92ac372655cd3af63e0cc0d0806e8ee94b/src/Cake.Common/Tools/ILRepack/ILRepackAliases.cs#L9

**Comment by patriksvensson** [comment]
@gep13 @devlead Should this issue be closed?

**Comment by gep13** [comment]
Yes, sorry, I thought this had been closed.
