### ISSUE TITLE
Git support

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#95]

**Comment by gep13** [comment]
@devlead have you published your Cake.Git addin?  If so, should this issue be closed?

**Comment by devlead** [comment]
Not published yet, will in January.

**Comment by gep13** [comment]
@devlead and is there enough in Cake.Git to close out this issue?

**Comment by mholo65** [comment]
I'm also in need of a generic Git tool.

@devlead, noticed your addin didn't have **git-branch** command, any plans on adding this?

**Comment by gep13** [comment]
The Cake.Git addin is now alive and kicking: https://www.nuget.org/packages/Cake.Git/ so I think this issue can be closed.
