### ISSUE TITLE
Add configuration for default NuGet source

### ISSUE THREAD

**Issue by wwwlicious** [cake-build/cake#960]
When using the #tool preprocessor directive in cake scripts, it is possible to use an absolute uri to specify a specific nuget source. 

It is not possible to override the nuget system default, as can be done for the ROSLYN_NUGET key using the `cake.config` file for the bootstrapper.

Allowing the default nuget sources for tooling and addins to be specified is useful for those without access to public nuget servers but with access to internal private nuget sources

I am proposing that a config key called `NUGET_SOURCE` be checked for a value in the `cake.config` file when installing packages via the `NuGetPackageInstaller`

example of config
```
[NuGet]
Source=http://myfeed/nuget/
```

If no absolute uri is specified. The value of this key will be a semi-colon separated list of nuget package sources.

This still will allow specific overrides per directive but a custom source/s can be specified for a project.

**Comment by patriksvensson** [comment]
@wwwlicious Perfect! Thanks!
