### ISSUE TITLE
DotNetCore test alias can not pass specifics parameters to the test runner

### ISSUE THREAD

**Issue by phenixdotnet** [cake-build/cake#963]
Actually the DotNetCore test aliase doesn't allow user to pass specific parameters to the test runner like ```-xml resultsfile.xml``` for xunit

The PR https://github.com/cake-build/cake/pull/962 fix that.

**Comment by phenixdotnet** [comment]
Just found the ArgumentCustomization, shame on me RTFM ^^'

**Comment by gep13** [comment]
@phenixdotnet ha ha, I was just typing a response to that effect :smile:
