### ISSUE TITLE
Cake should have a -v and --version argument

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#973]
Which would then output the current version number.

Similar to what you can get from:

`npm -v`
`node --version`

**Comment by gep13** [comment]
In our case though, I think -v is reserved for verbosity.

**Comment by gep13** [comment]
scratch that, it is already there :smile:

**Comment by devlead** [comment]
@gep13 and it's awesome😎

**Comment by gep13** [comment]
Yes it is....

![image](https://cloud.githubusercontent.com/assets/1271146/15908713/f35051c2-2dba-11e6-97f3-080459d33609.png)
