### ISSUE TITLE
Add custom attribute for obsoleted aliases

### ISSUE THREAD

**Issue by patriksvensson** [cake-build/cake#974]
Mono seems to care about obsoleted aliases even though they only exist in generated code and isn't explicitly called. We could work around this by creating a custom attribute for aliases like `CakeObsoletedAliasAttribute`.

![image](https://cloud.githubusercontent.com/assets/357872/15913639/8197811a-2ddb-11e6-9e33-e7f1b9822731.png)

**Comment by devlead** [comment]
Could also be that we should ignore on the generated classes.

Also on that note, we should probably now remove the obsolete XmlPoke methods.

**Comment by patriksvensson** [comment]
@devlead We call the obsoleted methods in the generated aliases. I think that is the problem.
Yes, we should remove the XmlPoke methods.

We should also invest in a way of tracking stuff that we obsolete. Like when we obsoleted it (what version).

**Comment by devlead** [comment]
a warning version and error version options to attribute perhaps.

**Comment by patriksvensson** [comment]
@devlead Not a bad idea. Let me think some more about this.
