### ISSUE TITLE
Fix broken Publish-GitHub-Release Task

### ISSUE THREAD

**Issue by gep13** [cake-build/cake#988]
Both both the 0.12.0 and 0.13.0 release of Cake, we were met with an error similar to this:

https://ci.appveyor.com/project/cakebuild/cake/build/0.12.0.build.2049#L506

When trying to Publish the GitHub Release.  Initially, I thought this was an error with GitReleaseManager, but I have just ran the following test:

![image](https://cloud.githubusercontent.com/assets/1271146/16078540/7024c39a-32f7-11e6-87fd-76818b804727.png)

And as you can see here, the asset got added correctly:

https://github.com/gep13/FakeRepository/releases/tag/untagged-694b79655a063bd1e6f7

So, if we get this https://github.com/cake-build/cake/issues/923 working, we can try to figure out what is going on.  Looks like there is an issue in one of the parameters that are being passed in, but I can't replicate it on my test repository.

**Comment by patriksvensson** [comment]
@gep13 Should be possible now when we can set the verbosity of the logger from the script.

**Comment by gep13** [comment]
In an update to this, it also failed for the 0.14.0 release:

https://ci.appveyor.com/project/cakebuild/cake/build/0.14.0.build.2320#L575

This time, with the aid of the additional logging, I have come to the conclusion that the problem is the password that is being passed into the command line.  I think it must contain a `"` or similar, that is breaking the input to GitReleaseManager.  Going to change this password for the next release, and assume that everything is going to work :smile:   Will re-open if required.

**Comment by gep13** [comment]
Tested this locally using an newly generated personal access token, and it seems to work :+1:
