### ISSUE TITLE
GetDirectoryName not parsing location for name like "../"

### ISSUE THREAD

**Issue by robgha01** [cake-build/cake#992]
Hi

Its my second day with this Cake build system and im finding it a nice project moved from phantom but now to the issue.

**The Issue:**
If one do this
```
var root = "../";
var projectName =  ((DirectoryPath)Directory(root)).GetDirectoryName();
```

the return value is  "../" when it should have ben the folder name to get around this i have to call it like this:
`((DirectoryPath)(MakeAbsolute(Directory(root)).FullPath)).GetDirectoryName();`

as you can see it becomes uggly pritty fast xD i looked in the source for GetDirectoryName and it seams to not parse the url to get the full path wich seams strange ?

**Comment by patriksvensson** [comment]
@robgha01: Try the following:

```csharp
var root = "../";
var projectName = MakeAbsolute(Directory(root)).Path.GetDirectoryName();
```

I'm assuming you're talking about https://github.com/cake-build/cake/blob/develop/src/Cake.Core/IO/DirectoryPath.cs#L35 ?
I'm not sure what you mean with `not parse the url to get the full path` though. Could you explain some more?

**Comment by robgha01** [comment]
Hi @patriksvensson 

Yes im talking about this method "http://cakebuild.net/api/cake.core.io/38f83116/7a424795" what that metod says is "Gets the name of the directory." however if i made a directory with "../" as a path that method would return "../" and not the actuall name of the parent directory.

however if i call it like this
`((DirectoryPath)(MakeAbsolute(Directory(root)).FullPath)).GetDirectoryName();`
the "MakeAbsolute" method returns the full path and the GetDirectoryName would return the correct name but im asumming the method GetDirectoryName should get the directory name and not GetPathLastSegment() if the method was called like that i would understand that it cant parse the name witout MakeAbsolute. What i suggest is to parse the expression or any expression "../" and return the directory name after that what it dose now is return the last segment ignoring any path expressions to evaluate.

**Comment by patriksvensson** [comment]
@robgha01 Yes. That is correct behavior. The `DirectoryPath` and `FilePath` has no real knowledge of the underlying file system and just works with paths. This is by design. We could however add checks here that would throw if the parent path is unresolvable from the current information.

**Comment by robgha01** [comment]
@patriksvensson Ok, then maybe change the discription to "Get the name of the directory" to someting or add a note somewere its hard for new comers as i read it and converted that text to the above workflow. :)

**Comment by devlead** [comment]
@robgha01 @patriksvensson some action planned here or can this issue be closed?

**Comment by patriksvensson** [comment]
@devlead This can be closed since the behavior won't be changed.
