### ISSUE TITLE
Team Services extension for cake cant find nuget.exe

### ISSUE THREAD

**Issue by robgha01** [cake-build/cake#993]
Hi

i get this in a team service build i just created for the first time with "https://marketplace.visualstudio.com/items?itemName=cake-build.cake"

but it throws this error

> ******************************************************************************
Starting task: Cake
******************************************************************************
Executing the powershell script: C:\LR\MMS\Services\Mms\TaskAgentProvisioner\Tools\agents\1.101.1\tasks\Cake\0.1.6\Cake.ps1
Creating tools directory...
Installing Cake...
Installing 'Cake 0.13.0'.
Successfully installed 'Cake 0.13.0'.
C:\a\1\s\tools\Cake\Cake.exe "C:\a\1\s\Build\build.module.cake" -target="Build-Nuget" -verbosity="Diagnostic" -targetOutput="C:\a\1\a"
Module directory does not exist.
Analyzing build script...
Analyzing C:/a/1/s/Build/build.module.cake...
Processing build script...
Installing tools...
Creating directory C:/a/1/s/Build/tools
Installing NuGet package NUnit.ConsoleRunner...
**Error: Cake.Core.CakeException: Could not locate nuget.exe.
at Cake.Core.IO.NuGet.NuGetToolResolver.ResolvePath()
at Cake.NuGet.NuGetPackageInstaller.GetNuGetPath()
at Cake.NuGet.NuGetPackageInstaller.Install(PackageReference package, PackageType type, DirectoryPath path)
at Cake.Core.Scripting.ScriptProcessor.InstallTools(ScriptAnalyzerResult analyzerResult, DirectoryPath installPath)
at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
at Cake.Commands.BuildCommand.Execute(CakeOptions options)
at Cake.CakeApplication.Run(CakeOptions options)
at Cake.Program.Main()
System.Exception: Unexpected exit code 1 returned from tool Cake.exe
at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeToolCmdlet.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()**
******************************************************************************
Finishing task: Cake
******************************************************************************

**Comment by robgha01** [comment]
Ok, i found way it dide not work with the cake extension for team services... its not installing nuget if its not found in the tools folder but it do download and install cake.exe this must be a bugg... i managed to patch it with the following powershell that i run before the extension `New-Item -ItemType Directory -Force -Path "./Build/tools/";
Invoke-WebRequest https://dist.nuget.org/win-x86-commandline/latest/nuget.exe -OutFile "./Build/tools/nuget.exe"`

**Comment by gep13** [comment]
Issue moved to [cake-build/cake-vso #5](https://github.com/cake-build/cake-vso/issues/5) via [**ZenHub**](https://www.zenhub.com/)

**Comment by gep13** [comment]
@robgha01 as you will see, I have moved this issue over to the VSTS Extension repository, we can continue the discussion there. Thanks.
