### ISSUE TITLE
Add OutputPath to ProjectParserResult

### ISSUE THREAD

**Issue by wwwlicious** [cake-build/cake#997]
There currently isn't a good method to get a project output assembly from any of the build aliases.

An alternative is to return the outputPath from the project file using the `ProjectParser`. 

Using this information together with the following it is possible to determine the output file generated by the project compilation.

ProjPath / OutputPath / AssemblyName [.] Type[Library|Exe]

**Comment by gep13** [comment]
Thanks again for your contribution to Cake!

**Comment by wwwlicious** [comment]
Thanks for merging, just haven't had the time recently to get this done!

**Comment by gep13** [comment]
@wwwlicious not a problem at all, so did all the hard work :-)
