### ISSUE TITLE
Create a mechanism to inject loggers

### ISSUE THREAD

**Issue by kschaab** [cake-build/cake#999]
I want to inject a logger (that will log to file)  There are several other issues which could by the ability to inject a logger.

**Comment by kschaab** [comment]
Removing previous comments, found a backwards compatible solution.

**Comment by gep13** [comment]
@kschaab can you provide some information about what you have done, or are doing?

As part of the 0.13.0 release we included Module support: https://github.com/cake-build/cake/issues/646  We haven't fully documented this yet, but it is a way to replace the core components of Cake with your own implementation.  Take a look at the example in the PR associated with the above linked issue.   Does this fit your need?

**Comment by kschaab** [comment]
I think I can use this, I hooked into the module loader in Cake to present a logger that will allow scripted adds of loggers (so it will log to file and to the default CakeBuildLog for example).  I was missing the module resolve beyond the hardcoded resolve in the Cake libraries themselves.  Thanks for the information.

**Comment by gep13** [comment]
@kschaab not a problem at all. Let us know if you run into any issues.  Like I said, we haven't documented this feature yet, as we wanted to test it out internally first after it was released.  And then the documentation will come from our investigations.
